### ISSUE TITLE
Baking AWS AMIs needs env var SPINNAKER_AWS_DEFAULT_ACCOUNT set

### ISSUE THREAD

**Issue by lflux** [spinnaker/spinnaker#1001]
Baking an AMI for AWS with the Packer amazon-ebs provider (suspected but untested with amazon-chroot as well) with Rosco 0.51.0-3 fails unless the enviroment variable `SPINNAKER_AWS_DEFAULT_ACCOUNT` is set. If this is not set, the AMI build will fail with the following log message:

```
==> amazon-ebs: Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value " " for userId item type.
==> amazon-ebs: 	status code: 400, request id: []
```

This seems to be introduced in [rosco commit b414c73](https://github.com/spinnaker/rosco/commit/b414c73bd4a5bc63318f3cb37a20c8d79b689843)

# Steps to reproduce
## Setup and verification of released AMI
* Deploy Spinnaker in us-west-2 from `Spinnaker-Ubuntu-14.04-42 - ami-cfb87eaf`
* Create a pipeline with a Bake step, installing package `redis-server` on base image`trusty (v14.04)` 
* Start manual execution. Image builds correctly.

## Upgrade Spinnaker
* Run `apt-get update` and `apt-get upgrade` to update to latest spinnaker packages.
* Restart all spinnaker services

Package versions I'm using are:
```
spinnaker                        0.50.0-3
spinnaker-clouddriver            1.235.0
spinnaker-deck                   2.705.0-3
spinnaker-echo                   1.108.0-3
spinnaker-front50                1.30.0-3
spinnaker-gate                   2.67.0-3
spinnaker-igor                   1.50.0-3
spinnaker-orca                   1.168.0-3
spinnaker-rosco                  0.51.0-3
```

## Retrigger pipeline
* Start manual execution.
* Packer build fails with error:
```
Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value " " for userId item type
```

Packer build log is attached: [rosco_packer_output.txt](https://github.com/spinnaker/spinnaker/files/372651/rosco_packer_output.txt)

# Remediation
* Set `SPINNAKER_AWS_DEFAULT_ACCOUNT` to the account ID of the AWS account the Spinnaker instance is launched in (available with `aws iam get-user | grep arn:aws | cut -d':' -f6`). To improve new user experience this should probably be documented and also set in [spinnaker/packer/init.aws.region](https://github.com/spinnaker/spinnaker/blob/master/packer/init.aws.region) in the same fashion as `AWS_VPC_ID` and `AWS_SUBNET_ID`

Longer term there should be a better way to specify account IDs and regions for AMI bake when launching in a multiple account/region environment, since the current template uses the same ID for all regions and accounts.

**Comment by duftler** [comment]
Thanks for providing such a detailed bug report.
I've been able to reproduce.

**Comment by bailejl** [comment]
I ran into this bug today and fixed by putting the variable in /etc/default/spinnaker.  I am not sure this is the best place, but I wanted to test the suggestion.  It worked as advertised and got me pass the bug.

**Comment by sdarwin** [comment]
I just got this error again yesterday from the prebuilt AMI, the solution was exactly as mentioned above. Add:
SPINNAKER_AWS_DEFAULT_ACCOUNT=123456789  (replace with your account ID all numerals)
into file
/etc/default/spinnaker

sudo restart spinnaker

**Comment by chapitos** [comment]
Run into the same problem. The same fix (SPINNAKER)_AWS_DEFAULT_ACCOUNT variable) worked for me too.
