### ISSUE TITLE
Openstack UI to support UDP and ICMP security group rules

### ISSUE THREAD

**Issue by ashleykasim** [spinnaker/spinnaker#1006]

**Comment by varikin** [comment]
UDP & TCP use fromPort and toPort (-1 through 65535)
ICMP use icmpType and icmpCode (-1 through 255)
-1 means all, it really should be -1 for both to/from or type/code.
All types can either provide a cidr or a remoteSecurityGroupId

For ICMP rules, the actual openstack API uses fromPort for type and toPort for code which is not obvious.


curl -X POST -H "Content-Type: application/json" -d '[{ "upsertSecurityGroup": { 
    "region": "west",
    "name": "sg-test-1",
    "description": "test",
    "account": "test",
    "rules": [ { 
      "ruleType": "TCP",
      "fromPort": 80,
      "toPort": 80,
      "cidr": "0.0.0.0/0"  
    }, {
      "ruleType": "UDP",
      "fromPort": -1, 
      "toPort": -1,
      "remoteSecurityGroupId": "e56fa7eb-550d-42d4-8d3f-f658fbacd496"
    }, {
      "ruleType": "ICMP",
      "icmpType": 8,
      "icmpCode": 0,
      "remoteSecurityGroupId": "e56fa7eb-550d-42d4-8d3f-f658fbacd496"
    }
  ]
}}]' localhost:7002/openstack/ops

**Comment by gadresushrut** [comment]
PR : https://github.com/spinnaker/deck/pull/2580
