### ISSUE TITLE
Add network info in load balancer info for openstack provider

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1016]
Network information is missing from the load balancer detail object (e.g. returned from /applications/<app name>/loadBalancers) for the OpenStack provider. Please add it so that we can show the information in the detail and edit portions of the UI.

**Comment by drmaas** [comment]
attributes will be as follows:
```
...
        "networkId": "08c2990a-b630-491c-9d1b-5534e25bc118", 
        "networkName": "my-ext-net", 
...
        "subnetId": "93df79bc-79ac-4cba-97d5-ac22393eb65c", 
        "subnetName": "my-subnet", 
...

```

**Comment by drmaas** [comment]
Will do a PR once #1017 is completed.
