### ISSUE TITLE
Front50's health check fails if Redis is not running locally

### ISSUE THREAD

**Issue by gkuchta** [spinnaker/spinnaker#1018]
### Issue

Front50's health check fails if Redis is not installed/running locally. It appears that this is due to springboot's `org.springframework.boot.actuate.health.RedisHealthIndicator` bubbling up to the surface.
### Expected behavior

With `"spinnaker.redis.enabled" : false` and Front50 configured to use S3 for persistence, we had expected that `http://localhost:8080/health` would return `UP` if the S3 check passed. Instead, it returned `DOWN`, despite S3 working correctly. (ie: we could create pipelines, applications, etc, and see them populating the S3 bucket)
### Steps to reproduce
- Tell Front50 NOT to use Redis.
- Stop the Redis instance running locally.
- `curl http://localhost:8080/health` -- it will report `DOWN`
- Re-start Redis
- `curl http://localhost:8080/health` -- it will report `UP`
- `netstat -atnp | grep 6379` will show connections from the Front50 JVM to Redis. 
### Remediation

We were able to disable the springboot health check in `front50-local.yml`, though it might be useful to add this to the default configuration.

``` yaml
management:
  health:
    redis:
      enabled: false
```

**Comment by TheDigitalNinja** [comment]
I experienced the exact same issue today and can confirm that the above config change worked for us.

**Comment by lflux** [comment]
I experienced the same issue, and the above fix helped. It doesn't return UP immediately after boot which can be confusing while debugging. Looking at [S3Support.java:100](https://github.com/spinnaker/front50/blob/master/front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java#L100) this seems to be 45 seconds due to the timeout.

**Comment by ttomsu** [comment]
Just got bit by this too. @gregturn, can you but a conditional on this?

**Comment by ttomsu** [comment]
Thanks, @gregturn !

https://github.com/spinnaker/front50/pull/174
