### ISSUE TITLE
Feature request: Config History for pipelines

### ISSUE THREAD

**Issue by nate-opti** [spinnaker/spinnaker#1024]
Feature Area: 
Pipelines, UI

Description:
In the UI for configuring pipelines, it would be very useful to have a View Config History option to view a timestamped historical log of changes made to the pipeline, so the user can verify if the pipeline has been changed recently, for example. 

Even better would be a way to compare two different configs, for example: compare the latest version of the Pipeline Config to the previous, so the user can see what has changed (example: the min capacity of a server group has increased from 1 to 2). 

As a reference, Jenkins provides this functionality in "Job Config History".

Thanks!

**Comment by ajordens** [comment]
We've been working towards this with the S3/GCS support in Front50 (in combination with a versioned bucket).

What we don't have yet is a reasonable means for displaying the historical versions.

**Comment by ajordens** [comment]
This is now available for S3/GCS (in UI and Front50).
