### ISSUE TITLE
Pipeline in UI for openstack-Bake

### ISSUE THREAD

**Issue by ashleykasim** [spinnaker/spinnaker#1033]

**Comment by gadresushrut** [comment]
PR : https://github.com/spinnaker/deck/pull/2724
Need to work on bake with Packages.

**Comment by gadresushrut** [comment]
Installing Packages with Bake stage is done.
Need to have configuration changes in rosco config and json files.
Created the issue for the same.
https://github.com/spinnaker/spinnaker/issues/1163
