### ISSUE TITLE
Spinnaker attaches still initializing -unhealthy instances- and detaches the healthy ones 

### ISSUE THREAD

**Issue by medyagh** [spinnaker/spinnaker#1037]
when we enabled "Consider only cloud provider health when executing tasks"

Even though the instances are showing out ofService in the elb.
The spinnaker has detached "inService" ones and replaced them with "outOfService" ones
this makes the elb to be unhealthy for a few minutes.

I reproduced this behaviour for both high lander and red/black strategies.  

More details:

- we made sure the "Consider only cloud provider health when executing tasks" is reflected in the pipeline json. (by updating the server group)
- in the advanced settings "Health Check Type" is set to "elb"
- if we disable "Consider only cloud provider health when executing tasks" it will behave correctly and wont detach the healthy ones pre-maturely.

**Comment by ajordens** [comment]
If you're using an ELB ... you probably should not be selecting "Consider only cloud provider health when executing tasks". 

I suspect that is the root of your issue.

Feel free to reach out on Slack if you have additional questions.
