### ISSUE TITLE
Front50 ignores redis server settings from spinnaker.yaml and front50.yaml

### ISSUE THREAD

**Issue by AleksandrNull** [spinnaker/spinnaker#1038]
I'm trying to deploy spinnaker on top of kubernetes cluster and it looks like front50 ignore settings 
for redis location. It always trying to reach redis at localhost:6379

**Comment by lflux** [comment]
I'm seeing this too - no combination of settings i've tried will let me configure front50 to use an Elasticache redis cluster.

**Comment by lwander** [comment]
I believe @gregturn added redis support to front50

**Comment by gregturn** [comment]
You need...

```
spinnaker.redis.enabled: true
redis.configuration.secure: true
redis.connection: redis://username:<password>@<host>:<port>
```

...at a minimum to talk to any redis instance (you supplying password, host, and port number). Whether you put that in front50-local.yml or spinnaker.yml, it doesn't matter.

**Comment by AleksandrNull** [comment]
I'm sorry but I didn't get what I should do. First version of comment doesn't solve anything because it was the same as in default config files and only adds secure mode with user/pass. It's unclear where to put two last lines from comment because in config file explicitly specified that "cassandra.enabled" option is deprecated ...

**Comment by jrefi** [comment]
Raised PR to fix this issue.

https://github.com/spinnaker/front50/pull/149

**Comment by kkapelon** [comment]
Shouldn't this issue be closed? Both pull requested that address it, are merged.
