### ISSUE TITLE
Where is the proposal for how to incorporate authentication/authorization?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#1039]
I saw there is a planned feature about Authentication/authorization in roadmap, ''Develop a proposal for how to incorporate authentication/authorization in Spinnaker and implement it.'', Is the proposal finished, if it is, where is it? or Is there any details about  the planned feature of Authentication/authorization?

**Comment by gbougeard** [comment]
Is http://www.spinnaker.io/docs/securing-spinnaker enough for you?

The AuthZ part is being implemented in the fiat service.

**Comment by feihujiang** [comment]
@gbougeard Thanks,  this is enough for me now.
