### ISSUE TITLE
UI changes to support lbaasV2

### ISSUE THREAD

**Issue by ashleykasim** [spinnaker/spinnaker#1041]

**Comment by kmarquardsen** [comment]
comment from jeff:  UI for openstack supports 3 options for listeners: HTTP, TCP, and TERMINATED_HTTPS... in all cases, the internal protocol is implied, so there is no reason to prompt the user for it

it looks like the back end supports the same 3 options: HTTP, HTTPS (==TERMINATED_HTTPS), TCP
