### ISSUE TITLE
provider/openstack: Unable to wait for up instances.

### ISSUE THREAD

**Issue by derekolk** [spinnaker/spinnaker#1044]
![pasted image at 2016_08_02 12_46 pm](https://cloud.githubusercontent.com/assets/4722324/17372095/f8cf58f4-5967-11e6-937b-08d2169fea6a.png)

"tasks":[{"endTime":1470167057302,"id":"1","name":"stageStart","startTime":1470167057225,"status":"SUCCEEDED"},{"endTime":1470167057535,"id":"2","name":"determineSourceServerGroup","startTime":1470167057321,"status":"SUCCEEDED"},{"endTime":1470167057776,"id":"3","name":"createServerGroup","startTime":1470167057561,"status":"SUCCEEDED"},{"endTime":1470167058983,"id":"4","name":"monitorDeploy","startTime":1470167057818,"status":"SUCCEEDED"},{"endTime":1470167059206,"id":"5","name":"forceCacheRefresh","startTime":1470167059038,"status":"SUCCEEDED"},{"endTime":1470167059471,"id":"6","name":"waitForUpInstances","startTime":1470167059263,"status":"TERMINAL"},{"endTime":null,"id":"7","name":"forceCacheRefresh","startTime":null,"status":"NOT_STARTED"},{"endTime":null,"id":"8","name":"getCommits","startTime":null,"status":"NOT_STARTED"},{"endTime":null,"id":"9","name":"stageEnd","startTime":null,"status":"NOT_STARTED"}],"type":"createServerGroup"}]

2016-08-03 12:33:06.019  INFO 8192 --- [TaskExecutor-13] c.n.s.o.b.StageTaskPropagationListener   : Setting task status to TERMINAL (stageId: 61f57a6a-ce0a-470e-9c11-7ef00810456b, taskId: 6) [afterTask]
2016-08-03 12:33:06.027  INFO 8192 --- [TaskExecutor-13] c.n.s.o.b.ExecutionPropagationListener   : Marked 5e8159b3-89c2-4cc7-bfa8-340e343432ea as TERMINAL (afterJob)
2016-08-03 12:33:06.031  INFO 8192 --- [TaskExecutor-13] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=Orchestration:5e8159b3-89c2-4cc7-bfa8-340e343432ea]] completed with the following parameters: [{orchestration=5e8159b3-89c2-4cc7-bfa8-340e343432ea, application=os1, timestamp=1470241983058, description=Create New Server Group in cluster os1-s2-d2}] and the following status: [FAILED]

**Comment by jcwest** [comment]
I see the following in the orca log:

2016-08-03 12:33:05.956  INFO 8192 --- [TaskExecutor-13] c.n.s.o.c.t.i.WaitForUpInstancesTask     : Orchestration:5e8159b3-89c2-4cc7-bfa8-340e343432ea waitForUpInstances TERMINAL -- Batch step id: 81,  Task Outputs: { },  Stage Context: {
  "application" : "os1",
  "cloudProvider" : "openstack",
  "account" : "test",
  "region" : "RegionOne",
  "stack" : "s2",
  "freeFormDetails" : "d2",
  "serverGroupParameters" : {
    "minSize" : 1,
    "desiredSize" : 1,
    "maxSize" : 2,
    "securityGroups" : [ "os1-0729" ],
    "subnetId" : "09782cc5-ef8e-4a9a-98da-70d55ec1a4ef",
    "poolId" : "7a1a7f92-10d9-4c3b-8b0f-be7d209c96ee",
    "instanceType" : "m1.nano",
    "image" : "2426f47e-a3ff-492f-a791-23913bcdfc36"
  },
  "user" : "anonymous",
  "stageDetails" : {
    "name" : null,
    "type" : "createServerGroup",
    "startTime" : 1470241983098,
    "isSynthetic" : false
  },
  "batch.task.id.stageStart" : 76,
  "batch.task.id.determineSourceServerGroup" : 77,
  "notification.type" : "createdeploy",
  "deploy.account.name" : "test",
  "kato.last.task.id" : {
    "id" : "154"
  },
  "batch.task.id.createServerGroup" : 78,
  "kato.result.expected" : false,
  "kato.tasks" : [ {
    "id" : "154",
    "status" : {
      "completed" : true,
      "failed" : false
    },
    "history" : [ {
      "phase" : "ORCHESTRATION",
      "status" : "Initializing Orchestration Task..."
    }, {
      "phase" : "ORCHESTRATION",
      "status" : "Processing op: DeployOpenstackAtomicOperation"
    }, {
      "phase" : "DEPLOY",
      "status" : "Initializing creation of server group"
    }, {
      "phase" : "DEPLOY",
      "status" : "Looking up next sequence index for cluster os1-s2-d2..."
    }, {
      "phase" : "DEPLOY",
      "status" : "Heat stack name chosen to be os1-s2-d2-v000."
    }, {
      "phase" : "DEPLOY",
      "status" : "Loading templates"
    }, {
      "phase" : "DEPLOY",
      "status" : "Finished loading templates"
    }, {
      "phase" : "DEPLOY",
      "status" : "Getting load balancer details for pool id 7a1a7f92-10d9-4c3b-8b0f-be7d209c96ee"
    }, {
      "phase" : "DEPLOY",
      "status" : "Found load balancer details for pool id 7a1a7f92-10d9-4c3b-8b0f-be7d209c96ee with name os1-0729-1114"
    }, {
      "phase" : "DEPLOY",
      "status" : "Getting internal port used for load balancer os1-0729-1114"
    }, {
      "phase" : "DEPLOY",
      "status" : "Found internal port 443 used for load balancer os1-0729-1114"
    }, {
      "phase" : "DEPLOY",
      "status" : "Getting network id from subnet 09782cc5-ef8e-4a9a-98da-70d55ec1a4ef"
    }, {
      "phase" : "DEPLOY",
      "status" : "Found network id f7cfa725-5ba8-4d0e-9310-886105c94c9b from subnet 09782cc5-ef8e-4a9a-98da-70d55ec1a4ef"
    }, {
      "phase" : "DEPLOY",
      "status" : "Creating heat stack os1-s2-d2-v000"
    }, {
      "phase" : "DEPLOY",
      "status" : "Finished creating heat stack os1-s2-d2-v000"
    }, {
      "phase" : "DEPLOY",
      "status" : "Successfully created server group."
    }, {
      "phase" : "ORCHESTRATION",
      "status" : "Orchestration completed."
    } ],
    "resultObjects" : [ {
      "deployedNames" : [ "os1-s2-d2-v000" ],
      "deployedNamesByLocation" : {
        "RegionOne" : [ "os1-s2-d2-v000" ]
      },
      "messages" : [ ],
      "serverGroupNameByRegion" : { },
      "serverGroupNames" : [ ]
    } ]
  } ],
  "deploy.server.groups" : { },
  "deploy.jobs" : {
    "RegionOne" : [ "os1-s2-d2-v000" ]
  },
  "batch.task.id.monitorDeploy" : 79,
  "force.cache.refresh.errors" : [ ],
  "refreshed.server.groups" : [ ],
  "batch.task.id.forceCacheRefresh" : 80,
  "zones" : [ ],
  "processed.server.groups" : [ ]
}
