### ISSUE TITLE
orca fails to launch

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1046]
Getting the following error when trying to launch orca with './gradlew bootRun' on Ubuntu 14.04 using Java 1.8.0_101:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'operationsController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.spinnaker.orca.igor.BuildArtifactFilter com.netflix.spinnaker.orca.controllers.OperationsController.buildArtifactFilter; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.netflix.spinnaker.orca.igor.BuildArtifactFilter] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

The problem did not exist in commit d2bfc0b9b2e084b0c1b1eb4f27c7e7df55866642 (Aug 1, 2016).
@ajordens: please take a look

**Comment by SteveKMin** [comment]
👍 bump

**Comment by duftler** [comment]
Please verify the issue is fixed when you have a chance.

**Comment by jcwest** [comment]
Orca is starting up fine with the latest code. Thanks for the fix. Sorry it took so long to verify.
