### ISSUE TITLE
Feature Request: Kubernetes - Show Images for Cluster and Project

### ISSUE THREAD

**Issue by bfarrell** [spinnaker/spinnaker#1047]
Much like the ability to see the Jenkins Build when using AWS or other cloud providers, it would be great to be able to see the images deployed at a glance for the cluster and especially project page showing those clusters

Originally, I had thought to see the image that triggered the deployment, but it likely makes sense to see all the container images deployed during the pipeline.

The project page today just shows #0 for all clusters when using Kubernetes.

Ive done a bit of work just to check out what it would potentially look like.  Adding a couple of screen shots for that purpose.

Cluster page:
Utilize a list of images
![image](https://cloud.githubusercontent.com/assets/3035661/17415825/fcde8aac-5a50-11e6-82ea-a0526a9f2008.png)

Realized as a string of images
![image](https://cloud.githubusercontent.com/assets/3035661/17415841/153e05aa-5a51-11e6-8124-8641385cc732.png)

Project Dashboard:
![image](https://cloud.githubusercontent.com/assets/3035661/17415854/23cabd20-5a51-11e6-9458-43e95895fafb.png)

Please let me know your thoughts @lwander or others.

**Comment by lwander** [comment]
This is a really good idea. Some of the build info is missing because there
is (so far) no way to surface image provenance for docker, but in the mean
time listing images alone would be really nice.

**Comment by bfarrell** [comment]
So I am looking at how to retrieve the code.  Looks like the read operation isnt using expand=true to get the details so that I can pull the containers from deployDescription.  So it seems I can do a couple of things, looking for some feedback

1) Use expand=true when making the serverGroup call for those two pages
2) Update KubernetesClusterProvider to add an image list to the serverGroup
a.  Can do this in buildInfo and not change anything else
b.  Do this in another field, imageList?, and update the summary to pass that back

Thoughts?

**Comment by lwander** [comment]
The approach you're taking taking in 855 with 2a is the way to go, I think.

Keep in mind this representation is subject to change once we have image provenance figured out, but we'll be sure to loop you in.
