### ISSUE TITLE
Docker trigger not working on 'install in kubernetes' version

### ISSUE THREAD

**Issue by grandmore** [spinnaker/spinnaker#1053]
I have a set of pipelines that trigger when a docker image is updated. Currently I have them set to the ':latest' tag. The trigger never takes place when docker hub is updated.

I have installed spinnaker into the Kubernetes version it's managing.

I have looked through the logs and cannot see any issues. I assume that spinnaker is polling hub.docker.com for changes. What log should I look at to diagnose this.

**Comment by lwander** [comment]
Spinnaker doesn't allow you to automatically trigger deployments off of aliased tags like `:latest`. The reason being it reduces visibility into your cluster when you should instead be versioning your containers. Instead you need to push a new tag matching the optional "tag" regex in the trigger dialog.

**Comment by lwander** [comment]
I closed this because this matches the intended behavior, but if you have any questions/suggestions about how to get these deployments/triggers to work feel free to raise them here.

**Comment by grandmore** [comment]
Thanks @lwander, I read about the viability issue but I assumed this was a suggested way of working not standard behaviour.

I'm testing various networking setups in kubernetes with 5 services and manually deploying over and over is tedious hence why I wanted to use 'latest' as an interim as its very repetitive creating a release in github x 5 services just to test an idea. I setup some spinnaker pipelines to take some of the headache out of it.

However, I would suggest that the popup text to the left should explain this in the interface.. Currently is says this:
(optional) if specified, only the tags that match this java Regular Expression will be triggered. Leave empty to trigger builds on any tag pushed.

It should really say:
(optional) if specified, only the tags that match this java Regular Expression will be triggered. Leave empty to trigger builds on any tag pushed, except 'latest'.

**Comment by lwander** [comment]
If you're using dockerhub, the release process is pretty easy:

```
git checkout -b new-release-version
git push origin new-release-version
```

It's only 1 extra command to create the feature branch that will turn into a docker tag.

Also, `:latest` isn't the only branch that can't be auto-deployed, Spinnaker only triggers builds on new incoming tags.
