### ISSUE TITLE
OpenStack: fix issues with server group detail object

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1057]
In order for the UI to work properly, we need the following issues fixed for the server group detail object sent by clouddriver for openstack:

- Missing subnet information. ID at a minimum, but having the name also would allow the UI to avoid a lookup when displaying detail info.
- Security group IDs are coming as "[u'...']" instead of plain text UUIDs.
- minSize, maxSize, desiredSize values are sent as strings instead of numbers.

**Comment by emjburns** [comment]
@jcwest min/max/desired size for what

**Comment by jcwest** [comment]
min/max/desired are all under scalingConfig in JSON.
Example of received security group ID value: "securityGroups":["[u'5342bd23-f9b4-40c0-8d6b-e33bc316d21a']"]
Looks like some kind of unicode escaping format.

Example JSON that the UI is getting presently: {"account":"test","buildInfo":{},"createdTime":1470787628000,"health":null,"image":{"createdAt":1469497768000,"id":"2426f47e-a3ff-492f-a791-23913bcdfc36","name":"cirros-0.3.4-x86_64-uec","properties":{"kernel_id":"12ac58ae-3237-4259-9f9b-81a3b1ebc028","ramdisk_id":"8c5a353a-1728-4e10-8e06-29a170f24c25"},"size":25165824,"status":"active","updatedAt":1469497769000},"insightActions":[],"instances":[{"account":"test","instanceId":"7d61c6ab-ddcf-44a6-a1a6-7b238facf348","keyName":null,"launchTime":1470773239000,"metadata":{"metering.stack":"44781e92-471f-4454-a74b-ee1a235d2361"},"name":"os-cbr3-6ii5itjvolzx-2yaxnysqiude-server-bifgx5mbypj5","region":"RegionOne","status":"active","zone":"nova"}],"launchConfig":{"image":"2426f47e-a3ff-492f-a791-23913bcdfc36","instanceType":"m1.nano","loadBalancerId":"73b48a9c-c1e5-4fa7-9162-65a755e32409","networkId":"f7cfa725-5ba8-4d0e-9310-886105c94c9b","securityGroups":["[u'5342bd23-f9b4-40c0-8d6b-e33bc316d21a']"]},"loadBalancers":["openstack:loadBalancers:test:RegionOne:73b48a9c-c1e5-4fa7-9162-65a755e32409:os1-0808-1826"],"name":"os1-0809-1306-v000","region":"RegionOne","scalingConfig":{"desiredSize":"1","maxSize":"1","minSize":"1"},"type":"openstack","zones":["nova"]}

**Comment by varikin** [comment]
@jcwest what is the API you are hitting to get this reponse?
