### ISSUE TITLE
docker provider configuration not merged correctly

### ISSUE THREAD

**Issue by colemickens** [spinnaker/spinnaker#1058]
**Cloud Provider**: Kubernetes

**Environment**: Spinnaker running on an Azure VM pointed at a Kubernetes cluster

**Feature Area**: Configuration

**Description**

*Expected:*

* I can easily add Docker Hub credentials to the `spinnaker-local.yml` and reference them from the `kubernetes` provider section.

*Actual:*

* a couple hours spent only to realize that I had the fields right, they just weren't being merged together properly

**Steps to Reproduce**

* (in `spinnaker-local.yml`) try to add a new docker account, then reference it from the kubernetes section, it will complain it can't find it

* (in `spinnaker-local.yml`) try to remove the default "repository" from the primary credentials. The "library/nginx" image still gets set as the requested one

* try to remove the repository field, in *any* way, including direct edits to `clouddriver.yml`, pointed at Docker Hub. It seems like it access the images... but when the the web UI queries for containers in the autocomplete, an array of empty objects is returned

**Workaround**

* for my needs, I just wanted to show it working, so I picked a repository and hard coded it and the docker credentials into `clouddriver.yml`

**Comment by lwander** [comment]
Hey @colemickens, could you post the docker registry section of your `spinnaker-local.yml` config that failed?

**Comment by JargoonPard** [comment]
I have validated that these same values placed into clouddriver.yml will work but not when they only exist in spinnaker-local.yml

  dockerRegistry:
    # For more information on configuring Docker registries, see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-configuration#section-docker-registry

    # NOTE: Enabling dockerRegistry is independent of other providers.
    # However, for convienience, we tie docker and kubernetes together
    # since kubernetes (and only kubernetes) depends on this docker provider
    # configuration.
    enabled: true

    primaryCredentials:
      name: my-docker-registry
      address: https://index.docker.io/
      repository: larryguger/web-lab
      username: larryguger
      # A path to a plain text file containing the user's password
      #passwordFile: ${SPINNAKER_DOCKER_PASSWORD_FILE}
      password: <removed>

**Comment by JargoonPard** [comment]
What shows up for a list of accounts when I try to create a new application is "my-docker-registry" but not "my-kubernetes-account".  Below is the K8S config section.
  kubernetes:
    # For more information on configuring Kubernetes clusters (kubernetes), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-kubernetes-cluster-setup

    # NOTE: enabling kubernetes also requires enabling dockerRegistry.
    enabled: true
    primaryCredentials:
      # These credentials use authentication information at ~/.kube/config
      # by default.
      name: my-kubernetes-account
      dockerRegistryAccount: ${providers.dockerRegistry.primaryCredentials.name}

**Comment by trescst** [comment]
@JargoonPard, I ran into a similar issue today.

When I looked at my clouddriver logs (`/var/log/spinnaker/clouddriver/clouddriver.log`) I noticed that it was not able to connect due to an authorization issue:

```
2016-08-31 12:59:23.755  INFO 25289 --- [           main] Class                                    : Could not load account my-kubernetes-account for Kubernetes.
com.netflix.spinnaker.clouddriver.kubernetes.deploy.exception.KubernetesOperationException: Get Namespaces for account my-kubernetes-account failed: Unauthorized! Token may have expired! Please log-in again.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
```

I was first using a GCP service account to connect to my Kubernetes cluster, this gave the above error.  When I put some actual credentials into `~/.kube/config` and restarted spinnaker everything worked.

Not saying that you are hitting the same issue, but my solution may get you on the right track to resolve your issue.

**Comment by lwander** [comment]
hey @JargoonPard I believe you had a fix for this? These are separate issues, @trescst, this one stems from spring-config being merged incorrectly whereas yours I believe comes from using the `auth-provider` section in your kubeconfig.

**Comment by JargoonPard** [comment]
Hey @trescst, I actually found the issue and let Lars know but forgot to update here.  The clouddriver.yml file had a colon ":" at the end of the passwordFile and username references which was causing them to not resolve correctly. Once I removed those errant characters everything worked correctly.  You might check your config files as well.

**Comment by ajordens** [comment]
Is this still an issue?

**Comment by lwander** [comment]
The colon is gone, thanks @JargoonPard 
https://github.com/spinnaker/spinnaker/blob/master/config/clouddriver.yml#L78
