### ISSUE TITLE
Allow metadata during server group create and clone

### ISSUE THREAD

**Issue by emjburns** [spinnaker/spinnaker#1068]
inject information to the VM through the openstack metadata service - using the 'user data' field in server groups/options. This is implemented in AWS. 

Done through nova meta (http://docs.openstack.org/cli-reference/nova.html#nova-meta)

In OpenStack4j: http://www.openstack4j.com/learn/compute - metadata operations

This is a request from someone interested in using the openstack provider

**Comment by drmaas** [comment]
Metadata is different than user data.

User data is already implemented - it provides scripts (or urls to scripts) that will execute on vm boot via cloud-init.

Metadata consists of key-value pairs.

This ticket will be for metadata.
