### ISSUE TITLE
Not Able to scroll the home page of spinnaker 

### ISSUE THREAD

**Issue by ishwar1987** [spinnaker/spinnaker#1078]
Hi,
I follow the installation steps from this url 
https://github.com/spring-cloud/spring-cloud-spinnaker
I have push this app on cloud foundry successfully. But i am not able to scroll down entire page to fill the details.  Kindly check the screen shot.
![spinnakerissue](https://cloud.githubusercontent.com/assets/7974404/17896273/a6052020-696d-11e6-8fea-50e91a3a7e8a.PNG)

I am not able to see submit button and others text box.
Thanks in advance

**Comment by danielpeach** [comment]
@gregturn

**Comment by gregturn** [comment]
Superceded by https://github.com/spring-cloud/spring-cloud-spinnaker/issues/65

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-spinnaker/commit/f49ba694aaf1226463a5e962b688197bc6956893

Suggest closing.
