### ISSUE TITLE
Eureka health provider DNS/TXT support

### ISSUE THREAD

**Issue by daltonconley** [spinnaker/spinnaker#1084]
Netflix Eureka supports searching for specific Eureka instances using DNS TXT records. See [Configuring EIPs Using DNS](https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2#configuring-eips-using-dns)

It would be nice to support this functionality via the Eureka health provider in Cloud Driver. Currently, it appears that you must specify a single Eureka instance ip address.

**Comment by florind** [comment]
The solution I used is to configure an ELB for Eureka and have a Route53 CNAME entry that exposes it over a fixed DNS. FInally, have this DNS configured in clouddriver.
This ELB will _only_ be used for integrating Eureka with Spinnaker.

**Comment by robzienert** [comment]
The solution that @florind mentioned is how we do it at Netflix. Closing due to age, can be reopened if the community intends to add a fix for it.
