### ISSUE TITLE
Configure discovery service/health provider per server group/cluster

### ISSUE THREAD

**Issue by daltonconley** [spinnaker/spinnaker#1085]
I'm currently running multiple logical environments within a single AWS account (using security groups to separate them). Because of this, I use multiple Eureka instances (one to represent each environment). With that said, I have to name my accounts differently (even though its the same account) in the cloud driver configuration, in order to support multiple Eurekas per account, per environment.

I'm sure there could be some improvements on the Eureka health provider configuration, however, my proposal is that we move discovery service configuration to the cluster/server group level of Spinnaker so that if I want to configure a discovery service for an application, I do it when setting up a server group. I'm also proposing that we store this information within the pipeline JSON (within Cassandra or S3 - however the Front50 is configured). This would solve my strange problem mentioned above with running multiple environments in a single account, but it would also make it much easier to configure discovery services for applications, rather than updating the cloud driver configuration. 

Other notes: 
* I'm aware that I could potentially hookup Spinnaker to a config server such as Spring's config server and pull in my config data, without having to manage the config on the machine. 
* I would love to see account level configuration done via the UI, rather than within the cloud driver configuration but I think thats outside the scope of this issue.

**Comment by florind** [comment]
I'm actually facing the same issue. I did configure two accounts with the same accountId (trying to avoid the 2 account setup) but I see duplicated entries (one per account) in the cluster and load-balancer views. @daltonconley are you seeing the same?
I think the idea is valid. It would also help to be able to explicitly select the Eureka healthcheck provider(s) in the Server Group setup alongside ELB and EC2.

**Comment by tomaslin** [comment]
See `allowMultipleEurekaPerAccount` functionality. https://github.com/spinnaker/clouddriver/tree/master/clouddriver-eureka
