### ISSUE TITLE
OpenStack support for clusters without assigned LoadBalancer

### ISSUE THREAD

**Issue by meledin** [spinnaker/spinnaker#1092]
Clouddriver-OpenStack currently has a strict requirement that a cluster comes with a load balancer, something not enforced by AWS/GCE. In the latter cases, it is possible to create instances without an assigned Load Balancer; however, on OpenStack it is not.

This is useful both for purely internal services, services that use discovery and other methods of load balancing, for which a load balancer is unnecessary. This also could make it possible to use on clusters without LBaaS.

**Comment by derekolk** [comment]
Overall, I needed to create a separate asg resource template to remove openstack load balancer additions/deletions.

Currently internally being reviewed.
