### ISSUE TITLE
refactor lbaasv2 to use one pool for all lb listeners

### ISSUE THREAD

**Issue by drmaas** [spinnaker/spinnaker#1095]
This is supported in mitaka, which we are now targeting for those wishing to use openstack load balancers.

**Comment by drmaas** [comment]
Update: It looks like this feature is not yet released in openstack - see http://docs.openstack.org/releasenotes/neutron-lbaas/unreleased.html

**Comment by lwander** [comment]
Closing because "wont-fix"
