### ISSUE TITLE
Please add support for Kubernetes Annotations

### ISSUE THREAD

**Issue by equinox0815** [spinnaker/spinnaker#1106]
It would be nice to have the possibilty to add [annotations](http://kubernetes.io/docs/user-guide/annotations/) to kubernetes objects. For our usecase adding them to services (load-balancers) would be enough but of course annotating pod templates and possibly other objects could be handy too.

**Comment by lwander** [comment]
For anyone who wants to get working on this project, this is a pretty quick 2-step fix. Follow this pair of PRs for an example of how to add a field to the deployment description:
https://github.com/spinnaker/clouddriver/pull/992
https://github.com/spinnaker/deck/pull/2657

**Comment by lwander** [comment]
@danielpeach the backend work is in, could you take care of the frontend?

**Comment by philsttr** [comment]
@lwander / @danielpeach, any updates on UI support?

**Comment by lwander** [comment]
Support is in for pods & replicasets

**Comment by lwander** [comment]
Ah, and services

**Comment by cristim** [comment]
Is this possible for Spinnaker itself?

I couldn'd find anything about this in the installation manuals, and this is really useful on distributed production setups running on Kubernetes.
