### ISSUE TITLE
Please make terminationGracePeriodSeconds (kubernetes) configurable

### ISSUE THREAD

**Issue by equinox0815** [spinnaker/spinnaker#1107]
Some services in our cluster need some time to shutdown (longer than the default kubernetes grace period of 30s). We also don't want to change this value globally since some services are much faster when shutting down.
It would be great if pod templates (server group templates) would allow to change the terminationGracePeriodSeconds option of kubernetes.

**Comment by lwander** [comment]
For anyone who wants to get working on this project, this is a pretty quick 2-step fix. Follow this pair of PRs for an example of how to add a field to the deployment description:
https://github.com/spinnaker/clouddriver/pull/992
https://github.com/spinnaker/deck/pull/2657

**Comment by equinox0815** [comment]
Thanks, i will give it a try... just need to get a build/test environment running....

**Comment by parajanoff** [comment]
Hi All, we've completed the development of this feature. We are reviewing the changes and will be initiating a pull request soon.

**Comment by parajanoff** [comment]
@lwander @equinox0815 Could you please review and close the issue?
