### ISSUE TITLE
Checkboxes not working anymore in firefox

### ISSUE THREAD

**Issue by giladwolff** [spinnaker/spinnaker#1109]
*Title*

Cheboxes in Firefox browser stopped working recently.

*Cloud Provider*
AWS

*Environment*
Spinnaker running in aws.

*Feature Area*
UI

*Description*
When trying to check a checkbox instead of a checkmark the visual item is select (see image). Using the mouse or navigating to the element and trying to check/uncheck it with the space bar do not work. It does work in Chrome.

![checkbox](https://cloud.githubusercontent.com/assets/1806752/18321476/f7c30488-74e2-11e6-8ecc-6e3631c39a84.jpg)

*Steps to Reproduce*
Go to a checkbox to to check it.

*Additional Details*
I'm running on Ubuntu 16.04, firefox 48.0 and spinnaker/deck of spinnaker-deck_2.788.0-3_all.deb.

**Comment by anotherchrisberry** [comment]
Confirmed this is a bug on OSX, too.

The problem seems to be that we're adding `contenteditable="true"` to all inputs, and FF doesn't like that. Working on a fix - thanks for pointing it out!

**Comment by anotherchrisberry** [comment]
fixed in 2.790.0

**Comment by giladwolff** [comment]
Thanks for the quick fix!
