### ISSUE TITLE
Rollback for servergroups - orca

### ISSUE THREAD

**Issue by ashleykasim** [spinnaker/spinnaker#1113]
Implement rollback in clouddriver

**Comment by drmaas** [comment]
Rollback happens from the orca layer - I think it issues the correct sequence of options (disable new server group, enable old server group, delete new server group) to clouddriver.

**Comment by drmaas** [comment]
I don't think there is any provider-specific stuff to do here, but we can keep this open in case.

**Comment by duftler** [comment]
I agree with @drmaas; shouldn't be anything openstack-specific to do here. If Enable, Resize and Disable all work properly, Rollback should come for free.
It Enables the 'new' server group, Resizes it to match the capacity of the soon-to-be-disabled server group, and DIsables the 'old server group'.

https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/RollbackServerGroupStage.groovy
