### ISSUE TITLE
Create button on Create Server Group window not showing up

### ISSUE THREAD

**Issue by varikin** [spinnaker/spinnaker#1121]
The Create button on the Create Server Group window doesn't appear after filling out the form until I click around more and scroll. Seems the validation for the create button is missing something.

**Comment by drmaas** [comment]
I have seen this behavior too on and off. Usually it's apparent when the window first pops up.

**Comment by SteveKMin** [comment]
There is logic that requires you to "visit" every section before the create button actually shows up. However, the button is always disabled until all sections are filled out. I think it might be more intuitive if we just have the button visible at all times, and remove all logic involving visiting every section. You still won't be able to submit until the form is all filled out.
