### ISSUE TITLE
Instance status on more than one LB associated to 1 SG should be the same on all LBs.

### ISSUE THREAD

**Issue by gbougeard** [spinnaker/spinnaker#1122]
_Title_

Instance status on more than one LB associated to 1 SG should be the same on all LBs.

_Cloud Provider_

AWS

_Environment_

running AMI or via docker-compose

_Feature Area_

Load balancer UI

_Description_

I have 2 load balancers associated to 1 SG.
The instances are never green on both Load balancers. One instance can be green on only one LB.
They should be green for both.

**Comment by gbougeard** [comment]
I search a little bit in deck to check if it's a deck issue but I did not really find out because I'm not an Angular expert.
Could anyone point me how the health status of an instance is retrieved?
I'd like to verifiy if the issue is on the deck or clouddriver side.

cc @anotherchrisberry @cfieber

**Comment by gbougeard** [comment]
The issue looks like to not be in deck but clouddriver.
I investigated a little `AmazonLoadBalancerProvider` and found something but I'm not pretty sure it's easy to fix without breaking anything.

**Comment by ajordens** [comment]
Can you let me know what you found? 

We have ASGs attached to multiple load balancers w/o issue (both are green).

Is it actually showing as down in one of the load balancers?

**Comment by gbougeard** [comment]
![screen shot 2016-10-10 at 10 59 37](https://cloud.githubusercontent.com/assets/728814/19231167/c94f3062-8ed8-11e6-94bc-d0aef291a2ee.png)

The ASG has 2 ELB associated, 1 internal one and 1 external one. The instances are never green in both LB.

What I found : 
In `AmazonLoadBalancerProvider` there is something wrong with the cache. Health informations are set only for 1 LB associated to the ASG. Because this health informations are not set, the instance health status is displayed by a grey icon (detached). 

@ajordens if in your configuration it looks ok, maybe something is incorrectly setup in my ASG/ LB?

**Comment by gbougeard** [comment]
The ASG has 2 ELB associated, 1 internal one and 1 external one. The instances are never green in both LB.

What I found : 
In AmazonLoadBalancerProvider there is something wrong with the cache. Health informations are set only for 1 LB associated to the ASG. Because this health informations are not set, the instance health status is displayed by a grey icon (detached).

@ajordens if in your configuration it looks ok, maybe something is incorrectly setup in my ASG/ LB?
![r_ _load_balancers_ _instance_details](https://cloud.githubusercontent.com/assets/728814/19231742/f631fe2c-8edb-11e6-99b3-22573c04afbf.png)

**Comment by robzienert** [comment]
Closing, this is definitely not an issue with Spinnaker itself, but feel free to re-open with more information if you need some help to triage.
