### ISSUE TITLE
It should be possible to modify capacity when cloning a SG

### ISSUE THREAD

**Issue by gbougeard** [spinnaker/spinnaker#1123]
*Title*

It should be possible to modify capacity when cloning a SG

*Cloud Provider*

AWS

*Environment*

Running AMI or through docker-compose

*Feature Area*

UI, cloning a SG

*Description*

When I clone a SG, I'd like to modify the capacity (to set it to 0 for instance).
Doing this, the save button becomes hidden.

Conclusion : you can't clone a SG without redefining the capacity.
Consequence : it will pop instances to the new SG even I don't want to.

**Comment by duftler** [comment]
Are you trying to do this ad-hoc via the Clone server group wizard, or via
a Clone pipeline stage?

And what are the exact steps to reproduce the save button becoming hidden?

**Comment by gbougeard** [comment]
- select a SG
- clic on Clone on the Menu on the right pane
- select the radio to specify a custom Capacity
- When I change the value of the capacity, the Save button disappear

**Comment by duftler** [comment]
There is some validation in play there.
Have you ensured that you have values for Min/Max/Desired, that Min is not
greater than Max, and that Desired is within the Min/Max boundaries?
If any of those tests fails, the 'Create' button will disappear until the
issue is addressed.

**Comment by gbougeard** [comment]
Yep, testing it deeper shows me those validations.
I did not realize the values could be incorrect.

My bad :(
