### ISSUE TITLE
Pipeline in UI for openstack-Script

### ISSUE THREAD

**Issue by gadresushrut** [spinnaker/spinnaker#1136]

**Comment by drmaas** [comment]
What does this mean? Please provide context for the implementer so they know what the issue is.

**Comment by WaniMukesh** [comment]
Created Jenkins job <job_name> with two parameters REPO_URL and COMMAND and set the <job_name> in orca.yml
Added Execute Windows Batch Command in <job_name> job with following script

e.g.
cd %WORKSPACE%
rmdir /Q /S myrepo
git clone %REPO_URL%
Script file to be executed.

Run the Script pipeline manullay from spinnaker ui and it run successfully.
