### ISSUE TITLE
Userdata url doesn't work against authenticated url (e.g. swift)

### ISSUE THREAD

**Issue by drmaas** [spinnaker/spinnaker#1141]
Allow 3 different user data types: swift, text, and url

add top-level attribute 'userDataType'.

```
val payload = client.objectStorage().objects().download(ObjectLocation.create("test", "test/test.sh"), DownloadOptions.create())
println(payload.httpResponse.getEntity(String::class.java))
```

**Comment by drmaas** [comment]
Probably want to also store userData and userDataType into the stack metadata.

**Comment by varikin** [comment]
@drmaas How did you plan to send the swift container and path via `userData`?

**Comment by drmaas** [comment]
It's just a full path to the objext, and type is marked as 'Swift'

**Comment by varikin** [comment]
So we also need the container name then.

**Comment by drmaas** [comment]
yes :(

**Comment by drmaas** [comment]
I propose using "container:path/to/object" for now.

**Comment by drmaas** [comment]
Created #1172
