### ISSUE TITLE
Add support for AWS ALB Load Balancers

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#1150]
We're starting to explore the use of [ALBs](https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/) within my company and would like Spinnaker to support this as a Load Balancer option.

When adding a new Load Balancer in AWS, it'd be nice to have a radio of either ELB or ALB, which would change the following configuration sections. Alternatively, depending on how much implementation we'd hide from the end-user, perhaps we'd just expose HTTP/2 and Websockets (for example) as new options, Level 7 configs, etc and then under the covers choose for the user which one to use.

I presume this would primarily only affect Deck and Clouddriver, yes?

**Comment by cfieber** [comment]
There's some preliminary support in there now for ALBs - namely:

1) during a deploy, if you add the name of an ALB in the `loadBalancers` list, the new server group will get attached to all the target groups associated with that ALB
2) target group health is indexed and associated with a server group's instances, so instances have to pass targetgroup health checks before a deploy stage will consider them healthy and proceed
3) if a server group is associated with an ALB and is cloned, the new server group will also be associated with the ALB
4) if a server group is enabled or disabled, its instances are associated/removed from ALBs

Definitely much more to do, but it is enough to start using ALBs with the CRUD of them still having to happen via the AWS console

**Comment by robzienert** [comment]
Oh, delightful. We setup loadbalancers via Terraform right now anyway, so this sounds like it would fit our usecases perfectly for the timebeing.

**Comment by cterrykenzan** [comment]
Is there any additional configuration that needs to be done in order to use ALBs?  Or do they have to be created a certain way to be picked up by Spinnaker?

When I add the ALB to the pipeline's JSON and execute, I get an Exception "Provided Load Balancers may not be valid. Please ensure they exist and try again. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: <req id>)"

**Comment by KristianOellegaard** [comment]
I just had to add it to the pipeline JSON but unfortunately it adds the instance to all target groups associated with the load balancer, effectively making it fairly useless for us, because we want to use ALB for internal apps that do not need a dedicated load balancer so that we could mount different apps on different endpoints.

**Comment by davidedimauro88** [comment]
Hi @cterrykenzan 
I'm having the exact same problem with one of my ASGs trying to add the ALB to the `load_balancers` Terraform attribute. Have you, by any chance, found the solution to this issue?
Thanks in advance!

**Comment by robertsigler** [comment]
Just linking this PR so that it is visible from this issue.

https://github.com/spinnaker/clouddriver/pull/1457

**Comment by cdoughty-r7** [comment]
We tested this branch and it appears to be solving our problems with ALBs.  We are able to now use an ALB with multiple target groups by creating a "targetGroups" array in the pipeline JSON and we're now able to get multiple ec2 instances routing through a single ALB.  

We'd love to get this merged asap so we can use this.  Please let us know if we can help in any way. Thanks for creating this!

**Comment by jrsquared** [comment]
Clouddriver support for ALBs should be in from spinnaker/clouddriver#1457. I will work on support in Deck in the coming weeks.

**Comment by torarvid** [comment]
Hi, is there any update on this issue?

**Comment by JJediny** [comment]
@jrsquared is this closed? https://github.com/spinnaker/clouddriver/pull/1457#issuecomment-294188617

**Comment by cristim** [comment]
https://github.com/spinnaker/clouddriver/pull/1457 is merged, so I think this can be closed now.
