### ISSUE TITLE
Make server group consul aware

### ISSUE THREAD

**Issue by derekolk** [spinnaker/spinnaker#1157]
In order for server groups to be enabled/disabled by consul, we need to add the following:

- Add consul health checks into OpenstackInstance and Caching Agent
- Add discovery flag to OpenstackServerGroup
- Update disable flag to include consul state (disabled and discoverable) 

// If the server group is disabled, but Consul isn't, we say the server group is discoverable.
 // If the server group isn't disabled, but Consul is, we say the server group can be reached via load balancer.
 // If the server group and Consul are both disabled, the server group remains disabled.
 // If the server group and Consul are both not disabled, the server group is not disabled.
 serverGroup.disabled &= consulDisabled

https://github.com/spinnaker/clouddriver/pull/984/files

**Comment by lwander** [comment]
This sounds correct to me

**Comment by drmaas** [comment]
Will be able to test once we create an image with consul, and a service registered.
