### ISSUE TITLE
(AWS) Unable to create new applications in deck

### ISSUE THREAD

**Issue by okoye** [spinnaker/spinnaker#1162]
Attempting to create a new application in spinnaker results in the following shown:

<img width="599" alt="github" src="https://cloud.githubusercontent.com/assets/152554/18773808/8428b87a-8107-11e6-8a7a-514a7d48e3fe.png">

*Cloud Provider*

AWS.

*Environment*

I am running Spinnaker using the latest version of deck (v2.823.0), gate (2.75.0-3) and orca (1.220.0-3). We have only enabled the AWS provider and our front50 service is still backed by cassandra.

*Description*

After filling the required information you would expect it to create an application entry in cassandra instead it throws an error complaining about the HTTP method used to post information. A peek in Chrome console shows no conspicuous errors (I see all 200s. code for requests). Existing applications (100 of them) work without issues.

*Steps to Reproduce*

Install deck, gate and attempt to create an application in chrome.

*Additional Details*

No exception logs shown in gate either.

**Comment by ajordens** [comment]
Are you also running the latest version of `front50`?

Any exceptions in `orca`?

**Comment by okoye** [comment]
I am currently installing the latest release of front50 (1.45.0-3). Will get back to you on orca.

**Comment by ajordens** [comment]
It's quite possibly that ... the newer `orca` is hitting a /v2/applications api that is in `front50` as of ~7-10 days ago.

**Comment by okoye** [comment]
I do see an exception in orca which maybe solved by the current ongoing upgrade to front50?

```
2016-09-23 04:24:16.206 ERROR 907 --- [tTaskExecutor-7] c.n.s.security.AuthenticatedRequest      : Error occurred propagating authentication context

retrofit.RetrofitError: 405 Method Not Allowed
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy62.create(Unknown Source)
```

**Comment by okoye** [comment]
We did upgrade our orca earlier today, that could explain this problem.

**Comment by okoye** [comment]
Upgrading front50 solved it. Thanks @ajordens !
