### ISSUE TITLE
Rosco : Configurations need for Bake stage with packages.

### ISSUE THREAD

**Issue by gadresushrut** [spinnaker/spinnaker#1163]
We need to below changes in config and json files.
Changes in config/rosco.yml
rosco:
 jobs:
   local:
      timeoutMinutes: 60

Changes in config/packer/openstack.json
"ssh_timeout": "10000s”,
"pause_before": "300s"

**Comment by varikin** [comment]
@gadresushrut why did both `pause_before` and `ssh_timeout` need to be set?  And why was `ssh_timeout` set to `10000s`? That is almost 3 hours. Also, where was ssh_timeout set? The documentation says that is for a `communicator` which is not explicitly set.

**Comment by gadresushrut** [comment]
@varikin  We need to set pause_before to 300sec [5 minutes] because it was failing to install softwares as machine didn't came up in 30s, because of that it was failing.
I had set to 5 min and it started to work. I don't know what should be the exact time, time may change with the images.
About ssh_timeout, I don't know exact value needs to be set for ssh_timeout, but with the default ssh_timeout it was not working.
