### ISSUE TITLE
Clouddriver: Make all operation descriptions implement a common interface

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#1164]
Currently all operations are mostly independent of each other. This means making description-wide changes requires touching every description in each cloud provider. 

I propose  a simple, common trait for all descriptions that would increase type safety. Specifically [this one](https://github.com/ttomsu/clouddriver/blob/b50bd129e9f0478221768f34de13803394a083f9/clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/resources/CredentialsNameable.groovy).

Any thoughts or objections?

@spinnaker/reviewers

**Comment by lwander** [comment]
SGTM

**Comment by derekolk** [comment]
SGTM

**Comment by duftler** [comment]
SGTM2

**Comment by cfieber** [comment]
can you make that a java interface instead?

**Comment by lwander** [comment]
Looks like this was implemented in the above PRs
