### ISSUE TITLE
Create instances from volumes

### ISSUE THREAD

**Issue by drmaas** [spinnaker/spinnaker#1179]
See http://docs.openstack.org/user-guide/cli-nova-launch-instance-from-volume.html

nova equivalent:

```
nova boot --flavor FLAVOR --block-device \
  source=SOURCE,id=ID,dest=DEST,size=SIZE,shutdown=PRESERVE,bootindex=INDEX \
  NAME
```

This will involve modifying the heat template to specify the source in a block_device_mapping(_v2) node, instead of simply specifying the image.

**Comment by drmaas** [comment]
Shelving - doing this will not have a performance benefit for booting instances, it would solely be to aid maintenance operations.

See https://github.com/target/clouddriver/tree/feature_instance_devicemapping

**Comment by lwander** [comment]
Closing because "wont-fix"
