### ISSUE TITLE
Incomplete Overview and Code Lab Documentation 

### ISSUE THREAD

**Issue by gogreen53** [spinnaker/spinnaker#1182]
The existing documentation under the "Overview" and various "Code Lab" pages on http://spinnaker.io do not contain any information on the project concept within spinnaker nor how spinnaker suggests handling setups with multiple cloud accounts for different environments or geographic regions.

Could we get some folks to update the documentation and make sure new feature work includes documentation before release?

Cheers

**Comment by ajordens** [comment]
Thanks for the feedback.

Your best bet for cloud provider-specific help is to reach out on the Spinnaker slack. We try our best to document where we can (_videos are forthcoming on our youtube channel_) but the project moves far faster than can be documented right now.

Cheers.
