### ISSUE TITLE
(Openstack) Cache refresh during shrink cluster pipeline takes 10+ minutes

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1209]
The "Force Cache Refresh" step in the "Shrink Cluster" pipeline stage takes 10+ minutes before succeeding.
Not sure if this is an orca or clouddriver issue.

**Comment by drmaas** [comment]
Is this repeatably slow? I believe that orca makes the cache refresh request to clouddriver, which should only take a few seconds to complete the actual refresh. It would be interesting to check the actual task id in clouddriver to see if it has completed while deck waits.

**Comment by SteveKMin** [comment]
I just ran it and it took a minute on our internal openstack environment, maybe it was just an environmental issue?
