### ISSUE TITLE
Add support for Kubernetes init containers

### ISSUE THREAD

**Issue by philsttr** [spinnaker/spinnaker#1214]
_Title_

Add support for Kubernetes [init containers](https://kubernetes.io/docs/user-guide/pods/init-container/)

_Cloud Provider_

Kubernetes

_Feature Area_

Kubernetes clouddriver, UI

_Description_

It would be nice to be able to configure [init containers](http://kubernetes.io/docs/user-guide/production-pods/#handling-initialization) when configuring a server group in Spinnaker.

Init containers were an alpha feature in kubernetes 1.3, and are a beta feature in kubernetes 1.4.

_Steps to Reproduce_

Create a new server group.  Expect to see an option to configure init containers.

**Comment by philsttr** [comment]
Note that if you don't want to support init containers until after they are officially supported by kubernetes (i.e. out of beta), then they could be configured in the meantime via annotations (#1106)

**Comment by lwander** [comment]
Implemented in above PR
