### ISSUE TITLE
Add support for Kubernetes configMap volume source

### ISSUE THREAD

**Issue by philsttr** [spinnaker/spinnaker#1215]
_Title_

Add support for Kubernetes configMap volume source

_Cloud Provider_

Kubernetes

_Feature Area_

Kubernetes cloud driver, UI

_Description_

It appears spinnaker currently only supports these kubernetes volume source types:
- EMPTYDIR
- HOSTPATH
- PERSISTENTVOLUMECLAIM
- SECRET

It would be great if the [configMap volume source](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_configmapvolumesource) was supported as well.

Bonus points would be to allow lookups of available configmaps, but that is not strictly required.

_Steps to Reproduce_

Create a new Server group using the kubernetes cloud driver.  Add a volume source.  Expect to be able to configure a configmap volume source.

**Comment by philsttr** [comment]
![image](https://cloud.githubusercontent.com/assets/7027966/19245554/a1298f8a-8ed6-11e6-9d0f-09e954c18245.png)

**Comment by lwander** [comment]
@danielpeach, the backend work is in - could you take care of the UI?

**Comment by philsttr** [comment]
@lwander / @danielpeach, any updates on UI support?
