### ISSUE TITLE
Spinnaker Deck Issue

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1224]
![deck_error](https://cloud.githubusercontent.com/assets/6929267/19291963/750b3276-8fcd-11e6-9cb1-bd7920a93cf9.png)

I did below step. My instance is Ubuntu 16.04 EC2 on AWS
1) Installed nodejs and npm
root@spin-control:~/deck# npm -v
3.10.3
root@spin-control:~/deck# nodejs -v
v6.7.0

2)git clone https://github.com/spinnaker/deck.git
  cd deck
  sudo npm install
  API_HOST=http://spin-gate:8084 sudo npm start

I checked that I am able to hit gate successfully. 
However when I try to hit deck it does not show me the Spinnaker main page, but just hungs up saying "hello!". Please find attached screenshot

3) Logs when I run the deck using " API_HOST=http://spin-gate:8084 sudo npm start"

chunk    {3} init.js (init.js) 0 bytes [rendered]

ERROR in ./app/scripts/modules/google/loadBalancer/loadBalancer.setTransformer.ts
Module build failed: A file specified in tsconfig.json could not be found: /home/ubuntu/deck/typings/index.d.ts
 @ ./app/scripts/modules/google/gce.module.js 2:20-73

ERROR in ./app/scripts/modules/core/application/service/applicationDataSource.registry.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/netflix.module.js 2:29-95

ERROR in ./app/scripts/modules/core/help/helpContents.registry.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/help/netflixHelpContents.registry.js 2:20-62

ERROR in ./app/scripts/modules/core/modal/wizard/v2modalWizard.service.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/serverGroup/wizard/serverGroupCommandConfigurer.service.js 4:21-71

ERROR in ./app/scripts/modules/core/delivery/executionBuild/buildDisplayName.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/delivery/delivery.module.js 2:24-75

ERROR in ./app/scripts/modules/core/forms/numberList/numberList.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/forms/forms.module.js 2:18-62

ERROR in ./app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/loadBalancer/loadBalancer.module.js 2:24-63

ERROR in ./app/scripts/modules/core/modal/wizard/v2modalWizard.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/modal/modal.module.js 2:21-64

ERROR in ./app/scripts/modules/core/modal/buttons/modalClose.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/modal/modal.module.js 6:18-59

ERROR in ./app/scripts/modules/core/presentation/anyFieldFilter/anyField.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/presentation/presentation.module.js 2:16-59

ERROR in ./app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/serverGroup/configure/serverGroup.configure.gce.module.js 2:35-112

ERROR in ./app/scripts/modules/google/loadBalancer/details/deleteModal/deleteModal.controller.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js 4:19-66

ERROR in ./app/scripts/modules/google/loadBalancer/configure/http/templates.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/loadBalancer/configure/http/createHttpLoadBalancer.controller.js 38:17-39

ERROR in ./app/scripts/modules/core/task/displayableTasks.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/core/stage.core.module.js 2:24-68

ERROR in ./app/scripts/modules/core/pipeline/config/stages/deploy/clusterName.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.module.js 2:19-50

ERROR in ./app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/config/applicationConfig.controller.js 2:35-97

ERROR in ./app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/config/applicationConfig.controller.js 4:25-81

ERROR in ./app/scripts/modules/core/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/modal/createApplication.modal.controller.js 4:39-109

ERROR in ./app/scripts/modules/core/application/service/applicationDataSource.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/service/applications.read.service.js 4:30-73

ERROR in ./app/scripts/modules/core/application/application.model.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/service/applications.read.service.js 5:19-50

ERROR in ./app/scripts/modules/core/delivery/status/executionUser.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/delivery/status/executionStatus.directive.js 2:21-54

ERROR in ./app/scripts/modules/core/delivery/details/executionDetailsSection.service.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/checkPreconditions/checkPreconditionsExecutionDetails.controller.js 2:31-95

ERROR in Path must be a string. Received undefined
webpack: bundle is now VALID.

**Comment by tomaslin** [comment]
I think we support only node 4 and 5

**Comment by anotherchrisberry** [comment]
Deck does not work with node 6.x - only 4.x or 5.x. Can you switch to an older version of node and try again?

**Comment by veeresh1982** [comment]
Ok let me try and update

**Comment by veeresh1982** [comment]
I tried for both 5 and 4 node version. Here are the details 

ubuntu@ip-172-16-3-124:~/deck$ nodejs -v
v5.12.0
ubuntu@ip-172-16-3-124:~/deck$ npm -v
3.8.6

ubuntu@spin-control:~/deck$ nodejs -v
v4.6.0
ubuntu@spin-control:~/deck$ npm -v
2.15.9

This time it does not give above error. It shows different error. 

It shows the spinnaker deck as just "Hello!" but does not still show the main page

PFA deck screenshot and error being displayed
![deck_error2](https://cloud.githubusercontent.com/assets/6929267/19321409/c8b1cefc-9069-11e6-82dc-8efba7d11440.png)

**Comment by danielpeach** [comment]
You'll get the `getEmitOutput` error if you don't have a `typings` folder.
Run `typings install` inside Deck's directory (if that doesn't work try `node_modules/typings/dist/bin.js`, or just install typings globally).
This is a post-install step inside Deck's `package.json`, but it may not have run if your npm install failed the first time (maybe because you were using node 6).

**Comment by veeresh1982** [comment]
I installed typings using "sudo npm install typings --global" and it shows up as installed
It gives below error now as below:

ERROR in ./app/scripts/modules/google/loadBalancer/loadBalancer.setTransformer.ts
Module build failed: A file specified in tsconfig.json could not be found: /home/ubuntu/deck/typings/index.d.ts
 @ ./app/scripts/modules/google/gce.module.js 2:20-73

ERROR in ./app/scripts/modules/core/application/service/applicationDataSource.registry.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/netflix.module.js 2:29-95

ERROR in ./app/scripts/modules/core/help/helpContents.registry.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/help/netflixHelpContents.registry.js 2:20-62

ERROR in ./app/scripts/modules/core/modal/wizard/v2modalWizard.service.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/netflix/serverGroup/wizard/serverGroupCommandConfigurer.service.js 4:21-71

ERROR in ./app/scripts/modules/core/delivery/executionBuild/buildDisplayName.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/delivery/delivery.module.js 2:24-75

ERROR in ./app/scripts/modules/core/forms/numberList/numberList.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/forms/forms.module.js 2:18-62

ERROR in ./app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/loadBalancer/loadBalancer.module.js 2:24-63

ERROR in ./app/scripts/modules/core/modal/wizard/v2modalWizard.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/modal/modal.module.js 2:21-64

ERROR in ./app/scripts/modules/core/modal/buttons/modalClose.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/modal/modal.module.js 6:18-59

ERROR in ./app/scripts/modules/core/presentation/anyFieldFilter/anyField.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/presentation/presentation.module.js 2:16-59

ERROR in ./app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/serverGroup/configure/serverGroup.configure.gce.module.js 2:35-112

ERROR in ./app/scripts/modules/google/loadBalancer/details/deleteModal/deleteModal.controller.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js 4:19-66

ERROR in ./app/scripts/modules/google/loadBalancer/configure/http/templates.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/google/loadBalancer/configure/http/createHttpLoadBalancer.controller.js 38:17-39

ERROR in ./app/scripts/modules/core/task/displayableTasks.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/core/stage.core.module.js 2:24-68

ERROR in ./app/scripts/modules/core/pipeline/config/stages/deploy/clusterName.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.module.js 2:19-50

ERROR in ./app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/config/applicationConfig.controller.js 2:35-97

ERROR in ./app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/config/applicationConfig.controller.js 4:25-81

ERROR in ./app/scripts/modules/core/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/modal/createApplication.modal.controller.js 4:39-109

ERROR in ./app/scripts/modules/core/application/service/applicationDataSource.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/service/applications.read.service.js 4:30-73

ERROR in ./app/scripts/modules/core/application/application.model.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/application/service/applications.read.service.js 5:19-50

ERROR in ./app/scripts/modules/core/delivery/status/executionUser.filter.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/delivery/status/executionStatus.directive.js 2:21-54

ERROR in ./app/scripts/modules/core/delivery/details/executionDetailsSection.service.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/home/ubuntu/deck/node_modules/ts-loader/index.js:432:33)
 @ ./app/scripts/modules/core/pipeline/config/stages/checkPreconditions/checkPreconditionsExecutionDetails.controller.js 2:31-95

**Comment by veeresh1982** [comment]
I used below to install 

/usr/bin/typings -> /usr/lib/node_modules/typings/dist/bin.js
/usr/lib
└── typings@1.4.0

**Comment by veeresh1982** [comment]
I guess it's an issue might be due to ubuntu 16.04 . I am going to try with Ubuntu 14.04

**Comment by veeresh1982** [comment]
Ok it worked in both 14.04 and 16.04 . I have to do below 

sudo npm install -g bower
sudo npm install typings --global
sudo typings install
sudo npm install ts-loader
sudo npm install typescript
sudo npm install
