### ISSUE TITLE
Destroy Server Group stage for Kubernetes should remove associated HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by philsttr** [spinnaker/spinnaker#1236]
*Title*

Destroy Server Group stage for Kubernetes does not remove associated HorizontalPodAutoscaler.  I believe it should.

*Cloud Provider*

Kubernetes

*Environment*

I'm running all spinnaker components on a local Ubuntu 14.04 vm to try it out.

```
# dpkg -l | grep spinnaker
ii  spinnaker                                             0.63.0-3                                            all          spinnaker
ii  spinnaker-clouddriver                                 1.361.0                                             all          spinnaker-clouddriver
ii  spinnaker-deck                                        2.844.0-3                                           all          spinnaker-deck
ii  spinnaker-echo                                        1.110.0-3                                           all          spinnaker-echo
ii  spinnaker-fiat                                        0.11.0                                              all          spinnaker-fiat
ii  spinnaker-front50                                     1.48.0-3                                            all          spinnaker-front50
ii  spinnaker-gate                                        2.79.0-3                                            all          spinnaker-gate
ii  spinnaker-igor                                        1.53.0-3                                            all          spinnaker-igor
ii  spinnaker-orca                                        1.230.0-3                                           all          spinnaker-orca
ii  spinnaker-rosco                                       0.60.0-3                                            all          spinnaker-rosco
```
*Feature Area*

Pipelines - Destroy Server Group Stage

*Description*

When a Server Group (i.e. ReplicaSet) has an associated HorizontalPodAutoscaler, I expect the Destroy Server Group stage to destroy the ReplicaSet AND the associated HorizontalPodAutoscaler.  Currently, it only destroys the ReplicaSet, and leaves the HorizontalPodAutoscaler dangling.

This can be particularly painful if the Destroy Server Group executes as part of a rollback flow.  Then the dangling HorizontalPodAutoscaler will create a naming conflict during the next pipeline execution, as detailed below.

*Steps to Reproduce*

Consider a pipeline like the following:

![image](https://cloud.githubusercontent.com/assets/7027966/19369953/a559bbfa-915d-11e6-8a58-8b41ae8e8da1.png)

Say, during the first pipeline execution:

The deploy stage executes, which creates a new ReplicaSet `foo-v002` and HorizontalPodAutoscaler also named `foo-v002`.  Then the rollback branch is taken, which removes ReplicaSet `foo-v002` but _does not remove_ the HorizontalPodAutoscaler `foo-v002`  (It is my expectation that it should remove this HorizontalPodAutoscaler).

Then, during the second pipeline execution:

The deploy stage executes, which creates a new ReplicaSet `foo-v002` and tries to create HorizontalPodAutoscaler also named `foo-v002`, but fails because the HorizontalPodAutoscaler with the name `foo-v002` still exists.

AFACT, there is no way to remove the HorizontalPodAutoscaler through spinnaker, so I must now go to kubernetes to remove it manually.

*Additional Information*
![image](https://cloud.githubusercontent.com/assets/7027966/19370176/ef5ba4ec-915e-11e6-9da0-7c9b346a5901.png)

**Comment by lwander** [comment]
Good catch
