### ISSUE TITLE
Front50 with S3 - fromt50 application failed to startup

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1244]
I am trying to run front50 with S3 on AWS as a separate micro service. If I enable only for cassandra with all details of it, it works. Seeing issue only with S3

Please find below front50.yml
-------------------------------------------------------------------------
`
server:
  port: 8080
cassandra:
  enabled: false
spinnaker:
  cassandra:
    enabled: false
  redis:
    enabled: false
  s3:
    enabled: true
    rootFolder: "some-rootname"
    bucket: "some-bucketname"
`
-------------------------------------------------------------------------

Error:
2016-10-17 21:19:08.799 ERROR 32479 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'awsS3Client' threw exception; nested exception is java.lang.NoSuchMethodError: com.amazonaws.http.AmazonHttpClient.disableStrictHostnameVerification()V

**Comment by ajordens** [comment]
Are you running the most recent release of `front50`?

**Comment by veeresh1982** [comment]
The front50 version I am using is : 1.49.0-3. Do you want me to try out with the latest version ?

**Comment by veeresh1982** [comment]
I will try with the latest version of front50 and update on the results

**Comment by veeresh1982** [comment]
I tried with latest version of front50 and able to run front50 microservice only with S3 details. Thanks
