### ISSUE TITLE
Spinnaker UI does not populate Ingress IPs field

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1263]
When I deploy spin-kube-demo application on K8s using Spinnaker, I could see that when I click the loadbalancer tab in Spinnaker it shows up the Loadbalancer type(LoadBalancer), Internal DNS Name, Cluster IP, Load Balancer IP all correctly but it does not display the Ingress IPs field value [ as shown in the attachment ]. 

I can see that when I do kubectl describe svc the output shows the correct value for field "LoadBalancer Ingress:"

So why is Spinnaker UI not showing up the Ingress IPs field populated in UI
![spinnaker ingress-ip](https://cloud.githubusercontent.com/assets/6929267/19700999/648bdd42-9aae-11e6-8b90-80575af9e3df.png)

**Comment by lwander** [comment]
@danielpeach  could you take a look at this?

**Comment by danielpeach** [comment]
I'm not able to recreate this bug. 

Can you please post more information about how you configured your load balancer / could you post the yaml for your service?

It would also be helpful to know if you're seeing any errors in your browser console.

**Comment by lwander** [comment]
A screen shot of the `edit` screen for that load balancer should be enough to replicate this.

**Comment by akrymets** [comment]
Perhaps it's not a bug - seems the AWS doesn't provide public IP for Load Balancers. Only public DNS-name. Try to look at the Load Balancers section inside you AWS account. It doesn't have explicit public IP

**Comment by veeresh1982** [comment]
So this ingress IPs will not be populated for AWS ? Is this how it is going to be for Spinnaker AWS deployments. Actually now when I deploy applications on AWS, I can see success, but now I need to click the load-balancer YAML file ( like attached in screenshot) to get the actual loadBalancer name and click in browser to see the application output.

![image](https://cloud.githubusercontent.com/assets/6929267/22666640/357efbe4-ec6e-11e6-9139-8c61c7dab86b.png)

**Comment by veeresh1982** [comment]
I used the latest deck version: v2.1000.0. 

Created a HTTP loadbalancer on AWS. I see now Ingress being populated in UI. 

However I do see it with https protocol set instead of http

https://a767d30eaf31211e6aea302548fde441-523055056.us-west-2.elb.amazonaws.com/ [ instead of http]

![image](https://cloud.githubusercontent.com/assets/6929267/22955348/728b462e-f2d0-11e6-817c-1ae96e96d5b7.png)
