### ISSUE TITLE
Deck is not showing application when deploying with docker-compose

### ISSUE THREAD

**Issue by tingzhang1210** [spinnaker/spinnaker#1282]
*Cloud Provider*

docker-compose local

*Environment*

ubuntu 14.04

*Feature Area*

UI

*Description*

The behavior you expect to see, and the actual behavior.
![image](https://cloud.githubusercontent.com/assets/20940338/19915603/9905f486-a0ee-11e6-9e14-30878d923ad3.png)

*Steps to Reproduce*

when use docker-compose up all the components, open up Deck UI, application not showing up

*Additional Details*

Additional information such as screenshots and exception logs.
here's the component up
~# docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
6b86e56717db        quay.io/spinnaker/gate:master          "/opt/gate/bin/gate"     17 hours ago        Up 17 hours         0.0.0.0:8084->8084/tcp   gate
341a20abe1fa        quay.io/spinnaker/orca:master          "/opt/orca/bin/orca"     17 hours ago        Up 17 hours         0.0.0.0:8083->8083/tcp   orca
2496d5a6b863        quay.io/spinnaker/igor:master          "/opt/igor/bin/igor"     17 hours ago        Up 17 hours         0.0.0.0:8088->8088/tcp   igor
9bbe638aa789        quay.io/spinnaker/fiat:master          "/opt/fiat/bin/fiat"     17 hours ago        Up 17 hours         0.0.0.0:7003->7003/tcp   fiat
da21208eb51a        quay.io/spinnaker/clouddriver:master   "/opt/clouddriver/bin"   17 hours ago        Up 17 hours         0.0.0.0:7002->7002/tcp   clouddriver
2d15d23bb9c2        quay.io/spinnaker/rosco:master         "/opt/rosco/bin/rosco"   17 hours ago        Up 17 hours         0.0.0.0:8087->8087/tcp   rosco
d9a587c81296        redis                                  "docker-entrypoint.sh"   17 hours ago        Up 17 hours         6379/tcp                 redis
80dc9439f6b8        quay.io/spinnaker/deck:master          "/bin/sh -c 'npm star"   17 hours ago        Up 17 hours         0.0.0.0:9000->9000/tcp   deck
9aa5f3d2b248        quay.io/spinnaker/front50:master       "/opt/front50/bin/fro"   17 hours ago        Up 17 hours         0.0.0.0:8080->8080/tcp   front50
e39bf7b0a460        quay.io/spinnaker/echo:master          "/opt/echo/bin/echo"     17 hours ago        Up 17 hours         0.0.0.0:8089->8089/tcp   echo

**Comment by robzienert** [comment]
Can you open the Inspector/Developer Tools and locate any network calls to gate (should be :8084) that are erroring out?

**Comment by tingzhang1210** [comment]
http://xx:8084/swagger-ui.html is okay
but when access http://xx:8084 will redirect to http://localhost:9000

**Comment by tingzhang1210** [comment]
using public ip during compose up, DOCKER_IP=<public ip> docker-compose up -d, now it working, thanks!

**Comment by emperorente** [comment]
hi,I encountered the same problem,what's means of public ip?

**Comment by mccricardo** [comment]
Still having this issue under Linux. Any insight?

**Comment by facewy** [comment]
what is pubilc ip，vm_host ip? i set DOCKER_IP=VM_HOSTIP, it doesn't work.
Can you share how did you fix this issue?
