### ISSUE TITLE
[Feature Request] Shared pipeline templates between applications

### ISSUE THREAD

**Issue by tony612** [spinnaker/spinnaker#1291]
*Cloud Provider*

For me, it's Kubernetes now.

*Feature Area*

Pipelines

*Description*

Now we can create pipeline using another pipeline as a template. But it will more convenient if there're templates between applications. For example, I want to set several special annotations/labels for pods of server groups in all applications so that our Prometheus system can scrape metrics from all pods in k8s. And I also want every container to expose a special port for the metrics endpoint. Writing all of these down in Wiki is not a good way, I think.

However, please point out if there's other way to achieve this. I'm open to other solutions 😁

**Comment by zakcrawford** [comment]
I would also appreciate this greatly.
I use spinnaker to deploy spinnaker and I set it up as 8 separate applications with 8 almost identical pipelines all belonging to one project. I ended up using the bulk API to set up the pipelines but it was more than annoying that at least within a 'Project' the pipeline templates did not exist.

I also think that some sort of global Pipeline template options would be quite helpful with encouraging standards and make adoption easier for engineers who are not familiar with Spinnaker.

**Comment by tomaslin** [comment]
might be worth investigating https://github.com/gogoair/foremast . We have some work in flux around Declarative Continous Delivery that will address pipeline re-use and re-assembly but it's still at the early stages

**Comment by zakcrawford** [comment]
@tomaslin I want to make pipeline creation and management a self-service operation that is as easy as possible. Checking pipelines into a git repository adds friction and negates a lot of the value that Spinnaker adds by having such a powerful UI and API. If I want to manage pipelines as code I could do that with the front50 batch APIs, and tbh if I followed that philosophy I'd be using Terraform or Cloudformation and not Spinnaker.

**Comment by tomaslin** [comment]
You can reuse pipeline across applications, etc using parameters - http://www.spinnaker.io/docs/pipeline-expressions-guide#section-pipeline-parameters . 

The combination that seems to work for teams here is to craft a pipeline skeleton with the important bits parameterized out, i.e, application name, cluster definition, labels, etc. This gives you a pop-up dialog when you run this manually.

You can also craft a completely new pipeline or combination of tasks and trigger off an api. I'm not sure there is much else to do here.

**Comment by zakcrawford** [comment]
The problem with the parameterized pipeline is that it still doesn't create a clear pattern for use across multiple applications, if I have 8 separate applications for the 8 spinnaker microservices (soon to be 9 with fiat) and I want to use the skeleton pipeline pattern, where do I create the skeleton pipeline? In a separate empty application?
Is that confusing?

It seems like having pipelines associated with a Project would solve this. I could create the 'master' pipeline under the Project, and then each Application could have a pipeline that executes the master pipeline with the appropriate parameters.

**Comment by lwander** [comment]
This should close this: https://github.com/spinnaker/pipeline-templates/blob/master/README.md
