### ISSUE TITLE
deck no longer lists accounts in 'new application'-dialog since upgrade

### ISSUE THREAD

**Issue by ineb** [spinnaker/spinnaker#1294]
i recently updated deck from v2.905.0 to latest (using quay.io images). latest ist not tagged right now on quay.io, but i think its corresponding to v.2.906.0 on github.

what happened is, that i no longer see any of my configured accounts when i try to create new applications. see the following screenshots for comparison:
latest (v.2.906.0):
![spinnaker_deck_latest](https://cloud.githubusercontent.com/assets/13886716/20180060/0ed80792-a759-11e6-9b93-e211de240ab2.png)

v2.905.0 
![spinnaker_deck_v2905](https://cloud.githubusercontent.com/assets/13886716/20180059/0ed7926c-a759-11e6-9b50-7a62bbcc5695.png)

i changed no other components during both screenshots. just spin-deck is changed, all other spinnaker components are running on latest.

i took a quick look and maybe 
https://github.com/spinnaker/deck/commit/6211a756bc905860421056ba76af881096e175e3
is responsible for it. but iam not sure.

**Comment by danielpeach** [comment]
I'm able to recreate this bug, and I'm not seeing it on the commit before spinnaker/deck@ 6211a75

@icfantv could you please take a look?

**Comment by icfantv** [comment]
@danielpeach yes, I will take a look
