### ISSUE TITLE
Stages Are Missing Input Fields for Kubernetes: (1) Shrink, (2) Scale Down

### ISSUE THREAD

**Issue by goldspin** [spinnaker/spinnaker#1295]
*Cloud Provider*

Kubernetes  (don't see how I can assign the label)

*Environment*

```I am running Spinnaker from Cloud Launcher on GCP.  I am using it to deploy a webapp docker image to GKE. ```

*Feature Area*

Pipelines, UI

*Description*

Please see the screenshot that I'm including here.  They are taken from a custom strategy, but is also present when trying to add the stages in a pipeline context.

This is important to support stop a server group first, before deploying a new server group.  This is necessary in the case where the server groups are assigned a static host port for configuring global load balancer in GCP.

shrink
![shrink](https://cloud.githubusercontent.com/assets/10765448/20186141/a40f3b9a-a723-11e6-8efc-e111934dc2c8.png)

scale down
![scale down](https://cloud.githubusercontent.com/assets/10765448/20186320/578e7b04-a724-11e6-9ba4-da7654f2c9a3.png)

*Steps to Reproduce*

- Create a new pipeline.
- Add a shrink stage.
- Add a scale down stage.

*Additional Details*
Please also make sure this works when creating a custom strategy.

Additional information such as screenshots and exception logs.

**Comment by lwander** [comment]
@danielpeach this seems to only be missing UI support. When you get a chance, can you look into this?

**Comment by lwander** [comment]
Closed by https://github.com/spinnaker/deck/pull/3008
