### ISSUE TITLE
Fiat should discount trailing spaces in group names

### ISSUE THREAD

**Issue by leelasharma** [spinnaker/spinnaker#1306]
While configuring the groupMembership for an application through deck, there was a stray trailing space which led to authorization failure. 
Fiat was configured to use GAFW  and google groups.
@ttomsu 

*Cloud Provider*
Kubernetes

*Feature Area*
UI, Fiat

**Comment by ttomsu** [comment]
Closing in lieu of https://github.com/spinnaker/fiat/issues/117
