### ISSUE TITLE
what about support Redis Cluster?

### ISSUE THREAD

**Issue by wangchangjian** [spinnaker/spinnaker#1317]
Now Redis server is single node, and more than 6 micro-services use redis cache and persist pipeline info,  is any plan to support redis cluster ?

**Comment by robzienert** [comment]
We run a separate Redis instance for each service that needs it, as well as read replicas. There's no immediate plans at Netflix to support Redis Cluster but we've discussed it a number of times to figure out a longer-term strategy. The main blocker to getting this done is that we use pipelines over multiple keys - refactoring these use cases would allow Cluster.

**Comment by lwander** [comment]
I think this is largely obsolete with the [dynomite](https://medium.com/netflix-techblog/introducing-dynomite-making-non-distributed-databases-distributed-c7bce3d89404) integration

**Comment by robzienert** [comment]
I think it'd still be useful to support, since Dynomite has a higher operational burden than Redis Cluster would. That said, Netflix likely won't be doing this work - but we'd be happy to talk with anyone that was interested in doing the legwork.
