### ISSUE TITLE
Colorblind friendliness

### ISSUE THREAD

**Issue by ismith** [spinnaker/spinnaker#1327]
*Feature Area*

UI + Pipelines

*Description*

Pipeline UI really wants you to be able to distinguish green from orange/yellow, which is tricky.  Using a pattern there, or an indicator arrow ("this is the active step, waiting for input") would be nice.  Screenshot below.

*Steps to Reproduce*

Create a pipeline that includes a manual judgement step; execute the pipeline but don't provide a judgement.

*Additional Details*
![image](https://cloud.githubusercontent.com/assets/172694/21065453/27495e2a-be15-11e6-9c06-6bc2b0caaa89.png)

**Comment by anotherchrisberry** [comment]
Thank you for calling this out! Our initial color palette was chosen with color-blind users in mind, but we didn't take that into consideration when we added this particular color.

We'll try to find another color that provides better contrast while still conveying the idea that the stage is awaiting judgment - or, if we can't find a good, friendly color, add an icon to the stage, as you suggested.

**Comment by anotherchrisberry** [comment]
We've added an indicator icon for manual judgment stages when they are awaiting user input.

(This happened a while ago, just remembered this ticket was around).
