### ISSUE TITLE
429 Too Many Requests on AWS Cloud Quick Start

### ISSUE THREAD

**Issue by juliole** [spinnaker/spinnaker#1340]
Cloud Provider:
AWS

Environment:
Standard deployment following:
https://s3.amazonaws.com/quickstart-reference/spinnaker/latest/doc/spinnaker-on-the-aws-cloud.pdf 

Feature Area:
UI

Description:
After installing spinnaker I am trying to follow: 
http://www.spinnaker.io/v1.0/docs/bake-and-deploy-pipeline
and after creating the application , I am not able to create security group and I keep getting errors like:
GET http://localhost:8084/credentials 429 Too Many Requests
GET http://localhost:8084/applications/jstest/serverGroups 429 Too Many Requests

AWS has API Gateway limits the request rates to 1000 requests per second across all APIs. I could try to increase it, but it must be something wrong on Spinnaker to make that many requests.
	
Steps to Reproduce:
I tried on different regions with same problem, so any AWS Cloud Quick Start should reproduce it.

**Comment by piyushk** [comment]
I just hit this myself. The cloudformation stack file used in that docs is launching an `m4.large` instance for spinnaker which doesn't have enough memory (8GB). The too many requests error is a red herring. Change that instance type to an `m4.xlarge` as the spinnaker docs suggest. I've been using an `r4.large` instance, and haven't seen any crashes of the JVE.

**Comment by juliole** [comment]
I changed to m4.xlarge and got the same problem.

**Comment by juliole** [comment]
I followed a manual install and is works. 
http://www.spinnaker.io/v1.0/docs/installing-and-running-spinnaker 
Some steps are missing on quick-starter

**Comment by robzienert** [comment]
Try looking at the logs of gate and clouddriver. If it isn't an issue of not having enough resources, the logs will be able to point you in a more concrete direction.

**Comment by juliole** [comment]
I got it to work. It looks like we get error 429 for any authentication related issue and it does not mean "too many requests". The following changes were need:
http://stackoverflow.com/questions/34788034/unable-to-create-an-application-no-accounts-listed-in-dashed-rectangle-beside
https://github.com/spinnaker/spinnaker/issues/1001
Thanks

**Comment by lwander** [comment]
Closing since the stackoverflow link seems to have an answer
