### ISSUE TITLE
Reconfigure_spinnaker.sh doesn't configure OpenStack in settings.js

### ISSUE THREAD

**Issue by varikin** [spinnaker/spinnaker#1342]
The `scripts/reconfgure_spinnaker.sh` should configure OpenStack as a provider in `settings.js`. This was done manually in the Deck repo for development. It needs to be done in the Spinnaker repo as well for deployment.

**Comment by ewiseblatt** [comment]
Contact me if you need help with this.

**Comment by varikin** [comment]
Oh! I had this done and forgot about it over the holiday. I just opened https://github.com/spinnaker/spinnaker/pull/1362.

**Comment by varikin** [comment]
This was fixed with #1362
