### ISSUE TITLE
how did netflix manage the config files(for mirco services)

### ISSUE THREAD

**Issue by emperorente** [spinnaker/spinnaker#1344]
at #732 i see,netflix have each service deployed within it's own cluster（nine services）,
I want to know how you manage the configuration file，Whether they are managed independently(in ervery service directory include a config file like igor.yml) or unified by a configuration file(just like spinnaker-local.yml,all of the services use it)

**Comment by cfieber** [comment]
@ajordens has a good blog post on how we deal with this:
https://medium.com/@ajordens/scaling-spinnaker-at-netflix-custom-features-and-packaging-e78536d38040#.kailu8f8t
