### ISSUE TITLE
Artifact handling in spinnaker

### ISSUE THREAD

**Issue by gardleopard** [spinnaker/spinnaker#1348]
Artifacts in spinnaker is currently files like ie. rpm and debian packages. We have decided to make the scope of artifacts in spinnaker bigger and the definition more precise. 

Artifacts from igor have got the following format now:
```
"artifacts": [
{
"displayPath": "spinnaker-igor_1.54.0.224.692755-3_all.deb",
"fileName": "spinnaker-igor_1.54.0.224.692755-3_all.deb",
"relativePath": "spinnaker-igor_1.54.0.224.692755-3_all.deb"
}
]
```

The new format will be:
```
"artifacts": [
{
"type": "deb",
"name"" "spinnaker-igor",
"version": "1.54.0.224.692755-3_all",
"reference": "schibsted-igor_1.54.0.224.692755-3_all.deb"
}
]
```

This means that the producers of artifacts into spinnaker needs to know the details about the artifacts, while the consumers in spinnaker does not need to know the details of artifacts. Which will make it easier to add support for new artifact types in spinnaker.

Increasing the scope of artifacts means that artifacts will not only be files any more. Deployable things like docker containers or amis are also artifacts and can be represented with the new artifact format.

Ami example:
```
"artifacts": [
{
"type": "ami",
"name"" "spinnaker-igor",
"version": "1.54.0.224.692755-3_all",
"reference": "ami-432662"
}
]
```

This will enable us to be more explicit on what we want to deploy. For example triggering two bakes in parallel `service-backend` and `service-frontend`, and go for serialised deployments with `service-backend` deployed before `service-frontend`. Because we have `name` and `type` for all artifacts, it will be easy to configure and understand.

The rollout of this change is going to take a while. We need to add the rich artifact data to every producer of artifacts and keep the old format support as well. The consumers needs to test for the new artifact format and use that if it its available or fall back to the old logic if its not available.

**Comment by lwander** [comment]
I think this is safe to close...

**Comment by diasjorge** [comment]
Thank @gardleopard this is the only place, I've seen explained how to pass deb packages as artifacts. It's nowhere in the docs :(

**Comment by gardleopard** [comment]
Nice, would probably be nice with an update in the docs then:) Nice to see you @diasjorge !

**Comment by diasjorge** [comment]
Ok you got it :) https://github.com/spinnaker/spinnaker.io/pull/279
