### ISSUE TITLE
GCE my-kubernetes-account failed: Unauthorized

### ISSUE THREAD

**Issue by grandmore** [spinnaker/spinnaker#1349]
I just upgraded spinnaker on a new cluster on GCE, running inside Kubernetes, and it will not authorise complaining with:

```com.netflix.spinnaker.clouddriver.kubernetes.deploy.exception.KubernetesOperationException: Get Namespaces for account my-kubernetes-account failed: Unauthorized! Token may have expired! Please log-in again.```

If I log into the clouddriver pod I can check the credentials file at ``` cat ~/.kube/config``` and the auth details are there.

I have tried lots of approaches but to no avail. Is this a known bug of am missing something?

I have an older version running fine on a different cluster.

**Comment by danielpeach** [comment]
If you have not already done so, please try the fix documented here: 
http://www.spinnaker.io/docs/troubleshooting-guide#section-my-gke-google-container-engine-cluster-isn-t-showing-up-as-a-kubernetes-account-

**Comment by grandmore** [comment]
@danielpeach Thanks for the suggestion.

I have eventually tracked it down to be the simplest issue. IAM api was not enabled. 

Perhaps the docs could specify what apis need to be activate in order to work.

Thanks.

**Comment by improvebartek** [comment]
@grandmore I seem to have the same error while trying to run spinnaker on my GCE kubernetes cluster. By "IAM api was not enabled." did you mean Google Identity and Access Management (IAM) API in the API manager?

**Comment by improvebartek** [comment]
ok, thanks to the help from slack the solution was to do: `gcloud config set container/use_client_certificate true` based on http://www.spinnaker.io/docs/troubleshooting-guide

**Comment by lwander** [comment]
Closing since this is resolved with the above troubleshooting guide
