### ISSUE TITLE
Can't delete hung pipeline

### ISSUE THREAD

**Issue by sheinbergon** [spinnaker/spinnaker#1353]
Hung pipelines ( i.e. Jenkins job finsihed but spinnaker still waits for it to finish ) are found and can't be deleted.

*Cloud Provider*

AWS

*Environment*

Spinnaker version - 0.69.0-3 , Orca version -  1.282.0-3 , Gate version - 2.99.0-3
Orca persistence is to Redis ElasticCache

*Feature Area*

Pipelines,UI,Jenkins,Orca

*Description*

Deleting pipelines , even hung ones, should succeed. Instead the request seems to hang indefinitely 

*Steps to Reproduce*

Most of the times, pipeline execution do not halt. On very specific scenarios we get these hung pipelines. That never make beyond one of the steps of the pipeline because they "think" it's still running. In this case, we had one step pipeline consisting of jenkins job. Even though the jenkins job finished within 13 seconds, the spinnaker thought it was still running. Never the less, we should be able to at least delete such pipelines via the UI.

*Additional Details*

Hitting the cancel button sends the a "cancel" PUT request to the gate service. Looking inside its logs, we can see the following line :

```
2016-12-28 18:38:10.309  INFO 11210 --- [hystrix-tasks-9] c.n.s.g.services.internal.OrcaService    : ---> HTTP PUT http://127.0.0.1:8083/pipelines
/ef5599e9-cf7b-4639-8fe9-d209541f7564/cancel
2016-12-28 18:38:10.318  INFO 11210 --- [hystrix-tasks-9] c.n.s.g.services.internal.OrcaService    : <--- HTTP 202 http://127.0.0.1:8083/pipelines/ef5599e9-cf7b-4639-8fe9-d209541f7564/cancel (8ms)
```

And nothing more ( the orca logs , doesn't even say anything about it )
We have to delete the matching pipeline id from redis (pipeline:ef5599e9-cf7b-4639-8fe9-d209541f7564)
in order to get rid of it

Any ideas ?

**Comment by vbarba** [comment]
Same here, we had to delete the pipeline id manually using the redis-cli because the pipeline won't stop...
