### ISSUE TITLE
Add an entrypoint to orca to expose number of active workflows.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#1394]
This would allow reaper logic to easily determine which instances are no longer active.

As a point of reference Rosco has:
https://github.com/spinnaker/rosco/blob/master/rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/InstanceStatusEndpoint.groovy
and
https://github.com/spinnaker/rosco/blob/master/rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/AllStatusEndpoint.groovy

**Comment by robzienert** [comment]
In the meantime, this is an option for ad-hoc investigation of orca execution status (although it's obviously not ideal, nor a resolution to this issue): https://github.com/robzienert/orca-executions

**Comment by robzienert** [comment]
Relevant PRs: https://github.com/spinnaker/orca/pull/1173 and https://github.com/spinnaker/gate/pull/333

**Comment by robzienert** [comment]
* Orca 1.336.0
* Gate 3.4.0
