### ISSUE TITLE
#stage('stage') helper always returning false for stage attributes

### ISSUE THREAD

**Issue by leandrocmaia** [spinnaker/spinnaker#1396]
Somehow my evaluation expression always returns false and I don't know why. 

I have two check preconditions to each status but both fail no matter the json result.

![screenshot from 2017-02-01 18-35-15](https://cloud.githubusercontent.com/assets/385715/22518527/326eed16-e8ad-11e6-9130-c987f3f67925.png)

Succeeded stage Expression: ${#stage('Acceptance')['status'] == 'SUCCEEDED'}
Rollback stage Expression: ${#stage('Acceptance')['status'] == 'FAILED_CONTINUE'}

This is how it is configured:

![screenshot from 2017-02-01 18-32-51](https://cloud.githubusercontent.com/assets/385715/22518440/deb68ad0-e8ac-11e6-83c6-30054334c1fa.png)

The source json:

```
"name": "Acceptance",
      "parentStageId": null,
      "refId": "5",
      "requisiteStageRefIds": [
        "2"
      ],
      "scheduledTime": 0,
      "startTime": 1485969178240,
      "status": "SUCCEEDED",
```

Tried it in all other possible ways: 

```
${#stage('Acceptance')['status'] == 'SUCCEEDED'}
${stages[5]['status'] == 'SUCCEEDED'}
${executor.stages[5]['status'] == 'SUCCEEDED'}
${executor.stages.?[name == 'Acceptance'][0]['status'] == 'SUCCEEDED'}
```
None of them seem to work. Any help? Thanks.

**Comment by leandrocmaia** [comment]
I tried using the context path and worked:

`${#stage('Acceptance')['context']['buildInfo']['result']=='SUCCESS'}`

Seems like the #stage() helper only makes the 'context' path accessible, not the stage attributes as it is written in the docs:

> OTHER STAGES
> You can also access the value of other stages by doing a lookup by name using the #stage( stage name ) helper method. To access stage attributes, you can call ${ #stage('stage name')['id']}. To access the values passed into the stage, use ${ #stage('stage name')['context']['baseAmiName']}.
> 

In my case it is satisfactory to check the build status, but if I needed to check another stage that is not a Jenkins Job it would not be possible.

**Comment by lwander** [comment]
Closing since it seems you found the answer - feel free to reopen though

**Comment by Pamir** [comment]
Hi @leandrocmaia 
You can actually access all the manifest variables.
${ #stage('Find Artifacts From Resource (Manifest)')['context']['manifest']['metadata']['labels']['app'] }
