### ISSUE TITLE
Server group with no load balancer shows up as disabled

### ISSUE THREAD

**Issue by matthewrj** [spinnaker/spinnaker#1401]
Cloud provider: Kubernetes

Environment: Spinnaker running on GCP, used to deploy to GKE cluster.

Feature Area: UI

Description:
When a server group is created that does not need a load balancer (in my case it subscribes to messaging layer and writes to a DB), it always shows up as disabled. It would be better if server groups with no load balancers were always enabled.

Steps to Reproduce:
Create a server group with no attached load balancer.

**Comment by lwander** [comment]
Seems reasonable - are you asking for cosmetics, or is there a deeper reason for this change?

**Comment by matthewrj** [comment]
Cosmetics. As long as it doesn't break the functionality of any of the deployment strategies.

**Comment by lwander** [comment]
https://github.com/spinnaker/clouddriver/releases/tag/v1.527.0
