### ISSUE TITLE
Not able to create security group and cluster in GCP

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#1402]
When creating a security group from an application on a GCP environment the task fails with the following error:

Exception: Can not deserialize instance of java.lang.String out of START_OBJECT token at [Source: N/A; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.clouddriver.google.deploy.description.UpsertGoogleSecurityGroupDescription["sourceRanges"]->java.util.ArrayList[0])

*Environment* GCP

ii  spinnaker                          0.75.0-3                          all          spinnaker
ii  spinnaker-clouddriver         1.499.0                           all          spinnaker-clouddriver
ii  spinnaker-deck                   2.968.0-3                         all          spinnaker-deck
ii  spinnaker-echo                   1.130.0                           all          spinnaker-echo
ii  spinnaker-fiat                     0.20.0                            all          spinnaker-fiat
ii  spinnaker-front50              1.70.0                            all          spinnaker-front50
ii  spinnaker-gate                   3.2.0                             all          spinnaker-gate
ii  spinnaker-igor                   1.61.0                            all          spinnaker-igor
ii  spinnaker-orca                  1.312.0                           all          spinnaker-orca
ii  spinnaker-rosco                 0.81.0                            all          spinnaker-rosco

**Comment by duftler** [comment]
This issue was reported in #1392 and the fix was released in Deck 2.981.0. Please update your deck service to the latest to pick up the fix. We'll get an updated Cloud Launcher image posted as well.
```
sudo service spinnaker stop
sudo apt-get upgrade
sudo dpkg -l | grep spinnaker
sudo service spinnaker start
```
