### ISSUE TITLE
Ingress UI - Spinnaker on AWS

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1428]
I used the latest deck version: v2.1000.0. 

Created a HTTP loadbalancer on AWS. I see now Ingress being populated in UI. 

However I do see it with https protocol set instead of http

https://a767d30eaf31211e6aea302548fde441-523055056.us-west-2.elb.amazonaws.com/ [ instead of http]

![image](https://cloud.githubusercontent.com/assets/6929267/22955348/728b462e-f2d0-11e6-817c-1ae96e96d5b7.png)

**Comment by anotherchrisberry** [comment]
I'm guessing this line is the culprit:
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/loadBalancer/details/details.html#L107

I'm assuming you're accessing Deck itself via HTTPS?

This is a problem throughout the load balancer details - not just for kubernetes. We're cheating a bit and assuming the protocol Deck uses is the same as the load balancer...

**Comment by veeresh1982** [comment]
Yes! we are accessing deck with https

**Comment by veeresh1982** [comment]
Can we have that taken care based on PORTS->name or port used. In this case name(http) and port(80) is being used

**Comment by veeresh1982** [comment]
@ anotherchrisberry, @lwander , @danielpeach : Can you suggest me here if they will be some code changes to handle above comment from Chris.  Thanks!

**Comment by anotherchrisberry** [comment]
@veeresh1982 this should be fixed by https://github.com/spinnaker/deck/pull/3331, which is included in https://github.com/spinnaker/deck/releases/tag/v2.1012.0

**Comment by veeresh1982** [comment]
Thanks @anotherchrisberry : I tested the version and it looks good.

**Comment by veeresh1982** [comment]
I am testing for Azure k8s and it seems it is taking Ingress differently for Azure where we have an IP and should be http instead of https

AWS Ingress:http://adf6da5275baf11e7a95202adcba9ba3-307409616.us-west-2.elb.amazonaws.com/ <looks fine>
Azure Ingress:https://52.160.102.212/  < should be http instead of https, based on the protocol>

So fix we had for AWS should be done for Azure/<ingressp.ip  related ?
