### ISSUE TITLE
ChaosMonkey Deck issue

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1451]
I am running Spinnaker Deck on AWS EC2 instance with the version: 2.958.0

I updated  /root/deck/settings.js file to have below feature added and restarted the deck service
chaosMonkey: true,

However I don't see any ChaosMonkey option enabled in Deck UI  (once we create a new application)

**Comment by anotherchrisberry** [comment]
Can you verify the feature flag is being set? If you look at the settings.js file in your browser, is it in there at the bottom?

**Comment by veeresh1982** [comment]
Correct. I was able to get it working now with this troubleshooting from browser . Thanks!
