### ISSUE TITLE
Unable to install Rosco due to invalid postint script

### ISSUE THREAD

**Issue by jrbury** [spinnaker/spinnaker#1462]
The Rosco deb package contains an invalid postinstall script which prevents it from being installed.

GCE

Ubuntu 14.04.5 LTS

In Rosco 0.91.0, specifically this [commit](https://github.com/spinnaker/rosco/commit/47273753a7fe7eb6804b83ddbaf47554f50ce3f8), the post install script was updated to include installing packer. This also included the addition of adding an [apt-get install](https://github.com/spinnaker/rosco/blob/master/rosco-web/pkg_scripts/postInstall.sh#L22) which causes the install of the deb to fail.

This is the result of an attempted install of the latest version (NOTE: I modified the postinst script to add -x to the shebang so I could be sure where it was failing).

```
root@prod-spinnaker-dyvx:~# dpkg --configure -a
Setting up spinnaker-rosco (0.92.0) ...
+ getent group spinnaker
+ [ -z spinnaker:x:1013: ]
+ getent passwd spinnaker
+ [ -z spinnaker:x:1013:1013::/home/spinnaker: ]
+ install_packer
+ PACKER_VERSION=0.12.1
+ packer --version
2017/03/06 18:25:36 [INFO] Packer version: 0.12.2
[...]
2017/03/06 18:25:36 Setting cache directory: /packer_cache
2017/03/06 18:25:36 waiting for all plugin processes to complete...
+ local packer_version=0.12.2
+ local packer_status=0
+ [ 0 -ne 0 ]
+ [ 0.12.2 != 0.12.1 ]
+ mktemp -d installrosco.XXXX
+ TEMPDIR=installrosco.zDhF
+ cd installrosco.zDhF
+ wget https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip
--2017-03-06 18:25:36--  https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip
Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.193.183, 151.101.1.183, 151.101.129.183, ...
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.193.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10422895 (9.9M) [application/zip]
Saving to: ‘packer_0.12.1_linux_amd64.zip’
[...]
2017-03-06 18:25:37 (15.8 MB/s) - ‘packer_0.12.1_linux_amd64.zip’ saved [10422895/10422895]

+ apt-get install unzip -y
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
dpkg: error processing package spinnaker-rosco (--configure):
 subprocess installed post-installation script returned error exit status 100
Errors were encountered while processing:
 spinnaker-rosco
```

The fix is to simply remove the `apt-get install unzip -y` line from postint and adding `unzip` to the `Depends` field for Rosco. 

I'll try and find how to do this with the gradle build and submit a PR but someone more familiar with the gradle build will be able to do it much quicker.

**Comment by jtk54** [comment]
We're trying to install `unzip` while installing `rosco`, so there is a `dpkg` deadlock. I need to add `unzip` as a dependency to rosco and get rid of the line installing `unzip`. PR incoming.
