### ISSUE TITLE
Kube UI link text and url in the instance details shows account name instead of instance name

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spinnaker#1466]
*Title*

Kube UI link text and url in the instance details shows account name instead of instance name.

*Cloud Provider*

Kubernetes

*Environment*

Running docker-compose and deploying to Kubernetes

*Feature Area*

Instance information in the Cluster view of Deck.

*Description*

Expected:
In the instance information panel for a Kubernetes server group, the Kube UI link should show the name of the instance and link to that instance in the Kubernetes UI.  

Actual:
It shows the name of the  account and the account name is in the link URL as well, making it invalid.

![](https://www.evernote.com/l/AAFniNQvkYhB66S7VsYY2afDZpgflylIjYsB/image.png)

*Steps to Reproduce*

Using a build of Gate from the master branch, deploy a server group to a Kubernetes account and view the instance information panel in the Clusters view. 

*Additional Details*

This appears to have been introduced to master several days ago with the commit https://github.com/spinnaker/gate/commit/afc3816f0c336db2a73bb69646d8986e1132d0eb.  By merging the account into the instance, any fields in account with the same name as a field in the instance will overwrite the instance.  For Kubernetes both the account and the instance happen to have a "name" field.

**Comment by danielpeach** [comment]
Thanks @willgorman. The Gate issue you recognized was resolved here: https://github.com/spinnaker/gate/pull/364 and was released in Gate 3.18.0.

I've just verified that the UI now shows the instance name, and that the link URL uses the instance name instead of the account name.
