### ISSUE TITLE
"UDF" for Google Cloud Platform

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#1505]
Description: In AWS and Openstack we are able to define a UDF template for a common set of userdata we can pull from the pipeline information.

There has been discussion on making this generic in this issue, https://github.com/spinnaker/spinnaker/issues/1274 but I'm hoping to open this issue, and get it done at least with regards to Google.

For AWS and example UDF file is as below:

```
CLOUD_ACCOUNT="%%account%%"
CLOUD_ACCOUNT_TYPE="%%accounttype%%"
CLOUD_ENVIRONMENT="%%env%%"
CLOUD_SERVER_GROUP="%%group%%"
CLOUD_CLUSTER="%%cluster%%"
CLOUD_STACK="%%stack%%"
CLOUD_DETAIL="%%detail%%"
EC2_REGION="%%region%%"
```

**Comment by lwander** [comment]
https://github.com/spinnaker/clouddriver/pull/1639
