### ISSUE TITLE
Kubernetes accounts are expected to match /a-zA-Z0-9/

### ISSUE THREAD

**Issue by ismith** [spinnaker/spinnaker#1515]
*Cloud Provider*

Kubernetes

*Description*

When I use an account containing a '.' (e.g., 'k8s.ismith'), GET /gate/credentials/k8s.ismith 404s.  If I change it to k8sismith, it 200s.

It'd be nice if this were enforced somehow - perhaps requiring it to match a regex on clouddriver startup, if there's a reason '.' is disallowed; making GET /gate/credentials/{account} route properly if there isn't.

**Comment by lwander** [comment]
Enforced by [Halyard](https://github.com/spinnaker/halyard) now
