### ISSUE TITLE
Deck - Missing Pagination buttons from applications page

### ISSUE THREAD

**Issue by jrbury** [spinnaker/spinnaker#1531]
Currently running Deck 2.1061.0 on GCP and the pagination buttons are not displaying on the applications page (chrome, safari, firefox). There are no console errors and the `uib-pagination` element just contains no elements.

From my testing this was introduced in deck 2.1058.0 (upgrade from angular 1.5 -> 1.6)

I confirmed this by the following steps

```
apt-get install spinnaker-deck=2.1058.0
/opt/spinnaker/bin/reconfigure_spinnaker.sh
service apache2 restart
```

This results in no pagination buttons on the applications page in all browsers

```
apt-get install spinnaker-deck=2.1057.0
/opt/spinnaker/bin/reconfigure_spinnaker.sh
service apache2 restart
```

Fixes this and the buttons are visible again.

Let me know if you need me to grab any additional information.

**Comment by anotherchrisberry** [comment]
Thanks for catching this - should be fixed in 2.1062.0.
