### ISSUE TITLE
Spinnaker ./InstallSpinnaker.sh does not work on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kkapelon** [spinnaker/spinnaker#1544]
**Title:** The install scripts works only on Ubuntu 14.x and nothing else
**Cloud provider:** None
**Environment:** Ubuntu 16.04 LTS 64 bit (under Virtualbox in Windows 10)
**Feature area:** Installation

I downloaded the install script locally and examined it to see what it does (as I always do with these scripts that need root access). I saw the message that says "we require 14.04 or higher" and I assumed that I was good to go.

Unfortunately the installation script fails

1.  It tries to install package python-support that exists in Ubuntu 14.x but not in 16.x
2.  It tries to downgrade Cassandra to 2.x while Ubuntu 16.x comes with 3.x

I manually installed python-support and also tried with ./InstallSpinnaker.sh --noinstall_cassandra
This failed as well with error message

```
0 to upgrade, 0 to newly install, 0 to remove and 316 not to upgrade.
~/spin/spinnaker/installspinnaker.kynf/packer ~/spin/spinnaker
~/spin/spinnaker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package spinnaker
```

I found out that  there is indeed no package for xenial at
https://dl.bintray.com/spinnaker/debians/dists/
Only trusty packages are offered.

**Steps to reproduce**
Run `./InstallSpinnaker.sh --noinstall_cassandra` in Ubuntu 16.04 LTS

**Expected result**

1. Either have Spinnaker installed OR
2. get a message that Ubuntu 16.x is not supported

I think that the installation script should be modified and rather than a "less than" check, perform an "exactly like" 14.x check.

Documentation pages of Spinakker should also be updated to say that Ubuntu 14.x is the only version supported and newer versions will not work (even LTS ones)

**Actual Result**

Spinnaker packages are not available for Ubuntu Xenial

**Comment by ewiseblatt** [comment]
@lwander would halyard work?

**Comment by lwander** [comment]
No, the install Halyard script has the same problem: https://github.com/spinnaker/halyard/issues/279

**Comment by lwander** [comment]
We aren't publishing our spinnaker packages with the Xenial distribution enabled. @jtk54 might have some ideas on how to fix this.

**Comment by jtk54** [comment]
@kkapelon As you've noticed, our debian repos don't have a `xenial` distribution. Can you manually curl and install that deb so we can verify that Spinnaker runs on xenial or at least get an understanding for how far off we are? This is the first step for 16.04 support.

**Comment by istolga** [comment]
+1 for Ubuntu16 support

**Comment by kkapelon** [comment]
I downloaded the deb packages manually. First of all, I do not understand the distinction between the <service> and spinnaker-<service> packages. For example there is a rosco package and a spinnaker-rosco package, a clouddriver and a spinnaker-clouddriver package and so on.

I installed spinnaker_0.9.0-3_all.deb and all the dependencies it asked (which were the <service-name> packages). The packages installed without errors. I kept cassandra at version 3.x

However starting spinnaker fails because of an unknown **services.docker.baseUrl** property. I am attaching the full log.

[spinnaker-launch-error.zip](https://github.com/spinnaker/spinnaker/files/911631/spinnaker-launch-error.zip)

**Comment by jtk54** [comment]
@kkapelon The {service} packages are old and deprecated, while the spinnaker-{service} packages are up-to-date. Having said that, we have a 'wrapper' package `spinnaker` that declares dependencies on the other packages. You should install the `spinnaker` package at the latest version 0.79.0: https://bintray.com/spinnaker/debians/spinnaker.

Also note that Cassandra is no longer supported, but we do have support for a few bucket storage systems (s3, GCS, etc).

**Comment by mdelapenya** [comment]
I had to install `python-support` manually to install cassandra:

```
wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb
```

Now I'm stuck in here:
```
W: --force-yes is deprecated, use one of the options starting with --allow instead.
cassandra set on hold.
cassandra-tools set on hold.
Retrying...
Retrying...
Retrying...
Retrying...
Retrying...
```

**Comment by mdelapenya** [comment]
Downgraded my box to Ubuntu 14.04 and everything worked as expected

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker-gradle-project/pull/30

**Comment by sirajmansour** [comment]
@mdelapenya i'm having the same problem on 14.04 running inside a docker container on windows

**Comment by wawastein** [comment]
Hello, we still cannot use repository with latest 16.04 LTS release. This is pretty inconvenient.

**Comment by kalaiganeshan** [comment]
Hi, I am trying to setup spinnaker with kubernetes on ubuntu 1.14 [ As kubernetes doesnt not support ubuntu 1.16 ]. But kubernetes expects ubuntu version to be 1.16 and above . So how can I install spinnaker with kubernetes? Can anyone help ?

**Comment by christophetd** [comment]
Any updates? I'm running into the same issue with Ubuntu 16.04 LTS.

**Comment by consueloel** [comment]
I have the same issue, hope this gets worked on soon

**Comment by sebadiaz** [comment]
+1

**Comment by lmeadows** [comment]
+1

**Comment by decker502** [comment]
+1

**Comment by Subaru365** [comment]
+1

**Comment by brandonnelson3** [comment]
Taking a look.

**Comment by brandonnelson3** [comment]
@Subaru365 Did you have an issue with the script? Which script did you use? Can you send me the log you received?

**Comment by Subaru365** [comment]
@brandonnelson3 I used this InstallHalyard.sh (https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh)

It outputted same error message.
```
Installing Halyard...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package spinnaker-halyard
```

Environment: ubuntu:16.04 (docker image)

**Comment by brandonnelson3** [comment]
@Subaru365 So we are only deploying debian packages for the other services in Spinnaker for 16.04. Luckily you can use a different script to install halyard instead on 16.04 via the jars directly instead of the debian package.

https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh is the InstallHalyard.sh you are looking for. I'll send a PR tomorrow to add some docs for it.

**Comment by brandonnelson3** [comment]
For parity:

I sent https://github.com/spinnaker/spinnaker.github.io/pull/502 which updates docs and https://github.com/spinnaker/halyard/pull/806 to prevent a situation if a user on 14.04 runs both scripts on the same machine.
