### ISSUE TITLE
Expressions aren't working for custom notifications

### ISSUE THREAD

**Issue by tonyjchong** [spinnaker/spinnaker#1545]
*Title*
Expressions aren't working for custom notifications

*Cloud Provider*

Kubernetes on AWS

*Environment*

I am running Kubernetes 1.5.2 on top of AWS. Used spinnaker's experimental scripts to launch the services as containers.

*Feature Area*

Notifications

*Description*

My main issue is that I cannot get the expressions to in my notifications to Slack. Everything works fine, deployments, the slack integration, just the expressions don't interpolate. All I want to do is capture some information from the deployment and place them into the slack notification. 

I have several deployments that either initiate on a trigger via Docker hub, or a manual deployment using a drop down to pick my version of the containers.

When using custom notifications, I've tried a variety of combos like this:

![2017-04-06_1502](https://cloud.githubusercontent.com/assets/1631917/24777402/0f248d2a-1ada-11e7-8d53-61d0cb2b4ee6.png)

All my notifications end up like this:

![2017-04-06_1503](https://cloud.githubusercontent.com/assets/1631917/24777425/338cbc96-1ada-11e7-8946-7eff3d8b91ae.png)

I've tried doing things like adding custom comments like `${trigger['tag']}` and then adding `${#stage('Deploy in stage')['context']['comments']}` to the notification and even that doesn't work.

![2017-04-06_1506](https://cloud.githubusercontent.com/assets/1631917/24777541/a83ad424-1ada-11e7-99ca-3bb3b4e31149.png)

The helper function is working as you can see here:
![2017-04-06_1508](https://cloud.githubusercontent.com/assets/1631917/24777583/e01572e6-1ada-11e7-8d0c-349cd3112f7b.png)

Thanks a lot. This has been a thorn in my side for about a month.

**Comment by duftler** [comment]
The dialog in your screen grab looks to be the application-level notification preferences (that is, the settings that apply to all pipelines).

Can you please try configuring some of your expressions using pipeline-level notifications?

I've experimented with this a bit, and I see behavior similar to what you are reporting; but only when using the application-level settings. I want to make sure we've isolated the issue before we dig deeper.

Expressions seem to work fine for me via email and slack when configured directly on the pipelines or stages.

I'm testing on GCE, but this really shouldn't make any difference in this case (especially since I was able to reproduce the behavior).

**Comment by tonyjchong** [comment]
That was exactly it. Pipeline notifications over application level notification.s

<img width="510" alt="2017-04-06_1629" src="https://cloud.githubusercontent.com/assets/1631917/24779595/48f2e41e-1ae6-11e7-85cf-6c641c55546d.png">

Thank so much @duftler I truly am grateful!

**Comment by duftler** [comment]
Cool. Will look into a fix for expressions in application-level notifications, since that should work too.

**Comment by duftler** [comment]
Fix released in Orca 1.384.0 if you wanted to try out the application-level notifications again.

**Comment by aamol** [comment]
Hi , I am having similar problem and I am not able to use expression in slack notification in Pipeline . I have tried a lot of different format which I found any suggestion
${execution.stages[0].name}
${execution.stage[0].name} , 
${ #stage('stage name')['name']} 
#stage('stage name')['name']

**Comment by souravsekhar** [comment]
@duftler I too am facing similar issue as @aamol is facing while using expression language in pipeline level.

I have tried format as below `${execution.stages[0]['name']}`. However, i don't see the expected value in my email notification. rather i see the same ${execution.stages[0]['name']} expression appearing in the email body.

I am on Spinnaker version 1.6.1 and `orca:
    version: 0.10.1-20180326113234
    commit: d0ba41ed8cff01abd3cbf2af7a00f73846ff3e1b`

Any help on this?

**Comment by souravsekhar** [comment]
@aamol By any chance, did you get a solution to the above issue you were facing?

**Comment by jdstone-loansnap** [comment]
I'm experiencing this issue as well.
I'm on Spinnaker version `1.10.2`.
```
$ hal --version
1.14.0-20190117020510
```

**Comment by dmyerscough** [comment]
I was able to get Slack to render notifications with the following

```
Deploying ${ trigger['artifacts'][0]['name'] }
Version: ${ trigger['artifacts'][0]['version'] }
User: ${ trigger['user'] }
```

```bash
$ hal --version
1.13.1-20190115161217
```

**Comment by jdstone-loansnap** [comment]
Hmm, my apologies, it seems the `parentExecution` are the only notifications not rendering...
```
${trigger[ 'parentExecution' ][ 'trigger' ][ 'parentExecution' ][ 'trigger' ][ 'tag' ]}
```

**Comment by derek9gag** [comment]
It only works when I remove all `${execution[...]}` expressions. #2922 is still valid and unresolved.

If you have one invalid expression in the message, the entire message will not be evaluated. For example if you have `User: ${ trigger['user'] }; BuildTime: ${execution.buildTime}`, it will not get evaluated at all.

**Comment by renperez** [comment]
any update on parentExecution not rendering? still not working for me
