### ISSUE TITLE
Cannot start Spinnaker using Docker compose configuration

### ISSUE THREAD

**Issue by kkapelon** [spinnaker/spinnaker#1546]
[container-logs.zip](https://github.com/spinnaker/spinnaker/files/904132/container-logs.zip)

**Title:** Failing experimental/docker-compose/docker-compose.yml
**Cloud provider:** None
**Environment:** Docker toolbox on Windows 10 
**Feature Area:** Installation

I am using the Docker toolbox on windows 10
it comes with 

- Boot2Docker version 1.12.4, build HEAD (Has 8GB RAM assigned)
- Docker version 1.12.4, build 1564f02
- Docker compose version 1.11.1

**Steps to Reproduce**

I followed the instructions by downloading Spinnaker, copying the `default-spinnaker-local.yml` file to `spinnaker-local.yml` and finally running:

DOCKER_IP=`docker-machine ip default` docker-compose up -d

**Expected results:**

All Spinnaker services should start with no error

**Actual results:**

The fiat container dies right away with message:
_Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'services.front50.baseUrl' in string value "${services.front50.baseUrl}"_
. I am attaching the full log as well

The echo container dies right away with message:
_Caused by: org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.expression.spel.SpelParseException: EL1041E:(pos 42): After parsing a valid expression, there is still more data in the expression: 'colon(:)'_
I am attaching the full log

The gate container starts ok, but attempts to connect to localhost:7002 and localhost:8080 instead of the correct clouddriver:7002 and igor:8080. I am attaching the full log.

The rest of the services start without error and if I ping them on **/health** endpoint they all report as _"status" : "UP"_

With gate non-functioning I am unable to create a new application. With echo down I assume that I cannot get notifications from Jenkins. I don't know the effect that fiat has if it is down.

**Comment by lwander** [comment]
Looks like this was fixed in the referenced PR
