### ISSUE TITLE
None deploy strategy with Kubernetes Deployment scales replica-set to zero

### ISSUE THREAD

**Issue by hekike** [spinnaker/spinnaker#1547]
*Cloud Provider*: Kubernetes
*Environment*: GCP Spinnaker Deployment (updated to latest spinnaker) with GCP hosted Kubernetes
*Feature Area*: Pipelines

**Description**

With the "None" deploy strategy I'm expecting to keep old replica sets running with new ones as well.
Current behavior: Old replica sets are scaled back to zero.

**Steps to Reproduce**

Add deploy pipeline with None strategy and use Deployment.

**Other**

Is it possible to use deploy strategies with Kubernetes Deployment?
Or Deployment's built-in strategy makes it impossible?

**Comment by lwander** [comment]
Kubernetes deployments always scale down the prior replica set. If you don't want this behavior, don't use the Deployment resource.
