### ISSUE TITLE
[Openstack] Null Pointer Exception when caching Server groups

### ISSUE THREAD

**Issue by kkapelon** [spinnaker/spinnaker#1558]
*Title* : Exception is thrown when Clouddriver is reading Servergroups
*Cloud Provider*: Openstack (Mitaka)
*Environment*: Running Spinnaker on Ubuntu 14.4.
*Feature Area*: clouddriver

*Description*

I have setup Openstack Mitaka in Spinnaker and created a simple application. Without doing anything else a Null pointer exception is thrown in the logs (because **autoscalingType** it null)

I am attaching the log
[clouddriver-exception-log-caching.zip](https://github.com/spinnaker/spinnaker/files/911815/clouddriver-exception-log-caching.zip)

Here is the respective source code https://github.com/spinnaker/clouddriver/blob/master/clouddriver-openstack/src/main/groovy/com/netflix/spinnaker/clouddriver/openstack/provider/agent/OpenstackServerGroupCachingAgent.groovy#L283

I use Openstack Mitaka with the a10 load-balancer integration plugin

**Comment by jrsquared** [comment]
Fixed by https://github.com/spinnaker/clouddriver/pull/1594
