### ISSUE TITLE
Clouddriver queries unknown Kubernetes pools on GKE

### ISSUE THREAD

**Issue by hekike** [spinnaker/spinnaker#1570]
*Cloud Provider*

GCP, Kubernetes

*Environment*

Google cloud Spinnaker Deployment

*Feature Area*

Clouddriver

*Description*

Clouddriver throws:
```
Error while querying target pool instance health: The resource 'projects/X/zones/europe-west1-c/instances/gke-experiment-data-scie-default-pool-c63965ce-9zs0' was not found
```
For the following pool variants:

- `gke-experiment-data-scie-default-pool-*`
- `gke-monitoring-small-pool-*`
- `gke-tracing-small-pool-*`

Are those built-in Google services?

**Comment by lwander** [comment]
This is happening because these pools exist in your project, and the Google Compute provider caches them.

**Comment by jtk54** [comment]
Thanks for the update. I'll do some poking around to ensure we're removing the group/instances from the network LB target pool correctly. IIRC this is not the first time we've seen strange behavior from target pools.
