### ISSUE TITLE
Clone Server Group Task on AWS Omits user data field

### ISSUE THREAD

**Issue by dmourati** [spinnaker/spinnaker#1575]
*Title*

Clone Server Group Task on AWS Omits user data field

*Cloud Provider*

AWS

*Environment*

I've deployed Spinnaker on Kubernetes following the "experimental" directory of the spinnaker repo. 

I'm using this Spinnaker installation to manage VMs on AWS.

*Feature Area*

Pipelines

*Description*

Expect to see user data in Launch Configuration.

See no user data in Launch Configuration.

*Steps to Reproduce*

I initialize a new Spinnaker Server Group with Terraform. This Server Group gets the name: "N/A" and the Server Group's Launch Configuration contains user data. 

I then create a  pipeline comprising two stages:

1. Find image from tags

2. Clone server group

The pipeline completes successfully. The resulting Server Group is named _my_app-v001_. Its Launch Configuration has no user data.

*Additional Details*

![image](https://cloud.githubusercontent.com/assets/2293813/25095302/09757f00-2350-11e7-9af1-202482028ea2.png)

![image](https://cloud.githubusercontent.com/assets/2293813/25095335/2e92ed0e-2350-11e7-8134-6a496ddfc036.png)

![image](https://cloud.githubusercontent.com/assets/2293813/25095362/41ecb240-2350-11e7-92a2-a55739bf9b1c.png)

Also worth noting, the Advanced Settings, Enabled Metrics also appears to be omitted or otherwise misformatted.

![image](https://cloud.githubusercontent.com/assets/2293813/25095401/7106e9e2-2350-11e7-9e9e-2d813aa63986.png)

**Comment by danielpeach** [comment]
Looking here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy#L183-L191

I see that `localFileUserDataProperties.enabled` is true by default. If you'd like a clone stage to be able to copy user data, I would set this flag in your `clouddriver-local.yml`:

```
udf:
  enabled: false
```

@anotherchrisberry will know more about the Enabled Metrics formatting.

**Comment by muslumb** [comment]
Hi ,
 i've same problem .i also checked that in my clouddriver-local.yml in /opt/spinnaker/config/ thast's look like "false".but user data in to launchconfig is "none".my version 1.8.7

Do you have any idea?
