### ISSUE TITLE
[GCP] Loadbalancers without Healthchecks cause Caching Agent to not complete

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#1581]
*Title*

Loadbalancers without Healthchecks cause Caching Agent to no complete

*Cloud Provider*

GCP

*Environment*

Running Clouddriver v1.586.0

*Feature Area*

Loadbalancer caching agent

*Description*

Expected behavior is if there is a malformed or incomplete load balancer in the GCP project, it should continue trying to cache the rest and skip over the error, but still report it of course.

*Steps to Reproduce*

Two load balancers were created via the Google Console, unsure how the Health Checks disappeared but they did and the load balancers still existed.

*Additional Details*

> [spinnaker-clouddriver-1298540586-2rb6x] 2017-04-19 13:51:49.745  INFO 8 --- [tionAction-2043] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:gcp-tgt-pe-prod/GoogleImageCachingAgent completed in 0.429s
> [spinnaker-clouddriver-1298540586-2rb6x] 2017-04-19 13:51:50.737  WARN 8 --- [tionAction-2060] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:gcp-tgt-pe-test/global/GoogleHttpLoadBalancerCachingAgent completed
> [spinnaker-clouddriver-1298540586-2rb6x]
> [spinnaker-clouddriver-1298540586-2rb6x] com.netflix.spinnaker.clouddriver.google.deploy.exception.GoogleOperationException: The resource 'projects/test-account/global/httpHealthChecks/linkerd-adaptive-manish-healthcheck-test' was not found
> [spinnaker-clouddriver-1298540586-2rb6x] at sun.reflect.GeneratedConstructorAccessor269.newInstance(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.PlatformErrorPropagator$Trait$Helper.onFailure(PlatformErrorPropagator.groovy:28)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.PlatformErrorPropagator$Trait$Helper$onFailure.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent$HttpHealthCheckCallback.onFailure(GoogleHttpLoadBalancerCachingAgent.groovy)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.google.api.client.googleapis.batch.BatchRequest$execute$0.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper.timeExecuteBatch(GoogleExecutorTraits.groovy:49)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper$timeExecuteBatch$3.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.timeExecuteBatch(AbstractGoogleCachingAgent.groovy)
> [spinnaker-clouddriver-1298540586-2rb6x] at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.lang.reflect.Method.invoke(Method.java:498)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
> [spinnaker-clouddriver-1298540586-2rb6x] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.executeIfRequestsAreQueued(AbstractGoogleCachingAgent.groovy:71)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent$executeIfRequestsAreQueued$0.callCurrent(Unknown Source)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent.getHttpLoadBalancers(GoogleHttpLoadBalancerCachingAgent.groovy:103)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent.loadData(GoogleHttpLoadBalancerCachingAgent.groovy:75)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
> [spinnaker-clouddriver-1298540586-2rb6x] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [spinnaker-clouddriver-1298540586-2rb6x] at java.lang.Thread.run(Thread.java:745)
> [spinnaker-clouddriver-1298540586-2rb6x]

> [spinnaker-clouddriver-1298540586-tdhxc] 2017-04-19 14:02:29.896  WARN 8 --- [ecutionAction-2] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:lab-account/global/GoogleHttpLoadBalancerCachingAgent completed
> [spinnaker-clouddriver-1298540586-tdhxc]
> [spinnaker-clouddriver-1298540586-tdhxc] com.netflix.spinnaker.clouddriver.google.deploy.exception.GoogleOperationException: The resource 'projects/tgt-pe-lab/global/httpHealthChecks/manish-test-ip-health-check' was not found
> [spinnaker-clouddriver-1298540586-tdhxc] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [spinnaker-clouddriver-1298540586-tdhxc] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [spinnaker-clouddriver-1298540586-tdhxc] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.PlatformErrorPropagator$Trait$Helper.onFailure(PlatformErrorPropagator.groovy:28)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.PlatformErrorPropagator$Trait$Helper$onFailure.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent$HttpHealthCheckCallback.onFailure(GoogleHttpLoadBalancerCachingAgent.groovy)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.google.api.client.googleapis.batch.BatchRequest$execute$0.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper.timeExecuteBatch(GoogleExecutorTraits.groovy:49)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper$timeExecuteBatch$3.call(Unknown Source)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.timeExecuteBatch(AbstractGoogleCachingAgent.groovy)
> [spinnaker-clouddriver-1298540586-tdhxc] at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
> [spinnaker-clouddriver-1298540586-tdhxc] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.lang.reflect.Method.invoke(Method.java:498)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
> [spinnaker-clouddriver-1298540586-tdhxc] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.executeIfRequestsAreQueued(AbstractGoogleCachingAgent.groovy:71)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent$executeIfRequestsAreQueued$0.callCurrent(Unknown Source)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent.getHttpLoadBalancers(GoogleHttpLoadBalancerCachingAgent.groovy:103)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHttpLoadBalancerCachingAgent.loadData(GoogleHttpLoadBalancerCachingAgent.groovy:75)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
> [spinnaker-clouddriver-1298540586-tdhxc] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [spinnaker-clouddriver-1298540586-tdhxc] at java.lang.Thread.run(Thread.java:745)
> [spinnaker-clouddriver-1298540586-tdhxc]

**Comment by danielpeach** [comment]
@jtk54

**Comment by jtk54** [comment]
The reason we fail here is because writing bad data to the cache is worse than writing nothing (see https://github.com/spinnaker/clouddriver/pull/1336). 

The way we implemented the failure causes the whole batch to exit on a LB component lookup failure. I _think_ we can write the successfully retrieved LBs without tainting the cache if we record the names of the LBs we fail on and just remove them from the result before we write it to the cache.

I'll cook up a PR and see if we can do this.

**Comment by jtk54** [comment]
On the topic of your health checks disappearing: make sure you're using `httpHealthCheck` or `httpsHealthCheck` types _only_ with L7 LBs. We have a bug to support the newer `healthCheck` types. The issue is you can configure the latter in Google Gloud Console but Spinnaker doesn't handle it properly yet.

**Comment by nfirvine** [comment]
https://github.com/spinnaker/spinnaker/issues/1581#issuecomment-295398067
@jtk54 Do you have a link to this bug? I can't find any mention of this anywhere and I suspect it's killing us

**Comment by jtk54** [comment]
I'm a little confused at what you're asking. Which bug are you referring to?

**Comment by nfirvine** [comment]
@jtk54 so fast! 

> We have a bug open to support the newer healthCheck types.

**Comment by jtk54** [comment]
Ah, OK. My last comment in this thread was addressed in https://github.com/spinnaker/clouddriver/pull/2030. Are you seeing behavior where health checks are missing?

**Comment by nfirvine** [comment]
I'm still experimenting to triage, but at first glance, looks like when selecting a health check for an autohealing group, it gets added to the wrong type, or vice versa. That's our main problem.

But yes, also I'm not seeing any health checks in the list, but I'm not sure that problem is this problem :)

**Comment by jtk54** [comment]
Which version of Spinnaker are you running?

**Comment by nfirvine** [comment]
1.6.1, planning on upgrading to 1.7.0 this week probably

**Comment by nfirvine** [comment]
Ok, looks like the upgrade fixed that particular deck/gate interaction. Hurray!

My original problem that lead me down this rabbit hole is that my instance groups with new-style httpChecks never become ready from Spinnaker's POV. I opened a separate bug https://github.com/spinnaker/spinnaker/issues/2736

**Comment by jtk54** [comment]
Summing up: updating to 1.7.x fixes the missing health checks, but #2736 is still open after updating, correct?

**Comment by nfirvine** [comment]
Right. I was thinking the UI problem was deeper than an API mismatch, but I don't think it was. And yes, #2736 is still valid on 1.7.2. I'm going to be working on it today
