### ISSUE TITLE
[GKE] [Kubernetes] deployment guide not working on GKE

### ISSUE THREAD

**Issue by lihan** [spinnaker/spinnaker#1589]
Cloud Provider:  **GKE**, Kubernetes

AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc. Please assign a label from the right so your issue can be properly sorted.

*Environment*

I am trying to deploy Spinnaker using [this guide](https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple) onto GKE. ```

*Feature Area*

Install

*Description*

Following the guide will not create a working Spinnaker

*Steps to Reproduce*

Follow this [guide](https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple) and trying to create it on GKE 

*Additional Details*

At least 
1. Documentation should state that `services.desk.host` from `spinnaker-local.yml` is to change to `localhost`, or you will hit `access-control-allow-origin` issue, and after that you should restart `gate` service.
2. After solve above 1, hit [this issue](https://github.com/spinnaker/spinnaker/issues/1276)

**Comment by lwander** [comment]
Deployment guide is deprecated in favor of [Halyard](https://www.spinnaker.io/setup/install/halyard/).
