### ISSUE TITLE
bug(clouddriver/kubernetes): Docker Registries and Kubernetes accounts with the same name cause an exception to be thrown

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1605]
bug(clouddriver/kubernetes): Docker Registries and Kubernetes accounts with the same name cause an exception to be thrown

*Cloud Provider*

Kubernetes

*Environment*

Kubernetes

*Feature Area*

Clouddriver Docker Registry/Kubernetes

*Description*

I only realized this because I was configuring my Kubernetes account with the `namespaces` parameter and it was attempting to map that field to the Docker Registry object.

Expected: 
Docker Registries with the same name as a Kubernetes account don't cause the `/credentials` endpoint in Clouddriver to 500 causing the pod to never appear healthy.

Actual:
Docker Registries and Kubernetes accounts that have the same name cause an exception to be thrown. 

```
com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials cannot be cast to com.netflix.spinnaker.clouddriver.docker.registry.security.DockerRegistryNamedAccountCredentials (through reference chain: com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials["namespaces"])
```

*Steps to Reproduce*

Configure a Kubernetes account and a Docker Registry with the same `name` parameter and assign a `namespaces` parameter to the Kubernetes configuration. You should see some exceptions thrown with something tries to hit `/credentials`.

**Comment by lwander** [comment]
All account names must be unique. This is enforced with Halyard.
