### ISSUE TITLE
clouddriver should be more liberal with crashing instead of logging exceptions

### ISSUE THREAD

**Issue by nfirvine** [spinnaker/spinnaker#1610]
I've had this happen in a few different scenarios where credentials for platforms are grossly misconfigured and yet clouddriver still runs and appears healthy. It logs a stack trace to the logs, but users just see missing accounts.

As an example, here's a Kubernetes account failing to initialize:

```
2017-04-27 20:33:25.586  INFO 1 --- [           main] s.c.k.s.KubernetesCredentialsInitializer : Could not load account kube-dev for Kubernetes.

java.lang.IllegalStateException: Unable to build secret: Constraint Validations: metadata.name must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$" on bean:...
```

This is because the referenced Docker repo account name had underscores in it. That's a silly restriction in itself, but not the point. The point is that failing to load an account should be a fatal error.

The same sort of behaviour happens when the `kubeconfig.yml` file is missing or invalid.

**Comment by lwander** [comment]
Agreed - this is a problem across several platform.s Credential configuration & validation is now being handled by [Halyard](https://www.spinnaker.io/setup/install/halyard/) for this reason.
