### ISSUE TITLE
Spinnaker 0.80.0 fails with traceback when running reconfigure_spinnaker.sh

### ISSUE THREAD

**Issue by ryan-mf** [spinnaker/spinnaker#1617]
*Title*

Spinnaker 0.80.0 fails with traceback when running reconfigure_spinnaker.sh

*Cloud Provider*

GCP

*Environment*

I'm running Spinnaker using the GCP Cloud Launcher template and have been stable with our configs (spinnaker-local.yml and clouddriver-local.yml) for a few weeks now.

*Feature Area*

Upgrade

*Description*

I used apt-get upgrade (which I've done every couple days the past few weeks and Spinnaker components have always upgraded without error), and Spinnaker fails it's upgrade with this error output from reconfigure_spinnaker.sh:
```
Traceback (most recent call last):
  File "/opt/spinnaker/bin/../pylib/spinnaker/reconfigure_spinnaker.py", line 25, in <module>
    configurator.update_deck_settings()
  File "/opt/spinnaker/pylib/spinnaker/configurator.py", line 173, in update_deck_settings
    settings = self.process_deck_settings(source)
  File "/opt/spinnaker/pylib/spinnaker/configurator.py", line 223, in process_deck_settings
    value = self.bindings.replace(match.group(2))
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 157, in replace
    return self.__resolve_value(text, [], text)
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 128, in __resolve_value
    got = self.__get_field_value(exact_match.group(1), saw, original)
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 120, in __get_field_value
    return self.__resolve_value(value, saw, original)
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 144, in __resolve_value
    got = self.__get_field_value(str(match.group(1)), saw, original)
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 112, in __get_field_value
    value = self.__typed_value(value)
  File "/opt/spinnaker/pylib/spinnaker/yaml_util.py", line 105, in __typed_value
    return yaml.load('x: {0}'.format(value_text), Loader=yaml.Loader)['x']
  File "/opt/spinnaker/pylib/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/opt/spinnaker/pylib/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/opt/spinnaker/pylib/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/opt/spinnaker/pylib/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/opt/spinnaker/pylib/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/spinnaker/pylib/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/spinnaker/pylib/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/opt/spinnaker/pylib/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/spinnaker/pylib/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/opt/spinnaker/pylib/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/opt/spinnaker/pylib/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '`' that cannot start any token
  in "<string>", line 1, column 4:
    x: `__get_google_metadata_value "pr ...
       ^
```

*Steps to Reproduce*

1. Create a Spinnaker instance from the GCP Cloud Launcher template
2. SSH to the host and run "sudo apt-get update && sudo apt-get upgrade"
3. Watch Spinnaker's package upgrade fail when installs 0.8.0 and then attempts to run reconfigure_spinnaker.sh.

I attempted to reboot just to get a fresh start and this continues to fail. Luckily Spinnaker *appears* to be working just fine from a functionality standpoint, but apt believes a package upgrade is still pending to finish and I'm unable to run reconfigure_spinnaker.sh if I need to make any other changes.

**Comment by ryan-mf** [comment]
I've done some more research here - it looks like reconfigure_spinnaker.sh is just a thin wrapper that calls reconfigure_spinnaker.py. However, the only reference I can find in the entire Spinnaker github project for `__get_google_metadata_value` is in /etc/default/spinnaker, where it has a function called get_google_metadata_value that is called by another ENV VAR set command in order to find out what the value of the VAR should be. 

Python is erroring that a token can't begin with a backtick, and /etc/default/spinnaker uses backticks to wrap the command that the ENVVAR needs to be set equal to the output of.

I've not changed anything related to this in /etc/default/spinnaker vs what is default installed; the only changes I've made to that file are defining more ENV VARs at the bottom of the file and enabling some components like stackdriver by changing enabled from false to true.

So, I don't think I've changed anything that would impact this, in fact I diff'd them side-by-side to be sure, and I haven't changed anything in this file in several weeks and have gone through several spinnaker apt-get upgrades since without issue.

**Comment by ewiseblatt** [comment]
On first glance, it looks like /etc/default/spinnaker is not being sourced so the SPINNAKER_GOOGLE_PROJECT_ID is not being evaluated. Instead you are seeing the expression rather than the evaluation of it. I'm looking into what might have changed.

**Comment by ewiseblatt** [comment]
For a workaround in the meantime, set an explicit value of SPINNAKER_GOOGLE_PROJECT_ID there, or override providers.google.primaryCredentials.project in spinnaker-local.yml to explicitly set it there.

**Comment by ryan-mf** [comment]
Hi @ewiseblatt ,

Thanks for the advice. Yep, setting the ENVVAR to the static value of the GCP project (instead of calling that function) resolved my issue as a workaround for now. I'll wait for updates to this ticket before setting it back to the function call again.

Thanks,
-R

**Comment by ewiseblatt** [comment]
There were two unusual things going on here.
First is that he was defining primaryCredentials.name as a function of primaryCredentials.project which was referencing the environment variable. That is unusual. The settings.js file doesnt reference the project so would not have otherwise hit this. The reconfigure script is a python script that reads the environment variables so they are not evaluated and thus he was seeing the expression rather than the value. We could evaluate them in the bash script wrapping the python but there are other potential implications and it will all go away with Hal.

The second unusual thing is that although the environment variable is in fact defined as a function to be evaluated, in practice launcher sets the startup script to first_google_boot.sh which will replace the environment variable definition with the actual deployed project. Clearly that hadnt happened, which is unheard of as well.

So I think what happened here is that when he performed the upgrade, the spinnaker.deb upgraded and overwrote the /etc/default/spinnaker file. That file is protected in a way that updates would detect the modification and prompt about how to handle it. I'm not exactly sure what happened here, but looks like it is correct.
