### ISSUE TITLE
[deck] Project UI on firefox no longer responding to mouse scrolling 

### ISSUE THREAD

**Issue by erickt** [spinnaker/spinnaker#1621]
We're having trouble with the latest version of Deck and Firefox. When we're inside a project dashboard, while the page scrolls if we press the up and down arrows, it no longer scrolls with the mouse wheel. However, Chrome and Safari mouse scrolling still works. This was repeatable on multiple machines. Thanks for any help.

**Comment by anotherchrisberry** [comment]
Sorry - fix should be rolling out here: https://github.com/spinnaker/deck/pull/3634
