### ISSUE TITLE
Deprecated Amazon AMI Ids ?

### ISSUE THREAD

**Issue by abrass** [spinnaker/spinnaker#1649]
I try to install Spinnaker in AWS using the provided CloudFormation-Template:
https://s3.amazonaws.com/quickstart-reference/spinnaker/latest/templates/quickstart-spinnakercf.template

The deployment fails with following problem:
SpinnakerWebServer	The image id 'ami-b12edade' does not exist

If I check the website with available AMIs:
http://www.spinnaker.io/docs/amazon-ami-ids

Only following seems to be existing:
us-east-1 
us-west-1
us-west-2
sa-east-1

Do I have to access the AMI differently or why I cannot use them? If I search in Public Images for Spinnaker in region=eu-central or eu-west, I do not find any.

**Comment by abrass** [comment]
The installation works if I change eu-central to following AMI.
      "eu-central-1": {
        "AMI": "ami-25a97a4a"
      }

At least it is as much working as the us-west. If I use the SSL port-forwrds, the website is reachable over localhost:9000. But if I try to create an application an communication error to localhost:8080 is shown.

**Comment by mkaja** [comment]
any update on ami-id in us-east-1 for ubuntu 14.04? @lwander

**Comment by anshrma** [comment]
@mkaja - meanwhile the support for a AMIs in remaining regions is added, can you pls try copying AMIs listed above to other regions as mentioned [here](https://aws.amazon.com/premiumsupport/knowledge-center/copy-ami-region/) . That will also future proof you from any further changes in AMIs from the owner accounts.
