### ISSUE TITLE
[Gate]: Redirect URL gets set to httpss in URL if SSL enabled is set to false

### ISSUE THREAD

**Issue by devopsdynamo** [spinnaker/spinnaker#1650]
Title

[Gate]: Redirect URL gets set to httpss in URL if SSL is set to false in gate

*Cloud Provider*

AWS

*Environment*

I am running Spinnaker as independent microservices within AWS.   I have Deck configured behind AWS ELB with SSL terminating at the ELB.    Deck is running on Apache and is configured to proxy all requests to /gate, /login and /auth/redirect to Gate which is running behind private ELB.

*Feature Area*

Authentication - Github

*Description*

When browsing to deck url, I expect to be redirected to github login page using the url value configured under spring.oauth2.preEstablishedRedirectUri within gate.yml.  If I set the redirect url to use https,  I have noticed from debugging issue that gate is attempting to redirect url starting with httpss://MY_URL  (e.g duplicate s in httpss).

*Steps to Reproduce*

1. in settings.yml set authentication to enabled.
2. Add oauth2 and auth config in gate.yml (I am currently using Github as our auth provider)
3. Set ssl.enabled.false in gate.yml  (I am terminating SSL on our deck ELB in AWS)
4. Set preEstablishedRedirectUri to URL starting with https://
5. Attempt to browse to deck_url. e.g https://deck_url
6. In response headers for below request you should see location set to httpss://deck_url/login

https://deck_url/gate/auth/redirect?to=https://deck_url/#/infrastructure

**Comment by devopsdynamo** [comment]
To add,  I can confirm this issue is not present in gate version 3.33.0.

**Comment by ttomsu** [comment]
This was my fault - I just cut 3.35.0, which should hopefully fix it. Please ping me on the slack channel (join.spinnaker.io), username ttomsu, if that doesn't work.

**Comment by devopsdynamo** [comment]
@ttomsu awesome, thanks!.  I've just deployed 3.35.0 and I can confirm this is now fixed :)
