### ISSUE TITLE
[Clouddriver] Autoscaling isn't working with kubernetes 1.6

### ISSUE THREAD

**Issue by bacher09** [spinnaker/spinnaker#1651]
*Title*
Autoscaling isn't working with kubernetes 1.6

*Cloud Provider*

Kubernetes 1.6

*Environment*

I'm using simple spinnaker installation from [here](https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple)

*Feature Area*

Clouddriver, Autoscaling

*Description*

Spinnaker failed to create autoscaling kubernetes resource. This happens because clouddriver is using old API URL (`apis/extensions/v1beta1/namespaces/{namespace}/horizontalpodautoscalers`). It should use new one: `apis/autoscaling/v1/namespaces/{namespace}/horizontalpodautoscalers`.

*Steps to Reproduce*

Just try to deploy service with autoscaling to kubernetes 1.6. 

*Additional Details*

Possible related issue: https://github.com/fabric8io/kubernetes-client/issues/730
Also, here's [clouddriver exception](https://github.com/spinnaker/spinnaker/files/1008271/autoscaling_exception.txt)

**Comment by lwander** [comment]
We're aware, that issue was filed against the client library for that reason

**Comment by radubutnaru** [comment]
Does this issue prevent using a Kubernetes v1.6 account altogether? 

I'm evaluating Spinnaker and connected a test installation to a Kubernetes v1.6.2 cluster. 'hal config provider kubernetes account add ...' was successful. However, there's no account available in the Spinnaker UI (Application screens). The only exception from the logs is related to the autoscaling URLs.

**Comment by ethanfrogers** [comment]
@radubutnaru it does not! You can still use Kubernetes 1.6, just not HPAs. The Accounts option was removed from the UI so you should still be able to create Applications.

**Comment by radubutnaru** [comment]
@ethanfrogers thanks! I was misinterpreting then - trying to follow the instructions from https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/ and expected Accounts to be present in the Create Application screen.
