### ISSUE TITLE
[Kubernetes]: Add Ability to further configure Run Job stage

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1683]
feat(Kubernetes): Add Ability to further configure Run Job stage

*Cloud Provider*

Kubernetes

*Feature Area*

Pipelines - Run Job Stage

*Description*

When configuring the Run Job stage there should be additional options for configuration such as Labels, Annotations and possibly Stack name. Why? Since there is currently no way to expose the logs for Kubernetes Pods, when a Pod created during a Run Job stage and is then destroyed there is no way to see the log output with something like `kubectl logs {podname}` or view them from the Kube UI. You could configure something like Fluentd to capture the logs, but the naming convention of the Pods created by Run Job makes that difficult to match with a Regular Expression since the name is something like `{appname}-{hash}`. 

This feature would allows users to configure annotations, labels and stack name through the Run Job configuration that would then be applied to the Pod created to do the work in order to make it easier to target specific Pods in the Kubernetes logs.

**Comment by viglesiasce** [comment]
Agreed! This would definitely help. Additionally it might be nice to be able to add an arbitrary chunk of html to that little pane that could be used to link to your log viewer of choice (possibly parameterized).

**Comment by lwander** [comment]
Good idea - there's no good reason why labels aren't allowed on the job pods right now.
