### ISSUE TITLE
Deploy Classic ELB to AWS always Internet facing after spinnaker-clouddriver=1.609.0

### ISSUE THREAD

**Issue by bensnet1** [spinnaker/spinnaker#1692]
*Title*

Create Classic ELB on AWS is always Internet facing after spinnaker-clouddriver=1.609.0

*Cloud Provider*

 AWS

*Environment*

I am using the ubuntu/debian packages to Spinnaker my Spinnaker. I am running on AWS and deploying services to AWS across multiple accounts with success.

*Feature Area*

Deployment of classic ELB to AWS

*Description*

When creating a classic ELB to AWS if you check the "Internal" box or not it is always Internet facing post version spinnaker-clouddriver=1.609.0. Using 1.609.0 and earlier does not have this issue. 

*Steps to Reproduce*
I stepped through multiple versions of of the spinnaker-clouddriver package to isolate this issue. My current working workaround is to hold at spinnaker-clouddriver=1.609.0. Any version post this has been shown to have the issue in my testing. I spent quite a few hours isolating this problem to this exact version of the spinnaker-clouddriver package.

*Additional Details*

As noted in the steps to reproduce, stepping past spinnaker-clouddriver=1.609.0 shows the issue, stepping back to spinnaker-clouddriver=1.609.0 removes the issue.

**Comment by jrsquared** [comment]
@bensnet1 I just merged a fix this and it's in [Release 1.625.0](https://github.com/spinnaker/clouddriver/releases/tag/v1.625.0). Let me know if it works for you!

**Comment by bensnet1** [comment]
@jrsquared - I have just build a new Spinnaker with the updated package. 

I can confirm that your fix has indeed fixed the problem. 
Installed - spinnaker-clouddriver            1.625.0

I am able to create both internal and external classic AWS ELB's depending on the option chosen within the UI.

Thank you.
