### ISSUE TITLE
end users coming to https://groups.google.com/forum/#!forum/spinnakerusers

### ISSUE THREAD

**Issue by alan-stokes** [spinnaker/spinnaker#1695]
*Steps to Reproduce* 

google SpiNNaker, points you at end users coming to https://groups.google.com/forum/#!forum/spinnakerusers first. People head here first, unaware of your end user interface.

*Additional Details* 

as moderator of end users coming to https://groups.google.com/forum/#!forum/spinnakerusers, we would like to know where to send them, instead of telling them we are not you. Best would be if your users found your comms first.

**Comment by lwander** [comment]
Can you remove the boiler plate from your issue description? I'm having trouble understanding the problem.

**Comment by anotherchrisberry** [comment]
@lwander boilerplate removed

**Comment by lwander** [comment]
Ah I see - could you point users either at https://groups.google.com/forum/#!forum/spinnaker-announce, or at http://join.spinnaker.io?

**Comment by lwander** [comment]
Feel free to reopen if that doesn't answer your question
