### ISSUE TITLE
Pipelines doc spelling error

### ISSUE THREAD

**Issue by jmaclabs** [spinnaker/spinnaker#1713]
Pretty sure this isn't a dup..

*Feature Area*

Documentation

*Description*

Pipelines section of doc has a spelling error

> Pipelines are your way of managing deployments in a consistent, repeatable and safe way. A pipeline is a sequence of stages provided by Spinnaker, ranging from functions that manipulate infrastructure (deploy, resize, disable) as well as utility scaffolding functions (manaul judgment, wait, run Jenkins job) that together precisely define your runbook for managing your deployments.

The first item in the parenthesis is "manaul judgment," which is misspelled. 

*Steps to Reproduce*

https://spinnaker.github.io/concepts/pipelines/

*Additional Details*

Obviously minor issue

**Comment by skim1420** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/205
