### ISSUE TITLE
 Server Group with only HTTP(s) Load Balancer cannot be enabled after deployment

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#1722]
*Title*

Server Group with only HTTP(s) Load Balancer cannot be enabled after deployment

*Cloud Provider*

GCP

*Environment*

Clouddriver: 1.617.0
Orca: 1.401.0 (yeah I know it's old)

*Feature Area*

Server group enablement

*Description*
When a server group is deployed as disabled and only has a HTTP(s) load balancer defined, it should be able to get attached to the load balancer via the Enable Server Group function in the Server Group tab of the Deck interface

*Steps to Reproduce*

1. Create a server group to deploy that does NOT accept traffic immediately when it is ready
2. Add only an HTTPs Load Balancer to the server group in the deployment step
3. Deploy the server group
4. Wait for the server group to become ready.
5. Enable the server group in the Server Group tab of Deck
6. The Enable Server group task will fail with the following error

```
Exception: Load balancers [] not found.
```

*Additional Details*

This happens because global-load-balancers is a different field than load-balancers and I think the atomic enable operation only looks for load balancers and not global-load-balancers

**Comment by jtk54** [comment]
Clouddriver currently can't start up below (GitHub release) version v1.635.0 due to a new region being introduced. This has two pretty bad ramifications:
* I can't verify this bug since I can't get clouddriver to start.
* If you restart clouddriver, it will break horribly until you upgrade. Don't turn it off if you want to use Spinnaker to manage things.

If you upgrade and this exception still persists, ping this bug with new component versions.

**Comment by edwinavalos** [comment]
It somehow didn't click to me to think 'below' was the keyword there #ripprod

**Comment by edwinavalos** [comment]
Still happening in the 1.637.0

**Comment by jtk54** [comment]
Ok, working on the ILB bug now and will repro this today hopefully.

**Comment by jtk54** [comment]
What is your Orca version? still ye olde 1.401.0?

**Comment by edwinavalos** [comment]
Yep, I can try bumping it, but it might take a few days for them to let us bump up to latest after we killed clouddriver the other day.

**Comment by jtk54** [comment]
Didn't get around to this yet since I made breaking UI changes in https://github.com/spinnaker/spinnaker/issues/1717 that need reverted and fixed. Will verify this behavior once that's taken care of.

**Comment by jtk54** [comment]
With clouddriver=1.637.0, orca=1.401.0 and everything else at head, I couldn't reproduce this behavior.

I created an application with "consider cloud provider health only" and followed the repro steps. Server group was enabled (but not marked as "up" on account of considering only the cloud provider health.

@edwinavalos Can you provide more information? Is this the setup you were using when you initially saw this issue?

**Comment by edwinavalos** [comment]
I can try and recreate tomorrow with the most up to date components of everything, but if I don't get to it tomorrow, I'll be out of contact till the 4th.

**Comment by jtk54** [comment]
Is this issue still outstanding?

**Comment by edwinavalos** [comment]
Looks good now. Closing
