### ISSUE TITLE
Preconfigured Webhook Stage Issue

### ISSUE THREAD

**Issue by lluu** [spinnaker/spinnaker#1738]
Issue using preconfigured Webhook stage provided in [PR 1329](https://github.com/spinnaker/orca/pull/1329)

*Description*

I expected headers and statusURLResolution configured in orca.yml being leveraged, but they were not.  The issues are:
1. The parameter for the headers is named headers, but the code looks for customHeaders to create the Stage context.
2. statusURLResolution is overriden by the default set in User context.

*Steps to Reproduce*

Add a preconfigured webhook stage in orca.yml as described in [PR 1329](https://github.com/spinnaker/orca/pull/1329), having headers and statusURLResolution set to localHeader.  
Add this preconfigured stage in Deck
Execute the stage and examine orca.log to see Stage Context has statusURLResolution set to getMethod, and step through orca code, you'll see HTTP headers is null.

*Additional Details*

I have the fix for this issue (in orca and deck), will create a PR for this issue.

**Comment by jervi** [comment]
This should probably be closed? Thanks @lluu!
