### ISSUE TITLE
Custom Links don't show up for Kubernetes provider

### ISSUE THREAD

**Issue by emptywee** [spinnaker/spinnaker#1739]
*Cloud Provider*

Kubernetes

*Environment*

Self-hosted on-premises Kubernetes cluster

*Feature Area*

UI

*Description*

When custom links are added in the config tab of an app, they don't show up anywhere in the UI. I'd expect them to appear in the instances details with Pod's IP address as the base address.

*Steps to Reproduce*

Create any custom link for any app and try to find it anywhere in the UI.

*Additional Details*

Additional information such as screenshots and exception logs.

![image](https://user-images.githubusercontent.com/4997180/26997422-21055d66-4d3f-11e7-9e56-da53b64ccb37.png)

![image](https://user-images.githubusercontent.com/4997180/26997432-3787b8a4-4d3f-11e7-94cb-c2cebad9ac41.png)

**Comment by emptywee** [comment]
@danielpeach Hi. Thanks for taking care of this! Although the links appeared now in the UI, the links are constructed with the 'undefined' word instead of a base IP address of the instance. The rest is good. Could you check if there's a typo or some other mistake? Thank you.

**Comment by danielpeach** [comment]
Not sure how you're updating Spinnaker and your config - you'll need to add this line to your `settings.js`:
https://github.com/spinnaker/deck/blob/master/settings.js#L82

That template will be used as the base of the instance link, and will be interpolated with values from the instance. The default assumes that you'll proxy through the Kubernetes API, but if you just want to use the pod's IP (as you mentioned on Slack), you can set it to `{{podIp}}`.

**Comment by emptywee** [comment]
Oh, did not notice that the change to the settings.js was required. Sorry! I will try it out. Thanks!

**Comment by emptywee** [comment]
Works just fine now! Thanks again!
