### ISSUE TITLE
Why not use go as the key language in spinnaker?

### ISSUE THREAD

**Issue by sunfaces** [spinnaker/spinnaker#1755]
I have tried every way to install spinnaker in mac-os and ubuntu 14.04, but they all failed, so why use python to implement such a large platform? If it is go, everything can be done with just one binary

**Comment by tomaslin** [comment]
Only installer is python. Most services are Java / Groovy / Kotlin. Try https://www.spinnaker.io/setup/install/halyard/ and ask in Spinnaker slack for issues. I'm closing this because it's not actionable.
