### ISSUE TITLE
Halyard cannot be set up?

### ISSUE THREAD

**Issue by hb951396063** [spinnaker/spinnaker#1776]
hey guys,I met a problem: It goes well when I enter "sudo bash InstallHalyard".But [Spinnaker-Halyard] reach 53% or 40%, it cannot continue download anything.Then it show:operation too slow.Less than 10 bytes/sec tansferred the last 120 secs.So it's just blamed for network?is there someway to solve it ?

**Comment by lwander** [comment]
Could be that the bintray repo hosting halyard is slow - where are you downloading from? 

See https://bintray.com/spinnaker-releases/debians/spinnaker-halyard

**Comment by hb951396063** [comment]
@lwander from China company.The speed of downloading at home was 50KB/sec and finally made it .

Then it went to a new one:java.lang.runtimeexception:Fail to invoke validate() on "DeploymentConfigurationValidator" for node "DeploymentConfiguration。

By the way,I built it on my vmware machine.Does it matter?

**Comment by linlynn** [comment]
@hb951396063  you can run --debug option to see more details about this failure

**Comment by lwander** [comment]
Duplicate of: https://github.com/spinnaker/spinnaker/issues/2405
