### ISSUE TITLE
Cannot specify Kubernetes field ref env vars in Spinnaker Service Groups.

### ISSUE THREAD

**Issue by radubutnaru** [spinnaker/spinnaker#1777]
*Title*

Cannot specify Kubernetes field ref env vars in Spinnaker Service Groups.

*Cloud Provider*

Kubernetes

*Environment*

clouddriver-kubernetes-1.635.0

*Feature Area*

Service Groups.

*Description*

Kubernetes pods/replica sets/deployments can be injected env vars with introspection info - e.g. node hostname, per https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ 

Kubernetes-based Server Groups only allow defining env vars having as source: Explicit, Config Map, Secret. 

Ideally, it should be possible to have a new source type: FieldRef.

*Steps to Reproduce*

In Spinnaker UI, create a new Kubernetes-based Server Group for an Application. The Environment Variables field Source lists only Explicit, Config Map, Secret.

*Additional Details*

N/A

**Comment by lwander** [comment]
This is implemented, what version of deck are you on? https://github.com/spinnaker/deck/pull/3804

**Comment by radubutnaru** [comment]
Oh, perfect then! Sorry for the duplicate issue. I'm on Spinnaker 1.0.1, Deck version https://github.com/spinnaker/deck/releases/tag/version-1.2.0 

So, do I have to wait for the next release Spinnaker release or is there an easy way to upgrade to the latest deck in the meantime?

Thanks a lot.

**Comment by lwander** [comment]
Yup, will be out in 1.1
