### ISSUE TITLE
gate :unrecognized service 

### ISSUE THREAD

**Issue by linlynn** [spinnaker/spinnaker#1783]
all,   i setup halyard in docker container and try to deploy spinnaker on same container  and when run sudo hal deploy apply ,it ends with lots of service unrecognized 
"service echo start"

these config file are located in /etc/init folder and looks good ,any idea ? i suppose it is using upstart in ubuntu 14.04

rosco: unrecognized service
Reading package lists...
Building dependency tree...
Reading state information...
spinnaker-echo is already the newest version.
The following package was automatically installed and is no longer required:
  libjemalloc1
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
echo: unrecognized service
Reading package lists...
Building dependency tree...
Reading state information...
spinnaker-gate is already the newest version.
The following package was automatically installed and is no longer required:
  libjemalloc1
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
gate: unrecognized service
Reading package lists...
Building dependency tree...
Reading state information...
redis-server is already the newest version.
The following package was automatically installed and is no longer required:
  libjemalloc1
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
spinnaker: unrecognized service
! ERROR Error encountered running script. See above output for more
  details.

**Comment by lwander** [comment]
I don't think installing the Debians into a docker container is a good
idea. Also, the script output seems to say that the services are already
installed? What did you use as your base image?

**Comment by linlynn** [comment]
I am using ubuntu:14.04 from official docker hub base my base image then add additional packages  

what's limitation to use docker container for this case?

**Comment by lwander** [comment]
Well running apt in a docker container is not a common practice; a quick
Google search shows other people have similar problems, but they seem
resolvable.

**Comment by linlynn** [comment]
thanks @lwander ,let me take a look  meanwhile I plan to setup a new ubuntu in my another physical machine

**Comment by linlynn** [comment]
Closed .

**Comment by linlynn** [comment]
closed

**Comment by odino** [comment]
@linlynn did you find a fix to the issue?
