### ISSUE TITLE
workdir handling in the spinnaker Dockerfiles

### ISSUE THREAD

**Issue by realmbgl** [spinnaker/spinnaker#1801]
*Title*

*workdir* handling in the spinnaker Dockerfiles

*Environment*

running spinnaker docker images with mesos universal containerizer

*Description*

I’m running into an issue launching the spinnaker docker images with the mesos universal containerizer. The launch fails with the following message.

```
Failed to chdir into current working directory '/workdir': No such file or directory
```
 
Looking at the Dockerfile for front50 for example.

```
FROM java:8
 
MAINTAINER delivery-engineering@netflix.com
 
COPY . workdir/
 
WORKDIR workdir
 
 
RUN GRADLE_USER_HOME=cache ./gradlew buildDeb -x test && \
 dpkg -i ./front50-web/build/distributions/*.deb && \
 cd .. && \
 rm -rf workdir
 
CMD ["/opt/front50/bin/front50"]
```

The **COPY** will implicitly create the **workdir** directory, and in the **RUN** it gets removed with **rm -rf workdir**. Even so that the **workdir** got removed if you do a docker run with the image and go to the cmd shell you will see that it is still there, looks like docker magically creates it again. If you launch the same with the mesos universal containerizer it will fail, it does not re-create the **workdir** but tries change to it.
 
There is a way around this by changing the spinnaker docker files to the following.

```
FROM java:8
 
MAINTAINER delivery-engineering@netflix.com
 
RUN mkdir workdir
 
COPY . workdir/
 
RUN cd workdir && GRADLE_USER_HOME=cache ./gradlew buildDeb -x test && \
 dpkg -i ./front50-web/build/distributions/*.deb && \
 cd .. && \
 rm -rf workdir
 
CMD ["/opt/front50/bin/front50"]
```

With this the workdir is really gone after the docker build.
 
Let me know what you think, happy to help to make these changes.

**Comment by lwander** [comment]
This is fixed by the "Dockerfile.slim" builds we do for each service these days: https://github.com/spinnaker/clouddriver/blob/master/Dockerfile.slim
