### ISSUE TITLE
Spinnaker 1.1 halyard missing canary feature flag

### ISSUE THREAD

**Issue by rebalag** [spinnaker/spinnaker#1820]
*Description*

Deploy Spinnaker using Halyard. 
hal version latest - returns
+ Get latest released version
  Success
1.1.0

diff deck/settings.js and deck/halconfig/settings.js has differences in feature flag (missing in halconfig)
>     canary: canaryEnabled,

And variable processing from environment:
> var feedbackUrl = process.env.FEEDBACK_URL;
> var gateHost = process.env.API_HOST || 'http://localhost:8084';
> var bakeryDetailUrl = process.env.BAKERY_DETAIL_URL || (gateHost + '/bakery/logs/{{context.region}}/{{context.status.resourceId}}');
> var authEndpoint = process.env.AUTH_ENDPOINT || (gateHost + '/auth/user');
> var authEnabled = process.env.AUTH_ENABLED === 'false' ? false : true;
> var netflixMode = process.env.NETFLIX_MODE === 'true' ? true : false;
> var chaosEnabled = netflixMode || process.env.CHAOS_ENABLED === 'true' ? true : false;
> var fiatEnabled = process.env.FIAT_ENABLED === 'true' ? true : false;
> var entityTagsEnabled = process.env.ENTITY_TAGS_ENABLED === 'true' ? true : false;
> var debugEnabled = process.env.DEBUG_ENABLED === 'false' ? false : true;
> var canaryEnabled = process.env.CANARY_ENABLED === 'true';

halconfig/settings.js needs to be merged with settings.js.

**Comment by lwander** [comment]
If you make the necessary changes I'll publish the updated settings.js & halyard debian
