### ISSUE TITLE
XPN support on GCE breaks server group wizard/security group display

### ISSUE THREAD

**Issue by awithersdd** [spinnaker/spinnaker#1831]
*Cloud Provider*

GCP

*Environment*

Ubuntu 16.04.2 from packages (latest release as of today)
```
  ii  spinnaker                        0.82.0                                     all          spinnaker
  ii  spinnaker-clouddriver            1.650.0                                    all          spinnaker-clouddriver
  ii  spinnaker-deck                   2.1127.0                                   all          spinnaker-deck
  ii  spinnaker-echo                   1.139.0                                    all          spinnaker-echo
  ii  spinnaker-fiat                   0.27.0                                     all          spinnaker-fiat
  ii  spinnaker-front50                1.99.0                                     all          spinnaker-front50
  ii  spinnaker-gate                   3.44.0                                     all          spinnaker-gate
  ii  spinnaker-igor                   1.71.0                                     all          spinnaker-igor
  ii  spinnaker-orca                   2.14.3                                     all          spinnaker-orca
  ii  spinnaker-rosco                  0.96.0                                     all          spinnaker-rosco
```
*Feature Area*

Deck, pipeline, deploy, edit a cluster

*Description*

I expect to see the cluster wizard popup with security group information.

What I see when the SG has a tag without a corresponding security group in securityGroupObjectsKeyedByTag: It hangs, the loading indicator just spins.

Even when it works the information in Security Groups is empty (when it shouldn't be).

*Steps to Reproduce*

You can reproduce by simply:
1. Create pipeline, find image, deploy
2. Create a SG that has tags that will get you some security group
3. Save
4. Edit pipeline and cluster
5. Note missing Security Groups

If you happen to have a tag that has no security group mapping then you won't be able to load the edit screen until you edit the JSON and remove it.

e.g. 
```
...
"tags": [
            "tagwithsg",
            "tagwithoutsg"
          ],
...
```
*Additional Details*

I put a comment in the code that I believe causes this:

https://github.com/spinnaker/deck/commit/7d0d532a9750238ae66726e6bc73f6bbdc37f88b#diff-63bfd4e147030a147bb2273b89286d07R36

This is our workaround for now:

```
    this.inferSecurityGroupIdsFromTags = function () {
        var commandTags = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
        return _lodash2.default.chain(commandTags).map(function (t) {
            return _this.securityGroupObjectsKeyedByTag[t.value];
        })
        .flatten()
        .filter(function (sg) {
            return sg !== undefined && sg.network === _this.command.network;
        })
        .map('id').compact().uniq().value();
    };
```

The only change is to call flatten() before filter (so it flattens out the security groups) and then to handle cases where a security group didn't match the tag (by filtering out undefined).

**Comment by danielpeach** [comment]
Just reproduced this - thanks. Should be a quick fix.
