### ISSUE TITLE
Kubernetes - Run Jobs Logs

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1832]
*Title*

Kubernetes - Run Jobs Logs

*Cloud Provider*

Kubernetes 

*Feature Area*

Pipelines - Run Job Stage

*Description*

Out of the box, the Run Job stage doesn't provide any way to debug failures. The current implementation doesn't capture the output from the Pod and and deletes the pod on Success or Failure. By the time you see a failure in the pipeline, the Pod is already gone.  This stage has been improved recently to provide various ways to annotate/label the Pods so that log forwarders can pick them up, but that forces users to configure external services to accommodate this and pushes them outside of Spinnaker to debug. 

Ideally, Spinnaker would capture the output of the Pod and store it off somewhere before deleting the Pod. We could then render those logs in the execution details section or perhaps via modal. 

I've seen more folks mention this in Slack as an issue lately and I think it would be a huge improvement.

@danielpeach I'm filing this so we have something to reference when it comes up.

**Comment by carllhw** [comment]
Any progress?

**Comment by nfirvine** [comment]
Bump. This makes Jobs useless IMO.

**Comment by bernardoVale** [comment]
@nfirvine you mean without this feature right?

**Comment by nfirvine** [comment]
@bernardoVale Yes, updated.

**Comment by bernardoVale** [comment]
awesome!!!!!

**Comment by saokar** [comment]
Using halyard to deploy Spinnaker. Will this change be available in version 1.5?
