### ISSUE TITLE
Kubernetes Headless Services cannot be created in Spinnaker

### ISSUE THREAD

**Issue by emptywee** [spinnaker/spinnaker#1836]
*Title*

A headless service in Kubernetes cannot be created in Spinnaker. Clouddriver requires a valid IP address or blank string submitted when creating a service (Load Balancer). However, per Kubernetes docs it should and will accept "None" as a value to create a headless service.

*Cloud Provider*

Kubernetes

*Environment*

Self-hosted kubernetes cluster.

*Feature Area*

Clouddriver

*Description*

Entering "None" in the Spinnaker UI when creating/modifying a load balancer should create/make the service headless. 

See https://kubernetes.io/docs/concepts/services-networking/service/#headless-services for more details on what headless service is.

In reality the following error is shown:

```
Error:

upsertKubernetesLoadBalancerAtomicOperationDescription.clusterIp.invalid (Not valid IPv4 address)
```

*Steps to Reproduce*

Create a new load balancer and enter "None" as Cluster IP. Click "Create"

**Comment by ethanfrogers** [comment]
This should be an easy fix. 

Offending line: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/loadbalancer/UpsertKubernetesLoadBalancerAtomicOperationValidator.groovy#L61

We just need to check if the value is `None` before validating a valid IPV4 address.

**Comment by emptywee** [comment]
May require proper translation of the string "None" from the UI to the type None for Kubernetes. Just a guess here.

**Comment by ethanfrogers** [comment]
@emptywee according to the K8S API and the underlying client library that Clouddriver uses, `clusterIp` is just a `String` so anything that isn't `None` will be validated as an IP address.

**Comment by emptywee** [comment]
Awesome. Then it should be easy. :)

**Comment by emptywee** [comment]
Will test and close if it works.

**Comment by emptywee** [comment]
Works perfectly! Many thanks to @ethanfrogers ! Closing the issue.
