### ISSUE TITLE
Bake Pipeline Concurrent execution

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1848]
Provider: AWS

I have a pipeline with one single bake stage. when I uncheck  the "Disable concurrent pipeline executions (only run one at a time)." option and try to run the same pipeline twice in one go , I see that the pipeline starts both for two, but one gets cancelled and other keeps running and succeeds later. Why does not both runs parallelly ?

Also I tried with triggering 5 times, but still it makes only one pipeline to be run and fails the others.

Rosco version: 0.94

**Comment by veeresh1982** [comment]
![pasted image at 2017_07_19 07_26 pm](https://user-images.githubusercontent.com/6929267/28424442-7fae8aa6-6d22-11e7-8a99-8c2feed2373b.png)

**Comment by veeresh1982** [comment]
Checking rosco and orca logs, it seems that rosco service is the once which cancels the job

`07-20 17:54:37.699 DEBUG 1757 --- [io-8087-exec-10] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /api/v1/us-west-2/bake
2017-07-20 17:54:37.699 DEBUG 1757 --- [io-8087-exec-10] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public com.netflix.spinnaker.rosco.api.BakeStatus com.netflix.spinnaker.rosco.controllers.BakeryController.createBake(java.lang.String,com.netflix.spinnaker.rosco.api.BakeRequest,java.lang.String)]
2017-07-20 17:54:37.699 DEBUG 1757 --- [io-8087-exec-10] m.m.a.RequestResponseBodyMethodProcessor : Reading [class com.netflix.spinnaker.rosco.api.BakeRequest] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@95d5d24]
2017-07-20 17:54:37.805  INFO 1757 --- [io-8087-exec-10] c.n.s.rosco.jobs.local.JobExecutorLocal  : Canceling job 65db3cae-30d4-4800-876e-f737fed052d1...`

Orca logs:
`2017-07-20 17:54:50.311  INFO 23797 --- [askExecutor-117] c.n.s.orca.bakery.tasks.MonitorBakeTask  : Pipeline:8e1ceea5-a4d6-461d-b1db-407b3e96105f monitorBake TERMINAL -- Batch step id: 1552,  Task Outputs: {
  "status" : {
    "id" : "65db3cae-30d4-4800-876e-f737fed052d1",
    "state" : "CANCELED",
    "result" : "FAILURE",
    "resourceId" : "65db3cae-30d4-4800-876e-f737fed052d1"
  }
},`

Checking if setting this value helps in rosco.yml
`  @Value('${rosco.polling.waitForJobStartTimeoutMillis:5000}')
  long waitForJobStartTimeoutMillis`

**Comment by duftler** [comment]
Are you enabling 'Force Rebake' (aka 'Rebake image without regard to the status of any existing bake')?

Rosco calculates a bake key for each bake request. If a new bake request, with force rebake enabled, is determined to have the same bake key as an existing bake request the prior bake request will be cancelled. The reason for this is that the bake key is used to dedupe bake requests and no future bake request will resolve to the prior (in-flight) bake once the newer bake request is received.

**Comment by duftler** [comment]
If force rebake is not enabled, you should see that the uuid for the new bake request (you can find this by clicking on 'View Bakery Details') should match that of the in-flight bake request.

**Comment by duftler** [comment]
The relevant logic lives here: https://github.com/spinnaker/rosco/blob/master/rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy#L168-L174

**Comment by veeresh1982** [comment]
I am enabling "Force Rebake" on every run of the pipeline. But when I rebake enable each time, I see a unique/different bake key. 

So to explain my testing, consider below iteration

Iteration: Three back to back bake pipelines being triggered
------------------------------------------------------------------
A) Test-1: Ran all three pipelines with rebake=false
Result: 
1. All pipelines succeeded.
2. bake keyid remains same for all three pipelines:6daf2757-fb98-41ea-9c16-a8936b198d8f

B) Test-2: Ran 1 with (rebake=true) and next 2,3 with (rebake=false)
Result: 
1. All pipelines succeeded.
2. bake keyid remains same for all three pipelines:18bff5d7-4b86-4672-8422-291c3eff55ae

C) Test-3: Ran all 3 with (rebake=true)
Result: 
1. Pipeline-3 got succeeded and previous 2,1 got failed
2. bake keyid remains different for all three pipelines
3. bake pipeiline-1:13dfab9d-952b-42f5-b9c7-ca007859973b <failed>
4. bake pipeiline-2:2e2fe2c5-9b0d-4af2-8af2-37c32249c0ff <failed>
5. bake pipeiline-3:83bdeb5f-dfbb-4c7d-909c-9fcb7eb8dace <success>

So Test-A and Test-B looks OK
However Test-C even though the keyids are unique, is it an expected result to fail ?

My use-case:
--------------
I don't populate "package field in the bake stage", since we trigger bake stage using a jenkins job which invoke a boot script within packer instance  to download all our rpms needed to install and bake that image. so every run of the pipeline, it may pick-up a new/updated rpms.

**Comment by duftler** [comment]
The paths you described above are working as intended.

Btw, the uuid is not the bake key. You can see the actual calculated bake key by interrogating redis. A new uuid is generated for any new in-flight bake; if a bake request's key matches a prior or in-flight bake request, that bake request's uuid is used instead of generating a new one. Details on troubleshooting bakes (including finding the bake key) can be found here: https://medium.com/@duftler/troubleshooting-spinnaker-rosco-bakes-c0c600aa3598

Some suggestions on how to address your use case can be found here: https://blog.spinnaker.io/spinnaker-rosco-deduping-logic-e03716e04a30

**Comment by veeresh1982** [comment]
@duftler : The above solution works perfectly with my sample bake pipeline. Tomorrow I am going to have it done for the actual pipeline, but yes this should solve my user- case :). Thanks and keep you update.

**Comment by duftler** [comment]
Glad it worked out.
