### ISSUE TITLE
New added docker registry doesn't show in automated trigger configuration of portal

### ISSUE THREAD

**Issue by VincentLiu028** [spinnaker/spinnaker#1858]
Hi,
I added a docker registry provider use command 
hal config provider docker-registry account add my-docker-registry --address --repositories  --username --password
Add I could see it show up with list command.
Then I went to spinnaker portal and try to add an automated trigger with docker registry, 
I don't see the new registry I added,
I checked hal config , the new registry account is added. but clouddriver.yml didn't not get updated. 
How could I get clouddriver.yml updated.

**Comment by lwander** [comment]
Have you rerun `hal deploy apply`?

**Comment by VincentLiu028** [comment]
Thanks for your information.
I ran hal deploy apply then I got below error 

Problems in Global:
! ERROR Could not parse connection information from:
()
Then I run hal deploy apply again

Problems in Global:
! ERROR Failed to monitor task: timeout

**Comment by lwander** [comment]
Seems something is off with your k8s cluster - where is it running?

**Comment by VincentLiu028** [comment]
K8s is deployed on Azure version is 1.6.6, one master and one agent.
I find an older spin-redis-bootstrap pod hang in terminating status. The other pods of spinnaker are running. I manully delete this pod.  Then I verified in the portal then my pipeline works as expect.  I kick off hal deploy apply again. At last I get error Failed to monitor task: timeout.
Then I view the pod status I found many pods are in unknown or pending status.

spin-clouddriver-bootstrap-v000-0w07v   0/1       Pending   0          50s
spin-clouddriver-bootstrap-v000-bfwr7   1/1       Unknown   0          10m
spin-clouddriver-v000-nhbjq             1/1       Unknown   0          23h
spin-clouddriver-v000-thtjp             0/1       Pending   0          50s
spin-clouddriver-v001-dgc1h             0/1       Pending   0          50s
spin-clouddriver-v001-zwmqm             0/1       Unknown   0          8m
spin-deck-v000-6snfq                    0/1       Pending   0          50s
spin-deck-v000-n0ktz                    1/1       Unknown   0          23h
spin-deck-v001-qmjp4                    0/1       Pending   0          50s
spin-deck-v001-z7tp7                    1/1       Unknown   0          8m
spin-echo-v000-jbswx                    0/1       Pending   0          50s
spin-echo-v000-r2bwk                    1/1       Unknown   0          23h
spin-echo-v001-mvzrv                    1/1       Unknown   0          8m
spin-echo-v001-xd28b                    0/1       Pending   0          49s
spin-front50-v000-9h0s9                 1/1       Unknown   0          23h
spin-front50-v000-mv8t7                 0/1       Pending   0          49s
spin-front50-v001-1cznj                 0/1       Unknown   0          8m
spin-front50-v001-7n4v0                 0/1       Pending   0          49s
spin-gate-v000-1wvgj                    0/1       Pending   0          49s
spin-gate-v000-jwg2r                    1/1       Unknown   0          23h
spin-gate-v001-26dvx                    1/1       Unknown   0          8m
spin-gate-v001-d8zl9                    0/1       Pending   0          49s
spin-igor-v000-prthl                    1/1       Unknown   0          23h
spin-igor-v000-zd06m                    0/1       Pending   0          49s
spin-igor-v001-639kz                    1/1       Unknown   0          8m
spin-igor-v001-7fc3d                    0/1       Pending   0          48s
spin-orca-bootstrap-v000-83vhf          0/1       Pending   0          48s
spin-orca-bootstrap-v000-zg7nw          1/1       Unknown   2          9m
spin-orca-v000-7bs5v                    0/1       Pending   0          48s
spin-orca-v000-c1c9j                    1/1       Unknown   0          23h
spin-orca-v001-2zgb6                    0/1       Unknown   0          8m
spin-orca-v001-rx0z5                    0/1       Pending   0          48s
spin-redis-bootstrap-v000-mhx3g         1/1       Unknown   0          10m
spin-redis-v000-wcj2h                   1/1       Unknown   0          23h
spin-redis-v000-xqh7q                   0/1       Pending   0          48s
spin-rosco-v000-bcx2f                   0/1       Pending   0          48s
spin-rosco-v000-zn91n                   1/1       Unknown   0          23h
spin-rosco-v001-8cfdb                   0/1       Pending   0          48s
spin-rosco-v001-fqxzh                   1/1       Unknown   0          8m
And I find the agent is in not ready status. I suspect that agent ran out of resources due to too many containers on it. But why hal deploy apply will create more than two pods for same api

**Comment by lwander** [comment]
Seems it doesn't have enough resources - hal only specifies a target size of 1 by default for those clusters. I'm guessing you're seeing more than 1 because k8s is trying to overcome the fact that each of your pods are either "unknown" or "pending". I recommend deleting this namespace and growing the size of your underlying cluster.

**Comment by mlevitzzky** [comment]
Hi,
I'm trying to update spinnaker 1.6 to 1.7 but it fails on apply deploy.

hal config version edit --version 1.7.2
+ Get current deployment
  Success
+ Edit Spinnaker version
  Success
+ Spinnaker has been configured to update/install version "1.7.2".
  Deploy this version of Spinnaker with `hal deploy apply`.

hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
- Deploy spin-clouddriver
  Failure
- Deploy spin-front50
  Failure
- Deploy spin-orca
  Failure
- Deploy spin-deck
  Failure
- Deploy spin-echo
  Failure
- Deploy spin-gate
  Failure
- Deploy spin-igor
  Failure
- Deploy spin-rosco
  Failure
Problems in Global:
! ERROR Could not parse connection information from:

Have you idea what might be the issue?

Thanks!
