### ISSUE TITLE
Is it possible to support 'judgement' be used as an alias of 'judgment' in spEL?

### ISSUE THREAD

**Issue by yue9944882** [spinnaker/spinnaker#1862]
### Is it possible to support 'judgement' be used as an alias of 'judgment' in spEL?

I wasted lot of time trying spEL of 'Precondition Check' because I use 'judgement' instead of 'judgment' when using macros in the pipellines. Truely, I don't know the form of 'judgment' before I come to use spinnaker. And I admit that my vocabulary is sort of limited but wouldn't it be better if we can avoid to waste our time on something like this when experiencing spinnaker?

Btw, anyone has the same experience as mine? :-(

**Comment by tomaslin** [comment]
fixed with https://github.com/spinnaker/orca/pull/1487
