### ISSUE TITLE
Multiple env vars adjusted when removing one in some cases

### ISSUE THREAD

**Issue by bggpoort** [spinnaker/spinnaker#1866]
*Title*

Multiple env vars adjusted when removing one in some cases

*Cloud Provider*

GCP

*Environment*

Spinnaker 1.1.1 deploying to GCP

*Feature Area*

Deck
version: 1.3.0-135

*Description*

While removing a configured env var the one below was partially adjusted in some specific cases. I expect only the one I selected to be removed.

*Steps to Reproduce*

- Create a deployment containing two environment variables
- Have the first one of source secret
- Have the second one of source configmap
- Save
- Open deployment and remove the first env var

In my case the second one still exists but is of source secret containing no values. 

When the first one was configured to have source configmap and the second to have source secret the one left (the second one) after removal was changed to type configmap with no values. 

*Additional Details*

I did not see the behaviour in the following cases:

- Both env vars have source explicit
- Both env vars have source configmap
- Both env vars have source secret

**Comment by lwander** [comment]
Thanks for the detailed report - @danielpeach do you think this might be related to what @ethanfrogers has reported?
