### ISSUE TITLE
reconfigure_spinnaker.sh pulls incomplete/inconsistent config

### ISSUE THREAD

**Issue by ismith** [spinnaker/spinnaker#1868]
*Feature Area*

Deck config

*Description*

`settings.js` comments indicate that `This section is managed by scripts/reconfigure_spinnaker.sh`, which pulls in config from yml.  It is not clear without looking at `reconfigure_spinnaker.sh` and `reconfigure_spinnaker.py` that this _only_ loads data from `spinnaker.yml` and `spinnaker-local.yml`.  Thus, for instance, `var slackEnabled = ${services.echo.notifications.slack.enabled};`, which means to enable slack notifications, you edit `spinnaker-local.yml` (to enable the notifications UI in deck) and `echo-local.yml` (to enable notifications in the echo service).

This is kind of confusing, and feels like duplication of config; I feel like either deck should load all the relevant ymls (and get service-ui-specific-config from service config ymls), or deck should get this sort of config at load time from the service.

*Steps to Reproduce*

Confirmed with `sudo strace -f -e open ../scripts/reconfigure_spinnaker.sh` that only `spinnaker.yml` and `spinnaker-local.yml` are being loaded.

(Might also be illuminating to rename that file `reconfigure_deck.sh` or something, since that's what it actually does?)

**Comment by lwander** [comment]
I don't think that script is being actively maintained anymore with Halyard taking its place. Maybe it's time to formally deprecate? @ewiseblatt thoughts?

**Comment by ewiseblatt** [comment]
I am locked out of github at the moment to see the context of this message.
However reconfigure_spinnaker.sh was obsoleted by Halyard.

**Comment by ismith** [comment]
I came across it because settings.js exists in my /opt/spinnaker/config directory along with all my other config files, and settings.js has a comment:
```
/**
 * This section is managed by scripts/reconfigure_spinnaker.sh
 * If hand-editing, only add comment lines that look like
 * '// var VARIABLE = VALUE'
 * and let scripts/reconfigure manage the actual values.
 */
```

(https://github.com/spinnaker/spinnaker/blob/master/config/settings.js#L5)

**Comment by lwander** [comment]
Made obsolete by release of Halyard
