### ISSUE TITLE
(Deck/Jenkins) Deck's Jenkins parameter functionality could use some improvement.

### ISSUE THREAD

**Issue by Atchuu** [spinnaker/spinnaker#1872]
*Title*

Deck's Jenkins task treat all parameters like simple strings, limiting it's usefulness.

*Feature Area*

Deck/Jenkins

*Description*

When using the Jenkins pipeline task, all parameters get loaded in Deck as simple strings. I believe this causes issues with security and compatibility.

Security: Parameters such as password parameters, as bad as they are to use, are exposed in plain text in the Deck and services like Orca.

Compatibility: Jenkins provides support for quite a large amount of parameter types, and not every one can be fully utilized by simple strings. (Multi-Line parameters being one). Choice parameters will only allow pre-entered choices, which requires creators/maintainers of Spinnaker pipelines to know the available options when using Spinnaker pipelines with Jenkins tasks.

I read that Angular is being replaced with React, so I kept the proposed changes as consolidated as I could.

*Additional Details*
If this seems like something that would be useful, I'll create a PR with my changes for review.

Proposed changes to Jenkin's Tasks UI:
<img width="680" alt="screen shot 2017-08-01 at 10 14 44 am" src="https://user-images.githubusercontent.com/3680008/28829612-58519d66-76a2-11e7-8361-864690e00fa7.png">

Loaded from a Jenkins job:
<img width="466" alt="screen shot 2017-08-01 at 10 06 03 am" src="https://user-images.githubusercontent.com/3680008/28829232-108c021a-76a1-11e7-9cb9-6009f6a6e398.png">

**Comment by Atchuu** [comment]
To be clear, I have made the changes locally by extending the angular html code responsible for this piece of the UI by adding a ng-switch div within the parameter loop. Using the parameter type (which is already recorded by Igor and available to Deck) it switches into input/textarea/ui-selecct elements, while the default is left as the previous input+text to prevent breakages with older functionality.

**Comment by anotherchrisberry** [comment]
This looks great - would love to see a PR!

**Comment by Atchuu** [comment]
PR created.

I welcome any criticisms/recommendations.

https://github.com/spinnaker/deck/pull/3972

**Comment by anotherchrisberry** [comment]
Resolved/released in https://github.com/spinnaker/deck/releases/tag/v2.1130.0

**Comment by anotherchrisberry** [comment]
Thanks!!!
