### ISSUE TITLE
Difficulty creating server group with two similarly-named images in UI

### ISSUE THREAD

**Issue by ngaya-ll** [spinnaker/spinnaker#1880]
*Cloud Provider*

Kubernetes (+ AWS)

*Environment*

Probably not relevant

*Feature Area*

Web UI

*Description*

The UI obstructs the user from creating a server group with two similarly-named Docker images.

*Steps to Reproduce*

1. Create two Docker images sharing a name prefix (e.g. foo-a and foo-b).

2. In the Spinnaker UI, navigate to the "Clusters" view and select "Create Server Group"

3. Select Kubernetes provider

4. Under "Basic Settings" --> "Containers", add image foo-a.

5. Under "Basic Settings" --> "Containers", attempt to add image foo-b.  foo-b will replace foo-a in the list of containers.  It is apparently not possible to add both foo-a and foo-b.

*Additional Details*

As a workaround, the user can select two images with dissimilar names, then change one of the images using the "Container" --> "Image" field towards the bottom of the UI.

**Comment by ethanfrogers** [comment]
This can _easily_ be replicated by creating a Server Group using `library/nginx`. Even starting to type `nginx` causes the first container to get removed.

**Comment by ethanfrogers** [comment]
@danielpeach it looks like this is default behavior for `ui-select`. It doesn't allow the same selection twice.
