### ISSUE TITLE
Enhancement: Allow to define a specific time zone for triggers

### ISSUE THREAD

**Issue by nonotest** [spinnaker/spinnaker#1886]
*Title*

In some cases you need to be able to trigger pipelines using cron jobs that are in a different time zone as the UI. Because of daylight savings issues it can be unreliable to just calculate the time difference manually.

This is probably not useful to too many people but certainly a nice addition.

*Feature Area*

Pipelines / Triggers

*Description*

Allow an extra field to specify a timezone different than the one set in the deck config.

**Comment by lwander** [comment]
This is already supported: https://www.spinnaker.io/reference/halyard/commands/#hal-config-edit

**Comment by nonotest** [comment]
Hello,
I don't believe this does what I am suggesting:

`this affects what the UI will display as well as how CRON triggers are run.`
there is still just one timezone for the ui and the cron.

Example:
I want my UI to display in "Europe/Paris" and I want one cron to run on "Australia/Perth"

**Comment by lwander** [comment]
Oh sorry, I see what you mean. You can override the cron behavior using a [custom profile](https://spinnaker.io/reference/halyard/custom) for `echo-local.yml` by setting `scheduler.cron.timezone: `. This will only affect cron triggers.

**Comment by nonotest** [comment]
thanks! that will serve my purpose since I only ever need 2 time zones for this app.

Maybe in a future version it would still be good to be able to set the cron trigger timezone in the pipeline definition, but not sure how hard that would be.

Cheers,
