### ISSUE TITLE
403 on Catalog endpoint when installing in new GCP project 

### ISSUE THREAD

**Issue by viglesiasce** [spinnaker/spinnaker#1891]
*Environment*
Google Container Engine

Using the steps here to install Spinnaker 1.1.0:
https://github.com/viglesiasce/gke-info/blob/master/tests/scripts/install-spinnaker.sh

*Feature Area*
Catalog endpoint in CloudDriver

*Description*
My images are not showing up in the Spinnaker UI, in the logs of CloudDriver I am seeing:
2017-08-09 18:42:36.737  WARN 1 --- [ecutionAction-6] c.n.s.c.d.r.a.v.c.DockerRegistryClient   : Error encountered during catalog of null403 Forbidden

*Steps to Reproduce*

1. Create a new GCP project
2. Run the script from [here](https://github.com/viglesiasce/gke-info/blob/master/tests/scripts/install-spinnaker.sh) 
3. Create an application, then try to create a trigger with an image from your project.
4. No images are shown.

**Comment by lwander** [comment]
@skim1420 is this what you saw earlier today?

**Comment by skim1420** [comment]
I saw this:

Problems in default.provider.dockerRegistry.my-gcr-account:
! ERROR Your docker registry has no repositories specified, and the
  registry's catalog is empty.
? Manually specify some repositories for this docker registry to
  index.

..which seems related. It's okay to not specify repositories, but I haven't investigated exactly why the catalog came back empty. Possibly a 403, but haven't looked.

**Comment by lwander** [comment]
The halyard logs should give more context

**Comment by viglesiasce** [comment]
I set the image repository explicitly and that worked as expected. Sounds like this is an issue purely with the catalog endpoint.

**Comment by viglesiasce** [comment]
This was caused by not having the Cloud Resource Manager API enabled. This is a new requirement for using the catalog endpoint in Google Container Registry.

**Comment by stevemcghee** [comment]
this cost me a few hours today in setting up via: https://www.spinnaker.io/setup/quickstart/halyard-gke/

perhaps a doc fix is at least in order?

**Comment by lwander** [comment]
@dorbin

**Comment by james-woods** [comment]
I want to personally sent you a DEFI Sticker right now @viglesiasce I was pulling my hair out all morning about this

**Comment by viglesiasce** [comment]
@james-woods!!! Long time no see. DEFInitely happy that I could help 😀

**Comment by dorbin** [comment]
https://github.com/spinnaker/spinnaker.github.io/issues/711

**Comment by vtajzich** [comment]
> This was caused by not having the Cloud Resource Manager API enabled. This is a new requirement for using the catalog endpoint in Google Container Registry.

This should be mentioned in install guide!
