### ISSUE TITLE
ACA task is failing immediately(Kubernetes)

### ISSUE THREAD

**Issue by veerendra2** [spinnaker/spinnaker#1904]
### *Description*
ACA stage is failing with error `Canary failure: No StageDefinitionBuilder implementation for acaTask found` in GUI (Attched Screenshots)
### *Cloud Provider*
Kubernetes
### *Environment*
Running Dev-Spinnaker in `aws`
### *Feature Area*
ACA Stage
### *Description*
ACA stage failing immediately with no score. Added logs links below. Configured pipeline like below

`Docker Trigger` -- > `Deploy(on K8s)` --> `ACA Stage`

Because of this [bug](https://github.com/spinnaker/spinnaker/issues/1814), I was not able to add the `account` in ACA stage GUI. So, I have updated `account` with API (http://localhost:8084//applications/test10/pipelineConfigs/ACA)

### *Steps to Reproduce*
Clone the Dev-spinnaker; I followed the installation steps [here](https://github.com/spinnaker/spinnaker#ubuntu-linux). Configure the pipeline and add the `account` like I said in description. 

### Screen Shots.
![ACA Stage Error](https://image.ibb.co/im5Bga/Screenshot_from_2017_08_18_14_04_43.png?raw=true "Optional Title")

### Logs
[Downloads logs tar file](https://drive.google.com/file/d/0B06UXkXyC1hSME91SEZ5YnZDZXc/view?usp=sharing)

**Comment by lwander** [comment]
Obsolete by release of kayenta
