### ISSUE TITLE
feat(clouddriver/docker): Catalog Endpoint option

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1909]
The Clouddriver Docker implementation gives uses a couple of ways to specify which repositories they'd like to be able to deploy with Spinnaker:

1. List each repository by name in the Clouddriver configuration
2. Rely on the `/v2/_catalog` endpoint specified in the Docker Registry API spec. (https://docs.docker.com/registry/spec/api/#catalog)

Unfortunately, not all Docker registries are created equal. Some implement the Catalog endpoint and some do not. For example, Quay.io does not support the Catalog endpoint. This can be a problem for organizations using one of these registries, especially if they're pushing new services often. A pattern then emerges of having to add the repository to the Clouddriver configuration and then restarting Clouddriver. 

I think it might be nice to provide users a way of configuring a `catalogEndpoint` option for their registry such that Clouddriver uses that to get a list of all repositories it can deploy. Users can then implement their own "catalog service" that serves a list of repositories (conforming to the `/v2/_catalog` spec). In theory, this would allow organizations using registries like Quay.io to use Spinnaker without so much management overhead. 

In practice, a Spinnaker user might configure a Docker registry like so:

```
dockerRegistry:
  enabled: true
  accounts:
    - name: quay
       address: https://quay.io
       username: <username>
       password: <password>
       catalogEndpoint: http://my-catalog-service/v2/_catalog
```

Clouddriver would then use this option since the `repositories` option is missing. If the `catalogEndpoint` option is _also_ missing, it would fallback to the default behavior of trying to query the `/v2/_catalog` API of the registry provider.

### Potential Issues

One issue I can see with this approach is that the "catalog service" may expose more repositories than Clouddriver can access with the provided `username`/`password`. One way around this might be to implement a service that uses the same configuration as Clouddriver with the same credentials.

This might be a crazy idea but I wanted to throw it out there. @lwander WDYT?

**Comment by lwander** [comment]
This sounds good to me, but it also feels like it might be a lot of work for a user to implement. 

The goal is to make it easy to add/remove repositories w/o restarting clouddriver, right? What if we instead pointed to an object in a bucket with a list of repositories? I think that would be easier for a user to set up than a v2 compliant catalog endpoint, especially when you start dealing with auth.

**Comment by ethanfrogers** [comment]
Yep, that would be way easier. I'm a fan of that idea. Perhaps an object per `dockerRegistry`? 

I can still see the need for some glue if users wanted something more automated, though. To get the same behavior as `/v2/_catalog` there would need to be a process running somewhere that keeps each object in sync with the organizations they're interested in. For Dockerhub, that may be `library` and for Quay it may be `my-awesome-company`. But that's really outside the scope of this idea anyway. 

MVP for Clouddriver would be the addition of a  `catalog` (or something else) option that allowed users to point to an S3/GCS object that listed the repositories they're interested in. It may be best keep the object structure the same as `/v2/_catalog` so we at least have a _somewhat_ stable spec to point toward and we can reuse logic that already exists.
