### ISSUE TITLE
Replace all Frigga usage in Orca

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#1920]
See #1917

#1914
#1902

**Comment by lwander** [comment]
@andrewbackes

**Comment by andrewbackes** [comment]
These are the remaining open PRs:
https://github.com/spinnaker/orca/pull/1697
https://github.com/spinnaker/orca/pull/1703
https://github.com/spinnaker/orca/pull/1727
https://github.com/spinnaker/orca/pull/1732
https://github.com/spinnaker/orca/pull/1736

After these are complete I'm sure more will pop up as we make more headway on the new provider. But after these, the bulk of it should be done.

**Comment by lwander** [comment]
Nice!
