### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by zhuzhiyang** [spinnaker/spinnaker#1924]
About deployment,the spinnaker use pipelines,when a docker images changes,how to trigger the pineline 
again? use the webhooks to trigger  DockerEventMonitor?

**Comment by ethanfrogers** [comment]
@zhuzhiyang if your pipeline has the Docker Registry trigger enabled, it should trigger anytime a new tag is pushed to the registry. If it isn't check the Igor logs to make sure it's actually picking it up. You may have to enable `dockerRegistry.enabled` for Igor.
