### ISSUE TITLE
hal deploy clean confirmation prompt should be (y/N)

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker#1926]
Currently `hal deploy clean` responds with confirmation prompt `This command cannot be undone. Do you want to continue? (Y/n)`. The default is actually `n`, correctly, however the prompt should be `(y/N)` to indicate as such.

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/commit/3a5bcf0754de02bfcf0800a1d77ac1fc2b168c0f
