### ISSUE TITLE
Destroy Server Group stage can destroy any group instead of oldest/newest.

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spinnaker#1927]
*Title*

Destroy Server Group stage can destroy any group instead of oldest/newest.

*Cloud Provider*

DC/OS

*Environment*

Running Spinnaker from latest Docker images.

*Feature Area*

Destroy Server Group stages

*Description*

Expected: When a pipeline for a DC/OS application has Destroy Server Group stage to destroy the oldest or newest, only the oldest or newest should be destroyed.
Actual: Any server group may be destroyed

*Steps to Reproduce*

* Create a DC/OS cluster with multiple server groups.
* Run a pipeline that should destroy either the oldest or newest.

*Additional Details*

I think this issue was introduced very recently with https://github.com/spinnaker/clouddriver/commit/ca5329e8fd3049cf560ac0e5e427788d4b67eefa#diff-b4daa3aa77b6e99a84a8cf9d4ff44ef3R204. The server groups being sorted no longer have all details loaded.  For DC/OS (and possibly Kubernetes?) this means that there is no `createdTime` and so the sort order is undefined.

If there's no reason that the server groups should be sorted before loading the details, I propose moving the sort until after the details have been loaded for the filtered server groups.  If this is acceptable I can submit a patch.

**Comment by ajordens** [comment]
Sorting after details have been loaded sounds reasonable to me.

**Comment by willgorman** [comment]
Closing this since it was fixed by https://github.com/spinnaker/clouddriver/pull/1842 instead.
