### ISSUE TITLE
Not a supported operating system:  Debian

### ISSUE THREAD

**Issue by davideuler** [spinnaker/spinnaker#1959]
*hal deploy apply Error: Not a supported operating system:  Debian*

I am running spinnaker on docker to deploy images to kubernetes (via minikubernetes) on my MacOS.

When I run "hal deploy apply" finally. it shows error as:

**root@d305e7bc8970:/workdir# hal config version edit --version 1.3.0**
+ Get current deployment
  Success
+ Edit Spinnaker version
  Success
+ Spinnaker has been configured to update/install version "1.3.0".
  Deploy this version of Spinnaker with `hal deploy apply`.

**root@d305e7bc8970:/workdir# hal deploy apply**

+ Get current deployment
  Success
+ Apply deployment
  Success
Problems in default.provider.kubernetes.developer:
- WARNING You have not specified a Kubernetes context in your
  halconfig, Spinnaker will use "dev-frontend" instead.
? We recommend explicitly setting a context in your halconfig, to
  ensure changes to your kubeconfig won't break your deployment.
? Options include:
  - dev-frontend
  - dev-storage

+ Run `hal deploy connect` to connect to Spinnaker.
Not a supported operating system:  Debian
It's recommended you use Ubuntu 14.04 or higher.

Please file an issue against https://github.com/spinnaker/spinnaker/issues
if you'd like to see support for your OS and version
! ERROR Error encountered running script. See above output for more
  details.

**Comment by lwander** [comment]
You need to set your environment to Kubernetes https://www.spinnaker.io/setup/install/environment/#distributed

**Comment by davideuler** [comment]
Hi Iwander, Thanks for your help. 

I follow the steps to configure kubernetes, then the error shows as the above thread. And the 2 commands works.
# kubectl get namespaces
# kubectl get pods

Any ideas what's the problem?

**#cat config-demo**

apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.hal/ca.crt
    server: https://192.168.64.6:8443
  name: development
contexts:
- context:
    cluster: development
    namespace: frontend
    user: developer
  name: dev-frontend
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage
current-context: ""
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: /root/.hal/client.crt
    client-key: /root/.hal/client.key


kubectl config --kubeconfig=config-demo set-cluster development --server=https://192.168.64.6:8443/ --certificate-authority=/root/.hal/ca.crt
kubectl config --kubeconfig=config-demo set-credentials developer --client-certificate=/root/.hal/client.crt --client-key=/root/.hal/client.key


kubectl config --kubeconfig=config-demo set-context dev-frontend --cluster=development --namespace=frontend --user=developer
kubectl config --kubeconfig=config-demo set-context dev-storage --cluster=development --namespace=storage --user=developer


**Set the current context:**
kubectl config --kubeconfig=config-demo use-context dev-frontend

kubectl config --kubeconfig=config-demo view --minify

export KUBECONFIG=config-demo

kubectl config view

kubectl get namespaces

cp config-demo ~/.kube/config

hal config provider kubernetes enable

**Comment by lwander** [comment]
You need to add an account like shown here: https://www.spinnaker.io/setup/providers/kubernetes/#adding-an-account

And then configure hal to use it like shown here: https://www.spinnaker.io/setup/install/environment/#required-hal-invocations-1
