### ISSUE TITLE
RunJob stage UI doesn't allow for Find Image from Cluster

### ISSUE THREAD

**Issue by ismith** [spinnaker/spinnaker#1960]
*Cloud Provider*

Kubernetes

*Environment*

spinnaker-deck deb is 2.1115.0

*Feature Area*

Pipelines/Deck

*Description*

I expect that in a RunJob stage, I can use an image from a previous Find Image from Cluster stage.  (Deploy stages can do this; RunJob doesn't have this UI.)

Currently working around by editing the pipeline json directly, replacing the contents of `imageDescription` with:
```
          "cluster": "[redacted]",
          "fromContext": true,
          "fromTrigger": false,
          "imageId": "[redacted] undefined",
          "repository": "Find Image from Cluster",
          "stageId": "3"
```

This works, in that I can run the pipeline and it completes successfully.  It does, however, fail to validate in the pipeline UI; the pipelineConfigurerCtrl.warningsPopover button tells me that `Tag is a required field for RunJob stages`.

**Comment by lwander** [comment]
👍 this is a good point. As it stands, the run job stage has a number of improvements coming - I'll create a tracking issue and link to it here.

**Comment by ethanfrogers** [comment]
@lwander can you close this issue for me?
