### ISSUE TITLE
Improve run job stage for Kubernetes

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#1961]
This is a tracking bug. 

The run job stage can be improved in a number of ways for the k8s provider, starting with

1. Proper support for streaming logs to the UI/a configured bucket
2. Proper support for extracting job results and placing them in the pipeline context

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker/issues/1960

**Comment by ethanfrogers** [comment]
I've been thinking about improvements to this stage for a while. One thing I've noticed is that when we add support for more fields, they're generally added to both the Run Job stage and the Deploy stage. Maybe we could consolidate the views, leaving out the Deployment Strategy/Replica options for Run Job. We'd get "Images from Trigger" and "Images from Cluster" OOB, as well as an improved UX.

I have a bit of a discovery/design doc that I could share WRT job logs. @danielpeach and I have talked about how to implement and some potential issues before. If you'd like to see it, I can clean it up and share!

Let me know if there's anything we can do!

**Comment by lwander** [comment]
Sharing the doc would be great! could you share with spinnaker-sig-kubernetes@googlegroups.com?

**Comment by ethanfrogers** [comment]
I've shared the doc with the SIG. It's still kind of rough, but includes a basic problem statement as well as some potential solutions.

**Comment by lwander** [comment]
Awesome, will read in detail soon

**Comment by katrielt** [comment]
Another possible improvement can be supporting resource management (CPU and RAM) in the pipeline stage. Alternatively, supporting the whole Pod spec might be useful.

**Comment by lwander** [comment]
Agreed.

**Comment by ethanfrogers** [comment]
I have clearance to prioritize some of this work in an upcoming sprint. If we can nail down where to start, I don't mind trying to tackle it. Perhaps the UI work would be a good place to start while we flesh out the requirements to the logging story.

**Comment by lwander** [comment]
I agree that the UI work (minus log display) is a good place to start. Making sure other pod spec features are surfaced feels important.

**Comment by rosskevin** [comment]
@lwander - another improvement for kubernetes - A job should allow multiple containers (for sidecar pattern).

Example - GKE rails db:migrate:
- container 1 - rails code - cmd: `bundle exec rake db:migrate`
- container 2 - `cloud_sql_proxy` - cmd: `cloud_sql_proxy`

As-is, I cannot run a sidecar pattern which is recommended by GCP for execution of a job.

**Comment by ryan-mf** [comment]
I'm actually in the same spot as @rosskevin. I need to add a db migrate job stage to a pipeline, and our POD needs the Cloud SQL proxy sidecar. In the meantime, my plan tomorrow is to just run it as a deployment with a single replica and make the readiness check the same db migrate command (waiting 60 seconds to start checking, the migrate on POD startup is always very quick). That health check will exit zero or non zero depending on if the migrate state is ok or not, which will allow or prevent the stage to succeed. In a later stage in that same pipeline, I then delete the earlier one replica deployment. A bit hacky but that's the plan until we have full job and sidecar support.

**Comment by rosskevin** [comment]
@ryan-mf I ended up with a dedicated service/pod. [Check out this doc](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md) and don't forget to add `0.0.0.0` to your instances arg.

**Comment by ryan-mf** [comment]
@rosskevin yep we heavily use the Cloud SQL proxy already in our PODs with our main application, so definitely familiar with that. Our new requirement is to run a **single**, basically identical replica earlier in the pipeline that runs DB migrations before all the high-quantity replicas start up later and try to all run migration simultaneously, stepping on each other, which causes random migration issues due to the inability to lock on schema updates.

I suppose our hacky workaround will suffice, but I'm definitely looking forward to seeing more advanced job support in Spinnaker to make this cleaner.

**Comment by ethanfrogers** [comment]
I'd like to pick this up again and start thinking about logs for this stage. I've already done some work to get a sense for potential implementation [here](https://groups.google.com/forum/#!topic/spinnaker-sig-kubernetes/DetV_RHOtDI) but would like some more input from the community.

A couple of questions I'd like to pose:

1) Has anyone come up with a workaround/solution that they'd like to share? We annotate our Run Job stages and use [this Fluentd plugin](https://github.com/skuid/fluent-plugin-json-lookup) to forward the logs to an Elasticsearch index. If needed, we can lookup the logs there.
2) What would you like to see from a solution for this? A simple solution might be to provide a configurable link to some external logging platform that shows up in Deck when viewing this stage, for example. Other complex solutions might involve configuring a sidecar for Clouddriver and forwarding logs to some external storage, out of band from your current logging pipeline. 

If anyone has any other thoughts, please post them here!

**Comment by ethanfrogers** [comment]
I'm starting to work through some of the UI enhancements right now. Starting with adding the ability to use images found in Context. From there, I'll tackle multi-container jobs.

@danielpeach @lwander do you guys think it would be possible to introduce multi-container jobs without backwards incompatible changes?

**Comment by ethanfrogers** [comment]
@ryan-mf @rosskevin on the subject of multi-container Jobs: when you execute `cloudsql-proxy`, how does it know when to exit? According to my research, if you execute a proper Kubernetes Job, the Job isn't considered successful until all containers in the Pod exit with a `0` status code. Is this something you've managed to accomplish using Kubernetes directly?

**Comment by rosskevin** [comment]
Sorry @ethanfrogers - I haven't done it directly.  Once I found I couldn't execute with multiple, I bailed out and have a separate Service+Deployment for cloud_sql_proxy.

**Comment by ethanfrogers** [comment]
@rosskevin thanks for the reply! i'll need to dig into how it would behave using a bare Pod (which is what the Run Job stage currently does), but I suspect that the status of the Pod would _not_ be `Succeeded`.

**Comment by ethanfrogers** [comment]
@rosskevin @ryan-mf according to [this issue](https://github.com/kubernetes/kubernetes/issues/25908), that's not the way Jobs behave in Kubernetes and I'm hesitant to try to force that behavior with Spinnaker. We can add support for multiple containers with the understanding that if they don't _all_ exit, they'll just keep running.

**Comment by ethanfrogers** [comment]
aside from the logging story, most of this work is done now. the last thing on my list is to make deck support multiple containers.

fyi @rosskevin @ryan-mf @katrielt

**Comment by ethanfrogers** [comment]
I believe I've addressed all of the improvements for this Issue over the last few weeks. Here's a brief summary:

1. Reorganize the Run Job configuration.
2. Add support for _most_ of the Pod spec.
3. Support multi-container Jobs.
4. Record/View log output from Jobs.

I'm going to close this issue. We can reopen if necessary!
