### ISSUE TITLE
Redis timeouts on Front50 with redis 1.3.1 (Ozark)

### ISSUE THREAD

**Issue by owainlewis** [spinnaker/spinnaker#1976]
**Cloud Provider**
Kubernetes

**Environment**
Ubuntu 14.04 bare metal 1.3.1 (Ozark) deployed with Halyard.

**Description**

There appears to be issues with Redis as a persistent store in 1.3.1. It works in 1.2.2.

After fresh install of Spinnaker with Halyard, the UI freezes/hangs and eventually fails due to connection timeouts relating to persistent storage (Redis). 

Restarting front50 seems to temporarily resolve the issue for a few requests until it falls over again (connection timeouts)

The request below for example succeeds the first two times after restarting front50 then falls over.

```
curl -i http://localhost:8083/v2/applications/kube/pipelines?limit=3
HTTP/1.1 500
X-Content-Type-Options: nosniff
...
Connection: close

{
  "timestamp" : "2017-09-20T11:32:07.463+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "exception" : "retrofit.RetrofitError",
  "message" : "Failed to connect to localhost/127.0.0.1:8080"
}
```

**Downgrading to 1.2.2 seems to resolve the issue.**

**Steps to Reproduce**
Create a new Spinnaker deployment with Halyard. Use redis as the persistent store.

** Additional information **
Installed with 

```
hal config version edit --version=1.3.1
hal config provider docker-registry enable
hal config provider docker-registry account add docker ...
hal config provider kubernetes enable
hal config provider kubernetes account add my-kubernetes-account --docker-registries=docker
hal config storage edit --type redis
sudo hal deploy apply
```

**Comment by lwander** [comment]
Unfortunately we don't do any testing against the redis implementation since it does have some known issues. We'd like to deprecate it (@ttomsu has more details). If you need a local non-cloud storage solution I suggest you try [minio](https://www.minio.io/) in place of S3.

**Comment by owainlewis** [comment]
Thanks @lwander that makes sense. Maybe we should remove it as an option from the docs post 1.3.1. If you and @ttomsu think it makes sense, I'll create an issue to track. Happy to help with getting that done.
