### ISSUE TITLE
Clouddriver - NullPointerException when using context with Kubernetes Accounts

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1979]
*Title*

Clouddriver - NullPointerException when using context with Kubernetes Accounts

*Cloud Provider*

Kubernetes

*Environment*
N/A

*Feature Area*

provider/kubernetes

*Description*

When configuring Clouddriver with multiple Kubernetes accounts, `context` is used to identify their authentication properties within the `kubeconfig`. This is broken in recent Travis releases, though I can't quite nail down where the regression was introduced. It _is_ related to the introduction of the new Kubernetes client library. It looks each account's credentials get an instance of the Fabric8 client & the new client.

*Steps to Reproduce*

Configure a Kubernetes account using `context`. When Clouddriver tries to add the account, it fails by throwing a `NullPointerException`.

*Additional Details*

@lwander mentioned that he recently added support to the new client library but it hasn't been released at this time.

```
clouddriver_1  | 2017-09-21 01:44:44.354  INFO 1 --- [           main] c.n.s.c.security.ProviderUtils           : Adding accounts [gcloud, test2] of type KubernetesNamedAccountCredentials...
clouddriver_1  | 2017-09-21 01:44:44.896  WARN 1 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
clouddriver_1  | 2017-09-21 01:44:45.674  INFO 1 --- [           main] rnetesNamedAccountCredentialsInitializer : Could not load account gcloud for Kubernetes.
clouddriver_1  |
clouddriver_1  | java.lang.NullPointerException: null
clouddriver_1  | 	at io.kubernetes.client.util.KubeConfig.findObject(KubeConfig.java:219) ~[client-java-util-0.1.jar:na]
clouddriver_1  | 	at io.kubernetes.client.util.KubeConfig.setContext(KubeConfig.java:101) ~[client-java-util-0.1.jar:na]
clouddriver_1  | 	at io.kubernetes.client.util.KubeConfig.loadKubeConfig(KubeConfig.java:85) ~[client-java-util-0.1.jar:na]
clouddriver_1  | 	at io.kubernetes.client.util.Config.fromConfig(Config.java:103) ~[client-java-util-0.1.jar:na]
clouddriver_1  | 	at io.kubernetes.client.util.Config.fromConfig(Config.java:94) ~[client-java-util-0.1.jar:na]
clouddriver_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
clouddriver_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
clouddriver_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
clouddriver_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
clouddriver_1  | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1469) ~[groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:65) ~[groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesApiClientConfig.getApiCient(KubernetesApiClientConfig.groovy:37) ~[clouddriver-kubernetes-1.680.0-SNAPSHOT.jar:1.680.0-SNAPSHOT]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesApiClientConfig$getApiCient.call(Unknown Source) ~[na:na]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-2.4.7.jar:2.4.7]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesClientApiAdapter.<init>(KubernetesClientApiAdapter.groovy:67) ~[clouddriver-kubernetes-1.680.0-SNAPSHOT.jar:1.680.0-SNAPSHOT]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.v1.security.KubernetesV1Credentials.<init>(KubernetesV1Credentials.java:83) ~[clouddriver-kubernetes-1.680.0-SNAPSHOT.jar:1.680.0-SNAPSHOT]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials$Builder.buildCredentials(KubernetesNamedAccountCredentials.java:271) ~[clouddriver-kubernetes-1.680.0-SNAPSHOT.jar:1.680.0-SNAPSHOT]
clouddriver_1  | 	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials$Builder.build(KubernetesNamedAccountCredentials.java:320) ~[clouddriver-kubernetes-1.680.0-SNAPSHOT.jar:1.680.0-SNAPSHOT]
```

**Comment by ethanfrogers** [comment]
It looks like the workaround is to set a `current-context` in your `kubeconfig`. Following the stack trace, you can see the _potential_ error, here: https://github.com/kubernetes-client/java/blob/ef5b3c862711376be0172054c097dd7aa61f7be6/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L79-L85

**Comment by lwander** [comment]
@chasling

**Comment by rossedman** [comment]
@ethanfrogers can confirm. i also had to set current-context to make this work properly.

**Comment by ethanfrogers** [comment]
I feel like @lwander meant to ping @chlung

**Comment by chlung** [comment]
OK. I will take a look.  Are you place more than one kubernetes accounts in you spinnkaer-local.yml?

**Comment by ethanfrogers** [comment]
@chlung yes. the error presents when you configure multiple accounts using `context` to map them to a context within the `kubeconfig`. it might even happen if you had 1 account configured and your `kubeconfig` didn't have a `current-context` set. 

the bug might just be in the client library's assumption that _all_ kube config files have that property.

**Comment by chlung** [comment]
@ethanfrogers thanks for the info.  Is it common not having these context setting?  I am calling k8s-client api utilities to handle parsing the kubconfig file.  I need to talk @lwander about it.  I will get back with you.  thx.

**Comment by ethanfrogers** [comment]
i'm not sure if it's uncommon or not. if you're using the `context` property, `current-context` should be irrelevant. we've been programatically generating our `clouddriver-local.yaml` and `kubeconfig` from a common configuration so we left it out. the old client library didn't care if it was present or not.

thanks for following up!

**Comment by rossedman** [comment]
@chlung @ethanfrogers where this happened to me is when i removed clusters that were the current-context. the current-context was then not set, when deploying it then errored. i dont think thats a very common scenario.

**Comment by lwander** [comment]
Maybe it's not super-common, but it's a pretty severe bug. @chlung I will release a new version of the client library - can you make sure to integrate it correctly so it respects the `context` parameter in the credential config?

**Comment by chlung** [comment]
@lwander OK.  I will verify this issue once the client library is ready. thanks.
