### ISSUE TITLE
Support for markdown in pipeline comments

### ISSUE THREAD

**Issue by t0mpson** [spinnaker/spinnaker#2005]
- Markdown support was added to echo [in this PR](https://github.com/spinnaker/echo/pull/165).
- This is awesome and extremely useful to be able to provide formatted context in pipeline notifications.
- However, the comments section of pipelines, which are rendered in the UI currently do not support markdown (only HTML).  Would be very useful to have that also supported.

**Comment by t0mpson** [comment]
@anotherchrisberry Hi Chris, any chance of getting this included?

**Comment by anotherchrisberry** [comment]
Sure - this had slipped through the cracks but is addressed in https://github.com/spinnaker/deck/pull/4985

**Comment by anotherchrisberry** [comment]
Available in https://github.com/spinnaker/deck/releases/tag/v2.1181.0

**Comment by t0mpson** [comment]
Awesome Chris! I owe you a beer 👍🏼😎

**Comment by t0mpson** [comment]
@anotherchrisberry Hi Chris,

Sorry to nag, and thanks so much for the fix earlier.
The tooltip renders beautifully as markdown. 

However, adding the same markdown text to a Wait stage comment (or any other stage) doesn't render as markdown.

Any chance to add that as well?

![screen shot 2018-03-12 at 9 10 29 pm](https://user-images.githubusercontent.com/1511533/37304382-1b6c7fcc-263a-11e8-8bff-48f432082802.png)


Here's the pipeline json I tried:

```
{
  "description": "* test\n* test2\n## heading 2\n### heading 3",
  "keepWaitingPipelines": false,
  "lastModifiedBy": "anonymous",
  "limitConcurrent": true,
  "stages": [
    {
      "comments": "* test\n* test2\n## heading 2\n### heading 3",
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 30
    }
  ],
  "triggers": [],
  "updateTs": "1520881717951"
}
```

**Comment by anotherchrisberry** [comment]
Sure, that's easy enough - https://github.com/spinnaker/deck/pull/4988
