### ISSUE TITLE
[Kubernetes] - Add support for init containers

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#2006]
*Title*

kubernetes - support init containers

*Cloud Provider*

Kubernetes

*Environment*

N/A

*Feature Area*

Server Groups

*Description*

In Kubernetes 1.9, the use of annotations to specify init containers will be deprecated in favor of using the `initContainers` field on the Pod Spec. Spinnaker does not support the use of this field so users who attempt to deploy Server Groups that need init containers will not be able to use them and have no way around. We should add support for the `initContainer` field on the Pod Spec.

You can see the change coming down the pipe in the Kubernetes Changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v180-alpha3

_Hopefully_ the Fabric8 client library supports this field 🤢

**Comment by SteveEasley** [comment]
https://github.com/spinnaker/spinnaker/issues/1214

**Comment by ethanfrogers** [comment]
@lwander in order to support this we'd have to migrate the pieces of the current implementation to use the official client library instead of Fabric8. Is this something that would be accepted or should we just wait until the the `v2` provider is ready? I need to do some research to determine how difficult it would be to transition the deploy operation to use the new library.

**Comment by lwander** [comment]
Transforming the full deploy config to the new client library (which there is precedent for, in particular with stateful/daemon sets) will be tricky & error prone. It might be best to wait for the v2 provider

**Comment by ethanfrogers** [comment]
It looks like the Fabric8 library _does_ support init-containers so I think this can happen!

**Comment by ethanfrogers** [comment]
I lied :( the version of the Fabric8 library that Clouddriver uses doesn't include the correct version of `kubernetes-model`. @lwander, what are the chances that we could bump the library version?

**Comment by lwander** [comment]
Bump it!

**Comment by devng** [comment]
+1

**Comment by lleiguo** [comment]
+1

**Comment by skymeyer** [comment]
+1

**Comment by ethanfrogers** [comment]
Looks like I forgot to close this when I implemented it! 

Closed as of:
spinnaker/clouddriver#2219
spinnaker/deck#4582
