### ISSUE TITLE
Halyard install removes user account from all groups

### ISSUE THREAD

**Issue by SteveEasley** [spinnaker/spinnaker#2012]
*Title*

Halyard install removes user account from all groups

*Cloud Provider*

GCP

*Environment*

Halyard in a GCP compute instance running Ubuntu 14.04

*Feature Area*

Halyard install

*Description*

Halyard install removes user account from all groups

*Steps to Reproduce*

Upon creation of a new VM, I can verify my linux account is a member of a number of groups (most notably the `google-sudoers` group)

```
$ grep easleys /etc/group
adm:x:4:gke-xxx,easleys
dip:x:30:gke-xxx,easleys
video:x:44:gke-xxx,easleys
plugdev:x:46:gke-xxx,easleys
google-sudoers:x:1000:gke-xxx,easleys
easleys:x:1004:
```

But immediately after running `sudo bash InstallHalyard.sh` my account has been removed from all groups except the new spinnaker group. 

```
$ grep easleys /etc/group
easleys:x:1004:
spinnaker:x:1005:easleys
```

Logging out and not noticing this means being locked out of the server (sudo wise), for good if you are the only user.

**Comment by lwander** [comment]
Well that's very bad - which install script did you run?

**Comment by SteveEasley** [comment]
My full one-liner (ran yesterday) was `curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh && sudo bash InstallHalyard.sh`

**Comment by lwander** [comment]
Should be fixed here https://github.com/spinnaker/halyard/pull/735
