### ISSUE TITLE
[security/oauth] provider/google - User's info does not have all required fields

### ISSUE THREAD

**Issue by rosskevin** [spinnaker/spinnaker#2014]
*Title*
Ouickstart [Public Spinnaker on GKE](https://www.spinnaker.io/setup/quickstart/halyard-gke-public/) fails with on authentication attempt.  [Asked on SO first, no answer](https://stackoverflow.com/questions/46534989/spinnaker-gke-oauth-users-info-does-not-have-all-required-fields?noredirect=1#comment80024714_46534989)

```
{
  "error": "Unauthorized",
  "message": "Authentication Failed: User's info does not have all required fields.",
  "status": 401,
  "timestamp": 1506985726074
}
```

*Cloud Provider*:
google

*Environment*:
GKE deployment of 1.4.1 and 1.4.2, new installation following GKE [codelab](https://www.spinnaker.io/setup/quickstart/halyard-gke/) and following quickstart [Public Spinnaker on GKE](https://www.spinnaker.io/setup/quickstart/halyard-gke-public/)

As much information about your spinnaker environment as possible, for example: ```I am running Spinnaker using the Amazon images to deploy into AWS and GCP. ```

*Feature Area*
Security provider/google

*Description*
Login success

*Steps to Reproduce*
1.  New installation following GKE [codelab](https://www.spinnaker.io/setup/quickstart/halyard-gke/)
2. Quickstart [Public Spinnaker on GKE](https://www.spinnaker.io/setup/quickstart/halyard-gke-public/)

This succeeds up to:
> If you’re greeted with the following login screen on localhost:9000 you’re all set! 

It fails on:
> Make sure you can successfully login before continuing, however.

The following json is returned:

```
{
  "error": "Unauthorized",
  "message": "Authentication Failed: User's info does not have all required fields.",
  "status": 401,
  "timestamp": 1506985726074
}
```

*Additional Details*
I have reviewed [spinnaker's authentication setup](https://www.spinnaker.io/setup/security/authentication/) docs and tried several times with versions 1.4.1 and 1.4.2 to login, each with a fresh incognito browser as instructed.

**Note** the troubleshooting guide in the issue_template links to a non-existent page on spinnaker.io.

How can I help provide more relevant information?

**Comment by saokar** [comment]
I am running into the same issue. can someone help address this ?

**Comment by rosskevin** [comment]
This was due to the $DOMAIN not being set to the fully qualified domain name.  I used `foo` instead of `foo.com`.  See https://github.com/spinnaker/spinnaker.github.io/issues/363

**Comment by saokar** [comment]
Works only with G Suite/Google Apps for Work account. which is not the case for us.

**Comment by rosskevin** [comment]
This issue is about Google and gsuite connection, I suggest you start an issue specific to your case, as this one was a user error on my part.

**Comment by saokar** [comment]
ok. thanks
