### ISSUE TITLE
Deployment fails when Azure Container Registry is used

### ISSUE THREAD

**Issue by altvnk** [spinnaker/spinnaker#2015]
Azure Container Registry cannot pass healthcheck from clouddriver. This affects Spinnaker deployments on Kubernetes when Azure ACR is connected as container registry.

*Cloud Provider*
Kubernetes, Azure

*Environment*
Spinnaker is deploying on top of Kubernetes on Azure Container Service

*Feature Area*
Container registry

*Description*
When i'm adding Azure Container Registry to configuration, Spinnaker deployment never finishes. This happens because `spin-clouddriver-bootstrap` pod doesn't passes health check. After short investigation i've found that this happens due unhealthy Azure ACR. The strange this is when i'm adding registry via `hal config provider docker-registry account add azureacr --address https://myregistry.azurecr.io --repositories myimage --username myregistry --password
`,  it passes validation, but later, when `clouddriver` checks registry it fails with `s.c.d.r.h.DockerRegistryHealthIndicator : Unhealthy` and `retrofit.RetrofitError: 401 Unauthorized` in head of stack trace.

*Steps to Reproduce*
Add Azure ACR to config and try to deploy Spinnaker on Kubernetes. 100% reproducible.

**Comment by avenda** [comment]
same issue here, but except with Classic (Storage account: xxxx) SKU

**Comment by vijayinjam** [comment]
@avenda I'm assuming you do not have this issue with Classic ACR correct? can you please let me know the storage type and service principle roles that you used to create ACR with?

**Comment by avenda** [comment]
@vijayinjam that's right. ACR storage: 
Performance
Standard
Replication
Locally-redundant storage (LRS)
Account kind
Storage (general purpose v1)

**Comment by vijayinjam** [comment]
@avenda, thanks for the information. another quick question. With the Storage information you provided above, Does spinnaker(v-1.5.1) able to create new application?

**Comment by vijayinjam** [comment]
@avenda, thanks for the information. another quick question. With the Storage information you provided above, Does spinnaker(v-1.5.1) able to create new application?

**Comment by avenda** [comment]
@vijayinjam Neither, there is another bug, check this issue #1948

**Comment by vijayinjam** [comment]
@avenda Thanks for the information.

**Comment by mike10010100** [comment]
This is a massive blocker for us. Can anyone please help?

**Comment by SteveLas** [comment]
What auth type are you using? Did you provide a service principal username/password?
And, can you provide the actual registry URL? Feel free to direct message/email me at SteveLas at microsoft

**Comment by yuwaMSFT2** [comment]
I saw that our token server issued token successfully. But then their request to registry failed with this error:
err_auth_malformed_token

It means the bearer token is in bad format.

The spinnaker code seems to be only checking _bearer_token_ or _token_ field in the response from token server. But ACR only returns _access_token_ field (which is OAuth2 compatible):
https://github.com/spinnaker/clouddriver/blob/a090bf39a9ba0ded7247bb44cb29cc243fd776cf/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy#L394

From docker document, at least one of _token_ or _access_token_ field should be present in the token response. Can spinnaker try to use the _access_token_ field in the response and see if it works?

**Comment by vijayinjam** [comment]
This is a major blocker for us as well.

**Comment by mike10010100** [comment]
PR for fix opened here: https://github.com/spinnaker/clouddriver/pull/2274

**Comment by hafizullah** [comment]
Hi @mike10010100 is your PR part of any spinnaker release yet?

**Comment by mike10010100** [comment]
@hafizullah I believe so? It's been a while, so I'm not sure of the version it was included in, but I believe it was either 1.5.4 or 1.6.0.

**Comment by hafizullah** [comment]
Thanks I just checked its part of 1.5.4. Should this PR be closed if that issue is now fixed?

Kind Regards
Hafiz
________________________________

**Comment by mike10010100** [comment]
@hafizullah Absolutely.

**Comment by sbwsg** [comment]
Thanks!
