### ISSUE TITLE
Color distinction between pipeline stage statuses is insufficient for colorblind user

### ISSUE THREAD

**Issue by avram** [spinnaker/spinnaker#2024]
*Cloud Provider*

Not provider-specific

*Environment*

Running Armory Spinnaker, but this is a general accessibility issue.

*Feature Area*

UI

*Description*

Stage status should be conveyed in a way that the user can quickly understand, such as pattern or words or symbols, or using more easily distinguished colors.

*Steps to Reproduce*

Create pipelines with a mix of successful and failed stages. Procure a person with some degree of red-green colorblindness. Note the person's confusion.

*Additional Details*

![image](https://user-images.githubusercontent.com/224208/31361889-a0e90840-ad0a-11e7-8ffa-fb322279ab36.png)

Colorblind mode in Jenkins:
![image](https://user-images.githubusercontent.com/224208/31361926-d36d6e32-ad0a-11e7-8702-1b6fe9b9a40b.png)

**Comment by ttomsu** [comment]
@anotherchrisberry @danielpeach @tatelmania

**Comment by PoorImpulseCtrl** [comment]
When designing the pipeline screens, we specifically looked at distinguishing failures for a variety of users, including red/green and yellow/blue color-blind.

**Red/Green**
![screen shot 2017-10-12 at 12 35 00 pm](https://user-images.githubusercontent.com/5777375/31515452-18f06b80-af4a-11e7-9e93-f70d168a07c5.png)

**Yellow/Blue**
![screen shot 2017-10-12 at 12 35 15 pm](https://user-images.githubusercontent.com/5777375/31515471-26287cde-af4a-11e7-9ba2-4c62313c9b23.png)

**Jenkins**, in my opinion, has less contrast between the two, compared to Spinnaker.
![screen shot 2017-10-12 at 12 39 29 pm](https://user-images.githubusercontent.com/5777375/31515595-880583a2-af4a-11e7-83bc-ae9a2a682af1.png)

While the red/green doesn't show fundamentally different colors (it can't, given red/green colors by any standard), the contrast between the two meets our expectations of contrast ratio. However, we're always looking at ways of making our tools more usable, by a variety of users, and appreciate the feedback!

**Comment by avram** [comment]
My comment about Jenkins was that they complement the colors with big letters which I can easily distinguish-- the red and green balls are confusing, so the ugly overlaid letters let me ignore the colors.

I suppose I'm commenting because I know I've personally failed to see that stages were red, especially if they are in isolation. I don't know why this is the case, but I suspect it has to do with my red-green colorblindness.

One affordance I would appreciate, given that perhaps the colors are as well-chosen as is possible, would be to the tool tips on stage hover include the status of the stage.

**Comment by PoorImpulseCtrl** [comment]
@avram Definitely understand. I apologize if the recognition of the letters wasn't apparent in my response. It's definitely something we've discussed (an icon for failures) and a good suggestion.

**Comment by avram** [comment]
Closing as there is no immediate action needed.
