### ISSUE TITLE
No options in stage type dropdown when creating a pipeline

### ISSUE THREAD

**Issue by ShashankYadav** [spinnaker/spinnaker#2031]
*No options in stage type dropdown when creating a pipeline*

*Cloud Provider*
docker-registry. Configured a local docker registry to act as a source for triggering pipelines

*Environment*

Running spinnaker 1.4.2 in a local ubuntu 14.04 virtual machine deployed using halyard 0.35. Storage being used is amazon s3.

*Feature Area*

Pipelines

*Description*

Created a new application and a new pipeline in the app. When adding a new stage to the pipeline, the stage type dropdown shows no options to select from ( Added screenshot below). The web console did not throw any errors. gate.log also shows no errors.

*Steps to Reproduce*

1) Setup a fresh spinnaker installation in a ubuntu Vm using halyard 0.35, configured to use s3 bucket for storage.
2) Expose spinnaker by following https://blog.spinnaker.io/exposing-spinnaker-to-end-users-4808bc936698 and apache configuration from https://github.com/spinnaker/spinnaker/issues/997.
2) Create a new application successfully, create a new pipeline successfully
3) Click on add stage.

The new stage does not have any options in the stage type dropdown.

*Additional Details*
![image](https://user-images.githubusercontent.com/5380191/31542862-5feb6be2-b031-11e7-811a-7fe081e3d056.png)

**Comment by nextrevision** [comment]
Downgrading to 1.4.1 via halyard fixed this issue for me.

**Comment by ShashankYadav** [comment]
I'm still having the same issue after downgrading to 1.4.1.

**Comment by nextrevision** [comment]
I'm seeing the same now. Was working fine after I downgraded, then stopped after a subsequent hal deploy for a minor config change.

**Comment by ShashankYadav** [comment]
Bumping the thread, since still facing this issue. Any pointers on how to go ahead and debug this would be helpful.

**Comment by nextrevision** [comment]
Here's where I believe the UI logic is for this: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/config/stages/stage.html#L23

I primarily use spinnaker with orchestrating Jenkins at the moment, although have AWS enabled via halyard.

**Comment by ShashankYadav** [comment]
In deck/app/scripts/modules/core/src/pipeline/config/stages/stage.module.js, we have
```
accountService.listProviders($scope.application).then((providers) => {
    $scope.options.stageTypes = pipelineConfig.getConfigurableStageTypes(providers);
    $scope.showProviders = providers.length > 1;
});
```

In the console for the new stage page, `angular.element($0).injector().get('accountService').listProviders(angular.element($0).scope().application)` returns a Promise object with value [].  providers is set to [],  which I believe is expected since I have not configured any cloud providers during installation with halyard.

The stage types are populated in options.stageTypes which comes from the  contains the return value of `pipelineConfig.getConfigurableStageTypes(providers)`. In my case, the return value is `[]` hence there are no options being shown in the stage type dropdown. The function definition in deck/app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts as follows:

```
public getConfigurableStageTypes(providers?: string[]): IStageTypeConfig[] {
    const allStageTypes = this.getStageTypes();
    const configurableStageTypes = allStageTypes.filter(stageType => !stageType.synthetic && !stageType.provides);                                                                                  
    if (!providers) {
      return configurableStageTypes;
    }
    configurableStageTypes.forEach(type => type.cloudProviders = this.getCloudProvidersForStage(type, allStageTypes, providers));
    return configurableStageTypes
      .filter(stageType => stageType.cloudProviders.length)
      .sort((a, b) => a.label.localeCompare(b.label));
  }
```

- `this.getStageTypes()` returns an array of 105 entries
-  allStageTypes.filter() call reduces it to 25 elements.
-  Since providers is `[]`, the if condition is false. **I believe that if there are no cloud providers configured, we should return from here. But the code moves on when providers=[]**.
- The configurableStageTypes.filter() in last line of the function reduces the list to 0 elements. 

As a solution, maybe changing the if condition to the following can fix the issue:
```
if (!providers || providers.length == 0) {
      return configurableStageTypes;
}
```

**Comment by christopherthielen** [comment]
@shashankyadav your analysis makes sense. Care to test the theory and then make a PR?

**Comment by hyunto** [comment]
I suffered same issue that don't appear any type of stage when I create or modify pipeline.
I can solve this problem by modifying the source code(line 329 in `/opt/deck/html/app.js`) that @ShashankYadav mentioned.

At this time, it has not been changed at latest version. (2.0.1-20171130174645)

Here is my environments :
* os : ubuntu 14.04
* halyard : 0.38
* spinnaker : v 1.5.1
* deployment : Local Debian
* storage : s3 (use minio)
* cloud provider : only docker registry

Thank you, @ShashankYadav !!!

**Comment by ShashankYadav** [comment]
The easiest solution without any source code modifications is to configure a kubernetes cluster as a cloud provider. In case you do not have an existing cluster, you can setup a simple one with [minikube](https://kubernetes.io/docs/getting-started-guides/minikube/) for testing and configure spinnaker to use it. It seems like spinnaker was never intended to be configured without a cloud provider ( docker-registry does not count as one). Closing this issue.
