### ISSUE TITLE
[feature request] Do not restart redis services when external redis is used

### ISSUE THREAD

**Issue by rosskevin** [spinnaker/spinnaker#2034]
*Title*
Do not restart redis services when external redis is used

*Cloud Provider*
GCP
GKE
redislabs

*Environment*
We use redislabs.com deployed in GCP for managed redis.  Spinnaker is deployed in GKE

*Feature Area*
kubernetes services - redis

*Description*
Once I override the redis url, I expect subsequent `hal deploy apply` executions to avoid starting/restarting redis services.

*Steps to Reproduce*
- start with a good spinnaker deployment
- edit `~/.hal/default/service-settings/redis.yml` ([custom config example](https://www.spinnaker.io/reference/halyard/custom/))
```
overrideBaseUrl: redis://:password@c1.us-central1-2.gce.cloud.redislabs.com:6379
```
- `hal deploy apply`
- wait
- Delete all from kubernetes: 
  - services `spin-redis-bootstrap`
  - replica sets `spin-redis-v*`,  `spin-redis-bootstrap-*`
- Deploy again `hal deploy apply`
- Note services, replica sets and pods are recreated.

**Comment by lwander** [comment]
Have you set `enabled: false` in that service settings file?

**Comment by rosskevin** [comment]
No, will do. Will that disable running services in the kubernetes cluster?  

If not, what is the best way to deploy this? clean/apply?

The reason I ask is because later I found `spin-orca-bootstrap` and `spin-clouddriver-bootstrap` to be failing as they were looking for the local redis.  I deleted/redeployed them but I suspect them to still be pointed at local (no evidence just a hunch).

**Comment by lwander** [comment]
It won't affect anything running in your cluster - so you'll have to clean up those redis nodes by hand.

You'd need to configure `redis-bootstrap.yml` with its own overrideBaseUrl as well.

**Comment by rosskevin** [comment]
Ok, so `enabled: false` and `overrideBaseUrl` for both `service-settings/redis.yml` and `service-settings/redis-bootstrap.yml`.

I'll do a clean/apply, just to make sure I don't miss anything.

**Comment by rosskevin** [comment]
Great!  This worked, here's a set of instructions for anyone else that wants to use an external redis:

- create `~/.hal/default/service-settings/redis.yml` with

```yaml
enabled: false
overrideBaseUrl: redis://:password@c1.us-central1-2.gce.cloud.redislabs.com:6379
```
- create `~/.hal/default/service-settings/redis-bootstrap.yml` with

```yaml
enabled: false
overrideBaseUrl: redis://:password@c1.us-central1-2.gce.cloud.redislabs.com:6379
```

- Delete replica sets, services etc, or perhaps more simply (depending on your situation) `hal deploy clean && hal deploy apply`.  If you `hal deploy clean`, don't forget to re-apply external IP to services if you have set them up.

**Comment by brantburnett** [comment]
To help others avoid the pain I encountered using some of the above steps, I recommend looking at this documentation for externalizing Redis: https://www.spinnaker.io/setup/productionize/caching/externalize-redis/

In particular, in my experience you *should not* override redis-bootstrap.yml, only redis.yml.  We starting have all kinds of weird behavioral problems when clouddriver and clouddriver-bootstrap were sharing the same Redis cluster.

More info: https://github.com/spinnaker/spinnaker/issues/2635#issuecomment-382515817
