### ISSUE TITLE
Enable setting of labels on k8s Load Balancers (aka Service objects)

### ISSUE THREAD

**Issue by mdirkse** [spinnaker/spinnaker#2035]
We use Prometheus which discovers its k8s targets based on labels set on Service objects. In the Spinnaker world k8s Services map to Load Balancers and it is currently not possible to set labels on those (it is possible to set annotations). I propose to add the ability to add labels to Load Balancers via the "Advanced Settings" part of the Load Balancer create/edit UI.

**Comment by lwander** [comment]
This won't be supported in the v1 provider due to restrictions it places on labeling. This will be supported in v2. Development can be tracked [here](github.com/spinnaker/spinnaker/projects/1).

**Comment by lwander** [comment]
Oh sorry I misread, this, yes, this is a good feature request that can be supported in both versions of the provider.
