### ISSUE TITLE
[notifications] staging/settings.js wiped out when overridden by profiles/settings.js

### ISSUE THREAD

**Issue by rosskevin** [spinnaker/spinnaker#2036]
*Title*
When configuring notifications based on [_Where to put echo-local.yml and settings.js_](https://www.spinnaker.io/setup/features/notifications/#where-to-put-echo-localyml-and-settingsjs) and the slack notification instructions, `deploy apply` wipes out `staging/settings.js` and replaces with `profile/settings.js`.

*Cloud Provider*
GCP, GKE

*Environment*
1.4.2 running on GKE 1.7.6

*Feature Area*
Notifications

*Description*
Perhaps the [_Where to put echo-local.yml and settings.js_](https://www.spinnaker.io/setup/features/notifications/#where-to-put-echo-localyml-and-settingsjs) is wrong, or there is a bug.

*Steps to Reproduce*
[Follow slack notification instructions on spinnaker.io](https://www.spinnaker.io/setup/features/notifications/#slack)

- check the contents of `~/.hal/default/staging/settings.js` on a good deployment
- vi `~/.hal/default/profiles/echo-local.yml`
```
slack:
  enabled: true
  token: <API token for bot>
```
- vi `~/.hal/default/profiles/settings.js`
```js
window.spinnakerSettings = {
  notifications: {
    slack: {
      enabled: true,
      botName: 'spinnaker-bot'
    }
  }
}
```
- `hal deploy apply`
- check the contents of `~/.hal/default/staging/settings.js`, contents are solely what is in `~/.hal/default/profiles/settings.js`

*Additional Details*
I store all generated configs in git, so I can better see diffs when I have a problem.  Please ignore that this pictures both `settings-local.js` and `settings.js`, I tried with both and accidentally left `settings-local.js` which had no effect.

You can see from the pic below, that the contents of `~/.hal/default/staging/settings.js` was replaced with my `~/.hal/profiles/settings.js`, and I'm expecting them to be merged or overridden.

![diff](https://user-images.githubusercontent.com/136564/31639110-b93d959a-b29c-11e7-8a14-8232a6dcbb5d.png)

**Comment by danielpeach** [comment]
Yep, you'll need 1.5 to use `settings-local.js`.
