### ISSUE TITLE
Issue in creating server groups in spinnaker

### ISSUE THREAD

**Issue by ramimmadi** [spinnaker/spinnaker#2043]
I am trying to do the codlabs given in spinnaker. following the steps given in _https://www.spinnaker.io/guides/tutorials/codelabs/gce-source-to-prod/_ but I am unabe to create the server group(create without template). It is getting loaded for infinite time. I could say I got stuck at that point. I did that multiple times to check if I am missig any step but I think I am not missing anything.

One more thing is that I am able to do ssh tunneling using Azure VMs and Local machines but not with Google cloud VMs. It is not opening beyond "Hello" page If I use Google cloud VMs to do "SSH tunneling". Please help me out to solve this. 

  Thank you

**Comment by ezimanyi** [comment]
I've upgraded the version of spinnaker in the codelab image to spinnaker 1.5.4, which addresses the bug noted here.  Following the instructions in the codelab now works as expected.
