### ISSUE TITLE
Manual Trigger with Docker Registry does not return tags 

### ISSUE THREAD

**Issue by joshughes** [spinnaker/spinnaker#2044]
**Cloud Provider**

Kubernetes on GCP with Google Container Registry

**Environment**

Running Spinnaker 1.4.2 deployed with the latest Halyard 

**Feature Area**

Using the Manual Docker Trigger with Pipeline

**Description**

Around every 1 - 2 days when we go to do a manual deployment of a new docker tag, for some docker image the tags do not return. It is not the same image every time and often tags will not resolve for one image but will for another in the same registry. 

Restarting CloudDriver clears up the issue for another 1 -2 days.

**Steps to Reproduce**

I have not found a known way to reproduce this issue... except for leaving Clouddriver running for a few days. Automated Triggers seem to continue working but manual triggers cannot list the tags. 

**Additional Details**

In the Kubernetes Slack Channel, I have confirmed with at least one other user that this has occurred in their environment as well.

**Comment by SandeepVaman** [comment]
I faced the same issue and restarting clouddriver pod with the following command `kubectl get pod PODNAME -o yaml | kubectl replace --force -f -` helped me to resolve the issue.
