### ISSUE TITLE
Allow scaling down latest server group during rollback

### ISSUE THREAD

**Issue by CB-GuangyaoXie** [spinnaker/spinnaker#2051]
This is a feature request.

*Cloud Provider*
AWS

*Environment*
Spinnaker + AWS
Service discovery using Consul. Services in this case talk to each other directly without ELB.

*Feature Area*
UI, Server Group Actions

*Description*
Current rollback operations are:
- Enable previous server group
- Resize previous server group to desired capacity
- Disable current server group  
For us, the current server group still takes traffic because traffic is not through ELB. 

We want to have a rollback option to do red/black rollback:
- Enable previous server group
- Resize previous server group to desired capacity
- Disable current server group
- Resize current server group to size 0

**Comment by lwander** [comment]
This can be done using a pipeline
