### ISSUE TITLE
Rosco is enabled, and no connection to rosco could be  established: retrofit.RetrofitError: 503 Service Unavailable

### ISSUE THREAD

**Issue by hpejustin** [spinnaker/spinnaker#2052]
Rosco is enabled, and no connection to rosco could be  established: retrofit.RetrofitError: 503 Service Unavailable

*Cloud Provider*
Kubernetes

*Ubuntu14.04 LTS*

*Docker info*

Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 83
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-125-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45GiB
Name: ip-172-31-39-112
ID: 6UAP:QLHX:O2L4:V6US:LPTJ:XHKZ:RR4S:UYNX:NUU4:5HOH:DCC4:B6XK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: hpejustin
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker.demo.artifactory.jfrogchina
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

when i install spinnaker step by step as described here:
https://www.spinnaker.io/setup/install/halyard/

*Steps to Reproduce*

use kubernetes as target deployment environment, and use halyard container as the tools

docker run -p localhost:8084:8084 -p localhost:9000:9000 --name halyard --rm -v ~/.hal:/root/.hal -v /root/.kube/config:/root/.kube/config gcr.io/spinnaker-marketplace/halyard:stable

...

hal deploy apply

*log*

+ Get current deployment
  Success
- Apply deployment
  Failure
+ Deploy spin-clouddriver
  Success
+ Deploy spin-front50
  Success
+ Deploy spin-orca
  Success
+ Deploy spin-deck
  Success
+ Deploy spin-echo
  Success
+ Deploy spin-gate
  Success
+ Deploy spin-igor
  Success
+ Deploy spin-rosco
  Success
Problems in default:
- WARNING Version "1.0.0" is no longer supported by the Spinnaker
  team. Please upgrade when possible.
? https://spinnaker.io/setup/install/upgrades/

Problems in default.provider.kubernetes.my-k8s-account:
- WARNING You have not specified a Kubernetes context in your
  halconfig, Spinnaker will use "default-context" instead.
? We recommend explicitly setting a context in your halconfig, to
  ensure changes to your kubeconfig won't break your deployment.
? Options include:
  - default-context

Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

Problems in Global:
! ERROR Rosco is enabled, and no connection to rosco could be
  established: retrofit.RetrofitError: 503 Service Unavailable

- Failed to deploy Spinnaker.

**Comment by hpejustin** [comment]
i found the reson, kubernetes has enabled ServiceAccount AdmissionControl, when i remove that, it works fine. so i will close this issue.

**Comment by mickengland** [comment]
@hpejustin Did you just remove ServiceAccount or the entire AdmissionControl line? I tried just removing the reference to ServiceAccount but still get the same issue.

**Comment by amitmindstix** [comment]
Same error with halyard 0.44 and SPinnaker 1.6.0

**Comment by celamb4** [comment]
Seeing similar behavior with hal 0.43 and Spinnaker 1.6.0
