### ISSUE TITLE
Cannot find provided path: /root/.kube/config (Permission   denied)

### ISSUE THREAD

**Issue by hpejustin** [spinnaker/spinnaker#2053]
Cannot find provided path: /root/.kube/config (Permission   denied)

*Cloud Provider* 
Kubernetes

*Environment*

halyard  version 0.35 / ubuntu 14.04 LTS

*Feature Area*

add kubernetes account

*Description*

i add kubernetes account , but got failure.

*Steps to Reproduce*

hal config provider kubernetes account add my-k8s-account --docker-registries my-docker-registry

i change file to -rwxrwxrwx 1 root root 339 Oct 21 09:32 /root/.kube/config, i still got failure.

*log*

Problems in default.provider.kubernetes.my-k8s-account:
! ERROR Cannot find provided path: /root/.kube/config (Permission
  denied).
? Halyard is running as user ubuntu. Make sure that user can read
  the requested file.

**Comment by YacheLee** [comment]
I face the same problem. My solution is setting the environment variable for $VERSION,
then deploy.

`hal version list`
`hal config version edit --version $VERSION`
`hal deploy apply`
