### ISSUE TITLE
Kubernetes/Deck - Evicted Pods cause user confusion

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#2059]
*Title*

Kubernetes/Deck - Evicted Pods cause user confusion

*Cloud Provider*

Kubernetes

*Environment*

N/A

*Feature Area*

Server Group display in Deck

*Description*

Within the Server Group view in Deck, Kubernetes Pods that have been evicted (due to Memory/Disk/CPU pressure) are displayed in the same way as Pods that are online. The only way to figure out which Pods are online vs evicted is to click through each of them to see the status. 

It would be nice to have some visual indicator of instances which had been evicted, similar to how Disabled or Down instances are displayed (gray and red).

For instance, there should only be one instance that is green, but there are 5 showing online.
![image](https://user-images.githubusercontent.com/3324110/32027438-0f0e5e16-b9b7-11e7-856a-198aede389cf.png)

![image](https://user-images.githubusercontent.com/3324110/32027488-4b9e2802-b9b7-11e7-85b9-b42bb464f3d4.png)

@lwander @anotherchrisberry any thoughts on this or what color might be best to display this difference? I don't mind doing the work, just let me know what you think!

**Comment by lwander** [comment]
Ah this is tricky due to how health is handled - I would look inside of KubernetesV1Health.java in clouddriver to get a sense for what is being computed there.

**Comment by ethanfrogers** [comment]
The health state being returned on those Pods is `Failed`. Is there a reason to reflect that state in the same way as `Up`? Since `Failed` reflects a different state than `Down`, I'd want to see, at a glance, what Pods can be terminated for clean up.

**Comment by ethanfrogers** [comment]
And after looking at Deck, it seems that the only reason it isn't reflected by a different color is because there's not a CSS class defined for `health-status-Failed` and the default is the same as `health-status-Up`.

**Comment by lwander** [comment]
Ah that's good - if Chris agrees then that should probably just look like
the regular "unhealthy" pods.
