### ISSUE TITLE
redis storage edit failure - Task interrupted without cause

### ISSUE THREAD

**Issue by m0rt1-m3r** [spinnaker/spinnaker#2062]
I'm trying to setup a local instance of Spinnaker on a dedicated VM running RancherOS.
For evaluation purposes I'd like to use redis for the persistent storage, yet it's failing with the below message.

```
root@447db218097e:/workdir# hal -v
0.35.0-20171002192634
root@447db218097e:/workdir# hal config storage edit --type redis
+ Get current deployment
  Success
+ Get persistent storage settings
  Success
/ Edit persistent storage settings
  Timed out
Problems in Global:
! ERROR Unexpected exception:
  DaemonTaskInterrupted(interruptedTime=1509012123084, message=Task interrupted
  without cause at Thu Oct 26 10:02:03 UTC 2017)
- Failed to edit persistent storage. Task killed because it was
  taking too long.
root@447db218097e:/workdir#
```

output of hal config storage edit --type redis --debug 
https://gist.github.com/m0rt1-m3r/e608c8f047b0cd83f7c1025434ea4f82

Any ideas what's causing the issue?

**Comment by lwander** [comment]
Are you running behind a proxy? Halyard was checking to see what subcomponents your Spinnaker version corresponds to by checking our GCS bucket. When this hangs, it's usually a network config issue

**Comment by m0rt1-m3r** [comment]
Yup, behind a proxy

**Comment by m0rt1-m3r** [comment]
Our FW Team replied that the below are being blocked:

216.58.205.138, 216.58.205.202  -> www.google.com
5.153.231.4 -> senfter.debian.org
212.211.132.250 -> lobos.debian.org

Does it sound right?
Is there a way to chanell all communication via proxy?
I have found this https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-run-halyard-behind-a-proxy
but not sure how to pass required values to Halyard (i'm running it in a container).

**Comment by m0rt1-m3r** [comment]
I was able to sort everything out. After sorting out connection issues I was able to pass proxy to Halyard

`docker run -p 8084:8084 -p 9000:9000     --name halyard --rm  -e JAVA_OPTS="-Dhttp.proxyHost= PROXY_SERVER_COM -Dhttp.proxyPort=PORT -Dhttps.proxyHost=PROXY.SERVER.COM -Dhttps.proxyPort=PORT"   -v ~/.hal:/root/.hal -v ~/.kube:/root/.kube    gcr.io/spinnaker-marketplace/halyard:stable`
