### ISSUE TITLE
Pipeline timeout fails with "No reason provided"

### ISSUE THREAD

**Issue by rosskevin** [spinnaker/spinnaker#2064]
*Title*
When pipeline times out, the UI states `No reason provided`, it should state something about failing to complete within xxx.

*Cloud Provider*
GCP

*Environment*
Kubernetes

*Feature Area*
- Pipelines
- UI

*Description*
I was investigating a pipeline deploy failure because the UI stated `No reason provided`, looking in logs and finding nothing, I double-checked timeout.  Indeed, it passed timeout then failed it with `No reason provided`.

*Steps to Reproduce*
- use an existing pipeline
- override the default timeout to something too low like 1 minute
![coverbid_ _pipeline_config](https://user-images.githubusercontent.com/136564/32066307-f0f017f6-ba44-11e7-9dfd-d4bd5535345d.png)
- execute pipeline

*Additional Details*
![coverbid_ _pipeline_executions_ _execution_details__23d32b3e-2936-47e7-b25c-37c92787f458](https://user-images.githubusercontent.com/136564/32066257-cafa4d3c-ba44-11e7-97d3-21a815115705.png)

**Comment by emjburns** [comment]
This should be fixed now. Apologies. Usually if you click on the "Source" link (bottom right) you can see the bigger stack trace or error message. Agreed that this isn't a great user experience.
