### ISSUE TITLE
rosco packer update incompatible with rosco packer templates

### ISSUE THREAD

**Issue by chrono** [spinnaker/spinnaker#2065]
The update of packer in https://github.com/spinnaker/rosco/pull/223 broke the packer templates shipped with rosco. They reference `enhanced_networking` which is not supported in that packer version: https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#110-september-12-2017

This breaks rosco bakes.

**Comment by avram** [comment]
Fixed in https://github.com/spinnaker/rosco/pull/227 -- can this be closed now?

**Comment by ezimanyi** [comment]
Closing per above comment; please re-open or create a new issue if you still experience issues.
