### ISSUE TITLE
ACA Task - Lists only AWS accounts

### ISSUE THREAD

**Issue by sher4locked** [spinnaker/spinnaker#2083]
*Title*
ACA Task - Lists only AWS accounts

*Cloud Provider*
AWS and Kubernetes

*Environment*
I am running Spinnaker on AWS to deploy into AWS and Kubernetes.

*Feature Area*
Pipeline Templates, Canary

*Description*
During creation of an ACA task, accounts of all configured providers should be listed but only AWS accounts are listed in the drop down.

*Steps to Reproduce*
Configure a provider apart from AWS to be true and create an ACA task. Other Cloud Providers' accounts are not listed in the drop down.

**Comment by lwander** [comment]
Looks like this was fixed in the above PR.
