### ISSUE TITLE
GCP Triggered deploy : NamedPort.port to java.lang.Double

### ISSUE THREAD

**Issue by jeffbean** [spinnaker/spinnaker#2096]
GCP provider Deploy provision fails when pipeline is triggers with Cron and passed with manual execution.

*Cloud Provider*

GCP.

*Environment*

Halyard 1.5.0 deployment debian local install running in GCP.

*Feature Area*

Pipelines
*Description*
When a pipeline that does a depoy of a server group is started it fails with an error around NamedPort type issue. 

```
Can not set java.lang.Integer field com.google.api.services.compute.model.NamedPort.port to java.lang.Double 
(through reference chain: 
com.netflix.spinnaker.clouddriver.google.deploy.description.BasicGoogleDeployDescription["loadBalancingPolicy"]
  ->com.netflix.spinnaker.clouddriver.google.model.loadbalancing.GoogleHttpLoadBalancingPolicy["namedPorts"]
  ->java.util.ArrayList[0]
  ->com.google.api.services.compute.model.NamedPort["port"])
```
*Steps to Reproduce*

Create a pipeline deploying a server group with multiple named ports. Create this pipeline with a CRON trigger for whenever. Wait for the triggered pipeline to start to see the failure

**Comment by jtk54** [comment]
I reproduced this on my deployment of 1.5.0, I'll do it again in my dev environment tomorrow and work on a fix then.

**Comment by jtk54** [comment]
Opened a PR with a fix for this issue. Will cherry-pick into 1.5.0 and make a patch release if all goes well.

**Comment by jtk54** [comment]
Cherry pick PR: https://github.com/spinnaker/clouddriver/pull/2139.

**Comment by jeffbean** [comment]
I can confirm from my deployment that `1.5.1` fixes this issue. Thanks!
