### ISSUE TITLE
Kubernetes v2 "versioned" resources aren't begin deployed correctly

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2108]
When a resource with suffix `-v000` exists, the v2 provider creates the next resource with suffix `-v000-v000` rather than `-v001`.

This is a good place to start: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/artifact/KubernetesVersionedArtifactConverter.java

**Comment by brandonnelson3** [comment]
Looks like the frontend is simply not setting the versioned parameter to true. Setting that seems to fix the problem.
