### ISSUE TITLE
(provider/kubernetes): Enable using all key-value pairs from ConfigMaps and Secrets as environment variables source.

### ISSUE THREAD

**Issue by valdemon** [spinnaker/spinnaker#2120]
*Title*

(provider/kubernetes): Enable using all key-value pairs from ConfigMaps and Secrets as environment variables source.

*Cloud Provider*

Kubernetes.

*Environment*

Kubernetes with RBAC enabled.

*Feature Area*

Pipelines, UI

*Description*

Currently we can define environment variables from ConfigMaps & Secrets only by explicit mapping, which enforces to declare each variable one by one, mapping it to corresponding ConfigMap or Secret key reference (eg in `Deck`).

Would be cool when we could simply declare the whole ConfigMap or Secret as an environment variable source, following the [Configure all key-value pairs in a ConfigMap as Pod environment variables](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-pod-environment-variables) pattern.
The above pattern works both for `ConfigMaps` and `Secrets`, as described in [container-v1-core](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#container-v1-core) - the `envFrom` attribute which is an array of [EnvFromSource](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#envfromsource-v1-core) type.

**Comment by ethanfrogers** [comment]
@valdemon I’m currently looking at upgrading the client library for the V1 provider which should support more recent API additions. I’ll verify and look into adding it once the upgrade hits HEAD.

**Comment by ethanfrogers** [comment]
It looks like the library supports it, so it should be possible!

**Comment by ethanfrogers** [comment]
addressed in the PRs mentioned above.
