### ISSUE TITLE
Add config flag to support deployment of standard java appengine apps

### ISSUE THREAD

**Issue by darin-willits** [spinnaker/spinnaker#2130]
*Title*

Add config flag to support deployment of standard java appengine apps

*Cloud Provider*

AppEngine

*Environment*

I am running Spinnaker 1.5.0 in GCE.

*Feature Area*

Pipeline.

*Description*

Spinnaker can't deploy Standard Java Appengine app since it uses

gcloud app deploy ... 

to deploy Appengine apps.  Standard Java apps can be deployed using:

gcloud beta app deploy ... 

The feature request here is to add a config flag to use gcloud beta instead of normal gcloud.

*Steps to Reproduce*

- Create a pipeline to deploy a standard java app engine application via GCS
- Run the pipeline
- Note the error returned from gcloud app deploy

**Comment by danielpeach** [comment]
This should be available in 1.6.0.

**Comment by darin-willits** [comment]
That’s awesome, thanks!  Any chance you know approximately when 1.6.0 will be released?

Thanks,
Darin
