### ISSUE TITLE
Unable to pull spinnaker-marketplace images from gcr.io

### ISSUE THREAD

**Issue by jimmythedog** [spinnaker/spinnaker#2165]
When trying to deploy spinnaker via halyard, the pods remain in ImagePullBackOff status, and show events:
```
Normal   Pulling                3m (x4 over 4m)   kubelet, k8sworker1.xxxxxxx  pulling image "gcr.io/spinnaker-marketplace/clouddriver:1.0.0-20171108151529"
Warning  Failed                 3m (x4 over 4m)   kubelet, k8sworker1.xxxxxxx  Failed to pull image "gcr.io/spinnaker-marketplace/clouddriver:1.0.0-20171108151529": rpc error: code = Unknown desc = denied: Permission denied for "1.0.0-20171108151529" from request "/v2/spinnaker-marketplace/clouddriver/manifests/1.0.0-20171108151529".
Normal   BackOff                3m (x5 over 4m)   kubelet, k8sworker1.xxxxxxx  Back-off pulling image "gcr.io/spinnaker-marketplace/clouddriver:1.0.0-20171108151529"
```

A manual pull results in a similar problem:
```
kgibbs@kgibbs:~$ docker pull gcr.io/spinnaker-marketplace/clouddriver:1.0.0-201711081515
Error response from daemon: pull access denied for gcr.io/spinnaker-marketplace/clouddriver, repository does not exist or may require 'docker login'
kgibbs@kgibbs:~$ 
```

And, browsing the [gcr.io repo](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL) appears to show that the spinnaker-marketplace repo is missing

*Cloud Provider*

Kubernetes

*Environment*

I am trying to deploy Spinnaker to a private K8S cluster, using Halyard

*Feature Area*

Deployment

**Comment by betandr** [comment]
I have this same issue...

**Comment by lwander** [comment]
I'm looking into this now - everything seems to be public on our end

**Comment by lwander** [comment]
Does `gcloud container images list --project spinnaker-marketplace` work? I've updated a bucket permission that (it seems) maybe we didn't previously need?

**Comment by betandr** [comment]
I get:

```
NAME
gcr.io/spinnaker-marketplace/clouddriver
gcr.io/spinnaker-marketplace/deck
gcr.io/spinnaker-marketplace/echo
gcr.io/spinnaker-marketplace/fiat
gcr.io/spinnaker-marketplace/front50
gcr.io/spinnaker-marketplace/gate
gcr.io/spinnaker-marketplace/gradle_cache
gcr.io/spinnaker-marketplace/halyard
gcr.io/spinnaker-marketplace/igor
gcr.io/spinnaker-marketplace/monitoring-daemon
gcr.io/spinnaker-marketplace/orca
gcr.io/spinnaker-marketplace/rosco
gcr.io/spinnaker-marketplace/spinnaker-monitoring
gcr.io/spinnaker-marketplace/spinnaker-monitoring-daemon
Only listing images in gcr.io/spinnaker-marketplace. Use --repository to list images in other repositories.
```
...but `docker pull gcr.io/spinnaker-marketplace/clouddriver` doesn't work. Could you try that maybe?

**Comment by lwander** [comment]
We don't publish "latest", could you try `docker pull gcr.io/spinnaker-marketplace/clouddriver:1.0.0-201711081515`?

**Comment by betandr** [comment]
'Error response from daemon: manifest for gcr.io/spinnaker-marketplace/clouddriver:1.0.0-201711081515 not found'

**Comment by betandr** [comment]
I've just tried the same version as wasn't working beforehand and it's working now!

`docker pull gcr.io/spinnaker-marketplace/clouddriver:1.0.1-20171130174645`

**Comment by betandr** [comment]
Yes! Trying my deploy and running! 👍

**Comment by lwander** [comment]
Thanks!

For posterity, we needed

```bash
gsutil acl ch -u AllUsers:R gs://artifacts.{PROJECT_NAME}.appspot.com
```

to open up the GCR bucket's access

**Comment by betandr** [comment]
🔥

**Comment by leylmordor** [comment]
Does anyone have this issue ?

Error: ImagePullBackOff
Source
kubelet gke-deployinator-pool-2-c782f8c4-w7na
Count
41
Sub-object
spec.containers{front50}
Last seen
2021-03-08T07:15:46Z
Failed to pull image "gcr.io/spinnaker-marketplace/front50:0.23.0-20200428230017": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/spinnaker-marketplace/front50:0.23.0-20200428230017": failed to resolve reference "gcr.io/spinnaker-marketplace/front50:0.23.0-20200428230017": unexpected status code [manifests 0.23.0-20200428230017]: 403 Forbidden

**Comment by JudeaDumont** [comment]
this is still an issue

**Comment by ethai** [comment]
something changed recently as I'm no longer able to pull any images from 'spinnaker-marketplace' project

ERROR: (gcloud.container.images.list) Access denied: gcr.io/spinnaker-marketplace

**Comment by peppe77** [comment]
same problem...anyone has found a solution?

``` Pulling image "gcr.io/spinnaker-marketplace/halyard:1.37.0"
  Warning  Failed                  12s                kubelet                  Failed to pull image "gcr.io/spinnaker-marketplace/halyard:1.37.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/spinnaker-marketplace/halyard, repository does not exist or may require 'docker login': denied: Permission denied for "1.37.0" from request "/v2/spinnaker-marketplace/halyard/manifests/1.37.0".```

**Comment by ethai** [comment]
use this instead

us-docker.pkg.dev/spinnaker-community/docker/halyard:TAG

**Comment by peppe77** [comment]
thank you @ethai
