### ISSUE TITLE
Formatting error on curl command blurb in "GCE Source To Prod" codelab

### ISSUE THREAD

**Issue by stewchen** [spinnaker/spinnaker#2171]
In "GCE Source To Prod" codelab page, the curl command blurb under "Install gcloud" is formatted with a lot of blank space.

**Comment by dorbin** [comment]
Created issue #453 in spinnaker/spinnaker.github.io

**Comment by dorbin** [comment]
@stewchen , can you close this? I don't seem to be able to close issues in this repo.
