### ISSUE TITLE
settings-local.js custom profile not honored

### ISSUE THREAD

**Issue by mbascus** [spinnaker/spinnaker#2199]
*Cloud Provider*

Kubernetes (GKE)

*Environment*

- Halyard: 0.38.0-24
- Spinnaker: 1.5.1
- Kubernetes: 1.7.8-gke.0 (GKE)

*Feature Area*

UI

*Description*

Expected settings-local.js parameters to be honored. They are not.

*Steps to Reproduce*

- deploy a custom profile for settings-local.js, eg `window.spinnakerSettings.notifications.hipchat.botName = 'hello world';`
- in the spinnaker ui, add a hipchat notification and you will see the default bot name still: 
  >**Please note:** You need to invite the **Skynet T-800** bot to...

*Additional Details*

if you copy the settings-local.js file to settingsLocal.js and reload apache, the expected botName will show up
- on the deck pod:

      cp /opt/deck/html/settings-local.js /opt/deck/html/settingsLocal.js
      apachectl graceful
- in the spinnaker ui, hard refresh and the expected bot name shows up when adding a hipchat notification:
  >**Please note:** You need to invite the **hello world** bot to...

**Comment by lwander** [comment]
@danielpeach could you take a look?

**Comment by lwander** [comment]
Closed by dan's patch above
