### ISSUE TITLE
Kubernetes V2 opt-out-of-caching annotation

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2214]
`caching.spinnaker.io/ignore: True` will tell spinnaker to ignore this resource 

Should include a doc update too: https://www.spinnaker.io/reference/providers/kubernetes-v2/#reserved-annotations

**Comment by tony612** [comment]
Any plan to support whitelist? We can configure the default is ignore but allow caching for resources with annotation like `caching.spinnaker.io/allow: True`, so that we can use Kubernetes V1 and Kubernetes V2 together for one k8s cluster.
