### ISSUE TITLE
bug(deck): deleting env var from causes displayment error

### ISSUE THREAD

**Issue by yue9944882** [spinnaker/spinnaker#2230]
### bug(deck): deleting env var from causes displaying error

As is shown in the following picture, I set two env var for a container, one is loaded from `ConfigMap` and the other is loaded from `Secret`. Then I delete the upper env:

(before)

<img width="644" alt="before" src="https://user-images.githubusercontent.com/12049380/34637803-c907db7e-f2f8-11e7-9f98-6dc7d959e718.png">

(after)

<img width="654" alt="after" src="https://user-images.githubusercontent.com/12049380/34637804-d0c1f156-f2f8-11e7-9f5b-ae05a1cb2a08.png">

As u can see, the env var displays weirdly, and the type of `bar` was mismatched.

### Cloud Provider 

kubernetes

### Environment

deployed by halyard

*image: gcr.io/spinnaker-marketplace/deck:2.0.0-20171108151529*

**Comment by ethanfrogers** [comment]
@yue9944882 this was originally reported here: https://github.com/spinnaker/spinnaker/issues/1866

and fixed in this PR: https://github.com/spinnaker/deck/pull/4430

it should be available whenever the next minor release happens.
