### ISSUE TITLE
Kubernetes V2 jobs are timing out under load

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2232]
What's likely is that https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy is unable to create enough worker threads to handle the number of calls to required to cache more than a handful of accounts. Testing to confirm by increasing the required cache threads & number of available accounts.

**Comment by lwander** [comment]
The work the scheduled threads are doing is dominated by this (kind of suspect) sleep: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy#L95

I'm guessing that this `computation` scheduler is not the right choice here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.groovy#L43

**Comment by lwander** [comment]
It's actually not clear why we need that scheduler at all - it exists only to create a thread which does no heavy synchronous work, and is polled for completion immediately. Removing it seems to make everything run faster - so far it's only been a bottleneck.

**Comment by lwander** [comment]
@davidxia - I'm going to build another `master-latest-unvalidated` with this patch - I'll ping you when it's ready

**Comment by davidxia** [comment]
Awesome. Thanks so much.
-- 
David Xia
davidxia.com

**Comment by lwander** [comment]
Let me know if that patch is working for you @davidxia

**Comment by lwander** [comment]
Confirmed to be working now
