### ISSUE TITLE
Showing Environment Variables in Custom Notifications

### ISSUE THREAD

**Issue by winlamevite** [spinnaker/spinnaker#2256]
*Feature Area*
Notifications

*Description*
When setting up Slack/Email notifications for each stage in my Spinnaker pipeline, I would like to request an option to enter a customer notification message that shows the Jenkins Job Name, Git Branch Name, and/or a customer bash variable in the customer notification message.

**Comment by lwander** [comment]
Turns out this was working - see https://community.spinnaker.io/t/variables-in-custom-notification-message/142/7?u=lwander
