### ISSUE TITLE
AWS Jenkins multi debian package jobs fail to bake

### ISSUE THREAD

**Issue by bensnet1** [spinnaker/spinnaker#2269]
*Title*

AWS Jenkins multi debian package jobs fail to bake

*Cloud Provider*

AWS

*Environment*

We build our own Spinnaker using the debian packages.
Package list below:
ii  spinnaker                        0.84.0                                     all          spinnaker
ii  spinnaker-clouddriver            1.762.0                                    all          spinnaker-clouddriver
ii  spinnaker-deck                   2.1171.0                                   all          spinnaker-deck
ii  spinnaker-echo                   1.543.0                                    all          spinnaker-echo
ii  spinnaker-fiat                   0.37.0                                     all          spinnaker-fiat
ii  spinnaker-front50                1.120.0                                    all          spinnaker-front50
ii  spinnaker-gate                   4.17.2                                     all          spinnaker-gate
ii  spinnaker-igor                   1.87.6                                     all          spinnaker-igor
ii  spinnaker-orca                   5.10.7                                     all          spinnaker-orca
ii  spinnaker-rosco                  0.102.0                                    all          spinnaker-rosco

Last known working version of this ( we have not tried to update for a while )
ii  spinnaker                        0.83.0                                     all          spinnaker
ii  spinnaker-clouddriver            1.684.0                                    all          spinnaker-clouddriver
ii  spinnaker-deck                   2.1141.0                                   all          spinnaker-deck
ii  spinnaker-echo                   1.146.0                                    all          spinnaker-echo
ii  spinnaker-fiat                   0.30.2                                     all          spinnaker-fiat
ii  spinnaker-front50                1.114.0                                    all          spinnaker-front50
ii  spinnaker-gate                   4.6.5                                      all          spinnaker-gate
ii  spinnaker-igor                   1.75.1                                     all          spinnaker-igor
ii  spinnaker-orca                   3.22.3                                     all          spinnaker-orca
ii  spinnaker-rosco                  0.99.0                                     all          spinnaker-rosco

*Feature Area*

AMI bake / Rosco

*Description*

Bake should apply both configured package artifacts in the order provided in the bake job.

*Steps to Reproduce*

Any deployment that creates two debian packages to be installed onto a Base AMI on AWS.

*Additional Details*

Additional information such as screenshots and exception logs.

**Comment by bensnet1** [comment]
This is the message in the GUI:

Exception ( Create Bake )
Jenkins job detected but no artifacts found, please archive the packages in your job and try again.

**Comment by bensnet1** [comment]
More info 

Seeing this in the job
"exception": {
"details": {
"error": "Unexpected Task Failure",
"errors": [
"Jenkins job detected but no artifacts found, please archive the packages in your job and try again."
],
"stackTrace": "java.lang.IllegalStateException: Jenkins job detected but no artifacts found, please archive the packages in your job and try again.\n\tat com.netflix.spinnaker.orca.pipeline.util.PackageInfo.createAugmentedRequest(PackageInfo.java:117)\n\tat com.netflix.spinnaker.orca.pipeline.util.PackageInfo.findTargetPackage(PackageInfo.java:86)\n\tat com.netflix.spinnaker.orca.pipeline.util.PackageInfo$findTargetPackage.call(Unknown Source)\n\tat com.netflix.spinnaker.orca.bakery.tasks.CreateBakeTask.bakeFromContext(CreateBakeTask.groovy:137)\n\tat com.netflix.spinnaker.orca.bakery.tasks.CreateBakeTask.execute(CreateBakeTask.groovy:67)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:68)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$29387641.call(AuthenticationAware.kt)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:153)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:46)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:30)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:56)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:30)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:65)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:52)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:39)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:146)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:57)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:45)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:54)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
},


Noted that this is what is missing:
"bakePackageName":

**Comment by bensnet1** [comment]
Looking into this further.

In this file package is type string. - https://github.com/spinnaker/orca/blob/master/orca-validation/src/main/resources/schemas/bake.json

The UI has this description and it did used to work in this exact way.
"If there are multiple packages (space separated), then they will be installed in the order they are entered."

**Comment by ajordens** [comment]
Should be fixed by https://github.com/spinnaker/orca/pull/2016

**Comment by bensnet1** [comment]
This was fixed by https://github.com/spinnaker/orca/pull/2016
Closing issue.
