### ISSUE TITLE
Orca 5.10.1 ContextParameterProcessor doesn't handle non-map buildInfo data

### ISSUE THREAD

**Issue by dotdotdotpaul** [spinnaker/spinnaker#2278]
We have a webhook test that simply does a GET from www.google.com.  Upgrading to 5.10.1, this webhook no longer exits, it idles for an hour before being timed out.

Searching logs, found this error in Orca:

```
Exception in thread "handlers-25" groovy.lang.MissingPropertyException: No such property: scm for class: java.lang.String
org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:410)
com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.precomputeValues(ContextParameterProcessor.groovy:86)
com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor$precomputeValues.callCurrent(Unknown Source)
com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.process(ContextParameterProcessor.groovy:51)
...
```

In 5.10.1, it looks like `ContextParameterProcessor` was added to all stage processes.  This class (at least the `precomputeValues` function) assumes that `buildInfo` is set to null or a map.  In fact, the output of the GET request is stored there as a string -- causing the above failure.  This failure doesn't appear to get reported back up to the task processor, so the task just times out, rather than fail with an indication of the underlying exception.

Here's the stage JSON we used:

```
{
  "method": "GET",
  "name": "Ping Google",
  "statusUrlResolution": "getMethod",
  "type": "webhook",
  "url": "https://www.google.com/"
}
```

This should not be provider-specific.

Not sure if the fix for this should be to "robustify" `ContextParameterProcessor` so it doesn't make assumptions about `buildInfo` (and sanely handle when it's not a map)...  Or if the webhook stuff needs to get tweaked so that it doesn't save a non-map into `buildInfo` regardless what was returned from the call.

**Comment by mikerowehl** [comment]
This looks to be fixed by https://github.com/spinnaker/orca/commit/bcf7a17843d43d9ba56a9e7d8e46712dbd6551fb

Thanks folks!

**Comment by dotdotdotpaul** [comment]
Woot!
