### ISSUE TITLE
Defaults for artifacts should allow a user to specify a branch

### ISSUE THREAD

**Issue by imosquera** [spinnaker/spinnaker#2293]
*Title*
Defaults for artifacts should allow a user to specify a branch

*Cloud Provider*
Kubernetes

*Feature Area*
Kubernetes V2 Provider, pipeline configuration

*Description*
In the pipeline configuration, we should be able to specify a branch for the default github manifest artifacts.  Currently you can only specify a single path.

![image](https://user-images.githubusercontent.com/69049/35755104-d12753b6-081a-11e8-83ef-cac8404d3c72.png)

**Comment by imosquera** [comment]
Spoke to @lwander - suggested that we expose a version field so we can input a branch name.

**Comment by lwander** [comment]
Also just to be clear, this should only be exposed on the __Default artifact__.
