### ISSUE TITLE
Upgrade base Docker images in Spinnaker services

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#2298]
The current base image for orca and deck (and I assume for other Spinnaker services as well) is `openjdk:8u111-jre-alpine` which is based on Alpine Linux 3.4.6.

This fact raises the following concerns:

- Alpine Linux 3.4.6 was released 15 months ago so it probably contains many known security vulnerabilities
- Newer JDK versions treat OS memory and CPU limits better: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

So the proposal is to upgrade the base to the latest `8u151-jre-alpine`.

**Comment by tomaslin** [comment]
sounds good, please submit a pr

**Comment by wheleph** [comment]
@tomaslin please have a look at the PRs above. If they look good to you I'll make the similar changes in the rest of the services.

**Comment by wheleph** [comment]
@tomaslin @lwander do the above PRs look good to you? Can you accept those?

**Comment by lwander** [comment]
Looking now - sorry for the wait

**Comment by lwander** [comment]
We appreciate this - thanks! They'll be live in spinnaker 1.6
