### ISSUE TITLE
Show which artifacts arrived in a trigger

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2299]
Similar to to how pipeline parameters are rendered, we should be pointing out which artifacts are arriving as well for visibility.

**Comment by sbwsg** [comment]
From in-person convo and for my own reference, here's how params currently appear in pipelines in deck (the `foo:"bar"` bit):

![params](https://user-images.githubusercontent.com/34253460/35820973-6d92307a-0a75-11e8-8ede-e2c202902f86.png)
