### ISSUE TITLE
Triggers don't work when configured from Github organization webhooks

### ISSUE THREAD

**Issue by imosquera** [spinnaker/spinnaker#2300]
*Title*
Github triggers don't work when used from an organization webhook

*Feature Area*
Triggers in Pipeline configuration

*Description*
There are two scopes to create github webhooks: organization wide or repository specific.  If you use the organization wide webhook it does not execute the pipeline.

*Steps to Reproduce*
Setup organization webhooks in github, configure a github trigger in Spinnaker.  Make a commit to the repo.  No pipeline should trigger.

*Steps to Reproduce*
Setup a github trigger on a pipeline an then configure your github webhooks at the organization level for all repositories.  

*Additional Details*
Here is how i setup the org level trigger
![image](https://user-images.githubusercontent.com/69049/35820190-c18bc2fc-0a59-11e8-9ab8-d8feb2aa69c2.png)

**Comment by lwander** [comment]
Can you share the API reference for org-wide push events rather than rep-wide ones?

**Comment by wjoel** [comment]
I've been using an organization level webhook ever since I started testing the Kubernetes v2 provider at work, without any issues. Do you see anything in the echo logs?

**Comment by imosquera** [comment]
I'll dig into the issue and see if I can find more information.

**Comment by lwander** [comment]
Can't repro -- isaac

**Comment by imosquera** [comment]
This should work now.  I no longer see the issue.
