### ISSUE TITLE
Tags do not persist when cloning a cluster (AWS)

### ISSUE THREAD

**Issue by nc-fosterr** [spinnaker/spinnaker#2316]
As a user on AWS, I expect that tags I set in Spinnaker cluster persistent when I clone it. Currently, it does not appear to be case.

### Steps to reproduce

1. On **Server Group Actions**, select **Clone**.
2. Scroll all the way to the bottom, add a tag or tags (For example: "Environment" for Key and "Production" for Value)
3. Click on **Create**.
4. On the new cluster, click on **Clone**.
5. Scroll all the way to the bottom.

### Expected Behavior

The tag(s) should be present.

### Actual Behavior

The tag(s) are not present.

### Version

Spinnaker 1.5.4
Clouddriver: 1.0.4-20180110144440 (2018-01-10)

**Comment by anotherchrisberry** [comment]
This was fixed in https://github.com/spinnaker/deck/pull/4491 - not sure if that was included in Spinnaker 1.5.4 or not, but it should be included in Deck starting with version 2.1159.0.

**Comment by nc-fosterr** [comment]
It looks like 1.5.4 runs 2.0.1-20180110144440, so no, I don't have it. Good to know, I'll keep a watch for it and test it.

**Comment by nc-fosterr** [comment]
I confirmed that it is working, so I am closing this. Thanks, @anotherchrisberry !
