### ISSUE TITLE
Link to resources in UI next to YAML in Deploy Pipeline

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2327]
![links](https://user-images.githubusercontent.com/4874941/36029669-33b388ae-0d72-11e8-8a16-5bebdf658150.png)

Right now only the YAML shows up, but you should be able to click on another link that will take you to the server group/load balancer/config map details

**Comment by sbwsg** [comment]
Deployments and ReplicaSets now link to their details view in the clusters tab.  We also need a generic details view for resources that don't get described elsewhere in the UI.

**Comment by lwander** [comment]
Also https://github.com/spinnaker/spinnaker/issues/2496 to make the mapping generic

**Comment by sbwsg** [comment]
Re: a generic details view for kubernetes resources that aren't currently represented by spinnaker's UI elements see https://github.com/spinnaker/spinnaker/issues/2586
