### ISSUE TITLE
Spinnaker webhook stage should be able to produce artifacts

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2330]
If you provide "expected artifacts" to a webhook stage, and it returns ` { "artifacts": [ ... ], ... }`, it should be injected into the stage outputs.

**Comment by lwander** [comment]
Will be built on: https://github.com/spinnaker/spinnaker/issues/2339

**Comment by ethanfrogers** [comment]
i'm currently working on adding support for this.
