### ISSUE TITLE
Figure out how to pass pipeline context from child pipeline back to parent

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2338]

**Comment by lwander** [comment]
The context was to support passing artifact info back from child pipelines. This works now in 1.6.0

**Comment by rosepan** [comment]
Sorry to update this closed issue. Wondering what's the usage to get the pipeline context from child pipeline to parent pipeline? I can't find any doc for this.

Also how to get the pipeline context from sibling pipelines back to the current pipeline?

Appreciate your help. Thanks.
