### ISSUE TITLE
Add pipeline stage to Find Arbitrary Artifact

### ISSUE THREAD

**Issue by hodgesmr** [spinnaker/spinnaker#2345]
Currently, there's a pipeline stage that allows to find an artifact from a previous stage's execution. It would be beneficial to also have a stage that simply took a path to an artifact without needing a **Pipeline Selector**.

A provided object path could be static, or rely on pipeline configuration values or pipeline expressions.

We're currently getting around this requirement by populating the **Find Artifact From Execution Configuration** section with a no-op stage.

**Comment by hodgesmr** [comment]
This might be a duplicate of #2339

**Comment by lwander** [comment]
Closing as it's a dup of #2339 (close to be implemented, too)
