### ISSUE TITLE
Differentiate K8s V1 and V2 providers when creating application in deck

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#2350]
A user with both a v1 and v2 provider configured in halyard is not able to select which provider version to use when creating an application.

TODO:
- Confirm whether this has a negative impact when configuring an application.  Is it possible to choose v1 vs v2 despite this limitation when creating an app?
- If the user is somehow able to choose between v1 and v2 then document that.
- Otherwise, fix the App Creation screen to allow selection of either v1 or v2.

**Comment by ethanfrogers** [comment]
Does this suggest that using both provider versions in the same application will be restricted?

**Comment by sbwsg** [comment]
Turns out this issue is a no-op.  We already have a version selector when creating an application:

![kubernetes_choice](https://user-images.githubusercontent.com/34253460/36319513-2169b368-1311-11e8-800e-460c224c1804.png)

![kubernetes_version](https://user-images.githubusercontent.com/34253460/36319518-23b6c354-1311-11e8-8d94-934c7750511e.png)

Chalk this one up to a newbie dev not knowing the UI well enough.

**Comment by sbwsg** [comment]
@ethanfrogers the opposite - i wanted to make sure that users could absolutely run both versions of the provider in a single application.  turns out they can already.

**Comment by ethanfrogers** [comment]
@sbwsg ah, cool. i was going to mention that but wanted to make sure of the other point first. thanks!
