### ISSUE TITLE
Slack notifications from stages not being sent on "release-1.6.x-latest-unvalidated"

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#2357]
*Slack notifications from stages not being sent with "release-1.6.x-latest-unvalidated"*

*Cloud Provider*: Kubernetes + AWS

*Environment*: Distributed - and Halyard-managed Spinnaker running on top of GKE, but deploying to AWS.

*Feature Area*: Notifications / Echo / Slack.

*Description*: After upgrading Spinnaker 1.5.4 to "release-1.6.x-latest-unvalidated" - the stage-level notifications to Slack stopped going out. Echo does not log anything. Notifications from application level- and pipeline level are going out normally.

*Steps to Reproduce*

1. bump Spinnaker version to "release-1.6.x-latest-unvalidated"
2. configure pipeline with a stage - and enable Slack notifications from stage
3. expect: no notifications to Slack

*Additional Details*: none

**Comment by anotherchrisberry** [comment]
We just noticed this yesterday and pushed a couple of changes to address it:
* https://github.com/spinnaker/orca/pull/2007 (available in https://github.com/spinnaker/orca/releases/tag/v6.7.0)
* https://github.com/spinnaker/echo/pull/238 (available in https://github.com/spinnaker/echo/releases/tag/v1.547.0)

**Comment by lwander** [comment]
Will cherry pick into release-1.6.x -- I'll let you know when the branches are rebuilt.

**Comment by jtk54** [comment]
Nice.

**Comment by lwander** [comment]
Cherry picked, building now

**Comment by lwander** [comment]
release-1.6.x-latest-unvalidated has been updated - can you confirm the fix @iniinikoski?

**Comment by iniinikoski** [comment]
@lwander & others, works beautifully now. Cool, thanks!

**Comment by lwander** [comment]
Great!
