### ISSUE TITLE
User doesn't see new service account in UI

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker#2360]
See [issue #576](https://github.com/spinnaker/spinnaker.github.io/issues/576) in spinnaker/spinnaker.github.io.

**Comment by dorbin** [comment]
@stewchen

**Comment by danielpeach** [comment]
Thanks, @prashantdj1, can you please provide more detail? Two things to check:

- Do you see your service account listed under `{gate}/auth/user/serviceAccounts`?
- Have you confirmed that your service account has been persisted by front50?

**Comment by prashantdj1** [comment]
I can't see in {gate}/auth/user/serviceAccounts
yes the service account is persisted to front50 as I am able to do curl $FIAT/authorize/myApp-svc-account after doing curl -X POST $FIAT/roles/sync

**Comment by ethanfrogers** [comment]
@prashantdj1 is the user a member of _all_ groups listed in the service account? to prevent privilege escalation, users must be in all groups that the service account lists in the `memberOf` key.

**Comment by prashantdj1** [comment]
I think my bad. I made memberOf to all applications in spinnaker. I changed it to google groups for which we are using.

**Comment by ethanfrogers** [comment]
fantastic, let us know if it works so we can close this issue!

**Comment by prashantdj1** [comment]
It works!! Thanks!! Please close this.
