### ISSUE TITLE
Server Group Manager details view is broken

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#2362]
It looks like https://github.com/spinnaker/deck/pull/4868 may have broken the Server Group Manager details view in the v2 provider.

Before that PR commit, accessing server group manager details rendered the view correctly:
![0f990322-36a7-473b-a150-7e5418348dbd](https://user-images.githubusercontent.com/34253460/36490975-9d22159c-16f7-11e8-8141-74bf73c15283.gif)

After the commit, the details view does not appear on click:

![f85e27f3-2a54-4703-98c8-1c3cb6e66d5f](https://user-images.githubusercontent.com/34253460/36490892-6064df04-16f7-11e8-9b9f-276524b53da8.gif)

I'm unclear exactly why but checking out the commit directly before that PR allows the details view to appear correctly.

**Comment by anotherchrisberry** [comment]
This bug is also affecting instance and load balancer details on AWS

**Comment by ethanfrogers** [comment]
@anotherchrisberry does the pending fix from @christopherthielen fix it?

**Comment by christopherthielen** [comment]
@sbwsg can you try with what's in master right now?

**Comment by sbwsg** [comment]
This issue looks to have been resolved by https://github.com/spinnaker/deck/pull/4889

Thanks!
