### ISSUE TITLE
Need ability to specify a pull policy for Run Job stage, or at least to manually refresh

### ISSUE THREAD

**Issue by nneul** [spinnaker/spinnaker#2461]
*Cloud Provider*

AWS via kops

*Environment*

Halyard deployed, currently 1.5.4, running against kops deployed k8s

*Feature Area*

Pipelines / Run Job

*Description*

No way appears to exist to be able to update a run job image that has used :latest - I can understand not defaulting to pull always - but there should be SOME option to be able to trigger a pull without having to hardwire a version tag in the pipeline stage. 

Ideally, would like to have 'Pull Always' and 'Pull if older than X seconds' options or something along those lines.

**Comment by ethanfrogers** [comment]
@nneul the ability to define a Pull Policy on the Run Job stage is available in 1.6! However, pipelines cannot be triggered based on `:latest` as Spinnaker indexes image tags instead of digests.
