### ISSUE TITLE
Not able to create or list Application or Projects in Spinnnaker UI.

### ISSUE THREAD

**Issue by janoobhandar** [spinnaker/spinnaker#2466]
Not able to create or list Application or Projects in Spinnnaker UI.

*Cloud Provider*

Kubernetes

*Environment*

I am running Spinnaker using Ubuntu16.04.

*Feature Area*

UI

*Description*

Not able to create a cluster group/ Pipelines etc

![capture](https://user-images.githubusercontent.com/11307448/36672606-30b57662-1b00-11e8-85c2-903ec74f7273.PNG)

**Comment by brandonnelson3** [comment]
@janoobhandar Going to need more information about your setup. Are you running Spinnaker locally? It looks like maybe you are running Spinnaker on a cloud VM, and maybe didn't port forward port 8084 to the instance? 

Feel free to ping me on slack to discuss.

**Comment by janoobhandar** [comment]
Hi @brandonnelson3 , Many thanks for the reply.
I am running Spinnaker Locally and I get this error, I have installed Spinnaker's latest version-Glow.

**Comment by brandonnelson3** [comment]
@janoobhandar Are you running Spinnaker in a docker container? Why are you running docker-proxy on port 9000?

**Comment by brandonnelson3** [comment]
@janoobhandar can you run:

$ netstat -nlp | grep 8084

**Comment by cdelguercio** [comment]
I have the same issue, but I've progressed a little further. I noticed that only my redis and Deck (9000) ports were listening in netstat.

When I tried using the UI to create a new application or project I would see the similar errors to janoobhandar (except I would see ERR_EMPTY_RESPONSE) with these messages on my Spinnaker server's stdout:

channel 22: open failed: connect failed: Connection refused
channel 23: open failed: connect failed: Connection refused
channel 17: open failed: connect failed: Connection refused

To fix this I ran sudo service gate restart and then port 8084 showed up. I then ran sudo service restart on orca, igor, front50, echo, and clouddriver and their respective ports started showing up in netstat.

Now I still can't create or list Applications or Projects but I don't get the connect refused errors that I was seeing earlier. I do get a 500 error on localhost:8084/projects. Also, I don't see any error logs in /var/log/spinnaker/XXXX/.

To note is that I see this WARNING when I do a sudo hal deploy apply:

WARNING No validation for the AWS provider has been implemented.

**Comment by brandonnelson3** [comment]
@cdelguercio did you upgrade from a previous version of Spinnaker?

**Comment by brandonnelson3** [comment]
Also, error logs don't show up in /var/log/spinnaker/XXXX/ anymore in 16.04, since xenial uses systemd, it also uses journalctl for logging. Try running journalctl to see the entire log.

**Comment by janoobhandar** [comment]
root@ubuntu:/home/ubuntu# netstat -nlp | grep 8084
tcp6       0      0 127.0.0.1:8084          :::*                    LISTEN      27349/java

**Comment by janoobhandar** [comment]
Should I use a specific version of Kubernetes, Spinnaker, and hal?

**Comment by wardviaene** [comment]
I experience the same issue as @cdelguercio, only service start brings up the different services. They were not started automatically. This is a local Spinnaker install on ubuntu xenial with the latest Spinnaker version.

This is not an upgrade, but a new install. When I ran deploy, I had configured auth and storage, but not a cloud provider account (yet)

**Comment by janoobhandar** [comment]
@wardviaene: I have restarted all the services and still I am getting the same error.

**Comment by tech-vsilva** [comment]
@janoobhandar have you found a solution to your problem? I'm facing the same issue, unfortunately.

**Comment by fr34k8** [comment]
@janoobhandar  @tech-vsilva 
any progress here ?

**Comment by tech-vsilva** [comment]
@fr34k8 Yes, the solution was to check if all the services are running properly. On Ubuntu 16.04 you need to (re)start all the service manually:

Make a script file with this and execute it:
```
#!/bin/bash

sudo systemctl restart apache2
sudo systemctl restart gate
sudo systemctl restart orca
sudo systemctl restart igor
sudo systemctl restart front50
sudo systemctl restart echo
sudo systemctl restart clouddriver
sudo systemctl restart rosco
```

**Comment by sbwsg** [comment]
I'm going to close out this issue now. For anyone seeing this problem, please check that Spinnaker's services have started by looking for the bound ports the services use with `netstat -nlp` command. To restart the services, follow @tech-vsilva's comment above.

If the problem persists after following those instructions please create a new Github issue describing the symptoms along with the following details:

- OS / VM image you're running Spinnaker on
- Spinnaker version
- Halyard version
- Contents of `hal config -q` with any sensitive information removed

**Comment by rushins** [comment]
i have the issue even today with latest 1.15 release, can someone help me what is the root cause.

**Comment by rushins** [comment]
my setup ubuntu 16.04 and Minio on separate hosts, ubuntu running spinnkar install , i made sure all services all up 
sudo systemctl restart apache2
sudo systemctl restart gate
sudo systemctl restart orca
sudo systemctl restart igor
sudo systemctl restart front50
sudo systemctl restart echo
sudo systemctl restart clouddriver
sudo systemctl restart rosco

I checked my Minio bucket and front50 bucket got created. All seems functioning ok but when create application or project from deck the screen hung and runs forvever.
 can someone please help , if this error due to ubuntu /spinnaker or minio. what is the best way to use local debian without kubernetes

please suggest
