### ISSUE TITLE
Kubernetes v2 save stored manifest embeds a new list each time

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2470]
To reproduce: 

1. Create a new pipeline with a Deploy (Manifest) stage.
2. Enter any YAML (e.g. 
   ```yaml
   apiVersion: v1
   ```
3. Save & exit the pipeline editor.
4. Edit the pipeline again, notice that the YAML has become
   ```yaml
   - apiVersion: v1
   ```
   This is a single item list, and is OK and intentional (manifests are stored as a list to support manifest docs).
5. Make a trivial edit to the YAML
   ```yaml
   - apiVersion: v2
   ```
6. Save & exit the pipeline editor
7. Edit the pipeline again, notice that the YAML has become
   ```yaml
   - - apiVersion: v2
   ```
   This is now list with one element containing a single item list. (not good)

**Comment by lwander** [comment]
What's weirdest is that the JSON stored by spinnaker after 7. is
```json
  "manifests": [
    {
      "0": {
        "apiVersion": "v2"
      }
    }
  ],
```

**Comment by e96wic** [comment]
Any workarounds for this?

**Comment by lwander** [comment]
I don't know yet, but this should be fixed shortly
