### ISSUE TITLE
Page Not Found: https://www.spinnaker.io/docs/troubleshooting-guide

### ISSUE THREAD

**Issue by svenbovens** [spinnaker/spinnaker#2482]
The incident template refers to https://www.spinnaker.io/docs/troubleshooting-guide which doesn't appear to exist (any more). Preferably the link should be corrected, or if the guide is no longer available, this paragraph should be removed from the template.

**Comment by sbwsg** [comment]
Thanks for reporting! The issue template should now be fixed.
