### ISSUE TITLE
Spinnaker services are not starting when Spinnaker starts

### ISSUE THREAD

**Issue by btromanova** [spinnaker/spinnaker#2489]
Hi,

I'm trying to install Spinnaker 1.6.0 on Ubuntu 16.04 using Halyard with local deployment.
`sudo hal deploy apply` finishes without error, but there're no Spinnaker services (gate, deck, etc) running.

*Cloud Provider*

AWS

*Environment*

Halyard 0.41.0-180212111030, Spinnaker 1.6.0, Ubuntu 16.04.

*Feature Area*
Installation

*Steps to Reproduce*

* Follow Spinnaker installation with Halyard from https://www.spinnaker.io/setup/install/halyard/ on Ubuntu 16.04. 
* Select local deployment `hal config deploy edit --type localdebian`
* Set up S3 as persistent storage and AWS as provider.
* Set Spinnaker to v1.6.0
* After `sudo hal deploy apply` check if gate is listening on port 8084:

Expected:
```
tr@spinnaker:~$ telnet localhost 8084
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'
```

Actual:
```
tr@spinnaker:~$ telnet localhost 8084
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```
*Additional Details*

When I tried to start Spinnaker manually via `sudo service spinnaker start`, I didn't see its dependencies starting. As far as I understand halyard writes systemd startup script to `/lib/systemd/system/spinnaker.service`. In my case it looks like that:
```
[Unit]
Description=All Spinnaker services
After=network.target
Wants={%systemd-service-configs%}
[Service]
Type=oneshot
ExecStart=/bin/true
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
```

I managed to make Spinnaker working by manually replacing `{%systemd-service-configs%}` with `gate.service orca.service clouddriver.service front50.service rosco.service igor.service echo.service fiat.service` and run
```
systemctl daemon-reload
service spinnaker start
```
But I don't know, why the variable wasn't substituted during the installation.

**Comment by brandonnelson3** [comment]
That sounds like a bug in some code I wrote a while back, let me take a look and get back to you.

**Comment by brandonnelson3** [comment]
I've sent https://github.com/spinnaker/halyard/pull/859 to fix this... thanks for filing the bug. 

This should get built tonight and released with our next patch release, but the outcome is basically to generate the file as you have modified it from the get-go.

**Comment by btromanova** [comment]
Thanks for the quick fix!

**Comment by brandonnelson3** [comment]
I also sent: https://github.com/spinnaker/halyard/pull/860 to prevent this from being likely to occur in the future, or at least help prevent it.
