### ISSUE TITLE
Scroll is not working on Spinnaker Applications tab in Chrome

### ISSUE THREAD

**Issue by btromanova** [spinnaker/spinnaker#2508]
*Title*
Scroll is not working on Spinnaker Applications tab in Chrome

*Cloud Provider*
AWS

*Environment*
Spinnaker 1.6.0, Chrome Version 58.0.3029.110 (64-bit)

*Feature Area*
UI

*Description*
Scroll or pager don't appear when Applications list is too long. Doing
```
$('.spinnaker-container').css('overflow', 'scroll')
```
helps.

*Additional Details*

Before adding ("overflow", "scroll"):
<img width="738" alt="screen shot 2018-03-06 at 1 26 50 pm" src="https://user-images.githubusercontent.com/3741685/37032258-2705b2c4-2142-11e8-9e6d-c6430de1ff1a.png">

After:
<img width="743" alt="screen shot 2018-03-06 at 1 27 15 pm" src="https://user-images.githubusercontent.com/3741685/37032283-3c4fe546-2142-11e8-8df0-d866db73b110.png">

**Comment by dansimau** [comment]
Also reproduced in Firefox 57.0, macOS.
