### ISSUE TITLE
AWS security groups are created with empty Name tag

### ISSUE THREAD

**Issue by j-vizcaino** [spinnaker/spinnaker#2509]
*Cloud Provider*

AWS

*Environment*

Spinnaker running on AWS.
Spinnaker components and version:

```
ii  spinnaker-deck                      2.1.0-20180301113852                       all          spinnaker-deck
ii  spinnaker-echo                      0.8.0-20180220013007                       all          spinnaker-echo
ii  spinnaker-front50                   0.9.0-20180220013007                       all          spinnaker-front50
ii  spinnaker-gate                      0.10.0-20180220013007                      all          spinnaker-gate
ii  spinnaker-halyard                   0.41.0-20180212220704                      all          spinnaker-halyard
ii  spinnaker-igor                      0.10.0-20180228121942                      all          spinnaker-igor
ii  spinnaker-monitoring-daemon         0.5.0-20180220013007                       all          spinnaker-monitoring-daemon
ii  spinnaker-orca                      0.10.0-20180301113852                      all          spinnaker-orca
ii  spinnaker-rosco                     0.5.0-20180220013007                       all          spinnaker-rosco
```

*Feature Area*

Clouddriver?

*Description*

Creating a new security group with Spinnaker creates an AWS security group resource with a single tag `Name` and no value. The expected behaviour would be to have `Name` set to the security group name.

*Steps to Reproduce*

* create an application
* create a new security group
* inspect newly created security group tags using AWS console or aws-cli: it has a single `Name` tag with no associated value.

**Comment by anshrma** [comment]
@spinnaker/netflix-reviewers - Wanted to get your opinion on this. Currently upsert operation for SG does not uses any tags and input name is mapped to GroupName property as appropriate (and , hence this is not a bug. 

We should rather generalize this to a feature  request to add tagging support for Security Group. Thoughts ?
