### ISSUE TITLE
Fiat uses Frigga to parse resource names

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#2513]
See: https://github.com/spinnaker/fiat/blob/master/fiat-api/src/main/java/com/netflix/spinnaker/fiat/shared/FiatPermissionEvaluator.java#L106-L111

This breaks authz for applications with dashes - e.g., Fiat interprets a read request for `my-app` as a read request for `my`.

**Comment by wjoel** [comment]
Oh, so *that's* (almost certainly) why I was having issues the other week and had to delete the `spin-fiat` deployment, even if it never caused any issues before. Nice catch, thank you! I didn't manage to figure it out myself.

**Comment by danielpeach** [comment]
This (hopefully) requires only a bit of work and manual verification.

`hasPermission` should only be invoked with an account name or an application name, not an `app-stack-detail` resource in which the application name can be derived using Frigga.

In many places we resolve the application name from a resource's Moniker:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/ServerGroupController.groovy#L72

In some places, we fall back on Frigga if we can't find a Moniker on a resource, but it should be up to callers of `hasPermission` to do this fallback instead of `hasPermission` itself.

Would need to verify that `hasPermission` is being used appropriately across the Spinnaker microservices, and then remove the Frigga parsing from `hasPermission`.

**Comment by dibyom** [comment]
Compiled a list of all `hasPermission` usages in all Spinnaker repos:
https://gist.githubusercontent.com/dibyom/901f3b336fd0b8962895d46d33b0526b/raw/b11feb0672ea64a0a03c2abbdf08ef687d586c41/gistfile1.txt
