### ISSUE TITLE
Support instance-links in Kubernetes v2 UI

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2528]
This will help users format custom links into the kubernetes UI, logs & metrics viewers, context-specific details,  etc....

**Comment by sbwsg** [comment]
Relevant doc for existing links: https://www.spinnaker.io/guides/user/instance-links/

**Comment by sbwsg** [comment]
This feature may be best implemented using annotations as per https://github.com/spinnaker/spinnaker/issues/2529

**Comment by sbwsg** [comment]
Instance links are now covered by the work done for https://github.com/spinnaker/spinnaker/issues/2529

**Comment by wuzhihui1123** [comment]
I want to have a place to configure custom links for instances globally.  now ,If there are changes, I need to modify the instance one by one @sbwsg

**Comment by sbwsg** [comment]
@wuzhihui1123 Please create a Github issue to describe your feature request: https://github.com/spinnaker/spinnaker/issues/new
