### ISSUE TITLE
Support annotation-driven custom sidebar sections in Kubernetes v2

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2529]
Annotation:

`"details.ui.spinnaker.io/<section>/<key>": "Here are some html-friendly details"`

Will render a collapsible section named `<section>` with  __`<key>`__: `Here are some html-friendly details`

@gardleopard

**Comment by sbwsg** [comment]
It doesn't look like kubernetes allows a path two levels deep:

```
kubectl annotate pods hello-ds-jwtnh "details.ui.spinnaker.io/stuff/things"="<a href='localhost:9000'>Test Link</a>"

The Pod "hello-ds-jwtnh" is invalid: metadata.annotations: Invalid value:
"details.ui.spinnaker.io/stuff/things": a qualified name must consist of alphanumeric
characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g.
'MyName',  or 'my.name',  or '123-abc', regex used for validation is
'([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix
and '/' (e.g. 'example.com/MyName')
```

So we could make the `<section>` part of the subdomain prefix:
`"details.<section>.ui.spinnaker.io/<key>": "<a href='foobar'>Test Link</a>"`

Or make the `<key>` part of the annotation:
`"details.ui.spinnaker.io/<section>": "<key>/<a href='foobar'>Test Link</a>"`

Thoughts on either of these?

**Comment by sbwsg** [comment]
As part of this issue, extensively document the format that the annotations and eventual rendered HTML take.

**Comment by sbwsg** [comment]
We've created a short proposal to discuss the possibilities for this in the k8s sig google group here: https://groups.google.com/forum/#!topic/spinnaker-sig-kubernetes/O7SprtmWEco

**Comment by ethanfrogers** [comment]
I think this would actually be a really useful feature for V1 as well!

**Comment by lwander** [comment]
I think @gardleopard left a few comments asking to keep the format a little more terse, so we don't wind up having to rely on large JSON blobs in the annotation body.

**Comment by sbwsg** [comment]
I had one question in response to the feedback but that's been answered.  We can use camelCase in the annotation key to translate to spaces be included in section titles / content labels.  So `fooBar.details.spinnaker.io/myFooBar="baz quux"` will become:

```
Foo Bar
-------
My Foo Bar: Baz quux
```

I plan to start implementing in the next day or so.

**Comment by lwander** [comment]
We should be careful to correctly handle acronyms -- is underscore an
allowed character? That might be easier to replace w/o guessing

**Comment by sbwsg** [comment]
yup, underscore works fine instead

**Comment by sbwsg** [comment]
correction: underscore does not work.  dashes work fine though.

**Comment by sbwsg** [comment]
Documentation for this feature is in PR here: https://github.com/spinnaker/spinnaker.github.io/pull/686
