### ISSUE TITLE
Kubernetes v2: support binding docker image to init containers

### ISSUE THREAD

**Issue by danilina-wsib** [spinnaker/spinnaker#2535]
I have a UI pod with main nginx container and an init container that copies UI files for nginx.
I would like to bind docker image tag to a init container image in yaml file.

Right now when I try to do this, I get this error:

Exception ( Monitor Deploy )
The following artifacts could not be bound: '[Artifact(type=docker/image, name=eclaims/frontend, version=master-32, location=null, reference=eclaims/frontend:master-32, metadata=null, artifactAccount=null, provenance=null, uuid=null)]' . Failing the stage as this is likely a configuration error.

My k8s manifest looks like this:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
          readOnly: true
      initContainers:
      - name: copy-files
        image: eclaims/frontend
        volumeMounts:
        - name: www
          mountPath: /site
      volumes:
      - name: www
        emptyDir:

**Comment by lwander** [comment]
Can confirm this isn't supported -- will be a quick addition.

**Comment by letsbringachange** [comment]
Some more details.
I am able to bind the "default" docker image tag within the YAML, however it is not working for the tag from the docker trigger. Here are the steps:

Prereq- My YAML has image: docker_repo/org/image:tag. Example: grr.io/myorg/custom-ms-app:7

1) Create docker trigger to trigger the pipeline.
2) Add expected parameters of type DockerRegistry and provide a default type DockerRegistry value with a tag say 1.
3) Click on "Start manual execution." and say you select the tag 15 from the tag list populated.

Now the deployed YAML has image: grr.io/myorg/custom-ms-app:1

@lwander  : Do you know by when the fix will be available ?

**Comment by letsbringachange** [comment]
This probably works for me. Here is my pipeline setup:

YAML has: image: grr.io/myorg/image

1) DockerRegistry trigger. 
2) DeployManifest.

Spinnaker V2 was able to replace as mentioned in the link: https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-manifest/
