### ISSUE TITLE
Create Load Balancer button not responding in UI

### ISSUE THREAD

**Issue by MoShitrit** [spinnaker/spinnaker#2536]
*Title*

Create Load Balancer button not responding in UI

*Cloud Provider*

Kubernetes

*Environment*

I am running spinnaker in an on-prem k8s cluster. The deployment was done manually since halyard can't properly run behind our proxy server because it can't properly trust our self-signed cert.

*Feature Area*
UI

*Description*

When following the [K8s Source to Prod](https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/) tutorial, Step 2 is guiding to create a new load balancer for the demo application. However, on my deployment, when hitting that button, nothing happens in the forefront. 
When opening the browser console, I get this error when hitting the button:
```﻿
TypeErrorcolumnNumber: 28fileName: "http://my.server.domain:8082/app.js"lineNumber: 55929message: "_this.cloudProviderRegistry.getProvider(...) is null"stack: "selectVersion/<@http://my.server.domain:8082/app.js:55929:28\nu@http://my.server.domain:8082/vendor.bundle.js:55:67746\nl/<@http://my.server.domain:8082/vendor.bundle.js:55:68168\n$digest@http://my.server.domain:8082/vendor.bundle.js:55:73783\n$evalAsync/<@http://my.server.domain:8082/vendor.bundle.js:55:75407\ni@http://my.server.domain:8082/vendor.bundle.js:55:21726\nhe/l.defer/n<@http://my.server.domain:8082/vendor.bundle.js:55:23190\n"__proto__: Object { stack: "", … } Possibly unhandled rejection: {} vendor.bundle.js:55:62024
```
Based on a quick advisory from @lwander , I have reviewed the `settings.js` file in `/opt/deck/html` and added the `versionedProviders: true,` line which was not there, however that didn't solve the issue. Here's the full settings.js file, taken from the browser console debugger (to make sure the correct file is loaded). I masked some vars like `account` and `namespace` in kubernetes provider for security reasons:
```
'use strict';

var feedbackUrl = 'http://localhost';
var gateHost = '/gate';
var bakeryDetailUrl = gateHost + '/bakery/logs/global/{{ context.status.id }}';

window.spinnakerSettings = {
  defaultProviders: ['kubernetes'],
  feedbackUrl: feedbackUrl,
  gateUrl: gateHost,
  bakeryDetailUrl: bakeryDetailUrl,
  pollSchedule: 30000,
  defaultTimeZone: 'America/Los_Angeles', // see http://momentjs.com/timezone/docs/#/data-utilities/
  providers: {
    kubernetes: {
      defaults: {
        account: '<account>',
        namespace: '<namespace>'
      },
    }
  },
  notifications: {
    email: {
      enabled: false,
    },
    hipchat: {
      enabled: false,
      botName: 'Skynet T-800'
    },
    sms: {
      enabled: false,
    },
    slack: {
      enabled: false,
      botName: 'spinnakerbot'
    }
  },
  whatsNew: {
    gistId: '32526cd608db3d811b38',
    fileName: 'news.md',
  },
  feature: {
    authEnabled: false,
    versionedProviders: true,
    pipelines: true,
    jobs: true,
    notifications: true,
    fiatEnabled: true,
    fastProperty: false,
    vpcMigrator: false,
    clusterDiff: false,
    chaosMonkey: true,
    pipelineTemplates: true,
    notifications: true,
    artifacts: true,
    canary: true,
    roscoMode: false,
    netflixMode: false,
    infrastructureStages: true, // Should 'createLoadBalancer' be a pipeline stage? (no).
  },
};
```

*Steps to Reproduce*
I have deployed these images on my environment:
gcr.io/spinnaker-marketplace/clouddriver:2.0.0-20180221152902
gcr.io/spinnaker-marketplace/deck:2.1.0-20180221143146
gcr.io/spinnaker-marketplace/echo:0.8.0-20180221133510
gcr.io/spinnaker-marketplace/front50:0.9.0-20180221133510
gcr.io/spinnaker-marketplace/gate:0.10.0-20180221133510
gcr.io/spinnaker-marketplace/igor:0.9.0-20180221133510
gcr.io/spinnaker-marketplace/orca:0.10.0-20180221133510
gcr.io/spinnaker-marketplace/rosco:0.5.0-20180221133510

redis is deployed manually as well as minio as a persistent storage solution (minio is set up as a distributed solution with 4 replicas).

*Additional Details*

Deck logs don't show any useful information for this issue.

**Comment by lwander** [comment]
Given the very odd browser error & the "off the beaten path installation" I get the feeling this is a deck configuration issue.

Can you describe the steps you took to deploy Spinnaker -- Deck in particular?

**Comment by MoShitrit** [comment]
@lwander My teammate just informed me that he might have found a misconfiguration in gate which could affect what's described here. We're going over it now and we'll share our findings asap. If we managed to solve- we'll share the solution here, if not- I'll share the config here for further review. 
Thanks!

**Comment by MoShitrit** [comment]
Indeed this was an internal configuration issue. After recreating the configmap it's working fine. Closing issue.

**Comment by flah00** [comment]
@MoShitrit I'm running into the same exact error at the same point of the same tutorial. But, I'm using helm to install my infrastructure. Any chance you want to share what you needed to change?
