### ISSUE TITLE
Please upgrade Rosco's Packer version to >= 1.1.2

### ISSUE THREAD

**Issue by CB-GuangyaoXie** [spinnaker/spinnaker#2545]
**Cloud Provider**
AWS

**Feature Area**  
Bake, Packer

**Description**
There's an issue with current Packer version(v1.1.0) that Rosco uses. The issue causes aws-ebs bake failing pretty often. 
Packer community fixed the issue in v1.1.2. Please upgrade Packer in new Rosco builds.
The issue is mentioned here:
Intermittent runtime error: invalid memory address or nil pointer dereference on Packer 1.1.0/1.1.1 
https://github.com/hashicorp/packer/issues/5535

**Additional Details**
Exception logs:
https://gist.github.com/CB-GuangyaoXie/19b91fb42d240fe5007ff192e2a6ed72

**Comment by ezimanyi** [comment]
Addressed by the commit referenced above

**Comment by CB-GuangyaoXie** [comment]
Thank you!
