### ISSUE TITLE
Kubernetes V1 Run Job: Run Init Container

### ISSUE THREAD

**Issue by hodgesmr** [spinnaker/spinnaker#2552]
We're leveraging the V1 RunJob stage as part of our deploy pipeline, where we spin up a container to do some pre-deploy work. The UI allows us to specify a container with pod annotations and labels. We'd like to also specify a kubernetes init container for this stage for pre-job initialization.

Is there any mechanism to facilitate this today?

**Comment by ethanfrogers** [comment]
@hodgesmr there's isn't currently but it could easily be added. 

out of curiosity: what's the use case? is it something you could do with another Run Job stage beforehand?

**Comment by hodgesmr** [comment]
We have a process where we pull secrete from HashiCorp Vault in init containers, which then get mounted into the target container. This way our target container can have access to secrets without touching Vault directly.

**Comment by hodgesmr** [comment]
@ethanfrogers It seems like much of the feature-dev for [this kind of functionality](https://github.com/spinnaker/spinnaker/issues/2587#issuecomment-376628302) is happening in #2587. So I'd say that replaces the need in V1.

**Comment by ethanfrogers** [comment]
👍 i'll go ahead and close this issue out then!
