### ISSUE TITLE
Weird deployment of apps with Spinnaker 1.6.0

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#2560]
*Cloud Provider*

GKE

*Environment*

Spinnaker 1.6.0 running on GKE deployed with halyard 0.42.0

*Description*

I noticed a weird behavior of Spinnaker 1.6.0 running on GKE. When Spinnaker is deployed via halyard 0.42.0, the new versions of pods start to replace the old ones (for example spin-orca-v001-ckctx to replace spin-orca-v000-vb7cs) as shown below:

```
spin-orca-v000-vb7cs                                         0/2       Terminating   0          1h
spin-orca-v001-ckctx                                         2/2       Running       0          3m
```

But I noticed that after some time the old version of Orca is restarted for some reason:

```
spin-orca-v000-xdd2p                                         1/2       Running   0          20s
spin-orca-v001-ckctx                                         2/2       Running   0          4m
```

As a result the deployment takes too much time and is timed out in the end.

I noticed the same behavior when I tried to deploy an application using Spinnaker 1.6.0 using a simple pipeline with “highlander” strategy. So this looks like an issue in Clouddriver/Orca rather than in Halyard.

I didn’t observe this issue for Spinnaker 1.5.4.

**Comment by iniinikoski** [comment]
I noticed the same before 1.6.0 - this started IMO happening when I increased the RS sizes to 2; before that - no issues...

I've noticed this only with Halyard-Spinnaker deployments - for now at least...

**Comment by nfirvine** [comment]
For me at least, the orca that halyard uses to redeploy your real Spinnaker deployment is usually called `spin-orca-bootstrap-v000`. These bootstrap replicasets would be deployed without orca (sort of obvious). I've never seen a `spin-orca-bootstrap-v001` created.

**Comment by wheleph** [comment]
Seeing the same issue with Spinnaker 1.6.1 and Halyard 0.49.0.

@lwander maybe the restart of the old pod is intentional to apply the change in the load balancer label (like `load-balancer-spin-gate=false`)?

**Comment by wheleph** [comment]
@lwander to investigate the issue further I triggered several redeployments Deck and I found an interesting fact. Here's a history of replica sets (obtained via `kubectl get rs -w`:

```
spin-deck-v004   1         0         0         0s
spin-deck-v004   1         0         0         0s
spin-deck-v004   1         1         0         0s
spin-deck-v004   1         1         1         5s
spin-deck-v003   1         1         1         6m
spin-deck-v003   1         1         1         6m
spin-deck-v003   0         1         1         6m
spin-deck-v003   0         1         1         6m
spin-deck-v003   0         0         0         6m
spin-deck-v003   1         0         0         6m
spin-deck-v003   1         0         0         6m
spin-deck-v003   1         1         0         6m
spin-deck-v003   1         1         1         6m
spin-deck-v003   0         1         1         9m
spin-deck-v003   0         1         1         9m
spin-deck-v003   0         0         0         9m
```

As you can see at the beginning it deploys a new version (v004) and scales down the old one (v003) but then all of a sudden after v003 is scaled to 0 it changes the desired number of pods again to 1!

```
spin-deck-v003   0         0         0         6m
spin-deck-v003   1         0         0         6m
```

I suppose this is not intended. Do you have any ideas?

**Comment by wheleph** [comment]
The issue is no longer present in Spinnaker 1.8.5 with clouddriver 3.3.3-20180802154248.
