### ISSUE TITLE
'hal deploy apply' always overwrites java keystore

### ISSUE THREAD

**Issue by ljohnston** [spinnaker/spinnaker#2573]
Doing a `hal deploy apply` always reinstalls java, including the ca-certificates-java package, overwriting any custom modifications to the keystore.

*Environment*

Ubuntu 14.04
Halyard 0.43.0-20180320121427
Spinnaker 1.6.0

localdebian environment

*Feature Area*

hal deploy

*Description*

We have to add a cert to the java keystore on the halyard/spinnaker box so that we can configure our private docker repository via hal and access it from spinnaker. Unfortunately, every `hal deploy apply` overwrites the java keystore with a stock version because halyard re-installs java, including the ca-certificates-java package, on every deploy.

It would be nice to have a switch or deployment option to tell halyard to only redeploy spinnaker but ignore all the system packages it installs.

*Steps to Reproduce*
```
hal deploy apply
keytool -import -alias ... -keystore ...
hal deploy apply
```
The keystore update done via keytool will have been undone at this point.

**Comment by ArievdB** [comment]
Same problem here, might there be any workaround available for this?

_Environment:_ 
Ubuntu 16.04
Halyard 1.2.0-20180509113540
Spinnaker 1.7.3

localdebian environment

Thanks,
