### ISSUE TITLE
Kubernetes V1 / V2 Provider Erroneous RunJob Stage Appearances

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#2574]
*Cloud Provider*

Kubernetes

*Environment*

Running Spinnaker under a LocalGit deployment

*Feature Area*

UI

*Description*

RunJob stage should be available in applications configured with v1 k8s accounts and not available in applications configured only with v2 k8s accounts.

*Steps to Reproduce*

Setup an application solely with a v2 k8s account.  Notice that the RunJob stage is erroneously available to add to a pipeline.

Setup an application solely with a v1 k8s account.  Notice that the RunJob stage is not available to add to a pipeline.

**Comment by benjaminws** [comment]
We're seeing this as well. In our case, we have a k8s cluster configured using both v1 and v2 providers. This is needed so we can use the RunJob Stage.

We're on a nightly, version `master-20180308012807`

**Comment by skim1420** [comment]
@benjaminws to be clear, this issue is saying that the Run Job stage shouldn't show up at all for those using only the V2 provider. It seems you're saying something different -

**Comment by benjaminws** [comment]
Sure thing! I’ll agree that what we seeing is different. What we have is V1 and V2 providers enabled for the same kubernets cluster. The goal is to use Run Job with the V1 provider in a pipeline stage, then deploy to the same cluster wth the V2 provider. When we attempt to use Run Job, we are not seeing the option for the v1 accounts in the account list. 

For example

```
$ hal config provider kubernetes account list
+ Accounts for kubernetes:
  - staging-test-v1
  - staging-fox-v1
  - staging-test-v2
  - staging-fox-v2
```

However we only see v2 accounts

![e120c204-0f04-4948-8f27-59fea212d5d5](https://user-images.githubusercontent.com/121679/37878281-6e90ef54-3034-11e8-8c89-9092e815586d.png)

More than willing to open a separate issue.

**Comment by sbwsg** [comment]
I'm considering this issue closed by https://github.com/spinnaker/deck/pull/5072 for the time being.  Please re-open this if the problem with v1 or v2 manifests again.
