### ISSUE TITLE
Kubernetes v2 - Webhooks sent from dockerhub and Roles

### ISSUE THREAD

**Issue by kevinawoo** [spinnaker/spinnaker#2588]
There's a few issues I found trying to run the new Webhooks from dockerhub:
- There doesn't seem to be a way to set the `Run As User` for a webhook.
- When spinnaker is configured with fiat and user permissions, Webhook triggers from dockerhub seem to go through gate ok, echo ok, but then it never makes it to orca.
- I'm not sure if this is related, but when I then tried sending the same payload directly through echo, and it does hit orca, however the user is `anonymous`. 

Are these all related, or should they be broken up into new issues?

**Comment by kevinawoo** [comment]
@lwander fyi

**Comment by lwander** [comment]
I'm thinking 

> There doesn't seem to be a way to set the Run As User for a webhook.

is the root cause of

> When spinnaker is configured with fiat and user permissions, Webhook triggers from dockerhub seem to go through gate ok, echo ok, but then it never makes it to orca.

^ Try manually setting the `Run As User` in the trigger description

Is this still with fiat enabled? 

> I'm not sure if this is related, but when I then tried sending the same payload directly through echo, and it does hit orca, however the user is anonymous.

**Comment by kevinawoo** [comment]
>Try manually setting the Run As User in the trigger description

I can't seem to set it for the docker webhook trigger
![](https://cl.ly/0v2N1R150p09/Image%202018-03-28%20at%2011.32.16.png)

> I'm not sure if this is related, but when I then tried sending the same payload directly through echo, and it does hit orca, however the user is anonymous.
> **Is this still with fiat enabled?**

Yeah, it is. I might be superseding fiat, and that's why it's not happy when I do that.

**Comment by lwander** [comment]
You have to set it using "Edit as JSON" in the pipeline options.

**Comment by kevinawoo** [comment]
I'm not actually sure how I got the previous result now, I can't recreate it, but now at least it's consistent.
I tried adding `"runAsUser": "spinnaker-dev",` to the dockerhub webhook trigger, but it didn't seem to work:
- I tried sending the webhook to gate: logs in gate, logs in echo, but it doesn't do anything to orca.
- I tried sending the webhook to echo: it goes to echo, but it doesn't do anything to orca.

**Comment by ethanfrogers** [comment]
This looks like it should be a pretty easy fix. All we need to do is add the `run-as-user-selector` directive to the webhook trigger UI. 

selector: https://github.com/spinnaker/deck/blob/40d11f8c5a48284bca56e639e46cf846311a5dd4/app/scripts/modules/core/src/pipeline/config/triggers/travis/travisTrigger.html#L57-L62

webhook trigger UI: https://github.com/spinnaker/deck/blob/40d11f8c5a48284bca56e639e46cf846311a5dd4/app/scripts/modules/core/src/pipeline/config/triggers/webhook/webhookTrigger.html
