### ISSUE TITLE
Add a way to modify "optional" field for env vars

### ISSUE THREAD

**Issue by bggpoort** [spinnaker/spinnaker#2589]
Please provide:

*Title*

Add a way to modify "optional" field for env vars

*Cloud Provider*

GCP

*Environment*

Spinnaker 1.6.0 and Kubernetes 1.8.7

*Feature Area*

Deck/Clouddriver

*Description*

A field "optional" was added for newly created deployments which defaults to true and there is no way to modify this in Spinnaker. This causes misconfiguration to be ignored during deployment. I would like to be able to modify this while configuring the deployment.

*Steps to Reproduce*

- Create new deployment via Spinnaker with some cm and secret env vars
- Describe the newly created deployment
- Notice the "optional: true" for configmap and secret related env vars

**Comment by bggpoort** [comment]
Apparently this option is added under the "Environment From" option. I'd rather not have to modify configuration of my deployments.

**Comment by ethanfrogers** [comment]
@bggpoort what version of Kubernetes are you using?

**Comment by bggpoort** [comment]
@ethanfrogers 1.8.5 and 1.8.7

**Comment by ethanfrogers** [comment]
@bggpoort ah, i think in understand what you're reporting. this defaults to `true` to align with the Kubernetes API, which I believe defaults to `optional: true` (at least it did when i implemented it). However, this should be exposed when configuring a deployment if you want to make it required.

**Comment by ethanfrogers** [comment]
for some reason the kubernetes api docs aren't working very well right now :/

**Comment by bggpoort** [comment]
@ethanfrogers Any luck with this?

**Comment by bggpoort** [comment]
@ethanfrogers It's about the optional field for the individual environment variables.

**Comment by ethanfrogers** [comment]
@bggpoort okay. fortunately it shouldn't be a hard addition if someone wants to jump in and add it.

**Comment by ethanfrogers** [comment]
@bggpoort Good news! Apparently I added support for this in Clouddriver back in November. I'll work on exposing it in Deck but, in the meantime, you can add the field in your pipeline JSON.
