### ISSUE TITLE
S3 Artifact Type

### ISSUE THREAD

**Issue by benjaminws** [spinnaker/spinnaker#2595]
Background: We need to be able to save artifacts (manifests) in a pipeline stage to either S3 or GCS, depending on where the deployment is targeted, then retrieve those artifacts in a subsequent pipeline stage. This almost works for us using Produces & Expected artifacts, however, there does not appear to be an option for S3 artifacts.

Before I get too much further into writing the code, I wanted to have a discussion to see if there are any known alternatives, or if this already exists and I missed it.

Thanks

**Comment by ethanfrogers** [comment]
@imosquera mentioned this to me the other day. i think they have some customers who are going to need it as well. it makes sense to support it so i'm sure a PR would be very much welcome.

**Comment by jtk54** [comment]
AFAIK there's no support for s3 artifacts yet, this will be welcome. Probably should confer with @lwander and @ezimanyi who are working in this space.

**Comment by benjaminws** [comment]
Great, sounds like it's worth the effort. I'll have a PR ready shortly.

**Comment by imosquera** [comment]
@benjaminws - this is awesome!  Let me know if you run into any issues. We actually prioritized it for next week but if you crank it out it would be great

**Comment by benjaminws** [comment]
Some docs to support this https://github.com/spinnaker/spinnaker.github.io/pull/651

**Comment by lwander** [comment]
Sweet! Let's close this
