### ISSUE TITLE
Error Running Packer Using aws-windows-2012-r2.json

### ISSUE THREAD

**Issue by brantburnett** [spinnaker/spinnaker#2598]
*Cloud Provider*

AWS

*Environment*

I am running Spinnaker 1.6.0 deployed to Kubernetes running within AWS.

*Feature Area*

Rosco Packer

*Description*

The behavior you expect to see, and the actual behavior.

*Steps to Reproduce*

Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.

*Additional Details*

All Windows Server 2012R2 bakes fail with:

Exception ( Create Bake )
Failed to parse template: Error parsing JSON: invalid character '\n' in string literal At line 55, column 1 (offset 1508): 54: "ena_support": "{{user `aws_ena_support`}}, 55: ^

Appears to be missing the trailing double quote here:
https://github.com/spinnaker/rosco/blob/master/rosco-web/config/packer/aws-windows-2012-r2.json#L54

This can be corrected with a custom Packer script, but we're currently unable to deploy custom Packer scripts using Halyard due to this bug not being fixed as of Kubernetes 1.8.7: https://github.com/kubernetes/kubernetes/issues/57421

**Comment by ezimanyi** [comment]
Fixed by https://github.com/brantburnett/rosco/commit/aa189d5ab7b7acc4c08b9e102814f0e6224eeb1c
