### ISSUE TITLE
Unable to enable Jenkins master csrf

### ISSUE THREAD

**Issue by amitmindstix** [spinnaker/spinnaker#2602]
Using Spinnaker 1.6.0, Halyard 0.43
When I add Jenkins using hal config ci command options - I cannot use --csrf flag with either of add or edit commands. Both result in error - "More than one master supplied"

**Comment by sweetib** [comment]
+1. I am also facing this issue.

**Comment by amitmindstix** [comment]
For now I have found a work around - edit the .hal/config file directly and add this option. Run sudo hal deploy apply once you save the changes to above file.

**Comment by marfenij** [comment]
+1 have same problem, to fix I delete and recreate jenkins master with ----csrf true

**Comment by lwander** [comment]
@jtk54 is this related to your csrf fix?

**Comment by jtk54** [comment]
Certainly related. Looks like the Jenkins CSRF Halyard support is included in 0.45.x:

![image](https://user-images.githubusercontent.com/5456773/38998088-d8e899ce-43bc-11e8-98ee-62d3f3ddcf9a.png)

Please update and confirm.

**Comment by wuzhihui1123** [comment]
i have the same issue.
spinnaker version : 1.7.2
hal version: 1.1.0

**Comment by jtk54** [comment]
The `--csrf` flag is intended to be used as a 'switch':

`hal config ci jenkins master add <name> ... --csrf ...`.

Note that the invocation is not `--csrf true`. Let me know if that solves the issue.

**Comment by amitmindstix** [comment]
Thanks @jtk54 for this information! I wasted a lot of time due to misleading documentation.
It should be updated here - https://www.spinnaker.io/setup/ci/jenkins/
Moreover, it is not so intuitive even with this working. How would someone disable it once set - I tried edit command without --csrf, expecting the flag would be set to false or removed - and it was still set to true. The only option then is to directly edit the .hal/config or remove and add master - both ugly.
There should ideally be a way to only change the csrf to true or false.
Wouldn't it be cleaner to have both - the flag and its value taken as input instead of just the flag?

**Comment by jtk54** [comment]
This is a good point. https://github.com/spinnaker/halyard/pull/943 makes it so the flag takes an argument.

**Comment by jtk54** [comment]
The referenced `csrf` change will be picked up in the next Halyard release (next week or so). In the mean time, I cut a manual github release (https://github.com/spinnaker/halyard/releases/tag/v0.34.0) if you want to test this out. Closing for now, feel free to reopen if there are issues.

**Comment by laksgreen** [comment]
Yes, if you added manually the csrf: true in your config file ~/.hal/config getting an error, so try to enable using the command,

```
hal config ci jenkins master add my-jenkins-master  --csrf true --address http://<IP ADDRESS>:8080 --username jenkins --password
```
If you have added already, can edit the config
```
hal config ci jenkins master edit my-jenkins-master --csrf true
```
