### ISSUE TITLE
Spinnaker docker images should not run as "root"

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2606]
This should be a pretty self-contained change. The services (as far as I know) don't do any privilege escalation, and only read from mounted files. Let's try and get this in before 1.7 is released.

**Comment by lwander** [comment]
Our nightlies are running fine as non-root.

**Comment by wheleph** [comment]
@lwander you only updated `Dockerfile.slim` files in each service but didn't update `Dockerfile`. Is there a reason for skipping those?

**Comment by lwander** [comment]
We don't build the `Dockerfile` in each service, or maintain anything that consumes those built images, so I don't feel confident changing them. If anyone uses those & feels confident in updating them I'm happy to merge their changes.
