### ISSUE TITLE
2nd level and deeper expression references not working in Spinnaker 1.6.0+

### ISSUE THREAD

**Issue by ryan-mf** [spinnaker/spinnaker#2615]
*Title*

2nd level and deeper expression references not working in Spinnaker 1.6.0+

*Cloud Provider*

GCP, Kubernetes

*Environment*

We are 100% GKE + GCR

*Feature Area*

Expressions

*Description*

Up until Spinnaker 1.5.4, we've been using (without issue) Expression references in many pipelines. Primarily, we reference the image tag in a couple places:
1. The notification to slack of what image is being deployed in that pipeline.
2. Setting a Pipeline Parameter in a pipeline stage to trigger another application's pipeline, to use the same image tag as the application we're in (different applications using the same image source).

This has been working without issue for months, just have to get the number of levels right, to trigger stage from dev, and prod from stage. We upgraded to 1.6.0 (latest available) and this stopped working. We thought maybe the source JSON had changed schema, or maybe there were fewer depths in the path, but we verified the source hadn't changed.

Example:
1. In application A, we have pipeline "deploy to stage". This pipeline is triggered by pipeline "deploy to dev". "Deploy to dev"s top-level Expression references work fine. We're using the Expression like this: ```${trigger[ 'tag' ]```
2. In "Deploy to stage" pipeline, we have a notification that references the same Expression, but one level further down, like this: ```${trigger[ 'parentExecution' ][ 'trigger' ][ 'tag' ]}```
3. We also use this same Expression reference in the "Deploy to Stage" pipeline's stage that launches application B's "Deploy to Stage" pipeline. It's used to set the value of a pipeline parameter to the value of the image tag that application B will use.

Once we upgraded from 1.5.4 to 1.6.0, any Expression used in the "Deploy to Dev" pipeline that's using the top-level ```${trigger[ 'tag' ]``` continues to work just fine, including both for notifications and pipeline parameters. However, any second- or further-level pipeline that uses that Expression reference via ```${trigger[ 'parentExecution' ][ 'trigger' ][ 'tag' ]}```, or deeper (IE Prod, 3rd level, uses ```${trigger[ 'parentExecution' ][ 'trigger' ][ 'parentExecution' ][ 'trigger' ][ 'tag' ]}```) no longer works, even though looking at the pipeline source shows this JSON path is valid and contains the data we're trying to do a lookup on with the Expression.

*Steps to Reproduce*

Deploy Spinnaker 1.5.4 or older and setup a series of pipelines design to trigger down a path, like deploy to dev, stage, prod. Use pipeline expressions, even in just notifications, further and further down the path to get the data you want to lookup to place in the notification, as you go further down the depth of pipelines. Notice it working just fine. Upgrade to 1.6.0. It stops working. Your notifications will container the literal string of the reference, ie ${trigger[ 'parentExecution' ][ 'trigger' ][ 'tag' ]}, instead of the value that was supposed to lookup.

*Additional Details*

Happy to provide hal configs or whatever if requested.

**Comment by ryan-mf** [comment]
Note that we reverted to 1.5.4, and the Expression references returned to normal function.

**Comment by sbwsg** [comment]
Hi there, thanks for the issue report!

It would be really helpful here to have a portion of the log from Orca when you run the pipeline.  Specifically, the log output will include a line such as this: `running pipeline uuid-abc-xyz:` followed by JSON for your triggered pipeline.  As part of that JSON object there should be a field, "expressionEvaluationSummary" that includes a description of the error that occurred while the expression was being parsed.

If it's possible for you to capture that and include it here it would be really useful.  Thankyou!

**Comment by robfletcher** [comment]
@Marcux83 Can you show me the JSON of the trigger in the actual running pipeline? I might be able to figure out what's going on then.

**Comment by Marcux83** [comment]
json is in my post above. will revert 1.5 for now..

**Comment by jasonkshar** [comment]
That return type error looks like something we ran into in our deployed Spinnaker instance. 1.6 introduced a number of classes for the various triggers. We had to make sure we had this commit to include the update to the restricted return classes: https://github.com/tomaslin/orca/commit/d7fd7b75069f99bd158f8f8d8d573299a22482da

**Comment by ryan-mf** [comment]
I just tested an upgrade to Spinnaker 1.7.6 and this looks to be resolved.

**Comment by lwander** [comment]
Closing as this seems to be resolved in releases after 1.7
