### ISSUE TITLE
Default security password is present in logs

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#2616]
Some Spinnaker services (Gate for instance) print the default Spring Security password:

```
/tmp → kubectl logs spin-gate-v022-6xqxl -c spin-gate | grep password
Using default security password: 4a98a7c1-b06a-4805-8e6e-4e43bfc49072
```

The following services have this issue:
- Orca
- Clouddriver
- Front50
- Gate

Apparently the password is not actually used so it should be completely disabled (not just muted in the logs).

From the Slack channel:

> @ethanfrogers can you help me understand the impact BTW? What can a blackhat hacker do using the password?
> @Volodymyr Sobotovych it depends on if you are already using some level of authn. if you don't have it enabled (x509, Oauth, etc), then it's irrelevant. the API will be open regardless. If you _are_ using some level of authn then anyone with the password will be able to access the API. however, if you're using authn + authz (fiat) it then becomes irrelevant again because the default spring user won't have have any roles associated with it.

**Comment by jervi** [comment]
Orca, Clouddriver and Front50 should not be publicly accessible. If you turn off the logging of the password, a lot of the Spring Actuator endpoints won't be accessible anymore. If you turn off security, that's worse than printing the password in a log. Isn't the real solution here (if you're concerned with this) to just provide an explicit username/password or alternative auth mechanism for Spring Actuator security (by setting `spring.security.user.name` and `spring.security.user.password` in your config)?

**Comment by jervi** [comment]
If you just want to not log this password, just change the log level for `org.springframework.boot.autoconfigure.security` to `WARN` or higher.

**Comment by wheleph** [comment]
@jervi thanks for the elaborate answer. For now I don't need to use those endpoints so I just switched off logging as you suggested
