### ISSUE TITLE
Fiat is polling Google for service accounts

### ISSUE THREAD

**Issue by BenCoffman** [spinnaker/spinnaker#2628]
*Title*

Fiat is polling Google for service accounts

*Cloud Provider*

AWS

*Environment*

AWS deploying AWS AMIs

*Feature Area*

Fiat 

*Description*

We're noticing that Fiat is polling service accounts created in spinnaker, but they're not found in GoogleDirectory. This isn't a major issue, however this does contribute to hitting rate limits quicker.

*Steps to Reproduce*

- Setup a service account in spinnaker
- Make sure fiat is polling for user groups

*Additional Details*

> 2018-04-02 19:31:47.355 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey
> 2018-04-02 19:31:47.360 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-svc-account: Invalid Input: memberKey
> 2018-04-02 19:31:47.370 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey
> 2018-04-02 19:31:47.370 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey
> 2018-04-02 19:31:47.371 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey
> 2018-04-02 19:31:58.702 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey
> 2018-04-02 19:31:58.703 WARN 1 — [ecutionAction-4] s.f.r.g.GoogleDirectoryUserRolesProvider : [] Failed to fetch groups for user-service-account: Invalid Input: memberKey

**Comment by BenCoffman** [comment]
This turned out to be an issue due to some outages on Googles end.  This is no longer an issue.

**Comment by axot** [comment]
I saw this error today.
