### ISSUE TITLE
Replace user-facing term 'Security Group' with more generic 'Firewall'

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#2629]

**Comment by duftler** [comment]
We'll add a feature-flag to control the ui logic and add aliased entrypoints to the api gateway while deprecating the original securityGroup-oriented api's.

**Comment by duftler** [comment]
The api docs on spinnaker.io will get automatically updated to reflect the new swagger docs, but we'll need to manually update any other screenshots or references throughout the site.

**Comment by duftler** [comment]
https://github.com/spinnaker/gate/pull/525

**Comment by duftler** [comment]
Tracking needed docs changes here:
Update this description: https://www.spinnaker.io/concepts/#security-group
Update language here (no screen-grabs): https://www.spinnaker.io/guides/tutorials/codelabs/bake-and-deploy-pipeline/#bake-and-deploy-pipeline
Update 2 references here: https://www.spinnaker.io/guides/user/pipeline-expressions/
Update this description: https://www.spinnaker.io/reference/providers/gce/#security-group
Update language here (+ 3 screen-grabs): https://www.spinnaker.io/guides/tutorials/codelabs/hello-deployment/#create-security-group
Update this description: https://www.spinnaker.io/reference/providers/azure/#security-group
Update language here (+ 1 screen-grab): https://www.spinnaker.io/guides/tutorials/codelabs/azure-vmss-source-to-prod/#ii-create-a-security-group
Update language here (+ 1 screen-grab): https://www.spinnaker.io/guides/tutorials/codelabs/openstack-source-to-prod/#create-a-security-group
Update mappings here: https://www.spinnaker.io/reference/providers/kubernetes-v2/#terminology-mapping

**Comment by demobox** [comment]
> The api docs on spinnaker.io will get automatically updated to reflect the new swagger docs, but we'll need to manually update any other screenshots or references throughout the site.

/cc @dorbin

**Comment by duftler** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/656

**Comment by duftler** [comment]
UI work: https://github.com/spinnaker/deck/pull/5284

**Comment by duftler** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/851
