### ISSUE TITLE
Kubernetes: Unable to Disable/Destroy cluster

### ISSUE THREAD

**Issue by amitmindstix** [spinnaker/spinnaker#2634]
With Spinnaker 1.6.0 and Kubenetes v1.7.7
When I try to disable or destroy the cluster - I see another server group created automatically.
FYI - I am using Azure template - https://github.com/Azure/azure-quickstart-templates/tree/master/301-jenkins-acr-spinnaker-k8s to setup the spinnaker+k8s

**Comment by danielpeach** [comment]
Could you please provide a bit more detail about what you're doing and what you're seeing? Hard to imagine Spinnaker really creating a new server group when deleting/disabling a server group. 

It seems more likely that a). the operations are failing, or b). you're deleting a resource that Kubernetes is automatically recreating.

**Comment by ethanfrogers** [comment]
+1 @danielpeach answer. this _can_ happen if you're destroying/disabling a `Deployment`. if that is the case, it's a known issue.

https://github.com/spinnaker/spinnaker/issues/2162

**Comment by lwander** [comment]
Closing as this is a dupe
