### ISSUE TITLE
Deployment of new application throws exception with Spinnaker 1.6.1

### ISSUE THREAD

**Issue by bggpoort** [spinnaker/spinnaker#2639]
Please provide:

*Title*

Deployment of new application fails with Spinnaker 1.6.1

*Cloud Provider*

GCP

*Environment*

Spinnaker 1.6.1 with Kubernetes 1.8.7

*Feature Area*

Orca/Kato

*Description*

I've upgraded Spinnaker to version 1.6.1 today. After that I've created a new application with a new pipeline to deploy the application. When deploying the application the pipeline almost immediately reports "succeeded", but throws the following exception: "Unable to map context to class com.netflix.spinnaker.orca.kato.pipeline.support.StageData"

This behavior does not occur with applications that were configured before the upgrade.

*Steps to Reproduce*

- Upgrade Spinnaker to 1.6.1
- Create pipeline and add step "Deploy"
- Configure deployment
- Deploy application

*Additional Details*

[exception.pdf](https://github.com/spinnaker/spinnaker/files/1890367/exception.pdf)

**Comment by bggpoort** [comment]
Downgrade to Spinnaker 1.6.0 did not resolve this behaviour

**Comment by sbwsg** [comment]
Hi bggpoort thanks for the issue report!  Could you add the pipeline JSON to this issue?  You can access this through deck by configuring the pipeline and clicking Pipeline Actions -> Edit as JSON.

I've just tried reproducing this by adding a completely new application and deploying from it to a k8s 1.8.7 cluster.  I did not see the same error.  I'd like to try your pipeline JSON from my spinnaker deployment to see if I can reproduce the issue on my side.

**Comment by bggpoort** [comment]
@sbwsg I've been playing around a bit more and eventually decided to delete the pipeline and recreate it. Now it appears to be working as desired. The difference is that I was testing with the Deploy (Manifest) stage while creating the first pipeline. Eventually I switched to the normal Deploy stage and configured it. Second time I selected Deploy stage directly.

**Comment by KalenWessel** [comment]
I just wanted to say this bug still exists on Spinnaker 1.10.12

- Create new Pipeline
- Create stage Deploy (Manifest)
- Save the pipeline
- Edit the pipeline and change the stage to regular V1 Deploy
- Add a server group with a container
- Save the pipeline
- Run the pipeline
It will fail with "`Unable to map context to class com.netflix.spinnaker.orca.kato.pipeline.support.StageData`"

**Comment by rampatnaik** [comment]
I am also having same issue with com.netflix.spinnaker.orca.kato.pipeline

c.n.s.orca.clouddriver.OortService : success
c.n.s.orca.clouddriver.katoService : fail
