### ISSUE TITLE
Clouddriver doesn't start

### ISSUE THREAD

**Issue by Hayyk** [spinnaker/spinnaker#2647]
After Spinnaker deployment on EC2, clouddriver doesn't start. tried the same on local machine and the result is the same. Trying to run 1.6.1 on ubuntu 16.04.
I am using s3 as storage aws as cloudprovider.
After deployment spinnaker UI is accesable, when creating new application the windows hangs and error message appears in browser's console regarding localhost:8084/ credentials and 7002 port.
tried to send curl request to localhost:7002 from the server, but connection refused. 7002 port isn't being listened but all other services ports are. clouddriver start and then enters failed state (for about after 30 seconds).
For deployment I've followed [this guide](https://www.spinnaker.io/setup/install/) on official website.
Also I can't find logs of services in /var/log/spinnaker/*any service*/ path, there are logs only in /var/log/spinnaker/halyard/ path.
All policies/roles/users have been made in aws properly as described in official setup guide. double checked. Still facing issue.
Maybe I am missing anything?
Here is the error from browser console when trying to create new application
`GET http://localhost:8084/credentials?expand=true 500 ()
angular.js:14525 Possibly unhandled rejection: {"data":{"error":"Internal Server Error","exception":"com.google.common.util.concurrent.UncheckedExecutionException","message":"retrofit.RetrofitError: Failed to connect to localhost/127.0.0.1:7002","status":500,"timestamp":1523484058259},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://localhost:8084/credentials","cache":true,"params":{"expand":true},"timeout":65000,"headers":{"X-RateLimit-App":"deck","Accept":"application/json, text/plain, */*"},"withCredentials":true},"statusText":""} undefined`

**Comment by lwander** [comment]
Thanks @Hayyk -- what version of halyard are you running? I'm thinking this issue might be fixed in the latest stable halyard.

**Comment by Hayyk** [comment]
Thanks for your response @lwander . I am running 0.48
My problem has been solved 2 days before. don't know exactly what was the reason - latest stable halyard or changes I've made.
When I was configuring AWS and S3 I used different user accounts(acces key and secret key appropriately). As described in setup doc in your website, at first I've configured S3 and credentials of my S3 account were filled in /home/spinnaker/.aws/credentials file (I suppose this is default credentials). After I've configured AWS as cloud provider, gave credentials, but in the /home/spinnaker/.aws/credentials file there were still S3 account's credentials. After I've manually changed key id/secret-key with AWS account's ones in the mentioned file, Now clouddriver again didn't work as it couldn't connect to S3 now.
To avoid this I've created one user with S3 admin role and other roles in AWS and used credentials of this user for both S3 and AWS configs in spinnaker

**Comment by authayam** [comment]
Hi @Hayyk 

can you guide me.

How spinnaker can get deployed without configuring the cloud provider and persistence storage.

**Comment by shaileshrathod1811** [comment]
@lwander , I have done a standalone installation of Halyard and Spinnaker on AWS EC2 using the official documentation on Ubuntu 18.04. I have used S3 as the persistent storage. I am able to open the Deck GUI and create projects and application. However every other actions fails in the background. Can you guide me to help get spinnaker fully functional ?

Below are partial snips of error seen in Gate logs using command : sudo journalctl -u gate 

Feb 11 13:12:47 ip-172-31-37-211 gate[24486]: 2020-02-11 13:12:47.930  INFO 24486 --- [applications-10] c.n.s.g.s.internal.Front50Service        : <--- HTTP 200 http://localhost:8080/v2/applications?restricted=false (17ms)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]: 2020-02-11 13:12:52.932  INFO 24486 --- [-applications-9] c.n.s.g.s.internal.Front50Service        : ---> HTTP GET http://localhost:8080/v2/applications?restricted=false
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]: 2020-02-11 13:12:52.932  INFO 24486 --- [applications-10] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://localhost:7002/applications?restricted=false&expand=true
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]: 2020-02-11 13:12:52.932  INFO 24486 --- [applications-10] c.n.s.g.s.internal.ClouddriverService    : ---- ERROR http://localhost:7002/applications?restricted=false&expand=true
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]: 2020-02-11 13:12:52.932  INFO 24486 --- [applications-10] c.n.s.g.s.internal.ClouddriverService    : java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7002
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
Feb 11 13:12:52 ip-172-31-37-211 gate[24486]:         at com.squareup.okhttp.Call.get

Also sharing the error seen in browsers developer console below ;

angular.js:14961 Possibly unhandled rejection: {"data":{"timestamp":1581426187983,"status":500,"error":"Internal Server Error","message":"Internal Server Error"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://localhost:8084/securityGroups","timeout":65000,"headers":{"X-RateLimit-App":"deck","Accept":"application/json, text/plain, */*"},"withCredentials":true},"statusText":"","xhrStatus":"complete"} undefined
