### ISSUE TITLE
Multiregion bakes not working after upgrading to 1.6.0 (also recreatable in 1.7.4)

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [spinnaker/spinnaker#2663]
*Cloud Provider*

AWS

*Environment*

We am running spinnaker in AWS. We have a "spinnaker deploy spinnaker" model. We don't use halyard but we keep to sanctioned releases. We also use the open source version of spinnaker (not armory). We deploy RPM packages to custom redhat based EC2 instances (no containers)

*Feature Area*

multiregion baking (parallel bake in multiple regions, not bake and then copy to other regions)

*Description*

in older versions (1.3.0) we were following the region template method described at https://docs.armory.io/admin-guides/rosco/#region-templates to do multiregion bakes. but when we upgraded to 1.6.0 this began to fail because the ${region} variable no longer got populated properly. it came up blank. 

(testing 1.5.4 now..) 

*Steps to Reproduce*

to reproduce create a pipeline in 1.6.0 and set it up as follows...
![image](https://user-images.githubusercontent.com/1447492/38824469-292aa064-415e-11e8-8013-62834d58afbf.png)

*Additional Details*

I did some digging and noticed that in 1.6.0 the ${regions} variable gets populated in the bake stage. but this is a list of the regions we selected so not very useful for getting the appropriate variables. when I compare the source of the pipeline run i did in 1.3.0 and that i did in 1.6.0 they look basically the same. I noticed that ${regions} is a variable in the high level bake stage while ${region} is a variable in the broken down parallelized version of it. It seems as though the current stage context (https://www.spinnaker.io/guides/user/pipeline-expressions/#the-current-stage) for the bake stage is pointed at the high level one rather than the parallel one now. Is this intentional? Are others able to reproduce this? is this configurable? Are there better methods of getting the appropriate region based 
 variables (VPC/subnet/packer SG) to the packer script?

**Comment by JazminGonzalez-Rivero** [comment]
Just verified this is not broken in 1.5.4

**Comment by JazminGonzalez-Rivero** [comment]
![image](https://user-images.githubusercontent.com/1447492/40197144-6e72053c-59c7-11e8-884b-f3c6ab3a6450.png)
this is the error returned FYI

**Comment by JazminGonzalez-Rivero** [comment]
Closing since this turned out to be specific to our env.

**Comment by uohzxela** [comment]
@JazminGonzalez-Rivero may I ask how did you fix this issue? I am having the same problem as well.
