### ISSUE TITLE
Halyard breaks expectations with PasswordFile for docker registry

### ISSUE THREAD

**Issue by optimuspaul** [spinnaker/spinnaker#2673]
*Cloud Provider*: Kubernetes

*Environment*: Kubernetes on AWS, spinnaker deployed with Halyard

*Description*

In an attempt to get ECR token refreshing working I set the passwordFile for a docker registry. When halyard runs it moved that file into a kubernetes secret and rewrote the config. Therefore when my sidecar was refreshing the password clouddriver wasn't seeing the change.

*Steps to Reproduce*

Setup a docker registry with a password-file. Run a deploy of halyard. Look at clouddriver config. If the passwordFile value the same? (I think it should be, but it is not)

**Comment by lwander** [comment]
The mounting of files in Halyard at different paths is a feature (for better or worse), mainly to make it easier to snapshot Spinnaker's state including all files it depends on. 

If you don't want halyard to rewrite your config, then put it in a [custom profile](https://www.spinnaker.io/reference/halyard/custom).
