### ISSUE TITLE
Chose when to use eureka discovery depending on application

### ISSUE THREAD

**Issue by tidowu** [spinnaker/spinnaker#2685]
![screen shot 2018-04-20 at 11 35 42 am](https://user-images.githubusercontent.com/33040540/39065432-0999ea50-448f-11e8-8c9c-5e24b28c752b.png)
*Title*

Chose when to use eureka discovery in cloud driver depending on application

*Cloud Provider*

AWS

*Feature Area*

Pipelines, Cloud driver, eureka discovery. 

*Description*

When you define an account in cloud driver based on the docs https://github.com/spinnaker/clouddriver/tree/master/clouddriver-eureka, and the application being deployed is not using eureka for discovery, pipeline run take a long time to deploy because it is checking eureka for the application. We have multiple applications in the same aws account. Some uses eureka and some does not. So there should be a way to decide if spinnaker should check eureka or not based on the application. 

It seem when an application is not in eureka and you have **discovery: "http://10.0.0.1:8080/eureka/v2"** set in cloud driver config, **Monitor Disable Cluster** task take well over 10mins to complete.

**Comment by tomaslin** [comment]
This can be solved by specifying a flag interestingHealthProviders in the pipeline JSON and specifying which health providers to check

**Comment by Ciphero** [comment]
On Spinnaker version 1.18.12 I've tried setting "interestingHealthProviders" to both "Amazon" and "aws" in the pipeline JSON, but doesn't make a difference.
The Clouddriver still does Eureka health discovery for non-Eureka apps until reaching timeout and short-circuiting in the "Disable Cluster" stage. 
Is it broken or is there another way to control this behaviour? Perhaps by reducing maxRetry from 99 to 5 or similar?
