### ISSUE TITLE
Permission denied doing `apk update` on slim containers

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#2687]
Found during 1.7.0 release experimentation.

```
$ kubectl exec -it spin-clouddriver-6b78fdf65c-jwfm2 --namespace spinnaker -- bash
bash-4.4$ 
bash-4.4$ 
bash-4.4$ apk update
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

It appears that running as the `spinnaker` user (https://github.com/spinnaker/clouddriver/blob/master/Dockerfile.slim#L23) doesn't allow us to add debugging tools like `curl`. This should be added to the container beforehand or revert back to just running as root.

cc @lwander @sbwsg

**Comment by lwander** [comment]
This is all intentional, people shouldn't be allowed to download tools at will against a production container. If you want to debug like that, attach a sidecar if you need. `wget` is also already installe.d
