### ISSUE TITLE
WaitForClusterDisableTask times out during red/black deployment for v1 kubernetes provider

### ISSUE THREAD

**Issue by imosquera** [spinnaker/spinnaker#2690]
*Cloud Provider*

Kubernetes on Spinnaker branch, 1.7, 1.6 and master

*Environment*

reproduced locally using master branches and just running `./gradlew bootRun` to start and configure services

*Feature Area*

WaitForClusterDisableTask stages for v1 kubernetes provider

*Description*

Deploy with red/black strategy for kubernetes v1 provider times out in the 1.7 branch of orca.  This however seems like more of a symptom then the root cause.  The change the exposed the behavior was the following: https://github.com/spinnaker/orca/commit/462bfaaa83c183812340daaedb0503dfa3f8673d#diff-12b24be8325f89fb73f267f8664a82a4R82

The behavior I'm also noticing is that during a red/black deploy the pods are being killed and re-spawned.  This might be a regression where orca (or clouddriver) should be resizing the replicaset/server group to 0 instances during the red/black deployment but it never reaches this state for an unkown reason.  The commit listed above requires for the server group to be scaled to 0 but it never reaches that state.  This behavior appears on 1.6 but pipelines succeed despite not resizing the old servergroups/resplicasets properly.

I can see pods being killed and respawn by simply doing a `kubectl get pods` and it shows pods with ages of only a few seconds and a new unique name.

*Steps to Reproduce*

Create a single stage pipeline with red/black deployment.
![configuration image](https://cl.ly/2P271s2j0Z3x/Image%202018-04-23%20at%209.21.10%20AM.png)

*Additional Details*
Below is the exception I receive when running pipeline:

```
"com.netflix.spinnaker.orca.exceptions.TimeoutException: WaitForClusterDisableTask of stage disableCluster timed out after 30 minutes 7 seconds. pausedDuration: 0 seconds, elapsedTime: 30 minutes 7 seconds,timeoutValue: 30 minutes at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForTaskTimeout(RunTaskHandler.kt:216) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForTimeout(RunTaskHandler.kt:193) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$checkForTimeout(RunTaskHandler.kt:51) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:75) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:51) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:173) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:51) 
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:47) 
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:31) 
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:57)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:31) 
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:66)
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:51) 
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:53) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:51) at ```

**Comment by imosquera** [comment]
Talking to @lwander - I dug into the `waitForRequiredInstancesDownTask.hasSucceeded` method above which always returns false.  I do not have enough context to make a decision as to what needs to change but the following is happening:

For each ` interestingHealthProviderNames`, in this case `Pod` and `Container` health it returns true.  However the `instance` health returns `OutOfService`.   The function above does not check instance health so it always returns that there are "Up" instances which is true for pod/containers but those containers are not behind the loadbalancer.

**Comment by lwander** [comment]
If you change the health provider to "Service", does it work?

**Comment by lwander** [comment]
Pretty critical breakage since it affects both load balanced and non-load balanced pods.

**Comment by sbwsg** [comment]
Once we've got the commit into master I'll cherry-pick it into release-1.7.x and kick off another build.

**Comment by imosquera** [comment]
I'm making an assumption the reason to check `desiredPercentage` is for a rolling red/black deployment which is not needed for a standard red/black deployment which only requires the instances to be disabled.

**Comment by ajordens** [comment]
The check of desiredPercentage is actually to assert that 100% of the
instances are actually also disabled.

@dreynaud can provide more details.

You’re right that historically desiredPercentage was used for RRB.

**Comment by dreynaud** [comment]
Here is some context for my change: https://github.com/spinnaker/orca/pull/2124#discussion_r179848247

The motivation is this: during a red/black we first disable old server groups and then optionally scale them down to 0 instances. `WaitForClusterDisableTask` used to wait for the cluster to be disabled (regardless of instance health status), but the scale down task was expecting instances to be down (it skips any server group with at least one up instance). So there is a mismatch between these 2 tasks, in most cases we would get disabled and down server groups out of `WaitForClusterDisableTask` (hence scale down would happen), but occasionally one or more instances would still appear up and scale down would not happen.
