### ISSUE TITLE
Deploy artifacts stored in private Github Enterprise

### ISSUE THREAD

**Issue by eboumendil** [spinnaker/spinnaker#2693]
*Cloud Provider* : Kubernetes V2

*Feature Area* : Artifact deployment from a private Github Enterprise

*Description*

I am trying to deploy artifacts using a private Github Enterprise setup. Looking at https://github.com/spinnaker/clouddriver/blob/master/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/github/GitHubArtifactAccount.java, it seems I cannot specify an alternative base URL to point to my private Github Enterprise endpoint.

*Steps to Reproduce*

Deploy an artifact from a private Github Enterprise.

**Comment by wjoel** [comment]
The URL to your private GitHub Enterprise endpoint is included in the webhook messages that trigger your pipelines, and/or specified in the artifacts themselves (eg. in the case of default artifacts).

You shouldn't need to specify it in any config.

**Comment by lwander** [comment]
That's right, the `reference` field should link to the content URL for your GHE domain. There is an example here: https://www.spinnaker.io/reference/artifacts/types/github-file/#fields
