### ISSUE TITLE
Halyard: Failed to install Spinnaker on K8S using Halyard in Docker

### ISSUE THREAD

**Issue by posox** [spinnaker/spinnaker#2703]
I'm trying to install Spinnaker using `halyard:1.0.0` docker image but it fails.

Environment:
Halyard: 1.0.0 in Docker
Provider: K8S V2

Steps to reproduce:
1. Deploy Spinnaker using command:
`hal deploy apply`

After some time deploy fails with error:
`error: error validating "STDIN": error validating data: mkdir
  /home/spinnaker/.kube: permission denied; if you choose to ignore these errors,
  turn validation off with --validate=false`

**Comment by lwander** [comment]
Was this closed by https://github.com/spinnaker/halyard/pull/924?

**Comment by posox** [comment]
Yes

**Comment by lwander** [comment]
Awesome, thanks for the fix @posox!
