### ISSUE TITLE
UI can't delete pipelines with / in their name 

### ISSUE THREAD

**Issue by octplane** [spinnaker/spinnaker#2715]
Pipelines with a `/` in their name cannot be deleted via the UI. The UI performs a requests and omits to encode the `/` correctly. It leads to a `404` when posting the action.

```
https://spinnaker.ddbuild.io:8084/pipelines/myapp/Deploy%20to%20AWS%20Kubernetes%20staging/test%20cluster
```

I believe this is an issue in deck.

**Comment by sbwsg** [comment]
hi @octplane thanks for the issue report!

How did you create the pipeline initially?  When I try creating one with "/" in the name I'm not able to:

![2018-04-30_17-50-39](https://user-images.githubusercontent.com/34253460/39452128-25e4dd92-4c9f-11e8-8607-f33db3773c79.png)

As a temporary workaround you should be able to rename the pipeline in Deck so as not to include the "/" character, and then delete the new name.

**Comment by octplane** [comment]
I think it was creating by some nasty script, so using Spinnaker API, although I'm not sure. I think the encoding issue should probably be addressed anyway...

I have managed to delete the offending using hand crafted `curl` :)

Thanks for your quick feedback!

**Comment by jdassonvil** [comment]
I encountered the same issue with a `[`. The rename trick worked.

**Comment by sbwsg** [comment]
Thanks!
