### ISSUE TITLE
Load Balancer Named Port does not appear in deployment cluster

### ISSUE THREAD

**Issue by chainlink** [spinnaker/spinnaker#2717]
*Cloud Provider*

GCP

*Environment*

I am running spinnaker using the [cloud launcher](https://console.cloud.google.com/launcher/details/click-to-deploy-images/spinnaker)

Spinnaker version 1.5.4 

cloud driver 1.0.4-20180110144440 (2018-01-10)

*Description*

I expect to see the named port configured in the load balancer appear in the deploy configuration

*Steps to Reproduce*

1. create SSL load balancer of type ssl. Select a pre existing cert, enter a port name, and default health check values
2. Add a deploy step to a deployment pipeline,
3. add new server group 
4. select the load balancer you just created

Expected outcome: port created previously appears under dropdown for port name mapping

Actual outcome: port name does not appear

*Additional Details*

<img width="911" alt="screen shot 2018-04-27 at 9 15 29 am" src="https://user-images.githubusercontent.com/1187682/39364319-95d1f960-49fb-11e8-99c6-8e347945a7ec.png">

**Comment by sweetib** [comment]
@chainlink you might want to try the latest version. I was also facing same issue and it was fixed in here https://github.com/spinnaker/spinnaker/issues/2490

**Comment by chainlink** [comment]
Yep! Tried the latest version and it's all good.
