### ISSUE TITLE
hal deploy apply fails

### ISSUE THREAD

**Issue by nitrogear** [spinnaker/spinnaker#2735]
### Issue Summary:
hal deploy apply fails

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker: 1.6.1
hal: 1.1.0
Kubernetes 1.8.1

### Feature Area: 
Kubernetes, installation

### Description:
Newly created Spinnaker fails to deploy to Kubernetes cluster

### Steps to Reproduce:
I installed hal on ubuntu host with kubectl and then run hal apply deploy command. Full output of command is below. If I open spinnaker namespace in K8s I see that all services (10) are up and running

### Additional Details:
Log output:
```
hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.provider.kubernetes.ofm-k8s-int:
- WARNING Field KubernetesAccount.kinds not supported for Spinnaker
  version 1.6.1: Configuring kind caching behavior is not supported yet.
? Use at least 1.7.0 (It may not have been released yet).

- WARNING Field KubernetesAccount.omitKinds not supported for
  Spinnaker version 1.6.1: Configuring kind caching behavior is not supported
  yet.
? Use at least 1.7.0 (It may not have been released yet).

Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
+ Deploy spin-clouddriver
  Success
+ Deploy spin-front50
  Success
+ Deploy spin-orca
  Success
+ Deploy spin-deck
  Success
+ Deploy spin-echo
  Success
+ Deploy spin-gate
  Success
+ Deploy spin-igor
  Success
+ Deploy spin-rosco
  Success
Problems in Global:
! ERROR Rosco is enabled, and no connection to rosco could be
  established: retrofit.RetrofitError: 404 Not Found

- Failed to deploy Spinnaker.
```

**Comment by nitrogear** [comment]
I used following sequence of commands:
```
hal version list
hal config version edit --version 1.6.1
hal config storage s3 edit --access-key-id XXX --secret-access-key --region us-east-1 --bucket xxx-spinnaker-xxx
hal config storage edit --type s3
hal config provider docker-registry enable
hal config provider docker-registry account add docker-registry --address https://docker-registry.xxx.xxx 
hal config provider kubernetes enable
hal config provider kubernetes account add k8s --docker-registries docker-registry
hal config deploy edit --type distributed --account-name k8s
hal config ci jenkins enable
hal config ci jenkins master add master --address https://jenkins.xxx.xxx --username <JENKINS_USER> --password
hal deploy apply
```

**Comment by lwander** [comment]
Does it fail each time? Perhaps rosco registered itself as healthy, and then briefly went down when halyard tried to connect.

**Comment by nitrogear** [comment]
Yes, it fails each time. I tried different version of Spinnaker 1.5.4, 1.6.1 and 1.7.2. What interesting is that if I open kubernetes cluster I see that all pods are up and running , including rosco. This error prevents me to do any configuration change:
```
hal deploy apply
...
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
- Deploy spin-clouddriver
  Failure
! Deploy spin-front50
  Interrupted
- Deploy spin-orca
  Failure
- Deploy spin-deck
  Failure
- Deploy spin-echo
  Failure
- Deploy spin-gate
  Failure
- Deploy spin-igor
  Failure
- Deploy spin-rosco
  Failure
Problems in Global:
! ERROR Unexpected exception: retrofit.RetrofitError: 404 Not
  Found

- Failed to deploy Spinnaker.
```

**Comment by ezimanyi** [comment]
@nitrogear : I wanted to quickly double-check the version of Kubernetes that you're running.  We've discovered an issue that would explain the error you're seeing, but it only affects users running Spinnaker on Kubernetes 1.10 or above.  You said above that you're running Kubernetes 1.8.1 but I wanted to double-check that.

If you are running Kubernetes < 1.10, do you have a stack trace from your halyard log that has more details on this `RetrofitError` that would allow me to investigate more?  Thanks!

**Comment by photonecomm** [comment]
@ezimanyi ,  same issue for me as well. 

I tried to deploy spinnaker on K8s v1.10 & v1.10.2 with Halyard version 1.0.xx & spinnaker version 1.7.0 & v.1.7.1

**Comment by bhaskar-chenchu** [comment]
I'm facing same issue. tried to deploy spinnaker v1.7.1/v1.7.0 on K8s cluster v1.10.0 or v1.10.2
[halyard.log](https://github.com/spinnaker/spinnaker/files/1987038/halyard.log)

**Comment by nitrogear** [comment]
@ezimanyi you're right, we have 1.10
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Does it depend from server version or also from kubectl version?

**Comment by ezimanyi** [comment]
This is actually an issue where Kuberetes 1.10 removed a deprecated endpoint that Halyard was depending on.  The issue will be fixed once we merge https://github.com/spinnaker/halyard/pull/933.  I was doing some testing to make sure it didn't break on Kubernetes <1.10 but everything looks good, so we should merge that today.

You'll need to make sure that the user running Spinnaker has the `services/proxy` RBAC permission for this to work, as the new endpoint relies on that permission (while the deprecated and now removed one did not).

**Comment by ezimanyi** [comment]
I just pushed a new version of Halyard (1.2.0) with the fix noted above (spinnaker/halyard#933); this should be resolved by upgrading to that version.

**Comment by ciciya-lal** [comment]
Spinnakker deploy command : " hal deploy apply " failing with error 
Problems in Global
ERROR: Unexpected exception : java.lang.IndexOutOfBoundsException:
Index: 0, Size :0

Used Enviornment : local debain , storage S3 , Cloud :AWS

**Comment by ezimanyi** [comment]
@ciciya-lal : Can you please create a new issue for your issue?  This issue was for a specific problem in Halyard that has been addressed, so your issue will likely get more visibility if you create a dedicated issue.  Can you also please include in that issue any relevant entries in your Halyard log files (usually `~/var/log/spinnaker/halyard`), in particular if you can find a stacktrace for that exception.  Thanks!

**Comment by gmccue** [comment]
@ciciya-lal I had this same issue. The fix for me was adding values to the `regions` parameter in the aws config:
```hal config provider aws account add my-aws-account \
    --account-id ${ACCOUNT_ID} \
    --assume-role ${SPINNAKER_MANAGED_ROLE} \
    --regions us-west-2```

or in `~/.hal/config`:
```
    aws:
      enabled: true
      accounts:
      - name: account-name
        ...
        regions:
        - name: us-east-1
```

**Comment by auqf** [comment]
![Uploading image.png…]()
this my error,how can fix it
