### ISSUE TITLE
GCP: Clouddriver uses old httpsChecks to determine health of instance group

### ISSUE THREAD

**Issue by nfirvine** [spinnaker/spinnaker#2736]
### Issue Summary:

https://github.com/spinnaker/clouddriver/pull/2030

uses the new UHC `compute.healthChecks.*` API. Whereas

https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/GCEUtil.groovy#L304

uses `compute.httpsHealthChecks.*`.

The net result is that deploying a server group with an autohealing policy using a new-style `compute.healthCheck` with never be detected as "up", even though it definitely is.

### Cloud Provider(s):

GCP

### Environment:

Spinnaker 1.7.2 deployed on GKE deploying to GKE + GCE.

### Feature Area: 

Clouddriver

### Steps to Reproduce:

1. Create a `compute.healthCheck`
2. Create a pipeline with a Deploy stage to GCE that has an autohealing policy with health check set to the one you made in step 1
3. Run the pipeline
The instance group will remain unhealthy forever and fail the deploy

**Comment by jtk54** [comment]
Your description does make sense -- do you have `This application considers only cloud provider health when executing tasks` enabled? I suspect I had that enabled when I revamped the GCE caching and didn't hit these cases (e.g. [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHttpLoadBalancerCachingAgent.groovy#L524)). I'll repro this hopefully tomorrow and address.

**Comment by nfirvine** [comment]
I generally do not have that box checked. I tested with it checked, and the new group deployed fine and the pipeline finished. Except that it didn't get added to the LB. And the old (working) group got disabled. Leaving me with a 100% backend-less LB :D

**Comment by jtk54** [comment]
Yep definitely not correct, will investigate. Which type of LB are you trying to associate the server group with?

**Comment by nfirvine** [comment]
HTTPS

**Comment by nfirvine** [comment]
I'm starting to question whether Spinnaker is the problem here. We've got some complex logic that happens at boot and are suspicious of whether it's finishing in time for the autoheal to not kill it. I'm actually seeing some deploys going through, but with a pretty big variance around the deploy time.

So if you find a smoking gun @jtk54 that'd be cool, but if you're struggling to repro, there's a good chance it's something on our end.

**Comment by jtk54** [comment]
I configured my application to complete operations only on configured health checks only (not platform health). I did an ad-hoc deploy with a UHC (checking `/` on port 80) configured as the autohealing health check. 
* When I deployed a vanilla ubuntu VM image, the deploy never completed. 
* When I added apache to the vanilla ubuntu (which will succeed when pinged on `/` on port 80), the deployment succeeded.

This signals to me that something strange is happening on startup in the VM so that the configured UHCs aren't passing (and thus the operations aren't completing).

**Comment by nfirvine** [comment]
Thanks Jacob. I'm going to try simplifying the test case, but pretty sure
we're failing autoheal checks.

FWIW, the GCP UI seems to create old httpHealthChecks, right? You have to
create UHCs from the CLI?

Does Spinnaker log the health as reported by the health check anywhere? I
was expecting to find it in the instance API endpoint where I can see the
platform and load balancer health.

And semi related, are there any release notes about the Google API change
around UHCs? I found a single reference to "new style health checks", but
no details.

**Comment by jtk54** [comment]
> FWIW, the GCP UI seems to create old httpHealthChecks, right? You have to create UHCs from the CLI?

I think this depends what you are creating - when creating LBs I think the default in the GCP UI is the new style health checks. If you're creating standalone health checks under 'Compute", those are the old-style httpHealthChecks. It's a bit confusing, I know :/

> Does Spinnaker log the health as reported by the health check anywhere? I
was expecting to find it in the instance API endpoint where I can see the
platform and load balancer health.

I don't think it's logged anywhere, but you can query with:

`curl http://localhost:8084/instances/spin-jtk54/us-central1/<instanceName>`

to see the instance health states.

> And semi related, are there any release notes about the Google API change
around UHCs? I found a single reference to "new style health checks", but
no details.

Unfortunately the only details we recorded were in the changelog and the PR you referenced in the first issue comment. I think we can do a better job of providing GCE reference documentation for things like health check oddities, instance metadata entries, etc. Would that help?

**Comment by nfirvine** [comment]
>
> Does Spinnaker log the health as reported by the health check anywhere? I
> was expecting to find it in the instance API endpoint where I can see the
> platform and load balancer health.
>
> I don't think it's logged anywhere, but you can query with:
>
> curl http://localhost:8084/instances/spin-jtk54/us-central1/<instanceName>
>
> to see the instance health states.
>

Yeah, that's where I'm looking, but I don't see any info about the the
autoheal health check, just the platform. When the autoheal stabilizes
eventually, I'll see load balancer info as well, but never anything about
autoheal.

> And semi related, are there any release notes about the Google API change
> around UHCs? I found a single reference to "new style health checks", but
> no details.
>
> Unfortunately the only details we recorded were in the changelog and the
> PR you referenced in the first issue comment. I think we can do a better
> job of providing GCE reference documentation for things like health check
> oddities, instance metadata entries, etc. Would that help?
>
That would help. But I was talking more about from Google's perspective. I
literally cannot find any information about why there are two redundant
resources, like when the UHC API was added, etc. I think I've deduced it by
now, but would be nice to have a reference

>

**Comment by jtk54** [comment]
Seems to me like there are possibly two separate issues here: 1. Whether the deploy operation completes from the LB health check's point of view _without autohealing configured_ and 2. Whether adding autohealing to the server group changes the behavior. I couldn't tell if this was exercised from the initial repro case, or whether the same health checks were used in both places.

@nfirvine can you try out these two cases and let me know what the results are on your side?

Regarding the legacy/UHC reasoning: I don't think there is any public documentation on the decision. We were essentially in the same boat earlier in development and had to intuit the reasoning and ramifications for introducing UHCs. I think eventually it will be just a migration and the legacy types will be dropped from the platform, but we're not there yet. There is a tiny bit of information [here](https://cloud.google.com/compute/docs/load-balancing/health-checks). Sounds like network L4 are the only load balancers using legacy. [This](https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-managed-instances#monitoring_groups) is the doc I located for autohealing.

**Comment by nfirvine** [comment]
@jtk54 nailed it. I disabled autoheal and there are tests when it doesn't come up cleanly. So probably safe to say that autoheal was just making it worse ;)

Thanks for your help, sorry for the false alarm

**Comment by nfirvine** [comment]
Here's a 100x facepalm for you.

There's this checkbox in the Deploy stage:

`Traffic [ ] Send client requests to new instances`

We had it unchecked. Not sure why, or what use case that flag has, but it sure tripped me up for many hours.
