### ISSUE TITLE
Kubernetes v2  serverGroups api  return the deleted pods.

### ISSUE THREAD

**Issue by eisig** [spinnaker/spinnaker#2737]
### Issue Summary:
The cloud dirver serverGroups api (http://localhost:7002/applications/{application}/serverGroups) return then deleted pods. 

I debug the code, found that the old replicaSet relationships would not delete from the cache.

sample keys:
```
kubernetes:replicaSet:relationships:kubernetes.v2:infrastructure:replicaSet:test100:default:nginx2-576b6d8595:pod:test100/KubernetesCoreCachingAgent[1/1]
```
==
And Why shoud the method   `translateClustersWithRelationships(Collection<CacheData> clusterData) `  in class `KubernetesV2ClusterProvider` loads serverGroups or pods  the are not in the `clusterData`?

### Cloud Provider(s):
Kubernetes v2
version: (v2.36.0)

**Comment by lwander** [comment]
Pretty sure this got fixed here: https://github.com/spinnaker/clouddriver/pull/2587

**Comment by lwander** [comment]
I would first clear the cache, then verify that this works. If those pods were in the cache before that patch was merged they will stick around until you clear them.

**Comment by eisig** [comment]
Yes, it's ok now 👍
