### ISSUE TITLE
{“error”:“Unauthorized”,“message”:“Authentication Failed: Incoming SAML message is invalid”,“status”:401,“timestamp”:1524402208502}

### ISSUE THREAD

**Issue by aniketksh** [spinnaker/spinnaker#2738]
I am trying to integrate my spinnaker application with Okta. I created application in Okta. 

Spinnaker Dashboard Application configuration:

[![enter image description here][1]][1]

I have configured my gate-local.yml file accordingly.

saml:

     enabled: true
     metadataUrl: file:/opt/spinnaker/config/metadata.xml
     keyStore: file:/opt/spinnaker/config/saml.jks
     keyStorePassword: <password>
     keyStoreAliasName: saml
     issuerId: <issuerId>

When I hit url `http://localhost:8084` i am getting redirect to Okta login page. Once I successfully logged in I am getting error message as 

> {"error":"Unauthorized","message":"Authentication Failed: Incoming SAML message is invalid","status":401,"timestamp":1524402208502}

  [1]: https://i.stack.imgur.com/BCLfX.png

**Comment by stewchen** [comment]
Hi, I also tried out the Okta SAML integration, and was able to reproduce your error. Turns out, the entity ID / Audience Restriction that was suggested in the docs, `spinnaker.io:test` does not work due to the `:` character. Setting this to a simple string worked for me, let me know if this fixes it for you.

**Comment by aniketkmindstix** [comment]
Hi @stewchen,
Thanks for the response. I have changed __Audience Restriction__ to __myspinnakerID__ in Okta Spinnaker Application and changed __issuerId__ from `gate-local.yml` file to same __myspinnakerID__. But still not working. I have some queries regarding this issuerID. In the application configurations, there is an option named __SAML Issuer ID__ and it is set to __http://www.okta.com/${org.externalKey}__. So the question is ultimately, which issuerID should I enter in `gate-local.yml'? The __http://www.okta.com/${org.externalKey}__ or __myspinnakerID__?

**Comment by aniketksh** [comment]
Hi @stewchen,
Thanks for the response. I have changed __Audience Restriction__ to __myspinnakerID__ in Okta Spinnaker Application and changed __issuerId__ from `gate-local.yml` file to same __myspinnakerID__. But still not working. 
I have some queries regarding this __issuerId__. In the Okta application configurations, there is an option named __SAML Issuer ID__ and it is set to __http://www.okta.com/${org.externalKey}__. So the question is ultimately, which issuerId should I enter in `gate-local.yml'? The __http://www.okta.com/${org.externalKey}__ or __myspinnakerID__?
