### ISSUE TITLE
apt-get install failed - halyard: unrecognized service

### ISSUE THREAD

**Issue by bhpike65** [spinnaker/spinnaker#2741]
### Issue Summary:
apt-get upgrade & update failed 

```
$apt-get install spinnaker-halyard
Setting up spinnaker-halyard (1.2.0-20180502030508) ...
halyard: unrecognized service
dpkg: error processing package spinnaker-halyard (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 spinnaker-halyard
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
$apt-get update 
...
W: GPG error: https://dl.bintray.com trusty-nightly Release: The following signatures were invalid: KEYEXPIRED 1525205328 KEYEXPIRED 1525205328 KEYEXPIRED 1525205328
```

### Cloud Provider:
Docker registry

### Environment:
Dockerfile
```
FROM ubuntu:14.04

RUN useradd -ms /bin/bash halyard && \
	apt-get update && \
	apt-get install -y apt-transport-https ca-certificates telnet && \
	apt-get install -y curl && apt-get install -y software-properties-common && \
	curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh && \
	bash InstallHalyard.sh --user halyard
```

### Feature Area
Installation

### Description
I had a problem like [spinnaker/spinnaker#2489](https://github.com/spinnaker/spinnaker/issues/2489).
after ```hal deploy apply```,  some services didn't act expect. so I try to upgrade the package.

**Comment by ezimanyi** [comment]
I've rotated the key we use to sign our repository to replace the expired key.  You may need to import the new key via:
`curl https://bintray.com/user/downloadSubjectPublicKey?username=spinnaker-releases | sudo apt-key add -`

The new key expires on 2022-05-08 and has fingerprint `539E 3508 D31C 9E80 EF16  70C6 0440 13D2 D6BA FCDF` if you want to separately verify.

Once you have this new key installed, you should be able to proceed with the update; please let me know if continue to see issues.
