### ISSUE TITLE
Spinnaker hangs on "Wait for Up Instances" when creating a server group

### ISSUE THREAD

**Issue by KennethMojanaga** [spinnaker/spinnaker#2748]
### Issue Summary:
I've used the AWS cloudFormation template to create my spinnaker instance. When setting up, all goes well, until I have to create a server group. The process hangs when waiting for up instances. What's strange is that when logging into my AWS console, the EC2 instances get successfully created by spinnaker, however in Spinnaker's point of view, it gets stuck whilst waiting for the EC2 instances to be up. I've tried repeating this about 5 times, and I keep getting the same result.

And I do realize that this issue was once reported on #198, but this didn't fix it for me. 

### Cloud Provider(s):
AWS

### Additional Details:

---

**Comment by danielpeach** [comment]
If you're not using a load balancer, you should verify in your application config that `Consider only cloud provider health when executing tasks` isn't selected. Please reopen if it is selected, or if you're using a load balancer or other health provider.

![edit_application](https://user-images.githubusercontent.com/13868700/39772259-c455587a-52c2-11e8-8f5a-27dc185fd134.png)

The help text for that field should describe its behavior.

**Comment by KennethMojanaga** [comment]
Interesting. For me, this wasn't checked by default. So when I checked it, the hanging stopped. Thanks @danielpeach for pointing me in the right direction :)
