### ISSUE TITLE
Hal Deploy Fails for Spinnaker 1.7.3 (Ozark) - Missing/Incorrect Dependency?

### ISSUE THREAD

**Issue by garystafford** [spinnaker/spinnaker#2760]
### Issue Summary:
Hal Deploy Fails for Spinnaker 1.7.3 (Ozark) - Missing/Incorrect Dependency?

### Cloud Provider(s):
AWS, GKE

### Environment:
Spinnaker running on Azure VM

### Feature Area:
Upgrading to Spinnaker 1.7.3 (Ozark) from 1.6.1 (GLOW)

### Description:
Error encountered during `hal deploy apply` of 1.7.3:
```text
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be upgraded:
  spinnaker-igor
1 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/43.1 MB of archives.
After this operation, 1,649 kB of additional disk space will be used.
(Reading database ... 48312 files and directories currently installed.)
Preparing to unpack .../spinnaker-igor_0.10.0-20180424091600_all.deb ...
Unpacking spinnaker-igor (0.10.0-20180424091600) over (0.8.0-20180110144440) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up spinnaker-igor (0.10.0-20180424091600) ...
igor stop/waiting
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.1.0-20180507112917' for 'spinnaker-clouddriver' was not found
! ERROR Error encountered running script. See above output for more
  details.
```

Same commands for 1.6.1 (GLOW) and 1.5.4 (Atypical) complete without error.

### Steps to Reproduce:
```bash
hal config version edit --version 1.7.3
sudo hal deploy apply
```

**Comment by sbwsg** [comment]
hey @garystafford thanks for the issue report.  Can you confirm the following:

- What OS is Halyard being run on?
- What OS is Spinnaker being deployed on to?
- What version of halyard are you running?  `hal -v`

I'm looking into this and will try to reproduce.  I can see the clouddriver debian which matches your error message is available on bintray here: https://bintray.com/spinnaker-releases/debians/spinnaker-clouddriver/3.1.0-20180507112917 so I'm a bit puzzled as to why it can't be found.

One more question: is this issue reproducible if you run `hal deploy apply` again?

**Comment by garystafford** [comment]
Sure, thanks for reply.

1. Halyard OS?
```text
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
2. Spinnaker? Same as above
```text
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty```
3. Hal version?
```text
1.1.0-20180425120405
```
4. Yes, reproducible. I have tried it a few times, rolling back, trying again. Same results.

Might be related? I see below in the deploys. Using previous index?:

```text
Get:7 https://dl.bintray.com trusty Release
Err https://dl.bintray.com trusty Release

Ign https://pkg.jenkins.io binary/ InRelease
Hit https://pkg.jenkins.io binary/ Release.gpg
Hit https://pkg.jenkins.io binary/ Release
Hit https://pkg.jenkins.io binary/ Packages
Ign https://pkg.jenkins.io binary/ Translation-en_US
Ign https://pkg.jenkins.io binary/ Translation-en
Fetched 5,704 B in 4s (1,208 B/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com trusty-stable Release: The following signatures were invalid: KEYEXPIRED 1525205328 KEYEXPIRED 1525205328 KEYEXPIRED 1525205328

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com trusty Release: The following signatures were invalid: KEYEXPIRED 1525205328 KEYEXPIRED 1525205328 KEYEXPIRED 1525205328

W: Failed to fetch https://dl.bintray.com/spinnaker-releases/debians/dists/trusty-stable/Release

W: Failed to fetch https://dl.bintray.com/spinnaker-releases/debians/dists/trusty/Release

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by CliveJL** [comment]
If it helps I have the exact same problem, after attempting to upgrade from version 1.7.2 to 1.7.3. I'm running Halyard and Spinnaker on the same EC2 instance, and that's running Ubuntu 14.04.5 LTS as above. My Halyard version is also identical to the one above (1.1.0-20180425120405).

**Comment by sbwsg** [comment]
Hey thanks for the input @CliveJL!

Unfortunately I'm not very familiar with debian key signing so I'm still investigating.  We're aware that the key has expired and are investigating the best course of action to update it without affecting older packages.

Curiously I'm able to install halyard on a completely fresh VM and then switch around between deployed spinnaker versions without problem.  I see warnings about signatures but I don't receive mention of index files failing to download.

**Comment by lwander** [comment]
@ezimanyi have you seen packages fail to download when the key signing is out-of-date?

**Comment by ezimanyi** [comment]
Just looking at this now---I think this may actually be a difference in default behavior when installing fetching a repo for the first time vs. updating a repo.  When I try to reproduce on a fresh install of Ubuntu, I get just a warning---but it looks from the message above that if apt has already fetched a repo it will just fall back on the last known good index if the key is expired.

I'm just doing a few smoke tests to make sure prior versions of spinnaker won't break when we rotate this key, and will update the key as soon as I'm confident this will work.

**Comment by garystafford** [comment]
__Workaround__
As a workaround, I remove the expired key, the apt repository sources, did an update, and let the hal deploy script add them back, thinking it might avoid the error. Wasn't until I also did the `apt-get update` command that it finally worked, so...

```text
pub   2048R/5275478E 2017-05-01 [expired: 2018-05-01]
uid                  Spinnaker Release (spinnaker-release Bintray GPG key) <spinnaker-dev-ext@google.com>
```

Commands:

```bash
sudo apt-key list
sudo apt-key del 5275478E
sudo rm -rf /etc/apt/sources.list.d/spinnaker*
sudo rm -rf /etc/apt/sources.list.d/halyard*
sudo apt-get update -y
```

Redeploy and success! `hal config version`:

```text
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
1.7.3
```

Pinned packages,`apt-cache policy`:

Pinned packages before fix:

```text
Pinned packages:
     spinnaker-gate -> 0.10.0-20180221133510
     spinnaker-deck -> 2.1.1-20180302170105
     spinnaker-clouddriver -> (not found)
     spinnaker-orca -> 0.10.1-20180326113234
     spinnaker-front50 -> 0.9.0-20180221133510
     spinnaker-igor -> 0.10.0-20180424091600
     spinnaker-echo -> 0.8.0-20180221133510
     spinnaker-rosco -> 0.5.0-20180221133510
```

Pinned packages after fix:

```text
Pinned packages:
     spinnaker-gate -> 0.11.0-20180404132505
     spinnaker-deck -> 2.2.1-20180507112917
     spinnaker-clouddriver -> 3.1.0-20180507112917
     spinnaker-orca -> 0.11.1-20180430163121
     spinnaker-front50 -> 0.10.0-20180415022806
     spinnaker-igor -> 0.10.0-20180424091600
     spinnaker-echo -> 0.9.0-20180406152754
     spinnaker-rosco -> 0.6.0-20180414022806
```

**Comment by sbwsg** [comment]
That's excellent, thanks for the workaround @garystafford!  I'm keeping this issue open so that it's visible to users while we're working on the bintray key problem.

**Comment by ezimanyi** [comment]
I ran into one issue validating that rotating the key won't break `apt-get` for existing packages, so have not yet rotated the key.  I should be able to rotate within ~1 day which will resolve this issue.

**Comment by ezimanyi** [comment]
I've rotated the key we use to sign our repository to replace the expired key. You may need to import the new key via:
curl https://bintray.com/user/downloadSubjectPublicKey?username=spinnaker-releases | sudo apt-key add -

The new key expires on 2022-05-08 and has fingerprint 539E 3508 D31C 9E80 EF16 70C6 0440 13D2 D6BA FCDF if you want to separately verify.

Once you have this new key installed, you should be able to proceed with the update; please let me know if continue to see issues.
