### ISSUE TITLE
Helm Bake Cannot Target Namespaces

### ISSUE THREAD

**Issue by rossedman** [spinnaker/spinnaker#2763]
### Issue Summary: 
Helm Bake stage needs a way to target namespaces. Without this option, anti-patterns are introduced to charts where a namespace variable is passed in and then tiller cannot clean up charts properly. 

### Cloud Provider(s): 
Kubernetes

### Environment: 
Spinnaker running distributed on Kubernetes in GKE, backed by GCS.

### Feature Area: 
Pipeline stage for Bake Manifest

### Description:
The Helm Bake stage cannot target different namespaces. Helm 2 has a known issue about scoping namespaces. This has to be done as a command line flag at deploy time and Tiller stores this reference so it can rollback, purge, etc. Without being able to set this anti-patterns are introduced that could be destructive to rollbacks, etc. 

### Steps to Reproduce:
Use the Bake manifest stage and try to deploy to a different namespace than the default one that is created.

**Comment by rossedman** [comment]
Wanted to follow up on this, this may be better to introduce at the Manifest Deploy layer. If I add a `namespace` variable to my helm charts I receive this error on deploy:

```
deployKubernetesManifest.deployKubernetesManifest.kube-system.wrongNamespace
```

**Comment by posox** [comment]
I want to add namespace support for Helm. Please assign this issue to me.

**Comment by ethanfrogers** [comment]
@posox that would be great, thanks!

**Comment by lwander** [comment]
Seems all PRs are merged. Thank you @posox !
