### ISSUE TITLE
Spinnaker UI doesn't fully load in Kubernetes setup

### ISSUE THREAD

**Issue by rwillard** [spinnaker/spinnaker#2771]
### Issue Summary:
Can't use Spinnaker UI, loads indefinitely.

### Cloud Provider(s):
GCP, Kubernetes

### Environment:
Running spinnaker on GKE

### Feature Area: 
UI

### Description:
When using a proxy, or port-forwarding in kubernetes to connect to `spin-deck` I get the UI page, but none of the projects or applications load. I previously used the helm spinnaker chart and it worked there. I'm guessing it's something to do with how I'm proxying it.

### Additional Details:

<img width="1439" alt="screen shot 2018-05-11 at 1 23 01 pm" src="https://user-images.githubusercontent.com/1609410/39945366-148f0d50-551f-11e8-9989-d4d5cf7e61df.png">

**Comment by ezimanyi** [comment]
@rwillard : You'll need to also forward port 8084 to the gate service in your GKE pod.  Your browser will directly send API calls to Gate, so that service needs to be accessible from the machine running your browser.  If you deploy with Halyard and run `hal deploy connect`, this should happen automatically, but if you're manually proxying then you'll need to set up proxies to both Deck and Gate.

**Comment by rwillard** [comment]
Thank you for your help. I have setup port-forwarding to both pods, and the networking is working! but now I'm getting other errors. 

`
:8011/#/applications:1 Failed to load http://localhost:8084/applications: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8011' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
`

As far as `hal deploy connect` I have setup an ubuntu VM on GCE with halyard, I did additional port-forwarding through SSH but got the same results previously. I can also look into https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-expose-the-distributed-kubernetes-hosted-spinnaker-publicly, but I just wanted to verify it was working first. I'm curious to why this worked correctly via the helm chart deployment, but not via Halyard. Why isn't Deck making calls directly to Gate?

**Comment by ezimanyi** [comment]
I think what's happening here is that you're trying to access the Spinnaker UI using a different URL than what's configured.  It's configured to use `localhost:9000` by default but it looks like from your port-forwarding you've forwarded this to `localhost:8011`.  This means that the cross-origin resource sharing check is failing, as the request is coming from `localhost:8011`.  You'll need to configure it to accept requests from that URL if you want to use it (or just use port 9000).  There's some info here: https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-expose-localdebian-spinnaker-on-a-public-ip-address-but-it-always-binds-to-localhost

That info is more for setting up Spinnaker to bind to a public IP address/domain (and to allow CORS checks to succeed from that domain) but the principle is the same here.

**Comment by rwillard** [comment]
Thank you for your help, this now works for me. Opening up port `9000` instead of `8011`.

**Comment by alex-leonhardt** [comment]
@ezimanyi once ```hal config security ui edit --override-base-url <full ui url> and hal config security api edit --override-base-url <full api url>``` is done, do you need to do a `hal deploy apply` ?

**Comment by ezimanyi** [comment]
@alex-leonhardt : Yes, you will need to run `hal deploy apply` again after running the above commands, so that Halyard can push the required changes out to any affected microservice.  Let me know if ti still doesn't work after re-running `hal deploy apply`.

**Comment by alex-leonhardt** [comment]
Ok, cool - I'll try that, as soon as my Docker4Mac (running on `edge`) kubernetes starts responding to stuff again :) - thanks!

**Comment by alex-leonhardt** [comment]
@ezimanyi that worked, thanks!

**Comment by apraovjr** [comment]
i have the same error, while deploying the spinnaker through git source code and doing hal deploy apply 

`Failed to load http://localhost:8084/credentials?expand=true: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://127.0.0.1:9000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute'

Any advice?

**Comment by lwander** [comment]
The access control policy is set to accept requests on localhost rather
than 127.0.0.1 by default. This can be changed, but using localhost:9000 is
probably easier.

**Comment by apraovjr** [comment]
@lwander how can that be changed? I tried adding this 

`cors:
  allowedOriginsPattern: http:\/\/\w+(\.\w+)*(:[0-9]+)?\/?$/`

in gate.yml. if it doesnt seem to work. Do i have to change anything in halconfig

**Comment by apraovjr** [comment]
Sorry but this is right error message
`Failed to load http://localhost:8084/webhooks/preconfigured: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:9000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by lwander** [comment]
The response above shows how to configure CORs & redirect URLs: https://github.com/spinnaker/spinnaker/issues/2771#issuecomment-392951953
