### ISSUE TITLE
Add an endpoint to search for executions by providing correlating information

### ISSUE THREAD

**Issue by joonlim** [spinnaker/spinnaker#2778]
There should be an endpoint that can be used to search for executions.

This endpoint should:
* allow a user to search for executions using a trigger config payload.
* allow a user to search for executions using some ID relating to a trigger instance (e.g., a webhook trigger gives some ID that can be used with this endpoint to query the executions triggered by said webhook).
* limit results size using a limit parameter
* only return results of a given set of statuses

Would be nice to have:
* time bound - user supplies a time range to only obtain executions created within the time frame.

**Comment by ghostsquad** [comment]
was this completed? or just closed?

**Comment by almoskvin** [comment]
Speaking about 'hal version' 1.15.0,

Spinnaker returns "eventId" on a trigger request and tries to start an execution in an asynchronous way.
Using that "eventId", it is possible to check the execution using this call:
%URL%/applications/%APP_NAME%/executions/search?triggerTypes=webhook&eventId=%EVENT_ID%.

Using that search call, we will receive an empty body in case something went wrong (I would prefer to find a readable error message there), or an executions details in case it was triggered.

**Comment by ghostsquad** [comment]
@almoskvin might want to file a new issue. It's hard enough to get attention on open issues, let alone a closed issue.

**Comment by almoskvin** [comment]
@ghostsquad hey, thanks for mentioning this.
I didn't want to get attention, I just wanted to add a workaround here as I come around this bug closed without description.
Didn't think about filing an issue, but that sounds like a good idea for sure.

**Comment by ghostsquad** [comment]
> Using that search call, we will receive an empty body in case something went wrong (I would prefer to find a readable error message there), or an executions details in case it was triggered.

I mentioned filing an issue, because I agree with this.
