### ISSUE TITLE
New feature: Allow creating template pipelines from build artifacts

### ISSUE THREAD

**Issue by amanya** [spinnaker/spinnaker#2788]
### Issue Summary:

Our main workflow with declarative pipelines involves using artifacts generated during Travis builds. On the build we upload the template which is then recognized by Spinnaker as an artifact os type `pipeline-pac` when the pipeline is triggered.

To create the pipeline, we create an empty pipeline, edit it as json and put the following code in the `template` section:

```
"template": {
    "source": "{% for artifact in trigger.buildInfo.artifacts %}{% if artifact.name ==  'pipeline' && artifact.type == 'spinnaker-pac' %}http://{{artifact.reference}}{% endif %}{% endfor %}"
},
```

After saving the pipeline, Spinnaker is able to access the generated artifact and use the corresponding pipeline to each build.

We want to make this workflow easier to use so we are thinking of doing some changes to the create pipeline modal in Deck:

![image](https://user-images.githubusercontent.com/4490611/40125136-748f0778-592a-11e8-8434-844e188a1af0.png)

This will create a new pipeline with the template field filled with the code I mentioned previously.

### Feature Area: 

Deck / pipeline / template

### Additional Details:

In further iterations, it could be good to be able to select a job from a Travis/Jenkins trigger and Deck will be able to offer a list of artifacts generated from that job.

We are willing to hear feedback from you to know if do you think that could be interesting to add this feature to Deck, and some thoughts on implementation.

**Comment by lwander** [comment]
@robzienert @jtk54 what do you guys think of this?
