### ISSUE TITLE
 I see internal server error after I authenticate it redirects, with this exception "com.netflix.spinnaker.gate.services.commands.ServerErrorException"

### ISSUE THREAD

**Issue by GoverningCloud** [spinnaker/spinnaker#2790]
### Issue Summary:

I did a fresh installation from spinnaker documentation.
After making changes to AWS and S3 config edit.  I see with Warning: spinnaker.service changed on disk. Run 'systemctl daemon-reload' to reload units. Ran systemctl daemon-reload and restarted all the following services

sudo systemctl restart apache2
sudo systemctl restart gate
sudo systemctl restart orca
sudo systemctl restart igor
sudo systemctl restart front50
sudo systemctl restart echo
sudo systemctl restart clouddriver
sudo systemctl restart rosco

But on the browser, spinnaker is giving exception "com.netflix.spinnaker.gate.services.commands.ServerErrorException"
message | "Internal Server Error"
status | 500

It was working fine before I start making AWS and S3 config edits

AWS and S3 config edits I did is as below:

hal config provider aws account add aws-account \
    --account-id {account_id} \
    --assume-role role/spinnakerManaged

hal config provider aws edit --access-key-id {access_id} \
        --secret-access-key

hal config provider aws enable

hal config storage s3 edit \
    --access-key-id {access_key} \
    --secret-access-key \
    --region us-east-1 \
    --bucket spinakker.something

hal config storage edit --type s3

hal deploy apply 

### Cloud Provider(s):
AWS
### Environment:
Ubuntu -16 

HAL Version is 1.6.0

**Comment by GoverningCloud** [comment]
IAM setup was wrong, So got this error. This issue is closed.

**Comment by KrishnaKairamkonda** [comment]
Hi, I'm also getting the same error ({"error":"Internal Server Error","exception":"com.netflix.spinnaker.gate.services.commands.ServerErrorException","message":"Internal Server Error","status":500,"timestamp":1532710248080}).

Can you please let me know which part of the IAM setup wrong for you or what can I do to solve this issue?

Thanks.

**Comment by fr34k8** [comment]
@GoverningCloud @KrishnaKairamkonda yes this would be helpful for me as well..
