### ISSUE TITLE
Kubernetes v2 provider: why are HorizontalPodAutoscalers versioned?

### ISSUE THREAD

**Issue by mattnworb** [spinnaker/spinnaker#2791]
The Kubernetes V2 provider "versions" HorizontalPodAutoscaler instances, meaning that after deploying updates to an HPA, there will be more than one version that is "alive" in the cluster, all targeting the same Deployment (or other) resource.

Was this a conscious decision? I couldn't tell from the history of https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java.

It seems to me like this resource should not be versioned in the same way a ConfigMap or a Secret is - to my knowledge, no other Kubernetes resource can refer to (or point to, in other words) a HPA.

I'm not sure what the behavior will be if you have multiple HPA instances all targeting the same Deployment resource, but I expect that if the different HPAs have different settings for things like maxReplicas, scale threshold etc then they will effectively fight with each other.

Apologies for doing things in the reverse order but I already created the PR to address this at https://github.com/spinnaker/clouddriver/pull/2629

**Comment by lwander** [comment]
They should not be! Thank you for the fix :)
