### ISSUE TITLE
What's New modal stuck at version 1.4.2

### ISSUE THREAD

**Issue by mdirkse** [spinnaker/spinnaker#2795]
Issue Summary:
What's New modal stuck at version 1.4.2

Cloud Provider(s):
N/A

Environment:
1.7.4

Feature Area:
Deck/What's New

Description:
What's New modal which includes release notes is stuck at version 1.4.2 even though we're running 1.7.4 (confirmed by running `hal version bom`)

**Comment by mdirkse** [comment]
```
maarten@mdirkse:~$ kubectl get pods spin-deck-v011-bs5f4 -o jsonpath="{..image}"
gcr.io/spinnaker-marketplace/deck:2.2.1-20180507112917 gcr.io/spinnaker-marketplace/deck:2.2.1-20180507112917
```

**Comment by skim1420** [comment]
Just as a sanity check (I actually had this problem too, and this was the cause after 30 minutes wasted), can you please open an incognito window or force refresh the browser cache and verify you're still seeing the same issue?

How recently did you do the 1.7.4 upgrade, and was it directly from 1.4.2? Thanks.

**Comment by mdirkse** [comment]
Same issue in incognito mode. And we actually upgraded from 1.6.1.

**Comment by skim1420** [comment]
Let's take a look at your browser Developer Tools, in the Network tab. Reload Spinnaker and look for a network request for the gist. For `1.7.4`, it should be `e2ba64e21c1a05e890df8a25cc2bf036`. Can you tell me what you see?

Let's move the troubleshooting over there; please DM me (@stevenkim) on slack.

**Comment by mdirkse** [comment]
Alright, mystery solved. Turns out we overwrite the Deck settings (`settings.js`) in our Halyard install. We apparently created the custom settings from the 1.4.2 settings file, because it contains:

```
var changelogGistId = 'c791562094c040e936776b501b42c7a6';
```

Which is the 1.4.2 gist. Updating that to the 1.7.4 gist solved the problem.

**Comment by skim1420** [comment]
FYI, there is an override mechanism for settings.js as well. See [settings-local.js](https://github.com/spinnaker/deck/blob/master/settings-local.js) for an example of how to override values in settings.js.
