### ISSUE TITLE
Support skipping evaluation of SpEL in individual manifests

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2809]
Something like `spel.spinnaker.io/enabled: false` should allow users to inject SpEL-like expressions into their manifests without evaluating them.

**Comment by lwander** [comment]
Thanks to @jeyrschabu this is fixed, and will be released in 1.8!

Unfortunately the annotation approach is a little too hard to implement, simply because the entire pipeline context gets evaluated without ever checking if what it's operating on is a manifest or not. 

Instead, all you need to do is wrap your expression in `${}`.

Say you have an env var `${ENV_VAR}` you want in your manifest. You need to write it as `${"${ENV_VAR}"}`.

**Comment by lwander** [comment]
@davidxia @rossedman who ran into this.

**Comment by rossedman** [comment]
Thanks so much!

**Comment by maggieneterval** [comment]
@xxmaestroxx I'm curious if you've devised any sort of workaround for this issue -- thanks!

**Comment by maggieneterval** [comment]
@emjburns, I heard you may be working on a strategy for disabling SpEL evaluation in individual stages -- not sure if that could eventually help resolve this issue? Thanks in advance.

**Comment by emjburns** [comment]
I have dreams/a proposal for removing SpEL evaluation entirely from stages with the exception of resolving variables. Proposal here: https://github.com/spinnaker/spinnaker/issues/3500

The implementation is a long way out though :(

**Comment by maggieneterval** [comment]
Ah I see, thanks Emily!

**Comment by pselden** [comment]
Can this be reopened? Forcing to escape it makes it non-usable as a "normal" helm chart, which is useful for development.

**Comment by maggieneterval** [comment]
Just wanted to highlight that a workaround to this issue was released with Spinnaker 1.13. More details available in the PR here: https://github.com/spinnaker/spinnaker/issues/3028

**Comment by markentelo** [comment]
![Screen Shot 2019-04-08 at 3 33 10 PM](https://user-images.githubusercontent.com/38673441/55761403-061e3700-5a14-11e9-9c78-eaa0c86b92bd.png)
 clicking this fixed my issue

**Comment by dangvv-teko** [comment]
> ![Screen Shot 2019-04-08 at 3 33 10 PM](https://user-images.githubusercontent.com/38673441/55761403-061e3700-5a14-11e9-9c78-eaa0c86b92bd.png)
> clicking this fixed my issue

yep. Thanks

**Comment by Ant0wan** [comment]
hi everybody - The Skip SpEL expression does not fix the issue and keep substitution going on the helm chart retrieve from S3 bucket :/

**Comment by linjmeyer** [comment]
Seeing this break some configmaps that contain regex, where `${1}` becomes just `1` after Spinnaker evaluates the SPEL, that is with the "Skip SpEL expression evaluation" option checked.  I think at some point recently this feature became broken.  On Spinnaker 1.29.0 atm.
