### ISSUE TITLE
Halyard:stable container expects script to run with sudo but doesn't have sudo permissions 

### ISSUE THREAD

**Issue by medyagh** [spinnaker/spinnaker#2813]
### Issue Summary:

Running `hall deploy apply` on the stable container (gcr.io/spinnaker-marketplace/halyard:stable)
will result in error that it expects the script to be run with sudo. 

```
/home/spinnaker/.hal/default/install.sh must be executed with root permissions; exiting
```

I tried to do `sudo hal deploy apply` but the halyard container doesn't not have `sudo` installed and won't let me install it, since the spinnaker user is not a sudoer 
 ```bash: sudo: command not found``` 

### Cloud Provider(s):
kubernetes (minikube)

### Steps to Reproduce:

Follow the steps on `spinnaker.io/setup/install/` to deploy spinnaker to a kubernetes cluster (in my case a minikube cluster),
Configure everything as instructed (Roles, Kube Config, GCS bucket,...) 

For halyard choose the option of running halyard in docker (instead of on ubuntu)
in last step of the instruction, inside the halyard container, run `hal deploy apply`
and you will get this error `/home/spinnaker/.hal/default/install.sh must be executed with root permissions; exiting`

### Additional information

```
$ hal -v
1.2.0-20180509113540
```

I tried to modify the Dockerfile on halyard repo locally and built this Dockerfile

```
FROM gcr.io/spinnaker-marketplace/halyard:stable

USER root
```

That will let me become root and then add spinnaker to sudoers group, but I think that could be fixed in the original Dockerfile, if you agree I could make a PR for it.

**Comment by lwander** [comment]
We intentionally moved away from `root` for security reasons -- are you sure that you're deploying to a distributed env instead of a local debian env? 

What are the permissions of that install.sh file?

@spinnakerbot add-label operations/installation

**Comment by PatrickAuld** [comment]
I'm also encountering this; you hit this if you follow the recommended steps in the install docs.

**Comment by lwander** [comment]
@dorbin can you look at this? It seems the new recommended steps are causing trouble.

**Comment by lwander** [comment]
@medyagh can you share what the permissions are on that file?

**Comment by medyagh** [comment]
@lwander 
Since the `.hal` folder is mounted from the host, it is owned by the user that runs docker. (medya user)
so halyard's user on the container (spinnaker user) was not able to read it, so chown-ed it to spinnaker's UID on the host and also did chmod a+r+w on all the files in .hal folder.

Before that I was getting errors that it can not access .hal folder, after that I got passed that step.
however still in the very end, when everything was happy and wanted to do `hal deploy apply`

it yelled at me that it requires "root" which actually is in the halyard install.sh [source code here](https://github.com/spinnaker/halyard/blob/master/install/Installer.sh#L337) 

```
if [[ \`/usr/bin/id -u\` -ne 0 ]]; then
  echo "$0 must be executed with root permissions; exiting"
  exit 1
fi
```

**Comment by medyagh** [comment]
hm... yeah I pointed it to a `minikube` cluster on same host. I wonder it that would be a problem.

**Comment by lwander** [comment]
What's the output of `hal config deploy -o yaml`?

**Comment by medyagh** [comment]
here is the output of `hal config deploy -o yaml` testing against a minikube cluster.

```
$ hal config deploy -o yaml
+ Get current deployment
  Success
+ Get the deployment environment
  Success
+ Retrieved configured deployment environment.
size: SMALL
type: LocalDebian
updateVersions: true
consul:
  enabled: false
vault:
  enabled: false
customSizing: {}
gitConfig:
  upstreamUser: spinnaker


```

here is the full output from `hal deploy apply`

```
spinnaker@93341cb6d4db:~/.hal$ kubectl get nodes
NAME       STATUS    AGE       VERSION
minikube   Ready     3h        v1.10.0
spinnaker@93341cb6d4db:~/.hal$ VERSION=1.7.5
spinnaker@93341cb6d4db:~/.hal$ hal config version edit --version $VERSION
+ Get current deployment
  Success
+ Edit Spinnaker version
  Success
+ Spinnaker has been configured to update/install version "1.7.5".
  Deploy this version of Spinnaker with `hal deploy apply`.
spinnaker@93341cb6d4db:~/.hal$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.provider.kubernetes.my-k8s-account:
- WARNING You have not specified a Kubernetes context in your
  halconfig, Spinnaker will use "minikube" instead.
? We recommend explicitly setting a context in your halconfig, to
  ensure changes to your kubeconfig won't break your deployment.
? Options include: 
  - gke_nest-development_us-central1-a_medya-dumb-test
  - gke_nest-svcplat-sandbox_us-central1-a_cluster-1
  - minikube

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
+ Apply deployment
  Success
+ Run `hal deploy connect` to connect to Spinnaker.
/home/spinnaker/.hal/default/install.sh must be executed with root permissions; exiting
! ERROR Error encountered running script. See above output for more
  details.
spinnaker@93341cb6d4db:~/.hal$ 
```

I verified that the minikube cluster is accessible through the halyard's container.
by doing this:

```
$ kubectl get sa
NAME                        SECRETS   AGE
default                     1         3h
spinnaker-service-account   1         15m
```

here is the full file permissions

```
spinnaker@93341cb6d4db:~/.hal$ pwd
/home/spinnaker/.hal
spinnaker@93341cb6d4db:~/.hal$ ls -lah
total 36K
drwxr-xr-x  7 spinnaker spinnaker 4.0K May 24 00:44 .
drwxr-xr-x  1 spinnaker spinnaker 4.0K May 24 00:38 ..
drwxr-xr-x  2 spinnaker spinnaker 4.0K May 24 00:44 .backup
drwxr-xr-x  2 spinnaker spinnaker 4.0K May 24 00:30 .gcp
drwxr-xr-x  4 spinnaker spinnaker 4.0K May 24 00:27 .kube
drwxr-xr-x 10 spinnaker spinnaker 4.0K May 24 00:27 .minikube
-rw-r--r--  1 spinnaker spinnaker 4.6K May 24 00:43 config
drwxr-xr-x  7 spinnaker spinnaker 4.0K May 24 00:44 default
```


I only tested this against Minikube.

**Comment by lwander** [comment]
Is it possible that you missed the `hal config deploy edit --type distributed --account-name <account>` command called out [here](https://www.spinnaker.io/setup/install/environment/#distributed-installation)? If so that's why halyard is trying to install this using debian packages.

**Comment by alex-leonhardt** [comment]
had the same issue, and missed the above - after I ran it, ran `halyard deploy apply` and it's creating _all the things_ now 👍

**Comment by lwander** [comment]
Nice!

@dorbin @nhayes it seems the new docs are causing some confusion around this point -- is that something we can look into clarifying?

**Comment by dorbin** [comment]
@medyagh 
@alex-leonhardt 
You aren't the only ones who have missed this. But I'm trying to figure out how it's happening. With the new version of setup instructions, everything but the Distributed Installation is collapsed, and Distributed has only two steps. Step 2 is the one that's getting missed. 
Can either of you offer any insight into what's happening? Anything I could do to make the step harder to miss?

Thanks!

**Comment by medyagh** [comment]
@dorbin I noticed when you follow the guided step by step docs , some steps are are not put in the "Next do this", for example configuring the persistent storage. Thats very common for documentations to get complicated like this, specially with big projects docs. Good thing is we can make a PR and make the docs better for others :)

**Comment by karlazzam** [comment]
im installing this locally and following the docs and still getting this error. 

seems the hal config deploy edit --type distributed --account-name <account> command is a fix for distributed accounts? i dont even think the local installation has an account name

**Comment by grabcocque** [comment]
Why was this issue closed when the error still exists?

Following the local deploy documentation:

/home/spinnaker/.hal/default/install.sh must be executed with root permissions; exiting

**Comment by lwander** [comment]
Because you cannot (regardless of the error) deploy a `--type localdebian` install to a docker image. Arguably the error message can be made better, but it's not super easy to tell if you're running in a docker container or if your permissions are just wrong.
