### ISSUE TITLE
Next steps on "Install Halyard" skip "Configure Cloud Providers"

### ISSUE THREAD

**Issue by thepatrick** [spinnaker/spinnaker#2814]
### Issue Summary:
Next steps on "Install Halyard" skip "Configure Cloud Providers"

### Cloud Provider(s):
N/A

### Environment:
N/A

### Feature Area: 
Documentation

### Description:
On https://www.spinnaker.io/setup/install/halyard/ at the bottom under "Next Steps" it sends you to https://www.spinnaker.io/setup/install/environment/ instead of https://www.spinnaker.io/setup/install/providers/

### Steps to Reproduce:
N/A

### Additional Details:
This was super confusing.

**Comment by lwander** [comment]
@dorbin can you take a look at this?

@spinnakerbot add-label docs

**Comment by dorbin** [comment]
Good catch, @thepatrick 
Sorry 'bout that.

[spinnaker/spinnaker.github.io/pull/795](https://github.com/spinnaker/spinnaker.github.io/pull/795)

**Comment by thepatrick** [comment]
thanks @dorbin :)
