### ISSUE TITLE
Deploy (manifest) is missing in Spinnaker 1.7.5

### ISSUE THREAD

**Issue by tsadoklevi** [spinnaker/spinnaker#2840]
### Issue Summary:
After upgrading Spinnaker (using Halyard) from version 1.6 to version 1.7.5 "Deploy (manifest)" stopped showing up in the "Type" combo box when creating a new stage. 

### Cloud Provider(s):
Google Cloud Platform

### Environment:
K8s

### Steps to Reproduce:
Create a new stage and open the "Type" combo box.  

### Additional Details:
None

**Comment by sbwsg** [comment]
Thanks for the issue report.  Can you confirm whether any of the other "(manifest)" stages appear in the dropdown (e.g. "Delete (manifest)" or "Undo Rollout (manifest)")?

I'd like to also confirm the version of the kubernetes provider you're running and its configuration; could you provide your halyard config with any sensitive information removed?  You can get this by running `hal config` at your terminal.

**Comment by tsadoklevi** [comment]
1. None of the other "(manifest)" stages appear

2. **Kubernetes**: 1.9.6-gke.1

3. hal conifg:

name: default
version: 1.7.5
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: true
    accounts:
    - name: my-gcr-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://eu.gcr.io
      username: _json_key
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
      passwordFile: /home/[INFO-CHANGED]/.gcp/gcp.json
    - name: my-docker-hub-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://index.docker.io
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories:
      - library/nginx
      - google/cloud-sdk
    primaryAccount: my-gcr-account
  google:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: my-k8s-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      dockerRegistries:
      - accountName: my-gcr-account
        namespaces: []
      context: gke_[INFO-CHANGED]_europe-west1-b_spinnaker
      configureImagePullSecrets: true
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      kubeconfigFile: /home/[INFO-CHANGED]/.kube/config
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: my-k8s-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oraclebmcs:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: my-k8s-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/[INFO-CHANGED]/.gcp/gcp.json
    project: [INFO-CHANGED]
    bucket: spin-dd2b8ebf-2404-484f-9122-733a7b35066e
    rootFolder: front50
  redis: {}
  s3:
    rootFolder: front50
  oraclebmcs: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: true
    masters:
    - name: my-jenkins-master
      address: http://[INFO-CHANGED]:8080
      username: [INFO-CHANGED]
      password: [INFO-CHANGED]
  travis:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
    overrideBaseUrl: http://[INFO-CHANGED]:8084
  uiSecurity:
    ssl:
      enabled: false
    overrideBaseUrl: http://[INFO-CHANGED]:9000
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
    enabled: false
artifacts:
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
    ldap:
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true

**Comment by sbwsg** [comment]
Ah ok so the issue here appears to be that you don't have a k8s v2 provider configured.  The kubernetes account in your hal config, `my-k8s-account`, is set to `providerVersion: v1`.  The manifest stages are only present if you are running the v2 provider.  In older versions of spinnaker the stage dropdown did not correctly filter out the manifest stages which likely explains why you used to see them in the UI.

In order to get a v2 account set up follow the instructions on this page: https://www.spinnaker.io/setup/install/providers/kubernetes-v2/

Once you've done that and deployed spinnaker with `hal deploy apply` you should see both your v1 and v2 accounts appear in the configuration for your application in the UI and additionally you should be able to select the manifest stages when working with pipelines.

**Comment by tsadoklevi** [comment]
Thanks a lot! Perfect! 

```
hal config provider kubernetes account add my-k8s-v2-account 
--provider-version v2 
--context $(kubectl config current-context)

hal config features edit --artifacts true

hal deploy apply
```
BTW - Any idea why I received the following (I succeeded with `hal deploy apply` only the third time)?

```
Problems in Global:
! ERROR Failed to monitor task: 503 Service Unavailable
```

**Comment by sbwsg** [comment]
It's difficult to tell exactly what's causing the 503s.  If you continue to see them I recommend capturing halyard's debug output by running the `hal deploy apply` command with the `-d` flag and then including that in a new issue on this repo.  Thanks!
