### ISSUE TITLE
Skip lifecycle management flag is not being respected by redis service

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2851]
As per @rossedman neither the v1 or v2 deployments are respecting the `skipLifecycleManagement` service setting for Redis.

Assigning @brandonnelson3 as he added this flag

**Comment by lwander** [comment]
Ha it turns out the flag is `skipLifeCycleManagement` (notice the capital C).

**Comment by rossedman** [comment]
@lwander Ahhhhhhhhhhhhh. Dang.
