### ISSUE TITLE
Update spinnaker configuration with Halyard crashes

### ISSUE THREAD

**Issue by angegar** [spinnaker/spinnaker#2858]
### Issue Summary:
Can't modify my configuration after a first installation with halyard.

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker deployed with halyard.
Github Authentication enabled
Spinnaker accessible throught a Kubernetes Service of type LoadBalancer
Kubernetes deployed with KOPS on AWS
I created ane executed the rbac.yml from the documentation

### Feature Area: 
spinnaker deployment with halyard

### Description:
I perfectly manage to install spinnaker with halyard a first time. However when i tried to modify the configuration and deploy it, the deployment crashes. I  see the new pods coming in kubernetes but orca can't delete the old one and their status becomes unknown. 

### Steps to Reproduce:
Deploy spinnaker a first time with halyard
Try to upate the configuration with hal deploy apply

### Additional Details:

` 2018-06-01 07:40:27.611  INFO 13890 --- [     Thread-134] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Deploy spin-orca] (a271b9c4-0384-4561-9eb7-41b2bb008bfe) - FAILED completed
<--- HTTP 503 http://localhost:62685/api/v1/namespaces/spinnaker/services/spin-orca-bootstrap:8083/proxy/pipelines/ffc36460-1133-436d-9212-e87a26bd16ed (162ms)
2018-06-01 07:40:27.617  INFO 13890 --- [     Thread-130] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Deploy spin-clouddriver] (4eac33fb-1e7f-4f4d-84e3-d779e5e6fe0d) - RUNNING failed with HalException:

com.netflix.spinnaker.halyard.core.error.v1.HalException: Failed to monitor task: 503 Service Unavailable
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.OrcaRunner.monitor(OrcaRunner.java:135) ~[halyard-deploy-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.OrcaRunner.monitorPipeline(OrcaRunner.java:60) ~[halyard-deploy-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deployServiceWithOrca(DistributedDeployer.java:288) ~[halyard-deploy-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.lambda$deploy$4(DistributedDeployer.java:214) ~[halyard-deploy-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:127) ~[halyard-core-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.2.0-20180509113540.jar:1.2.0-20180509113540]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171] `

**Comment by angegar** [comment]
Hi all, i still not solve this issue and it prevents me to update my spinnaker stack. I tried to downgrade halyard to the version 1.1.0 but it still not work. Please find below the execution log :

` Determining status of spin-redis-bootstrap: Manually deploying spin-redis-bootstrap
---> HTTP GET http://localhost:8064/v1/tasks/fe25ed03-a3bf-4463-8977-5707a27695f2/
---> END HTTP (no body)
<--- HTTP 200 http://localhost:8064/v1/tasks/fe25ed03-a3bf-4463-8977-5707a27695f2/ (2ms)
X-Application-Context: halyard:test,local:8064
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 05 Jun 2018 14:35:53 GMT
OkHttp-Sent-Millis: 1528209353879
OkHttp-Received-Millis: 1528209353882

{
  "name" : "Apply deployment",
  "timeout" : 1800000,
  "events" : [ {
    "message" : "Building service endpoints",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207553564
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for clouddriver-bootstrap",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207564838
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for clouddriver",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207565606
  }, {
    "message" : "Generated 1 profile and discovered 0 custom profiles for deck",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207566488
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for echo",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207567283
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for fiat",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207568081
  }, {
    "message" : "Generated 4 profiles and discovered 0 custom profiles for front50",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207569375
  }, {
    "message" : "Generated 2 profiles and discovered 1 custom profile for gate",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207570642
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for igor",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207571473
  }, {
    "message" : "Generated 3 profiles and discovered 0 custom profiles for orca-bootstrap",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207572962
  }, {
    "message" : "Generated 2 profiles and discovered 0 custom profiles for orca",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207573712
  }, {
    "message" : "Generated 0 profiles and discovered 0 custom profiles for redis-bootstrap",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207573712
  }, {
    "message" : "Generated 0 profiles and discovered 0 custom profiles for redis",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207573712
  }, {
    "message" : "Generated 17 profiles and discovered 0 custom profiles for rosco",
    "stage" : "Generating all Spinnaker profile files and endpoints",
    "timestamp" : 1528207579241
  }, {
    "message" : "Manually deploying spin-redis-bootstrap",
    "stage" : "Determining status of spin-redis-bootstrap",
    "timestamp" : 1528207581053
  } ],
  "children" : [ ],
  "uuid" : "fe25ed03-a3bf-4463-8977-5707a27695f2",
  "timedOut" : true,
  "version" : "1.1.0-20180425074556",
  "state" : "TIMED_OUT",
  "response" : {
    "responseBody" : null,
    "problemSet" : {
      "problems" : [ {
        "message" : "Unexpected exception: DaemonTaskInterrupted(interruptedTime=1528209353561, message=Task interrupted at Tue Jun 05 14:35:53 GMT 2018: sleep interrupted)",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      } ]
    }
  },
  "fatalError" : {
    "cause" : {
      "cause" : null,
      "stackTrace" : [ {
        "methodName" : "sleep",
        "fileName" : "Thread.java",
        "lineNumber" : -2,
        "className" : "java.lang.Thread",
        "nativeMethod" : true
      }, {
        "methodName" : "safeSleep",
        "fileName" : "DaemonTaskHandler.java",
        "lineNumber" : 153,
        "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler",
        "nativeMethod" : false
      }, {
        "methodName" : "ensureRunning",
        "fileName" : "KubernetesV1DistributedService.java",
        "lineNumber" : 603,
        "className" : "com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v1.KubernetesV1DistributedService",
        "nativeMethod" : false
      }, {
        "methodName" : "deployServiceManually",
        "fileName" : "DistributedDeployer.java",
        "lineNumber" : 253,
        "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
        "nativeMethod" : false
      }, {
        "methodName" : "deploy",
        "fileName" : "DistributedDeployer.java",
        "lineNumber" : 197,
        "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
        "nativeMethod" : false
      }, {
        "methodName" : "deploy",
        "fileName" : "DistributedDeployer.java",
        "lineNumber" : 56,
        "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
        "nativeMethod" : false
      }, {
        "methodName" : "deploy",
        "fileName" : "DeployService.java",
        "lineNumber" : 252,
        "className" : "com.netflix.spinnaker.halyard.deploy.services.v1.DeployService",
        "nativeMethod" : false
      }, {
        "methodName" : "lambda$deploy$20",
        "fileName" : "DeploymentController.java",
        "lineNumber" : 253,
        "className" : "com.netflix.spinnaker.halyard.controllers.v1.DeploymentController",
        "nativeMethod" : false
      }, {
        "methodName" : "build",
        "fileName" : "DaemonResponse.java",
        "lineNumber" : 127,
        "className" : "com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder",
        "nativeMethod" : false
      }, {
        "methodName" : "lambda$submitTask$1",
        "fileName" : "TaskRepository.java",
        "lineNumber" : 48,
        "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository",
        "nativeMethod" : false
      }, {
        "methodName" : "run",
        "fileName" : "Thread.java",
        "lineNumber" : 748,
        "className" : "java.lang.Thread",
        "nativeMethod" : false
      } ],
      "message" : "sleep interrupted",
      "localizedMessage" : "sleep interrupted",
      "suppressed" : [ ]
    },
    "stackTrace" : [ {
      "methodName" : "safeSleep",
      "fileName" : "DaemonTaskHandler.java",
      "lineNumber" : 155,
      "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler",
      "nativeMethod" : false
    }, {
      "methodName" : "ensureRunning",
      "fileName" : "KubernetesV1DistributedService.java",
      "lineNumber" : 603,
      "className" : "com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v1.KubernetesV1DistributedService",
      "nativeMethod" : false
    }, {
      "methodName" : "deployServiceManually",
      "fileName" : "DistributedDeployer.java",
      "lineNumber" : 253,
      "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
      "nativeMethod" : false
    }, {
      "methodName" : "deploy",
      "fileName" : "DistributedDeployer.java",
      "lineNumber" : 197,
      "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
      "nativeMethod" : false
    }, {
      "methodName" : "deploy",
      "fileName" : "DistributedDeployer.java",
      "lineNumber" : 56,
      "className" : "com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer",
      "nativeMethod" : false
    }, {
      "methodName" : "deploy",
      "fileName" : "DeployService.java",
      "lineNumber" : 252,
      "className" : "com.netflix.spinnaker.halyard.deploy.services.v1.DeployService",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$deploy$20",
      "fileName" : "DeploymentController.java",
      "lineNumber" : 253,
      "className" : "com.netflix.spinnaker.halyard.controllers.v1.DeploymentController",
      "nativeMethod" : false
    }, {
      "methodName" : "build",
      "fileName" : "DaemonResponse.java",
      "lineNumber" : 127,
      "className" : "com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$submitTask$1",
      "fileName" : "TaskRepository.java",
      "lineNumber" : 48,
      "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "Thread.java",
      "lineNumber" : 748,
      "className" : "java.lang.Thread",
      "nativeMethod" : false
    } ],
    "interruptedTime" : 1528209353561,
    "message" : "Task interrupted at Tue Jun 05 14:35:53 GMT 2018: sleep interrupted",
    "localizedMessage" : "Task interrupted at Tue Jun 05 14:35:53 GMT 2018: sleep interrupted",
    "suppressed" : [ ]
  },
  "runningJobs" : [ ]
/ Apply deployment
  Timed out
Problems in Global:
! ERROR Unexpected exception:
  DaemonTaskInterrupted(interruptedTime=1528209353561, message=Task interrupted at
  Tue Jun 05 14:35:53 GMT 2018: sleep interrupted)

- Failed to deploy Spinnaker. Task killed because it was taking too
  long.`

**Comment by sbwsg** [comment]
Hi @angegar thanks for the issue report.  Did you manage to resolve this issue?  I notice on Slack that you were guided to check if your nodes were running out of memory during the deployment of the new pods.  Did you manage to do this?

**Comment by angegar** [comment]
@sbwsg Indeed i increase the cluster capacity and it seems to work now, however i still have test to do.

**Comment by sbwsg** [comment]
OK, I will close this issue for now but please feel free to re-open if this issue continues to happen.
