### ISSUE TITLE
Certain stages show up but don't work in a Spinnaker application running on GKE

### ISSUE THREAD

**Issue by nhayes** [spinnaker/spinnaker#2865]
### Issue Summary:
Several stages show up in the UI but don't seem to fully work on my GKE Spinnaker application, but do work on GCE. Specifically, I am able to add _Bake_, _Find Image from Tags_, or _Tag Image_ to my pipeline, but the configuration section is blank for all of them.

### Cloud Provider(s):
Kubernetes v1

### Environment:
Distributed installation, Spinnaker running on GKE

### Feature Area: 
Pipelines

### Description:
I am able to add a _Bake_, _Find Image from Tags_, or _Tag Image_ stage to a pipeline in my Spinnaker application running on GKE, but am unable to fully configure it. The configuration step is entirely blank, as you can see below:
![image](https://user-images.githubusercontent.com/2678856/40939438-a1161dbc-6812-11e8-9294-29cad3cccf8a.png)
The same blank configuration field shows up in both _Find Image From Tags_ and _Tag Image_. I haven't noticed it in any other stages.

### Steps to Reproduce:
1. Deploy Spinnaker to GKE and create an application
2. Create a pipeline, and try to add _Bake_, _Find Image from Tags_, or _Tag Image_

### Additional Details:
When I create an application on GCE using the same Spinnaker deployment, these stages work fine, so I think it's a Kubernetes-specific problem.

**Comment by lwander** [comment]
These stages don't work for that provider. I remember @sbwsg added a mechanism to remove stages from appearing for certain providers?

**Comment by nhayes** [comment]
Looks like I'm on version 1.7.0.

**Comment by sbwsg** [comment]
Great, thanks!  I was able to reproduce on 1.7.6 and then double-confirmed that the master branch doesn't exhibit the same problem.  I'm going to close this issue given that the 1.8 window will open next week and will include the fixed UI.  If we think it's worth updating 1.7 for this then I can do so but to me right now it doesn't seem urgent.

**Comment by lwander** [comment]
SGTM :+1:
