### ISSUE TITLE
Docker triggers have stopped working

### ISSUE THREAD

**Issue by greenkiwi** [spinnaker/spinnaker#2873]
### Issue Summary:
After upgrading spinnaker from 1.6 to 1.7.5, automatic docker triggers have stopped firing.

### Cloud Provider(s):
4 kubernetes v1

### Environment:
kubernetes 1.9.8
spinnaker 1.7.5
In AWS deployed via kops

### Feature Area: 
pipeline trigger

### Description:
We have a number of pipelines that are supposed to automatically trigger when a new docker image is available.  After upgrading to 1.7.5, all of our triggers stopped working.

### Steps to Reproduce:
* We have a pipeline as defined below
* We push a new docker image
* We expect the pipeline to start running, it doesn't.

### Additional Details:
```
{
  "keepWaitingPipelines": false,
  "lastModifiedBy": "a",
  "limitConcurrent": true,
  "stages": [
    {
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 90
    }
  ],
  "triggers": [
    {
      "account": "spinnaker-dockerhub",
      "enabled": true,
      "organization": "t",
      "registry": "index.docker.io",
      "repository": "t/httpd-spin",
      "type": "docker"
    }
  ],
  "updateTs": "1528239331000"
}
```

**Comment by tomrj** [comment]
I can see this happening in 1.7.x and unreleased 1.8.x. Behaviour is the same. There are no errors in CloudDriver, and it picks up new tags, but nothing happens.

**Comment by greenkiwi** [comment]
We are using docker.io for our CR.  We have the same behavior, tags all work but no triggers do.

I did see this ticket that was closed about a year ago:
https://github.com/spinnaker/spinnaker/issues/1424

**Comment by greenkiwi** [comment]
@tomrj I did find these log messages in `igor`
```
2018-06-06 06:32:40.148  INFO 1 --- [readScheduler-2] c.n.spinnaker.igor.docker.DockerMonitor  : Found 11334 new images for spinnaker-dockerhub
2018-06-06 06:32:40.149 ERROR 1 --- [readScheduler-2] c.n.spinnaker.igor.docker.DockerMonitor  : Number of items (11334) to cache exceeds upper threshold (1000) in monitor=DockerMonitor partition=spinnaker-dockerhub
```
And that matched the comments here: 
https://github.com/spinnaker/spinnaker/issues/2037#issuecomment-393837705

Once I increased the cache threshold, everything was good  `./profiles/igor-local.yaml`
```
spinnaker:
  pollingSafeguard:
    itemUpperThreshold: 50000
```

**Comment by joaquinclearmetal** [comment]
Is there any way to configure this with `hal`.   Looking through logs, we seem to be running into this right away.

```
spinnaker:
  pollingSafeguard:
    itemUpperThreshold: 50000
```
