### ISSUE TITLE
Support bearychat notification

### ISSUE THREAD

**Issue by abcsnowwolf** [spinnaker/spinnaker#2874]
### Issue Summary:
Although echo have supported 4 kinds of message tools such as Email and Slack and so on. Some Chinese developer are using bearychat as a teamworking tool Because IMs like slack is hard to use in China. Bearychat is a kind of IM software just like slack. Add support to bearychat will make chinese developer  convenient to use notification function in echo. 

### Feature Area: 
echo

### Description:
I have implemented this feature and deploy it on our test env. To support bearychat i modify deck to display bearychat on the related UI page. Add the Notification type 'BEARYCHAT' in orca and front50. Implement feature in echo module. 
Do you think it is necessary to add this feature?

**Comment by lwander** [comment]
That sounds like a great feature to add! If you feel like your changes are ready, please open a pull request :)

**Comment by lwander** [comment]
Thanks @abcsnowwolf!
