### ISSUE TITLE
Notifications not being sent, Slack doesn't show as option

### ISSUE THREAD

**Issue by rwillard** [spinnaker/spinnaker#2876]
### Issue Summary:
Notifications aren't being sent and missing notification options.

### Cloud Provider(s):
GKe

### Environment:
I'm running halyard via docker and working with Kubernetes V2.

### Feature Area: 
Notifications

### Description:
In a pipeline or application settings, I've successfully added email notifications, but none are sent out. Additionally I've setup Slack notifications via halyard, but Slack doesn't show up as a notification option in settings. 

### Additional Details:
I looked through my logs and found logs like these

```
c.n.s.front50.model.GcsStorageService : Failed to load notifications __global: 404 Not Found
```

**Comment by rwillard** [comment]
Hey I'm wanting to solve this notifications issue before fully replacing my current CI setup. Is there any more information I can provide to help, or maybe how can I attempt to solve this on my own? Thanks for your help!

**Comment by lwander** [comment]
Email can be tough to setup correctly... maybe @skim1420 has some pointers?

**Comment by rwillard** [comment]
Good news, Slack is showing up as an option for notifications and notifying now, yay. The only change I made was a change I made to spinnaker was a change to auth via halyard a few days ago. I'm guessing all of the components that needed to be redeployed when I added Slack weren't, but did get redeployed with the auth change. Does that sounds right? Should I close this issue since things are working for me now, or leave it open incase someone wants to track down the first issue? Thanks for your help.

**Comment by abcsnowwolf** [comment]
only echo needed to be redeployed i think.

**Comment by francoran** [comment]
Im facing the same issue, fresh spinnaker cluster (1.10.1) slack option won't appear in notifications dropdown even after echo redeployment.

**Comment by steffensol** [comment]
Seeing the same thing. My spinnaker cluster is deployed via the helm chart, on a AKS kubernetes cluster.
I've enabled slack notifications in halyard on the kube-cluster, and redeployed ALL microservices. The option is still not showing up in the notification dropdown menu.

**Comment by DavidGereb** [comment]
> same issue here, slack configured, enabled, stack redeployed, still not showing up in dropdown
> 
> spinnaker: 1.10.5
> kubernetes(AWS EKS): v1.10.11-eks
> k8s provider: v2
> halyard: 1.12.0

actually after like the 3rd redeploy, it started showing up, digged some logs and seems to be a caching issue, showed up after I saw this message in the logs:
```
spinnaker/spin-echo-54ff968f4b-dbwrj[echo]: 2018-12-06 13:30:58.792  INFO 1 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
```

**Comment by DavidGereb** [comment]
> > same issue here, slack configured, enabled, stack redeployed, still not showing up in dropdown
> > spinnaker: 1.10.5
> > kubernetes(AWS EKS): v1.10.11-eks
> > k8s provider: v2
> > halyard: 1.12.0
> 
> actually after like the 3rd redeploy, it started showing up, digged some logs and seems to be a caching issue, showed up after I saw this message in the logs:
> 
> ```
> spinnaker/spin-echo-54ff968f4b-dbwrj[echo]: 2018-12-06 13:30:58.792  INFO 1 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
> ```

also log out, then log back in, otherwise it may not appear

**Comment by huychau** [comment]
I got the same issue after following the document to enable Slack https://docs.armory.io/spinnaker-install-admin-guides/slack-notifications/ 
Slack item in notification options doesn't showing. Any solution?

**Comment by stacyodell** [comment]
Same thing happened to me.  I had to close any open browser tabs, go back into the deck UI, and refresh my cache via ctrl+f5 -- and then the Slack choice showed up.

**Comment by MortenKaae** [comment]
Just encountered the same issue with Slack not showing as a notification type when configuring a pipeline (even after redeploying everything).

I was able to resolve it by logging in and out of Spinnaker. Maybe this can help somebody experiencing similar issues.
