### ISSUE TITLE
Simplify AWS setup

### ISSUE THREAD

**Issue by anshrma** [spinnaker/spinnaker#2897]
### Issue Summary:
Under the following setup instructions

https://www.spinnaker.io/setup/install/providers/aws/
https://www.spinnaker.io/setup/install/providers/ecs/

Simplify the setup by adding CLI based steps

### Cloud Provider(s):
AWS,ECS

### Environment:
NA

### Feature Area: 
Documentation,CLI

### Steps to Reproduce:
NA

**Comment by lwander** [comment]
I believe @emjburns is/was working on this.

**Comment by anshrma** [comment]
Thanks @lwander . @emjburns - Pls let me know and i can contribute to work. Else, i have WIP in my fork. Planning to submit the PR by EOD tomorrow.

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/853
