### ISSUE TITLE
Git artifactAccount=null

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [spinnaker/spinnaker#2901]
### Issue Summary:

I have followed the instructions to enable Git several times and hit the same issue each time. When i add a Git artifact to to a pipeline phase following these instructions:

https://www.spinnaker.io/setup/artifacts/github/

When I start my pipeline it fails and the error from the pipeline is saying that the 

artifactAccount=nulll

Which makes sense as when I check in Git the access token I supplied to HAL at config time has never been accessed. My HAL config is at the bottom of this issue.

### Cloud Provider(s):

GCE

### Environment:

KUBERNETES

### Feature Area: 

ARTIFACT PROVIDER

## HAL CONFIG 

name: default
version: 1.7.6
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: my-k8s-v2-account
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: gke_kubernetes-production-201717_us-west1-c_production-1
      configureImagePullSecrets: true
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      kubeconfigFile: /home/dylan/.kube/config
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: my-k8s-v2-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oraclebmcs:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: my-k8s-v2-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/dylan/.gcp/gcs-account.json
    project: kubernetes-production-201717
    bucket: spin-bca5dfdb-72b4-44b9-9fc1-65a303fdb154
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oraclebmcs: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
  artifacts: true
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
    enabled: false
artifacts:
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: true
    accounts:
    - name: jhh-github
      tokenFile: /home/dylan/git.token
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true

**Comment by ezimanyi** [comment]
@dylanjohnsonsfo : I actually don't think that the `artifactAccount=null` is a problem here; that's just indicating that it's not filtering on the particular account when trying to match an artifact.

The issue is that if your trigger has specified an expected artifact, you won't be able to supply that artifact when manually starting a pipeline (as there's currently no way to supply artifacts for a manual execution).  What you probably want to do is check 'Use Default Artifact' and supply the default information there, so that Spinnaker will fall back to that artifact rather than fail the pipeline if the artifact is not present in the trigger.

**Comment by dylanjohnsonsfo** [comment]
@ezimanyi  Thanks for helping me out! I am still not too clear, even when I specify an artifact the pipeline stage never hits my git account to pull the file even though I am pushing commits / merging to the master branch. Do you have an example of a GIT pipeline please? Again , many thanks for your help here.

**Comment by ezimanyi** [comment]
I have the following pipeline set up and it's working for me:
![image](https://user-images.githubusercontent.com/1391982/41480517-bbf9c0ce-709c-11e8-82f5-0acfcda3dba5.png)

One thing that's worth noting is that the contents of an artifact are only fetched when needed---so unless you're using the git artifact in some way downstream it's expected that you wouldn't see your access key being used.

**Comment by dylanjohnsonsfo** [comment]
@ezimanyi Thanks ! I was my configuration, i have it all working now. I neglected to set up the webhooks / auth properly. Thanks again for all the help!
