### ISSUE TITLE
Move Halyard pid file to /var/run

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/spinnaker#2908]
Halyard currently stores its pid file in `/opt/halyard` which requires making that directory writeable to the user running Halyard.  Let's move to the more common paradigm of putting the pid file in `/var/run` thus allowing `/opt/halyard` to be only writeable by root and removing the need for the user running the software to write to that directory.

We'll of course need to make sure this change is done in a backwards-compatible way so that newer versions of Halyard can still find a pid file created by older versions.

See issue https://github.com/spinnaker/halyard/pull/971 for more details.

**Comment by lwander** [comment]
:+1:

**Comment by ezimanyi** [comment]
https://github.com/spinnaker/halyard/pull/973

**Comment by ezimanyi** [comment]
Closing this for now, as moving to `/var/run` adds system-specific dependencies we'd like to avoid, and that are not worth the minor benefit we'd gain.
