### ISSUE TITLE
hal command to restart Halyard

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker#2910]
### Issue Summary:
Can we add a new hal command to easily restart Halyard, or at least stop Halyard. Or both. 

### Cloud Provider(s):
N/A

### Environment:
Any

### Feature Area: 
Halyard

### Description:
This comes up because we noticed that Halyard needs to be able to find `kubectl` in the $PATH, and if you install `kubectl`after Halyard's already running, and then update the path to include it, Halyard can't see it without restarting. And we had to kill the Halyard daemon rather. A command like `hal restart` would be nice.

### Steps to Reproduce:
N/A

### Additional Details:

@brandonnelson3 

---

**Comment by lwander** [comment]
:+1:

**Comment by brandonnelson3** [comment]
@lwander How do you feel about hal shutdown to kill the halyard daemon, and hal deploy shutdown for localgit setups to kill everything on your local machine?

**Comment by brandonnelson3** [comment]
Discussed offline, going to implement hal shutdown to kill the halyard daemon now, and punt on the hal deploy shutdown until we can decide how that would behave in all environments instead of only implementing localgit.

**Comment by brandonnelson3** [comment]
https://github.com/spinnaker/halyard/pull/980 is sent

**Comment by joonlim** [comment]
Can I suggest adding a block on how to restart Halyard here (https://www.spinnaker.io/setup/install/environment/):

![image](https://user-images.githubusercontent.com/9713942/41919305-331af654-792c-11e8-9530-685a199de7b8.png)

**Comment by dorbin** [comment]
:+1: 
[spinnaker/spinnaker.github.io/#886](https://github.com/spinnaker/spinnaker.github.io/pull/886)

**Comment by aleon1220** [comment]
Is this implemented already?
