### ISSUE TITLE
macOS TAR not available

### ISSUE THREAD

**Issue by schmitzhermes** [spinnaker/spinnaker#2913]
### Issue Summary:
Halyard Stable for macOS is not available at: https://storage.googleapis.com/spinnaker-artifacts/halyard/stable/macos/halyard.tar.gz

### Cloud Provider(s):
local

### Environment:
local

### Feature Area: 
Halyard

### Steps to Reproduce:
Executing `sudo bash InstallHalyard.sh` 
Output:
```
Halyard version will be stable
Halconfig will be stored at /Users/schmitzhermes/.hal/config
Uninstall script is located at /Users/schmitzhermes/.hal/uninstall.sh
Java is already installed & at the right version
~/installhalyard.JRIe ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   247  100   247    0     0    436      0 --:--:-- --:--:-- --:--:--   435
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

The TAR is not downloaded properly. Accessing https://storage.googleapis.com/spinnaker-artifacts/halyard/stable/macos/halyard.tar.gz
 manually gives me:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to spinnaker-artifacts/halyard/stable/macos/halyard.tar.gz.
</Details>
</Error>

**Comment by ezimanyi** [comment]
I believe this is a temporary issue due to https://github.com/spinnaker/halyard/pull/970; the next halyard release will put the tarball there.  @lwander am I understanding this correctly?

**Comment by schmitzhermes** [comment]
Oh, I understand. Since #970 is being merged I am going to try this again! Thank u!

**Comment by lwander** [comment]
It was merged but not yet released... we will release soon. Sorry the docs don't reflect this.
