### ISSUE TITLE
Igor wont start because of travis missing artifact decorator after upgrading 1.6.1 -> 1.7.6

### ISSUE THREAD

**Issue by TheSpy** [spinnaker/spinnaker#2918]
### Issue Summary:
Igor wont start after upgrading 1.6.1 -> 1.7.6, in igor.log it says 
Parameter 5 of method travisMasters in com.netflix.spinnaker.igor.config.TravisConfig required a bean of type 'com.netflix.spinnaker.igor.service.ArtifactDecorator' that could not be found. Consider defining a bean of type 'com.netflix.spinnaker.igor.service.ArtifactDecorator' in your configuration.

### Cloud Provider(s):
GCP

### Environment:
Running on compute engine, ubuntu

### Feature Area: 
ci travis

### Description:
Error in igor.log

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 5 of method travisMasters in com.netflix.spinnaker.igor.config.TravisConfig required a bean of type 'com.netflix.spinnaker.igor.service.ArtifactDecorator' that could not be found.

Action:

Consider defining a bean of type 'com.netflix.spinnaker.igor.service.ArtifactDecorator' in your configuration.

### Steps to Reproduce:
hal config ci travis master add ci --address https://api.travis-ci.com --base-url https://travis-ci.com --github-token ...

hal config version edit --version 1.7.6

### Additional Details:
https://files.slack.com/files-pri/T091CRSGH-FB9U42YR5/tempsnip.png

**Comment by ethanfrogers** [comment]
@TheSpy i'm not sure how halyard handles this error (or would handle it), but you can add the following config to `igor-local.yml`:

```
artifact:
  decorator:
    enabled: true
```

**Comment by lwander** [comment]
@gardleopard does this sound familiar?

**Comment by TheSpy** [comment]
@ethanfrogers thanks for reply. Unfortunately, but I get the same error by adding the artifact decorator enabled to true.

**Comment by TheSpy** [comment]
I have tried placing igor-local.yml into .hal/default/profiles folder. After deploying configuration I can see the file appears in .hal/default/staging folder. Is that the right place?

**Comment by TheSpy** [comment]
Sorry, it seems to start without errors now.
