### ISSUE TITLE
Add validation to ensure at least one CONFIGURATION_STORE type account is configured for kayenta.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#2935]

**Comment by oahayder** [comment]
Can we also fix the instruction here to be more clear here: https://www.spinnaker.io/setup/canary/#enable-s3-for-your-canary

Changing it to
```
hal config canary aws edit --s3-enabled true
```

**Comment by duftler** [comment]
Have looked at that many times, and never noticed it was wrong. Thanks for spotting that.

Fix is here: https://github.com/spinnaker/spinnaker.github.io/pull/872
