### ISSUE TITLE
Deck doesn't cache bust its javascript after an update

### ISSUE THREAD

**Issue by jfillo** [spinnaker/spinnaker#2942]
### Issue Summary:
Deck UI uses old javascript after an upgrade.

### Cloud Provider(s):
Kubernetes

### Environment:
I am using Halyard to deploy Spinnaker to Kubernetes

### Feature Area: 
Deck UI

### Description:
Browser caches old javascript files even after an upgrade to Deck which would contain new javascript files
```
<script type="text/javascript" src="settings.js"></script>
<script type="text/javascript" src="settings-local.js"></script>
<script type="text/javascript" src="vendors~app.js"></script>
<script type="text/javascript" src="app.js"></script>
```

### Steps to Reproduce:
_This issue is most visible with the k8s v2 provider stages in 1.7 -> 1.8_ 

#### Repo
* Install Spinnaker version 1.7.X
* Go to the Deck UI and create an application/pipeline with various v2 provider stages
* Upgrade the Spinnaker version to 1.8.X
* Go to the Deck UI in same browser and try to view/edit/update the pipelines.
* The javascript files loaded are the ones from the Deck version of Spinnaker 1.7.X

#### Expected results
* The new javascript files are loaded by the browser after the upgrade.

#### Workaround
* Refreshing the Deck UI using Cmd+Shift+R (Mac) will force the new javascript files to be loaded.

We shouldn't expect users to delete their caches manually every time the UI is updated.

### Additional Details:

I would expect the Deck javascript file paths to be content hashed, so that when the page loads the browser is forced to download the newer resource, rather than using the cached version with the same name.

One common method to do this is:
```
<script type="text/javascript" src="settings.5654c47bdd.js"></script>
<script type="text/javascript" src="settings-local.7846bc9975.js"></script>
<script type="text/javascript" src="vendors~app.95dfc795d.js"></script>
<script type="text/javascript" src="app.6f65ff6c8d.js"></script>
```

**Comment by lwander** [comment]
@danielpeach, @sbwsg thoughts?

**Comment by danielpeach** [comment]
I've noticed this and would like to see this solved. I'd be very surprised if there isn't just a Webpack toggle that does this for us.

**Comment by sbwsg** [comment]
This is resolved with https://github.com/spinnaker/deck/pull/5482
