### ISSUE TITLE
Spinnaker does not list images in public dockerhub repository

### ISSUE THREAD

**Issue by jicowan** [spinnaker/spinnaker#2950]
### Issue Summary:
When creating a new server group or a pipeline, Spinnaker doesn't find the list of images in the dockerhub repository.  I've confirmed that there is a image in the repository with a tag (latest).  

### Cloud Provider(s):
Kubernetes (legacy) & DockerHub

### Environment:
Spinnaker 1.8.0, k8s client 1.10.4, server 1.10.3

### Feature Area: 
Infrastructure/Clusters & Pipelines

### Description:
Spinnaker is unable to enumerate the images in the Dockerhub repository. 

### Steps to Reproduce:
Create application, create server group, enter name of repo in containers field. 

### Additional Details:
Config of dockerhub.  I've tried editing the account and redeploying spinnaker but it had no effect. 
```
+ Account dockerhub:
DockerRegistryAccount(address=https://index.docker.io, username=[username], password=[pwd], email=fake.email@spinnaker.io, cacheIntervalSeconds=30, clientTimeoutMillis=60000, cacheThreads=1, paginateSize=100, sortTagsByDate=false, trackDigests=false, insecureRegistry=false, repositories=[], passwordFile=null, dockerconfigFile=null)
+ DOCKERHUB

DockerRegistryAccount(address=https://index.docker.io, username=[username],
password=[pwd], email=fake.email@spinnaker.io, cacheIntervalSeconds=30,
clientTimeoutMillis=60000, cacheThreads=1, paginateSize=100,
sortTagsByDate=false, trackDigests=false, insecureRegistry=false,
repositories=[], passwordFile=null, dockerconfigFile=null)
```
---

**Comment by sbwsg** [comment]
Hi @jicowan, thanks for the issue report!  It looks from your hal config snippet like there are no repositories configured for your docker registry account.  I believe this is the source of the problem - per the doc at https://www.spinnaker.io/setup/install/providers/docker-registry/#dockerhub 

> Dockerhub hosts a mix of public and private repositories, but does not expose a catalog endpoint to programmatically list them. Therefore you need to explicitly list which Docker repositories you want to index and deploy.

So I think the hal command to add repositories would look like this:

```bash
hal config provider docker-registry account edit my-dockerhub-account --repositories library/nginx yourusername/app
```

**Comment by jicowan** [comment]
Thanks for catching that @sbwsg. I could have sworn I specified a repository when I created the provider.
