### ISSUE TITLE
Failed to add account *** for provider  openstack.

### ISSUE THREAD

**Issue by vkryzh** [spinnaker/spinnaker#2951]
### Issue Summary:
Failed to add account *** for provider OpenStack.
When I try to add new OpenStack account, I get the next error:
Problems in default.provider.openstack:
! ERROR You must provide an environment name
I can not understand which environment does halyard mean. And can not google similar problems.

### Cloud Provider(s):
OpenStack

### Environment:
I'm trying to add OpenStack account using halyard. 

### Description:
Trying to deploy OpenStack account using [this](https://www.spinnaker.io/setup/install/providers/openstack/) manual

### Steps to Reproduce:
Used these two commands. Of course with my working values.
`hal config provider openstack enable
hal config provider openstack account add my-openstack-account \
    --auth-url http://authurl:5000/v3  --username service-account \
    --domain-name default --regions RegionOne --project-name the-project \
    --password service-password`

**Comment by sbwsg** [comment]
Hm, good question `hal config provider openstack account edit my-openstack-account --environment $ENVIRONMENT_NAME` is the command to issue but I don't know what an "openstack environment" refers to and I don't know why the spinnaker docs don't mention this in the linked examples.

@edwinavalos @varikin @emjburns can you provide any guidance here - how can a user find the correct string to give to the `--environment` argument when setting up an openstack account with halyard?

**Comment by edwinavalos** [comment]
Openstack environment doesn't correspond to an openstack construct, but on simply for ease of use in Spinnaker IIRC. @varikin explained it to me once, but it should just be whatever was specified for in @sbwsg's comment.

**Comment by sbwsg** [comment]
Thanks for the input here @edwinavalos and @varikin !  I added a doc update to https://www.spinnaker.io/setup/install/providers/openstack/ to use the --environment flag.
