### ISSUE TITLE
Artifact from another cluster is bound when pipeline is triggered via Pipeline stage

### ISSUE THREAD

**Issue by tomrj** [spinnaker/spinnaker#2997]
### Issue Summary:

When pipeline produces a versioned ConfigMap bound to a Deployment in a cluster, this artifact is bound to another cluster overriding other artifact versions of the same artifact name.

### Cloud Provider(s):

Kubernetes V2

### Environment:

K8, Halyard

### Feature Area: 

Artifact binding, Bake (Manifest), Deploy (Manifest)

### Description:

When binding ConfigMaps in produced by bake stage in a pipeline, the expected behaviour is that baked artifacts are used when available, and not artifacts from the parent pipeline execution bound and deployed to some other cluster.

### Steps to Reproduce:

- Create two pipelines with producing manifest with a ConfigMap bound to a deployment.
- Pipelines deploy same application to two different K8 clusters
- Pipelines bake or expect a manifest with a ConfigMap which is bound to a Deployment
- ConfigMaps has same name and metadata for all K8 accounts, but just with different values.
- First pipeline triggers second pipeline using Pipeline stage.
- Second pipeline consumes artifacts from first pipeline 
- Trigger some updates in second pipeline to bump the ConfigMap version there. 
- Clean up old versions of ConfigMap from second cluster.
- Trigger first pipeline. Second pipeline will bind ConfigMap from first pipeline's cluster and fail the deploy when bound artifact is not found in second pipeline.

### Additional Details:

![screen shot 2018-07-03 at 14 54 58](https://user-images.githubusercontent.com/4036575/42218401-1cbabee4-7ed1-11e8-9307-666a3a0cb7e6.png)
![screen shot 2018-07-03 at 14 54 45](https://user-images.githubusercontent.com/4036575/42218409-230a283e-7ed1-11e8-9e8c-0744687e5099.png)

**Comment by lwander** [comment]
This was fixed a while ago: https://github.com/spinnaker/clouddriver/pull/2799 It's releases 1.9 and 1.8
