### ISSUE TITLE
Pipeline expressions do not show candidates.

### ISSUE THREAD

**Issue by axot** [spinnaker/spinnaker#3004]
### Issue Summary:
Pipeline expressions do not show candidates.

### Cloud Provider(s):
GKE

### Environment:
spinnaker 1.8.0

### Feature Area: 
orca

### Steps to Reproduce:
Deploy Spinnaker in GKE. Typing in any pipeline expressions field.

<img width="629" alt="screen shot 2018-07-05 at 23 12 03" src="https://user-images.githubusercontent.com/611054/42328398-1cac7166-80a9-11e8-9c7a-4218f3368d77.png">

**Comment by kskewes** [comment]
Can second this. Although expressions do work, eg: `Docker Tag (git hash): ${trigger.tag}`

**Comment by axot** [comment]
@kskewes Thank you for the advice, without the candidate list how to know which variable could use?

**Comment by lwander** [comment]
No worries -- I'm not very qualified to help with this -- maybe @anotherchrisberry or @danielpeach know how well the autocomplete should work?

One reason why this is tricky is that many of the tokens in the expression aren't known until runtime, even if they are guaranteed to be there. This comes down to the fact that a lot of the internal state of pipeline executions is still represented as unstructured data inside the execution engine, even though we are taking steps to improve this.

**Comment by danielpeach** [comment]
Sorry, what is a candidate in this context?

When in the pipeline config view, typing `?` inside `${...}` should list the set of top-level keys from the previous execution. Typing `#` should list the set of helper functions.

**Comment by axot** [comment]
@lwander Thanks for the rapid reply and detailed explanation.

@danielpeach Hello, I tried both `${?}` and `${#}` but no candidate list showed up.

**Comment by danielpeach** [comment]
Have you run the pipeline yet? If not, then the expression helper won't work. 

In the past, I've noticed a bit of weird behavior in some input fields. The "Comments" boxes have always worked well for me to try out the expression helper.

**Comment by axot** [comment]
Yes, the pipeline which I am testing already ran over 100 times. Here is another example when I typed `stage` function. By the way, is there any debug tips so I can provide more details.

<img width="742" alt="screen shot 2018-07-06 at 23 34 50" src="https://user-images.githubusercontent.com/611054/42384592-65b732e8-8175-11e8-8d54-1b344d4b7b92.png">

**Comment by SeanStewart37** [comment]
@axot Did you ever find a solution?

**Comment by yatanasov** [comment]
Hi, is there any progress on this ? Thanks :)

**Comment by magine1989** [comment]
i have the same issues, and my spinnaker version is 1.12.9,  orca image is orca:2.4.2-20190323030609

**Comment by mitch-hamburger** [comment]
Any progress on this? @axot

**Comment by mitch-hamburger** [comment]
@emjburns thanks for the response! I do have previous runs' json to look at, and unfortunately nothing but the `trigger` block seems to be available to grab with the expression language. Specifically the stage is a script runner that invokes a basic script running jenkins job, and I would like to grab the url of the jenkins job output to display.

**Comment by emjburns** [comment]
Have you tried starting from `${ execution. }` to access properties? Sometimes the helper functions get intermittently broken :( 

Have you tried using the [stage helper function](https://www.spinnaker.io/guides/user/pipeline/expressions/#context-values) to grab the state?

Have you tried [grabbing the stages and filtering them](https://www.spinnaker.io/guides/user/pipeline/expressions/#filter-maps)?
