### ISSUE TITLE
GitHub AuthZ: cannot work correctly "No results found"

### ISSUE THREAD

**Issue by b4b4r07** [spinnaker/spinnaker#3006]
### Issue Summary:

Got "No results found" in Permission text area after enabling GitHub authz

### Cloud Provider(s):

Google, Kubernetes, GitHub

### Environment:

1.8.0

### Feature Area: 

Authorization

### Description:

I set the authorization with GitHub to my Spinnaker in accordance with https://www.spinnaker.io/setup/security/authorization/github-teams/

However, I got "No results found" message in Permission text area:

![2018-07-06 12 45 08](https://user-images.githubusercontent.com/4442708/42358998-87aa5d86-811a-11e8-9d42-25c89306d9c1.png)

I'd like to display GitHub teams in that area.

### Steps to Reproduce:

https://www.spinnaker.io/setup/security/authorization/github-teams/

```console
b4b4r07@halyard:~$ sudo su - spinnaker
spinnaker@halyard:~$ TOKEN=xxx
spinnaker@halyard:~$ ORG=kouzoh
spinnaker@halyard:~$ hal config security authz github edit --accessToken $TOKEN --organization $ORG --baseUrl https://api.github.com
+ Get current deployment
  Success
+ Get github group membership settings
  Success
+ Edit github group membership settings
  Success
+ Successfully edited github method.
spinnaker@halyard:~$ hal config security authz edit --type github
+ Get current deployment
  Success
+ Get group membership settings
  Success
+ Edit group membership settings
  Success
+ Successfully updated roles.
spinnaker@halyard:~$ hal config security authz enable
+ Get current deployment
  Success
+ Edit authorization settings
  Success
+ Successfully enabled authorization
spinnaker@halyard:~$
```

### Additional Details:

N/A

**Comment by stewchen** [comment]
Hi, is your fiat service up and healthy? I'd check the fiat and gate service logs to see if anything went wrong.
