### ISSUE TITLE
Clarify behavior of artifacts matching as regular expressions

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/spinnaker#3011]
The fact that artifacts match as regular expressions has caused some confusion (ex: [this community post](https://community.spinnaker.io/t/application-trigger-contains-name-of-another-application/488/4)).

While in some cases this can be useful (such as in allowing any file in a particular directory for a git artifact), in other cases it can lead to unexpected behavior (such as if a user has two docker registries, one of which is a prefix of the other).

Attempting to anchor the end of the regular expression with a `$` causes the SPEL syntax helper to appear, making it appear to the user that they should not be using the `$` character in its regex sense.  (Despite the confusing UI behavior, anchoring the end with a `$` does work.)

There are a few things we could consider to make this more clear (in addition to improving the documentation):
(1) Change the behavior so that these no longer match as regular expressions
(2) Let the user specify (such as via a checkbox) whether they want to match as a string or regex
(3) Leave the fields as regular expressions, but always implicitly anchor them, so that if a user enters `abc` we match against `^abc$`.  This would probably reduce the surprise of users who don't expect `abc` to match `abcde` but still lets them specify `abc*` if that's what they want.

I'm inclined to go with option (3) because that would leave all the same functionality in place, but would reduce a point of surprise and make the default behavior more intuitive.  Option (1) would remove functionality that is useful in many cases, while option (2) adds complexity (both in the UI and in the back-end code) that doesn't really give us anything that option (3) doesn't already

**Comment by ezimanyi** [comment]
Still need to pull the kork change above into the microservices that use `ExpectedArtifact`

**Comment by emjburns** [comment]
To marry option #2 and #3, there could be a UI checkbox that allows you to specify string (exact match) or regex. If string is checked, the json value the ui creates could still be the anchored one: ^blah$. Checking regex would allow you to go into "power user" mode and explicitly write regex.

**Comment by ezimanyi** [comment]
I think the solution I've come up with effectively gets the same switching behavior between simple and advanced mode, but without needing a checkbox.  The new behavior is:
* If a user enters a normal string, it must match exactly for the artifact to match (b/c the back-end is effectively treating the input string as the regex `^inputstring$`)
* If a user enters a regex then that will work too, so users can do things like `.*inputstring.*` to get substring matches if they'd like (or anything more complicated)

**Comment by ezimanyi** [comment]
All set; will be part of Spinnaker 1.9.
