### ISSUE TITLE
java.lang.Boolean cannot be cast to java.lang.String when using true/false annotation (v2 Kube Spinnaker 1.8)

### ISSUE THREAD

**Issue by sharkannon** [spinnaker/spinnaker#3017]
### Issue Summary:
When trying to use the "strategy.spinnaker.io/versioned" annotation in a v2 spinnaker pipeline (Version 1.8), on a Kubernetes Secret, we get the following error:

`java.lang.Boolean cannot be cast to java.lang.String`

If I quote the boolean, things seem to proceed as normal.

### Cloud Provider(s):
Google Cloud, Kubernetes 1.10.4

### Environment:
Spinnaker 1.8 running on Kube 1.9 in GCE.

### Feature Area: 
Spinnaker v2 Pipeline (1.8)

### Steps to Reproduce:
1. Create a Deploy Manifest Step
2. Create a secret ex:
```apiVersion: v1
kind: Secret
metadata:
  name: ssl
  namespace: splunk
  annotations:
    strategy.spinnaker.io/versioned: false
type: kubernetes.io/tls
data:
  tls.crt: <data>
  tls.key <data>
```

3. execute pipeline.

I've found if . you quote the "false" the pipeline proceeds as normal.

**Comment by ethanfrogers** [comment]
_very_ interesting. i ran into this last week as well.

**Comment by lwander** [comment]
Annotations are "string"->"string" map. In YAML, `false` and `False` are both interpreted as booleans, not strings when left unquoted.

**Comment by sharkannon** [comment]
Yea, I just found that after you posted, very annoying.

**Comment by lwander** [comment]
Yeah I agree -- I'm a little hesitant to trick the yaml parser into behaving differently. I'll make an edit to the docs to clarify this for now.

**Comment by lwander** [comment]
Updated by quoting the boolean values in the docs: https://www.spinnaker.io/reference/providers/kubernetes-v2/#strategy
