### ISSUE TITLE
Feature Request: Pod logs in the Pipeline UI

### ISSUE THREAD

**Issue by benjaminws** [spinnaker/spinnaker#3029]
We already have quite a bit of detailed information about a kubernetes operation in the spinnaker pipeline UI for a given kubernetes deploy manifest stage. It would be great to be able to see specific pod logs in that UI, specifically for `Job` kinds. For instance, we use `Job`s in certain pipelines to do some setup before a deployment (similar to Bake Manifest, but with some things specific for our usage). It would be extremely useful to see those logs in the pipeline UI, especially since they aren't surfaced in a server group. Currently the only way to access these logs is through `kubectl`.

Thanks!

**Comment by ethanfrogers** [comment]
the rebirth of spinnaker/spinnaker#1832 (but for v2). 🤣

**Comment by benjaminws** [comment]
HAHA YEP

**Comment by benjaminws** [comment]
Created https://github.com/spinnaker/deck/pull/5537 to help out and get this started.

**Comment by benjaminws** [comment]
I think technically this can be closed by https://github.com/spinnaker/deck/pull/5537

Feel free to re-open if we find otherwise.
