### ISSUE TITLE
exposing spinnaker to End user in distributed environment (Kubernetes v2 AWS) 

### ISSUE THREAD

**Issue by vdoodala** [spinnaker/spinnaker#3033]
### Issue Summary:
I am trying to expose spinnaker to end user in distributed environment (Kubernetes v2 AWS). Any inputs to  expose Spinnaker UI into hostname:9000 instead of to localhost:9000 ?

### Cloud Provider(s):
AWS

**Comment by sbwsg** [comment]
A Github Issue isn't really the correct venue to ask for directions or support.  I think you might have more luck either in the #kubernetes channel on Slack (http://join.spinnaker.io/) or on the community forum here: https://community.spinnaker.io
