### ISSUE TITLE
hal config provider kubernetes enable  error

### ISSUE THREAD

**Issue by liubin-cm** [spinnaker/spinnaker#3038]
### Issue Summary:
when I exec "hal config provider kubernetes enable" in docker, show some error.
### Cloud Provider(s):
kubernetes 1.10.3

### Environment:
centos 7.4
docker 1.13.1

### Feature Area: 
hal config

### Description:
when I add --debug to the command, show below errors
```
error information below：
X-Application-Context: halyard:test,local:8064
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 12 Jul 2018 02:59:08 GMT
OkHttp-Sent-Millis: 1531364348383
OkHttp-Received-Millis: 1531364348385

{
  "name" : "Edit the kubernetes provider",
  "timeout" : 60000,
  "events" : [ {
    "message" : "Validating halconfig with CanaryValidator",
    "stage" : "Running validation",
    "timestamp" : 1531364168553
  }, {
    "message" : "Validating halconfig with CanaryAccountValidator",
    "stage" : "Running validation",
    "timestamp" : 1531364168553
  }, {
    "message" : "Validating halconfig with HalconfigValidator",
    "stage" : "Running validation",
    "timestamp" : 1531364168554
  } ],
  "children" : [ ],
  "uuid" : "37fcbc97-55de-4d1d-be42-6e89a8db5147",
  "timedOut" : true,
  "version" : "1.3.1-20180620105301",
  "state" : "RUNNING",
  "response" : null,
  "fatalError" : null,
  "runningJobs" : [ ]
_ Edit the kubernetes provider
  Running validation: Validating halconfig with HalconfigValidator
---> HTTP GET http://localhost:8064/v1/tasks/37fcbc97-55de-4d1d-be42-6e89a8db5147/
---> END HTTP (no body)
<--- HTTP 200 http://localhost:8064/v1/tasks/37fcbc97-55de-4d1d-be42-6e89a8db5147/ (2ms)
X-Application-Context: halyard:test,local:8064
Content-Length: 0
Date: Thu, 12 Jul 2018 02:59:08 GMT
OkHttp-Sent-Millis: 1531364348785
OkHttp-Received-Millis: 1531364348787
<--- END HTTP (0-byte body)
java.lang.NullPointerException
	at com.netflix.spinnaker.halyard.cli.services.v1.ResponseUnwrapper.get(ResponseUnwrapper.java:52)
	at com.netflix.spinnaker.halyard.cli.services.v1.Daemon.lambda$setProviderEnableDisable$47(Daemon.java:407)
	at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:43)
	at com.netflix.spinnaker.halyard.cli.command.v1.config.providers.AbstractProviderEnableDisableCommand.executeThis(AbstractProviderEnableDisableCommand.java:66)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:201)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:149)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:46)
```

### Additional Details:
I'm in china

---

**Comment by danielpeach** [comment]
Could you provide a bit more information so that someone could reproduce this? 

- which version of Halyard are you running? 
- does this happen on a fresh install with no existing halconfig (~/.hal/config)? If not, what does your halconfig look like? If you paste your halconfig in here, please omit any secrets.

**Comment by liubin-cm** [comment]
It's resolved, maybe network problem, I set http_proxy and https_proxy in DEFAULT_JVM_OPTION to let my host can access www.google.com, then it worked.

**Comment by hallliu1984831** [comment]
@liubin-cm ,
I followed your solution but does not work, could you kindly specify how did you set http_proxy and https_proxy in DEFAULT_JVM_OPTION? thanks very much
I used below setting: 
DEFAULT_JVM_OPTS='"-Dhttp.proxyHost=<COMPANY_PROXY_HOST>" "-Dhttp.proxyPort=80" "-Djava.security.egd=file:/dev/./urandom" "-Dspring.config.location=/opt/spinnaker/config/"'

**Comment by kaybinwong** [comment]
same issue to me, any help? ths

**Comment by hallliu1984831** [comment]
fixed in my side with below setting:
DEFAULT_JVM_OPTS='"-Dhttp.proxyHost=<COMPANY_PROXY_HOST>" "-Dhttp.proxyPort=80" "-Dhttps.proxyHost=<COMPANY_PROXY_HOST>" "-Dhttps.proxyPort=80" "-Djava.security.egd=file:/dev/./urandom" "-Dspring.config.location=/opt/spinnaker/config/"'
Then execute "hal shutdown" to restart hal service, and run "hal config provider kubernetes enable" again

**Comment by kaybinwong** [comment]
@hallliu1984831 can you share your proxy setting. ths~

**Comment by hallliu1984831** [comment]
@kaybinwong ,
Sorry I cannot share my proxy setting because it's only valid within my company which involve specific VPN.
BTW, maybe your proxy does not work, you should check it

**Comment by kaybinwong** [comment]
@hallliu1984831 ok, i will try again, ths any away~~

**Comment by tobato** [comment]
DEFAULT_JVM_OPTS in file  /opt/halyard/bin/halyard

**Comment by junsionzhang** [comment]
> DEFAULT_JVM_OPTS in file /opt/halyard/bin/halyard

the id command in docker is  spinnaker, but the file' owner is root,  so permission problem
