### ISSUE TITLE
Error when using multiple config maps with service

### ISSUE THREAD

**Issue by ekarlso** [spinnaker/spinnaker#3071]
### Issue Summary:
I am trying to use multiple config maps with Spinnaker but the Deployment artifact it produces references the wrong resource version of the configmap

### Cloud Provider(s):
Kubernetes v2

### Environment:
Azure AKS
Kubernetes v1.10.x

### Feature Area: 
Clouddriver

### Description:
When I deploy my manifest that references 2 config maps the deployment references v001 for one of them whilst the deployed one is v000. I have talked to @sbwsg at there's nothing suspicious in my manifests. The funny thing is that the "dev" account get's the manifests deployed correctly but not the second "prod" account, both have differen bake stages

### Steps to Reproduce:
I was unable to reproduce it but I wonder if it's something to do with caching ?

**Comment by nvndnl** [comment]
@spinnakerbot add-label provider/kubernetes-v2

**Comment by lwander** [comment]
Can you share the pipeline that's causing trouble? My guess is that there are two upstream stages that are deploying these config maps, and clouddriver can't tell which one to use?
