### ISSUE TITLE
Unable to deploy Helm chart (Failed to evaluate)

### ISSUE THREAD

**Issue by posox** [spinnaker/spinnaker#3076]
Steps to reproduce:
1. Bake zookeeper Helm chart:
tarball: http://mirantisworkloads.storage.googleapis.com/zookeeper-1.7.0.tgz
source: https://github.com/Mirantis/k8s-apps/tree/master/charts/zookeeper

2. Deploy produced manifests. It fails with error:

```
[Result {description='Failed to evaluate [log4j.properties] EL1007E: Property or field 'root' cannot be found on null', exceptionType=class org.springframework.expression.spel.SpelEvaluationException, timestamp=1532353866296, level=ERROR}]}
```

[orca logs](https://gist.github.com/posox/03b0ce468c8a539d5000859431b3246c)

**Comment by ethanfrogers** [comment]
@posox perhaps it's related to this: https://github.com/spinnaker/spinnaker/issues/3028 and this line in your chart specifically: https://github.com/Mirantis/k8s-apps/blob/master/charts/zookeeper/templates/zookeeper/configmap.yaml#L34

**Comment by ethanfrogers** [comment]
Here's the original report: https://github.com/spinnaker/spinnaker/issues/2809.

**Comment by posox** [comment]
@ethanfrogers thank you for clarification.
