### ISSUE TITLE
Force Rebake option cannot be selected

### ISSUE THREAD

**Issue by tcrozier** [spinnaker/spinnaker#3079]
### Issue Summary:
After upgrading to version 1.8.1 I can no longer select the Force Rebake option on any pipeline.

### Cloud Provider(s):
AWS

### Environment:
I'm running Spinnaker on Kubernetes.

### Feature Area: 
deck

### Description:
![image](https://user-images.githubusercontent.com/25442647/43140962-c556e8aa-8f22-11e8-9575-55fcbbc3f5c2.png)

When trying to select the Force Rebake option I see the following error:

react-dom.production.min.js:17 Uncaught TypeError: Cannot set property 'rebake' of null
    at ManualExecutionBake.handleChange (ManualExecutionBake.tsx:11)
    at Object.ma (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at Ga (react-dom.production.min.js:20)
    at Ka (react-dom.production.min.js:22)
    at Ma (react-dom.production.min.js:22)
    at Array.forEach (<anonymous>)
    at Ia (react-dom.production.min.js:21)
    at Pa (react-dom.production.min.js:24)

### Steps to Reproduce:
1. Create and run a pipeline with a bake stage
2. Try to select the Force Rebake option.

**Comment by dotdotdotpaul** [comment]
Just found this as well with a customer.  I found that if I have a Jenkins trigger configured as the source of the pipeline, it seems to work fine, but if I just have it triggering off Github, the JS error shows up.  In these examples, we're using AWS for our host & destination.

The file `/app/scripts/modules/core/src/pipeline/config/stages/bake/ManualExecutionBake.tsx` appears to be new in 1.8.x (compared to 1.7.x), commit `5c977ac207`...

**Comment by dotdotdotpaul** [comment]
Looks like this MIGHT have been fixed on master, `ab83c704e9` shows the failing command changed to a lodash "set" call.  If this fix is valid, it needs to get pulled into the 1.8.x branch sooner than later.

**Comment by sbwsg** [comment]
Thanks for pulling this in 1.8.4 @dotdotdotpaul I'm going to close this issue now.  @tcrozier and anyone else experiencing this: please upgrade to 1.8.4 to get this change; if the problem persists please feel free to re-open this issue.

**Comment by tcrozier** [comment]
Thanks - Already installed and it fixed the issue.
