### ISSUE TITLE
Spin (Spinnaker CLI) does not support code verifier which makes the tool less secure

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#3129]
Desktop and mobile applications cannot protect their OAuth2 client secrets that's why as an additional security measure they should make use of code_verifier:
- https://developers.google.com/identity/protocols/OAuth2InstalledApp
- https://www.oauth.com/oauth2-servers/pkce/authorization-code-exchange/

I'm no expert in Go but I see that code verifier is not provided in https://github.com/spinnaker/spin/blob/master/command/meta.go:

```
authURL := config.AuthCodeURL("state-token", oauth2.AccessTypeOffline, oauth2.ApprovalForce)
m.Ui.Output(fmt.Sprintf("Navigate to %s and authenticate", authURL))
code := m.Prompt()

newToken, err = config.Exchange(oauth2.NoContext, code)
```

Because if it was then according to the [documentation](https://godoc.org/golang.org/x/oauth2#AuthCodeOption) the `Exchange` call should've had 3 arguments.

**Comment by jtk54** [comment]
Makes sense, will implement. Thanks for pointing this out.

**Comment by wheleph** [comment]
@jtk54 if you haven't yet implemented this, can I try to create a PR?

**Comment by jtk54** [comment]
I haven't got around to it yet, have been prioritizing the release process for spin. Go ahead and open a PR :+1:
