### ISSUE TITLE
RC 1.9 - Application config UI broken

### ISSUE THREAD

**Issue by MrTrustor** [spinnaker/spinnaker#3140]
### Issue Summary:

The application "config" UI is broken and empty. Kayenta is enabled for this application.
I have the following JS errors:

```
TypeError: Cannot read property 'render' of undefined
    at UIView.push.UIView.render (UIView.js:52)
    at UIView.push.lib.UIView.render (UIViewMonkeyPatch.js:33)
    at l (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at e (react-dom.production.min.js:176)
    at f (react-dom.production.min.js:176)
    at G (react-dom.production.min.js:182)
    at x (react-dom.production.min.js:181)
    at n (react-dom.production.min.js:181)
    at B (react-dom.production.min.js:180)
```
```
stateService.js:41 Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'render' of undefined)
```

![screen shot 2018-08-08 at 12 07 16](https://user-images.githubusercontent.com/2864678/43831212-ae9fccde-9b03-11e8-97d3-5d924369815f.png)

### Cloud Provider(s):
GCP

### Environment:
Running 1.9 RC on top of Kubernetes Engine. Installed with https://spinnaker.io/downloads/kubernetes/quick-install.yml, and updated with `hal config version edit --version release-1.9.x-latest-unvalidated`

### Feature Area: 

Deck

### Steps to Reproduce:

* Deploy a Spinnaker instance on GKE with https://spinnaker.io/downloads/kubernetes/quick-install.yml, update it with `hal config version edit --version release-1.9.x-latest-unvalidated` and go to an application's configuration.

**Comment by sbwsg** [comment]
Looks like this is also a problem on the master branch.

**Comment by sbwsg** [comment]
Just tested fix from https://github.com/spinnaker/deck/pull/5572 and it appears to resolve the issue documented here.  I'll cherry-pick into 1.9 release branch.
