### ISSUE TITLE
Echo should periodically re-attempt to listen to PubSub subscriptions

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#3141]
If, for whatever reason, Echo drops a subscription listener, Echo must be restarted in order to pick up the subscription again.

**Comment by ezimanyi** [comment]
It looks like this was actually implemented by @wjoel in https://github.com/spinnaker/echo/pull/263 a few months ago.  @danielpeach: Was the case you saw of needing to restart echo running a recent version of Echo (ie, including the above change)?

**Comment by wjoel** [comment]
Note however that https://github.com/spinnaker/echo/pull/276 stops echo from restarting the subscriber if there is ever a "not found" error.

**Comment by danielpeach** [comment]
My case was that the subscription was deleted and recreated. I think it would be OK to retry even if there is a "not found" error, but this should be a very rare case.
