### ISSUE TITLE
spinnaker-monitoring-daemon should not run as root

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#3147]
As a follow up after https://github.com/spinnaker/spinnaker/issues/2606 spinnaker-monitoring-daemon container should also run as non-root

**Comment by wheleph** [comment]
@lwander when do you expect this to be released?

**Comment by lwander** [comment]
With 1.9 this week -- you can test it out using the `release-1.9.x-latest-unvalidated` now. 

Although... I'm seeing the change was only merged into master. Let me cherry pick that for you.

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker-monitoring/pull/89

**Comment by wheleph** [comment]
In Spinnaker 1.9.2 still the old version of the pod is used: gcr.io/spinnaker-marketplace/monitoring-daemon:0.8.0-20180803022808
