### ISSUE TITLE
Gitlab trigger type has unlabeled fields

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#3166]
Not sure what's supposed to be here. No console errors.

<img width="789" alt="screen shot 2018-08-10 at 4 18 12 pm" src="https://user-images.githubusercontent.com/13868700/43979549-15c7976e-9cb9-11e8-81ae-eb938f9ff9fa.png">

**Comment by sbwsg** [comment]
From @rantav in #3118, 
> In Spinnaker, the trigger should be:
> 
> Type: Git
> Repo Type: gitlab
> Next empty line : username or group name
> Next empty line : project-name
> Example: https://jmp.sh/Ztk2XVR
