### ISSUE TITLE
Artifact accounts should be associated with artifact types

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#3168]
Clouddriver could serve artifact types associated with a given artifact account.

This would help solve two UI issues:

1). If I don't have a BitBucket artifact account, I shouldn't see BitBucket as an available artifact type.

<img width="564" alt="screen shot 2018-08-10 at 4 37 56 pm" src="https://user-images.githubusercontent.com/13868700/43980356-da846db4-9cbb-11e8-9a2b-320f7caefac7.png">

The UI should be able to determine which artifact types to show based on the list of artifact account that Clouddriver serves.

2). It's not clear what the `embedded-artifact` account is:
<img width="660" alt="screen shot 2018-08-10 at 4 40 40 pm" src="https://user-images.githubusercontent.com/13868700/43980459-2eeea4f0-9cbc-11e8-8e10-e65ad287cfe4.png">

The UI should be able to hide the artifact account selector when the base64 artifact type is selected, and should filter this account out of any artifact account dropdown.

@lwander what do you think?

**Comment by lwander** [comment]
Agreed

**Comment by sbwsg** [comment]
Closed by https://github.com/spinnaker/deck/pull/5598 and https://github.com/spinnaker/deck/pull/5612
