### ISSUE TITLE
Cannot delete application with no cluster

### ISSUE THREAD

**Issue by yejingtao** [spinnaker/spinnaker#3175]
### Issue Summary:
I can't delete application with no cluster from deck

### Cloud Provider(s):
OpenStack cloud provider

### Environment:
I am running Spinnaker using the centos images to deploy into openstack

### Feature Area: 
CloudDriver and Pipelines

### Description:
It is a clean application with no cluster in deck and then click button to delete it,  the validation task in application deleting stage stop it. View the screenshot.
Errors:Application is associated with one or more clusters
![error](https://user-images.githubusercontent.com/30470799/44017392-b8dba3ca-9f0a-11e8-82d3-e77a0ea4106c.jpg)

Request {clouddriver ip:port}/applications/yjtapp01/clusters
response:
{"yungu-openstack":["yjtapp01-dev-tester"]}

Request {clouddriver ip:port}/applications/yjtapp01
response:
{"attributes":{"accounts":"yungu-openstack","cloudProviders":"openstack","createTs":"1531364594982","dataSources":{"disabled":["securityGroups"],"enabled":["canaryConfigs","executions","serverGroups","loadBalancers"]},"email":"jingtao@mgtv.com","instancePort":80,"lastModifiedBy":"anonymous","name":"yjtapp01","updateTs":"1533434553000","user":"anonymous"},"clusters":{"yungu-openstack":[{"loadBalancers":[],"name":"yjtapp01-dev-tester","provider":"openstack","serverGroups":[]}]},"name":"yjtapp01"}

So, there is a cluster names 'yjtapp01-dev-tester' in cache binding with this application, but I am sure I had destroyed it.
In my opinion, code in Orac project 'com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.DestroyServerGroupStage', the last task should be ServerGroupCacheForceRefreshTask, refresh the cache in clouddriver after destroy one server group.

### Steps to Reproduce:
step1: create a application
step2: create a loadbalance in openstack provider
step3: create a server group with loadbalance of step3 in openstack provider
step4: destroy the server group in step3
step5: delete application in step1, error occurs

**Comment by yejingtao** [comment]
Fixed by new version

**Comment by rampatnaik** [comment]
I have same issue for 1.25.6 version
