### ISSUE TITLE
Unable to find acceptable protocols - Docker Registry

### ISSUE THREAD

**Issue by renantmagalhaes** [spinnaker/spinnaker#3188]
### Issue Summary:
Cant add a organization repo in my docker-registry account

### Cloud Provider(s):
EKS

### Environment:
hal 1.6.0-20180806143444
 - 1.8.5 (Dark):
   Changelog: https://gist.github.com/spinnaker-release/19a850b9081d0fd00a9ac607dfc3d8e0
   Published: Thu Aug 02 17:40:52 BRT 2018
   (Requires Halyard >= 1.0.0)

### Description:
I have a docker-registry account setup, in this account there's no repo inside itself, but this account is part of an organization with private repos.

When i try to add the repositories of my organization, or any other repo for that matter , show's this error:

```
hal config provider docker-registry account edit my-registry --repositories library/nginx                                                                                                          
+ Get current deployment
  Success
+ Get my-registry account
  Success
- Edit the my-registry account
  Failure
Problems in default.provider.dockerRegistry.my-registry:
! ERROR Unable to reach repository: Unable to find acceptable
  protocols. isFallback=false,
  modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
  TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
  TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA,
  TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA],
  tlsVersions=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true),
  ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
  TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
  TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA,
  TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA],
  tlsVersions=[TLS_1_0], supportsTlsExtensions=true), ConnectionSpec()], supported
  protocols=[TLSv1].

- Failed to edit account my-registry for provider
  dockerRegistry.

```
### Steps to Reproduce:
hal config provider docker-registry account add my-docker-registry-v3 \                                              
                     --address $ADDRESS \
                     --repositories library/nginx \
                     --username $USERNAME \
                     --password

**Comment by lwander** [comment]
What registry are you using?

**Comment by renantmagalhaes** [comment]
Dockerhub registry

ADDRESS=index.docker.io (i'm also try to put https://index.docker.io - same error)

Any repo i try to add shows the error above for example library/nginx
