### ISSUE TITLE
Halyard OSX Install Script Not Working with Oracle Java SE

### ISSUE THREAD

**Issue by kjenney** [spinnaker/spinnaker#3244]
### Description: 

Trying to install Halyard on OSX 10.13.6 with the script here: https://github.com/spinnaker/halyard/blob/master/install/macos/InstallHalyard.sh

### Steps to Reproduce:

Download the install script:
https://github.com/spinnaker/halyard/blob/master/install/macos/InstallHalyard.sh
Install/Have Oracle Java SE 10.0.1/2
Run the install script:
```sudo bash InstallHalyard.sh```
Get error:

```Halyard version will be stable
Halconfig will be stored at /Users/kenjenney/.hal/config
Uninstall script is located at /Users/kenjenney/.hal/uninstall.sh
Java >=8 not yet installed - please install java >=8.
  Try using brew or jenv
```

### Additional Details:

If I change line 155 from:

`[[ "$java_version" == *"10.0"* ]]; then`
to
`[[ "$java_version" == *"10"* ]]; then`

it installs fine.

This is what I get for java --version:

```
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

**Comment by lwander** [comment]
Could you make the change you've suggested?

**Comment by kjenney** [comment]
I've created a PR: https://github.com/spinnaker/halyard/pull/1017

**Comment by lwander** [comment]
Thanks! Merged
