### ISSUE TITLE
Add ability to set extra environment variables for ECS Task Definitions

### ISSUE THREAD

**Issue by fcoelho** [spinnaker/spinnaker#3283]
### Issue Summary:

Spinnaker does not have a way to set extra environment variables for an ECS Task Definition.

### Cloud Provider(s):

ECS

### Feature Area: 

Clouddriver, Deck, Gate (for automation with spin?)

### Description:

Container definitions that are part of an ECS Task Definition have a parameter for the environment variables supplied to the container. Currently, Spinnaker creates the task definition with 3 fixed environment variables, and it would be helpful if that could be expanded with custom variables (set possibly in the server group definition inside of a pipeline).

[This is the section of code](https://github.com/spinnaker/clouddriver/blob/cdb56c40a8217006f3b2295425258a9d7bb7b1c8/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L124-L147) in clouddriver responsible for setting the container environment

**Comment by lysimon** [comment]
Resolved by:
* https://github.com/spinnaker/deck/commit/0a5ebadf212ab982802db24efe41836db209afd2
* https://github.com/spinnaker/clouddriver/commit/3910a332e2d410ea977bbbc4e8bf8f039bee97cb

Merged with master branch on 14/09

**Comment by fcoelho** [comment]
Thanks @lysimon! Will give it a try today or tomorrow at the latest

**Comment by fcoelho** [comment]
My "tomorrow" was a bit further away than expected, but I tested this and it's working for me!
![spin-env](https://user-images.githubusercontent.com/44905/46823202-eeffd480-cd63-11e8-9d3b-13f884743a04.png)
