### ISSUE TITLE
Broken default container name for Deploy phase (Kubernetes V1)

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#3290]
### Issue Summary:
Pipelines created through UI that use artifacts from Pub/Sub GCR triggers in their Kubernetes V1 Deploy phase are broken by default.

Default names of containers in Deploy phases that use artifacts are inherited from Docker registry names which may contain "." (i. e. "eu-gcr.io-bolcom-sbx-vso-sbx-dpitc-e18-nginx-nonroot"). Which is not allowed by Spinnaker.

### Cloud Provider(s):
Kubernetes V1

### Environment:
Spinnaker 1.9.2 running on GKE

### Feature Area: 
Pipelines, artifacts

### Steps to Reproduce:

1. Configure GCR Pub/Sub trigger according to https://www.spinnaker.io/setup/triggers/google/#receiving-messages-from-google-container-registry-gcr
2. Define Pub/Sub trigger and Expected artifacts as shown in the pipeline fragment below:

```  
...
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "kind": "custom"
      },
      "id": "40c32339-d021-410b-8837-cdad4c8b86d7",
      "matchArtifact": {
        "kind": "docker",
        "name": "eu.gcr.io/bolcom-sbx-vso-sbx-dpitc-e18/nginx-nonroot",
        "type": "docker/image"
      },
      "useDefaultArtifact": false,
      "usePriorExecution": false
    }
  ],
...
"triggers": [
    {
      "attributeConstraints": {},
      "enabled": true,
      "expectedArtifactIds": [
        "40c32339-d021-410b-8837-cdad4c8b86d7"
      ],
      "payloadConstraints": {},
      "pubsubSystem": "google",
      "subscriptionName": "gcr-manual-subscription-with-sa",
      "type": "pubsub"
    }
  ],
...
```

3. Add a deployment step and observe that the auto-generated name contains '.':
```
  "stages": [
    {
      "clusters": [
        {
...
          "containers": [
            {
...
              "imageDescription": {
                "artifactId": "40c32339-d021-410b-8837-cdad4c8b86d7",
                "fromArtifact": true,
                "imageId": "eu.gcr.io/bolcom-sbx-vso-sbx-dpitc-e18/nginx-nonroot (Artifact resolved at runtime)"
              },
...
              "name": "eu-gcr.io-bolcom-sbx-vso-sbx-dpitc-e18-nginx-nonroot",
...
```

4. Push an image to the registry to trigger the pipeline and observe the error in the UI:
```
Exception ( Create Server Group )
deployKubernetesAtomicOperationDescription.container[0].name.invalid (Must match ^[a-z0-9]+([-a-z0-9]*[a-z0-9])?$)
```

### Workaround:

After adding of Deploy phase edit pipeline as JSON and remove/replace the dot in the field.

**Comment by ezimanyi** [comment]
Thanks for the report!  Fixed in the above PR, and cherry-picked into 1.9.x.
