### ISSUE TITLE
Only manifest base deployment configuration is available

### ISSUE THREAD

**Issue by andreyshamray** [spinnaker/spinnaker#3314]
### Issue Summary:
Only manifest base deployment configuration is available for creating Server Group or Load Balancer.

### Cloud Provider(s):
Kubernetes v2

### Environment:
Kubernetes in GKE (1.10.6-gke.2)

### Description:
Hi there, I am deploying Spinnaker using stable helm chart:
https://github.com/helm/charts/tree/master/stable/spinnaker
But for some reason, I can create Load Balancer and Server Group only using manifest other fields as 
Ports, Advanced settings, etc are not visible.

### Steps to Reproduce:
Applications -> My_app -> Clusters -> Create Server Group
![screen shot 2018-09-11 at 14 50 02](https://user-images.githubusercontent.com/32450129/45358422-05363b80-b5d2-11e8-8d3e-e79628be0aea.png)

### Additional Details:
For deploying we are using the latest version of Spinnaker helm chart  1.1.0 and spinnakerVersion: 1.9.1
Also, we have enabled these hal feature:
```
spinnakerFeatureFlags:
  - artifacts
  - jobs
  - infrastructure-stages
  - pipeline-templates
```
---

**Comment by sbwsg** [comment]
The Kubernetes V2 provider doesn't offer configuration settings of the kind you're describing; all configuration happens in the kubernetes manifests you provide via artifacts or text entry fields.

The Kubernetes V1 provider does provide those kinds of configuration settings but at the cost of not supporting custom kubernetes manifests.

There is some ongoing work at the moment to try and and find a middle ground for the V2 provider such that some configuration is exposed via GUI alongside the support for manifests. It's still quite early in the design process however.

**Comment by andreyshamray** [comment]
Hi, thanks a lot for the fast answer! So, how to change helm chart to use Kubernetes V1 provider? Or maybe it can be configured by halyard?

**Comment by sbwsg** [comment]
You can add a V1 Kubernetes Provider using halyard. You'll also need to configure a docker registry. The steps to follow are here: https://www.spinnaker.io/setup/install/providers/kubernetes/
