### ISSUE TITLE
Add support for authentication of private container registries in ECS provider

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#3339]
### Issue Summary: 

At the moment - it is possible to use private container registries with the ECS provider - but it's not possible to define credentials for the registries. This is more important for Fargate - as there it is not possible to use a custom-AMI which credentials included in ECS-agent documentation.

AWS has just (6 days ago :) ) released this feature to help Fargate users (https://aws.amazon.com/about-aws/whats-new/2018/09/aws-fargate-now-supports-private-registry-authentication/ and https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) - but for sure this would also help ECS-EC2-users as well.

### Cloud Provider(s): 

ECS

### Environment: 

All Spinnaker versions

### Feature Area: 

Pipeline configurations

### Description:

I expect I would be able to define the ARN of the secret on Secrets Manager.

### Additional Details:

Open: the ARN is region-specific, right? I guess this would not actually matter - as you anyway have one deploy-stage with one value for each region...?

---

**Comment by clareliguori** [comment]
This can be closed; all PRs are merged to master and will be in 1.10
