### ISSUE TITLE
feat(provider/kubernetes): v2 Add support for PodPreset kind

### ISSUE THREAD

**Issue by Rigdon** [spinnaker/spinnaker#3345]
### Issue Summary:

Clouddriver does not support the Kubernetes [PodPreset](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podpreset-v1alpha1-settings-k8s-io) resource. Similar to #2824

### Cloud Provider(s):

Kubernetes V2
Clouddriver version 3.5.0

### Feature Area: 

Clouddriver/Kubernetes Deployments

### Description:

When deploying a kubernetes manifest with a `PodPreset` resource the pipeline fails with the error "Unsupported Kubernetes object kind 'PodPreset', unable to continue" ![screenshot](https://dha4w82d62smt.cloudfront.net/items/3C3N3r032D1x0Y1i2r2Y/Image%202018-09-17%20at%2012.35.28%20PM.png?X-CloudApp-Visitor-Id=2880687&v=3327ca03)

We are currently able to work around by adding `PodPreset` to the custom resource list in the K8s cluster configuration.

### Steps to Reproduce:

Deploy a Kubernetes manifest that includes a `PodPreset` resource.

**Comment by lwander** [comment]
Closing in favor of https://github.com/spinnaker/spinnaker/issues/3007
