### ISSUE TITLE
feat(provider/kubernetes): v2 Add support for PodSecurityPolicy kind

### ISSUE THREAD

**Issue by greenorchid** [spinnaker/spinnaker#3352]
### Issue Summary:
Clouddriver does not support the Kubernetes [PodSecurityPolicy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podsecuritypolicy-v1beta1-extensions) resource (in v1beta1). Similar to #2824 & #3345 

### Environment:
Kubernetes V2
Clouddriver version 3.5.0

### Feature Area: 
Clouddriver/Kubernetes

### Description:
When deploying a kubernetes manifest with a PodSecurityPolicy resource the pipeline fails with the error "Unsupported Kubernetes object kind 'PodSecurityPolicy', unable to continue".

This resource is not namespaced, so adding it as a kubernetesKind customResource for clouddriver leads to unpredictable deployments. Is there a spinnakerKind that has isNamespaced set to false?

### Steps to Reproduce:
Deploy a k8s manifest including a PodSecurityPolicy resource.

**Comment by lwander** [comment]
Closing in favor of #3007
