### ISSUE TITLE
Can’t add a Google Kubernetes cluster to Spinnaker 

### ISSUE THREAD

**Issue by alex25555** [spinnaker/spinnaker#3365]
### Issue Summary:
We have a Spinnaker Google Kubernetes deployment to which we would like to add a Google Kubernetes Cluster to. I'm following the steps listed in the following doc to add a K8 cluster. 

https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/

However, Hal attempts to deploy a Spinnaker installation where as we want to add a Google Kubernetes cluster to use with Spinnaker. 

hal deploy apply
+ Get current deployment
  Success
- Prep deployment
  Failure
Problems in default.provider.kubernetes.my-test-account:
! ERROR The docker registry provider has not yet been configured
  for this deployment.
? KUBERNETES needs a Docker Registry as an image source to run.

One thing we noticed is that during the last step the "hal config deploy edit" command succeeds, but after that command succeeds "hal deploy connect" fails from then on. So, "hal deploy connect" works up until we run the "hal config deploy edit" command, which conducts a connection to Spinnaker. 

hal deploy connect

+ Get current deployment

Success

- Connect to Spinnaker deployment.

Failure

Problems in Global:

! ERROR No instances running in latest server group for service

spin-deck in namespace spinnaker

- Failed to generate connection script.

### Cloud Provider(s):
Google Kubernetes Engine 

### Steps to Reproduce:
Follow the steps in the following Doc,
https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/

**Comment by sbwsg** [comment]
Can you please provide the output of `hal config -q` with any sensitive data removed?

**Comment by alex25555** [comment]
Hi @sbwsg, Hal appears to request a docker registry which I don't understand why. Thank you for taking a look at this. We've been stuck on this for a while trying to figure it out. 

hal config -q
Problems in default.provider.kubernetes.my-test-account:
! ERROR The docker registry provider has not yet been configured for this
  deployment.
? KUBERNETES needs a Docker Registry as an image source to run.
Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs set even though
  your Spinnaker deployment is a Distributed deployment on a remote cloud
  provider. As a result, you will need to open SSH tunnels against that deployment
  to access Spinnaker.
? We recommend that you instead configure an authentication mechanism (OAuth2,
  SAML2, or x509) to make it easier to access Spinnaker securely, and then
  register the intended Domain and IP addresses that your publicly facing services
  will be using.
- Failed to deployment configuration.

**Comment by sbwsg** [comment]
OK, looks like you have added a v1 kubernetes provider account, which requires a docker registry be configured. We can use the public docker hub registry just to get past this validation error:

```
hal config provider docker-registry account add dockerhub --address index.docker.io
hal config provider docker-registry enable
hal config -q
```

Try these and let me know the output.

**Comment by alex25555** [comment]
@sbwsg Thank you. That explains the requirement for the Docker registry. I configured it for a local docker registry we had installed. This is the resulting error once the Docker registry failure is clear. I highly appreciate you helping out with this. 

! ERROR Unexpected exception:
  io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST
  at: https://xxxxxxxxxxx/api/v1/namespaces. Message: Forbidden! User
  spin1 doesn't have permission. namespaces is
  forbidden: User "system:serviceaccount:default:spinnaker-service-account" cannot
  create namespaces at the cluster scope: Unknown user
  "system:serviceaccount:default:spinnaker-service-account".


Output from `hal config -q`
name: default
version: 1.9.3
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: true
    accounts:
    - name: my-docker-registry
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://xxxxxx
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
    - name: my-gcr-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://xxxxxxxx
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
    primaryAccount: my-docker-registry
  google:
    enabled: true
    accounts:
    - name: my-gce-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: xxxxxxxx
      jsonPath: xxxxxxxx
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    - name: spinnaker-dk-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: xxxxxxxx
      jsonPath: xxxxxxxx
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    - name: spin-dk-gceaccount
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: xxxxxxxx
      jsonPath: xxxxxxxx
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    primaryAccount: my-gce-account
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: spin-k8s-acc
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: gke_spinnaker_test2
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: xxxxxxxx
      oauthScopes: []
      oAuthScopes: []
    - name: my-test-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      dockerRegistries:
      - accountName: my-gcr-account
        namespaces: []
      context: spin1
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: xxxxxxxx
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: spin-k8s-acc
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
 accountName: my-test-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: xxxxxxxx
    project: xxxxxxxx
    bucket: spin
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
  artifacts: true
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: true
      client:
      resource:
      userInfoMapping:
        email: email
        firstName: given_name
        lastName: family_name
      provider: GOOGLE
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: true
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true

**Comment by alex25555** [comment]
@sbwsg  What I ended up doing is recreating the k8 Cluster we're attempting to add for Spinnaker to manage. I recovered the Hal configs from a backup. I think because the spinnaker-service-account user already existed and some of the subsequent steps needed to be repeated was part of the problem. However, I don't see it in the Hal configs or do I see any steps that would add to it. None the less, you helped me get this finally working. I'm really happy to get this out of the way. 

I assume the following added the Google kubernetes Cluster to our Spinnaker. What's might be a good way to verify it?

hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.
Problems in default.provider.dockerRegistry.my-gcr-account:
- WARNING Your docker registry has no repositories specified, and
  the registry's catalog is empty. Spinnaker will not be able to deploy any images
  until some are pushed to this registry.
? Manually specify some repositories for this docker registry to
  index.
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
+ Apply deployment
  Success
+ Run `hal deploy connect` to connect to Spinnaker.

**Comment by alex25555** [comment]
@sbwsg Should I see the spinnaker-service-account that's in the instructions (https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/) for setting up GKE Cluster to be managed by Spinnaker? At least, I would have expected it to be there.

**Comment by alex25555** [comment]
@sbwsg However, there is another account that I created with Hal following the steps form the doc , my-test-account. I do see that account listed in the Gate service credentials.

**Comment by sbwsg** [comment]
Right, you shouldn't expect to see the spinnaker-service-account listed in the `credentials` API response. That service account is stored in Kubernetes, not Spinnaker. The `my-test-account` is the account that Spinnaker utilizes.

**Comment by alex25555** [comment]
@sbwsg  Thank you so much for all your help.

**Comment by anup13kumar** [comment]
@sbwsg ,
Could you please help me Im trying to set up spinnaker in gcp kubernetes cluster [distributed]  google compute engine but while running sudo hal deploy apply  I'm getting below error 
====
- Apply deployment
  Failure
Problems in Global:
! ERROR Failed to create instance template for
  projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608:
  404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
"message" : "The resource
  'projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608'
  was not found",
    "reason" : "notFound"
  } ],
"message" : "The resource
  'projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608'
  was not found"
}

- Failed to deploy Spinnaker.

**Comment by sbwsg** [comment]
@anup13kumar Let's follow up in this issue: https://github.com/spinnaker/spinnaker/issues/3446
