### ISSUE TITLE
Unable to Set Value to String Literal Containing JSON in Pipeline Template

### ISSUE THREAD

**Issue by mdavis333** [spinnaker/spinnaker#3367]
### Issue Summary:

I am unable to set the value of a Kubernetes pod annotation in a pipeline template to a String literal containing JSON

### Environment:

Spinnaker 1.4.1, Pipeline Templates (published with roer), Kubernetes

### Feature Area: 

Feature Area

Pipeline-templates

### Description:

  I would like to set the annotations on a pod template such that pod that is created in the Kubernetes "deploy" stage has the following annotation:

```
"annotations": {
      "ad.datadoghq.com/app.logs": "[{\"source\":\"appSource\",\"service\":\"appName\"}]"
}
```

  However, no matter how I specify/escape that value in the template, the rendered pipeline contains the JSON object represented by the string, and not the string literal.  E.g.

```
      podAnnotations: |
        "ad.datadoghq.com/{{ appName }}.logs": '[{"source":"appSource","service":"{{ appName }}"}]'
```
or
```
      podAnnotations: |
        "ad.datadoghq.com/{{ appName }}.logs": |
          [{"source":"appSource","service":"{{ appName }}"}]
```
results in:
```          
          "podAnnotations": {
            "ad.datadoghq.com/appName.logs": [
              {
                "service": "appName",
                "source": "appSource"
              }
            ]
          }
```

The closest I can get is:
```
      podAnnotations: |
        "ad.datadoghq.com/{{ appName }}.logs": |
          '[{"source":"appSource","service":"{{ appName }}"}]'
```

But then the single quotes end up in the annotation:
```
         "podAnnotations": {
            "ad.datadoghq.com/appName.logs": "'[{\"source\":\"appSource\",\"service\":\"appName\"}]'"
          }
```

**Comment by lwander** [comment]
This might be one of the fundamental limitations of pipeline template's use of jinja... @robzienert have you seen something similar/a workaround? 

We're very close to publishing some docs on MPT going forward that addresses these kinds of frustrating template/string conversion issues.

**Comment by robzienert** [comment]
There's a special marker `noexpand:` that you should be able to use: https://github.com/spinnaker/orca/pull/1665

**Comment by mdavis333** [comment]
Works like a charm.  Thanks.

**Comment by GabrielRivera21** [comment]
Hello, I'm wondering how is the `noexpand:` used? I have a similar issue where i'm trying to apply an annotation that needs to be maintained as a JSON literal string, but not sure how to use the `noexpand:` marker.

An example would be great
