### ISSUE TITLE
401 Unauthorized error occurred on Google oauth2

### ISSUE THREAD

**Issue by katsew** [spinnaker/spinnaker#3385]
### Issue Summary:

I try to login to Spinnaker UI, but this problem occurred and can't login all of a sudden.
It redirects to `spingate`, the following message's shown.

```
{"error":"Unauthorized","message":"Authentication Failed: Could not obtain access token","status":401,"timestamp":1538014097360}
```

It has state and code, and also has scope.

```
state=xxx&code=xxxx&scope=https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email
```

### Cloud Provider(s):

kubernetes v2

### Environment:

Spinnaker: v1.9.4

GKE
master: 1.10.6-gke.1
nodepool: 1.10.6-gke.1

### Feature Area: 

OAuth providers

### Description:

I have some project with spinnaker and all of these have the same issue.

### Steps to Reproduce:

Unknown.
Just try to login by using [google oauth2](https://www.spinnaker.io/setup/security/authentication/oauth/providers/google/) .

### Additional Details:

Other services of mine that use google oauth2 works fine.

**Comment by vinhlh** [comment]
+1 happened to me also

**Comment by greenkiwi** [comment]
From Slack -- it looks like others are seeing this issue in other applications.

```
@BusyMac - Google just made a breaking change on their servers, causing all OAuth requests to fail. We're reported this to them, however this in turn is causing both apps to crash unexpectedly. Sit tight for an update.
```
https://twitter.com/busymac/status/1045112552626298880

**Comment by llacoste** [comment]
+1 Having the same issue

**Comment by emman27** [comment]
Hitting this too!

**Comment by NorihisaNakai** [comment]
+1 This problem occurred our spinnaker too!

**Comment by rene00** [comment]
Running 1.9.3 and was affected with this issue. I cleared the single cookie I had for my spinnaker gate endpoint and can log in now. Let's see if this holds up....

**Comment by vinhlh** [comment]
Looks like they fixed the issue :D Able to login now

**Comment by ethanfrogers** [comment]
Looks like the issue has cleared up so I'll go ahead and close this out.
