### ISSUE TITLE
Can't see/use google Container Optimised OS

### ISSUE THREAD

**Issue by zdevi** [spinnaker/spinnaker#3386]
### Issue Summary:
I want to deploy docker images on google COS host. Spinnaker doesn't offer this option. 
My workaround had been to copy latest google's cos-stable image to my repo, then on the "find image from tag" step, i specify this image i previously copied.

I don't understand why spinnaker doesn't see google's public images, as i do see microsoft public windows server images...
Also, is there a way to tell spinnaker i need to run docker image over a COS host (and it automaticaly pulls the last public version.

**Comment by duftler** [comment]
Regarding your second question, I haven't tried it myself, but I do see on the public docs page that you're supposed to specify that type of configuration via instance metadata: https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#configuring_an_instance
