### ISSUE TITLE
Fiat Service Account causes NPE if the Service Account is not a user in LDAP

### ISSUE THREAD

**Issue by indrayam** [spinnaker/spinnaker#3388]
### Issue Summary:
We create a Fiat service account using FRONT50 API. We run the FIAT Roles sync command to make sure that the new service account information gets synced. However, the sync command fails with a Null Pointer Exception. However, if the Fiat Service Account name happens to be an actual LDAP user, things work and no NPE is thrown. However, creating an LDAP user for every single Fiat Service Account is not a scalable solution for us.

### Cloud Provider(s):
I am running Spinnaker 1.9.3 on Kubernetes v1.11.2. Kubernetes is running on an OpenStack cluster inside my company. I use LDAP (MS Active Directory) for AuthC and Groups.

### Environment:
My instance of Spinnaker is running on Kubernetes

### Feature Area: 
Service Accounts, Pipeline Permissions

### Description:
While Fiat Service Accounts are not supposed to be tied to the backend being used for Authentication (in our case, LDAP), we are finding that we cannot create a service account and sync it. Attempting to do that causes 500 Server Error and Null Pointer Exception in the Fiat logs. However, if the Service Account is created with a name that matches an LDAP user, it works fine. Tying Fiat Service Accounts to the Authentication backend User source seems like a bug to me

### Steps to Reproduce:
Here's how you can reproduce it. I am sure this issue will show up with other Group Providers as well, but I have only tested this where the Group Provider is LDAP Groups:

I create a service account using the following command:
```
curl -X POST \
  -H "Content-type: application/json" \
  -d '{ "name": "testsa@managed-service-account", "memberOf": ["code-phwhitin"] }' \
  $FRONT50/serviceAccounts | jq .
```
It successfully creates the service account, as this API call confirms it:
```bash
curl -s $FRONT50/serviceAccounts | jq .
```
Now, `code-phwhitin` is an LDAP group with just one LDAP user (`phwhitin`). Before creating this service account, this user did not have access to any Fiat Service Account. 

Since I am not sure if the sync command is mandatory after creating a new service account, I decided to run this command to see if the new service account `testsa@managed-service-account` got added to the user `phwhitin`:
```bash
curl -s $FIAT/authorize/phwhitin | jq .
```
Turned out, it did not. So, I dutifully run the sync command:
```bash
curl -X POST $FIAT/roles/sync
```
This command fails with this error:
```bash
{
  "timestamp" : 1538008639775,
  "status" : 500,
  "error" : "Internal Server Error",
  "exception" : "java.lang.NullPointerException",
  "message" : "No message available"
}
```
I see the following errors in Fiat log. I have only shown a snippet of it.
```bash
spin-fiat-6b96d6447f-8vfx7 fiat 2018-09-27 00:37:19.725  INFO 1 --- [0.0-7003-exec-6] c.n.s.fiat.controllers.RolesController   : [] Full role sync invoked by web request.
spin-fiat-6b96d6447f-8vfx7 fiat 2018-09-27 00:37:19.743  INFO 1 --- [0.0-7003-exec-6] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced anonymous user role.
spin-fiat-6b96d6447f-8vfx7 fiat 2018-09-27 00:37:19.774 ERROR 1 --- [0.0-7003-exec-6] c.n.s.f.r.ldap.LdapUserRolesProvider     : [] Unable to find a single user entry
spin-fiat-6b96d6447f-8vfx7 fiat org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
spin-fiat-6b96d6447f-8vfx7 fiat 	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntryInternal(SpringSecurityLdapTemplate.java:361)
spin-fiat-6b96d6447f-8vfx7 fiat 	at org.springframework.security.ldap.SpringSecurityLdapTemplate$3.executeWithContext(SpringSecurityLdapTemplate.java:318)
spin-fiat-6b96d6447f-8vfx7 fiat 	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:817)
...
```
You can see the full error log [here](https://s3.amazonaws.com/us-east-1-anand-files/spinnaker-fiat-npe-error-log.txt)

I was hoping this error would be benign and that upon running the API, the service account `testsa@managed-service-account` added to `phwhitin`

```bash
curl -s $FIAT/authorize/phwhitin | jq .
```
it did not. :frowning_face:

As I said earlier, if the service account name actually matches an actual LDAP user in our LDAP server, the sync API call works like a charm. And therein lies our problem. _We **really** do not want to find ourselves being forced to create an LDAP user for every single Fiat Service account we create._

### Additional Details:
Any ideas how we can bypass this without creating an actual LDAP user.

---

**Comment by indrayam** [comment]
Awesome! Thanks for taking this on @dibyom 

Btw, do you think the Pipeline Permissions feature uses the same "sync" logic internally? The one that is throwing the NPE issue.

I might have to confirm this again, but I could swear that the other day when I turned "Pipeline Permissions" on, I was able to:

1. Create a Pipeline
2. Add a bunch of LDAP groups to it
3. Noticed that Fiat Service Account was created behind-the-scenes with the right `memberOf` entries and
4. This is the part I need to double-check, but I thought that the LDAP users who belonged to all the LDAP groups added to the Service Account did show the new account when I called the following API with their LDAP User ID:

```bash
curl -s $FIAT/authorize/<ldap-user> | jq .
```

That said, Pipeline Permissions did not work for us either. Meaning, users who should have had WRITE access to the Pipeline based on the LDAP Groups configured actually did not.

The reason I thought I would share this is because I personally have not been able to make the 4th bullet point above work when I created the Service Account using Fiat APIs.

Anyways, thought you might find this nugget interesting as you try to fix the issue. Again, feel free to ping if you need any help.

**Comment by indrayam** [comment]
@dibyom Let me share the easy stuff first. Will send you the debug log soon.

My `fiat-local.conf`:

```bash
auth:
  groupMembership:
    service: LDAP
    ldap:
      roleProviderType: LDAP
      url: ldap://...:...
      managerDn: ....
      managerPassword:
      groupSearchBase: OU=Standard,OU=Cisco Groups,dc=cisco,dc=com
      groupSearchFilter: (member={0})
      groupRoleAttributes: cn
      userSearchFilter: (&(objectClass=user)(|(distinguishedName=CN={0}, OU=Generics, OU=Cisco Users, DC=cisco, DC=com)(distinguishedName=CN={0}, OU=Employees, OU=Cisco Users, DC=cisco, DC=com)))
      userSearchBase: OU=Cisco Users,DC=cisco, DC=com
  enabled: true
```
My `gate-local.conf`:

```bash
ldap:
  enabled: true
  url: ldap://...:...
  managerDn: ...
  managerPassword:
  userSearchFilter: (&(objectClass=user)(|(distinguishedName=CN={0}, OU=Generics, OU=Cisco Users, DC=cisco, DC=com)(distinguishedName=CN={0}, OU=Employees, OU=Cisco Users, DC=cisco, DC=com)))
  userSearchBase: OU=Cisco Users,DC=cisco, DC=com
```

**Comment by indrayam** [comment]
Hey @dibyom 

Here are the steps that I ran:
- I added `fiat.yml` to `~/.hal/default/service-settings`:
```bash
env:
  JAVA_OPTS: "-Dlogging.level.com.netflix.fiat=DEBUG"
```
- Ran `hal deploy apply`
- Waited for all the Pods to come up
- Split my iTerm2 terminal and ran the `stern --tail 1 spin-fiat` command
- Ran `kubectl exec...` to get inside a debug pod that I run inside the Spinnaker cluster. Once in, I executed the `curl -X POST $FIAT/roles/sync` command
- The logs generated, which I have to confess did not look too dissimilar from what I shared yesterday, is uploaded [here](https://s3.amazonaws.com/us-east-1-anand-files/spinnaker-fiat-npe-error-log-version-2.txt)

Let me know if this does not look right.

**Comment by indrayam** [comment]
@dibyom Just checking in. Any updates?

**Comment by dibyom** [comment]
Looks like for DEBUG logging, the `JAVA_OPTS` has to be 
`-Dlogging.level.com.netflix.spinnaker.fiat=DEBUG`

Could you switch the property and attach the log again?

**Comment by dibyom** [comment]
Looks like the is that the issue only occurs if  `userSearchFilter` is present: https://github.com/dibyom/fiat/blob/3121bed1c1dcb215a7c9f38174f29a0eb94ece3b/fiat-ldap/src/main/java/com/netflix/spinnaker/fiat/roles/ldap/LdapUserRolesProvider.java#L116

**Comment by indrayam** [comment]
Ah, great catch @dibyom That said, we in our company will definitely not be able to get around using userSearchFilter setting in our `fiat-local.yml` as the user groups are split across two OUs:

```bash
auth:
  groupMembership:
    service: LDAP
    ldap:
      roleProviderType: LDAP
      url: ldap://ds.cisco.com:3268
      managerDn: <userid>
      managerPassword: <password>
      groupSearchBase: OU=Standard,OU=Cisco Groups,dc=cisco,dc=com
      groupSearchFilter: (member={0})
      groupRoleAttributes: cn
      userSearchFilter: (&(objectClass=user)(|(distinguishedName=CN={0}, OU=Generics, OU=Cisco Users, DC=cisco, DC=com)(distinguishedName=CN={0}, OU=Employees, OU=Cisco Users, DC=cisco, DC=com)))
      userSearchBase: OU=Cisco Users,DC=cisco, DC=com
  enabled: true
```

Btw, we actually came across another scenaro that will lead to the same NPE issue. Here's how this scenario came about:

1. An employee (LDAP user) was actively interacting with our Spinnaker instance
2. He then left the company, so as part of the standard HR process, his LDAP account got disabled
3. No surprises, suddenly the Ops folks found that the Fiat Sync API started failing, not too dissimilar from what was happening with Service Accounts that do not exist in LDAP

Unfortunately, in a company of a decent size, people come and go all the time. This issue, along with mandating that a Fiat Service account be part of LDAP, is going to cause a lot of heartburn for Spinnaker Ops people.  These folks will have to constantly monitor the user entries in the Redis SET with key `spinnaker:fiat:users` and remove the ones that are no longer active in LDAP

Do you still want me to send you the DEBUG logs?

Anand

**Comment by dibyom** [comment]
I'm working on a fix that should resolve both of these situations. And I don't think the DEBUG logs are needed anymore.

**Comment by smuthuswamy** [comment]
Hey @dibyom, Thanks for the fix. @indrayam and I are working on the same project. We would like to test this fix in our dev environment. Is there a docker image/tag created for this fix? 
Thanks!

**Comment by indrayam** [comment]
Sorry, @dibyom Saw your Slack message a bit late in the evening. Ping me on Slack anytime tomorrow if you would like me to have a go at your fix. More than happy to do a Google Hangout too, if needed. Btw, @smuthuswamy and i are both based in EST time zone. FYI

**Comment by dibyom** [comment]
Additional NPE that we need to handle: https://gist.github.com/dibyom/022dfe10142583057fcd9c835c552d94

**Comment by dibyom** [comment]
Fixed in https://github.com/spinnaker/fiat/pull/269

Thank you for debugging and contributing the fix @smuthuswamy and @indrayam !

@emptywee you can this out now!

**Comment by emptywee** [comment]
Will test today and report back with the outcome. Great job so far!

**Comment by indrayam** [comment]
Thanks, @dibyom, and @emptywee The pleasure was really all ours!

😄

**Comment by emptywee** [comment]
Happy to confirm it's working very well in my case. Roles are synced and applied to users correctly, and service accounts are available to use in triggers if roles match.

**Comment by smuthuswamy** [comment]
Thanks @dibyom and @emptywee for your support in releasing this fix! Appreciate your time.
