### ISSUE TITLE
Feature: Accept Artifacts From Jenkins Trigger Property File

### ISSUE THREAD

**Issue by brantburnett** [spinnaker/spinnaker#3401]
### Issue Summary:
Jenkins stages can output artifacts from property files, but Jenkins triggers currently cannot.  Currently only build file artifacts are processed, but not other artificats like Docker images which could be included in a property file.

### Feature Area: 
Pipelines

### Description:

If I output this YAML file as a build artificate named `properties.yaml`:

```yaml
artifacts:
- type: docker/image
  reference: btburnett3/repo:tag
  name: btburnett3/repo
  version: tag
```

And configure a Jenkins trigger on a pipeline to read `properties.yaml`, I'd like the artifacts attribute to be processed as artifacts by the pipeline.

For manual triggers or triggers without artifact constraints, this is relatively easy to do with a minor change to Orca after it gets the properties from Igor.  However, for triggers with artifact constraints the constraint is processed in Echo.  This means that Echo needs to be aware of the properties file, which it currently is not.  This may require adding more information to the BuildEvent fired by Igor which is handled by Echo, or changing the architecture to allow Echo to also call Igor to request the build properties.

**Comment by brantburnett** [comment]
This orca commit handles manual triggers as well as triggers without artifact constraints: https://github.com/brantburnett/orca/commit/187636f4dca10751d6dd32bd84bb11537dd45f65

It may warrant some handling for artifacts with duplicate names, unsure about that.

**Comment by brantburnett** [comment]
@ezimanyi That plan sounds great, it makes sense to wait to implement anything until after triggers are fully inflated in echo to avoid conflicts. Is there anything I can do to assist?

**Comment by ezimanyi** [comment]
A lot of the work that I noted in my above comment has been merged---I'm working now on writing some documentation on it.  Briefly:
* Manual triggers not go through Echo (and thus fully inflate triggers before checking artifact constraints) assuming the `triggerViaEcho` deck feature toggle is set to `true`
* Echo can now run Jenkins triggers through a Jinja template to extract artifacts.  This works currently by configuring echo with:
```
artifacts:
  templates:
  - name: my-template
    templatePath: [ path to template ]
```
and then using a property file in Jenkins to pass `messageFormat=my-template` to the pipeline.

**Comment by brantburnett** [comment]
@ezimanyi I'm assuming this feature toggle will be available in 1.11? If so, I'll probably wait until then to experiment with it. Since we're a Windows shop, I haven't had any luck getting a test cluster running locally to work with.  Minikube is just too problematic on Windows.

**Comment by ezimanyi** [comment]
@brantburnett : The toggle I noted is actually present in 1.10, but none of the other work to enable artifact templates is.  (Turning that toggle on in 1.10 makes manual executions go through echo, which should have no visible effect.)  The bulk of this work will land in 1.11---I'd definitely be interested in your feedback if you get a chance to test this in 1.11.

**Comment by brantburnett** [comment]
@ezimanyi I was able to get this working for the most part. Took me a little bit to figure it all out. Below are my notes about the difficulties I had. You may have some simple workarounds for them, or they may be ideas for improvements.

1. I've been unable to determine how to add a custom template via Halyard. I've tried creating an `echo` directory within `profiles`, similar to how Packer scripts are handled, but that didn't work.
2. I'm getting my properties file from Jenkins as YAML, which is a bit more robust than the key/value pair property files.  In this case, `customFormat` must be `"true"`, and cannot be `true`, because the value is being typecast to a string.  If it's a boolean, it throws an exception.  Accepting both would be nice. https://github.com/spinnaker/echo/blob/master/echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/postprocessors/ArtifactPostProcessor.java#L115-L116
3. For simplicity, I'm trying to provide the list of artifacts within my YAML properties file, already hydrated.  Unfortunately, the `tojson` Jinja filter doesn't appear to work in this Jinja flavor, meaning I can't just iterate the list and output whole objects, I have to know which properties to expect.

    ```yaml
    artifacts:
    - type: docker/image
      reference: us.gcr.io/my-app/my-repo:spinnaker-48
      name: us.gcr.io/my-app/my-repo
      version: spinnaker-48
    messageFormat: basicArtifacts
    customFormat: 'true'
    ```

    ```json
    [
      {% for artifact in properties.artifacts %}
      {{ artifact|tojson }}{% if not loop.last %},{% endif %}
      {% endfor %}
    ]
    ```

4. A standard filter that can pull a Docker reference string from properties and convert it to to a Docker artifact would also be nice, as another way to approach this.

**Comment by ezimanyi** [comment]
@brantburnett : Thanks for testing this out and giving feedback!

1. I've just recently added Halyard commands for this, though they aren't in an official Halyard release yet.  As of Halyard 1.14, you'll be able to do: `hal config artifact templates add ez-test --template-path /path/to/template`, where the path is any local file on the machine running Halyard.
2. Great point, I'll look into fixing that, which should be easy
3. Looks like we're using an older version of jinjava; we should probably upgrade this, which would add `tojson` support.
4. Good idea, that should be easy to add

**Comment by brantburnett** [comment]
@ezimanyi I was able to use the nightly build of Halyard to deploy the artifacts, seems to work fine. I think at this point I'll close this issue as fixed, as my other points were basically just ideas for improvements. Thanks for all of your help.

Also, I'm glad to help out with some of the simpler improvements above, especially if there's any info floating around about how to do local development on a Windows machine.  I've never been able to get minikube working right.

Thanks,
Brant

**Comment by ezimanyi** [comment]
I've just linked two PRs above that address points 2 and 3 above.

Unfortunately I'm not aware of any info on how to develop against Spinnaker on a Windows machine; I'm not sure if anyone has successfully set that up.  That being said, point (4) above to add a standard template for a docker image would probably be reasonably easy to do without a full development setup.  (Would probably just involve generalizing a custom template you write for that purpose and upstreaming it.)
