### ISSUE TITLE
Patch (Manifest) UI incorrectly validates JSON patch as YAML

### ISSUE THREAD

**Issue by tillig** [spinnaker/spinnaker#3418]
### Issue Summary

When trying to use the Patch (Manifest) task to apply a JSON patch to a Kubernetes resource the UI incorrectly attempts to validate text contents as YAML, resulting in the inability to save changes to the pipeline for that step.

### Cloud Provider(s)

Google Kubernetes Engine

### Environment

Spinnaker deployed to GKE running deployments into the same cluster.

### Feature Area

UI, Kubernetes v2

### Description

I expect JSON patch types (patch types "json" and "merge") provided as text (not artifacts) to be validated as JSON (or not validated at all) and allowed to be saved into the pipeline.

### Steps to Reproduce

1. Add a "Patch (Manifest)" stage to a pipeline.
2. Set the "Merge Strategy" to "json"
3. Set the "Manifest Source" to "Text"
4. Enter a valid JSON Patch document into the text box. Sample below.
5. Notice the message "Invalid YAML" appears and the "Save Pipeline" button isn't available to save the changes.

Simple JSON patch doc (from the [JSONPatch site examples](http://jsonpatch.com/)):

```json
[
  { "op": "replace", "path": "/baz", "value": "boo" },
  { "op": "add", "path": "/hello", "value": ["world"] },
  { "op": "remove", "path": "/foo" }
]
```

### Additional Details

Screenshot of behavior:

![JSON patch being validated as YAML](https://user-images.githubusercontent.com/1156571/46435255-c85df000-c70a-11e8-92a6-8771951d5438.png)

**Comment by tillig** [comment]
You also are unable to specify the JSON patch contents as YAML. For example:

```yaml
- op: add
  path: /hello
  value: hi
```

This translates to the JSON patch document:

```json
[{
  "op": "add",
  "path": "/hello",
  "value": "hi"
}]
```

However, if you enter the YAML into the text box it's still seen as invalid YAML; and if you manually hack the JSON patch into the pipeline JSON then trying to run the patch step yields this exception:

`Cannot deserialize instance of com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifest out of START_ARRAY token at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesPatchManifestDescription["patchBody"])`

**Comment by tillig** [comment]
Note I'm using JSON patch because I'm trying to patch Istio resources and [Kubernetes didn't extend strategic merge patches (YAML) to custom resource definitions](https://github.com/kubernetes/kubernetes/issues/58414). Istio virtual services, gateways, and other entities are all custom resources.

**Comment by lwander** [comment]
This bug will change with 1.10, where we added a proper yaml editor in place of a text box. Although I think the result will be the same.

@dibyom FYI

**Comment by danielpeach** [comment]
Is this purely a UI issue? From what you're saying, it sounds Clouddriver is rejecting the patch even if the patch content is encoded into the pipeline JSON as you expect.

**Comment by tillig** [comment]
@danielpeach Agreed, I don't think it's just UI. I just hit it with the UI and then tried / failed to work around it. Ostensibly if the JSON patch format is allowed, the UI should allow it... but also Clouddriver should allow it.

**Comment by dibyom** [comment]
@maggieneterval

**Comment by lwander** [comment]
Safe to close?

**Comment by maggieneterval** [comment]
Yes, closing!
