### ISSUE TITLE
Application page not listing applications when Fiat is enabled (RC)

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#3425]
### Issue Summary:

After upgrading to the current RC version (release-1.10.x-latest-unvalidated) the Applications- page which lists all applications available does not list the applications which have permissions enabled - even though the user has permissions to the application. Also, when accessed the application directly with browser - the application opens (no 404 happens) - so the issue might be only on this application-page's list.

### Cloud Provider(s):

All of them.

### Environment:

Current release candidate at time of writing (release-1.10.x-latest-unvalidated).

### Feature Area: 

UI (Deck)

### Description:

Accessing the application-page shows an empty list (no applications).

### Steps to Reproduce:

1. have Fiat enabled (we are using it with SAML + SAML groups)
2. upgrade to the current RC version (release-1.10.x-latest-unvalidated)
3. open the Applications-page + witness all the applications missing from the list (only those which have permissions enabled)

### Additional Details:

Unfortunately we get no errors to log with INFO log level. I'll raise to DEBUG later and see if we'd get something nice out.

**Comment by ezimanyi** [comment]
I just ran into this as well, I believe it is caused by https://github.com/spinnaker/gate/pull/603

I think what's happening is that the thread to refresh the cache of applications isn't authenticated to front50, and so only receives back applications that don't have any read permissions.

@ajordens , mind taking a look?

**Comment by danielpeach** [comment]
@ajordens - could you please take a look? This is blocking the release of Spinnaker 1.10.

**Comment by ajordens** [comment]
Sorry this went into the blackhole of github notifications it would seem. '

Move the revert forward and I'll revise. Pointed out a hole in the previous fallback behavior which would have also only returned public applications.

**Comment by danielpeach** [comment]
Awesome, thank you.
