### ISSUE TITLE
Triggering by Google Pub/Sub broken after upgrading to the RC

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#3426]
### Issue Summary:

After upgrading to the release candidate version (release-1.10.x-latest-unvalidated) - the pipelines which has a Google Cloud Pub/Sub trigger do not trigger anymore.

### Cloud Provider(s):

AWS (at least)...

### Environment:

Spinnaker version release-1.10.x-latest-unvalidated (at time of writing), running on top of GKE in GCP.

### Feature Area: 

Pipelines (triggering)

### Description:

For some reason - after the upgrade to RC - pipelines with a Google Cloud Pub/Sub trigger do not work anymore.

### Steps to Reproduce:

1. upgrade Spinnaker to RC (release-1.10.x-latest-unvalidated)
2. try to trigger a pipeline which has a auto-trigger enabled with a Google Cloud Pub/Sub -> nothing happens

### Additional Details:

Unfortunately the INFO level logging does not reveal anything. I'll try to raise the logging level to DEBUG later so we could get some facts on what's actually happening.

**Comment by danielpeach** [comment]
Could you please clarify which pubsub system you're using? You mention that you're deploying to AWS but running Spinnaker on GCP. Is this Google PubSub?

**Comment by iniinikoski** [comment]
@danielpeach sorry for the misinfo - updated the original issue - yes it's Google Cloud Pub/Sub - although deploying to AWS.

**Comment by lwander** [comment]
This is a config issue, and fixed in the latest halyard nightly release -- we just need to release a stable halyard (will be 1.11), pin the minimum halyard version to 1.11 during the release, and then we can safely close this.
