### ISSUE TITLE
[Halyard] Enabling HA (High Availability) for clouddriver is not working

### ISSUE THREAD

**Issue by j-sandy** [spinnaker/spinnaker#3440]
### Issue Summary:
Halyard cannot able to deploy HA for clouddriver, even though it is being enabled in .hal/config as per the given document.
https://www.spinnaker.io/reference/halyard/high-availability/#ha-clouddriver

### Cloud Provider(s):
Kubernetes V2

### Environment:
Spinnaker 1.9.5 [Distributed]
Halyard 1.10.1-20180912131447

### Feature Area: 
Halyard

### Description:
After enabling clouddriver HA as per the document (https://www.spinnaker.io/reference/halyard/high-availability/#ha-clouddriver) along with providing external redis endpoint. While deploying spinnaker received the below error:
---------
Problems in Global:
! ERROR Unable to retrieve profile "clouddriver-caching.yml": 401
  Unauthorized
Anonymous caller does not have storage.objects.get access to
  halconfig/clouddriver/3.4.5-20180927041608/clouddriver-caching.yml.

- Failed to deploy Spinnaker.
--------------
### Steps to Reproduce:
Follow the document for enabling clouddriver HA:
1. hal config deploy ha clouddriver enable
2. hal config deploy ha clouddriver edit --redis-master-endpoint $REDIS_MASTER_ENDPOINT --redis-slave-endpoint $REDIS_SLAVE_ENDPOINT
3. sudo hal deploy apply 

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by lwander** [comment]
This is only enabled for spinnaker 1.10 or greater, I will close this for now.
@joonlim fyi
