### ISSUE TITLE
`yaml` in Azure OAuth documentation does not work, change to `yml`

### ISSUE THREAD

**Issue by vuza** [spinnaker/spinnaker#3448]
### Issue Summary:

I'm unable to use Azure as OAuth provider following the given instructions: https://www.spinnaker.io/setup/security/authentication/oauth/providers/azure/

### Description:

After I followed https://www.spinnaker.io/setup/security/authentication/oauth/providers/azure/ I'd expect Spinnaker to successfully communicate with Azure's OAuth. Instead I get `Requested tenant identifier '${azuretenantid}' is not valid.` prompted by Azure.

#### Solution:

After some digging in I fond the solution. The instructions at https://www.spinnaker.io/setup/security/authentication/oauth/providers/azure/ ask you to create a `~/.hal/default/service-settings/gate.yaml` which does not get read by Halyard. After changing `yaml` to `yml` the environment config got applied to `history/service-settings.yml` and authenticating towards Azure! Please change `Add the following to ~/.hal/default/service-settings/gate.yaml:` to `Add the following to ~/.hal/default/service-settings/gate.yml:`

**Comment by vuza** [comment]
Might be related:

- https://stackoverflow.com/questions/49177392/attempting-to-setup-oauth2-for-azure-error-instead-of-login-page
- https://github.com/spinnaker/spinnaker/issues/2519

**Comment by jtk54** [comment]
Care to submit a pull request with the docs fix?

**Comment by vuza** [comment]
done https://github.com/spinnaker/spinnaker.github.io/pull/1052
