### ISSUE TITLE
feat(sponnet): Extend JSONNET library with additional pipeline options

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#3456]
### Issue Summary:

[Sponnet demo](https://github.com/spinnaker/spinnaker/tree/master/sponnet/demo) has initial support for creating pipelines with `Wait` and  `Deploy Manifest` stages.
This is a great start.
It would be nice to extend this with additional pipeline stages, configuration options, execution options, etc.

I have found using MPT? YAML pipelines with partials and multiple levels of inheritance to be fragile and difficult to manage compared with what JSONNET provides.

### Cloud Provider(s):

Kubernetes for now.

### Environment:

1.9.5 on Kubernetes using V2 provider for applications.

### Feature Area: 

sponnet: pipeline templates with JSONNET

### Description:

Expect to be able to create json pipeline definitions with all features available in Deck UI.
Currently can only create json pipeline definitions with `Wait` and `Deploy Manifest (text)` stages.

### Steps to Reproduce:

Try to create a pipeline.json file for demo app with triggers and stages using artifacts.

### Additional Details:

Have started extending this in [my fork of spinnaker repo](https://github.com/kskewes/spinnaker/commit/c3b8f4b72ab14b3369d626f121fb2ce5f1a23be3#diff-16290c192c8881156d617597a2ef886b) and looking for guidance as to whether this would be acceptable for a PR and additional stylistic, structural and general guidelines/improvements.

I understand pipeline templates methodology has been under discussion for some time and that maintaining 'sponnet' would be somewhat duplicating API in areas.

I'm happy to maintain my own library and/or submit PR's and assist with any related issues. I don't have access to the full gamut of providers that Spinnaker support though.

**Comment by kskewes** [comment]
In addition to above I plan to use jsonnet to create and manage Application connfigs and Project configs.

**Comment by lwander** [comment]
Awesome! Can you open a PR? Let's collaborate to build the sponnet library together so you don't have to worry about throwing away what's built already.

**Comment by kskewes** [comment]
Sure, thanks, added.
