### ISSUE TITLE
SSL Setup: Gate Readiness probe failed: ssl_client: localhost: certificate verification failed: unable to get local issuer certificate wget: error getting response: Connection reset by peer 

### ISSUE THREAD

**Issue by alex25555** [spinnaker/spinnaker#3473]
### Issue Summary:
We've followed the procedure to setup a self signed cert using instructions outlined here, https://www.spinnaker.io/setup/security/authentication/ssl/. However, the Gate service fails after applying the Hal configs via `hal deploy apply` with "Gate Readiness probe failed: ssl_client: localhost: certificate verification failed: unable to get local issuer certificate wget: error getting response: Connection reset by peer". The Gate service can't locate the cert because it sees no cert. We followed through on each step as outlined to setup SSL via a self signed cert successfully. We don't know how to troubleshoot this further. Any help would really be appreciated. Thank you
security:
apiSecurity:
ssl:
enabled: true
keyAlias: spinnaker
keyStore: /home/username/.hal/certs/keystore.jks
keyStoreType: jks
keyStorePassword: xxxxxxxxxx
trustStore: /home/username/.hal/certs/keystore.jks
trustStoreType: jks
trustStorePassword:xxxxxxxxxx
overrideBaseUrl: https://xxxxxxxxxx:8084
uiSecurity:
ssl:
enabled: true
sslCertificateFile: /home/username/.hal/certs/server.crt
sslCertificateKeyFile: /home/username/.hal/certs/server.key
sslCertificatePassphrase: xxxxxxxxxx
overrideBaseUrl: https://xxxxxxxxxx:9000
### Steps to Reproduce:
Follow the steps to generate a self signed certification and setup SSL
https://www.spinnaker.io/setup/security/authentication/ssl

**Comment by alex25555** [comment]
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get BOM for 1.9.5
  Success
version: 1.9.5
timestamp: '2018-09-29 08:16:14'
services:
  echo:
    version: 2.0.1-20180817041609
    commit: c52ac8a652d61470ca5a0ad772932f3025f5434f
  clouddriver:
    version: 3.4.5-20180927041608
    commit: a1487014a21d456f4bf59873e0acd13de3a7c835
  deck:
    version: 2.4.3-20180926041608
    commit: b66f7fe282edb3bdeafed23f583dbd0f4c6cf827
  fiat:
    version: 1.0.1-20180829141913
    commit: 2c8212dbceeffb44c056e53ba956b49ada7e1c21
  front50:
    version: 0.12.0-20180802022808
    commit: 13c2f19d1e541e25f1d9c72e96941d6cf8bd77bc
  gate:
    version: 1.1.3-20180929041608
    commit: 95b28a6207a23528aa61478395b454db0da19495
  igor:
    version: 0.12.0-20180726022808
    commit: 12641e2de0d540dd9207f5f5707fdb831a4fe8e4
  kayenta:
    version: 0.3.0-20180724022806
    commit: 3f7ed7017948bc2da770fc91d20993539d21981c
  orca:
    version: 1.0.2-20180927041608
    commit: ec84726c3d1d9c8820be543529d8765ec44b620f
  rosco:
    version: 0.7.3-20180818041609
    commit: c057c1d4372c54a0f6d03ec6532fcfbbc9aafcb2
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.8.1-20180925041608
    commit: 1b2c9a294a36c3875edbbddcec264c4036e64e7a
  monitoring-daemon:
    version: 0.8.1-20180925041608
    commit: 1b2c9a294a36c3875edbbddcec264c4036e64e7a
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker

**Comment by vkvamsiopsmx** [comment]
Hi Alex,

I'm also facing the same issue, can you help me with the fix if you got any for the same.

**Comment by aleon1220** [comment]
> Hi Alex,
> 
> I'm also facing the same issue, can you help me with the fix if you got any for the same.

what halyard version do you have?

**Comment by vkvamsiopsmx** [comment]
My HAL Version is 1.32.0
