### ISSUE TITLE
Rollback is not working in Spinnaker, terminate a container instance timeout in log..

### ISSUE THREAD

**Issue by DockerAsura** [spinnaker/spinnaker#3512]
### Issue Summary:
Rolling back to previous version is not working, after new version not healthily, New pod is in terminating state not moving forward and later timeout.  retains the both versions in k8s cluster 

### Cloud Provider(s):
Kubernetes : 1.9.1

### Steps to Reproduce:
New version pushed to docker-hub, Automatic triggers on spinnaker.

**Comment by sbwsg** [comment]
Please include a sanitized copy of your halyard configuration:

```
hal config -q --no-validate
```

And copy/paste any error messages from your clouddriver logs into this issue.

**Comment by DockerAsura** [comment]
The was on K8S cluster, not sync with AWS ASG.
