### ISSUE TITLE
Issue with deck when using function in patch/find manifest from V2 provider 

### ISSUE THREAD

**Issue by rverma-nikiai** [spinnaker/spinnaker#3513]
### Issue Summary:
When used a variable in Resource to patch or Find Artifacts From Resource (Manifest) Configuration
Pipeline Step, Name configuration on opening the pipeline again its lost, also the pipeline start showing error.

### Cloud Provider(s):
Kubernetes v2

### Environment:
Spinnaker 1.10.0 installed via Halyard
Spinnaker 1.10.1 installed via Halyard

### Feature Area: 
deck
clouddriver
Pipelines, UI

### Description:
When used a variable in Resource to patch orFind Artifacts From Resource (Manifest) Configuration
  Pipeline Step, Name configuration on opening the pipeline again its lost, also the pipeline start showing error.
This was working fine till 1.9.5

### Steps to Reproduce:
Create a Project Dashboard
Under Applications, add any application
In Application create a parameter say stack and add a pipeline step Resource to patch Pipeline or 
Find Artifacts From Resource (Manifest) Configuration.
In Name try to put Name like a-${parameters.stack}
Save.
Open the pipeline again and you will find the step in error state with Name missing.

In the dashboard view you should see the error 'No clusters found for selected region/namespaces'

### Additional Details:
<img width="1217" alt="screenshot 2018-10-26 at 12 54 45 pm" src="https://user-images.githubusercontent.com/38323616/47551243-4d5db300-d91f-11e8-873c-498b22546bbc.png">

---

**Comment by rverma-nikiai** [comment]
@maggieneterval Can we prioritise this as this makes complete pipeline unusable if we have any of those stages.
Thanks

**Comment by rverma-nikiai** [comment]
@maggieneterval this issue is kind of blocker for us. Can you point me in the direction where I can figure out the issue and create a relevant pull request.
Thanks

**Comment by MrBlaise** [comment]
The same thing is happening with Find Artifacts From Resource (Manifest) stage. @rverma-nikiai As a workaround you can try editing the pipeline as JSON while you are *NOT* on the Patch stage and save it. Whenever you click on the stage the UI will revert it again just don't save it.

**Comment by maggieneterval** [comment]
@rverma-nikiai Apologies for the delayed followup, this is still on my todo list -- I am happy to take a look today, and in the meantime thanks for the helpful workaround @MrBlaise!

**Comment by maggieneterval** [comment]
@rverma-nikiai This fix will go out with the 1.10.4 release.

**Comment by maggieneterval** [comment]
@MrBlaise thanks for testing the fix, good catch -- I think my fix only resolved the issue with the `name` field per rverma-nikiai's issue, but I will check out the `namespace` field as well. There is also a design audit happening to hopefully land on a better way to handle expression inputs across the application.

**Comment by maggieneterval** [comment]
This will go out with the next patch release: https://github.com/spinnaker/deck/pull/6028
