### ISSUE TITLE
Docker registry trigger UI (deck) fails to show organization and images

### ISSUE THREAD

**Issue by MrBlaise** [spinnaker/spinnaker#3514]
### Issue Summary:
Using the latest spinnaker version 1.10.1 the UI (deck) fails to show the docker images and the organization.
When executing `curl http://spin-clouddriver.spinnaker:7002/dockerRegistry/images/find?account=gcr` manually returns all the images properly. It used to work in 1.9

### Cloud Provider(s):
Google Cloud

### Additional Details:

![image](https://user-images.githubusercontent.com/3867275/47562889-5307c880-d920-11e8-908f-8a12725333dd.png)

EDIT:

### Workaround:

- Add the trigger and save the pipeline.
- Pipeline actions -> Edit as JSON
- Manually update organization at the `triggers` section in the docker registry config
- Save
- Images now show up

**Comment by MrBlaise** [comment]
I am not familiar with React but the problem might be here: https://github.com/spinnaker/deck/blob/release-1.10.x/app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx#L319

My guess is that in this line the `onClick={this.handleRefreshImages}` part is the cause. The reason is that in javascript on an event this will point to the element that created the event, not the actual component unless React hides this. In Angular, I would use `(click)`

**Comment by maggieneterval** [comment]
Hi Balázs, thanks for reporting this issue! You're exactly right about the `this` binding -- just put in a PR to address this.
