### ISSUE TITLE
Add ServerGroupManager name clickable representation in Clusters screen

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#3516]
### Issue Summary:

We've had reports that the ServerGroupManager rendering in clusters view does not communicate the fact that it is clickable in the same way that ServerGroups and Instances do.

Including the ServerGroupManager's name (a pairing of k8s kind + resource name ala "deployment my-app") in clickable area would help to make this clearer.

### Cloud Provider(s):

Kubernetes v2

### Feature Area: 

Deck

### Screenshot:

The ServerGroupManager's name appears in the cluster's heading but not in the clickable box that represents it:

![screen shot 2018-10-26 at 11 50 17 am](https://user-images.githubusercontent.com/34253460/47577889-00291380-d916-11e8-8f5c-bb90ced93c47.png)

**Comment by sbwsg** [comment]
@demobox ^

**Comment by demobox** [comment]
> sbwsg closed this in spinnaker/deck#5952

Thanks, Scott!
