### ISSUE TITLE
Add example or aws doc link to Halyard S3 command reference

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#3526]
### Issue Summary:

The S3 [artifact account commands](https://www.spinnaker.io/reference/halyard/commands/#hal-config-artifact-s3-account-add) require the following AWS-specific flags:

```
--api-endpoint: S3 api endpoint
--api-region: S3 api region
--region: S3 region
```

Neither the format for these flags nor a description of where to get the correct values is provided.

An improvement would be to include a very short description for each flag of where to get the values, or a pointer to AWS docs specifically calling out how to retrieve them.

### Cloud Provider(s):

AWS S3

### Feature Area: 

Halyard

**Comment by ethanfrogers** [comment]
Good point @sbwsg. For anyone else who see this, the `api-endpoint` and `api-region` flags are only required if you're using an S3 clone like Minio. Otherwise, just providing the `region` will suffice.

**Comment by jensvdh** [comment]
@sbwsg I did some searching around and ended up here. 

How is access to S3 configured for the S3 artifact account? I can't find any steps anywhere on how to pass in my S3 credentials.

**Comment by jensvdh** [comment]
@sbwsg Yup! Got it to work by passing the creds as ENV variables in clouddriver.yml. Thank you!
