### ISSUE TITLE
Missing clouddriver-ro-deck profile in 1.10.x release

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#3533]
### Issue Summary:
From tony in the chat room:

tony [13 hours ago]
Hi guys, it seems that halyard is trying to pull this file  but it’s getting a 404: https://storage.googleapis.com/halconfig/clouddriver/4.0.0-20181005152808/clouddriver-ro-deck.yml
but it’s able to pull this file fine: https://storage.googleapis.com/halconfig/clouddriver/4.0.0-20181005152808/clouddriver-ro-deck.yml ….any ideas?

There are the clouddriver-caching, -ro, and -rw profiles, but no clouddriver-ro-deck profile. 

### Environment:
HA environments

**Comment by joonlim** [comment]
I fixed this by putting the clouddriver-ro-deck.yml into the gs://halconfig/clouddriver/4.0.0-20181005152808 bucket. I have also gone ahead and put the clouddriver-ro-deck.yml into all the gs://halconfig/clouddriver/* paths starting with 3.5.0-20180827165259.
