### ISSUE TITLE
[Enhancement] Collapse container list in Deck cluster view for pods with large numbers of sidecars

### ISSUE THREAD

**Issue by jensvdh** [spinnaker/spinnaker#3555]
### Issue Summary:
We are deploying quite a few pods with 8+ containers (we use the sidecar pattern extensively). As a result, the Cluster view in Deck gets cluttered very easily.

### Cloud Provider(s):
- K8s V2 provider

### Environment:
- Deck

### Feature Area: 
- Deck Cluster UI

### Description:
When deploying pods with a large number of containers, the UI gets cluttered.

see screenshot:

![spinnaker-proxy_ _clusters](https://user-images.githubusercontent.com/2640481/47946069-1578e180-dec4-11e8-86fb-e2195179fe3e.png)

### Steps to Reproduce:
Deploy a pod with a larger number of containers and sidecars.

### Additional Details:
I'd be more than happy to contribute a solution to this.

My initial thought process is the following:

- If a pod contains a single container, leave as is
- If a pod contains more than 1 container. Show "this pod contains (N) containers. show all" 
- Clicking show all would expand into the full list of pods.

Just wanted to run this by here before I start coding a solution !

**Comment by sbwsg** [comment]
Hey @jensvdh this sounds like a great feature addition & your initial thoughts seem reasonable to me. Reach out to me on Slack, user sbws, if you need pointers into the Deck codebase.

**Comment by jensvdh** [comment]
@sbwsg Sounds good. I'll take an initial stab at it and open a PR against Deck.

We can iterate from there 👍
