### ISSUE TITLE
[Spinnaker-Monitoring] In clouddriver HA services (cloudddriver-caching, clouddriver-ro, clouddriver-rw) monitoring sidecars are sending metric names containing "-", causing Prometheus to reject them.

### ISSUE THREAD

**Issue by j-sandy** [spinnaker/spinnaker#3578]
### Issue Summary:
Prometheus cannot able to detect metric names from clouddriver HA services cloudddriver-caching, clouddriver-ro and clouddriver-rw in Spinnaker 1.10.0 enabled with spinnaker-monitoring-daemon. 

### Cloud Provider(s):
Kubernetes 

### Environment:
Spinnaker 1.10.0 :
- enabled monitoring using Prometheus 
- enabled clouddriver HA

### Feature Area: 
Spinnaker-Monitoring-Daemon

### Description:
Issue is due to "-" used for separating multi-word spinnaker microservice names, while converting to Prometheus compatible metric names. Spinnaker-monitoring sidecar collects the spectator metrics from spinnaker microservice and converts them to auto-discoverable Prometheus compatible metric collection format. Monitoring sidecar prepends microservice name with metric name while exposing the list of metric names to Prometheus. Since Prometheus does not accept "-" in metric name, it throws error as "No Token Found".

### Steps to Reproduce:
Configure spinnaker 1.10.0
- enable clouddriver HA
- enable spinnaker-monitoring-daemon (For details https://www.spinnaker.io/setup/monitoring/prometheus/#prometheus)
Deploy spinnaker and wait for stablizing the deployment.
Access Prometheus logs, it throws error for clouddriver HA services as "No Token Found".

### Additional Details:
Most probable solution is to replace "-" with "_" before prepending the spinnaker microservice name to metric name. This can be acheived by changing the code in prometheus_service.py from :
 
 metric_name = '{service}:{name}'.format(service name=name.replace('.', ':'))

to:
 metric_name = '{service}:{name}'.format(service=service.replace('-', '_'), name=name.replace('.', ':'))

**Comment by ewiseblatt** [comment]
Instead of doing this in prometheus, I am doing this where the service name is determined in the registry itself. For now if chosen this will drop out the config decorator entirely. I'll rework it in the future to be able to chose how to add it back in. This is because I am trying to move to using tags to decorate metrics where the deployment variant would be a tag. However all that is not in place yet, nor would that fix be patchable to current releases.

FYI the registry name comes from the yaml file name in the registry_dir. So another option would be to write out a different name, perhaps using '_' rather than '-'. This is typically controlled by halyard. Nothing else uses that file so I dont forsee negative impact to that.

**Comment by ewiseblatt** [comment]
BTW, the actual fix for this is proposed in https://github.com/spinnaker/spinnaker-monitoring/pull/114. My previous response had assumed that was the cited fix. The removal of '-' would also fix it and retain the fully qualified names.

**Comment by sagnik-opsmx** [comment]
@ewiseblatt  We are still facing issue with Spinnaker 1.10.3 , I think the  fix was provided on
 spinnaker/spinnaker-monitoring#118

But we encountered this error on prometheus : 
Get http://spin-clouddriver-ro:8008/prometheus_metrics: net/http: HTTP/1.x transport connection broken: malformed MIME header initial line: File "/opt/spinnaker-monitoring/bin/http_server.py", line 103, in do_GET

We made change on "prometheus_service.py" mentioned above, from : 
metric_name=  '{service}:{name}'.format(service=service, name=name.replace('.', ':').replace('-', '_'))
to : 
metric_name = '{service}:{name}'.format(service=service.replace('-', '_'), name=name.replace('.', ':')) 

which started scraping the target  for the prometheus.

**Comment by ewiseblatt** [comment]
This should be fixed in https://github.com/spinnaker/spinnaker-monitoring/pull/121
