### ISSUE TITLE
Containers section not available UI

### ISSUE THREAD

**Issue by LakshmiVaishak** [spinnaker/spinnaker#3601]
### Additional Details:
![image](https://user-images.githubusercontent.com/7911059/48474213-1133b900-e820-11e8-962f-2b00bac446e3.png)

---

**Comment by lwander** [comment]
AWS doesn't have a container option, you can only deploy VM images. If you want to deploy to EKS or ECS, I would have a look at the docs
https://www.spinnaker.io/setup/install/providers/kubernetes-v2/aws-eks/
https://www.spinnaker.io/setup/install/providers/aws/aws-ecs/
