### ISSUE TITLE
Orca: Metrics From Manifest Tasks

### ISSUE THREAD

**Issue by Rigdon** [spinnaker/spinnaker#3605]
### Issue Summary:

We would like to see metrics in the spectator endpoint from the Manifest Tasks in Orca. There are a few places where operations are inferred and logged but getting explicit metrics for events [like this](https://github.com/spinnaker/orca/blob/617e47fdb0e6acb4b4a034bde165b6bc2b49f425/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java#L81-L84) could help us when diagnosing issues or working on Orca improvements.

### Cloud Provider(s):

Kubernetes 

### Feature Area: 

Pipelines

**Comment by lwander** [comment]
@ewiseblatt FYI

**Comment by ewiseblatt** [comment]
There is a timer metric called "stage.invocations.duration" that has a stage task. Does that help? It wouldnt count these events directly, but you could see the outliers (although timers do get aggregated across collection cycles so there may be smoothing depending on frequencies).

**Comment by Rigdon** [comment]
Yeah we're already tracking stage durations but want more detailed metrics out of our Kubernetes tasks in general. I'm just adding the spectator registry into this task similar to the way it's done in `MonitorKatoTask`
