### ISSUE TITLE
"Find Image from Tags" stage not available in GUI

### ISSUE THREAD

**Issue by slupers** [spinnaker/spinnaker#3608]
### Issue Summary:
"Find Image from Tags" does not appear as a stage type when creating a new stage in a new or existing pipeline. This stage type also doesn't seem to fully render in UI of the pipelines that already have it, but the stage still works when the pipeline is run.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.10.4 in AWS, installed using Halyard

### Feature Area: 
UI
Deck?

### Description:
Pipelines with this stage already configured continue to function, so it seems to be a UI issue. When looking at an existing pipeline with a "Find Image from Tags" stage, the stage's UI seems to not fully render, while the JSON looks normal and the pipeline continues to work. Also see https://community.spinnaker.io/t/cant-see-find-image-from-tags-in-ui/824

### Steps to Reproduce:
Install Spinnaker 1.10.4 using Halyard, configure AWS provider, create an app in Spinnaker and set cloud provider to AWS, create and configure a pipeline, try to add a "Find Image from Tags" stage

**Comment by rampatnaik** [comment]
I too have same issue .. I am using Spinnaker 1.10.11 in AWS, installed using Halyard .

Is the fix merged to release version??
