### ISSUE TITLE
Missing Jenkins Trigger for CF deployments

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#3617]
### Issue Summary:

Missing Jenkins Trigger for CF deployments.

### Cloud Provider(s):

CF

### Feature Area: 
UI

### Description:

When deploying a new server group from pipelines there is no longer an option to deploy via Jenkins triggers.

Current:
![screen shot 2018-11-19 at 3 28 05 pm](https://user-images.githubusercontent.com/8474965/48733172-c810aa00-ec0f-11e8-8005-af1429bf8ab9.png)

Expected:
![screen shot 2018-11-19 at 3 29 04 pm](https://user-images.githubusercontent.com/8474965/48733216-eecee080-ec0f-11e8-9881-6fcc0994466e.png)

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by okundzich** [comment]
can you align source type to be similar as source type for configuration, to start with artifact:
artifact, trigger, package
