### ISSUE TITLE
Trying to use spinnaker api but unable to authenticate using curl

### ISSUE THREAD

**Issue by ahsannaseem** [spinnaker/spinnaker#3659]
### Issue Summary:
I am trying to use `api` methods to manage spinnaker, creating pipelines if have to be specific. Reason for not using `spin cli` or other tools is plan to launch this automation at `aws lambda`.

### Cloud Provider(s):
AWS, kubernetes

### Environment:
spinnaker 1.9.5

### Feature Area: 
spinnaker api

### Description:
using google oauth and get methods are working fine when using browser. but when try to do same with curl get no response. Wondering whats missing in my curl command.

### Steps to Reproduce:
`curl -X GET "http://spinnaker-api.mydomain.com//applications"
`

would really be grateful I can get some context on this. I think its missing authentication header but wondering what fields should be provided?.

Thanks

**Comment by pravargauba** [comment]
Hey @ahsannaseem .. Did you find the solution? I am facing the same issue.

**Comment by goldiee36** [comment]
just use basic authentication on /login
