### ISSUE TITLE
Deploy status for Kubernetes v2 shows too many resources

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#3661]
I created three parallel stages, each deploying a different namespace & deployment. When I click on the details for any of the three executing stages, all 6 (instead of a single namespace/deployment pair) are shown.

![image](https://user-images.githubusercontent.com/4874941/49163995-49e19100-f2fc-11e8-9053-f42ec6c7b14e.png)

**Comment by sbwsg** [comment]
There's a race condition where a manifest subscription sends an update after the user has switched away from that stage's execution info. Unfortunately the component isn't unmounted when the user switches and so there's no clear moment to unsubscribe from stale subs.  Still looking.

**Comment by sbwsg** [comment]
Fixed in https://github.com/spinnaker/deck/pull/6101
