### ISSUE TITLE
Spinnaker's web UI application tab not working. Localdebian, Minikube

### ISSUE THREAD

**Issue by IAmMichal** [spinnaker/spinnaker#3691]
### Issue Summary:
I'm trying to setup a localdebian spinnaker and have managed to "sudo hal deploy apply" but when I go into the "Applications' tab I see the " Error fetching applications. Check that your gate endpoint is accessible." text. However the endpoint is accessible as the browser I am trying to connect from is the computer the VM is running on.

### Environment:
I run this on a headless ubuntu 16.04 inside VMplayer.
using the kubernetes v2.
Minikube is running as --vm-driver=none inside docker.
Spinnaker is deployed as localdebian.
The VM is using NAT to communicate with the internet.
I've overriden the base api and ui URL's.

### Description:
I can go onto the the spinnaker page on ipaddress:9000 but when I go in the application screen the " Error fetching applications. Check that your gate endpoint is accessible." text is displayed. I have followed the suggested actions on the link provided with no succes.

**Comment by sbwsg** [comment]
This sounds like the UI can't access Spinnaker's API, Gate.  The Gate service runs by default on port 8084.  Can you successfully `curl <ip-address>:8084/credentials` from your terminal?  If you open your browser's developer tools to the Network panel, do you see errors in requests going to Gate?  If not, do you see any errors at all in the browser console?

**Comment by sbwsg** [comment]
OK, so the challenge now is to figure out why Gate isn't responding to requests.

With a LocalDebian deployment you can check the logs of Spinnaker's services by running `journalctl -u gate` (assuming systemd) or by tailing logs in `/var/log/spinnaker/gate/` on older systems (ubuntu 14.04).

Take a look at the end of the Gate log and see if there's an error. If there is then post it in this issue.

**Comment by IAmMichal** [comment]
ERROR 37442 --- [rXiOsCHEDULER-3] c.n.s.gate.services.ApplicationService      : Unable to refresh application list, reason: Task java.util.concurrent.FutureTask@b279bf7 rejected from java.util.concurrent.ThreadPoolExecutor@73d83141[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
Is what I'm given back after running "journalctl -u gate.

**Comment by sbwsg** [comment]
That sounds like a downstream service is having issues.  At this point I suggest taking a look at the logs for `front50`, `orca`, and `clouddriver`. Do you see errors in any of these?

**Comment by IAmMichal** [comment]
Front50:
ERROR 37436 :Internal Server Error at Redis: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool.
orca: 
--No entries --
clouddriver:
ERROR 37437 --- [gentScheduler-1] c.n.s.c.r.c.CLusteredAgentScheduler : Unable to run agents.
redis.clients.jedis.exceptions.JedisConnectionException: could not get a resource from the pool at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.0.jar:na]

**Comment by sbwsg** [comment]
Do you have redis-server running?  You can check with `service redis-server status`. If it's not running then execute `sudo service redis-server restart` and then restart the spinnaker services `clouddriver` and `front50` in the same way.

**Comment by IAmMichal** [comment]
For service redis-server status it says dead and works once restarted.
For front50 and clouddriver it says dead the reason saying that their not found.

**Comment by IAmMichal** [comment]
I ended up changing from Redis to Manio.
With this I no longer have that problem. 
Authentication is now causing trouble but that's another issue.
Thank you for your help.

**Comment by HouJiangtao** [comment]
I meet the same problem, but after I execute the "systemctl daemon-reload". problem solved.
