### ISSUE TITLE
Gate broken on 1.11 in Kubernetes quick install

### ISSUE THREAD

**Issue by MrTrustor** [spinnaker/spinnaker#3732]
### Issue Summary:

I'm working to update the [Kubernetes quick install](https://github.com/spinnaker/spinnaker.github.io/blob/08779c29c5a3bb918e5310c7acf6c8d3af17c0f9/downloads/kubernetes/quick-install.yml) to 1.11. Something seems to have changed in the way that Gate handles requests, because I am now getting the error below in the Gate logs. Obviously, the GUI is not really usable without Gate.

```
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
```

### Cloud Provider(s):

GCP

### Environment:

GKE

### Feature Area: 

Gate

### Steps to Reproduce:

- Have a 1.10+ GKE cluster
- Download https://spinnaker.io/downloads/kubernetes/quick-install.yml
- In that file, change "1.9.5" to "1.11.0"
- `kubectl apply -f` the file
- When all pods are created, `kubectl port-forward` to deck on port 8080 (or use Cloud Shell's web preview)
- Open the GUI in the browser, you'll have 500 errors in the developer console, and this error in Gate's logs.

### Additional info

Just tested with 1.10.5, no problem.

**Comment by MrTrustor** [comment]
Closing as a dup of spinnaker/spinnaker.github.io#1154

**Comment by antoooks** [comment]
@MrTrustor  I installed spinnaker via helm and I got this error. But when I downgraded to `1.10.9` all back to normal.

It's quite dilemmatic because I need aws cli which only available on version `1.11.0` or above.

Any chance that the change might broke another install method on 1.11.0++?

**Comment by MrTrustor** [comment]
@antoooks see helm/charts#10147

**Comment by antoooks** [comment]
@MrTrustor Ahh I see. Thank you
