### ISSUE TITLE
Cannot create new Application

### ISSUE THREAD

**Issue by abergmeier** [spinnaker/spinnaker#3734]
### Issue Summary:
When I try to create a new Application and click _Create_ it never finishes.
Looking at the network requests, there is regularly sent a hash request which returns with `status` `NOT_STARTED`.
Not sure how I can debug this further.

### Cloud Provider(s):
Kubernetes V2

### Environment:
OpenShift 3.9

**Comment by abergmeier** [comment]
This might be related to a different Redis image being used (for OpenShift). I did not see any errors anywhere, though. Will try to validate.

**Comment by abcsnowwolf** [comment]
Can you post orca and front50 logs?

**Comment by abergmeier** [comment]
> n you post orca and front50 logs?

Sorry, will probably not get around to invest more time in this. Since it works with the Spinnaker Redis, will close this.
