### ISSUE TITLE
In __Create New Server Group__ dialog: lingering "Security Groups" label

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker#3754]
### Issue Summary:
The __Create New Server Group__ dialog has a section "Security Groups". Should be "Firewall, right?

### Cloud Provider(s):
GCE

### Environment:
Cloud Launcher (Marketplace) image

### Feature Area: 
Pipeline stage

### Description:
I first noticed this when I was configuring a Deploy stage, but it's also there when I Create Server Group from the __Clusters__ tab.

### Steps to Reproduce:
Navigate to __Clusters__ tab. Click __Create Server Group__.

### Additional Details:

---

**Comment by dorbin** [comment]
![create_server_group_security_group](https://user-images.githubusercontent.com/29312809/50164382-8f1c3180-02b0-11e9-9ada-d89223c497dc.png)

**Comment by duftler** [comment]
This is resolved with the recent update of the marketplace image:

![image](https://user-images.githubusercontent.com/8437718/50231218-43cf5500-037c-11e9-958b-f95643d9d59d.png)
