### ISSUE TITLE
Move configuration of all notification types to Halyard

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#3757]
### Issue Summary:

Per discussion with @ttomsu, all notification types should be disabled by default and configurable with Halyard. Currently, it is only possible to configure Slack with Halyard, and all notification types are enabled by default and displayed in the UI even if they are not configured.

### Feature Area:
Deck, Halyard

### Description:

- Add Halyard commands to enable/configure each notification type (Email, Bearychat, GoogleChat, Hipchat, SMS, and GitHub status).
- Only hydrate Deck notifications dropdown with notification types that have been enabled.
- Remove (unused?) `feature.notifications` flag.

**Comment by ttomsu** [comment]
> Only hydrate Deck notifications dropdown with notification types that have been enabled.

This seems to be accomplished by just disabling the notification types that aren't configured. Example:

```
window.spinnakerSettings.notifications = {
  bearychat: {
    enabled: false,
  },
  email: {
    enabled: true,
  },
  githubStatus: {
    enabled: false,
  },
  googlechat: {
    enabled: false,
  },
  hipchat: {
    enabled: false,
  },
  pubsub: {
    enabled: true,
  },
  slack: {
    enabled: false,
  },
  sms: {
    enabled: false,
  },
}

```
