### ISSUE TITLE
AWS Bake Failures Re: Spot Pricing In Spinnaker 1.11

### ISSUE THREAD

**Issue by brantburnett** [spinnaker/spinnaker#3764]
### Issue Summary:

Bakes in AWS that are using on-demand pricing (the default) fail with error "spot_price should be set to auto when spot_price_auto_product is specified" after upgrading to Spinnaker 1.11

### Cloud Provider(s):

AWS

### Environment:

Kubernetes deployment

### Feature Area: 

Rosco bakery

### Description:

This appears to be related to the upgraded version of Packer included in Spinnaker 1.11.  Packer now has this validation:

https://github.com/hashicorp/packer/blob/v1.3.1/builder/amazon/common/run_config.go#L130

The code in Rosco is filling command line variables here:

https://github.com/spinnaker/rosco/blob/12add382dcc58f9bbbf4cce37ff49d4744c58fd8/rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy#L109

The default for awsVirtualizationSettings.spotPrice is `0`:

https://github.com/spinnaker/rosco/blob/12add382dcc58f9bbbf4cce37ff49d4744c58fd8/halconfig/images.yml#L16

This means that by default, both `aws_spot_price` and `aws_spot_price_auto_product` are sent on the command line to Packer, resulting in the failure.  Changing the logic to only send `aws_spot_price_auto_product` if `aws_spot_price` is `auto` should fix the problem.  However, this logic should probably be applied *after* extended attributes are applied, in case users are setting just `aws_spot_price` in the extended attributes.

### Steps to Reproduce:

Create a basic AWS bake step, with no special configuration, and attempt to bake.

### Workaround

Add an extended attribute to the bake with the name `aws_spot_price_auto_product` and the value `${''}`

**Comment by brantburnett** [comment]
@ezimanyi

Makes sense to me. Just means some users may need to adjust their pipelines slightly upon upgrading, but that’s probably okay for this edge case.

However, updating the UI to allow easier setting of blank attributes would be helpful.  I had to use an empty string in an expression to get around validation rules.

**Comment by ezimanyi** [comment]
Fixed by the above commits
