### ISSUE TITLE
Jenkins triggers broken in 1.11 for jobs with slashes in name

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/spinnaker#3766]
In Spinnaker 1.11.0 and 1.11.1 Jenkins triggers are not working if the Jenkins job has a slash in the name (such as when using Folders or Multibranch pipelines).

This is due to Spinnaker encoding the slashes when sending requests to the Jenkins API whereas Jenkins expects the slashes to be unencoded.

**Comment by ezimanyi** [comment]
Fixed in 1.11.2.

**Comment by tonyg4864** [comment]
@ezimanyi , I see this issue re-occuring in Spinnaker 1.14.7. 
This occured while trying to invoking a Jenkins multi-branch job like below:
Jenkins Job Name: SAN_tony-dogclinic
Branch Name: release/2.0.1

Spinnaker resolves this as: SAN_tony-dogclinic/job/release%2F2.0.1

The exact error message is : 
    Exception ( Start Jenkins Job )
    The request was rejected because the URL contained a potentially malicious String "%25"

**Comment by tonyg4864** [comment]
Ok I see someone already reported this issue: https://github.com/spinnaker/spinnaker/issues/4477
Please disregard my previous comment.
