### ISSUE TITLE
Group by time boundary breaks deck pipeline UI (1.11)

### ISSUE THREAD

**Issue by eaceaser** [spinnaker/spinnaker#3767]
### Issue Summary:
Choosing the "Time Boundary" option in the group by dropdown can break the Spinnaker UI.

### Environment:
Spinnaker 1.11.1

### Feature Area: 
Deck

### Description:
I'm not 100% sure what the conditions for this are, but choosing the Time Boundary option for any of our pipeline views cause the Deck UI to break (it ceases to render) until local storage is cleared.

### Steps to Reproduce:
* Go to the pipeline view for a configured application
* Choose "Time Boundary" for the group by dropdown

### Additional Details:

![2018-12-19_15-03](https://user-images.githubusercontent.com/157866/50253569-72aaf280-039f-11e9-82c6-3d7a098b0d08.png)

**Comment by ezimanyi** [comment]
Fixed in https://github.com/spinnaker/deck/pull/6087; I've cherry-picked this to 1.11 in https://github.com/spinnaker/deck/pull/6253
