### ISSUE TITLE
CF - Add Clone SG as a pipeline stage

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#3797]
### Issue Summary:
Add Clone SG as a pipeline stage

### Cloud Provider(s):
CF

### Feature Area: 
Deck (UI)

### Description:
Add Clone SG as a pipeline stage

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by okundzich** [comment]
Assume env specific manifest is always an input.
