### ISSUE TITLE
Scale (Manifest) stage timeout when scale replicaSet to 0 replicas

### ISSUE THREAD

**Issue by vmagamedov** [spinnaker/spinnaker#3804]
### Issue Summary:

This is the same issue as #3148, where only deployments were fixed in https://github.com/spinnaker/clouddriver/pull/2848. Please make the same fix also for a replicaSet kind.

I assume that this function needs a fix: https://github.com/spinnaker/clouddriver/blob/b73c5f1/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java#L97

### Cloud Provider(s):

Kubernetes

### Environment:

Kubernetes

### Feature Area: 

`Scale (Manifest)` stage, `replicaSet` kind

### Additional Details:

Error details:
> Exception ( Wait For Manifest To Stabilize )
> 
> WaitForManifestStableTask of stage Down API Canary timed out after 30 minutes 1 second. pausedDuration: 0 seconds, elapsedTime: 30 minutes 1 second,timeoutValue: 30 minutes

Scale (Manifest) stage succeeds and replicas count is equal to 0, but this stage waits for a 30 minutes and then fails the whole pipeline.

**Comment by ezimanyi** [comment]
FYI @lwander

**Comment by lwander** [comment]
@spinnakerbot assign-issue lwander

**Comment by vmagamedov** [comment]
Updated image in the `spin-clouddriver` deployment from `4.2.0-20181220153244` to `4.3.0-20190104022809` and can confirm that pipeline now works. Thanks!
