### ISSUE TITLE
Add dynamic target selection to Delete Manifest stage

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#3829]
### Issue Summary:

Currently, dynamic target selection only exists in Kubernetes Enable, Disable, and Scale Manifest stages. In the Delete Manifest stage, we can either target multiple manifests by specifying one or more kinds and one or more labels, or target a single manifest by specifying a single kind and a single name. Ideally, we should be able to target a single manifest both statically (using current UI) and dynamically (by selecting cluster and target from pre-populated dropdowns as in the Enable, Disable, and Scale stages).

Additionally, namespace and kind(s) should pre-populate like they do in the Enable, Disable, and Scale stages. In order to re-use existing logic, might be worth converting the KubernetesMultiManifestSelectorComponent to React.

Edit: we should also add dynamic target selection to the Patch Manifest stage.

### Cloud Provider(s):
Kubernetes V2

### Feature Area: 
Pipelines

**Comment by maggieneterval** [comment]
cc @lwander let me know if I missed anything in capturing this issue!

**Comment by lwander** [comment]
Yup LGTM< I think the 'scale' stage has support already as well.

**Comment by maggieneterval** [comment]
Good call, updated the description to include the 'scale' stage.

**Comment by graycrock** [comment]
If the stage is edited through JSON, this can be achieved.
```
{
  "account": "k8s-v2-account",
  "app": "xyz",
  "cloudProvider": "kubernetes",
  "cluster": "replicaSet xyz",
  "criteria": "newest",
  "kind": "replicaSet",
  "location": "default",
  "manifestName": " ",
  "mode": "dynamic",
  "name": "Stage",
  "options": {
    "cascading": true,
    "gracePeriodSeconds": 0
  },
  "type": "deleteManifest"
}
```
