### ISSUE TITLE
Bug: spin cli tool allows creating/modifying non-k8s v2 application name with dashes and that broke the entire application

### ISSUE THREAD

**Issue by yinanfang** [spinnaker/spinnaker#3857]
### Issue Summary:
The UI for creating/modifying application name from the UI check for application name format. However, `spin application save` allows creating/modifying non-k8s v2 application name with dashes and that broke the entire application.
After the modification, the entire application is broken. The deploy stage becomes empty and all execution will timeout. We can delete each individual pipeline but we can't even delete the application.

Suggestion: 
Check should be added to spin or server to verify the format
There should be a way to delete app after the incident

### Cloud Provider(s):
k8s, gae

### Version
Spinnaker 1.11.4

### Feature Area: 
spin cli

### Steps to Reproduce:
Create an application with the following config and it shows `Application save succeeded`

`cloudProviders: kubernetes,appengine`

### Stack Trace
```
"java.lang.NullPointerException: Cannot get property 'status' on null object
 org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
 org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
 org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
 com.netflix.spinnaker.orca.applications.tasks.VerifyApplicationHasNoDependenciesTask.execute(VerifyApplicationHasNoDependenciesTask.groovy:64)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:100)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:311)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:99)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
 com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:97)
 com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:98)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:182)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:56)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:49)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:33)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:56)
```

**Comment by jtk54** [comment]
What is the context of the NPE stack trace? Is this during a failed application deletion?

**Comment by jtk54** [comment]
Can you clarify the sequence of events that lead to the broken app? e.g.

1. created app foo
2. created a bunch of pipelines
3. used the pipelines to create a bunch of server groups
4. tried to rename app to foo-bar
5. everything was broken in foo|foo-bar

As an aside, generally app names are meant to be static in spinnaker. The other attributes can change, but application names are ingrained deeply into how spinnaker indexes the infrastructure and pipelines and associates them with applications.

Can you clarify what you wanted to do with the application update?

**Comment by jtk54** [comment]
API hardening to prevent this in the future: https://github.com/spinnaker/orca/pull/2604.

**Comment by yinanfang** [comment]
Thanks for working on this @jtk54
