### ISSUE TITLE
Service-account not visible to Deck

### ISSUE THREAD

**Issue by sysadmin1139** [spinnaker/spinnaker#3859]
### Issue Summary:
After creating a service-account following [the documentation for such](https://www.spinnaker.io/setup/security/authorization/service-accounts/), we have a service-account set up that correctly returns a list of roles an applications when `authorize/${account name}` is hit on the API. Yet, this account does not show up in pipeline dropdowns, and when a `runAs` statement is injected into the Pipeline JSON, the account is not used.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.10.7
Using SAML through Okta

### Feature Area: 
Auth, Cloud50, Fiat, Deck

### Steps to Reproduce:
1. Add a service account.
   1. `curl -X POST -H "Content-type: application/json" -d '{ "name": "jenkins@example.org", "memberOf": [ "ciusers" ]' https://FRONT50/serviceAccounts`
1. Force a sync
   1. `curl -X POST https://FIAT/roles/sync`
1. Verify service-account creation
   1. `curl https://FIAT/authorize/jenkins@example.org`
1. Notice that the created user is listed with read-write permissions to the relevant App, QA-Example.
1. Go to the QA-Example application in the UI, logged in as a user in the `ciusers` group.
   * This user also has additional groups beyond `ciusers`.
1. Open an existing pipeline.
1. Open the `Run As User` dropdown, notice the user is not present.
1. Check `deck/html/settings.js` to verify `fiatEnabled` is set to true. It is.
1. Force-reload the UI. Repeat steps 5 through 7.
1. Edit the pipeline JSON to add `"runAs": "jenkins@example.com"`
1. Cause Jenkins to trigger the pipeline.
1. Pipeline fails on the deploy stage with 'anonymous is not allowed...' error.

### Additional Details:
From poking about in the browser debugger, I noticed a call to `serviceAccounts` when opening the pipeline, and it returns an empty array. The `GET` call was to `GATE/auth/user/serviceAccounts` with no parameters or obvious headers. In our case, the service-account was added a month ago, and the spinnaker server has been blown away and spun up anew several times.

This feels like something in deck/gate is not seeing the logged in user as authorized to permit the created service-account from being visible. The documentation says

> The roles you give this service account determine who has access to use it. In order to prevent a privilege escalation vulnerability, only users *with every role the service account has* may use it.

Perhaps this is an exactness check, where the extra roles the logged in user cause it to fail?

**Comment by ajordens** [comment]
Is authentication generally working for your installation? 

What do you see for `authentication` in one of your execution json? From the description, it sounds like `anonymous` but should be your authenticated username.

**Comment by sysadmin1139** [comment]
Authentication does generally work. Applications can be restricted to certain groups, and the groups on the user's auth-token do populate the dropdowns in Deck. We have evidence that this is actually enforced for users who log in through SAML.

For some reason service-accounts aren't treated the same. For a user in the same group as the service-account, the "Run as" dropdown does not populate with it like it should.

**Comment by ajordens** [comment]
Just double checking that `services.fiat.enabled: true` is in your echo config? 

That should be the only thing gating whether or not `echo` will pass along the `runAsUser` specified on a trigger.

Similar setting needs to be in `gate` as well (along with an appropriate `baseUrl` pointing to fiat).

Does that match your setup?

**Comment by sysadmin1139** [comment]
`var fiatEnabled = 'true' === 'true';` is what settings.js sees.

Setting `services.fiat.enabled: true` in our echo-local didn't seem to change the UI presentation (still not in the dropdown).

However, I did notice that `services.fiat.enabled` was set to false in the main spinnaker.yml file. Changing that, and restarting gate and fiat, got it into the dropdown. Very strange that having fiat disabled there seems to have ACLs work in a few places anyway.

**Comment by ajordens** [comment]
Not sure what your particular environment looks like, but generally speaking `fiat` needs to be enabled across the board.

Sounds like we've got this fixed, feel free to reach out if you run into other grief.
