### ISSUE TITLE
How to configure spinnaker gcp cloudprovider for host project and service project 

### ISSUE THREAD

**Issue by anup13kumar** [spinnaker/spinnaker#3876]
### Issue Summary:
I have a running aws spinnaker working set up want to configure GCP as a cloud provider for my existing spinnaker able to configure gcp  to single project with service account json file.
But i want to configure to host project and service project 
**Host project :** contains network resources configurationlike subnets, firewallsand routers. 
**Service project:** contains compute resources like a VM. Service project deploy resources to VPC in host project.

### Cloud Provider(s):
Google Cloud Provider

### Feature Area: 
clouddriver

Descriptions:
I have created one service account in host project and with the permission of below role

  Compute Instance Admin (beta)
Compute Network Admin
Compute Security Admin
Compute Storage Admin
Service Account Admin
Logs Writer
Storage Admin

after that cloud driver working well but in its launching the server in host project how to map that server should launch in service project

**Comment by rampatnaik** [comment]
any update

**Comment by dibyom** [comment]
You could add multiple GCE accounts, one for the Host project and one for the Service project.
https://www.spinnaker.io/setup/install/providers/gce/#adding-an-account

**Comment by rampatnaik** [comment]
You could add multiple GCE accounts, : we dont have issue for adding multiple account ..
Here we are having issue with VPS, subnet in one project and we would like to launch server in another project like   shared VPC concept . But spinnaker only lauching project in host project not in service project . 

https://cloud.google.com/vpc/docs/shared-vpc

**Comment by rampatnaik** [comment]
This can be close .
After adding service account of Service project added into host project issue has been solved
