### ISSUE TITLE
Run job stage incorrectly defaults to titus in the UI

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/spinnaker#3879]
When adding a "Run job" stage to a pipeline with the Kubernetes V1 provider enabled, the stage defaults to having `cloudProvider: titus` set.  This means the UI loads the titus-specific configurations, and also loads an account drop-down that is filtered to only titus accounts (which will be empty for kubernetes-only users).

I did some investigation, and it looks like the issue is:
* We correctly filter the available stages to only contain the kubernetes version of the run job stage
* Upon selecting the stage, `selectStage` calls `PipelineRegistry.getStageConfig` with the selected stage.  At that point, for a new stage, only the type (and not the cloud provider) is passed in, so that function is selecting from all available `runJob` stages without a way to distinguish which one we actually want.  The result is that we end up picking the `titus` one.

It would seem that this should affect other stages that are overloaded between different providers, but I haven't exhaustively tested that.

**Comment by clanesf** [comment]
If you have both v1 and v2 kubernetes accounts connected to spinnaker, even if you manually change the cloudProvider to kubernetes the account dropdown still lists the v2 providers.

**Comment by ezimanyi** [comment]
Dug a bit more into this, and I think this was introduced by converting the `titus` `runJob` controller to react.

For stages that exist in multiple providers, we delegate to `baseProviderStage` by [overriding the template and controller](https://github.com/spinnaker/deck/blob/4600bbd9d1588963c6bdde31a334674ffa90d8bc/app/scripts/modules/core/src/pipeline/config/stages/stage.module.js#L186); `baseProviderStage` then figures out what provider to use (with a selector if needed) and renders the correct actual stage.

The problem is that if the stage is in react, and has a `component` defined, we just [render the react component](https://github.com/spinnaker/deck/blob/4600bbd9d1588963c6bdde31a334674ffa90d8bc/app/scripts/modules/core/src/pipeline/config/stages/stage.module.js#L193) and ignore the overriden template/controller so we just end up with the stage directly.  It looks like the fix there is just to null out the `component` as well in that `useBaseProvider` block so we fall back to the angular `baseProviderStage` logic.

The more complex part is that we then need the `baseProviderStage` to understand how to render react components; normally when you pick a provider it just [sets](https://github.com/spinnaker/deck/blob/4600bbd9d1588963c6bdde31a334674ffa90d8bc/app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js#L58) `providerStageDetailsUrl` which triggers angular to render the full stage vi `ng-include`.  Ideally we'd do something similar to what's done in `stage.module.js`: check if the stage has a component, and if so mount the component.  But there are two issues with this I'm running into:
(1) [minor] This leads to duplication of the component mounting code between `stage.module.js` and `baseProviderStage.js` that would be nice to have in one place
(2) I can't seem to inject `$element` into `baseProviderStage.js`; I think from my searching that it's because it can only be injected into directives.

@anotherchrisberry @sbwsg : Any thoughts on what the best solution would be here?

**Comment by sbwsg** [comment]
At the moment it looks like the best way to workaround this might be to split `baseProviderStage` up a bit.  It looks to me like it does three things:

1. It figures out the correct stage config to use according to available cloud providers.
2. It renders UI for selecting a specific provider if there is more than 1 to choose from.
3. It renders the chosen stage's template.

I'm trying to keep it doing 1 and 2 but then have it give back the selected provider & stage config to `stage.module.js` for number 3, since the rules for react vs. angular rendering all live there.

**Comment by anotherchrisberry** [comment]
It might be easier to roll up the base provider stage bits into the `stage.module.js` file.

We should prioritize converting this to React, but it makes sense to try to get things working first with the Angular implementation.

**Comment by sbwsg** [comment]
This will be fixed in 1.13 and will be resolved in 1.12 upon the next patch release if one is made before 1.13.
