### ISSUE TITLE
RFC: Move all management endpoints to a common port

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#3883]
### Issue Summary:
Spring Management endpoints are a handy config debug tool, but Spring Security frequently gets in the way and requests full authentication, which isn't always available. 

I propose moving all management endpoints to some other port (off of the service's default port), lets say 8050, when deployed to Kubernetes, and maybe the regular service port + 1000 for non k8s deployments. 

Thoughts?

**Comment by lwander** [comment]
I agree. Is configuring this (minus the changes to halyard) possible today? And if so, as of what Spinnaker release is this possible? Just checking to see if we need a migration/backwards-compatible story in Halyard.

**Comment by ezimanyi** [comment]
I was just exploring this a bit before finding this issue.  Without halyard, this is already possible by adding the following to each service's `<service>-local.yml` file:
```
management:
  port: 9050
  ssl:
    enabled: false
```
That will expose all Spring managed endpoints on port 9050 without requiring SSL.  This is all directly supported by Spring, so should not be tied to a particular Spinnaker version (though we can check when this was introduced in Spring, and if we ever used a Spring version prior to that).

Presumably there's also somewhere in Halyard that sets the health check endpoint for Kubernetes deployments that would need to be changed as well.

**Comment by ttomsu** [comment]
Some parts of halyard will need to change to make the health port different from the service port. Example: https://github.com/spinnaker/halyard/blob/f8afe0ec05f05803cfbf51d11e8be9ce67ad37d2/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java#L95

**Comment by plumpy** [comment]
This RFC is very old. The old RFC process has been superseded by a new one. If you still care about this RFC and would like feedback, please move it over to [the new RFC process](https://www.spinnaker.io/community/contributing/submitting/#before-you-begin). Thanks.
