### ISSUE TITLE
Add "Export as Pipeline Template" button to pipeline action menu

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#3887]
### Issue Summary:

As a Publisher I want a button in the pipeline editor that exports the current pipeline's JSON as a pipeline template.

### Feature Area: 

MPT v2

### Description:

Provide Publishers with a mechanism to export a pipeline as an MPTv2 template.  The first iteration of this feature may simply take the form of a button that pops up a modal containing template JSON which the user then copy/pastes into Spin.

### Further Considerations

* The "export" button should not be visible to users who aren't authorized to create templates. (If auth is implemented for templates).
* A pipeline that is itself based on a template should not allow this functionality.
* The "export" button should be hidden behind the MPTv2 feature flag.

### Wireframes

Step 1: Publisher finds button to export in pipeline editor:

![screen shot 2019-01-28 at 4 00 20 pm](https://user-images.githubusercontent.com/34253460/51866032-d7019000-2315-11e9-94d8-b6ed2adcad59.png)

Step 2: Publisher clicks button and sees JSON in modal to copy/paste:

![screen shot 2019-01-28 at 4 11 37 pm](https://user-images.githubusercontent.com/34253460/51866643-7e32f700-2317-11e9-8a47-75a4715f51ad.png)

**Comment by louisjimenez** [comment]
Some thoughts on the required fields for the template:
```javascript
{ 
  "variables": [], // empty by default
  "id": "some uuid", // generated via deck
  "metadata": {
    "name": "generated name", // generated human readable name, can be overridden via input
    "description": "", // empty by default, can be supplied via input
    "scopes": ["global"]
  }
}
```
