### ISSUE TITLE
Render only the values in an Enum variable defined in a template

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#3899]
### Issue Summary:

As a User I only want to see the set of values in a pipeline editor field that are allowed by its associated template variable enum.

### Feature Area: 

MPT v2

### Description:

A Publisher is able to set a field in a pipeline template as an enum type. This type allows the publisher to specify exactly which values are available to the User who builds a pipeline from the template. When the User comes to build the pipeline they should only be able to see the set of values that the Publisher has defined.

### Wireframe:

<img width="710" alt="screen shot 2019-01-29 at 10 58 09 am" src="https://user-images.githubusercontent.com/34253460/51921136-d1a75280-23b4-11e9-90b1-f2ac183456cb.png">

**Comment by louisjimenez** [comment]
Going to close this. It is covered by https://github.com/spinnaker/spinnaker/issues/3231
