### ISSUE TITLE
RFC: Make Spectator controller ("/spectator/metrics") a Spring managed endpoint

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#3901]
### Issue Summary:

[Spectator](https://github.com/netflix/spectator) is considered an "application" controller, though it's sensitivity matches that of `/health`, `/env`, etc. 

Plugging into the managed endpoint infrastructure makes sense to me, but am willing to entertain other ideas to expose-but-protect this endpoint with more than just basic auth.

**Comment by ttomsu** [comment]
@ewiseblatt @jkschneider I don't know anything about micrometer - how would that system work with this?

**Comment by ewiseblatt** [comment]
A couple corrections. I think "/metrics" is a Spring controlled endpoint. Historically it was not possible to change its behavior. It was hardwired to work a particular way and serve particular things. So we added a new endpoints for Spectator, "spectator/metrics". That is what we use for Spinnaker.

So your question is either how to manage the *spectator* endpoint differently, or how to gain control over the /metrics endpoint which the micrometer work might have enabled.

**Comment by ezimanyi** [comment]
I was just looking into this as well as a way of resolving #3948.  A few brief notes from my investigation (which may be obvious to others who've worked in this code more):
* The binding to `/spectator/metrics` is directly in [spectator](https://github.com/Netflix/spectator/blob/eb5b9699b5a799f6b3b31896327598597959e902/spectator-web-spring/src/main/java/com/netflix/spectator/controllers/MetricsController.java#L99).  The web endpoint is enabled/disabled with `spectator.webEndpoint.enabled`
*  It seems like it's reasonably easy to write a [custom endpoint](https://docs.spring.io/spring-boot/docs/1.5.19.RELEASE/reference/htmlsingle/#production-ready-customizing-endpoints-programmatically)
* Ideally we'd probably want to replicate the spectator `MetricsController` as an `Endpoint`, hopefully without duplicating much code---the best way here might be to either have spectator itself support the endpoint, or at least refactor some of the logic out of `MetricsController`.

Interested in discussing this more, as I've seen a number of issues raised recently that would be solved by having introspection-type queries moved out of application controllers.

**Comment by ttomsu** [comment]
I wrote the `/resolvedEnv` [here](https://github.com/spinnaker/kork/blob/master/kork-web/src/main/groovy/org/springframework/boot/actuate/endpoint/ResolvedEnvironmentEndpoint.groovy) and yes, it's pretty easy. 

I would anticipate changes need to be made in Spectator to support this, though I've not dug into the details. @ewiseblatt, @jkschneider, and @robzienert seem to be keen on [Micrometer](https://spring.io/blog/2018/03/16/micrometer-spring-boot-2-s-new-application-metrics-collector) which has been backported to Spring 1.5. Atlas, Datadog, and Prometheus are all supported and Stackdriver support was scheduled for mid 2018, so I assume it's done now?

I think this is the ideal long term solution, and would enable us to stop shipping the monitoring daemon as a sidecar in k8s deployments.

**Comment by tingzhang-ming** [comment]
@ewiseblatt I got the same problem, i launched my clouddriver, and i could not visit http://localhost:7002/spectator/metrics , so i want to ask how to config spectator in my clouddriver-local.yaml?
the following is my config in clouddriver-local.yaml:
Registry:
  spectator:
    webEndpoint:
      enabled: true

**Comment by ewiseblatt** [comment]
I dont know what "Registry:" is refering to. The top-level key should be
"spectator". In my case I have it in clouddriver.yml, I assume halyard put
it there.

**Comment by robzienert** [comment]
For what it's worth, `spectator-web-spring` is Spring Boot 1.x only. In order to get to Spring Boot 2, this functionality either needs to be copied as it exists today in Spectator, or do it the way we want here in this PR.

I'm happy to "just" implement this as a managed `Endpoint` instead from the get-go?

**Comment by jkschneider** [comment]
@ttomsu Stackdriver support did ship with Micrometer 1.1.0 and has gone through some further patching to the point where I think it's pretty stable in 1.1.3. Many more supported monitoring systems beyond just Atlas, Datadog, Prom, and Stackdriver. As we install Spinnaker and more and more sites, the ability to plug Spinnaker metrics into whatever monitoring solution they've chosen only gets more important.

I can't be certain that the structure of metrics shipped by Micrometer to Stackdriver is exactly the same as what we had in the Spectator->Stackdriver bridge, or how much that difference matters. @ewiseblatt could probably help evaluate this?

**Comment by ewiseblatt** [comment]
I would definitely like to look into this and move into micrometer as I've
stated before. However I am going to first need to add another layer into
that to transform arbitrary spinnaker metrics into specific stackdriver
metrics to stay on the course we are on. I have a deadline coming up
requiring a bunch of work in some overlapping areas so dont think I have
the capacity or risk tolerance right now (though if this were there it
would save work elsewhere and mitigate other risks). I hope I would be
ready to pursue this in a few weeks. It probably wont leave enough time for
1.13 but 1.14 sounds viable at this time.

**Comment by plumpy** [comment]
This RFC is very old. The old RFC process has been superseded by a new one. If you still care about this RFC and would like feedback, please move it over to [the new RFC process](https://www.spinnaker.io/community/contributing/submitting/#before-you-begin). Thanks.
