### ISSUE TITLE
halyard daemon is not able to start

### ISSUE THREAD

**Issue by michaeljqzq** [spinnaker/spinnaker#3905]
### Issue Summary:
Halyard daemon timeout when trying to start
```
The halyard daemon isn't running yet... starting it manually..............................
Waiting for halyard to start timed out after 123 seconds
```

### Cloud Provider(s):
Not related

### Feature Area: 
halyard

### Description:
Everything works well based on this commit d04657137b3cfa6df67ab9e72b783a7a0ef43a92
When build halyard based on this commit b1ff8e4045622a9b6d24032bbca4d9ebc3dd265a, meet the timeout issue.
Not sure which commit between them causes the error. Please point out if it is not the right way to run a specific version of halyard from my local environment

### Steps to Reproduce:
I am trying to test the specific commit on the `master` branch.
I installed the halyard using InstallHalyard.sh
Then I point the code to specific commit.
Then I build the halyard project using `./gradlew build` command, and then replace the jar files under `/opt/halyard/lib` to make it work.

**Comment by sbwsg** [comment]
I run the hal daemon from git by simply running `./gradlew` in the root of the Halyard repo.  Make sure to stop any other running halyard daemon first. I just quickly checked out the commit you mentioned and was able to run it fine from the repo.

If you're trying to build and test the cli tool for this specific commit then you go into the `halyard-cli` subdirectory in the Halyard repo, then run `make`.  Once its built you can run it with `./hal` in that same directory.

**Comment by xacaxulu** [comment]
+1
