### ISSUE TITLE
Google analytics not recording page views

### ISSUE THREAD

**Issue by christopherthielen** [spinnaker/spinnaker#3914]
### Issue Summary:

Google Analytics reporting has been disabled since mid-december.

### Cloud Provider(s):

All

### Feature Area: 

UI Analytics reporting

### Additional Details:

PR incoming

**Comment by christopherthielen** [comment]
@ezimanyi any chance getting a 1.12.1 patch release with this fix in it?

**Comment by ezimanyi** [comment]
@christopherthielen : Yes, I'm planning on releasing 1.12.1 tomorrow, so as long as it's merged into the 1.12 branch by tomorrow, it will make it.
