### ISSUE TITLE
How to remove imageSource  for gcp

### ISSUE THREAD

**Issue by rampatnaik** [spinnaker/spinnaker#3924]
### Issue Summary:
due to       "imageSource": "priorStage", deployment failing

Exception ( Create Server Group )

Cannot deserialize value of type com.netflix.spinnaker.clouddriver.google.deploy.description.BaseGoogleInstanceDescription$ImageSource from String "priorStage": value not one of declared Enum instance names: [STRING, ARTIFACT] at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.clouddriver.google.deploy.description.BasicGoogleDeployDescription["imageSource"])

### Cloud Provider(s):
gce
### Environment:
spinnaker 1.10.5

### Feature Area: 
Deploy stage

### Description:
If we do any edition for deploy stage

  "imageSource": "priorStage" condition attaching in json which make build fail
### Steps to Reproduce:
Find Image from Tags
Region
    global
Image
    ubuntu-1404-trusty-v20190122a 

### Additional Details:
How to remove  "imageSource": "priorStage" condition

**Comment by rampatnaik** [comment]
How to remove  "imageSource": "priorStage" condition

**Comment by ezimanyi** [comment]
@rampatnaik : Can you please provide a bit more details about exactly how you have your pipeline configured?  The `priorStage` that exists in the JSON should be translated to either `ARTIFACT` or `STRING` before sending the request to create the server group to `clouddriver`.  This is working for me in a simple case of trying to deploy an image from a prior stage, so the case that is broken is likely some edge case that will require more details.

If you have the full stack trace for the clouddriver error above, that would also be helpful.  Thanks!

**Comment by rampatnaik** [comment]
Hello [ezimanyi](/ezimanyi) , thanks for reply .
For me , Artifacts is false . its disable  . I am not using Artifacts concept . 
I am using "Find Image from Tags" concept 

{
  "cloudProvider": "gce",
  "cloudProviderType": "gce",
  "name": "Find Image from Tags",
  "packageName": "ubuntu-1404-trusty-v20190122a",
  "regions": "asia-east1",
  "tags": {},
  "type": "findImageFromTags"
}

**Comment by ezimanyi** [comment]
@rampatnaik : Thanks for the additional information.  Are you seeing the error in the "Find Image from Tags" stage or the "Deploy" stage.  (I think it's the deploy stage if I'm understanding correctly but want to make sure.)  If it's the deploy stage, I'd be interested in more details on how that is configured.  Also, as noted above the full clouddriver stacktrace of the error would be most useful, as that should help me narrow down exactly what code path is not properly converting `priorStage` into the format understood by clouddriver.  Thanks!

**Comment by rampatnaik** [comment]
Are you seeing the error in the "Find Image from Tags" stage or the "Deploy" stage : yes right

**Comment by rampatnaik** [comment]
this issue can be close
