### ISSUE TITLE
Template schema version is unsupported

### ISSUE THREAD

**Issue by DavidGereb** [spinnaker/spinnaker#3930]
### Issue Summary:
Unable to create pipeline from MPTv2 based pipeline-template. 

### Cloud Provider(s):
kubernetes

### Environment:
Kubernetes (AWS EKS)

### Feature Area: 
pipeline-templates v2

### Description:
Expected behaviour:
Creating pipelines from v2 templates should work.

Actual behaviour:
Getting the following error message on deck, when configuring the pipeline
```
Could not generate pipeline from provided template configuration.

Error:
Message: template schema version is unsupported: expected '1', got 'v2'
Severity: FATAL
```

### Steps to Reproduce:
1. Save the pipeline using `spin pt save -f template.json`
2. Deck -> Some app -> Pipelines -> Create
3. Create from template -> Select the template saved in step 1.
4. Click configure

### Additional Details:
Tried with the example pipeline described here: https://blog.spinnaker.io/spinnaker-managed-pipeline-templates-v2-taking-shape-c7503d0a608d

spin cli: v1.6.0
spinnaker: v1.12.1

**Comment by jtk54** [comment]
Currently creating pipelines from v2 MPTs is not supported from the UI yet and is supported from saving pipelines from `spin` only. We do have a plan for a UI overhaul for MPT v2 but it will start landing in 1.13. In the meantime we likely should filter out v2 MPTs from the suggested list shown in the UI.

**Comment by DavidGereb** [comment]
@jtk54 thanks for the info

**Comment by rverma-nikiai** [comment]
@jtk54 Does it also meant that we can't see the pipeline as well as execution with spinnaker 1.12.1, I tried creating a pipeline with spin cli and v2 template, but neither can I see the pipeline in expanded mode nor the execution. Only thing I can see is the pipeline name with a weird logo.

**Comment by jtk54** [comment]
@rverma-nikiai The UI behavior for v2 templates is more or less undefined at this moment. All ops through `spin` should function properly however.

**Comment by DavidGereb** [comment]
> @rverma-nikiai The UI behavior for v2 templates is more or less undefined at this moment. All ops through `spin` should function properly however.

regarding the sentence

**Comment by DavidGereb** [comment]
sorry, closed it by accident

**Comment by jtk54** [comment]
> the functionality in the background should work properly as of 1.12.1?

Yes.

**Comment by costimuraru** [comment]
The behavior we're seeing in the UI when trying to create a pipeline based on a template is very confusing. Based on the error received, we were under the impression that the template itself was broken, so we spent quite a bit of time trying to update to make it work.

<img width="887" alt="screenshot 2019-03-01 15 57 18" src="https://user-images.githubusercontent.com/952836/53642538-b4c3a080-3c3a-11e9-9867-8c55fdc904f2.png">

It was not only after we read this issue that we figured out that we need to create the pipeline by using the `spin` CLI.

Could we at least update deck to show a more instructive error? (eg. "Use the `spin` CLI in order to create a pipeline based on v2 templates").

**Comment by jtk54** [comment]
@louisjimenez is addressing this.

**Comment by louisjimenez** [comment]
Hey @costimuraru we are planning on adding full support in the UI for MPTv2. In the short term, we are working on a patch to update the UI and make it clear what works for v2 and what doesn't. Here is one of the upcoming fixes https://github.com/spinnaker/spinnaker/issues/4056

**Comment by louisjimenez** [comment]
I'm going to close this as it has now been addressed via https://github.com/spinnaker/deck/pull/6660 and it will be a part of the next patch release. V2 pipeline templates are now filtered out of the template source list when creating a pipeline. Long term, this functionality will be added as part of https://github.com/spinnaker/spinnaker/issues/3980.
