### ISSUE TITLE
CF - investigate how to introduce shared services

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#3945]
### Issue Summary:
Feature request to introduce shared services.
CF documentation https://docs.cloudfoundry.org/devguide/services/sharing-instances.html

### Cloud Provider(s):
CF

### Feature Area: 
Deck, Clouddriver

### Description:
Currently we do not allow a user to share services to different regions (org/space). There is a request to enable shared service functionality

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by Jammy-Louie** [comment]
* There is an assumption here that the user running the cf commands has the privileges to run `cf enable-feature-flag service_instance_sharing` to enable the share service feature flag.

* once we enable share service according to the documentation we need to  ensure all services are unshared before attempting a delete. There is a sample script to delete all shares in the cf documentation.

* Not all services can be shared. It depends on the implementation

**Comment by stuart-pollock** [comment]
Some notes from our investigation:

- user-provided services cannot be shared
- if an instance is shared from Space A to Space B, and Then is shared again from Space B to Space C, then removing the share from Space B does not remove the share to Space C
- the feature flag for sharing must be set at the CF Foundation-level, and must be done outside of Spinnaker (`cf enable-feature-flag service_instance_sharing`, at https://docs.cloudfoundry.org/devguide/services/sharing-instances.html)

We used the service broker [bookstore](https://github.com/spring-cloud-samples/bookstore-service-broker) and modified its metadata to make it shareable.  We then followed the ensuing steps to build and publish it:

```
$ ./gradlew build
$ cf push -f deploy/cloudfoundry/manifest.yml
$ cf create-service-broker bookstore admin supersecret  https://bookstore-service-broker.apps.atherton.cf-app.com
$ cf enable-service-access bookstore
$ cf create-service bookstore standard to-be-shared-bookstore
$ cf share-service to-be-shared-bookstore -o dev-dev -s space-space
```
