### ISSUE TITLE
${scmInfo} and ${scmInfo.branch} expressions are not working after upgrade to 1.11.9

### ISSUE THREAD

**Issue by nitrogear** [spinnaker/spinnaker#3946]
### Issue Summary:
scmInfo and scmInfo.branch expressions are not working

### Cloud Provider(s):
AWS, running on Kubernetes

### Feature Area: 
Pipeline expressions

### Description:
We have working pipeline where parameter had expression in parameter:
https://s3.amazonaws.com/xxx/liveboard/application/${scmInfo.branch}/${trigger.buildInfo.artifacts[0].displayPath}
After upgrade from Spinnaker 1.11.3 to 1.11.9 pipeline started failing with warning:

`Failed to evaluate [APK_URL] EL1007E: Property or field 'branch' cannot be found on null`

### Steps to Reproduce:
1. Create pipeline with trigger type Jenkins
2. Add parameter with expression ${scmInfo.branch} in it
3. Trigger pipeline execution by Jenkins job and warning will be generated

### Additional Details:
I checked JSON output of source link for the pipeline executions before and after upgrade and see that in 1.11.3 we had object `trigger['buildInfo']['scm']`, but it's absent in execution of 1.11.9

**Comment by ezimanyi** [comment]
@nitrogear :  I suspect this is due to an issue on the jenkins-git plugin side.  See #3927 for some more details on how to fix the issue.

**Comment by nitrogear** [comment]
@ezimanyi you're right. Root cause of the issue is in git-plugin
