### ISSUE TITLE
Could not load "versions.yml" from config bucket : Installing Spinnaker using halyard from a no-internet access box.

### ISSUE THREAD

**Issue by learnteds** [spinnaker/spinnaker#3951]
Does anybody know how to fix the issue, Could not load "versions.yml" from config bucket. I am trying to install Spinnaker using Halyard but in VM with no internet access.

Is there anyway to avoid halyard checking this or I could load versions.yml locally somewhere and point Halyard to it. Please advise.

**Comment by sparciii** [comment]
When installing locally you can disable GCS reads alltogether by setting the following in `/opt/spinanker/config/halyard-local.yml`:

> spinnaker.config.input.gcs.enabled: false

The documentation at https://www.spinnaker.io/guides/operator/custom-boms/
 provides additional detail as well as how to set `versions.yml` locally.

I'm able to install and run halyard/spinnaker in a environment without public access (we're behind corp firewall). 

Hope that helps!

**Comment by LewisHope** [comment]
You can disable GCS: 
/opt/spinanker/config/halyard.yml
`spinnaker
      config
          input
             gcs
                 enabled: false`

**Comment by LewisHope** [comment]
You can disable GCS:
`/opt/spinanker/config/halyard.yml`
> spinnaker.config.input.gcs.enabled: false

**Comment by dxxd116** [comment]
You could change the DEAULT_JVM_OPTIONS in /opt/halyard/bin/halyard. Add in proxy settings to it 

```
  -Dhttp.proxyHost=<Your PROXY HOST> -Dhttp.proxyPort=<Your PROXY Port> 
  -Dhttps.proxyHost=<Your PROXY HOST> -Dhttps.proxyPort=<Your PROXY Port> 
```
then 
```
hal shutdown
hal 
```
Then it should work like charms.
