### ISSUE TITLE
RFC - Dynamic account discovery in Clouddriver

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#3969]
For the majority of users, Spinnaker's configuration is "set it and forget it" meaning that once they stand it up a large portion of it never changes. However, while working with users in the Kubernetes SIG we've found that cloud provider accounts are something that change frequently and enough that having to modify configuration and roll out Clouddriver can be painful and difficult to automate. With this RFC I hope to define the following:

1) A mechanism for discovering/providing account configuration dynamically.
2) A mechanism for reconfiguring account credentials without having to restart/redeploy Clouddriver.

Based on conversations I've had with community members in the past, I've identified a few use cases where this would be a helpful feature:

1) Cluster provisioning/de-provisioning
Since Kubernetes has become a first class offering for the majority of cloud providers, cluster provisioning/de-provisioning has become very easy to automate. Once these clusters have been provisioned users have to manually add them to Spinnaker's configuration for them to show up as deployment targets.

2) Credential rotation
Kubernetes accounts require a `kubeconfig` so that `kubectl` knows how it should authenticate with tke Kubernetes API. For platforms like EKS and GKE, you can use non-static credentials (via `aws-iam-authenticator` or `gcloud`) but some users choose to use `ServiceAccounts` or some other static credential. Again, rotating these credentials required reconfiguration and redeployment.

3) New team onboarding
One common pattern I've seen when working with teams is that each team gets a "isolated" slice of N clusters, typically segmented by namespace and given their own `Role` and `RoleBinding` to ensure correct permissions. Each of these segments then have their own accounts within Spinnaker which are further controlled by Fiat permissions. While this type of configuration only happens at scale, the faster teams onboard the more painful it becomes to keep up with the demand. 

We (the Kubernets SIG) plan on spending some time during our next meeting (2/26) to discuss this in more depth after which I'll likely spend some time building out a design doc with a proposed implementation and further documentation.

### Other notes
* This may also apply to other aspects of Spinnaker, specifically Jenkins or Artifact accounts.
* I don't imagine this is a purely Kuberntes problem as I know there are many orgs which have numerous AWS accounts or GCP projects.
* Automating this today requires custom tooling and we don't have a common, community defined solution to alleviate this pain.

**Comment by robzienert** [comment]
Great proposal. I've got a couple thoughts to pile on, here.

In terms of use case, some organizations (Netflix) for example, the operators of Spinnaker are different from those who provision new accounts in AWS or Titus. It would be beneficial if a third party team could remotely dictate both what accounts are available, the locations they're in, as well as the permissions required to gain access to said accounts.

I haven't (yet) dug too deep into what bits of clouddriver need to be refactored, but one requirement we'll need is to have a separate service provide the account credentials. Speaking for myself only, I'd like to see an interface that can poll a separate system and then cache account credentials into a common, shared store... sorta like having a `CachingAgent` for account credentials. Key thing for me here is that a service outage of this credentials provider should not prevent clouddriver from starting or continuing to operate, regardless of how long it's offline for.

**Comment by ethanfrogers** [comment]
Agreed, that's a pattern we've seen as well. My initial, perhaps naive, thoughts were to provide a simple endpoint(s) to query for this information. This would allow users manage that data however they see fit and, potentially, manage different accounts in different ways. In it's simplest form, you may maintain a single file in something like S3 and automate changes with some external process. In the more complex case, perhaps we provide some type of API (your separate service) which would allow external teams to register new accounts. In either case, the interface is the same - provide a valid list of credentials/account configurations which could be consumed by Clouddriver.

**Comment by robzienert** [comment]
Am I correct in interpreting you're proposing more of a push over pull model?

I'm personally biased towards a pull model; I don't think we need new endpoints. Rather, Clouddriver would have an interface that would allow you to implement some mechanism for providing credentials, be it local or remote. The default, of course, our current (hypothetical) `LocalCredentialsProvider`. Additional implementations may be an S3/GCS thing or potentially a standalone internal service.

This touches on some interesting scope creep: Are we just interested in dynamically provisioning accounts and credentials, or additionally what cloud providers are and are not enabled?

**Comment by avram** [comment]
All of this basically sounds like making the bits of clouddriver-local.yml around account specification able to be runtime-adjustable and sourced remotely (file, API call, etc.), which would serve our purposes well.

There are interesting options around walking things like the AWS Organizations API to do more complete auto-discovery, but there is so little we can take for granted in terms of account discovery that I agree with both of you that the next step basically should be making clouddriver able to pull from an external source of some sort.

**Comment by duftler** [comment]
Probably worth looking at https://spring.io/projects/spring-cloud-config,
especially if scope is beyond just credentials handling.

**Comment by ethanfrogers** [comment]
@robzienert from Clouddriver's perspective it'd be pull. However we choose to implement the service for providing the credentials is still up for debate but I imagine it'd almost have to be a push to that service (or file, or whatever). To @avram comment - I feel like discovery via cloud provider APIs is a logical progression but after thinking through it a bit I imagine there would be too much "customization"(?) for it to be practical. For example, let's say you want to split a Kubernetes cluster up into individual accounts, per the use cases above. We'd need to provide some mechanism for determining how an account is split up, though, maybe that's purely a concern for Kubernetes and doesn't map well to AWS or GCP. 

@duftler I actually stumbled across that while doing research for this feature. My initial thought was we could combine `spring-cloud-config` with `spring-boot-actuator` and `@RefreshScope` to provide a means of remote configuration and runtime adjustment for _all settings_ but @imosquera pointed out to me that it might actually reduce the safety we get from immutable configs. Imagine a scenario where you change the Redis endpoint on the fly - if there's any problem with the connection then things would automatically bomb. I think there's a lot of value in enabling Spinnaker to source config from a remote location but the above potential issues scare me a bit.

**Comment by bytesandwich** [comment]
I've been thinking through an approach I want to take to dynamically resolve AWS accounts, roles, and read/write permissions in clouddriver. Maybe it will inform our discussion about a general solution for all providers.

# How we set up one account in spinnaker with multiple roles for different users

Our spinnaker accounts are each an **AWS account** plus an **AWS Role**. I think this is normal. My current structuring of spinnaker accounts looks like:

```
hal config provider aws account add AWS-Some-Team-Account_Developer-Role \
  --assume-role role/Role-For-Developers
  --read-permissions  DL-Some-Team-Teammembers \
  --write-permissions DL-Some-Team-Developers DL-My-Team-Admins
```
and we might have anothers like:

```
hal config provider aws account add AWS-Some-Team-Account_Admin-Role \
  --assume-role role/Role-For-Admins
  --read-permissions  DL-Some-Team-Admins \
  --write-permissions DL-Some-Team-Admins
```

So user Joe might be able to use:
- AWS Account A, role A_admin
- AWS Account B, role B_developer

While Jim sees:
- AWS Account A, role A_developer
- AWS Account C, role C_developer


# How we're tying spinnaker into AWS IAM roles/policies

If you're running spinnaker in AWS, it has an instance/container profile which has trust relationships with roles to assume on behalf of users, and the roles have fine grained permissions in IAM. This all set up in AWS and doesn't live inside spinnaker.

This is important to us because **everything is locked down by IAM roles and policies**. Whatever a user does in spinnaker happens in their IAM role, which authorizes their actions and is auditable by many tools out of the box.


# Clouddriver dynamically resolving this data per account

1. clouddriver can query the AWS organizations api to get the list of accounts.
2. It then needs to determine the mapping from account to roles, and from roles to reader/writer groups

## account name => list of roles
I think it may be necessary to create a role in each account with a naming convention, that spinnaker knows it can assume and use to list the rest of the roles in that account.

1. spinnaker finds account: AWS-My-Team-Account
2. spinnaker adds suffix by convention AWS-My-Team-Account-Spinnaker-Account-Discovery-Role
3. spinnaker assumes the role AWS-My-Team-Account-Spinnaker-Account-Discovery-Role
4. spinnaker lists all the roles in AWS-My-Team-Account-Spinnaker-Account
5. the ones that have the right tags, clouddriver keeps


## role => list of reader/writers
I think this can be done pretty easily with some tagging convention for roles, like

```
list-role-tags --role-name AWS-Some-Team-Account_Admin-Role
> {
>     "read-permissions": ["DL-Some-Team-Admins"]
>     "write-permissions":  ["DL-Some-Team-ADMINS"]
> }
```

**Comment by ethanfrogers** [comment]
@bytesandwich thanks for the input! i like the idea of convention based discovery as it's a common pattern, especially with the AWS provider. my only concern is how that maps to something like Kubernetes where we don't have the same constructs. if we're talking about something like EKS or GKE i imagine we could so something with namespace annotations where you define the list of roles that could access that particular namespace and build accounts based on that metadata once each cluster has been discovered. in the case of on-prem (or self built) clusters the user would need to provide a cluster discovery mechanism.

**Comment by indrayam** [comment]
@ethanfrogers 

As a Spinnaker + Kubernetes v2 provider in our company, I think there is no hyperbole in me stating that this issue *singlehandedly* is killing us in our ability to drive company-wide adoption of Spinnaker. 

Why?

Let me play out a very typical scenario:

- An IT Delivery Organization decides to build a new software
- Technical lead from that IT Delivery Org goes to our internal Cloud Console and requests Kubernetes namespace (to be precise, OpenShift Projects) 
- They then request a CD pipeline for this software. As part of the pipeline, besides other things, we programmatically setup Spinnaker Account(s), Application and Pipelines

So far so good. But this is where things start to go downhill fast!

- We force the developer to sit around and wait until we can find a good time (every 60 mins or 120 mins) to restart our **production** Spinnaker Clouddriver. *Translation:* Bad Developer Onboarding Experience. *Translation:* Spinnaker gets dinged every before a single has been run! 😢 

This feature will do wonders in making Spinnaker + Kubernetes v2 provider mainstream as more Enterprises embrace Kubernetes as their Container Orchestrator of choice and try to build a CD pipeline that can work with Kubernetes, regardless of where it is run.

**Comment by avram** [comment]
@indrayam While I agree that dynamic discovery will make things easier, Clouddriver can be safely deployed without downtime, and deployed dozens of times a day without downtime. Our deployment does require that we specify the new account manually whenever a new one is onboarded, but we deploy Spinnaker with the new config without interrupting our users.

**Comment by indrayam** [comment]
@avram You know, this is definitely great to know. However, can you add more color on this statement:
`we deploy Spinnaker with the new config without interrupting our users`

How exactly are you guys pulling this off? I mean, when Kubernetes Controller is restarting clouddriver deployment, how are you ensuring that existing users are not impacted? Are you relying on Kubernetes and the Rolling Upgrades feature or is there some Spinnaker secret sauce that I am missing

**Comment by ajordens** [comment]
Thoughts @emjburns

**Comment by milesmatthias** [comment]
Manually running a script on the halyard pod is what everyone seems to be doing, but it would great to have the option to have Spinnaker automatically recognize new clusters. Keep in mind lots of Spinnaker customers are using Terraform to provision new Kubernetes clusters, so having an easy way to trigger an update to Spinnaker within/as a result of running Terraform would be awesome.

One common workaround I see is having Terraform create the K8s cluster, create the K8s service account that Spinnaker will use in `kubeconfig` to connect to the cluster (RBAC support), and then write out the cluster's IP, the K8s service account token, and the cluster's certificate to a store like S3 or GCS, and then running a script on the halyard pod to add the new cluster definition to Spinnaker so it can be used as a pipeline target.

**Comment by indrayam** [comment]
@milesmatthias Thanks for sharing. Our approach is similar to the one you have shared. We do not use Terraform and instead of S3 or GCS, we write it to Minio, the same Minio that we use for our Spinnaker Persistent Store.  While it works, I do not think this is an **ideal** end state for clouddriver v2 😢 

We should definitely strive to offer a capability whereby Kubernetes cluster configurations are either read (and cached in Redis) at startup-time and then continuously polled (for changes) at a pre-configured interval or read at runtime. Both these have their pros and cons, and we can debate the ideal approach. What is undeniable is that the current approach will not scale. At least, not for very large Enterprise Kubernetes deployments like the ones we have.

**Comment by robzienert** [comment]
@milesmatthias Interested in talking more about the Terraform auto-update idea, although that sounds somewhat separate from this specific issue (providing a dynamic config vs feeding said config). Hit me up on Slack if you're interested to talk more.

**Comment by jkschneider** [comment]
@ethanfrogers concerning this:

> Imagine a scenario where you change the Redis endpoint on the fly - if there's any problem with the connection then things would automatically bomb.

We don't need to necessarily source ALL configuration from config server. Focus initially on artifact and provider account configuration where the impact of `@RefreshScope` is more easily reasoned about and expand from there.

**Comment by ethanfrogers** [comment]
Thanks a good point, @jkschneider. Also, thanks for reminding me about artifact accounts. I think that makes sense for the scope of this project.

**Comment by jkschneider** [comment]
Also, just as a general item of interest: we (Spring team) are mulling over expanding the capabilities of Spring Cloud Config Server to include scoped properties, etc. such that it could be a suitable replacement for the aging Archaius Server at Netflix potentially. So employing it here in Spinnaker generally could be a win for them as well internally. cc / @robzienert

**Comment by ajordens** [comment]
@indrayam Not Kubernetes here, but we just do a regular red/black of `clouddriver` onto a new build with updated configuration. It's our choice what goes into the new build, sometimes it's code, sometimes it's configuration and sometimes it's code + configuration.

One could theoretically automate a .yml containing _only_ account details (and this yaml would be included by your normal clouddriver.yml). 

Adding new accounts is easy, there are nuances with accounts being disabled that this proposal would need to consider (cleaning up data that was indexed from a disabled account).

I'm motivated to see a significant reduction in the amount of configuration we're having to manage for each account and delegate that to an external service (the pull model discussed above).

**Comment by ethanfrogers** [comment]
@robzienert @jkschneider the more thought I put into this the more I keep coming back to Spring Cloud Config. As I talk to users I hear more properties that they'd like to be dynamic: base images in Rosco, Artifact accounts, Jenkins masters, etc. All of these properties could be sourced dynamically from a Cloud Config server (Halyard, perhaps?) and reloaded on the fly using OOB Spring capabilities. Instead of reinventing the wheel, I think I might explore that avenue a little bit.

One bit of feedback I got from the Kubernetes SIG was about config drift/consistency. Managing config in 2 places (Halyard + "dynamic account service") could lead to some interesting issues. If we make Halyard a config server we could alleviate those concerns.

**Comment by mdirkse** [comment]
Is the design document available yet? We designed [a whole service](https://www.youtube.com/watch?v=3GMxzYVqISo) that works around the problem that this proposal will solve, so I'm very interested :)

**Comment by ethanfrogers** [comment]
@mdirkse I had a decent start on it but have since changed the scope/approach to make it more generic. I actually just started rewriting the proposal. Will share when it's ready!

**Comment by andreasevers** [comment]
I've created a design document (coached by @jkschneider) describing how dynamic account discovery could be built in using Spring OOB features like the `/refresh` endpoint:
https://docs.google.com/document/d/1qrSxHMwZHrpiyAM25986a5V_rzfSOlVLhlC-BpOruyE/edit#

The current way of discovering credentials and providers is using prototype beans. I believe this can be simplified, while setting us up nicely for integration with e.g. the Spring Cloud Config server (or perhaps Halyard).

**Comment by cfieber** [comment]
The existing implementation is not radically different from spring config server, it just predates that project being something we could have considered using. Not being able to use the existing /refresh endpoint is likely a bug in the provider implementation. (Not surprising given the complexity around it)

That said, I think one of the biggest mistakes in the clouddriver codebase is the necessity to create beans per item in a list of config - spring doesn't do that well at all and the complexity that ended up in the clouddriver codebase as a result (and then the even crazier complexity of then attempting to make all that config refreshable...) is not warranted in my opinion.

I'd love to see a fresh approach at this where we have account credentials repository backed by the clouddriver datastore (SQL or whichever) and make all the current beans that we create per account singletons that can do work given an account to work on - I would be happy to collaborate with someone on that if there is interest.

**Comment by cfieber** [comment]
As a concrete example, instead of an instance of an Amazon cluster caching agent per account * region just have one that provides a service method to perform caching for a region in an account and have a work scheduler that loops on:
1) select all accounts
2) find accounts/regions that need refreshing
3) schedule a refresh job for that account/region

**Comment by andreasevers** [comment]
@cfieber could you take a look at my PR (https://github.com/spinnaker/clouddriver/pull/3539)?
I've simplified the bean creation logic from prototypes to singletons, and might just fix the issue you were raising.
