### ISSUE TITLE
Pipeline Configuration headers listing missing Expected Artifacts

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker#3970]
### Issue Summary:
In the pipeline editor, for the Configuration area, there is a headers listing along the left. In that list, "Expected Artifacts" is missing.

### Cloud Provider(s):
Observed with k8s v2 provider.

### Environment:
1.12.1

![image](https://user-images.githubusercontent.com/942631/52726946-343a4a00-2f82-11e9-961e-c97c33ded2a9.png)

**Comment by maggieneterval** [comment]
Just a note that Louis is going to tackle this but we can't assign him issues until he's made five PRs to be added to the org.
