### ISSUE TITLE
Add hal command for tweaking the component sizings (replicas, limits, requests)

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#3981]
### Issue Summary:
Hal supports specifying the number of replicas for each service, by manually editing the `customSizing` section in the hal config file (ie. `/home/spinnaker/.hal/config`), as specified here: https://www.spinnaker.io/reference/halyard/component-sizing/

> Custom sizing must be **manually** added to the Halyard Configuration, **there are no CLI commands** or flags to enable these settings.

However, when deploying hal via its [helm chart](https://github.com/helm/charts/tree/master/stable/spinnaker), we are not able to edit this file, unless we run some hal commands.

We would therefore need a hal command to update the `customSizing` section.

Replicas:
```sh
$HAL_COMMAND config deploy component-sizing clouddriver edit --replicas 2
$HAL_COMMAND config deploy component-sizing orca edit --replicas 10
$HAL_COMMAND config deploy component-sizing echo edit --replicas 2
```

Requests/limits:
```sh
$HAL_COMMAND config deploy component-sizing clouddriver edit --pod-requests-cpu 250m --pod-requests-memory 512Mi

$HAL_COMMAND config deploy component-sizing clouddriver edit --pod-limits-cpu 1 --pod-limits-memory 1Gi
```

### Cloud Provider(s):
Kubernetes

### Feature Area: 
Halyard

**Comment by louisjimenez** [comment]
@spinnakerbot add-label component/halyard

**Comment by milesmatthias** [comment]
Suggestion -- generalize this issue to both functions of customSizing -- requests/limits + replicas.

**Comment by costimuraru** [comment]
Added a fix via: https://github.com/spinnaker/halyard/pull/1219

Validated and it works quite nicely (tried it on AWS EKS):

```
$ kubectl get pods -n spinnaker

spin-clouddriver-7867dbc8f5-k6rxb   2/2       Running     0          2m
spin-clouddriver-7867dbc8f5-mqght   2/2       Running     0          2m
spin-clouddriver-7867dbc8f5-s55cb   2/2       Running     0          1m
```

```
$ kubectl get pods -n spinnaker spin-clouddriver-7867dbc8f5-k6rxb -o yaml
```

```yaml
spec:
  containers:
    image: gcr.io/spinnaker-marketplace/clouddriver:4.3.1-20190130095322
    ...
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
```
