### ISSUE TITLE
RFC: SQL as a standard persistence backend

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#3982]
## Motivation

Spinnaker currently uses Redis as the default one-size-fits-all persistence backend. This was done to help ease the hurdles of onboarding Spinnaker within an organization. Redis is easy to use and highly flexible which makes it easy to apply to most any use case from a development perspective, but its operational characteristics are left wanting in a production environment.

Netflix has already begun converting services, where applicable, over to SQL. The choice for SQL is multi-part:

1. SQL is operationally ubiquitous and familiar to a large percentage of developers.
1. SQL offers a dramatically better durability story than Redis
1. Many of our data models are relational and modeling this in Redis can be quite inefficient.
1. Modern SQL flavors, such as Aurora, Spanner, and Cockroach can offer a good high availability story even in the face of master failure (or in some of these cases, don't really suffer from master failure scenarios).

Orca's Execution storage is optionally now in SQL and provides a better reliability story for users and operators alike. Netflix has also observed it performing anywhere between 2-20x better than the Redis implementation, with plenty of room for additional improvements.

Netflix is nearing completion of an effort to add a SQL persistence backend for Clouddriver as well, to both serve task status as well as store provider cache data. The cache data models are inherently relational and the Redis implementation performs a dramatic amount of inefficient operations to build responses to requests. We've observed while the write latency is higher, read operations are largely much lower and have a much tighter and predictable p99.

With one clear success and a very promising second in the near future, I'm proposing adding SQL as a standard storage option across all services, where it makes sense.

## Scope

Redis still makes sense in a few cases where SQL does not make a good fit, namely in queue behavior and distributed locks. With that in mind, I'd like to propose adding SQL to the following services:

1. Gate for user session storage. I believe this should be plug-and-play in Spring Boot so this lift should be easy.
1. Front50 for configuration storage. Blob stores are great, but front50's heavy caching causes upstream complexity and occasional user grief when eventual consistency is not correctly handled. Furthermore, while solutions such as minio are available for non-cloud deployments, it's likely a new and operationally unfamiliar system for companies to onboard making adoption of Spinnaker even more difficult for these orgs.
1. Echo. This could be a proposal on its own, we could probably do well to get rid of the `scheduled-actions` library and use Quartz directly, using its SQL backend to better support an HA cron scheduler story. Echo also uses Redis for pubsub notification deduplication; SQL wouldn't be a great fit here but could certainly be attainable.
1. Igor. Tracking of builds and new docker tags.
1. Fiat. Storage of permissions.

**Comment by willgorman** [comment]
@robzienert Do you know if any of these are being worked on?  We're interested in SQL for Front50 and may be able to work on that but didn't want to pick it up if it was already in progress.  I saw @ajordens mention SQL support on spinnaker/front50#525 but that's the only reference that I've found so far.

**Comment by robzienert** [comment]
@willgorman Front50 is being worked on in private right now within Netflix. Our goal is to run it in production this quarter. The other services have not been started (outside of Clouddriver and Orca).

**Comment by robzienert** [comment]
Forgot to mention this was accepted, thus it being closed.
