### ISSUE TITLE
create application via api

### ISSUE THREAD

**Issue by darkrasid** [spinnaker/spinnaker#3986]
### Issue Summary:

Want to find api docs for create application

### Cloud Provider(s):
k8s

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):
api 

### Description:

Hi.

Is there any api can make application?

Because it is possible create application via cli tool(spin), I guess it is.
However I cannot find it.

### Steps to Reproduce:
Not bug

**Comment by ethanfrogers** [comment]
@darkrasid Applications are not created via a direct API but are carried out by submitting a `createApplication` task to Orca. See the `spin` implementation here (https://github.com/spinnaker/spin/blob/master/cmd/application/save.go#L102-L116).
