### ISSUE TITLE
[Halyard] Feature Request: Add cron to halyard container

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4029]
### Issue Summary:

Would love to add cron to the halyard container that is deployed when deploying distributed Spinnaker to a K8s cluster. Full description below.

### Cloud Provider(s):

Any with K8s.

### Environment:

K8s

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):

Halyard container

### Description:

It would be great to have cron available in the Halyard pod when deploying spinnaker to Kubernetes. Initial configuration and hal commands can be run on the initial install, but as the environment changes, it would be great to be able to schedule scripts to run periodically that may need to update the Spinnaker instance.

For example, if Spinnaker is responsible for deploying to all of your K8s clusters, and you add a new cluster to your environment, how is it registered with Spinnaker so it can deploy to it? Right now, you have to manually run hal commands to add the new cluster, but having cron in the halyard pod would allow for periodic checks that Spinnaker knows about all the clusters (via an event queue or some central registration). The alternative here is opening an API endpoint in the halyard pod to trigger a script, but for security reasons, I'd rather have a periodic script pulling that data.

**Comment by ethanfrogers** [comment]
@milesmatthias I'm actually working on a proposal to address adding accounts dynamically. Would be great to have your feedback on it! https://github.com/spinnaker/spinnaker/issues/3969

**Comment by milesmatthias** [comment]
@ethanfrogers thanks! I wrote a note in that issue.

Would still be *great* to have this so manual scripts aren't an issue.

**Comment by milesmatthias** [comment]
I started on a PR for this, but I don't have this working yet: https://github.com/milesmatthias/halyard/commit/6e627293d931edaca48d520125a1aad23366deaa

**Comment by milesmatthias** [comment]
Err -- a container should really only have 1 process running and it's not a good idea to put cron in the background of the container, so closing this.

If anyone else sees this, we're going with a dual container pod approach to address this need.
