### ISSUE TITLE
Unable to trigger deployment on GCR image push

### ISSUE THREAD

**Issue by BIGPHATTOBY** [spinnaker/spinnaker#4038]
### Issue Summary:
Spinnaker is unable to automatically trigger pipelines on pushes to our GCR repo.

Newly pushed images will show up our manual deployment tag option, and looking at cloud-driver logs it is able to cache the new images, nothing is raised in echo or igor.

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker running inside kubernetes, trying to automatically trigger and deploy images to other kubernetes clusters.

### Description:
As per recent, it has worked flawlessly, the majority of our staging environments is configured to automatically deploy the newest tag.

IGOR reports that it finds no new images for our various registries
```2019-02-26 09:44:19.544  INFO 1 --- [RxIoScheduler-3] c.n.spinnaker.igor.docker.DockerMonitor  : Found 0 new images for gcr-vml``` even though cloud-driver is able to pick them up and present the option doing a manual deployment.

We are using using this feature plenty but can't exactly pinpoint when it stopped working, a theory is that the upgrade to 1.12.2 have caused this and the plan is to downgrade back to 1.12.0 tonight to test that.

Rebooting the pod and trailing logs presents no errors in terms of services being unable to communicate with each-other

### Steps to Reproduce:
Deploy spinnaker 1.12.2 on a kubernetes cluster
Configure GCR as container registry
Set up an automatic trigger on the GCR repo
Push a new image
??
no profit

Please comment if additional information is required, I will continue to debug and continuously update.

**Comment by brunsgaard** [comment]
Could this be related
https://community.spinnaker.io/t/gcr-docker-registry-catalog-endpoint/1117

**Comment by BIGPHATTOBY** [comment]
It seems that the issue is internally with google, closing this issue
