### ISSUE TITLE
Error fetching applications. Check that your gate endpoint is accessible.

### ISSUE THREAD

**Issue by HouJiangtao** [spinnaker/spinnaker#4046]
### Issue Summary:
After deploy spinnaker on ubuntu 18.04, error "Error fetching applications. Check that your gate endpoint is accessible" happened on applications page. Try to troubleshooting many times, still not work.

### Cloud Provider(s):
kubernetes

### Environment:
ubuntu 18.04

### Description:
I can go onto the the spinnaker page on ipaddress:9000 but when I go in the application screen the " Error fetching applications. Check that your gate endpoint is accessible." text is displayed. I have followed the suggested actions on the link provided with no succes.

I installed one minio storage docker image on localhost docker container. And map the container port 9000 to localhost 9001.

**Comment by HouJiangtao** [comment]
the gate service status is ok but using netstat -an I can't see the 8084 port is LISTEN. 
And form the log I can see some connection issue: 
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         ... 26 common frames omitted
Feb 27 02:26:37 k8s-spinnaker gate[24782]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_191]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         at redis.clients.jedis.Connection.connect(Connection.java:184) ~[jedis-2.9.0.jar:na]
Feb 27 02:26:37 k8s-spinnaker gate[24782]:         ... 33 common frames omitted

**Comment by HouJiangtao** [comment]
solved!!!   two actions. 1. front50 failed for I using localhost:9001 as the minio interface but can connection. should be public ip or internal ip. 2.  gate application always failed for redis server is not started, after I started it problem solved.

**Comment by bachrilq** [comment]
Hei Hou, can I ask a question? , I have the same problem with you, and I have already start Redis server but spinnaker can't recognize that, what should I do? , can you help me?

**Comment by HouJiangtao** [comment]
I using #"jouralctl -u gate"  to check if the gate application is start successfully. Then I found the redis connect problem and do next step. You should first using jouralctl -u xxx (front50,gate) to check if all your spinnaker service is ok then do the troubleshooting. If all is ok, then just follow the "I want to expose LocalDebian Spinnaker on a public IP address, but it always binds to localhost"  in doc https://www.spinnaker.io/setup/quickstart/faq//#i-want-to-expose-localdebian-spinnaker-on-a-public-ip-address-but-it-always-binds-to-localhost   to configure the url.  This is all my execute steps.

**Comment by manikarnam** [comment]
I am facing this issue while running my spinnaker "
Error fetching applications. Check that your gate endpoint is accessible." Could you help me, anyone 
Thanks in advance
