### ISSUE TITLE
[GCE] Spinnaker is unable to Terminate instances

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4050]
### Issue Summary:
Spinnaker is unsuccessfully terminating instances when asked in the UI. Task log and Clouddriver log says the event was successful, but upon further digging inside the GCP Cloud Console the request never even made it to GCP.

### Cloud Provider(s):
Google/GCE

### Environment:
Spinnaker version 1.12.2

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):
Assuming Clouddriver, not sure though

### Description:
When attempting to Terminate an instance via Deck, the instance is not terminated and is left alone. There are no errors in the logs and we only see trails that the event made it through Spinnaker, but no event made it to Google itself. We are able to successfully Destroy Server groups though, this is not a permission problem. Before upgrading to 1.12.2 from 1.8.5 we were able to terminate instances. 

```

2019-02-27 15:00:17.538  INFO 21 --- [0.0-8083-exec-8] c.n.s.o.c.OperationsController           : [USER] requested task:{"application":"APPLICATION","name":"Terminate instance: INSTANCE","stages":[{"cloudProvider":"gce","managedInstanceGroupName":"SERVERGROUP,"type":"terminateInstances","instanceIds":["INSTANCE"],"region":"us-east1","zone":"us-east1-c","credentials":"ACCOUNT","user":"USER","refId":"0","requisiteStageRefIds":[]}],"trigger":{"type":"manual","user":"USER","parameters":{},"artifacts":[]},"origin":"deck"}
```

### Steps to Reproduce:
1. Add a google account
2. Deploy an Instance
3. Terminate an Instance

### Additional Details:
<img width="1109" alt="screen shot 2019-02-27 at 9 54 46 am" src="https://user-images.githubusercontent.com/10604059/53503493-c445bc80-3a75-11e9-832c-1d8ec0cb97da.png">

**Comment by ezimanyi** [comment]
What's happening is that as of orca#2505, the terminate instances task is checking that the instance exists before trying to terminate it; but it appears that the search endpoint to actually look for instances is broken for the GCE provider.  I'll fix the search endpoint, which also fixes this bug.
