### ISSUE TITLE
CF - Add Artifactory Trigger support

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#4069]
### Issue Summary:
Add Artifactory Trigger support to spinnaker

### Cloud Provider(s):
DECK, IGOR And ORCA

### Additional Details:
PR for IGOR
https://github.com/spinnaker/igor/pull/377/files

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by emjburns** [comment]
@Jammy-Louie it would be pretty cool if this was a more generic artifact trigger: the event could be an artifact event ([a spinnaker artifact](https://www.spinnaker.io/reference/artifacts/#format). This would make it easier to add other artifact providers/a push based artifactory provider.

Is this what you are thinking? I see that the Igor PR already creates spinnaker artifacts.

**Comment by Jammy-Louie** [comment]
@emjburns yes this would be generic and not specifically for CF

**Comment by Jammy-Louie** [comment]
To configure an Artifactory trigger you will need to provide the following:
![Screen Shot 2019-03-11 at 2 33 13 PM](https://user-images.githubusercontent.com/8474965/54148607-de36b600-440a-11e9-9027-41e0f43f360a.png)

which will result in availability of artifactory trigger:
![Screen Shot 2019-03-11 at 2 32 51 PM](https://user-images.githubusercontent.com/8474965/54148670-fe667500-440a-11e9-8539-cb5d0b651ae2.png)

**Comment by jkschneider** [comment]
@emjburns Really good point. I think @Jammy-Louie misunderstood your question. Yes, the event type could be generic and we'll refactor that to make this the case. I hope we get to a Nexus trigger this week as well, and I suppose we would have discovered the generalization at that point ;)

**Comment by Jammy-Louie** [comment]
Hi @emjburns ,
We were looking into making the event generic but we noticed a potential problem that could occur in `echo`. When we were looking at another generic event, `BuildEvent` used by Jenkins, Travis and Wrecker in [BuildEventHandleL94-L98](https://github.com/spinnaker/echo/blob/ad0dcf8968135b8d96fb5414d9e09188e656425f/echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java#L94-L98). It doesn't seem to differentiate between the possible different CI systems and if you were using both Jenkins and Travis and had for whatever reason named master and the jobs the same you could potentially trigger the wrong pipeline. If we did the same thing and a user was using Artifactory and Nexus we could also potentially trigger the wrong pipeline. If this is not really a concern please let me know. Cheers!

**Comment by emjburns** [comment]
@Jammy-Louie I think the identifying information for an artifact should be what system it comes from, the name, and the version. That might look like having a trigger of type "Artifact" with field options like `provider` (this would be artifactory for what you implemented), `packageName` (I think this is what Artifactory Name is above?), and the constraints. This would address the problem of two identical packages from different systems.

**Comment by kuberkaul** [comment]
@Jammy-Louie just what I was looking for. I see this has been shipped with version 1.13.0. Any docs for usage ? Where would this config for artifactory that you have the image for go ? is that in hal config ? could you give more info ?

**Comment by kuberkaul** [comment]
I created an igor-local.yaml to override which now has 

```
artifactory:
  enabled: true
  searches:
    - name: djin-artifactory
      base-url: https://artifactory.x.io/artifactory:5000
      repo: docker-local/djin
      username: username
      password: password
```

what's the groupID here and is it necessary ?

once I do this I see the following : 

<img width="883" alt="Screen Shot 2019-03-25 at 9 32 58 PM" src="https://user-images.githubusercontent.com/2179966/54965145-9acd6300-4f45-11e9-9ffd-11fbe2a94fda.png">

but this will trigger for any update made to the repo ? Can I not get granular and pick the docker image for which to trigger ?

**Comment by Jammy-Louie** [comment]
@kuberkaul we are currently in process of the writing documentation, here is a our [doc](https://docs.google.com/document/d/12Ia3R2zVpbuaIsKXfe6MjbrxREJsxrAhPq_CwN2Aj1k/edit#) in progress. I hope it helps.

we will be adding these changes to HAL as soon as possible.

[groupId](https://maven.apache.org/guides/mini/guide-naming-conventions.html) is used to help uniquely identify your project across all other projects.

you we use expected artifacts to help you narrow the changes you are looking for.

**Comment by jkschneider** [comment]
> groupId is used to help uniquely identify your project across all other projects.

This is incorrect. `groupId` is an _optional_ filter to reduce the scope of artifacts seen by the AQL query. So if for some reason you have to point your AQL query at a virtual repository, you'd want to scope artifact changes down to `com.mycompany` or similar so Igor isn't doing work every time a new OSS library lands in that repo.

**Comment by seanpeters86** [comment]
Is there any way this could possibly be extended to support rpm packages within Artifactory? Spun up the config and doesn't seem to work (as I figured).

Would love to have a way to automate our existing build process of:
1. Build RPM package 
2. Publish to Artifactory 
3. Manually start spinnaker pipeline after small delay for that artifact to be visible within Artifactory 
4. Configure `Bake` stage with package name that matches in Artifactory repo

Not sure how much extra work this would be, but it sure would be nice as our organization is still requiring the use of RPMs (for now sadly)

----

Also general feedback, if you could use `username` and `password` OR an `apikey` field that would probably be better suited for this type of integration imo.

**Comment by jkschneider** [comment]
@seanpeters86 Yes, I assumed someone would add additional repository types as needed. You would need to add an RPM type [here](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryRepositoryType.java#L20) and conditionalize the AQL query with the type [here](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java#L122).

I imagine you'll also need an RPM artifact account type in Clouddriver and surfaced in Deck, depending  on how you actually download and consume RPMs today. Might be able to use the HTTP artifact type, I'm not sure.
