### ISSUE TITLE
Unable to take application snapshot

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4086]
### Issue Summary:
Unable to `Take application snapshot` due to an unknown server error.

### Cloud Provider(s):
Google/GCE

### Environment:
Spinnaker 1.12.4

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
When attempting to Serialize an Application inside of your Application config, you are given an error:

`Error:
There was an unknown server error.`

During this time there are no network calls or console errors indicating why this failed.

I've tested this on several applications and all give me the same error. We only use GCE infrastructure with GCS storage, which should fit the requirements to use this as per the UI:

> Currently only GCE infrastructure and GCS or S3 storage are supported.

### Steps to Reproduce:
1. Create an application
2. Deploy to GCE
3. Use GCS for storage
4. Select `Take application snapshot` from the `Config/Serialize Application` section in the UI
5. confirm with `Take snapshot`

### Additional Details:
![screen shot 2019-03-07 at 4 22 30 pm](https://user-images.githubusercontent.com/10604059/53993507-3ad95e80-40f5-11e9-80b2-fea152d26bf7.png)

**Comment by seanpeters86** [comment]
This is still happening on 1.13.0

**Comment by jtk54** [comment]
The application snapshot feature was more or less an experiment, is not being maintained, and is not fit for production use currently -- closing this issue out.
