### ISSUE TITLE
buildRPM task is missing

### ISSUE THREAD

**Issue by lluu** [spinnaker/spinnaker#4091]
### Issue Summary:
buildRPM task is missing from all micro services in release 1.12.4

### Cloud Provider(s):
AWS

### Environment:
Development.  I'm building Spinnaker RPMs 

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
all microservices, release 1.12.4

### Description:
git clone the microservices
echo - 5db9d437ca7f2fa374dcada17f77bbbb2965bd67
clouddriver - b5539c47aad309e24428abb8f8303aff45323b43
fiat - daf21b24330a5f22866601559aa0f7ac99590274
front50 - 3105e86b8c084ad6ad78507e3a5e5a427f290b99
gate - b238ab993ab25381ce907260879548ed74a4953f
igor - 63d06a5c5d55f07443dd60a81035b35cf96238e7
orca - bad45e78566449117b678a3317552cf53d0dd14e
rosco - 42f81a2501de6d40676d47661579a6106b5c3e8a

### Steps to Reproduce:
cd to a microservice folder, e.g. gate

./gradlew buildRpm -Prelease.useLastTag=true
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildRpm' not found in root project 'gate'. Some candidates are: 'build'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

### Additional Details:
The last release that i built was 1.10, and both buildRPM and buildDeb are available gradlew tasks.  Looks like buildRPM is still available for deck and spinnaker-monitoring, but don't exist any more for the microservices.

**Comment by jkschneider** [comment]
Run `./gradlew -I gradle/init-publish.gradle buildRpm`

**Comment by makmaddy17** [comment]
Hi Team,

We are facing the issue again when trying to install 1.17.1
**_Task 'buildRpm' not found in root project 'dev'._**
