### ISSUE TITLE
k8s secrets too large to allow kubectl apply

### ISSUE THREAD

**Issue by mdirkse** [spinnaker/spinnaker#4108]
Hi,

We run Spinnaker with a *lot* of accounts. This results in a pretty big secret that Halyard cooks up for Clouddriver. So large in fact that, when the configuration is changed and Halyard issues a `kubectl apply` to update it, an error occurs because the previous config, which is stored in `metadata.annotations.last-applied-config` for diff purposes, is too large for a k8s annotation. Annotations have a [fixed size](https://github.com/kubernetes/kubernetes/blob/0b4275b6c7ecd55cfd9916dbef8fe48ae4a8c733/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L35) of 256k, and trying to squeeze more in results in an error (see https://community.spinnaker.io/t/halyard-with-v2-metadata-annotations-too-long/894)

We've had this problem with several Spinnaker version, which makes sense because it's really a k8s problem. We've hacked around it for now by having Halyard do a `kubectl replace` instead of `apply`, but we'd rather this be fixed upstream. So the question is: what is the best way to tackle this problem? Would it be possible, for instance, to have Halyard split the config up into multiple secrets in order to avoid this problem?

**Comment by ethanfrogers** [comment]
@mdirkse there's another open FR for this here - https://github.com/spinnaker/spinnaker/issues/3968

Though, I wonder if ConfigMaps are effected by the annotation issue as well.

**Comment by mdirkse** [comment]
Ah, missed that one, will close this and go there instead.
