### ISSUE TITLE
Jenkins stage not remove deleted parameter in Json

### ISSUE THREAD

**Issue by JamieChe** [spinnaker/spinnaker#4133]
### Issue Summary:
Jenkins parameters in pipeline jenkins stage could not be updated accordingly in json when jenkins job in this stage is changed. 

### Cloud Provider(s):
Kubernetes. 

### Environment:
Spinnaker v1.12.1

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@ui

### Description:
When I have previous saved jenkins stage with parameterized job, these parameters in pipeline json file will not be removed/updated,  if I delete some params from jenkins side, or edit stage to change for other job in spinnaker web side.  
In this case, the stage will fail by reporting:  Failed to evaluate [deleted_param] : parameters['deleted_param'] not found

### Steps to Reproduce:
1. Create one jenkins job1 with paramA and paramB in jenkins. Create one pipeline and choose job1 in one jenkins stage, config paramA and B as any input value. Then save pipeline. Edit pipeline as Json, you could find paramsA and B in this stage are written in Json file. 
2. Edit spinnaker pipeline again, select jenkins job2 (with param C but not A/B ) in previous jenkins stage then save. When checking pipeline json, job2 with paramC is updated but param A and B are still there. 
3. This also happened when removing params B of job1 in jenkins side.  The spinnaker UI could be updated to only one paramA input for job1, but actually in Json the paramsB   still exists. 

### Additional Details:
As a  workaround, I could fix it by manually update json. But still hope it could be fixed,

**Comment by ezimanyi** [comment]
Looks like this has already been addressed in spinnaker/deck#6669 and will be included in Spinnaker 1.13.

**Comment by JamieChe** [comment]
Thanks for the info.
