### ISSUE TITLE
Spinnaker: ERROR Account my-openstack-account is not in a provider that   supports distributed installation of Spinnaker yet

### ISSUE THREAD

**Issue by adyanthaya17** [spinnaker/spinnaker#4141]
Hi,

I am currently referring to the document 

https://www.spinnaker.io/setup/install/environment/

and have set up my OpenStack of Pike version which has been enabled using halyard. I am currently facing the below issue while trying to run the below command:

root@halyard:/home/oss# hal config deploy edit --type distributed --account-name openstack-account
+ Get current deployment
  Success
+ Get the deployment environment
  Success
- Edit the deployment environment
  Failure
Problems in default.deploymentEnvironment:
! ERROR Account openstack-account is not in a provider that
  supports distributed installation of Spinnaker yet

- Failed to update your deployment environment.

I have made sure to update as seen below:

hal config provider openstack enable
+ Get current deployment
  Success
+ Edit the openstack provider
  Success
+ Successfully enabled openstack

Is there a configuration I am missing to get the OpenStack in the provider list?

Thank you.

**Comment by seanpeters86** [comment]
Have you followed all the steps here already? https://www.spinnaker.io/setup/install/providers/openstack/

**Comment by emjburns** [comment]
https://github.com/spinnaker/spinnaker/issues/4316
