### ISSUE TITLE
Inconsistent Singulars And Plurals For Mapping And Unmapping LBs

### ISSUE THREAD

**Issue by stuart-pollock** [spinnaker/spinnaker#4147]
### Issue Summary:
Singulars and plurals are used inconsistently for mapping and unmapping LBs.

### Cloud Provider(s):
CF

### Environment:
CF version 2.0 and greater, additional details if applicable

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
CLOUDDRIVER

### Description:
In the 'Server Group Actions' menu, 'Map Load Balancer' should be singular (it is) and 'Unmap Load Balancers' should be plural (it is not).  In the Map Routes dialog, 'Map route' should be singular (it is not).  In the Unmap Routes dialog, 'Unmap routes' should be plural (it is).

### Additional Details:
![singular-map-singular-unmap](https://user-images.githubusercontent.com/1123244/54636268-71e83200-4a5c-11e9-89d1-f8c65055a11d.png)
![plural-map](https://user-images.githubusercontent.com/1123244/54636270-71e83200-4a5c-11e9-99c3-2431a9bd5eda.png)

**Comment by stuart-pollock** [comment]
@spinnakerbot add-label provider/cf
@spinnakerbot add-label bug

**Comment by jasonjchu** [comment]
Note:  a decision was made during a meeting to make the pipeline stages and Server Group Actions menu items for mapping and unmapping load balancer be singular.
