### ISSUE TITLE
Restrict template variable scope on MPTs.

### ISSUE THREAD

**Issue by stewchen** [spinnaker/spinnaker#4158]
### Issue Summary:
MPTs are able to access pipeline config variables not found in the `variables` section of a MPT.

### Feature Area:
MPT v2

### Description:
The MPT is able to access pipeline config variables that are not strictly defined in the MPT. This should probably be more locked down to only the variables defined in the MPT.

**Comment by jtk54** [comment]
@stewchen can you drop an example template/config where this happens and what the expected example is?

**Comment by stewchen** [comment]
Sample config:
```
{
  "application": "SampleApp",
  "index": 2,
  "inherit": [],
  "name": "Test Pipeline",
  "schema": "v2",
  "template": {
    "reference": "spinnaker://testMPT",
    "artifactAccount": "front50ArtifactCredentials",
    "type": "front50/pipelineTemplate"
  },
  "variables": {
    "account": "ok"
  }
}
```

MPT:
```
{
  "schema": "v2",
  "variables": [],
  "id": "testMPT",
  "protect": false,
  "metadata": {
    "name": "Test MPT",
    "description": "A manual MPT.",
    "scopes": [
      "global"
    ]
  },
  "pipeline": {
    "keepWaitingPipelines": false,
    "lastModifiedBy": "anonymous",
    "limitConcurrent": true,
    "stages": [
      {
        "failPipeline": true,
        "instructions": "Continue for ${ templateVariables.account }?",
        "judgmentInputs": [],
        "name": "Manual Judgment",
        "notifications": [],
        "refId": "1",
        "requisiteStageRefIds": [],
        "type": "manualJudgment"
      }
    ]
  }
}
```

Expected: when executed, the pipeline should not resolve `account` template variable since it was not explicitly defined in the MPT. Currently it does resolve the variable.
