### ISSUE TITLE
Kubernetes Account is not shown in "Deploy (Manifest) " stage.

### ISSUE THREAD

**Issue by pospome** [spinnaker/spinnaker#4165]
### Issue Summary:
Kubernetes Account is not shown in "Deploy (Manifest) " stage.
But I some operate Spinnaker, the Account sometimes is shown in the stage.
It's very strange.

### Cloud Provider(s):
Kubernetes(Manifest Based)

### Environment:
I am running Spinnaker using GKE.
Spinnaker deploy docker images into GKE.

Spinnaker version is 1.12.6.
Halyard version is 1.17.0-20190311152807.

### Feature Area:
Deploy (Manifest) stage in Pipelines

### Description:
I set up Manifest Based Spinnaker(V2).
But when I created new Pipeline, Kubernetes Account is not shown in "Deploy (Manifest) " stage.
Please show screen shots in "Additional Details" section of this issue.

I confirmed `hal config`, but it seems no problem.
I use V2 account.
I wrote `hal config` log in "Additional Details" section of this issue.

I also confirmed credentials, it's nothing.
```
$curl localhost:8084/credentials
[]
```

[But I created a Kubernetes provider when I install Spinnaker.](https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#adding-an-account)
Why is it nothing?

And strangely Kubernetes Account is shown sometimes.
For example
- When I deployed Spinnaker again.
- When I cleared cache.
- When it takes 30 minutes later.(I didn't do some oprations to Spinnaker.)

Then credentials exist in Spinnaker.
```
$curl localhost:8084/credentials
[{"authorized":true,"name":"my-k8s-v2-account","permissions":{},"providerVersion":"v2","requiredGroupMembership":[],"skin":"v2","type":"kubernetes"}]
```

### Steps to Reproduce:
1.I installed Spinnaker using [set up docs](https://www.spinnaker.io/setup/install/).

2.I skipped two sections.
Because these settings are optional.
https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#optional-create-a-kubernetes-service-account
https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#optional-configure-kubernetes-roles-rbac

3.I deployed Spinnaker.

4.I created new Application and Pipeline.

### Additional Details:

* Kubernetes Account is not shown.
<img width="1050" alt="Screen Shot 2019-03-21 at 8 15 10" src="https://user-images.githubusercontent.com/1498459/54727152-986faf80-4bb9-11e9-8f84-0f28d5233a27.png">

* Kubernetes Account is shown.
<img width="1015" alt="Screen Shot 2019-03-21 at 9 03 03" src="https://user-images.githubusercontent.com/1498459/54727171-b4735100-4bb9-11e9-8b46-5d166d512376.png">

* When Kubernetes Account is shown, applications that I didn't create is listed in Applications page.
For example  "event", "fluentd" etc.
<img width="1181" alt="Screen Shot 2019-03-21 at 21 52 56" src="https://user-images.githubusercontent.com/1498459/54753229-e15c4e00-4c23-11e9-954f-b4712149232d.png">

* I didn't use Legacy Kubernetes(V1).

* Similar issues.
https://github.com/spinnaker/spinnaker/issues/3133
https://github.com/spinnaker/spinnaker/issues/3223

* hal config
```
name: default
version: 1.11.11
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: my-k8s-v2-account
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: gke_spinnaker-v2-project_asia-east1-b_spinnakercluster
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /home/pospome/.kube/config
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: false
    primaryAccount: my-k8s-v2-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: oci.json
      baseImages: []
  cloudfoundry:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: my-k8s-v2-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  sidecars: {}
  initContainers: {}
  hostAliases: {}
  nodeSelectors: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
      disableClouddriverRoDeck: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/pospome/./halyard.json
    project: spinnaker-v2-project
    bucket: spin-722a6695-8746-4c82-8476-a190f445ffec
    rootFolder: front50
    bucketLocation: asia
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
  artifacts: true
metricStores:
  datadog:
    enabled: false
    tags: []
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
  twilio:
    enabled: false
    baseUrl: https://api.twilio.com/
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
      userAttributeMapping: {}
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  oracle:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  helm:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
  maven:
    enabled: false
    accounts: []
  templates: []
pubsub:
  enabled: false
  google:
    enabled: false
    pubsubType: GOOGLE
    subscriptions: []
    publishers: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: signalfx
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true

**Comment by eboumendil** [comment]
I have a similar issue. I am wondering if you are using an external Redis cache?

**Comment by pospome** [comment]
@eboumendil 
I knew external Redis by your comment.
https://www.spinnaker.io/setup/productionize/caching/externalize-redis/#externalize-redis

I don't use external Redis cache.

And recently this issue don't happen.

**Comment by ezimanyi** [comment]
Closing for now as this looks resolved---please feel free to re-open or make a new issue if this occurs again.  Thanks!
