### ISSUE TITLE
Unable to Authenticate with Google when Google group has no name

### ISSUE THREAD

**Issue by yinanfang** [spinnaker/spinnaker#4182]
### Issue Summary:
Got the following error when trying to sign in with Google
```java.lang.IllegalArgumentException: name cannot be null or empty at com.netflix.spinnaker.fiat.model.resources.Role.setName(Role.java:53)```

We the group info in json is here
```
{
"kind": "admin#directory#group",
"id": "placeholder_id",
"etag": "\"placeholder_tag\"",
"email": "placeholder@example.com",
"name": "",
"directMembersCount": "37",
"description": "Group for placeholder",
"adminCreated": false
},
```

There's a group with empty name. Leaving the group would solve the problem but Spinnaker can also filter out those broken groups

### Environment:
Spinnaker 1.12.5

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Authentication

### Additional Details:
Code location: https://github.com/spinnaker/fiat/blob/c3dea1d7017baa3d2462bd362ee98b108c53cdff/fiat-core/src/main/java/com/netflix/spinnaker/fiat/model/resources/Role.java#L53

**Comment by dibyom** [comment]
https://github.com/spinnaker/spinnaker/issues/4182 is the same issue which has a fix landing in the 1.14 release.
