### ISSUE TITLE
Where is the “Bake (Manifest)” stage

### ISSUE THREAD

**Issue by mitni455** [spinnaker/spinnaker#4188]
Page: [/guides/user/kubernetes-v2/deploy-helm/](https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/)

Feedback: I dont have the stage types of `Bake`, `Bake (manifest)` or `Deploy (manifest)` as per the documentation [here](https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/#configure-the-bake-manifest-stage) for deploying a helm chart. 

Am I missing something to do with `kubernetes v2` config?

**Comment by ethanfrogers** [comment]
@mitni455 have you configured a Kubernetes V2 account? 

https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#adding-an-account

**Comment by ezimanyi** [comment]
Closing per answer above.
