### ISSUE TITLE
How to change deployment namespace for `hal deploy apply`

### ISSUE THREAD

**Issue by DmitryBe** [spinnaker/spinnaker#4201]
### Issue Summary:
How to change default namespace (from spinnaker to something else) for `hal deploy apply` 

### Cloud Provider(s):
kubernetes

**Comment by bpowell** [comment]
You can do `hal config deploy edit --location NEW_NAMESPACE` that should switch the namespace that Spinnaker is deployed to

**Comment by DmitryBe** [comment]
Hey @bpowell ,

`--location` option works, but it creates two deployments, one in a specified location (namespace) and the second in `default` namespace;

The full sequence of steps I perform is below (following https://medium.com/oracledevs/install-spinnaker-with-halyard-on-kubernetes-88277bd61d59):

```bash
# deploy minio
helm install \
    --name minio-spinnaker \
    --namespace spinnaker-dev \
    --set accessKey=$MINIO_ACCESS_KEY,secretKey=$MINIO_SECRET_KEY \
    stable/minio

# disable versioning
mkdir -p ~/.hal/default/profiles &&   touch ~/.hal/default/profiles/front50-local.yml
echo 'spinnaker.s3.versioning: false' > ~/.hal/default/profiles/front50-local.yml

# run halyar (docker) 
docker run -itd \
    --rm \
    -p 8084:8084 -p 9000:9000 \
    --name halyard \
    -v ~/.hal:/home/spinnaker/.hal \
    -v ~/.kube:/home/spinnaker/.kube \
    -e SPIN_ACCOUNT=$SPIN_ACCOUNT \
    -e SPIN_NAMESPACES=$SPIN_NAMESPACES \
    -e K8S_NS=$K8S_NS \
    -e MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY \
    -e MINIO_SECRET_KEY=$MINIO_SECRET_KEY \
    -e SLACK_BOT_NAME=$SLACK_BOT_NAME \
    -e SLACK_BOT_KEY=$SLACK_BOT_KEY \
    gcr.io/spinnaker-marketplace/halyard:stable

docker exec -it halyard bash

# enable autocomplete
source <(hal --print-bash-completion)

# enable kube
hal config provider kubernetes enable

# create account (using current kube context)
hal config provider kubernetes account add $SPIN_ACCOUNT \
    --provider-version v2 \
    --context $(kubectl config current-context) 


hal config features edit --artifacts true

# config deployment
hal config deploy edit \
    --type distributed \
    --location spinnaker-dev \
    --account-name $SPIN_ACCOUNT

# config persist storage
echo $MINIO_SECRET_KEY | \
     hal config storage s3 edit --endpoint http://minio-spinnaker:9000 \
         --access-key-id $MINIO_ACCESS_KEY \
         --secret-access-key

hal config storage edit --type s3

# pick version (hal version list)
hal config version edit --version 1.12.7

# apply (deploy stuff on kube)
hal deploy apply

```

Manual inspection of  `.hal/config`  reveals only one deployment: `- name: default`; Any idea where the second one comes from?

**Comment by bpowell** [comment]
I see what you are saying. Halyard supports deploying multiple Spinnakers, which are called deployments. This is different to changing where Spinnaker is deployed. Halyard is the tool to control one or more Spinnakers.

By default when using halyard it will use the default deployment (`-name: default`). If you want to deploy another Spinnaker without deleting the contents in your current deployment, you can do `hal config --set-current-deployment NEW_DEPLOYMENT_NAME` and that will create a new halyard deployment. Then when using halyard commands pass the `--deployment DEPLOYMENT_NAME` flag and it will only change things in that deployment.

**Comment by bpowell** [comment]
Hi @DmitryBe did the above answer your question?

**Comment by DmitryBe** [comment]
Hi @bpowell ,

Thank you very much for your time and help. The answer above solved my problem.
