### ISSUE TITLE
Find Artifacts From Resource (Manifest) - Name and Kind are required fields

### ISSUE THREAD

**Issue by jwenz723** [spinnaker/spinnaker#4205]
### Issue Summary:
When defining a 'Find Artifacts From Resource (Manifest)' stage no matter what I do there is always a warning that says 'Name and Kind are required fields' if I select the 'Choose a target dynamically' option.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Kubernetes 1.11

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Pipelines. 
I think this would qualify as UI. @spinnaker/ui-ux-team

### Description:
The warning does not seem relevant because when using the 'Choose a target dynamically' option there is no 'Name' field available. The name field is only available when using 'Choose a static target'.

### Steps to Reproduce:
Define a 'Find Artifacts From Resource (Manifest)' stage and select the 'Choose a target dynamically' radio option.

### Additional Details:
<img width="967" alt="Screen Shot 2019-03-27 at 5 08 39 PM" src="https://user-images.githubusercontent.com/8587171/55118466-046b7f80-50b4-11e9-940c-28920a86d933.png">

**Comment by maggieneterval** [comment]
Hey @jwenz723 thank you for the awesome bug report, just put in PR to fix this issue that we should be able to patch into 1.13.

**Comment by jwenz723** [comment]
> Hey @jwenz723 thank you for the awesome bug report, just put in PR to fix this issue that we should be able to patch into 1.13.

Awesome! Glad to hear you already got a fix for this. Is there a way to get around this in the mean time without your fix?

Also, I am wondering if this is related... When I try to select something from the *Cluster* dropdown list there are no clusters available to choose:
<img width="787" alt="Screen Shot 2019-03-28 at 8 58 35 PM" src="https://user-images.githubusercontent.com/8587171/55206527-669faf80-519c-11e9-9214-b205ab1445bf.png">

But as you can see below, there are existing clusters if I view the infrastructure -> clusters page:
<img width="764" alt="Screen Shot 2019-03-28 at 9 00 21 PM" src="https://user-images.githubusercontent.com/8587171/55206559-87680500-519c-11e9-9bfb-5fd1f3cda596.png">

**Comment by maggieneterval** [comment]
Hey @jwenz723, in the meantime you should be able to ignore the irrelevant warnings and save your pipeline anyway, but let me know if that's not working for you.

Regarding the other issue, I don't think it's related but I can take a look at that as well. In the meantime I would recommend clicking "toggle for text input" and manually entering the cluster name as a workaround.
