### ISSUE TITLE
autoHealingPolicy : healthCheck is adding with full url instaed of only healthcheck name in pipeline json 

### ISSUE THREAD

**Issue by ciciya-lal** [spinnaker/spinnaker#4221]
Hello @lwander 

### Issue Summary:
autoHealingPolicy : healthCheck is adding with full url instead of only health check name in pipeline json 

### Cloud Provider(s):
Google Compute engine
spinnaker 1.13 release
### Environment:
Distributed

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
pipeline Edit as json 

### Description:
autoHealingPolicy : healthCheck is adding with full url instead of only health check name in pipeline json 

### Steps to Reproduce:
Precondition: Provider should be GCP
steps:
1. Goto deploy edit-->Autohealing Policy 
2. Enable Autohealing -->Add "Health Check" -->Done
3.Goto pipeline actions-->Edit as JSON
4.Check below part:

 "autoHealingPolicy": {
            "healthCheck": "https://www.googleapis.com/compute/beta/projects/xxxxxxxxxxxxxxx",
            "initialDelaySec": 300 

### Additional Details:

Actual issue:
 "autoHealingPolicy": {
            "healthCheck": "https://www.googleapis.com/compute/beta/projects/xxxxxxxxxxxxxxx",
            "initialDelaySec": 300 

--->should not add as url ,Only health policy name should display.

Expected:
 "autoHealingPolicy": {
            "healthCheck": "only healthcheck name",
            "initialDelaySec": 300 
},

![Capture](https://user-images.githubusercontent.com/38422004/55319049-b8dd1b00-5491-11e9-88bf-a9e69de624c6.PNG)

**Comment by maggieneterval** [comment]
Hi @ciciya-lal, thanks for opening this issue! Lars unfortunately no longer works on Spinnaker but I'm happy to take a look at this issue. Just to clarify, the expected behavior you describe exists in 1.12 and appears to be broken in 1.13 only?

**Comment by maggieneterval** [comment]
Hi @ciciya-lal, I dug into this a little and it looks like this broke with these changes:
https://github.com/spinnaker/deck/pull/6382/files
https://github.com/spinnaker/clouddriver/pull/3282/files
I need to put a little more thought into the best fix, but for now as a workaround you can use the Edit Stage as JSON feature to manually input the correct health check name.

**Comment by ciciya-lal** [comment]
> Hi @ciciya-lal, thanks for opening this issue! Lars unfortunately no longer works on Spinnaker but I'm happy to take a look at this issue. Just to clarify, the expected behavior you describe exists in 1.12 and appears to be broken in 1.13 only?

**Comment by ciciya-lal** [comment]
@maggieneterval ,

By mistake issue got closed..Hence i am re-openeing again..
Issue is not specific to 1.13 release.

Yes as you said we are using Edit json for inputting manually..

Please fix this issue..

Thanks,Cici

**Comment by ciciya-lal** [comment]
@maggieneterval ,

Since we are in production stage, can you make this fix ASAP , it would be a great healp..

Thanks for supporting us. !!

**Comment by ciciya-lal** [comment]
Hello @maggieneterval  , 
we have deployed health check fix version and now in json we can see healthcheck policy added  as below:

![h1](https://user-images.githubusercontent.com/38422004/55467063-1aca8b80-561e-11e9-8e69-39233e58899f.PNG)
![h2](https://user-images.githubusercontent.com/38422004/55467064-1aca8b80-561e-11e9-9b0a-7f32364120b9.PNG)


But Issue we are facing is healthcheck policy added through spinnaker in not attaching to instance group when we check from console.

please check currect issue and expected..

![image](https://user-images.githubusercontent.com/38422004/55467146-4ea5b100-561e-11e9-8add-f4027eb1bddb.png)

**Comment by maggieneterval** [comment]
Hi @ciciya-lal, glad the fix resolved your initial issue. I just tried to reproduce your second issue, and while initially the health check configured through Spinnaker did not show up in the GCP console, it did after I waited several minutes and then refreshed. According to the docs, `It can take 15 minutes before autohealing begins monitoring instances in the group.` Please let me know if you are still seeing any inconsistencies between your Spinnaker UI and GCP console. 

cc @jtk54 for any additional GCE insights!
