### ISSUE TITLE
Mac Local Git Install fails on Halyard backup

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4227]
### Issue Summary:

When doing a `hal deploy apply` with a local git deployment on a Mac, the deployment fails with error:

```
Problems in Global:
! ERROR Failed to backup user file:
  /home/my-user/.kube/config

- Failed to deploy Spinnaker.
```

Halyard isn't respecting `$HOME`, and is hard coding `/home`.

### Environment:

Mac

### Steps to Reproduce:

Follow [developer setup steps](https://www.spinnaker.io/guides/developer/getting-set-up/) and run `hal deploy apply`.

**Comment by ezimanyi** [comment]
@milesmatthias : Is that file `/home/my-user/.kube/config` directly referenced anywhere in your `.hal/config` file?  Halyard [should be either](https://github.com/spinnaker/halyard/blob/2a9cebabc89d881d93d2e819326b58e6f0550a41/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java#L95):
* Taking the value of `kubeConfigFile` set in the account in question in your halyard config if present
* Using `System.getProperty("user.home") + "/.kube/config"` as a default

**Comment by milesmatthias** [comment]
Yes, that is referenced as `kubeConfigFile` in `~/.hal/config`. I removed the hal config and re-ran, no luck.

**Comment by ezimanyi** [comment]
Hm, I'm confused...the code looks like it's correctly using the environment variable for user home.  I also just tested myself on my mac and it properly read my `.kube/config` file.  Do you also get the issue when you try `hal config generate`?

**Comment by milesmatthias** [comment]
I just updated halyard to 1.18.0, and same behavior. `hal config generate` results in the same error.

Let me uninstall and re-install halyard.

**Comment by milesmatthias** [comment]
Sorry @ezimanyi -- I was running a script to do my local install, and very silly me was passing in the path to my kubeconfig file incorrectly. Doh! 🤣
