### ISSUE TITLE
feature(sponnet) Add parameters to jenkins job stage

### ISSUE THREAD

**Issue by dodizzle** [spinnaker/spinnaker#4232]
### Issue Summary:
Add parameters to jenkins job stage

### Cloud Provider(s):
n/a

### Environment:
spinnaker  1.12.7

### Feature Area
sponnet, jenkins job stage

### Description:
Currently the jenkins job stage does not support parameters.

### Steps to Reproduce:
Run  jsonnet demo-pipeline.jsonnet

### Additional Details:
I will open a PR which will add parameters but does not require them.

**Comment by ethanfrogers** [comment]
@dodizzle the Jenkins stage should already support parameters if the Job you've selected has parameters configured.

**Comment by dodizzle** [comment]
PR opened.
https://github.com/spinnaker/spinnaker/pull/4233

**Comment by dodizzle** [comment]
The PR for this was merged.
