### ISSUE TITLE
bug(deck): 1.13: Helm expected artifacts fail to render properly

### ISSUE THREAD

**Issue by jfillo** [spinnaker/spinnaker#4239]
### Issue Summary:

After upgrading to Spinnaker 1.13.0 and 1.13.1 - pipelines that have a Helm default expected artifact stopped rendering properly.

This affects existing pipelines and would prevent the creation of new pipelines that want to specify a default Expected Artifact of kind `Helm`

### Cloud Provider(s):

Any

### Environment:

Spinnaker 1.13

### Feature Area:

Deck

### Description:

![Screen Shot 2019-04-03 at 1 10 38 PM](https://user-images.githubusercontent.com/794020/55502577-7ee75280-5612-11e9-971c-d928ca52633b.png)

### Steps to Reproduce:

Either load an existing pipeline that uses helm as a default expected artifact
OR
Create a new pipeline and try to specify a default expected artfact of kind `Helm`

**Comment by jfillo** [comment]
@spinnaker/ui-ux-team

**Comment by maggieneterval** [comment]
@jkschneider @sbwsg Guessing this might be related to the artifacts rewrite?

**Comment by sbwsg** [comment]
I'm working on repro now and will see about a fix

**Comment by sbwsg** [comment]
A fix for this will be released as part of the next 1.13 patch.
