### ISSUE TITLE
bug(deck): 1.13: delete (manifest) - match by label does not show all available kinds

### ISSUE THREAD

**Issue by jfillo** [spinnaker/spinnaker#4240]
### Issue Summary:

After upgrading to Spinnaker 1.13.0 and 1.13.1 the `Delete (Manifest)` stage using selector `Match target(s) by label` does not show all available Kinds that can be deleted.

### Cloud Provider(s):

Any

### Environment:

Spinnaker 1.13

### Feature Area:

Deck

#### Screenshot from 1.12:

![Screen Shot 2019-04-03 at 1 08 54 PM](https://user-images.githubusercontent.com/794020/55503184-d33f0200-5613-11e9-9eef-f90d6de8be66.png)

#### Screenshot from 1.13:

![Screen Shot 2019-04-03 at 1 08 46 PM](https://user-images.githubusercontent.com/794020/55503206-d89c4c80-5613-11e9-853d-38a25478c24d.png)

### Steps to Reproduce:

Attempt to create a `Delete (Manifest)` stage using selector `Match target(s) by label` to delete either a `horizontalPodAutoscaler` or `podDisruptionBudget`

**Comment by jfillo** [comment]
@spinnaker/ui-ux-team

**Comment by jfillo** [comment]
@maggieneterval , is this related to the work done on https://github.com/spinnaker/deck/commit/cbfcae454e61ce81de4d5882ab710c04f292ee1b ?

**Comment by jfillo** [comment]
Another thing to note. If I manually edit the stage json I can target `horizontalPodAutoscaler` and `podDisruptionBudget` resources for deletion. The UI just doesn't reflect that those kinds are selected, which is confusing.

**Comment by maggieneterval** [comment]
@jfillo Thank you for reporting this issue and also posting your current workaround! It looks like we are only giving options for each entry in a given account's `spinnakerKindMap`, which does seem to exclude the two kinds you mentioned. @ezimanyi -- do you have any insight into whether the `spinnakerKindMap` composed by Clouddriver is meant to be an exhaustive list of kinds? If not, I suppose we should revert to the free-form input of comma-separated kinds.

**Comment by ezimanyi** [comment]
@maggieneterval : Yes, it does look like the `spinnakerKindMap` will only contain [built-in kinds and registered CRDs](https://github.com/spinnaker/clouddriver/blob/5a952d1b8375c3cbf2d0a003cc8f2a26d48c2a78/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.java#L190).

@jfillo : Have you tried adding these as registered kinds?  (This issue may end up converging with #4237.)

**Comment by jfillo** [comment]
@ezimanyi even with explicit registration did not see the built-in kinds appear in the labels

**Comment by ezimanyi** [comment]
Hmm, I just tried this and kinds that I explicitly registered showed up in labels.  Maybe try hard refreshing the UI in case it's a stale cache issue?

![image](https://user-images.githubusercontent.com/1391982/55515073-a6044b00-5637-11e9-830b-857877a42f30.png)

**Comment by jfillo** [comment]
I actually was able to see registered CRD's just fine (see my original screenshot). It was the built in `horizontalPodAutoscaler` and `podDisruptionBudget` resources that wouldn't show.

**Comment by ezimanyi** [comment]
Oh, sorry, yeah I'm learning about this as I read through the code.  Built-in kinds don't show up if their [handler maps to a spinnaker kind](https://github.com/spinnaker/clouddriver/blob/5a952d1b8375c3cbf2d0a003cc8f2a26d48c2a78/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/KubernetesSpinnakerKindMap.java#L89) of `NONE` or `UNCLASSIFIED`.

I wonder if we need to do this filtering---certainly some operations would be restricted to Kubernetes kinds that map to a Spinnaker kind (which is probably the motivation behind filtering the list), but others (such as a simple delete) should work fine regardless of whether we have a mapped Spinnaker kind.

Maybe we could remove the filtering from the back-end and have `deck` decide when it needs mapping and when it doesn't?  (Or return a separate list for use cases where we don't actually need a mapping but just a list of kinds.)

**Comment by maggieneterval** [comment]
@ezimanyi thanks so much for looking into this. Either removing the filtering in the existing map or sending a new list of all kinds would work for Deck, I'm guessing the first is easier? (But if neither is I'm also happy to just revert the pre-populated dropdown.)

**Comment by jfillo** [comment]
Just upgraded to `1.13.4` and this issue is still hanging around. IMO this issue a regression from the previous implementation and should either be rolled back or fall forward with a fix.

**Comment by maggieneterval** [comment]
Hey @jfillo, completely agree, should have time to work on this by EOW. I'm leaning toward removing the filtering that removes kinds without Spinnaker-kind analogs from the map produced by Clouddriver, lmk if you have any thoughts on that!

**Comment by jfillo** [comment]
As long as if the Kind is able to be deleted via the stage it appears in the drop down we should be good to go. It sounds like removing that filter is the way to go.
