### ISSUE TITLE
Spinnaker / Kubernetes V2 - Containers are showing CPU and Memory resources as Unknown.

### ISSUE THREAD

**Issue by rbadillo** [spinnaker/spinnaker#4243]
### Issue Summary:

Using Kubernetes V2 provider, Containers are showing CPU and Memory resources as Unknown.

### Cloud Provider(s):

Kubernetes V2

### Environment:

Spinnaker 1.12.X
Spinnaker 1.13.X

### Feature Area

Clouddriver

### Steps to Reproduce:

1. Go to the `Infrastructure` tab inside your Spinnaker / Kubernetes V2 Application.

2. Click on any of your containers.

3. You will get a menu on the right , go to the `Resources` section.

4. CPU and Memory are Unknown.

![Screen Shot 2019-04-04 at 11 43 46 AM](https://user-images.githubusercontent.com/4214292/55572643-0b0e7e00-56d6-11e9-9236-c80293079942.png)

### Additional Details:

During our investigation, we found these logs in Clouddriver:

```
2019-04-04 15:25:00.261 DEBUG 1 --- [tionAction-1076] c.n.s.c.jobs.local.JobExecutorLocal      : Starting job: 'kubectl --kubeconfig=/home/spinnaker/.hal/default/staging/dependencies/1140023408-config-my-cluster --context=my-cluster --namespace=default top po --containers'...
```

```
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:572) ~[clouddriver-kubernetes.jar:na]
```

```
2019-04-04 14:26:14.165  WARN 1 --- [utionAction-918] s.c.k.v.c.a.KubernetesMetricCachingAgent : spinnaker-apps-engineering/KubernetesMetricCachingAgent[1/1]: Metrics for namespace 'engineering' in account 'spinnaker-apps-engineering' have not been recorded yet.
```

**Comment by jfillo** [comment]
I have this same issue, I can see that the `kubectl` top command is returning results, but those resources values don't seem to be making their way back up to the Deck UI

```
kubectl -n spinnaker exec -it spin-clouddriver-caching-7fc9fbc575-6pvsq -- /bin/sh
~ $ kubectl --kubeconfig=/home/spinnaker/.hal/default/staging/dependencies/1140023408-config-my-cluster --context=my-cluster --namespace=default top po --containers
POD                                                    NAME              CPU(cores)   MEMORY(bytes)   
hello-world-web-application-698845568b-jg875   web-application   3m           416Mi           
hello-world-web-application-698845568b-jz9jr   web-application   3m           466Mi           
hello-world-web-application-698845568b-rbnw7   web-application   4m           441Mi 
```

**Comment by ezimanyi** [comment]
Showing `unknown` for me too...I'm not at all familiar with the code path of how that gets populated, but seems like there's a bug somewhere.

**Comment by maggieneterval** [comment]
On my end, looks like the `/manifests/${account_name}/${namespace}/pod%20${pod_name}` request to populate this details pane is coming back with `metrics` always an empty array.

**Comment by jfillo** [comment]
@ezimanyi I think I came across this issue here when researching another.

This issue looks to be because the metrics lookup is not implemented for k8s v2 accounts using the `liveManifestCalls: true`

see:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2LiveManifestProvider.java#L79

as opposed to the other handler for accounts not using the `liveManifestCalls` setting:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/view/provider/KubernetesV2ManifestProvider.java#L131

**Comment by rbadillo** [comment]
@jfillo Actually I'm using `liveManifestCalls: true`.

**Comment by rbadillo** [comment]
What do you think @ezimanyi ?

**Comment by ezimanyi** [comment]
Linked PR will fix this for `liveManifestCalls: true`; it was indeed the issue in the above comment by @rbadillo.

For reference, this can also happen (regardless of `liveManifestCalls`) if the service account that Spinnaker is running as does not have permission to list `pods` in the API group `metrics.k8s.io`.  In that case you should see a warning on startup "Could not read pod metrics in account ... for reason: ..."
