### ISSUE TITLE
Setting State in Promises

### ISSUE THREAD

**Issue by louisjimenez** [spinnaker/spinnaker#4261]
### Issue Summary:

This proposed change came from a discussion on cancelling promises in this [PR](https://github.com/spinnaker/deck/pull/6819). I'm looking for feedback on adding the below section to the [conventions doc](https://github.com/spinnaker/deck/wiki/Conventions) as a best practice for setting state in a promise. @erikmunson @maggieneterval @anotherchrisberry @christopherthielen  @sbwsg 

### Setting State in Promises

Relying on a promise to `setState` can introduce a memory leak if the react component unmounts while the promise is pending. This can be prevented by wrapping the promise in a RxJS observable and taking values until a separate notifier observable emits.

```javascript
import * as React from 'react';
import { Observable, Subject } from 'rxjs';

import { ApplicationReader, IApplicationSummary } from 'core/application';

interface IExampleComponentState {
  applications: IApplicationSummary[];
}

export default class ExampleComponent extends React.Component<{}, IExampleComponentState> {
  public state: IExampleComponentState = {
    applications: [],
  };

  // Notifier observable
  private destroy$ = new Subject();

  public componentDidMount(): void {
    Observable.fromPromise(ApplicationReader.listApplications())
      .takeUntil(this.destroy$)
      .subscribe(
        applications => this.setState({ applications }),
        err => {
          // error handling
        },
      );
  }

  public componentWillUnmount(): void {
    // emits on the notifier observable, completing the promise observable.
    this.destroy$.next();
  }

  public render() {
    const { applications } = this.state;

    return <p>Applications: {applications.map(({ name }) => name).join(',')}</p>;
  }
}
```

**Comment by sbwsg** [comment]
lgtm 👍

**Comment by louisjimenez** [comment]
merged https://github.com/spinnaker/deck/wiki/Conventions
