### ISSUE TITLE
[GCE] Cluster view is failing to report instance health accurately

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4266]
### Issue Summary:
When viewing clusters for applications within Spinnaker, the "Health" status of the instances is not being reported properly. 

### Cloud Provider(s):
- Google/GCE

### Environment:
Spinnaker 1.13.2

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Not sure if Deck or something else

### Description:
When looking at clusters within Spinnaker, almost all instances will report as `in transition or no health status reported` in the UI, which means they are all blue in color. Seemingly regardless of application size or how many instances there are it will always be blue, even if those instances are actively passing healthy checks.

<details>
<summary>When clicking on the server group you can see this behavior:</summary>
<kbd><img width="1061" alt="Screen Shot 2019-04-09 at 1 09 55 PM" src="https://user-images.githubusercontent.com/10604059/55824226-15ab8780-5ac9-11e9-9660-e305dcf79cf1.png"></kbd>
</details>

<details>
<summary>When clicking on the instance you also see this reported:</summary>
<kbd><img width="314" alt="Screen Shot 2019-04-09 at 1 10 11 PM" src="https://user-images.githubusercontent.com/10604059/55824240-1cd29580-5ac9-11e9-9c2a-af87a600b6c7.png"></kbd>
</details>

<details>
<summary>However, if you navigate to the Load Balancer view you see a different story where all instances do accurately show as `Up`:</summary>
<kbd><img width="726" alt="Screen Shot 2019-04-09 at 1 12 53 PM" src="https://user-images.githubusercontent.com/10604059/55824286-3542b000-5ac9-11e9-8b42-97409537e6c5.png"></kbd>
</details>

### Steps to Reproduce:
- Deploy a cluster attached to a load balancer
- Add a valid health check to the instances and confirm it is passing
- Navigate to the clusters view or load balancer details pane to confirm the status is being incorrectly reported

### Additional Details:
- We did not notice this issue for any application on 1.12.X versions.
- The only console error we see is referencing `[react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually`

**Comment by erancx** [comment]
we are experiencing the same issue with 1.13.2. All MIGs reported with unknown state with GCE provider.
I rolled back to 1.12.x and it works.

**Comment by maggieneterval** [comment]
Hey @erancx and @seanpeters86, I will patch the fix for this into 1.13.

**Comment by seanpeters86** [comment]
Just confirmed things are working again! thanks for the quick turn around
