### ISSUE TITLE
wait 10 mins to have access to new created application in 1.13.x

### ISSUE THREAD

**Issue by JamieChe** [spinnaker/spinnaker#4276]
### Issue Summary:
 the UI reports "Application Not Found" after creating a new application, and need to wait up to 10 mins to access application 

### Cloud Provider(s):
K8S 1.14

### Environment:
Spinnaker 1.13

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Fiat, Front50

### Description:
In Spinnaker v1.13.x, we wait fiat do next regular role sync to get access for new created application, which is up to 10 mins.  
During this period, Front50 keeps reporting  
``2019-04-11 02:42:24.975  WARN 1 --- [.0-8080-exec-15] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.access.AccessDeniedException: Access is denied]
``

 Checked fiat log, I notice there is a non-regular sync when creating the app, but this sync seems don't work. 
```
######## previous regular sync ########
2019-04-11 02:32:19.292  INFO 1 --- [pool-2-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced anonymous user role.
2019-04-11 02:32:19.799  INFO 1 --- [pool-2-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced 6 non-anonymous user roles.
######## I am doing the app creation, but after sync I still couldn't access app ########
2019-04-11 02:33:37.534  INFO 1 --- [.0-7003-exec-17] c.n.s.fiat.roles.UserRolesSyncer         : [testuser] Synced anonymous user role.
2019-04-11 02:33:38.046  INFO 1 --- [.0-7003-exec-17] c.n.s.fiat.roles.UserRolesSyncer         : [testuser] Synced 5 non-anonymous user roles.
######## after this regular sync, I'm able to see my app ########
2019-04-11 02:42:19.818  INFO 1 --- [pool-2-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced anonymous user role.
2019-04-11 02:42:20.324  INFO 1 --- [pool-2-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced 6 non-anonymous user roles.
```
This issue didn't happen in previous version (tested in 1.12.6 and 1.9.5 ), we can access new app just after a few seconds after creating it. 

### Steps to Reproduce:
In Spinnaker v.1.13.x, just create a new application and will find this issue. 
And, the wait time is not necessarily 10 mins, depend on when the previous role sync happened. 

### Additional Details:
![image](https://user-images.githubusercontent.com/30921934/55928448-3f8cb780-5c4b-11e9-90de-fd41279b3249.png)
![image](https://user-images.githubusercontent.com/30921934/55928487-621ed080-5c4b-11e9-9705-39ad7ea2702d.png)

**Comment by seanpeters86** [comment]
We use fiat to sync roles via our saml provider for authn and authz and I was just able to create an application and instantly have access to it on 1.13.2 with no issues.

**Comment by JamieChe** [comment]
We've tested on 1.13.2, same issue. But we didn't see it in 1.12.6. We use ldap for auth.  
So what would be the problem ? Do you have any suggestion for further checking?
Thanks

**Comment by error418** [comment]
See #4307 for additional findings about this issue

**Comment by ajordens** [comment]
Out of curiosity, what object store do you have backing Front50?

**Comment by JamieChe** [comment]
We use Minio for backend storage, version 2019-04-09T01:22:30Z

**Comment by dibyom** [comment]
1.13.5 should have the fix

**Comment by JamieChe** [comment]
Yes, we've verified the fix in 1.13.5. The issue can be closed now.  Thanks.

**Comment by costimuraru** [comment]
The issue is present on in Spinnaker 1.16.0 (with S3 backend), when LDAP auth is enabled.
Application takes minutes to show after creation.

**Comment by clanesf** [comment]
You can fix this by setting the following feature flag in your fiat-local.yaml `fiat.allowAccessToUnknownApplications: true`
