### ISSUE TITLE
Can not Enable Canary 

### ISSUE THREAD

**Issue by tingzhang-ming** [spinnaker/spinnaker#4277]
### Issue Summary:
I build compoents including kayenta by myself, and it works well, now i want to enable canary, I enabled the canary by changing gate.yml :
kayenta:
    enabled: true

but i still can not see the Canary tab in Deck? (https://www.spinnaker.io/guides/user/canary/config/)

I do not follow the offical website installation, Since i want to build the code by myself. so is there anything missed for me?

Thank you!

### Cloud Provider(s):
kubernetes

### Environment:
release-1.13.x (compoents including deck,gate,orca,front50,echo,igor,clouddriver,kayenta)

**Comment by estebangarcia** [comment]
Did you enable it in deck ?

**Comment by tingzhang-ming** [comment]
yes, i did. but i set canaryFeatureDisabled = true. 

canaryFeatureDisabled = false will work, i will try again.

**Comment by tingzhang-ming** [comment]
it still could not work.
i changed setttings.js  as follows:
// var canaryEnabled = process.env.CANARY_ENABLED === 'true';
var canaryEnabled = 'true';
// var canaryFeatureDisabled = process.env.CANARY_FEATURE_ENABLED !== 'true';
var canaryFeatureDisabled = 'false';
// var canaryStagesEnabled = process.env.CANARY_STAGES_ENABLED === 'true';
// var chaosEnabled = process.env.CHAOS_ENABLED === 'true' ? true : false;
var debugEnabled = process.env.DEBUG_ENABLED === 'false' ? false : true;
var canaryStagesEnabled = 'true'
var chaosEnabled = 'true'

**Comment by tingzhang-ming** [comment]
> it still could not work.
> i changed setttings.js as follows:
> // var canaryEnabled = process.env.CANARY_ENABLED === 'true';
> var canaryEnabled = 'true';
> // var canaryFeatureDisabled = process.env.CANARY_FEATURE_ENABLED !== 'true';
> var canaryFeatureDisabled = 'false';
> // var canaryStagesEnabled = process.env.CANARY_STAGES_ENABLED === 'true';
> // var chaosEnabled = process.env.CHAOS_ENABLED === 'true' ? true : false;
> var debugEnabled = process.env.DEBUG_ENABLED === 'false' ? false : true;
> var canaryStagesEnabled = 'true'
> var chaosEnabled = 'true'



> Did you enable it in deck ? There is a file called settings.js you have to change the "canaryFeatureDisabled" and "canaryStagedEnabled" variables.

it still could not work.
i changed setttings.js as follows:
// var canaryEnabled = process.env.CANARY_ENABLED === 'true';
var canaryEnabled = 'true';
// var canaryFeatureDisabled = process.env.CANARY_FEATURE_ENABLED !== 'true';
var canaryFeatureDisabled = 'false';
// var canaryStagesEnabled = process.env.CANARY_STAGES_ENABLED === 'true';
// var chaosEnabled = process.env.CHAOS_ENABLED === 'true' ? true : false;
var debugEnabled = process.env.DEBUG_ENABLED === 'false' ? false : true;
var canaryStagesEnabled = 'true'
var chaosEnabled = 'true'

**Comment by estebangarcia** [comment]
Try with booleans not strings.

**Comment by tingzhang-ming** [comment]
thank very much.

yes, it could see the the Canary tab in Deck, but after i enable canary tab, there is no Delivery tab and no Canary configs and no Canary reports described in  https://www.spinnaker.io/guides/user/canary/config/ ? is there any configuration missed?

**Comment by tingzhang-ming** [comment]
> Try with booleans not strings.

thank very much.

yes, it could see the the Canary tab in Deck, but after i enable canary tab, there is no Delivery tab and no Canary configs and no Canary reports described in https://www.spinnaker.io/guides/user/canary/config/ ? is there any configuration missed?

**Comment by tingzhang-ming** [comment]
thanks, it works now.  I should visit deck again after enabling canary instead of refreshing partily.

**Comment by maggieneterval** [comment]
Thanks for helping resolve this, @estebangarcia! Going to close this issue.
