### ISSUE TITLE
Spin CLI: Make gate endpoint work without a port

### ISSUE THREAD

**Issue by stewchen** [spinnaker/spinnaker#4280]
### Issue Summary:
Gate endpoints that do not have a port throw an error on the validation. Currently, the workaround is to include port 80 or 443 in the config for the http/https endpoints, but this shouldn't be needed.

This issue is found in spin version 1.7.0

**Comment by jtk54** [comment]
Fixed by https://github.com/spinnaker/spin/pull/164.
