### ISSUE TITLE
Support Shielded VM related configurations for GCP instance templates.

### ISSUE THREAD

**Issue by haykbaluyan** [spinnaker/spinnaker#4281]
### Issue Summary:

Add support to enable Shielded VM related configurations for GCP instance templates.

### Cloud Provider(s):

GCP

### Environment:

n/a

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

UI, GCP, Instance Templates, Server Groups

### Description:

Shielded VMs are virtual machines (VMs) on Google Cloud Platform hardened by a set of security controls that help defend against rootkits and bootkits. Using Shielded VMs helps protect enterprise workloads from threats like remote attacks, privilege escalation, and malicious insiders. Shielded VMs leverage advanced platform security capabilities such as secure and measured boot, a virtual trusted platform module (vTPM), UEFI firmware, and integrity monitoring.

https://cloud.google.com/shielded-vm/

### Steps to Reproduce:

https://cloud.google.com/security/shielded-cloud/shielded-vm

#### UI changes to enable Shielded VM policies

![Enable_Secure_Boot_Vtpm](https://user-images.githubusercontent.com/1740049/56100319-129b0780-5ecc-11e9-907f-8d663f32a4b9.png)

#### Shielded VM policies as shown on Gcloud console

![Gcloud_ShieldedVM_Policies](https://user-images.githubusercontent.com/1740049/56100320-175fbb80-5ecc-11e9-9047-71ed8031c63c.png)

#### UI changes to show Shielded VM related polcies

![Shielded_VM_policies](https://user-images.githubusercontent.com/1740049/56100324-234b7d80-5ecc-11e9-8895-ceae1d651c0e.png)

#### For non-shielded VM images no Shielded VM policies are avaiable

![No_ShieldedVM_Policies](https://user-images.githubusercontent.com/1740049/56100321-19c21580-5ecc-11e9-9af2-61cf9e924cb7.png)

#### Help message

![SecureBoot_Help_Message](https://user-images.githubusercontent.com/1740049/56100323-2181ba00-5ecc-11e9-8fdc-b4e820a04369.png)

**Comment by seanpeters86** [comment]
@haykbaluyan are you aware of anything that needs to be done to make this work? Just upgraded components and I'm not seeing VMs come up with this config. No errors in clouddriver and I have given it sufficient permissions with `instanceAdmin.v1`.

**Comment by haykbaluyan** [comment]
@seanpeters86 just to clarify. After upgrading deck and cloud driver do you see the "Shielded VMs" config section in the Server Group details (just like it is show in the first image attached to this issue)?

If you see that section you can check all three boxes and once a VM is created in GCP, you can check the security section in the Google Console for that VM to see if the VM was created with Shielded VM options enabled. Again see the screenshots attached to this issue.

Please let me know how it goes.

**Comment by seanpeters86** [comment]
Correct, I can see all of these sections and even though I have the config selected in my pipeline's deploy stage (validated it is in the Json as well) the instance does not come up with this config.

In spinnaker and in the cloud console it both shows as no policies added.

**Comment by haykbaluyan** [comment]
@seanpeters86 that is strange given that you upgraded all components. Give me some time to setup a clean environment and check this myself.

**Comment by haykbaluyan** [comment]
@seanpeters86 I just verified that latest spinnaker release `release-1.14.x-latest-validated` (`hal config version edit --version release-1.14.x-latest-validated`) includes those changes and works as expected. I think the reason you are not seeing shielded vm options enabled is that **you are not using shielded image**. In other words, you cannot just use non-secured image to enable shielded vm configs. Could you please confirm that you are indeed using shielded image?

**Comment by seanpeters86** [comment]
@haykbaluyan that is probably the problem indeed. Just read through the doc again and [found this](https://cloud.google.com/compute/docs/images#shielded-images) (figured it would be on the shielded vms page directly). Are you aware of being able to use custom images instead? I assume not as the docs don't mention it, but I'm sure this is the cause of my problem.

Thanks for digging in on this!

**Comment by haykbaluyan** [comment]
@seanpeters86 that is indeed the problem. And i do not think shielded vm features are supported for custom images. It is only supported for images that are specifically created with shielded vm support which is done by specifying **UEFI_COMPATIBLE** and **SECURE_BOOT** features under **--guest-os-features** flag for **gcloud beta compute images create** command.

```
NAME
    gcloud beta compute images create - create Google Compute Engine images

SYNOPSIS
    gcloud beta compute images create IMAGE_NAME
        (--source-disk=SOURCE_DISK | --source-image=SOURCE_IMAGE
          | --source-image-family=SOURCE_IMAGE_FAMILY
          | --source-snapshot=SOURCE_SNAPSHOT | --source-uri=SOURCE_URI)
        [--csek-key-file=FILE] [--description=DESCRIPTION] [--family=FAMILY]
        [--force] [--force-create] **[--guest-os-features=[GUEST_OS_FEATURE,...]]**
        [--labels=[KEY=VALUE,...]] [--licenses=[LICENSES,...]]
        [--no-require-csek-key-create] [--source-disk-zone=SOURCE_DISK_ZONE]
        [--source-image-project=SOURCE_IMAGE_PROJECT]
        [--kms-key=KMS_KEY : --kms-keyring=KMS_KEYRING
          --kms-location=KMS_LOCATION --kms-project=KMS_PROJECT]
        [GCLOUD_WIDE_FLAG ...]

--guest-os-features=[GUEST_OS_FEATURE,...]
        This parameter enables one or more features for VM instances that use
        the image for their boot disks. The following features are available:

        ◆ MULTI_IP_SUBNET - For configuring interfaces with a netmask other
          than /32.

        ◆ SECURE_BOOT - Enables UEFI secure boot, which restrics unsigned
          software from booting or unsigned drivers from loading on the VM
          instance.

        ◆ UEFI_COMPATIBLE - Enables UEFI booting, which is an alternative
          system boot method. Most public images use the GRUB bootloader as
          their primary boot method.
```
