### ISSUE TITLE
error when deploying kubernetes cronjob manifest

### ISSUE THREAD

**Issue by renperez** [spinnaker/spinnaker#4283]
Issue Summary:
Error: Exception ( Deploy Manifest )
deployKubernetesManifest.deployKubernetesManifest.cronJob.notValidKind

Cloud Provider(s):
Kubernetes

Environment:
Spinnaker 
Cloud Driver version: 
gcr.io/spinnaker-marketplace/clouddriver:4.3.6-2019
--

Description:
Unable to deploy cronjob manifest. I'm able to deploy the manifest using kubectl locally with no issues. But when I have spinnaker do the deployment it gives me the error deployKubernetesManifest.deployKubernetesManifest.cronJob.notValidKind

Logs:

{"endTime":1555096451680,"id":"7","implementingClass":"com.netflix.spinnaker.orca.pipeline.tasks.artifacts.BindProducedArtifactsTask","loopEnd":false,"loopStart":false,"name":"bindProducedArtifacts","stageEnd":true,"stageStart":false,"startTime":1555096451672,"status":"SUCCEEDED"}],"type":"deployManifest"},{"context":{"account":"operations-nonprod-uswest2-01","cloudProvider":"kubernetes","exception":{"details":{"error":"Bad Request","errors":["deployKubernetesManifest.deployKubernetesManifest.cronJob.notValidKind"],"kind":"HTTP","responseBody":"{\n  \"error\" : \"Bad Request\",\n  \"errors\" : [ \"deployKubernetesManifest.deployKubernetesManifest.cronJob.notValidKind\" ],\n  \"exception\" : \"com.netflix.spinnaker.clouddriver.deploy.DescriptionValidationException\",\n  \"message\" : \"Validation Failed\",\n  \"status\" : 400,\n  \"timestamp\" : 1555096452336\n}","rootException":"com.netflix.spinnaker.clouddriver.deploy.DescriptionValidationException","status":400,"url":"http://spin-clouddriver.spinnaker:7002/kubernetes/ops?clientRequestId=cb16f855-5683-4e4b-8d55-5734fab1e3d1"},"exceptionType":"RetrofitError","operation":"deployManifest","shouldRetry":false,"timestamp":1555096452340},"failOnFailedExpressions":true,"manifestArtifactAccount":

**Comment by neelimamanubolu** [comment]
Hi Ren Perez , the above issue is working for me with kubectl 1.14 version, Can u pls share version in manifest and target environment  u are using for the above issue.

**Comment by renperez** [comment]
@neelimamanubolu 
I got this working already. I updated spinnaker to the latest version and enabled cronjob into spinnaker config. thanks
