### ISSUE TITLE
[GCE] Find image from Cluster does not respect region selection

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4299]
### Issue Summary:
When using the `Find Image from Cluster` stage in a Spinnaker pipeline, it does not respect the value the user inputs in the stage for `Region`. It can search in 2 regions in the same stage, even though you don't direct Spinnaker to do so.

### Cloud Provider(s):
- Google/GCE

### Environment:
- Spinnaker 1.13.2

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Orca -> Clouddriver

### Description:
When using the `Find Image from Cluster` stage within Orca you select the region you want to search for, this is no longer being respected when running your pipeline. The region that Orca tells Clouddriver to run the search in is influenced by the following deploy stage within the same pipeline.

For example, if you have a pipeline setup like this:

### Pipeline 1
1. Bake `my-test-app`
2. Deploy `my-test-app` to `us-central1`

---- Validate deployment ----

### Pipeline 2
1. Find image from `us-central1` with name `my-test-app`
2. Deploy to us-east1

The Spinnaker stage for `Find image from cluster` will look in both central and east regions, even though you only specify `us-central1` in the stage.

<details>
<summary>Pipeline stage showing the configuration</summary>
<kbd>
<img width="1142" alt="pipeline-config" src="https://user-images.githubusercontent.com/10604059/56156948-ef339380-5f83-11e9-85f2-77ebf85633a7.png">
</kbd>
</details>

<details>
<summary>Pipeline output showing the search in both regions</summary>
<kbd>
<img width="952" alt="pipeline-output" src="https://user-images.githubusercontent.com/10604059/56156827-a54aad80-5f83-11e9-95c1-bc45fc9b0015.png">
</kbd>
</details>

If you change the pipeline to Find Image in us-central1 and deploy in us-central1 the pipeline completes as expected. 

The issue with this is if you treat regions as an A-B deploy this causes significant problems. Notably, if you do not have a server group in east (yet) but are trying to deploy to east, while looking up an image in central, this pipeline will fail with no server groups found for east, even though you specify central only.

<details>
<summary>Error given when server group does not exist in BOTH regions when only specifying one</summary>
<kbd>
<img width="956" alt="pipeline-error" src="https://user-images.githubusercontent.com/10604059/56157408-10e14a80-5f85-11e9-95c1-515a43f7388d.png">
</kbd>
</details>

### Steps to Reproduce:
- Deploy a server group to us-central1
- Create a new pipeline that finds the image from us-central1 that you deployed, while then deploying to us-east1

### Additional Details:
This behavior was not noticed on version 1.12.X.

**Comment by seanpeters86** [comment]
If I had to guess it was this commit that broke things: https://github.com/spinnaker/orca/commit/6ee8fe911b7c9740a252d89b83d424c81cd292f5

**Comment by darkstarmv** [comment]
I understand why you would want to bake in all regions in AWS, but in GCP it doesn't make any sense. it is complete waste of time and resources (including money).

**Comment by seanpeters86** [comment]
I have since reverted the https://github.com/spinnaker/orca/commit/6ee8fe911b7c9740a252d89b83d424c81cd292f5 commit on our local dev spinnakers and the behavior is back to normal. 

Can we start a conversation about either fully reverting this commit, or adding it as a flag for users to enable in their pipeline?

CC: @marchello2000 @ajordens

**Comment by marchello2000** [comment]
@seanpeters86 thanks for reporting this. I am sorry this hit you like this - for AWS this a very important fix because without it one might end up with two regions running different versions of the app (if not all images are found). The fix should be fairly trivial (basically move [this](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy#L205) to line 187. I am in the middle of something but can get to it next week or someone from our team might be able to get it. You are also welcome to submit a PR and tag me - I am happy to review it

**Comment by asher** [comment]
fixed by https://github.com/spinnaker/orca/pull/2851

**Comment by seanpeters86** [comment]
@Asher thanks again for this fix, is there any chance we can pick this into 1.13? Not sure when 1.14 will come out. Just now noticed we never did
