### ISSUE TITLE
Current implementation of Upsert lambda alias does not work

### ISSUE THREAD

**Issue by saimadineni** [spinnaker/spinnaker#4304]
### Issue Summary:
Current implementation of Upsert lambda alias does not work. 
It fails with a null pointer exception error

### Cloud Provider(s):
AWS/lambda

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Clouddriver/lambda

**Comment by jtk54** [comment]
This issue needs a lot more detail to be helpful and actionable. Things like:

* Spinnaker version
* details about the operation input/configuration
* expected/actual behavior
* relevant logs
* reproduction steps

**Comment by saimadineni** [comment]
I should have mentioned that I was originally working on it. And I've fixed the issue.

https://github.com/spinnaker/clouddriver/pull/3571
fix(lambda): Current implementation of upsert lambda function does not work #4304 #3571
