### ISSUE TITLE
Halyard 1.19 is broken with aws-iam-authenticator

### ISSUE THREAD

**Issue by rverma-nikiai** [spinnaker/spinnaker#4306]
### Issue Summary:

Problems in Global:
! ERROR Failed check for Namespace/spinnaker in null
Unable to connect to the server: getting credentials: exec: fork/exec
  /usr/local/bin/aws-iam-authenticator: exec format error

### Cloud Provider(s):
aws

### Environment:
Spinnaker 1.13.4

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Halyard

**Comment by ezimanyi** [comment]
I think the change in spinnaker/halyard#1270 broke the link to download `aws-iam-authenticator`.  Unfortunately that didn't break the container build, but just ended up storing the error message file on disk, which fails when we try to execute that.  CC @jfillo

**Comment by ezimanyi** [comment]
Created a PR to fix the `aws-iam-authenticator` download in the docker build.  Also set the `kubectl` version to 1.12.7; as I thought of this more, we don't necessarily always want the newest `kubectl` version here.  As kubernetes allows a version skew of +/-1 between `kubectl` and the cluster, we will maximize overlap with our users by staying with at most N - 1 where N is the most recent version.  Given that 1.14 was just released, let's stay on 1.12 and then bump to 1.13 in a bit.

**Comment by ezimanyi** [comment]
Released halyard 1.19.1 with the fix for this.
