### ISSUE TITLE
Application is not immediately accessible after creation

### ISSUE THREAD

**Issue by error418** [spinnaker/spinnaker#4307]
### Issue Summary:

After creating an Application in the UI, Deck tells me that the Application cannot be found. After some time the Application appears in the UI and can be used.

The Spinnaker version `1.12.8` does not run into this issue. I can observe this behaviour since `1.13.0`.

This issue is similar to #1930.

### Cloud Provider(s):
* Kubernetes

### Environment:
* Kubernetes distributed deployment
* Minio `RELEASE.2019-03-27T22-35-21Z` as Storage
* GitHub Enterprise for authn/authz
* Spinnaker `1.13.4`

### Feature Area:
* Front50 (?)
* Fiat (?)

### Expectation

The application should be immediately available and be accessed after creating it.

### Actual Behaviour

Deck shows a 404 after creating an application. The application is not listed in the application list. After some time (5 to 8 minutes), the application becomes accessible and listed.

### Steps to Reproduce:
1. Create an Application
2. Redirect leads to 404
3. Wait some time (around 5 to 8 minutes)
4. Application appears in the application list and can be used

### Additional Details:

When trying to access the application front50 prints following logs:
(The application is configured to have no access restrictions)
```
10:25:19.420  INFO 1 --- [0.0-8080-exec-6] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/myuser
10:25:19.429  INFO 1 --- [0.0-8080-exec-6] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 200 http://spin-fiat.spinnaker:7003/authorize/myuser (8ms)
10:25:19.431  WARN 1 --- [0.0-8080-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.access.AccessDeniedException: Access is denied]
10:25:19.508  WARN 1 --- [.0-8080-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.access.AccessDeniedException: Access is denied]
```

It seems as soon as Fiat synchronizes the roles the application becomes accessible:

```

[ CREATING THE APPLICATION / FIRST ACCESS]

10:24:30.290  INFO 1 --- [0.0-7003-exec-4] c.n.s.fiat.controllers.RolesController   : [myuser] Role sync invoked by web request for roles: []
10:24:30.294  INFO 1 --- [0.0-7003-exec-4] c.n.s.fiat.roles.UserRolesSyncer         : [myuser] Synced anonymous user role.
10:24:30.336  INFO 1 --- [0.0-7003-exec-4] c.n.s.fiat.roles.UserRolesSyncer         : [myuser] Synced 11 non-anonymous user roles.

[ NO ACCESS POSSIBLE IN THIS TIME PERIOD (see front50 log above) ]

10:28:19.860  INFO 1 --- [pool-3-thread-1] c.n.s.kork.jedis.lock.RedisLockManager   : [] Acquired Lock Lock{name='fiat.userrolessyncer', ownerName='spin-fiat-697fd7d5fc-gvckr', leaseDurationMillis=10000, successIntervalMillis=600000, failureIntervalMillis=600000, version=1555410499859, ownerSystemTimestamp=1555410499860, attributes=''}.
10:28:19.861  INFO 1 --- [pool-3-thread-1] c.n.s.kork.jedis.lock.RedisLockManager   : [] Lock Lock{name='fiat.userrolessyncer', ownerName='spin-fiat-697fd7d5fc-gvckr', leaseDurationMillis=10000, successIntervalMillis=600000, failureIntervalMillis=600000, version=1555410499859, ownerSystemTimestamp=1555410499860, attributes=''} will heartbeats for 630000ms
10:28:19.869  INFO 1 --- [pool-3-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced anonymous user role.
10:28:19.882  INFO 1 --- [pool-3-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced 11 non-anonymous user roles.
10:28:19.883  INFO 1 --- [pool-3-thread-1] c.n.s.kork.jedis.lock.RedisLockManager   : [] Released lock (wasWorkSuccessful: true, Lock{name='fiat.userrolessyncer', ownerName='spin-fiat-697fd7d5fc-gvckr', leaseDurationMillis=10000, successIntervalMillis=600000, failureIntervalMillis=600000, version=1555410499859, ownerSystemTimestamp=1555410499860, attributes=''})

[ ACCESS POSSIBLE ]
```

**Comment by dibyom** [comment]
I think this is similar to https://github.com/spinnaker/spinnaker/issues/4276. Do you mind if we close this and track it there?

**Comment by error418** [comment]
@dibyom you are right - this issue slipped through my search
