### ISSUE TITLE
Memory usage of clouddrive keeps increasing

### ISSUE THREAD

**Issue by WakeupTsai** [spinnaker/spinnaker#4321]
### Issue Summary:
As you can see, the memory usage of the clouddrive (blue line) is keeping increasing, I have to restart the pod to release the memory. However the cpu usage(yellow line) seems really normal.
![image](https://user-images.githubusercontent.com/9034508/56479875-2fe25e00-64ea-11e9-81e5-8c5830dab730.png)

![image](https://user-images.githubusercontent.com/9034508/56479856-193c0700-64ea-11e9-9bb3-16c4c8d42662.png)

### Cloud Provider(s):
kubernetes v2.

### Environment:
Install on kubernetes
Spinnaker version: 1.13.3
clouddrive image tag: gcr.io/spinnaker-marketplace/clouddriver:4.4.2-20190406050308

**Comment by ezimanyi** [comment]
I'm going to merge this into #3287, which has a lot of other details/data on clouddriver's memory usage.  There have been a few fixes to how clouddriver calls `kubectl` in the past couple of releases that should help a bit, though the fact that this is still happening in 1.13 means we still need to investigate some more.

I plan to do some memory profiling of clouddriver to see if I can find anything; will use the other issue to track it.
