### ISSUE TITLE
[GCE/Deck] Unable to use parameters in Detail field

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4324]
### Issue Summary:
When adding a parameterized field into the `Detail` input, the UI does not let you save the pipeline, however you are able to edit the json directly and have it work as expected.

### Cloud Provider(s):
- GCE/GCP

### Environment:
Spinnaker 1.13.4

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
Inside the deploy stage in the `Detail` input if you try to type in a parameter, lets say `prod-east-${parameters["deployColor"]}`, the UI won't let you save the stage due to:

```
Detail can only contain letters, numbers, and dashes(-).
```

However, if you edit this in the json, and then save and run the pipeline, the expression is evaluated properly.

### Steps to Reproduce:
1. Create a paramter
2. Try to add it in the deploy-detail field when deploying to GCE

**Comment by seanpeters86** [comment]
Still happening on 1.14.0

**Comment by maggieneterval** [comment]
@seanpeters86 This should be a quick one to knock out: it appears we are reading off an (unconfigurable?) bool `templatingEnabled` on the view state that for other providers is defaulted to true but undefined for GCE, which determines the stack/detail validation regex. Just pinged the #deck channel to see if anyone else is using the bool so will either end up removing it altogether or figuring out why it's not defined in the first place for GCE :smile:
