### ISSUE TITLE
RFC: Remove Hipchat notification type

### ISSUE THREAD

**Issue by anotherchrisberry** [spinnaker/spinnaker#4328]
On [Feb 15](https://community.atlassian.com/t5/Stride-articles/Stride-and-Hipchat-Cloud-have-reached-End-of-Life-updated/ba-p/940248), Hipchat hit EOL. Atlassian is no longer supporting it, and have been encouraging users to migrate to Slack. On March 15, Atlassian discontinued access to historical data for Hipchat.

It's possible that there are users out there running the latest version of Spinnaker and also using Hipchat, but it seems unlikely. I can't find any issues (open or closed) mentioning Hipchat after 2014, and I can't find any mention of Hipchat in Slack (although I didn't look at the full archive).

We have no way of testing Hipchat (unless someone has a server running it), so I'd like to remove the code from the Spinnaker codebase altogether.

### Feature Areas:
Deck, Echo

**Comment by robzienert** [comment]
1. No disagreement on the work.
2. How to remove support of things in OSS version land? (Does this make us `v2.x`?) What's the implications of this?

**Comment by ajordens** [comment]
Approved.

**Comment by anotherchrisberry** [comment]
Code changes have been merged. Deferring to TOC on closing this issue.
