### ISSUE TITLE
Expose rendered Helm templates in k8s V2 bake manifest stage

### ISSUE THREAD

**Issue by eaceaser** [spinnaker/spinnaker#4334]
### Issue Summary:
Rendered Helm templates should be viewable from the UI directly.

### Cloud Provider(s):
K8s V2 Provider

### Environment:
n/a

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
UI, Rosco

### Description:
Currently, the rendered output of the bake manifest stage is only retrievable by looking at logs for the base64 output, and manually decoding it.

It would be great if the UI were to expose the rendered output directly; this would be a huge boon for debugging and general visibility.

### Steps to Reproduce:
n/a

### Additional Details:
n/a

**Comment by maggieneterval** [comment]
Hey @eaceaser this is a good idea, I just implemented this so hopefully we can get it in for release with 1.14.
