### ISSUE TITLE
spinnaker UI - In pipelines under bake  stage, Artifact Account is not showing selected option in the drop down

### ISSUE THREAD

**Issue by AnilKumarVasireddy** [spinnaker/spinnaker#4339]
### Issue Summary:
spinnaker UI - In pipelines under bake stage, Artifact Account is not showing selected option in the drop down and getting reset to always the first option in the drop down.

### Cloud Provider(s):
GCP

### Environment:
Kubernetes v2

### Description:
spinnaker UI - In pipelines under bake stage, Artifact Account is not showing selected option in the drop down. 
We have multiple Artifact account types.  Once we select desired one and save the stage and pipeline, if we come back and see it is always showing the first option in the drop down instead of the one which we select. If we change some other configuration and click on save, the above Artifact account is also getting saved to the first option which was displayed. 
<img width="880" alt="Screen Shot 2019-04-03 at 4 35 06 PM" src="https://user-images.githubusercontent.com/1965928/56760267-b3e94f80-674f-11e9-8d73-290ff2925e3c.png">

**Comment by maggieneterval** [comment]
Hey there @AnilKumarVasireddy, thanks for reporting. What version of Spinnaker are you running and do you have the `ARTIFACTS_REWRITE_ENABLED` flag on? This interface has churned a bit so just want to make sure I can reproduce your issue. Thanks!

**Comment by AnilKumarVasireddy** [comment]
Hi @maggieneterval , 
Thanks for looking into it.  Spinnaker version is 1.12.3. Not sure about option 'ARTIFACTS_REWRITE_ENABLED' . Can you please provide more details about it if we need to enable it.

**Comment by maggieneterval** [comment]
Hey @AnilKumarVasireddy, this has been resolved by this PR: https://github.com/spinnaker/deck/pull/6937

We'll patch this into 1.12 and 1.13!

**Comment by AnilKumarVasireddy** [comment]
Thanks @maggieneterval .
