### ISSUE TITLE
Recorded pipe configs are not respected by Start-Manual-Execution

### ISSUE THREAD

**Issue by mybayern1974** [spinnaker/spinnaker#4343]
### Issue Summary:
As the PR title

### Cloud Provider(s):
Azure. But it seems this issue is not related with any specific cloud provider.

### Environment:
1. Local Git Installation;
2. Use a VM-based pipe. While it seems this issue is not related whether VM or Container is used.

### Feature Area:
@spinnaker/ui-ux-team, or maybe Echo.

### Description:
Check repro steps below

### Steps to Reproduce:
1.	Create a pipe with simple stages say only including Bake and Deploy. Let’s name the business configurations of the pipe as Config-1;
2.	Execute the pipe, using either trigger or manual execution;
3.	Make whatever changes to Config-1 in #1 and let’s name the updated configurations of the pipe as Config-2;
4.	Execute the pipe, using manual execution.

**Expected Result:**
The pipe running in step 4 always respects Config-2;
**Actual Result:**
The pipe running in step 4 sometimes respects Config-1 and sometimes respects Config-2. Respecting Config-1 should be incorrect but it cannot stable repro.
In step 4, if using trigger rather than manual execution, then the execution always respect Config-2.

### Additional Details:
Per tier 1 investigation, we identified the commit: https://github.com/spinnaker/deck/commit/7f68f2218ed19905ecb3d0fea1ea390be9dc0e81. Things are normal if we revert code prior to this commit.

**Comment by cfieber** [comment]
I suspect this is fixed here
https://github.com/spinnaker/echo/pull/518

**Comment by mybayern1974** [comment]
> I suspect this is fixed here
> [spinnaker/echo#518](https://github.com/spinnaker/echo/pull/518)

Enn while i still ran into the problem with this fix

**Comment by mybayern1974** [comment]
Got the root cause. The used backend storage of front50 in this issue is Azure Storage. When fetching pipe configs there, by default the oldest one is fetched. The [fix ](https://github.com/spinnaker/front50/pull/520)has been merged. Close this issue.
