### ISSUE TITLE
Find Artifact from Execution does not support resolving from current pipeline trigger

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#4344]
### Issue Summary:
We need a way to attempt to resolve an artifact, then if not found use the normal artifact resolution strategy to pull a default artifact when specified

### Cloud Provider(s):
n/a

### Environment:
n/a

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
orca

**Comment by ezimanyi** [comment]
Dug into this a bit, and after chatting with @perek it seems like the correct solution here would be to have the "Find artifact from execution" stage support fields similar to the "Produces artifacts" section:
![image](https://user-images.githubusercontent.com/1391982/57306683-41faf980-70b1-11e9-9a78-9d443c324622.png)

That would allow both disambiguation of the trigger artifact vs the "find execution" artifact, as well as add the functionality for default artifacts into the "find artifact" stage.
