### ISSUE TITLE
Gremlin-stage broken (although enabled with Halyard)

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#4348]
### Issue Summary:

When Gremlin is enabled using Halyard (versions 1.19.0-1.19.2) - when trying to use the Gremlin-stage - we get a "Gremlin not enabled. Please set integrations.gremlin.enabled to true in Orca and Gate configuration." 

Screenshot here:

<img width="836" alt="Screenshot 2019-04-16 00 27 11" src="https://user-images.githubusercontent.com/26061075/56839765-57d41780-6884-11e9-8c6c-48a65ba03e94.png">

(API key is not valid anymore :) )

### Cloud Provider(s):

N/A

### Environment:

Spinnaker 1.13.5
Halyard versions: 1.19.0, 1.19.2

### Feature Area

Orca, Halyard, Gate

### Steps to Reproduce:

1. enable Gremlin with Halyard
2. try to use the Gremlin stage

### Additional Details:

PR's are already here:

PR's are already here:

https://github.com/spinnaker/halyard/pull/1293
https://github.com/spinnaker/gate/pull/788
https://github.com/spinnaker/orca/pull/2873

**Comment by iniinikoski** [comment]
PR's are already here:

https://github.com/spinnaker/halyard/pull/1293
https://github.com/spinnaker/gate/pull/788
https://github.com/spinnaker/orca/pull/2873

**Comment by iniinikoski** [comment]
This was released + fixed in Halyard version 1.12.1.

**Comment by rbmh** [comment]
Correction: 1.20.1...
