### ISSUE TITLE
Display name missing from Find Artifact from Execution stage

### ISSUE THREAD

**Issue by thecodejunkie** [spinnaker/spinnaker#4353]
### Issue Summary:
Artifact display names aren't included in `Find Artifact from Execution` stages, resulting in the artifact being displayed with blank names in the UI

### Cloud Provider(s):
GCP

### Environment:
Spinnaker v1.13.5 hosted on GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Pipelines

### Description:
When fetching an artifact, from a previous execution, then the artifact will not be assigned the display name, resulting in nameless artifacts being display in the UI

Creating the stage to find the artifact
![image](https://user-images.githubusercontent.com/50543/56922064-a7eeec00-6ac7-11e9-9cc0-237ff8869daf.png)

Trying to consume the artifact from a deploy stage
![image](https://user-images.githubusercontent.com/50543/56922080-afae9080-6ac7-11e9-8e1f-87a97056a4e3.png)

### Steps to Reproduce:
1. Create a pipeline that has an `Expected Artifact` declared with a `Display name` set
2. Create a second pipeline with a `Find Artifact from Execution` stage. Fill out the `File path` property, with the `Display name` from step one
3. Create a new `Deploy (Manifest)` stage. Choose `Manifest Source: Artifact`
4. Expand the `Manifest Artifact` drop-down

**Comment by ezimanyi** [comment]
I think this will end up being addressed along with #4344.

**Comment by ezimanyi** [comment]
Just confirmed that this was fixed by spinnaker/deck#6961.

**Comment by thecodejunkie** [comment]
@ezimanyi Which version will this fix land in? I'm currently on 1.14.4 and don't see it

**Comment by ezimanyi** [comment]
@thecodejunkie : This is in Spinnaker 1.14, so I'm not sure why you wouldn't be seeing it.

**Comment by thecodejunkie** [comment]
@ezimanyi the solution was to click on each of my previous `Find Artifact from Execution` steps so it could update the pipeline with the `display name` values, since it was those that were missing. Once I'd done that then they appeared in the `Deploy (Manifest)` -> `Manifest Artifact` dropdown
