### ISSUE TITLE
Enabling Canary Analysis causes the UI rendering failures

### ISSUE THREAD

**Issue by dmyerscough** [spinnaker/spinnaker#4360]
### Issue Summary:

When enabling Canary Analysis the "Infrastructure" > "Clusters" fails to render correctly. For example, before enabling Canary Analysis the UI looks like this:-

![image](https://user-images.githubusercontent.com/1395617/56944208-6403e300-6ad7-11e9-9596-ce98de37a9bf.png)

After enabling canary analysis you can see the ability to interact with the deployment does not appear:-

![image](https://user-images.githubusercontent.com/1395617/56944256-9281be00-6ad7-11e9-9182-b07ef59c39cd.png)

### Cloud Provider(s):

GCP

### Environment:

Kubernetes

### Steps to Reproduce:

Enable canary analysis for the features config.

**Comment by maggieneterval** [comment]
Hey @dmyerscough I'm having a tough time reproducing this one at head, what version of Spinnaker are you running?

**Comment by dmyerscough** [comment]
Hi @maggieneterval I believe this was due to an issue with the Canary backend /canary was throwing errors.
