### ISSUE TITLE
OutOfMemoryError for orca despite 80gb heap

### ISSUE THREAD

**Issue by mattnworb** [spinnaker/spinnaker#4367]
### Issue Summary:
We have been seeing an issue where all of a sudden Orca is using all of the Java heap available to it. We started with a heap size of 3gb, doubled it a few times, and are now using `-Xmx80g`. It seems like immediately after Orca starts up it very rapidly uses up the entire heap. Eventually all of the CPU time is spent in garbage collection, causing timeouts when Gate tries to communicate with Orca (for example to trigger a pipeline). Eventually Orca will exit since we have configured `-XX:+ExitOnOutOfMemoryError`.

![image](https://user-images.githubusercontent.com/113840/57080104-db946680-6cbf-11e9-9a45-c7c938478411.png)

In the graph above, Orca is deployed as a Kubernetes pod with 

```yaml
        requests:
          cpu: 8
          memory: 100Gi
```

Immediately after the pod is created, the memory usage spikes to ~80gb range (because of `-Xmx80g`), and Orca is using all of its CPU. The drop in the memory/CPU usage in the graph corresponds to the process exiting (`-XX:+ExitOnOutOfMemoryError`) and the container being recreated by the kubelet - the second instance of the container does not grow in heap usage as immediately fast as the first, but still grows rapidly.

`jstat` shows the survivor, eden, and old generation spaces completely full:

```
bash-4.4# jstat -gc 1 2s 200
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.6 76800.0 73978.8  0.0    0.0       45  144.146  37   1026.468 1170.615
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  38   1091.482 1235.629
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  39   1113.593 1257.739
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  39   1113.593 1257.739
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  39   1113.593 1257.739
9320448.0 9320448.0  0.0    0.0   9320960.0 9320960.0 55924224.0 55924021.3 76800.0 73978.8  0.0    0.0       45  144.146  39   1113.593 1257.739
```
 
### Cloud Provider(s):
We deploy Spinnaker on GKE, master version 1.11.8-gke.6 and node version 	
1.11.7-gke.12. The resource request of the Orca pod is above.

### Environment:
Spinnaker is deployed to Kubernetes via Halyard version 1.12.5. Orca is at version gcr.io/spinnaker-marketplace/orca:2.4.0-20190308182538.

Our Spinnaker instance has a single pipeline that deploys Kubernetes manifests to one of 15 GKE clusters (each is added as an account in Spinnaker, so there are 15 accounts). The pipeline is triggered with an argument that is the name of the GKE cluster to deploy to, and the pipeline has a conditional on each cluster to only deploy to the selected one. Each GKE cluster is at the same master/node version mentioned above.

We run Redis on a GCE instance outside of Kubernetes, at version 5:4.0.9-1ubuntu0.1. We do not use the SQL options for Orca's persistence. Some possibly interesting stats from the `redis-cli info` command:

```
# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:76095d16786fbcba
redis_mode:standalone
os:Linux 4.15.0-1029-gcp x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.3.0
process_id:8145
run_id:f2ec851105f1f1d472cc8aa02fe3800eb3ee7210
tcp_port:6379
uptime_in_seconds:76722
uptime_in_days:0
hz:10
lru_clock:13301520
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:48
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:4560737864
used_memory_human:4.25G
used_memory_rss:5111205888
used_memory_rss_human:4.76G
used_memory_peak:4562860264
used_memory_peak_human:4.25G
used_memory_peak_perc:99.95%
used_memory_overhead:10992833
used_memory_startup:273544
used_memory_dataset:4549745031
used_memory_dataset_perc:99.76%
total_system_memory:27389468672
total_system_memory_human:25.51G
used_memory_lua:87040
used_memory_lua_human:85.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.12
mem_allocator:jemalloc-3.6.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:17624
rdb_bgsave_in_progress:0
rdb_last_save_time:1556805357
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:40
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:38006784
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:2495
total_commands_processed:121573332
instantaneous_ops_per_sec:2958
total_net_input_bytes:41279502138
total_net_output_bytes:8040429303769
instantaneous_input_kbps:2891.43
instantaneous_output_kbps:304272.94
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:285718
expired_stale_perc:0.51
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:55060758
keyspace_misses:58215213
pubsub_channels:0
pubsub_patterns:3
latest_fork_usec:163824
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:f3cfc63310bb2b15cf336da1d82f3b11dd459dbb
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:5194.31
used_cpu_user:6772.37
used_cpu_sys_children:920.36
used_cpu_user_children:8534.84

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=163934,expires=9953,avg_ttl=19024940
```

---

Any tips or ideas into what we can look into to understand why Orca is consuming so much memory so fast?

**Comment by ethanfrogers** [comment]
@mattnworb do you all have `-XX:+UnlockExperimentalVMOptions XX:+UseCGroupMemoryLimitForHeap` set as `JAVA_OPTS` in the Orca deployment? I noticed that ,despite the resource constraints, it was exceeding the memory allocation.

**Comment by mattnworb** [comment]
@ethanfrogers our full JVM args are:

```
-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XX:+ExitOnOutOfMemoryError -Xmx80g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps/oom.bin
```

We added `-Xmx80g` because we found that `-XX:MaxRAMFraction=2 ` was topping out at a max heap size of 32gb, even with the memory request/limit in Kubernetes set to 100gb.

**Comment by mattnworb** [comment]
I was able to load a giant (63gb) heap dump into Eclipse's Memory Analyzer, here are a few things I found at first glance:

Instances of `rx.internal.operators.OperatorMerge$MergeSubscriber` are at the top of the "dominator" list: 

![image](https://user-images.githubusercontent.com/113840/57100341-b5d18680-6cec-11e9-9a22-ee1f9b2e631c.png)

expanding the child nodes of one of those shows that the data stored inside its RingBuffer is a lot of `com.netflix.spinnaker.orca.pipeline.model.Execution` instances:

![image](https://user-images.githubusercontent.com/113840/57100395-d8639f80-6cec-11e9-921e-5f59cf70a0e4.png)

All of the instances of `rx.internal.operators.OperatorMerge$MergeSubscriber` and what they are retaining account for almost all of the heap size used: 

![image](https://user-images.githubusercontent.com/113840/57100633-748da680-6ced-11e9-8f73-75699eab7972.png)

It seems like our Orca instance has quite a lot of `com.netflix.spinnaker.orca.pipeline.model.Execution` and `Task` instances in its heap:

![image](https://user-images.githubusercontent.com/113840/57101450-41e4ad80-6cef-11e9-935c-8dd445461c9c.png)

**Comment by mattnworb** [comment]
one potential problem - it looks like each `com.netflix.spinnaker.orca.pipeline.model.Stage` instance has a unique `com.fasterxml.jackson.databind.ObjectMapper` instance, for a total of 966,815 instances in this total heap:

![image](https://user-images.githubusercontent.com/113840/57102140-bf5ced80-6cf0-11e9-843e-705998838941.png)

**Comment by mattnworb** [comment]
We took a backup of the Redis datastore and found there were 11k instances of pipeline executions being stored (we did not realize Redis was persisting all of the executions, we have since enabled the expiration):

```
[mattbrown@mattmbp ~]$ redis-cli keys 'pipeline:*' | grep -v stageIndex | wc -l
   11140
```

Using Eclipse Memory Analyzer and a OQL query (`SELECT toString(x.id) FROM com.netflix.spinnaker.orca.pipeline.model.Execution x`) I was able to extract the `String id` field of all of the ~57k instances of `com.netflix.spinnaker.orca.pipeline.model` execution in my heap.

```
[mattbrown@mattmbp ~]$ uniq -c /tmp/ids | sort -r
 123 01D9W51ADYCYQZ5NC5APMNNQ9V
 123 01D9W4ZJTBSPBE8AYB0YC1R5TJ
 122 01D9W509DN07E3VSZ4CJGSARVD
 122 01D9W4Z8SS0FK7F5ZVXYWCBP7C
 121 01D9W4Y9013B7ZCW6VJKVQJA1A
 120 01D9W555Q1BNCEEX8BFTNRXZNZ
 120 01D9W4Z8EX8B6RZHSEDETZZZZF
 120 01D9W4Z8AXMC2YKVY0F646MA24
 119 01D9W54J15JV82TVVHJ3KQQ8M2
 119 01D9W4WJG6NMPGV5JAJ65JYF3N
 118 01D9W51VZZVF7G5YXHV5GMAF0Z
 117 01D9W58BVJ86BGHBH34PMFMBC3
 117 01D9W54HEP5E620ZGKCYRT1JYF
 117 01D9W4W3WHQJBTCWN47RVSNZGN
 116 01D9W4PKAR2HCZ58FB718VHQZB
 114 01D9W4PHX9VX9DKWGJ8M88ZFSY
 114 01D9W4PHVJJK09N631K9CN1Q5Z
 113 01D9W58W499EXNQYZK0RXA7X09
 113 01D9W4PHV17D966G890GF3MBST
 111 01D9W54GSMZ41Z043VN9FEDMJ4
 110 01D9W4P0ERGFAPKMCM5WBAS6V3
 108 01D9W4NWEHQQ1XTXFJTMEGZH1T
 108 01D9W4N8X4PQD0JW7V9ZEGVCJR
 108 01D9W4N8W3FT75VPX8V6ZQFWN8
 107 01D9W4N8VVH41KXQ4FGGW7JMWW
 105 01D9W4N8GYM9B7H91D1QDVRAX9
 102 01D9W4ME9TS46V3BTBWWBKXRYC
 102 01D9W4KA7B10AVJQGS2DEFJ273
 102 01D9W4K264EBM0NGCW34A0GX49
 102 01D9W4JKM7D30ZW3R81XB4NK4Z
 102 01D9W4J9P46NREHXVJRXFC30X4
 101 01D9W4HYF8D6B657KTSCCPR2SC
 101 01D9W4HNVAK1JRFVME7MZRJ9C9
 101 01D9W4HBXEA1Q7N66B3WM47ZB2
 101 01D9W4H7NDHJKYBYZG2PYJN5W1
 101 01D9W4GQ0TAZ6X2T8CB1P9R00G
 101 01D9W4GQ0PEQDT21391JXZT3MZ
 101 01D9W4GQ0BCYYYJ38GGTSCG1KG
 101 01D9W4GJ89SNQ68JD2KZJDVX21
 100 01D9W4FQFQ7R4624QV6CG941GM
 100 01D9W4FGH59JDV9Z26SHM8ANHM
 100 01D9W4ENTVKWQH8WEQJ9KZ5KBR
...
   1 01D9TJ1AYYKM2BESH10S996CB5
   1 01D9TJ1ATF4QNSESRK639DME02
   1 01D9TJ0VQMYKDR9KQ4VXG62TKA
   1 01D9TJ0JS14DF1WWVNA491HK41
   1 01D9TJ0JP31JEY8G78AQ8FJG7Z
   1 01D9TJ0JK6X49P36YPG4W7RY9V
   1 01D9THZWQ99H3DWKK574QS1S6Q
   1 01D9THZWJYGPV6PNZKJK73W1VZ
```

What could cause Orca to load 100+ or dozens of `Execution` instances for the same `id` into memory and retain them all in the heap?

**Comment by jtk54** [comment]
Can you run a slowlog on your redis instance that backs the pipeline execution repository? We've seen performance issues in the past somewhat related so I want to see if it's the same [suspect](https://github.com/spinnaker/orca/pull/2757).

**Comment by mattnworb** [comment]
@jtk54 that is a good idea, thanks! What time value do you think would be useful to use with `SLOWLOG GET` to find any possible problems?

**Comment by jtk54** [comment]
I think the [args are just an integer](https://redis.io/commands/slowlog), e.g. `redis 127.0.0.1:6379> slowlog get 25` which should dump out which commands are taking longest with all the relevant info.

**Comment by mattnworb** [comment]
@jtk54 ah thank you for the clarification, I misread the argument to `slowlog get` as being the threshold of what counts as too long of a query. I'll watch this and share anything interesting that we find!

**Comment by mattnworb** [comment]
Through a bit of trial and error, we've routed most of our services that deploy to GKE via Spinnaker to one Spinnaker instance and a small subset (3-5 services) to a second Spinnaker instance. Currently only the second one is seeing OOMs in Orca, so we have a good feeling that the content of one of these sets of manifests is the problem. Will take some more digging to narrow it down further.

We invoke our Spinnaker pipeline remotely via another tool, so we were able to easily modify that tool to have some logic around if it sends the trigger pipeline request and manifests to instance A or B.

**Comment by mattnworb** [comment]
Hi, I think we figured out the problem we were having (we had mitigated the problem for 99% of our applications using Spinnaker, so finding a resolution was not the highest priority).

Some of the problem is caused by the unique way we are using Spinnaker, although I think there are a few improvements that could be made in Orca that would be good ideas in general. 

A little bit about our environment: we use Spinnaker to deploy services to Kubernetes, and we trigger Spinnaker pipelines programmatically via another tool (we never trigger pipelines through the UI). We have a single pipeline that we snake all deployments and services through - since we are deploying k8s manifests via the Kubernetes V2 provider, we simply pass those from the first tool to the Spinnaker pipeline as artifacts in the trigger pipeline request. We don't have a need for a unique pipeline per application/service.

When Gate calls the `POST /orchestrate` endpoint of Orca, OperationsController’s [parsePipelineTrigger method invokes `artifactResolver.resolveArtifacts(pipeline)`](https://github.com/spinnaker/orca/blob/version-2.4.1/orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy#L260-L262). `ArtifactResolver.resolveArtifacts(pipeline)` loads [every Execution of the pipeline in order to find the artifacts of the previous execution](https://github.com/spinnaker/orca/blob/version-2.4.1/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java#L143-L151): 

```java
    Execution execution = executionRepository
        .retrievePipelinesForPipelineConfigId(pipelineId, criteria)
        .subscribeOn(Schedulers.io())
        .toSortedList(startTimeOrId)
        .toBlocking()
        .single()
        .stream()
        .findFirst()
        .orElse(null);
```

Our problem is that, since we have a single pipeline instance for all services, before we enabled `oldPipelineCleanup` we had an unbounded list in our Redis instance. Each concurrent "trigger pipeline" request to Orca will (in our case) load this same (large) `List<Execution>` before throwing all but the last one away. Some of our `Execution` instances are fairly large - 8mb in memory usage - because the "application" actually contains 100+ Kubernetes resources. 

Additionally, in our use case, we never actually need these priorArtifacts - because every pipeline trigger request includes the artifacts - but OperationsController/ArtifactResolver loads them anyway. 

As mentioned above, we have two identical spinnaker instances that are both configured with the same set of Kubernetes clusters, which was useful for us to A/B test various ideas. Once we enabled `oldPipelineCleanup`, the "main" instance was fully healthy, but the "test" instance still had the same OOM behavior. It took us a while to realize that this was because we had accidentally provisioned the Redis instance used in the second spinnaker instance in a different region than where the micro services were deployed, so each request to Redis had to traverse the Atlantic Ocean (from GCP’s us-central1 region to europe-west1), multiplied by the 1000+ past Execution instances stored in our Redis. Because of the latency, the growing List<Execution> is held in memory for far longer, allowing concurrent "Trigger pipeline" requests to fill up the entire heap as each thread tries to populate the same List<Execution>. Moving the Redis instance to be in the same region resolves the latency issue and therefore the OOM issue for this "test" spinnaker instance.

---

So while a lot of this is probably due to our (unique?) use case, there are a few suggestions I have to improve the memory performance here. Please let me know if I should turn these into separate issues - I'd also be happy to make a stab at PRs for each.

1. `ArtifactResolver.resolveArtifacts(Map)` could be made to not bother to call `ExecutionRepository.retrievePipelinesForPipelineConfigId()` until the point at which it actually needs to use any prior artifacts (when there are `unresolvedExpectedArtifacts` in `resolveExpectedArtifacts(List, List, List, boolean)` and `expectedArtifact.isUsePriorArtifact()` is `true`).

2. Ideally it would not be necessary for `ArtifactResolver.getArtifactsForPipelineId(String, ExecutionCriteria)` to load and fully hydrate every stored Execution instance of a Pipeline in order to access the most recent execution (although I can imagine that the schema of object storage in Redis makes that difficult - the SQL implementation is probably more straight forward). Adding a method in `ExecutionRepository` like `retrieveLastExecutionForPipelineConfigId(String pipelineId)` could be useful - perhaps the Redis implementation could look at all the executionIds of the pipeline and compare the startDate of each before hydrating the full object.

3. Lastly, I noticed in our heap dumps that there are hundreds of thousands of `ObjectMapper` instances, since each instance of `com.netflix.spinnaker.orca.pipeline.model.StageContext` creates a new ObjectMapper instance (and our heap has 80k StageContext instances). 

![image](https://user-images.githubusercontent.com/113840/58337454-d2586e80-7e13-11e9-9561-a3606c398a11.png)

[ObjectMapper is thread-safe after initial construction/configuration](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html), and reusing the same instance would save some memory. Each ObjectMapper instance has a unique [com.fasterxml.jackson.databind.ser.SerializerCache](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ser/SerializerCache.html) instance, meaning that all of these ObjectMappers are caching some of the data they have seen.

**Comment by mattnworb** [comment]
I submitted some PRs for 1 and 3 above 😎 : https://github.com/spinnaker/orca/pull/2937 and https://github.com/spinnaker/orca/pull/2938

**Comment by jtk54** [comment]
Thanks for the detailed solution and PRs, very helpful insight.

**Comment by ezimanyi** [comment]
Thanks for the thorough analysis and fixes for this!  spinnaker/orca#2937 and spinnaker/orca#2955 are merged now, and I believe that spinnaker/orca#2955 is superseded by those two that were merged.

**Comment by mattnworb** [comment]
I closed 2938 since it is definitely replaced by 2955. Thanks for the help and advice on implementing a patch @ezimanyi!

**Comment by mattnworb** [comment]
I wanted to share an update on this issue - Spinnaker v1.12.13 contained my PR https://github.com/spinnaker/orca/pull/2991 above, and we recently deployed this to our production Spinnaker instance on July 9- here is a graph of Orca's heap memory usage before and after:

![image](https://user-images.githubusercontent.com/113840/61746522-e19f5e00-ad69-11e9-855c-7db788fd5bd3.png)

thanks again for the help on this @ezimanyi @maggieneterval !
