### ISSUE TITLE
Deploying Istio manifests from helm charts fails

### ISSUE THREAD

**Issue by german-muzquiz** [spinnaker/spinnaker#4372]
### Issue Summary:
Trying to have Spinnaker to deploy Istio using their official helm charts fails.

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker running in EKS

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Kubernetes V2 provider

### Description:
We have a pipeline that bakes [Istio helm charts](https://istio.io/docs/setup/kubernetes/install/helm/). When the baked yaml's try to be deployed, there's this error in UI:

```
Exception ( Deploy Manifest )
java.lang.IllegalStateException: Failure evaluating manifest expressions: {#!/bin/sh

set -x

if [ "$#" -ne "1" ]; then echo "first argument should be path to custom resource yaml" exit 1 fi

pathToResourceYAML=1

kubectl get validatingwebhookconfiguration istio-galley 2>/dev/null if [ "$?" -eq 0 ]; then echo "istio-galley validatingwebhookconfiguration found - waiting for istio-galley deployment to be ready" while true; do kubectl -n istio-system get deployment istio-galley 2>/dev/null if [ "$?" -eq 0 ]; then break fi sleep 1 done kubectl -n istio-system rollout status deployment istio-galley if [ "$?" -ne 0 ]; then echo "istio-galley deployment rollout status check failed" exit 1 fi echo "istio-galley deployment ready for configuration validation" fi sleep 5 kubectl apply -f pathToResourceYAML=[Result {description='Failed to evaluate [run.sh] : #!/bin/sh

set -x

if [ "$#" -ne "1" ]; then echo "first argument should be path to custom resource yaml" exit 1 fi

pathToResourceYAML=1

kubectl get validatingwebhookconfiguration istio-galley 2>/dev/null if [ "$?" -eq 0 ]; then echo "istio-galley validatingwebhookconfiguration found - waiting for istio-galley deployment to be ready" while true; do kubectl -n istio-system get deployment istio-galley 2>/dev/null if [ "$?" -eq 0 ]; then break fi sleep 1 done kubectl -n istio-system rollout status deployment istio-galley if [ "$?" -ne 0 ]; then echo "istio-galley deployment rollout status check failed" exit 1 fi echo "istio-galley deployment ready for configuration validation" fi sleep 5 kubectl apply -f pathToResourceYAML not found', exceptionType=null, timestamp=1556900920154, level=INFO}]}
```

We did a test grabbing the generated yaml files from pipeline's execution and they were successfully installed by doing a manual `kubectl apply`. Istio yaml's are pretty big and have a lot of content like embedded shell scripts and regular expressions. Something might be broken in the process of passing those files to `kubectl`

### Steps to Reproduce:
1. Download Istio helm charts from official page.
2. Package the charts with `helm package`.
3. Create a pipeline in Spinnaker that grabs these charts and uses appropriate value overrides, bakes the charts (Bake Manifest stage) and deploys them (Deploy Manifest stage).

**Comment by ethanfrogers** [comment]
@german-muzquiz this is a known issue and is fixed in 1.13.

See:
https://github.com/spinnaker/orca/pull/2761
https://github.com/spinnaker/deck/pull/6696

This stems from a conflict between `${}` being used for shell expansion and SPeL evaluation. These PRs allow you to skip SPeL evaluation when using the Deploy (Manifest) stage.
