### ISSUE TITLE
Halyard: add --path-style-access option to `hal config storage s3 edit` command

### ISSUE THREAD

**Issue by tiggerlee2** [spinnaker/spinnaker#4400]
### Issue Summary:
The pathStyleAccess was make configurable(#4142), but hal can not set this option.

### Cloud Provider(s):
Kubernetes

### Environment:
Halyard

**Comment by ezimanyi** [comment]
Seems like a good change and could be done following what was done in spinnaker/front50#496

**Comment by tiggerlee2** [comment]
spinnaker/halyard#1308

**Comment by ezimanyi** [comment]
Added in spinnaker/halyard#1308
