### ISSUE TITLE
Can not load servergroup when some rs set dnsPolicy as 'None'

### ISSUE THREAD

**Issue by abcsnowwolf** [spinnaker/spinnaker#4406]
### Issue Summary:
When set dnsPolicy field as 'None', Servergroups(include deployment and rs) in this namespace will not be loaded. I find that in v1 provider DeployKubernetesAtomicOperationDescription class, dnsPolicy filed is a emu, and it does not contain 'None'. 
### Cloud Provider(s):
kubernetes

**Comment by ezimanyi** [comment]
Fixed in spinnaker/clouddriver#3663
