### ISSUE TITLE
Hal deploy apply: Unexpected Exception: while parsing a block mapping

### ISSUE THREAD

**Issue by BrianChristie** [spinnaker/spinnaker#4416]
### Issue Summary:
When executing `hal deploy apply` the following error occurs:
```
 Problems in Global:
! ERROR Unexpected exception: while parsing a block mapping
 in 'string', line 7, column 5:
        app: spin
        ^
expected <block end>, but found '}'
 in 'string', line 9, column 5:
        }
        ^

- Failed to deploy Spinnaker.
```

### Cloud Provider(s):
N/A

### Environment:
Mac OS

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
halyard

### Steps to Reproduce:
run `hal deploy apply` with 1.20.0

### Additional Details:
It's been noted on Slack that this is a known issue and will be fixed in halyard 1.20.1. 
Until then the workaround is to use 1.19.2 with `sudo update-halyard --version 1.19.2`

https://spinnakerteam.slack.com/archives/C091CCWRJ/p1557988226228500?thread_ts=1557986561.228000&cid=C091CCWRJ

Hope this is useful to anyone who runs into this problem.

**Comment by ezimanyi** [comment]
This has been fixed and Halyard 1.20.1 has been released; sorry for the inconvenience!
