### ISSUE TITLE
Annotations Missing after Bake + Deploy for Some Kubernetes Resources

### ISSUE THREAD

**Issue by daviddyball** [spinnaker/spinnaker#4418]
### Issue Summary:

When a Helm chart is baked and produces `annotations` on a `Service` the subsequent `deploy` stage removes the annotations entirely. We also see the same behaviour for some `CustomResources` we've authored.

### Cloud Provider(s):

Kubernetes v2

### Environment:
Spinnaker versions:
```
gcr.io/spinnaker-marketplace/clouddriver:4.4.1-20190402130801
gcr.io/spinnaker-marketplace/deck:2.8.1-20190402130801
gcr.io/spinnaker-marketplace/echo:2.4.0-20190318162446
gcr.io/spinnaker-marketplace/front50:0.16.1-20190329125256
gcr.io/spinnaker-marketplace/gate:1.7.0-20190402050308
gcr.io/spinnaker-marketplace/igor:1.2.0-20190322100313
gcr.io/spinnaker-marketplace/orca:2.6.0-20190402050308
gcr.io/spinnaker-marketplace/rosco:0.11.0-20190322234525
```

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Kubernetes v2 Provider

### Description:

A helm chart that includes a `Service` with annotations on it renders correctly during the "Bake" stage, but when applied in a "Deploy Manifest" stage the resulting entity is missing all `metadata.annotations` except the `kubectl.kubernetes.io/last-applied-configuration` key/value. It seems something is causing `clouddriver` to strip all the annotations (even the `moniker.spinnaker.io` and related ones that it adds itself)

### Steps to Reproduce:

I'm really struggling to find how to make this happen on demand. We have a base chart that we use for all of our deployments and using this chart causes it to fail for annotations but, after trying to create a test chart to attach to this issue, I found that annotations were working correctly. The only difference between the charts is that our companies chart contains >20 resources and the test chart only had a `Service` entity. Could it be something to do with multi-doc manifests?

I'd love to get to the bottom of this as annotations are integral to our platform, so any advice on debugging is appreciated

### Additional Details:
* Annotations on `Ingress` and `Deployments` seem to work fine.
* We're not using any SpEL functions in our charts

Could be related to https://github.com/spinnaker/spinnaker/issues/4355, but I saw that they are specifically having issue when using SpEL in their annotations. Disabling SpEL in our Deploy Manifest stages has no effect

**Comment by daviddyball** [comment]
OK, I've figured this out, but not sure if it's a bug that needs fixing or just documenting behaviour.

Basically our helm template looked like this:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: true
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8008"
  {{- end }}
spec:
......
...
```

The issue is simply that `prometheus.io/scrape: true` didn't have `true` wrapped in quotes (should be `"true"`). I think the issue is possibly located in the [KubernetesdeployManifestConverter](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/converter/manifest/KubernetesDeployManifestConverter.java). It seems that, if it runs into a non `Map<string, string>` value it seems to simply return an empty `Map` altogether, even if it was only one value that failed. Perhaps failures could be handled on a per-annotation basis? It certainly would have made it easier to debug if the only annotation that was missing was the one that wasn't correctly quoted.

**Comment by ezimanyi** [comment]
I think this is essentially the issue in #4355.  In that case the issue was that a SpEL expression in an annotation wasn't being evaluated and caused an invalid annotation---but the end result was that *all* annoations were removed which was confusing.  I'll close this and use the other issue to track seeing if we can fail on a per-annotation basis.

**Comment by ezimanyi** [comment]
Ha, you linked that issue above as well, didn't see that at first.
