### ISSUE TITLE
spin access/refresh token not found in OAuth Token

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4425]
### Issue Summary:

Following instructions to authenticate spin with OAuth tokens fails with messages:

```
  line 10: field accessToken not found in type oauth2.Token
  line 11: field refreshToken not found in type oauth2.Token
```

### Cloud Provider(s):

Google OAuth

### Environment:

Spinnaker 1.13.7 on GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

spin CLI

### Description:

Running `spin -k --config /home/spinnaker/.spin/config pt list` outputs (see output for contents of config file)

```
Could not deserialize config file with contents: gate:
  endpoint: http://spin-gate.spinnaker:8084
auth:
  enabled: true
  oauth2:
    authUrl: https://accounts.google.com/o/oauth2/auth
    tokenUrl: https://oauth2.googleapis.com/token
    scopes: []
    cachedToken:
      accessToken: xxx
      refreshToken: xxx
, failing.
yaml: unmarshal errors:
  line 10: field accessToken not found in type oauth2.Token
  line 11: field refreshToken not found in type oauth2.Token
```

### Steps to Reproduce:

Follow [instructions to create a spin config file with access & refresh tokens](https://www.spinnaker.io/guides/spin/cli/#access-and-refresh-token) instead of client id/secret.

### Additional Details:

One note here is that I'm not sure what to put for `scopes`, although I'm guessing this is unrelated.

**Comment by milesmatthias** [comment]
Ha, *very* subtle issue here: 

`accessToken` should be `accesstoken`

and

`refreshToken` should be `refreshtoken`

note the lack of camel casing, whereas `cachedToken` is camel cased.

**Comment by demobox** [comment]
Thanks for posting, @milesmatthias! Could you try walking through the [client ID and client secret flow]() (not necessarily for that Spinnaker installation) and then looking at the resulting `~/.spin/config` file?

Based on [the code](https://github.com/golang/oauth2/blob/master/token.go#L34-L43), I suspect the fields may actually be `refresh_token` and `access_token`, or something like that.

**Comment by demobox** [comment]
> Ha, very subtle issue here:

Ah, you beat me to it ;-) Glad it seems to be working!

**Comment by milesmatthias** [comment]
for scopes, I believe the correct Google OAuth scopes for sign in are:

```
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/userinfo.profile
```

**Comment by milesmatthias** [comment]
Still haven't been able to authenticate yet unfortunately...

**Comment by milesmatthias** [comment]
For anyone that sees this in the future (maybe I'll send a docs PR), here are the values you should use when using Google OAuth:

```
    tokenUrl: https://accounts.google.com/o/oauth2/v2/auth
    authUrl: https://www.googleapis.com/oauth2/v4/token
    scopes:
    - email
    - profile
```

and then obviously either a `clientId`/`clientSecret` or `accesstoken`/`refreshtoken`
