### ISSUE TITLE
Google Cloud Build breaks Igor

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4437]
### Issue Summary:

Following the directions to enable a Google Cloud Build account results in a crashed Igor deployment.

### Cloud Provider(s):

GCP

### Environment:

Spinnaker 1.14 on GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Igor / CloudBuild

### Description:

Here are the error logs when Igor tries to startup:

```
Property source 'applicationConfig: [classpath:/igor.yml]’:
Key: endpoints.health.sensitive
Line: 15
Reason: Endpoint sensitive flag is no longer customizable as Spring Boot no longer provides a customizable security auto-configuration .

Parameter 2 of method googleCloudBuildCacheFactory in com.netflix.spinnaker.igor.config.GoogleCloudBuildConfig required a bean of type 'com.netflix.spinnaker.igor.polling.LockService' that could not be found.

The following candidates were found but could not be injected:
- Bean method 'lockService' in 'LockManagerConfig' not loaded because @ConditionalOnProperty (locking.enabled) did not find property ‘locking.enabled'

Consider revisiting the entries above or defining a bean of type 'com.netflix.spinnaker.igor.polling.LockService' in your configuration.
```

### Steps to Reproduce:

On a Spinnaker instance that *does not* have Igor deployed (because it's not using Jenkins or Github), follow instructions to add a GCB CI account via hal: https://www.spinnaker.io/setup/ci/gcb/

### Additional Details:

This is the first deployment of Igor on this instance, so I thought I needed to add Github artifact account to get this to work (maybe someone forgot to test a fresh install with just GCB?), but I tried adding one and no luck either.

Also, I do not have a custom igor.yml file.

**Comment by ezimanyi** [comment]
I forgot to add to the docs that this requires setting:
```
locking:
  enabled: true
```
in your `igor-local.yml` file as this functionality depends on having igor locking enabled.  I was going to see if I could default locking to enabled in 1.14 but did not get that done in time for the release, so for now it will need to be manually enabled.

I'll add this to the docs so nobody else runs into it.

**Comment by milesmatthias** [comment]
Hmm, unfortunately that's not working for me.

**Comment by ezimanyi** [comment]
Discussed offline; the config block above is a top-level config block in `igor-local.yml` (not a sub-block of `gcb`).
