### ISSUE TITLE
K8S v2 support booleans in overrides

### ISSUE THREAD

**Issue by eddycharly** [spinnaker/spinnaker#4438]
### Issue Summary:
Booleans in value overrides are not supported in bake manifest stage.
If set to true it is kept in the pipeline json (as string).
If set to false it is not persisted in the pipeline json.

Boolean values are usefull to customise the helm chart processing.

### Cloud Provider(s):
K8S v2

### Steps to Reproduce:
Simply add a value override in the bake manifest stage for k8s v2 provider, set the value to true, the value is persisted to "true" (as string), set the value to false, the value is discarded when saving the pipeline.

**Comment by maggieneterval** [comment]
Hey @eddycharly, I think this issue is a duplicate of this [issue](https://github.com/spinnaker/spinnaker/issues/3950) -- going to close this one but feel free to continue the conversation there (I will remove the "stale" tag).
