### ISSUE TITLE
CF - Optionally skip validation of targeted Cloud Foundry API endpoint's SSL certificate

### ISSUE THREAD

**Issue by pdelagrave** [spinnaker/spinnaker#4441]
### Issue Summary:
CF accounts can sometimes be configured with an API endpoint having a convenient but unsecure self-signed/untrusted server certificates.
Until a feature to include arbitrary trusted certificates is implemented, the quick fix is to have strict validation enabled by default, with the option to disable it per account.

### Cloud Provider(s):
* Cloud Foundry

### Feature Area
* Halyard
  * `hal config provider cloudfoundry account add/edit`
* Clouddriver
  * `HttpCloudFoundryClient`

### Description:
* `hal config provider cloudfoundry account add/edit --skip-ssl-validation`
  * False by default/when parameter not specified
* `HttpCloudFoundryClient`
  * Validates the SSL certs using the existing default keystore's trusted certs.
  * Skips the validation when the account config explicitely says so.

Existing CF accounts will start validating SSL certs by default, which is a breaking change.
Users will have to `hal config provider cloudfoundry account edit ACCOUNT_NAME --skip-ssl-validation` on every accounts (as needed) to maintain the original behaviour.

**Comment by okundzich** [comment]
@spinnakerbot add-label provider/cf
