### ISSUE TITLE
Rosco fails with null exception when triggered from webhook

### ISSUE THREAD

**Issue by mrothroc** [spinnaker/spinnaker#4445]
### Issue Summary:
When a pipeline is triggered from a webhook that provides a GCS artifact, rosco throws an npe.

### Cloud Provider(s):
GCP

### Environment:
I am running Spinnaker 1.14.0 in GKE and deploying to the same GKE cluster in different namespaces.  All of my artifacts are stored in GCS, in the same project.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
components/rosco

### Description:
I have a pipeline that requires a helm package as an artifact.  This package is stored in GCS.  When I trigger the pipeline with a pubsub message from GCS, it works correctly.  When I run it with a webhook, rosco throws a null pointer exception and the pipeline fails.

This message is logged:
java.lang.NullPointerException: null at com.netflix.spinnaker.rosco.manifests.TemplateUtils.nameFromReference(TemplateUtils.java:37)

### Steps to Reproduce:
Store a helm package in GCS and trigger a pipeline with a webhook that lists that artifact.

### Additional Details:
Here is the webhook body as logged by the controller:
c.n.s.e.controllers.WebhooksController : Webhook webhook:jenkins:[artifacts:[[type:gcs/object, name:gs://redacted/test-cd-0.1.0.tgz]]]

![Screen Shot 2019-05-23 at 10 10 11 AM](https://user-images.githubusercontent.com/5827718/58273852-60feba00-7d46-11e9-9d2f-8c0956ac8ad5.png)

**Comment by ezimanyi** [comment]
@mrothroc : I think this is a duplicate of #4110 and there is an explanation on that issue.  (Also, the error message has been improved though not in a release yet.)

**Comment by mrothroc** [comment]
Yep, the fix from that bug works for me.  In addition to the error message, I think there is a doc bug on this page:
https://www.spinnaker.io/guides/user/pipeline/triggers/webhooks/

At the bottom of the page it says my artifacts need "type" and "name" KVPs.  For future searchers who might end up on this page, you also need a KVP "reference" that contains the same value as "name".

Thanks for the prompt help!

**Comment by ezimanyi** [comment]
Yes, you're right, added a PR to fix the docs.
