### ISSUE TITLE
templateVariables is invisiable in Github artifacts

### ISSUE THREAD

**Issue by shuai-gao-awx** [spinnaker/spinnaker#4453]
### Issue Summary:

"trigger" and "execution" object can be used in Github artifacts evaluation, but "templateVariables" is invisiable.

is it possible to make "templateVariables" visible in artifacts?

### Cloud Provider(s):

kubernetes V2

### Environment:

`spinnaker version: 1.14.0`

`MPT v2`

`Github Artifact`

### Description:

I defined a variable in my pipeline config:

```json

{
  "application": "pipetest",
  "name": "pipetest",
  "schema": "v2",
  "template": {
    "artifactAccount": "front50ArtifactCredentials",
    "reference": "spinnaker://template-v2-pipetest",
    "type": "front50/pipelineTemplate"
  },
  "variables": {
    "appConfig": {
      "appName": "pipetest"
    }
  }
}

```

Github Manifest:

```yaml

apiVersion: v1
kind: Service
metadata:
  name: "${ templateVariables.appConfig.appName }"
  namespace: "${ parameters['ENV'] }"
spec:
  ports:
    - name: http-main
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "${ templateVariables.appConfig.appName }"
  type: ClusterIP

```

When trigger the pipeline execution, errors occurs： 

```

Exception ( Deploy Manifest )

java.lang.IllegalStateException: Failure evaluating manifest expressions: {templateVariables.appConfig.appName=[Result {description='Failed to evaluate [name] EL1007E: 
Property or field 'appConfig' cannot be found on null', exceptionType=class 
org.springframework.expression.spel.SpelEvaluationException, timestamp=1558859952220, level=ERROR}, 
Result {description='Failed to evaluate [app] EL1007E: 
Property or field 'appConfig' cannot be found on null', exceptionType=class org.springframework.expression.spel.SpelEvaluationException, timestamp=1558859952221, level=ERROR}], 
templateVariables.appConfig.mainPort=[Result {description='Failed to evaluate [targetPort] EL1007E: Property or field 'appConfig' cannot be found on null', exceptionType=class org.springframework.expression.spel.SpelEvaluationException, timestamp=1558859952221, level=ERROR}]}

```

**Comment by neelimamanubolu** [comment]
Hi shuai-gao-awx,
 I have created MPT v2 and executed pipeline in the latest version 1.14.0.

I didnt find any errors. Please find below for refrence:

![Screenshot from 2019-06-12 09-57-45](https://user-images.githubusercontent.com/48236703/59323509-8d2faa00-8cf8-11e9-8189-a5d472f70bcf.png)

The MPT V2 pipeline template as follows :: 
{
 "id": "newSpelTemplate",
 "lastModifiedBy": "anonymous",
 "metadata": {
  "description": "A demonstrative Wait Pipeline.",
  "name": "Variable Wait",
  "owner": "neelima@opsmx.in",
  "scopes": [
   "global"
  ]
 },
 "pipeline": {
  "description": "",
  "keepWaitingPipelines": false,
  "lastModifiedBy": "anonymous",
  "limitConcurrent": true,
  "notifications": [],
  "parameterConfig": [],
  "stages": [
   {
    "name": "My Wait Stage",
    "refId": "wait1",
    "requisiteStageRefIds": [],
    "type": "wait",
    "waitTime": "${ templateVariables.waitTime }"
   }
  ],
  "triggers": [],
  "updateTs": "0"
 },
 "protect": false,
 "schema": "v2",
 "updateTs": "1560241922424",
 "variables": [
  {
   "defaultValue": 42,
   "description": "The time a wait stage shall pauseth",
   "name": "waitTime",
   "type": "int"
  }
 ]
}

Please confirm whether still u r facing the same issue...?

**Comment by neelimamanubolu** [comment]
Hi shuai-gao-awx,
For MPT V2, we cant create pipeline in UI, if we want to create we can do it only by SPIN-CLI.

It is possible to make "templateVariables" visible in artifacts, but we cant use them since we cant create V2 template through UI.

For your reference, please go through below link:
https://blog.spinnaker.io/spinnaker-managed-pipeline-templates-v2-taking-shape-c7503d0a608d

**Comment by shuai-gao-awx** [comment]
Hi, @neelimamanubolu , 

Thanks for your reply. Now, I rolled back to V1 template with V2 provider to avoid this problem. V1 template seems good enough for me :)

**Comment by neelimamanubolu** [comment]
> Hi, @neelimamanubolu ,
> 
> Thanks for your reply. Now, I rolled back to V1 template with V2 provider to avoid this problem. V1 template seems good enough for me :)

Great!.. Then kindly can u pls close the issue.

**Comment by louisjimenez** [comment]
This is correct in that template variables cannot be used by expressions in the manifest. Instead, I recommend continuing to use [parameters](https://www.spinnaker.io/guides/user/kubernetes-v2/parameterize-manifests/). You can still use the template to codify a required parameter that can be inherited by templated pipelines. You can then use that inherited parameter in your manifest. 

In your template you would have something like this:
```json
    "parameterConfig": [
      {
        "default": "${ templateVariables.deployName }",
        "description": "Deployment Name",
        "hasOptions": false,
        "label": "Deployment Name",
        "name": "deploymentName",
        "options": [
          {
            "value": ""
          }
        ],
        "pinned": false,
        "required": true
      }
    ],
  "variables": [
    {
      "description": "deployment name",
      "name": "deployName",
      "type": "string"
    } 
  ]
```
your pipeline config would then need to make sure to inherit and provide any required variables
```json
  ...
  "exclude": [],
  "variables": {
    "deployName": "demo"
  }
  ...
```
and in your manifest, you should then be able to use an expression with the inherited parameter
```yaml
metadata:
  name: '${parameters["deploymentName"]}'
  namespace: default
```

Hope this helps!
