### ISSUE TITLE
Application is not directly accessible after creation

### ISSUE THREAD

**Issue by error418** [spinnaker/spinnaker#4457]
### Issue Summary:

This issue was fixed in `1.13.5` and reappeared with `1.14.1`. For a detailed description see #4307 and #4276

### Cloud Provider(s):
* kubernetes

### Environment:
* Kubernetes distributed deployment
* Minio `RELEASE.2019-03-27T22-35-21Z` as Storage
* GitHub Enterprise for authn/authz
* Spinnaker `1.14.1`

### Feature Area:
* Fiat
* Front50

### Expectation

The application should be immediately available and be accessed after creating it.

### Actual Behaviour

Deck shows a 404 after creating an application. The application is not listed in the application list. After some time (5 to 8 minutes), the application becomes accessible and listed.

### Steps to Reproduce:
1. Create an Application
2. Redirect leads to 404
3. Wait some time (around 5 to 8 minutes)
4. Application appears in the application list and can be used

### Additional Details:

see #4307 and #4276 for details

**Comment by neelimamanubolu** [comment]
HI.. kindly can u provide me the latest code with version 1.14

**Comment by neelimamanubolu** [comment]
![Screenshot from 2019-06-04 18-13-46](https://user-images.githubusercontent.com/48236703/58880221-104b7180-86f5-11e9-8780-da900fdb3440.png)
![Screenshot from 2019-06-04 18-13-46](https://user-images.githubusercontent.com/48236703/58880225-15102580-86f5-11e9-8ed7-deab3fa6cb2e.png)
Please find the above for reference

**Comment by neelimamanubolu** [comment]
Please find below for reference ::  

![Screenshot from 2019-06-04 18-20-38](https://user-images.githubusercontent.com/48236703/58880482-99fb3f00-86f5-11e9-982f-e5dc68da2e22.png)
![Screenshot from 2019-06-04 18-21-20](https://user-images.githubusercontent.com/48236703/58880485-9c5d9900-86f5-11e9-8aa2-2f8fa458583b.png)

**Comment by error418** [comment]
This seems to be fixed with Fiat 1.5.1 in Spinnaker 1.14.3 according to the changelog. I will verify this as soon as possible and reopen the issue if necessary. Thanks!

Reference spinnaker/fiat#413

**Comment by lambertpan** [comment]
I upgraded to 1.14.4, but the issue still appears. Please reopen.

<img width="473" alt="Screen Shot 2019-06-11 at 11 49 18 AM" src="https://user-images.githubusercontent.com/10847950/59248122-226e6800-8c3f-11e9-9265-45d165c77a4f.png">

**Comment by error418** [comment]
`1.14.3` as well as `1.14.4` are not affected by this issue with my setup. I will not reopen this issue since the configuration details I provided in this issue seem not to match your configuration.

**Comment by crosswind27** [comment]
We have been facing this issue. It was present in 1.14.3, 1.14.4. Today I upgraded to 1.14.5, and the issue is still present.

**Comment by error418** [comment]
I think my point did come across the wrong way - you can open a new issue filled with details about your Spinnaker setup to pin down your issue or post your installation details here (as you would when creating a new issue)

As I mentioned: I did not run into this issue using the setup I am running. Does your setup differ from the one I described in this issue?

**Comment by clanesf** [comment]
You can fix this by adding the following feature flag to fiat-local.yaml
`fiat.allowAccessToUnknownApplications: true`
