### ISSUE TITLE
Pipeline templates get created 3 times

### ISSUE THREAD

**Issue by estebangarcia** [spinnaker/spinnaker#4462]
### Issue Summary:
When creating a Pipeline template either with Deck or Spin-CLI the template gets created 3 times instead of 1.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Version 1.14.0
Distributed deployment running on Kubernetes with LDAP authn and authz and S3 as persistent store

Components:
- clouddriver
- deck
- echo
- fiat
- front50
- gate
- igor
- orca
- rosco

### Steps to Reproduce:
1. Create a template using Spin-CLI or Deck
2. List templates
3. It should show it 3 times

### Additional Details:
Image of the issue:
![image](https://user-images.githubusercontent.com/16657038/58544283-d9f38b00-81f8-11e9-8e36-55d827843d27.png)

A few more things I'm seeing:
- This could be happening because in the S3 bucket I can see 3 folders with the pipeline-template id:
```
PRE canarytemplate/
PRE canarytemplate:latest/
PRE canarytemplate@sha256:9fbf2dbd65a843058ba34c0ff8e1229319de810b6f897afe8e765ff19d18648e/
```
- The 3 templates are created with the same id
- Can only delete 2 out of these 3 created templates. When trying to delete the last template (the one that appears in S3 with the ":latest") the API call seems to be successful but it doesn't get removed from the S3 bucket.
I'm attaching the JSON response and orca's logs 
[orca.log](https://github.com/spinnaker/spinnaker/files/3232337/orca.log)
[json_response.log](https://github.com/spinnaker/spinnaker/files/3232342/json_response.log)

**Comment by error418** [comment]
I am also running into this issue with following setup:
* Kubernetes V2 Provider
* Minio as Object Storage
* Spinnaker `1.14.1` (distributed deployment, unmodified containers)

**Comment by rverma-nikiai** [comment]
Same here, though I can understand that there is a purpose, e.g as one is an actual template, one is with tag latest, and one with tag digest. I believe we do require at least two versions but we can definitely improve the experience in the deck and front50 persistence logic.

**Comment by louisjimenez** [comment]
Thanks for reporting this. As of this change https://github.com/spinnaker/spinnaker/issues/4561, only the latest version is now listed. However, pipelines can still be made to reference a different version of the template by editing the JSON in the pipeline config screen. For example, if you wanted to reference a version tagged "stable" you can enter `spinnaker://my-template-id:stable` or if you wanted to reference a template by sha you can do something like `spinnaker://my-template-id@sha256:66fe7...`

There is now also this issue, https://github.com/spinnaker/spinnaker/issues/4563, to create a better versioning UI for templates and updates will be shared there. Thanks!
