### ISSUE TITLE
Server group "Scaling Policies" graph missing due to script error

### ISSUE THREAD

**Issue by danopia** [spinnaker/spinnaker#4468]
### Issue Summary:
ASG Average CPU, as seen under Scaling Policies, is missing/not visible

### Cloud Provider(s):
AWS (Kubernetes is also configured)

### Environment:
Spinnaker 1.14.2 deployed using Halyard to a Kubernetes account. Issue first discovered on 1.14.1 - possibly from 1.14 upgrade. Using Autoscaling groups with "target tracking scaling" rules.

### Feature Area:
Deck / UI

### Description:
The server group CPU graph crashes out and doesn't show up. The popup appears with no content. Issue has been reproduced on multiple devices.

![Screen Shot 2019-05-30 at 11 58 43 AM](https://user-images.githubusercontent.com/40628/58659566-206be700-82d8-11e9-871f-6ec8d0cfffd5.png)

### Steps to Reproduce:
1. Locate or create an EC2 server group.
1. Create a "target tracking scaling" autoscaling rule.
1. Open the Server Group rightmost panel for the ASG.
1. Hover over the rule in the "Scaling Policies section"
1. Examine the popup that appears - there _should_ be a line graph in it.

### Additional Details:
This message shows up in the browser console each time the scaling policy is hovered:

```
vendor_A_F~app.js:1 ReferenceError: d3 is not defined
    at EventManager.init (vendor_G_O~app.js:1)
    at Object.link (vendor_G_O~app.js:1)
    at vendor_A_F~app.js:1
    at vendor_A_F~app.js:1
    at invokeLinkFn (vendor_A_F~app.js:1)
    at nodeLinkFn (vendor_A_F~app.js:1)
    at vendor_A_F~app.js:1
    at nodeLinkFn (vendor_A_F~app.js:1)
    at vendor_A_F~app.js:1
    at vendor_A_F~app.js:1 "<div ng-class="$ctrl.chartData.noData ? 'no-data' : ''" data="$ctrl.chartData" options="$ctrl.chartOptions" class="ng-isolate-scope">"
```

**Comment by danopia** [comment]
Actually, I found a relevant fix: https://github.com/spinnaker/deck/pull/6989 Hoping we see it in 1.14

**Comment by maggieneterval** [comment]
Patching the fix into 1.14!
https://github.com/spinnaker/deck/pull/7072

**Comment by danopia** [comment]
I've upgraded to 1.14.3 and can confirm that the graphs have returned. Hurrah!

**Comment by maggieneterval** [comment]
Hooray for the return of the graphs!
