### ISSUE TITLE
ECS: Does not support non-load-balanced services in EC2 mode

### ISSUE THREAD

**Issue by justinrlee** [spinnaker/spinnaker#4475]
### Issue Summary:
When trying to launch a non-load-balanced service in ECS on EC2, I keep getting this error:

```
Exception ( Monitor Deploy )

IAM roles are only valid for services configured to use load balancers. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 05b6d6ad-861e-11e9-bf68-35e6fd5fa62b)
```

### Cloud Provider(s):
ECS (EC2)

### Environment:
Spinnaker 1.14.2, on EKS, deploying to EC2 and ECS

### Description:
I'm trying to launch a non-load-balanced service in ECS, which I think is a new feature in 1.14.x.  In Fargate, you can use `awsvpc` mode, but in EC2, I'm trying to set this up with either `host` or `bridge` or `none` mode (preferably, `bridge`).

Sample stage definition here: https://gist.github.com/justinrlee/e6b24fc9622218d782942482163cb716

### Steps to Reproduce:

Create an ECS stage in EC2 mode, with "Network Mode" set to `bridge`, and no target group or target container port set.

### Additional Details:

CC @clareliguori

**Comment by clareliguori** [comment]
@spinnakerbot add-label provider/ecs
