### ISSUE TITLE
gate container creating defunct ssl_client processes

### ISSUE THREAD

**Issue by rakewill** [spinnaker/spinnaker#4479]
### Issue Summary:
The readiness probe used for the gate container results in defunct ssl_client processes.

### Environment:
Spinnaker deployment with TLS termination for spin-gate.

### Description:
The readiness check for the _gate_ pod uses the _wget_ command. If gate is deployed with TLS termination, the URL for the readiness uses the https scheme. To handle https URLs, the _wget_ command on the busybox Docker image spawns the external _ssl_client_ command. The _wget_ process then exits/crashes without reaping the _ssl_client_ process resulting in the _ssl_client_ process becoming defunct and owned by the JVM process (process 1 in the container). Each defunct processes uses a file descriptor. Since the readiness probe runs every 10 seconds, a new defunct _ssl_client_ process is created and another file descriptor is used every 10 seconds. Eventually, the node runs out of file descriptors and becomes unstable.

### Steps to Reproduce:
A defunct _ssl_client_ process is left behind after execution of the readiness check so the only thing that must be done to reproduce this issue is to do a deployment of Spinnaker where TLS termination is configured for spin-gate. Defunct _ssl_client_ processes slowly accumulate without having to take any specific action.

To manually reproduce the issue, run the following command in the _gate_ container. 

wget --no-check-certificate --spider -q https://localhost:8084/health

### Additional Details:
It is unclear why the readiness check uses the external _wget_ command to do an HTTP GET when there is HTTP GET functionality built in to Kubernetes. Although the bug with the _wget_ command lies with the busybox image and not with Spinnaker itself, we believe the best way to resolve this is to use the built-in Kubernetes HTTP GET readiness check functionality. This approach avoids executing the external wget command thereby effectively avoiding the issue. We have configured the built-in HTTP GET functionality for our deployments and verified that this resolves the issue. We plan to submit a pull request with a change that would make the readiness check use the built-in HTTP GET functionality.

>         readinessProbe:
>           failureThreshold: 3
>           httpGet:
>             path: /health
>             port: 8084
>             scheme: HTTPS
>           periodSeconds: 10
>           successThreshold: 1
>           timeoutSeconds: 1

This issue appears to be the same issue reported in https://github.com/spinnaker/spinnaker/issues/3944.
---

**Comment by maggieneterval** [comment]
> We plan to submit a pull request with a change that would make the readiness check use the built-in HTTP GET functionality.

Thank you so much, that would be great!

**Comment by rakewill** [comment]
I have created pull request #1343 for this issue. The CI is currently failing due to other changes. Can you please take a look.

**Comment by maggieneterval** [comment]
Hey @rakewill, looks like the PR you linked to has already been merged, did you mean to link to another one? Thanks!

**Comment by rakewill** [comment]
Hi @maggieneterval, the pull request is https://github.com/spinnaker/halyard/pull/1344. The request has been merged.
