### ISSUE TITLE
GCB with GCS artifact gives - "Missing bound artifact for ID@

### ISSUE THREAD

**Issue by skalle** [spinnaker/spinnaker#4503]
### Issue Summary:
When using GCB to produce a GCS artifact I keep getting an error in the Appengine Deploy stage - Missing bound artifact for ID@

### Cloud Provider(s):
Google

### Environment:

Spinnaker 1.14.3 running in GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Spinnaker GCB + Appengine

### Steps to Reproduce:
- Create Appengine application. 
- Have GCB create a tar image in GCS
- Add an Appengine Deploy step to deploy the  artifact. 
=> Missing bound artifact for ID@

### Additional Details:

=== Error from execution.
        "configFiles": [],
        "exception": {
          "details": {
            "error": "Unexpected Task Failure",
            "errors": [
              "Missing bound artifact for ID 25f79cda-1ea4-42ec-b649-e54950349da5"
            ],
            "stackTrace": "java.lang.RuntimeException: Missing bound artifact for ID 25f79cda-1ea4-42ec-b649-e54950349da5\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)\n\tat org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)\n\tat org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator.appendArtifactData(AppEngineServerGroupCreator.groovy:71)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator$appendArtifactData.callCurrent(Unknown Source)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator.getOperations(AppEngineServerGroupCreator.groovy:51)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.ServerGroupCreator$getOperations.call(Unknown Source)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.CreateServerGroupTask.execute(CreateServerGroupTask.groovy:52)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:113)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:330)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:112)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:125)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:50)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:111)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:195)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:188)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
          },
          "exceptionType": "RuntimeException",
          "operation": "createServerGroup",
          "shouldRetry": false,
          "timestamp": 1559954356469
        },

==== Artifacts reported by the GCB stage

     "endTime": 1559954356339,
      "id": "01DCT81WQPP567ST2J84APX8M8",
      "name": "Google Cloud Build",
      "outputs": {
        "artifacts": [
          {
            "customKind": false,
            "name": "gcr.io/xxx/luci-config",
            "reference": "gcr.io/xxx/luci-config@sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70",
            "type": "docker/image",
            "version": "sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70"
          },
          {
            "customKind": false,
            "name": "gcr.io/xxx/luci-config",
            "reference": "gcr.io/xxx/luci-config@sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70",
            "type": "docker/image",
            "version": "sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70"
          },
          {
            "customKind": false,
            "name": "gcr.io/xxx/luci-config",
            "reference": "gcr.io/xxx/luci-config@sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70",
            "type": "docker/image",
            "version": "sha256:1354674a023637dc3bf8b9b6f779cae01f40bccb48baa65ec72d2d15ea849e70"
          },
          {
            "customKind": false,
            "name": "gs://xxx/luci-config/luci_gcb.tar",
            "reference": "gs://xxx/luci-config/luci_gcb.tar#1559954348089180",
            "type": "gcs/object",
            "version": "1559954348089180"
          }
        ]
      },

---

**Comment by skalle** [comment]
Tried a bunch of different GCS Artifact object paths , from exact naming , '.*' to skipping it all together.. None of which seem to make a difference.

**Comment by skalle** [comment]
Yet another piece of info 

Currently work around this with having a GCS trigger for the artifact produced by the GCB stage.. This works fine with the same GCS Object filter not working for the GCB stage.

**Comment by ezimanyi** [comment]
@skalle : Thanks for reporting this issue!  The above-linked PR will fix it, and we'll pull the fix into an upcoming 1.14 patch release.  Thanks!

**Comment by skalle** [comment]
Nice thx! .
