### ISSUE TITLE
[GCE] Image dropdown hangs with large number of images

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4510]
### Issue Summary:
When attempting to add a persistent disk inside of Deck, the image dropdown freeze your browser when attempting to load a long list. Once it does load it is impossible to navigate through the list.

### Cloud Provider(s):
Google/GCE

### Environment:
Spinnaker 1.13.4 & 1.14.3

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
When attempting to add more persistent disks in the deploy stage of a Spinnaker pipeline, the UI freezes and is unusable when there are a large amount of images.

The UI is stuck on this:
![Screen Shot 2019-06-10 at 1 33 18 PM](https://user-images.githubusercontent.com/10604059/59217776-533d9700-8b84-11e9-90e0-3a912e612d8c.png)

Eventually it loads:
![Screen Shot 2019-06-10 at 1 33 40 PM](https://user-images.githubusercontent.com/10604059/59217829-71a39280-8b84-11e9-9b4a-453f43d5ebce.png)

But all actions take about 10s to be registered each time (including scrolling or searching).

Currently this Spinnaker is wired up against 3 projects with a total of `24559` images. 

### Steps to Reproduce:
1. Have a large amount of images in a GCE set of projects
2. Connect these accounts to spinnaker
3. Create a new pipeline with a deploy stage
4. Try to add a new Persistent Disk in the deploy stage

### Additional Details:
The actual call in the browser is a bit long as well, might be related:
`https://spinnaker-gate/images/find?provider=gce&q=*`:
- 15.7 MB
- 11.20s

Yes, we plan on cleaning up more images, but there isn't a quick and easy way to "only remove old images that are not in use by current instance groups".

**Comment by maggieneterval** [comment]
Made Deck and Clouddriver performance enhancements to address this issue (linked above!).

**Comment by maggieneterval** [comment]
These fixes will go out with 1.15.0, would be grateful for any feedback!

**Comment by maggieneterval** [comment]
Hey @seanpeters86, just wanted to check in and see if these changes addressed the problems you were experiencing (and hopefully did not introduce any more!). :smile:

**Comment by seanpeters86** [comment]
This is perfect!!! 

Just got around to upgrading our dev spinnaker to 1.15 and the experience is much better here. Thanks for this!

**Comment by maggieneterval** [comment]
Yay so happy to hear that @seanpeters86. Thanks again for your help!
