### ISSUE TITLE
Clouddriver fails to start with 1.14.x release

### ISSUE THREAD

**Issue by diasjorge** [spinnaker/spinnaker#4514]
### Issue Summary:

Can't upgrade to spinnaker 1.14.X from 1.13.X.

### Cloud Provider(s):

GKE

### Environment:

version: 1.13.8
timestamp: '2019-05-22 09:03:29'
services:
  echo:
    version: 2.4.3-20190522050309
    commit: 9ea33ebbf2075d31ecb8bc071313bf1be9584f27
  clouddriver:
    version: 4.4.6-20190515050309
    commit: a7ce3a53d13906ea8733df337904fddc48e7669e
  deck:
    version: 2.8.7-20190518050309
    commit: 6a9b0a21bb7606f646fa8b908029e1d83e9d6ddd
  fiat:
    version: 1.4.1-20190418153116
    commit: 13f855f166350e78222c7a54d17af4f006eb16ac
  front50:
    version: 0.16.2-20190406050308
    commit: b796e8041055fc1e27074a236003261148f44801
  gate:
    version: 1.7.2-20190418153116
    commit: 28beaaa288464b5a079da0f9f2d5d50f32d4c7a7
  igor:
    version: 1.2.1-20190404161844
    commit: 98de62d636b520ba82dfc589830aa4cdc7451596
  kayenta:
    version: 0.7.1-20190425050308
    commit: f95afd1661cf9ccc85d8f0d444c9ac9d9a136aa5
  orca:
    version: 2.6.3-20190430050308
    commit: 92bc10dc45f76c8ad87564e338811c2ec464ab56
  rosco:
    version: 0.11.0-20190322234525
    commit: 95a2e29f53def2fce614412d0d9b27f273fc62d7
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
  monitoring-daemon:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Clouddriver

### Description:

Cloud driver fails to start with 1.14.x and current configuration. It raises an exception quite deep.

All other components boot correctly.

### Steps to Reproduce:

Not sure.

### Additional Details:

This are just the last lines of the stack, you can see the full log here: https://gist.github.com/diasjorge/f6a2ea8bfc37871fc9199ab71f888736

Not pasting here since it's quite long.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.clouddriver.aws.provider.config.AwsProviderConfig$AwsProviderSynchronizer]: Factory method 'synchronizeAwsProvider' threw exception; nested exception is java.lang.NullPointerException: Cannot get property 'name' on null object
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 104 common frames omitted
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-2.5.6.jar:2.5.6]
```

**Comment by darshannagaraja** [comment]
@diasjorge Please share the Halyard version that you are using while you faced this issue.

**Comment by diasjorge** [comment]
1.20.2-20190520111848

**Comment by darshannagaraja** [comment]
@diasjorge I tried on an similar environment with Ubuntu 16.04.6 LTS. Upgraded Spinnaker from 1.13.8 to 1.14.5. I could see that the upgrade was smooth. All services were up. I confirmed that it's working by checking through Spinnaker UI. 

Kindly share the hal config that you are using(a stripped down copy would do). 

I'll take a look into it and investigate it further.

**Comment by diasjorge** [comment]
Thanks @darshannagaraja. Here's a copy of the halconfig: https://gist.github.com/diasjorge/a896b8ce8ce94e8410b2bc160d973b4e

From the logs error message it makes me think it can be something that changed in the schema between the versions.

**Comment by darshannagaraja** [comment]
@diasjorge I checked the hal config shared by you and it seems good. While I investigate this further, please try running by disabling AWS and GCP. 
Kindly share your observations.
I ran with only k8s and was successful. Next I enabled GCP with k8s and reran; all seemed good. 
As reported last by me, I tried the upgrade from 1.13.8 to 1.14.5 and have a smooth transition with the same hal version as being used by you.

**Comment by diasjorge** [comment]
I tried again Today updating to 1.14.6 and I got a better error message.

So I found the error is actually triggered here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ReservationReportCachingAgent.groovy#L117

It tries to fetch the `region[0]` but in my configuration I have an empty [] for the account regions.

I only have defined defaultRegions for AWS. This was working fine with the 1.13.9 version so it must be some change introduced in the new 1.14.x branch.

As a workaround I've explicitly set the regions on each of the AWS accounts and it boots.

**Comment by diasjorge** [comment]
After the upgrade I noticed that for google cloud I also had the same case, the accounts config without regions and the defaultRegions set and after the upgrade the regions list appears empty for my google accounts.

I also had to explicitly set the regions for each google cloud account, which I didn't have to do for 1.13 branch

**Comment by darshannagaraja** [comment]
@diasjorge Thanks for the update! I believe this may need an update to the relevant documentation to make the needed changes to the hal config during an upgrade(in case that's not already available).

**Comment by darshannagaraja** [comment]
Raised the issue https://github.com/spinnaker/spinnaker.github.io/issues/1406 for documentation update

**Comment by diasjorge** [comment]
defaultRegions no longer works in 1.14.x for any provider. If that is desired a documentation update should be sufficient.
