### ISSUE TITLE
Deleting a canary manifest after canary analysis is unreliable

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4521]
### Issue Summary:

I'm running a simple example of canarying, [see repo](https://github.com/milesmatthias/rails-prometheus-canary), where a canary & baseline are deployed, a canary analysis is done, and then the baseline & canary manifests are deleted. Sometimes the delete canary manifest stage is successful, but the deployment + service hang around on the cluster. Baseline is always deleted. Here's what I've noticed:

Parallel deletes (baseline + canary) — only baseline is deleted
Sequential delete, baseline delete then canary — baseline + canary are deleted
Sequential delete, canary delete then baseline — only baseline is deleted

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.14.14
Kubernetes V2 Provider

### Feature Area:

Kubernetes V2 provider

**Comment by maggieneterval** [comment]
Thanks for the comprehensive bug report, Miles -- will investigate next week.

**Comment by sudhakaropsmx** [comment]
Hey, @milesmatthias  Started working in this.

**Comment by maggieneterval** [comment]
Oh, thanks so much for taking a look, @sudhakaropsmx -- I've removed myself as the assignee!

**Comment by milesmatthias** [comment]
Facepalm -- I just gave a demo on canarying and noticed my post-canary analysis deployment (promoting passed canary to live) was deploying the canary manifest. That's why this is happening. My fault.

Potentially a good idea for a safeguard or UI improvement here.

**Comment by maggieneterval** [comment]
> Potentially a good idea for a safeguard or UI improvement here.

Definitely! The canary configuration process leaves much to be desired, so any feedback you have is very, very welcome! Glad this issue is resolved, though :smiley:
