### ISSUE TITLE
Red/Black Deployment (k8 v2) is unreliable in disable manifest stages

### ISSUE THREAD

**Issue by kksharma1618** [spinnaker/spinnaker#4523]
### Issue Summary:
When doing a red/block deployment in k8 v2 provider. The disable manifest stages have issues.

### Cloud Provider(s):
Kubernets v2

### Environment:
Spinnaker running in eks (via hal)

### Description:
There are basically 2 issues with disabling manifest stages.
1) It tries to (and actually waits on it) disable already disabled manifest. We keep around 10 versions. 1 recent active, 9 disabled. The disable manifest stages works for all existing replica sets even when they are already disabled.
2) It tries to disable (and gets stuck) replica sets which have been deleted (even when replica sets were deleted before pipeline started). And because it waits for those non existing replica sets to be disabled, the whole pipeline gets stuck.

### Additional Details:

---

**Comment by maggieneterval** [comment]
Hi @kksharma1618, thanks so much for opening this issue! May I ask 1) what version of Spinnaker you are using and 2) whether you have `liveManifestCalls` enabled?

**Comment by kksharma1618** [comment]
Hey @maggieneterval,
Spinnaker version is "1.14.0". liveManifestCalls is not set. I just saw that config. Looks like this could help.
Will enable and retest if this works.
Thank you :)

**Comment by kksharma1618** [comment]
@maggieneterval 
This looks like such a useful option. I am curious why its not enabled by default? There is not much documentation about it either. Any downsides to it we should watch out for?

**Comment by maggieneterval** [comment]
Hey @kksharma1618, hope you had a great weekend!

I would actually recommend upgrading to the latest stable version, 1.14.5, since we made some fixes around the cache not properly being updated when using the new rollout strategies with the `max-version-history` annotation. We have not yet worked out all the kinks when using `liveManifestCalls` with these new strategies; see discussion on this [issue](https://github.com/spinnaker/spinnaker/issues/4422).

**Comment by kksharma1618** [comment]
Thanks @maggieneterval. My weekend was great. Hope you had fun too.

After upgrading to 1.14.6 our previous issues seem to be solved. Thank you :)
