### ISSUE TITLE
GCB produced artifact gets stuck at GAE deploy stage.

### ISSUE THREAD

**Issue by skalle** [spinnaker/spinnaker#4530]
### Issue Summary:
When getting an artifact from the GCB stage the GAE Deploy stage gets stuck at 'Wait For Up Instances'

### Cloud Provider(s):

Google with GCB and GAE.

### Environment:

Spinnaker 1.14.5 running on GKE.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

GCB and GAE

### Description:

Getting one step further after the fix of #4503. Now the Deploy stage binds the artifact but the deployment fails.

Looking at the clouddriver node '/var/tmp/clouddriver' folder, no untar folder seem to be created. Also no new cluster version ends up in Appengine.

### Steps to Reproduce:

- Create pipline using GCB to build an Appengine tar artifact.
- Create Deploy Step using the artifact. 
- Deploy stage gets stuck forever at 'Wait For Up Instances'
  - The version being deployed does not show up in the Appengine versions page.
  - The clouddriver temporary untarred folder is not created in '/var/tmp/clouddriver' folder during deployment.

### Additional Details:

As in #4503 building the artifact using the GCB stage and having another pipeline trigger on GCS Pub/Sub deploys fine. 

Is it possible the bla.tar#version confuses the Deploy logic to not un-tar the folder?

== part of the run output.

 "stages": [
    {
      "context": {
        "account": "luci-config-staging",
        "application": "luciconfig",
        "cloudProvider": "appengine",
        "configArtifacts": [],
        "configFilepaths": [
          "app-spin.yaml"
        ],
        "configFiles": [],
        "deploy.account.name": "luci-config-staging",
        "deploy.server.groups": {
          "us-central": [
            "luciconfig-staging-v000"
          ]
        },
        "exception": {
          "details": {
            "error": "Unexpected Task Failure",
            "errors": [
              "Stage Deploy in us-central timed out after 20 minutes 8 seconds"
            ],
            "stackTrace": "com.netflix.spinnaker.orca.exceptions.TimeoutException: Stage Deploy in us-central timed out after 20 minutes 8 seconds\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$checkForStageTimeout$1.accept(RunTaskHandler.kt:257)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$checkForStageTimeout$1.accept(RunTaskHandler.kt:69)\n\tat java.util.Optional.ifPresent(Optional.java:159)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForStageTimeout(RunTaskHandler.kt:249)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForTimeout(RunTaskHandler.kt:217)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$checkForTimeout(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:102)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:195)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:188)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
          },
          "exceptionType": "TimeoutException",
          "operation": "waitForUpInstances",
          "shouldRetry": false,
          "timestamp": 1560484268323
        },
        "expectedArtifactId": "1da5dcb3-2b03-4f1b-bea1-b2b04c445077",
        "force.cache.refresh.errors": [],
        "freeFormDetails": "",
        "fromArtifact": true,
        "gitCredentialType": "NONE",
        "interestingHealthProviderNames": [
          "App Engine Service"
        ],
        "kato.last.task.id": {
          "id": "81cd4621-50ae-4c02-ab88-ca5eb74dbe35"
        },
        "kato.result.expected": false,
        "kato.task.firstNotFoundRetry": -1,
        "kato.task.notFoundRetryCount": 0,
        "kato.tasks": [
          {
            "history": [
              {
                "phase": "ORCHESTRATION",
                "status": "Initializing Orchestration Task..."
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Processing op: DeployAppengineAtomicOperation"
              },
              {
                "phase": "DEPLOY",
                "status": "Initializing creation of version..."
              },
              {
                "phase": "DEPLOY",
                "status": "Grabbing repository gs://xxx/luci-config/8b0bc704-769a-4532-a72c-75abeb09a8aa.tar#1560483050722856 into local directory..."
              },
              {
                "phase": "DEPLOY",
                "status": "Fetching updates from gs://xxx/luci-config/8b0bc704-769a-4532-a72c-75abeb09a8aa.tar#1560483050722856 for (current)..."
              },
              {
                "phase": "DEPLOY",
                "status": "Querying all versions for project luci-config-staging..."
              },
              {
                "phase": "DEPLOY",
                "status": "Querying services for project luci-config-staging..."
              },
              {
                "phase": "DEPLOY",
                "status": "Deploying version luciconfig-staging-v000..."
              },
              {
                "phase": "DEPLOY",
                "status": "Done deploying version luciconfig-staging-v000..."
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Orchestration completed."
              }
            ],
            "id": "81cd4621-50ae-4c02-ab88-ca5eb74dbe35",
            "resultObjects": [
              {
                "createdArtifacts": [],
                "deployedNames": [],
                "deployedNamesByLocation": {},
                "deployments": [],
                "messages": [],
                "serverGroupNameByRegion": {
                  "us-central": "luciconfig-staging-v000"
                },
                "serverGroupNames": [
                  "us-central:luciconfig-staging-v000"
                ]
              }
            ],
            "status": {
              "completed": true,
              "failed": false
            }
          }

**Comment by ezimanyi** [comment]
@skalle : It was indeed that the version appended to the end of the GCS path was confusing the appengine provider; it did not have any logic to parse out the version number and assumed `app.tar#123` was the application name.

The GCB artifacts include a version, which I think is better as it avoids race conditions where another build replaces the artifact before it's fetched, this was breaking for GCB artifacts only.  I've updated the appengine code in the above PR to properly handle versions and will pull this into the 1.14 branch as well.

**Comment by jianglai** [comment]
@ezimanyi Thanks for the fix. Will this be included in next week's 1.14 release?

**Comment by ezimanyi** [comment]
@jianglai : Yes, it's already on the 1.14 branch so will be included in the next 1.14 release, which is usually early in the week.

**Comment by skalle** [comment]
Hey ezimanyi@ .. Thx. again for the quick fix , appreciated!
