### ISSUE TITLE
Infrastructure > Cluster view doesnt show created server groups in some applications

### ISSUE THREAD

**Issue by kksharma1618** [spinnaker/spinnaker#4559]
### Issue Summary:
The clusters view shows "NO SERVER GROUPS FOUND IN THIS APPLICATION" in some application even though there are server groups that spinnaker pipeline created. This only happens in some applications, not all.
Server group can be seen from pipeline execution details (clicking on details link).

### Cloud Provider(s):
Kubernetes V2 Manifest

### Environment:
AWS eks via hal

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
UI, I think. @spinnaker/ui-ux-team

### Additional Details:
Screenshots:
1) When it works fine:
![image](https://user-images.githubusercontent.com/2723026/60005811-de428500-968c-11e9-8de3-ee8b754cd19a.png)
2) When it doesnt work.
![image](https://user-images.githubusercontent.com/2723026/60005896-03cf8e80-968d-11e9-90da-d30ab347adee.png)
3) Though we can access server group from pipeline execution view by clicking on details.
Note that the main view for server group is still empty
![image](https://user-images.githubusercontent.com/2723026/60005936-1ba71280-968d-11e9-8cd9-81cf3fb4460d.png)

Spinnaker has properly applied monikers to launched replicaset in both cases (where it works and where it doesnt):
moniker.spinnaker.io/application: node-sample-3-beta
moniker.spinnaker.io/cluster: replicaSet node-sample-3-beta

**Comment by kksharma1618** [comment]
More info:
These apis:
/applications/node-sample-4-beta-us-east-1/clusters
/applications/node-sample-3-beta/serverGroups
return proper data for applications where replicasets are shown. for other applications its empty response.

Eg:
/applications/node-sample-4-beta-us-east-1/clusters
{}

/applications/node-sample-3-beta/clusters
{"beta-apps-eks":["replicaSet node-sample-3-beta"]}

**Comment by ezimanyi** [comment]
This generally happens when you create applications/clusters that contain a hyphen which confuse the typical `app-stack-detail` naming convention.  Is this only happening in cases where the application name or the cluster name contains a hyphen?

**Comment by kksharma1618** [comment]
I dont think it was related to hyphens. All our applications/clusters/pipelines names have hyphens. The issue happened only in 1 app out of around 10 we tried. 
App config also doesnt have account details set for that particular app. Maybe because of that.

![image](https://user-images.githubusercontent.com/2723026/61031364-021bff80-a3dd-11e9-8678-831133044f78.png)


It's working fine for all other apps, even any new apps we are trying. So we are good. Thanks :)

**Comment by sathishavm** [comment]
Yes, We are also facing these issues, We have the application with a hyphen, some other application with a hyphen in the name works well.

**Comment by dhinojosa** [comment]
Yes, I can confirm it is when you have `namespaces` for the `account` in `hal`.  This should re-open and should have a fix that states that "Spinnaker does not have access to a necessary namespace, either remove all namespaces from `hal` or include the `<namespace>`.  It may be that it requires the `default` namespace but I cannot confirm that.

**Comment by romil-punetha** [comment]
Has this been fixed? I'm also facing this issue.

**Comment by dhinojosa** [comment]
@romil-punetha Just make sure you don't have namespaces listed in your `~/.hal/.config` file

**Comment by soorajpv** [comment]
we are also facing the same issues on all cloud environments kubernetes V2 account

**Comment by andridzi** [comment]
Spinnaker 1.19.4 - facing the same issue described here
@dhinojosa I don't have any namespaces listed in my ~/.hal/config but Server Groups and Accounts periodically disappearing from Infrastructure->Clusters  tab
@ezimanyi , I see this issue was assigned to you, but was closed.
Is there any fix?
thanks

**Comment by ezimanyi** [comment]
This was closed by the original reporter as the resolution above addressed their issue; if you're still running into issues, please open a new issue with a detailed description.

**Comment by andridzi** [comment]
ok, thanks for the quick reply

**Comment by vuxuanlai** [comment]
I'm getting on this issue on Spinnaker 1.20.1

**Comment by jonathanheaden** [comment]
We are getting this behaviour for one account only on spinnaker 1.19.8. 
We tried removing the namespaces from the .hal/config file but still do not see any infrastrucure even though there are successfuly deployments. I will raise a new issue for this

**Comment by jonathanheaden** [comment]
looks like I spoke too soon. This issue resolved itself for us after we took the following action:

1. Remove the namespaces specified in the `~/.hal/config` file for the affected account
1. Add back in the namespaces in `~/.hal/config` file for the affected account

... resolved by a case of turning it off and on again :)

**Comment by sramek5** [comment]
Well, same problem here, verion 1.21.0.

We have only omitNamespaces.
I can list other namespaces though, but there is nothing in Infrastructure section.

**Comment by sdpoueme** [comment]
Issue is visible in Spinnaker 1.20.8.

**Comment by fftorres** [comment]
I have the same... And even for some applications, where we have more than 1 account, I see information only for some accounts.

**Comment by sdpoueme** [comment]
> I have the same... And even for some applications, where we have more than 1 account, I see information only for some accounts.

It seems to be a performance issue with clouddriver-caching, we increased the number of replicas and now we are able to load the the page correctly.

**Comment by shivamgupta211** [comment]
For me it's not showing for few deployment only

**Comment by phanikumarp** [comment]
In spinnaker  versio 1.26.6

**Comment by venksel** [comment]
After some digging found it's due to the annotation that gets applied by Spinnaker. Check your Kubernetes objects (Deployments, Services, PODs etc ) for `moniker.spinnaker.io/application=appname` and make sure it's pointing to the right application.  If you are using pipeline templates, check to ensure they are setup correctly as the annotation gets passed via the templates.

**Comment by VayshaYsno** [comment]
@venksel can you explain exactly where u have found it? I'm getting this issue too, my setup is for k8s, with spinnaker-operator. And I didn't find any `moniker.spinnaker.io` parts anywhere...
