### ISSUE TITLE
Bake of HelmBakeManifestRequest error converting YAML to JSON: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by KhadijaAmmar** [spinnaker/spinnaker#4570]
### Issue Summary:
I am trying to bake a mainfest from helm served by chartmuseum but it fails with:

```{"error":"Internal Server Error","errors":["Bake of HelmBakeManifestRequest(namespace=default) failed: Error: failed to parse /tmp/675e2136-370e-429d-a7dd-60e578ac42be/B69F82642EBFD85326CEC3DA582BD40F: error converting YAML to JSON: yaml: control characters are not allowed\n"],"kind":"HTTP","responseBody":"{\"timestamp\":1561647502078,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"java.lang.IllegalStateException\",\"message\":\"Bake of HelmBakeManifestRequest(namespace=default) failed: Error: failed to parse /tmp/675e2136-370e-429d-a7dd-60e578ac42be/B69F82642EBFD85326CEC3DA582BD40F: error converting YAML to JSON: yaml: control characters are not allowed\\n\"}```

However the helm chart is properly gzipped and installed ( manual install from chartmuseum) and it's actually working.

### Cloud Provider(s):
Kubernetes v2

### Environment:
kubernetes

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
rosco

### Description:
```,"rootException":"java.lang.IllegalStateException","status":500,"url":"http://spin-rosco.default:8087/api/v2/manifest/bake/helm"},"exceptionType":"RetrofitError","operation":"createBake","shouldRetry":false,"timestamp":1561647502086},"expectedArtifacts":[{"defaultArtifact":{"customKind":true,"id":"fa358ed4-f69a-463b-a8f9-c60d22d67471"},"displayName":"staging-documentation","id":"ea28e990-1b19-4dcf-846d-c1c51aefcd50","matchArtifact":{"artifactAccount":"helm-algoan","id":"dd9be75e-528f-49cf-8ebf-76b2925a56cc","name":"staging-documentation","reference":"helm-algoan","type":"embedded/base64","version":"0.3.0"},"useDefaultArtifact":false,"usePriorArtifact":false}],"inputArtifacts":[{"account":"helm-algoan","id":"b1f918aa-61db-4e01-b277-9408dd19facc"},{"account":"helm-algoan","id":"b1f918aa-61db-4e01-b277-9408dd19facc"}],"namespace":"default","outputName":"staging-documentation","overrides":{},"templateRenderer":"HELM2"},```

### Steps to Reproduce:
1. Setup a internal artifact helm-repo (Artifactory, Nexus)
2. Add repo to hal config (chartmuseum)
3. Create a pipeline with an expected artifact from helm repo
* Match Against
* Account: ...
* Name: ...
* Version: 0.0.1
[x] Use Default Artifact
* Default Artifact:
* Account: ...
* Name: ...
* Version: 0.0.1
4. Create a bake step using the expected artifact
5. Trigger pipeline manually
### Additional Details:
helm config (hal)
```
  helm:
    enabled: true
    accounts:
    - name: ...
      repository: https:/...../
  ```

Any idea about this issue please?

**Comment by neelimamanubolu** [comment]
Hi, @KhadijaAmmar , I have started working on this... Kindly can u send me the helm chart which u r using for the above issue for reference. Thanks.

**Comment by KhadijaAmmar** [comment]
Hello, I've created a packaged helm template tgz file using helm package (structure is app/Chart.yaml, app/template/, app/values.yaml) and commit to a chartmuseum (with gcs bucket).

Here's my values.yml 
```# Default values for documentation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: "*************"
fullnameOverride: "***********"
cluster: "******"
role: app

replicaCount: 1
image:
  repository: eu.gcr.io/*******/******
  tag: staging
  pullPolicy: Always
services:
  name: ******
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  public:
    port: 8080
  annotations:
    "service.spec.externalTrafficPolicy": "Local"
ingress:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

imagePullSecrets: []

tolerations: []

affinity: {}
```
My helm chart is working as excepted, I've installed it manually from chartmuseum and it's working fine. My issue is in the baking step.

**Comment by neelimamanubolu** [comment]
HI, @KhadijaAmmar , Can u pls let me know which version of spinnaker u r facing the above issue.

**Comment by neelimamanubolu** [comment]
HI, @KhadijaAmmar , Can u pls let me know which version of spinnaker u r facing the above issue. I have done the testing with the latest version of spinnaker 1.15, I made some changes, and able to bake a mainfest from helm.

**Comment by neelimamanubolu** [comment]
Hi, please find the pull request for the above issue, https://github.com/spinnaker/orca/pull/3057

**Comment by KhadijaAmmar** [comment]
Thank you, I am closing this issue
