### ISSUE TITLE
Manual Judgements doesn't timeout at default time (72 hours)

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4592]
### Issue Summary:

Manual judgement stages wait indefinitely, even though the default setting is to fail the stage at 72 hours.

### Cloud Provider(s):

Kubernetes, v2
Live manifest calls enabled

### Environment:

GKE
Halyard 1.21.1
Spinnaker 1.14.8

### Feature Area:

Orca

### Steps to Reproduce:

Create a manual judgement stage, run it without pressing one of the buttons, and wait.

**Comment by maggieneterval** [comment]
Hey @milesmatthias, thanks for reporting! I left a manual judgment stage running, and mine did time out after three days with the following expected exception: `com.netflix.spinnaker.orca.exceptions.TimeoutException: WaitForManualJudgmentTask of stage Manual Judgment timed out after 3 days 0 hours 0 minutes 4 seconds`

![3KScZ6hq23Z](https://user-images.githubusercontent.com/15936279/61221952-a789e880-a6e7-11e9-8263-64accb6ee866.png)

Would you mind sending me your manual judgment stage config JSON? I'm curious if the `stageTimeoutMs` was accidentally set. It is possible to override the default 72-hour timeout here:

![fy8Wq7KPnTE](https://user-images.githubusercontent.com/15936279/61222124-10716080-a6e8-11e9-8d9e-1f6e4301e4ab.png)

**Comment by bnutt** [comment]
Hi @maggieneterval , I have experienced issues with this as well. I have set my timeout to 15minutes and still experience pipelines still being in the manual judgement phase after this amount of time.

<img width="648" alt="Screen Shot 2019-07-15 at 8 20 49 AM" src="https://user-images.githubusercontent.com/6414172/61227709-ac47a000-a6d9-11e9-9e64-f20c20f5b29b.png">

<img width="1150" alt="Screen Shot 2019-07-15 at 8 22 25 AM" src="https://user-images.githubusercontent.com/6414172/61227724-b49fdb00-a6d9-11e9-9b50-3f01efe4956f.png">

**Comment by maggieneterval** [comment]
Hey @bnutt thanks for letting us know! Would you mind sending me your manual judgment stage JSON so I can try to reproduce exactly? Many thanks!

**Comment by bnutt** [comment]
Here is the JSON of the stage~

```
{
  "failPipeline": true,
  "instructions": "Approve to deploy ${execution['application']} to prod k8 cluster?",
  "judgmentInputs": [],
  "name": "Manual Judgment",
  "notifications": [
    {
      "address": "cd-notifications",
      "level": "stage",
      "message": {
        "manualJudgmentContinue": {
          "text": "Deploying ${execution['application']} to prod k8 cluster"
        }
      },
      "type": "slack",
      "when": [
        "manualJudgmentContinue"
      ]
    }
  ],
  "overrideTimeout": true,
  "propagateAuthenticationContext": true,
  "sendNotifications": true,
  "stageEnabled": {
    "expression": false,
    "type": "expression"
  },
  "stageTimeoutMs": "900000",
  "type": "manualJudgment"
}
```

**Comment by milesmatthias** [comment]
@maggieneterval this may be an issue with custom timeouts, because we've seen issues with timeouts ending too early or not ending when it should when a custom timeout has been set.

**Comment by maggieneterval** [comment]
I suspect that the issue is your `stageTimeoutMs` is set as a string (in @bnutt's example, "9000") -- @milesmatthias, curious if your `stageTimeoutMs` is also a string?

**Comment by maggieneterval** [comment]
Yeah, was able to reproduce this problem if `stageTimeoutMs` is set to a string. I think in that case we'll hit this codepath (https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java#L690) and default to the timeout being 72h rather than whatever you set as your default. I'm wondering if you both created this stage from  the UI and somehow it saved your timeout as a string?

**Comment by bnutt** [comment]
It looks like it is defined as a string, I defined it as a string as a pipeline template variable, I will try changing it to an int instead.

**Comment by maggieneterval** [comment]
Cool definitely let me know if it works for you as an int!

Curious where you see it defined as a string for pipeline templates (sorry in advance if that's a dumb question, I don't know anything about pipeline templates!)

**Comment by bnutt** [comment]
Verified it works as an int! It's actually an error on my part, the pipeline template doc clearly specifies it as an int and I used string for some reason..thanks for looking! https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/create/#3-edit-the-file-for-template-format

**Comment by maggieneterval** [comment]
Awesome, glad it is working, @bnutt!

@milesmatthias, let me know if changing string --> int resolves this for you as well!
