### ISSUE TITLE
Run Job stage manifest from artifact

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4605]
### Issue Summary:

The Run Job stage from @ethanfrogers is awesome! Would love to be able to have the manifest that the job runs be an artifact so it can be combined with the baking stage.

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.14.8

### Feature Area:

Spinnaker K8s

### Description:

As an example, if you want to launch n number of jobs to do some work in parallel, so you need to have a bake step that creates n manifests (1 artifact though, manifests separated by a `---`) then you could use this.

**Comment by milesmatthias** [comment]
Related to #4606.

**Comment by ethanfrogers** [comment]
Just merged the work to support this. Will be available in 1.16!
