### ISSUE TITLE
1.15 RC: Fargate-deployments failing (error: The container vXXX does not exist in the task definition)

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#4621]
### Issue Summary:

Note: this affects only Spinnaker-version 1.15 (which is in RC atm).

When trying to deploy Fargate-apps with the new "task definition artifacts"-feature, the deployments fail with an error "The container vXXX does not exist in the task definition)".

If I update both the task definition JSON and the Deploy configuration to reflect the "next deployed version" - following Spinnaker's internal numbering (e.g. v007) - the deployment succeeds.

### Cloud Provider(s):

AWS / ECS / Fargate

### Environment:

Spinnaker 1.15 (Release Candidate, 15.7.2019 19:13 CET) running on GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Clouddriver

### Description:

I'd expect the mapping between the deployment configuration and Fargate task definition to stay static - otherwise we'd need to bump both the pipeline configuration in Spinnaker + the task definition artifact-JSON in GitHub somehow...

### Steps to Reproduce:

1. Installing Spinnaker 1.15 RC + enabling ECS
2. Create a pipeline configuration + a task definition (artifact) to deploy (and pull the task definition from e.g. GitHub) - see example
3. Witness the error message

### Additional Details:

Here are both the task definition and the pipeline configuration from Spinnaker:

https://gist.github.com/iniinikoski/7dc6a61e4a7f6a9f2da8a4d63e82eaa1

**Comment by allisaurus** [comment]
Thanks for reporting @iniinikoski ! I'll take a look and update here with any questions or new info.

**Comment by allisaurus** [comment]
@spinnakerbot add-label provider/ecs

**Comment by allisaurus** [comment]
Hi @iniinikoski - the error indicates that ECS tried to create a load balanced service which would direct traffic to a container named "vXXX", but it couldn't find it in the task definition. This is confusing b/c in both your [fargate_task_definition.json](https://gist.github.com/iniinikoski/7dc6a61e4a7f6a9f2da8a4d63e82eaa1#file-fargate_task_definition-json) and `containerName` mapping in the pipeline, you indicate the container name is "envserver".

However, it doesn't look like your [pipeline configuration](https://gist.github.com/iniinikoski/7dc6a61e4a7f6a9f2da8a4d63e82eaa1#file-spinnaker_pipeline_config-json) includes a parameter for `loadBalancedContainer`, which indicates which container the load balancer should direct traffic to. (Previously, this field wasn't needed b/c there was only ever one container in the task definition, however w/ artifacts there can be multiple, so this field is used to indicate which should be behind the load balancer.) 

When this field is empty, clouddriver [falls back to using the auto-generated container name](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L658), which would result in "vXXX" being passed to ECS. I was able to repro this issue by removing this field in my own pipeline config and trying to deploy.

In the deck UI, you can select which container to load balance on with a drop-down beneath the artifact:

![loadBalancedContainer_ui](https://user-images.githubusercontent.com/34254888/61339674-b5c52b00-a7f3-11e9-8c8d-74ce836aefc9.PNG) 

Can you confirm that this field was missing when you ran into this issue, and if so, add it and attempt to deploy again? Let me know if this fixes it or if you continue to run into problems!

Also: I understand this is NOT a good experience or instructive error message, and we'll be working to add better messaging and validation here so it's more obvious what's actually wrong. Thanks again for reporting this and providing all your configuration info!

**Comment by iniinikoski** [comment]
Hi @allisaurus - good catch! I noticed the existence of the new `loadBalancedContainer`- parameter, but did not notice it was missing... I had some issues with the "Container Mappings"- table (the dropdown never included the envserver image+it's tag - I'll share the screenshot to you directly) - so the mapping broke there... Sorry, didn't catch this myself.

I'll close this one :) Thanks again!

**Comment by allisaurus** [comment]
@iniinikoski  no worries, this was a totally reasonable thing to miss! I've created an issue for us to add better validation so this situation is easier to diagnose in the future: https://github.com/spinnaker/spinnaker/issues/4635
