### ISSUE TITLE
500 when viewing console output of a deleted K8s resource

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4640]
### Issue Summary:

If you use the Deploy Manifest to deploy something (ex: a Job), then delete the job manually on the K8s cluster, when you go back to Spinnaker and click "Console Output (Raw)", you get a message of "Internal server error".

(It's clear to me why, but it may not be to other people, so giving a sane message saying the logs weren't able to be found, possibly because the resource was deleted would be ideal.)

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.14.9

### Feature Area:

Kubernetes v2

**Comment by maggieneterval** [comment]
Good call Miles, thanks for reporting. I added a better error message :+1:
