### ISSUE TITLE
run job (manifest) without producing artifacts

### ISSUE THREAD

**Issue by sparciii** [spinnaker/spinnaker#4642]
### Issue Summary:
`Run Job (Manifest)` fails when `Produces Artifact` section is left unconfigured.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Spinnaker 1.14.8

### Feature Area:
Spinnaker K8s

### Description:
Expected behavior: 

A `Run Job (Manifest)` stage should be able to return successfully (assuming the kubernetes job is successful) even if no `Produces Artifact` is configured.

Actual behavior:

I have a `Run Job (Manifest)` stage configured to run a kubernetes job. The kubernetes job that is triggered is able to complete successfully as is reported via `kubectl describe <job_name>`. However the spinnaker stage reports as failed due to missing properties file. 

```
        "exception": {
          "details": {
            "error": "Unexpected Task Failure",
            "errors": [
              "Expected properties file test but it was either missing, empty or contained invalid syntax"
            ],
```

Don't have an `Produces Artifact` configured for the run job stage as the job doesnt produce anything that is used later in the pipeline.

### Steps to Reproduce:

Configure a `Run Job (Manifest)` stage with a kubernetes job without specifying a expected artifact within the stage.

**Comment by iniinikoski** [comment]
Bumped into this one as well, in Spinnaker version 1.15 RC. Noticed from the stage's JSON version that there's something extra in the pipeline config. Edit it away + retrigger -> perfection.

**Comment by ethanfrogers** [comment]
Thanks for the report @sparciii and @iniinikoski! I know what's causing this so I'll try and get a patch for it today and into 1.15.1.
