### ISSUE TITLE
ECS/Fargate:Stack exception "Cannot cast object 'true' with class 'java.lang.Boolean' to class 'java.lang.Integer'" when "usePreviousCapacityIfAvailable: true" set

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#4646]
### Issue Summary:

When deploying to ECS-Fargate using a working pipeline configuration from Spinnaker version 1.13.11 - in Spinnaker version 1.15.0 - the pipeline execution fails with a beautiful stacktrace (see the bottom). Looks like this is causing it:

```usePreviousCapacityIfAvailable: true```

as commenting this one out from pipeline configuration fixes the deployment.

### Cloud Provider(s):

ECS/Fargate

### Environment:

Distributed Spinnaker, version 1.15.0 (release), running on GKE. Googol-managed Redis- and MySQL.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Pipelines

### Description:

I'd expect the "usePreviousCapacityIfAvailable" flag to work in the latest Spinnaker version with Fargate as well. I hope it is a bug :)

### Steps to Reproduce:

1. have a working Fargate-pipeline with Spinnaker version 1.13.11 - with this boolean set
2. upgrade to Spinnaker version 1.15.0-release
3. redeploy (execute the pipeline) again -> see it fail with the stacktrace
4. remove the "usePreviousCapacityIfAvailable: true" from the pipeline configuration
5. retrigger the pipeline -> everything works fine

### Additional Details:

`stackTrace: "org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'java.lang.Integer' at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToNumber(DefaultTypeTransformation.java:175) at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:282) at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:243) at org.codehaus.groovy.runtime.DefaultGroovyMethods.asType(DefaultGroovyMethods.java:17098) at org.codehaus.groovy.runtime.dgm$54.doMethodInvoke(Unknown Source) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:999) at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:990) at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180) at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:603) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask$_useConfiguredCapacity_closure2.doCall(WaitForUpInstancesTask.groovy:162) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at groovy.lang.Closure.call(Closure.java:405) at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5961) at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3994) at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:4020) at org.codehaus.groovy.runtime.dgm$100.invoke(Unknown Source) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask.useConfiguredCapacity(WaitForUpInstancesTask.groovy:161) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask$useConfiguredCapacity$1.callStatic(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask.calculateTargetDesiredSize(WaitForUpInstancesTask.groovy:121) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask$calculateTargetDesiredSize$0.callStatic(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:224) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask.allInstancesMatch(WaitForUpInstancesTask.groovy:71) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask.allInstancesMatch(WaitForUpInstancesTask.groovy) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask$allInstancesMatch.callStatic(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:232) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask.hasSucceeded(WaitForUpInstancesTask.groovy:178) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190) at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192) at com.netflix.spinnaker.orca.clouddriver.tasks.instance.AbstractInstancesCheckTask.execute(AbstractInstancesCheckTask.groovy:122) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:113) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:330) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:112) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt) at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127) at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:50) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:111) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:195) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:188) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69) at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69) at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69) at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)`

**Comment by allisaurus** [comment]
@spinnakerbot add-label provider/ecs

**Comment by allisaurus** [comment]
Hi @iniinikoski - would you be able to provide use with the (redacted as needed) pipeline config you were using when this happened? Thanks!

**Comment by iniinikoski** [comment]
A solution for this one was to change "usePreviousCapacityIfAvailable" to "useSourceCapacity" instead. We were running the pipelines with "usePreviousCapacityIfAvailable" with Spinnaker version 1.13.X - without issues. Interesting.

Thank you @allisaurus for your support! :)

**Comment by allisaurus** [comment]
Happy to help @iniinikoski !

For additional context: the field `usePreviousCapacityIfAvailable` seems to a hold over from a previous version of `deck`, first reported in https://github.com/spinnaker/spinnaker/issues/3779 and fixed in https://github.com/spinnaker/deck/pull/6251

Also: note the correct field for using previous capacity (`useSourceCapacity`) is a top-level field within a `cluster` (vs. within `capacity`)

**Comment by allisaurus** [comment]
Seems that the reason this was working in 1.13.x but threw and error in 1.15.x is because [this change](https://github.com/spinnaker/orca/pull/2923/files#diff-249f1c3c401e336e2515ac372b121bb4R161) tries to parse all the field values under `capacity` as integers (and chokes on `true`)
