### ISSUE TITLE
X.509 (with SAML enabled) breaks between Spinnaker upgrades (between 1.13.11 to 1.14.X+)

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#4648]
### Issue Summary:

When Spinnaker is upgraded from version 1.13.11 to 1.14.XX or 1.15.0 - X.509 stops working. When using roer, I'm able to see the SAML login page. Same behavior happens with Spin CLI.

### Cloud Provider(s):

-

### Environment:

Distributed Spinnaker version 1.15.0, running on GKE, with Cloud Memorystore and Cloud SQL. Halyard version is 1.20.1.

SAML enabled. SSL is offloaded in Gate and Deck, not in load balancers.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Authentication (SAML / X.509)

### Description:

I'd expect X.509 work on newer (1.14.X, 1.15.X) versions of Spinnaker as with 1.13.11. Or have instructions on what to reconfigure (on Gate, probably?).

### Steps to Reproduce:

1. Working setup: Spinnaker 1.13.11 with SAML and X.509 enabled. X.509 access works with both roer and Spin CLI
2. Upgrade Spinnaker to version 1.14.<latest> or 1.15.0 - and try to "roer -v app list". Witness roer to get a SAML login page.

### Additional Details:

--

**Comment by iniinikoski** [comment]
I'm not sure if this is a duplicate to https://github.com/spinnaker/spinnaker/issues/4472 - but decided to do an own for trackability / clarity.

**Comment by mingatfullcontact** [comment]
This is exactly what we encountered. X.509 breaks on 1.14+ when saml is enabled. All api calls to spin-gate using x.509 cert are redirected to SSO login url

**Comment by iniinikoski** [comment]
Yup... It's a bit nasty :/ I tried to understand the changes to Gate between versions, but for me it's... hopeless :) Hopefully someone can have a look & fix this soonish...

**Comment by iniinikoski** [comment]
These seemed to fix the problem for those who terminate SSL in load balancer(s): https://github.com/spinnaker/gate/commit/97f6477ffac66205d01949a05e8c6efabc65b7ef and https://github.com/spinnaker/gate/commit/193c7b9484d98fb55cf79581b9c1e3959ccb43fe

But - for us - as we don't - the problem persists in 1.15.0...

**Comment by iniinikoski** [comment]
@mingatfullcontact you also don't terminate SSL in load balancers...? Just to confirm...

**Comment by iniinikoski** [comment]
@ncknt I noticed you made the other fixes mentioned above - any vision on is there something similar to fix when running Gate with "defaults" in distributed setup (meaning, SSL not terminated in balancers but in Deck+Gate)...? I've noticed that in Armory setup SSL is terminated in balancers but...

**Comment by ncknt** [comment]
@iniinikoski When X509 is enabled, the default port 8084 also turns into an SSL port. You can check the Gate startup log for that. To use a non SSL (but now still with auth), you need to enable the `default.legacyServerPortAuth: <someport>`.

**Comment by iniinikoski** [comment]
@ncknt thanks. I was just wondering, that something changed between Spinnaker 1.13.x and 1.14.x on this - as when roer or Spin CLI tries to talk to Gate, they get the SAML login page...

I guess I could use `default.legacyServerPort` - with another port than 8084 - and point the LB traffic there, but that does not feel like the best fix here...

**Comment by iniinikoski** [comment]
Small update: I changed our setup to use Kubernetes Ingress + SSL-termination in there vs. Gate+Deck - but the behavior stayed the same. Darn...

**Comment by mingatfullcontact** [comment]
@iniinikoski our spin-gate currently only has https port open. When we first set it up, we tried to open 2 ports: HTTP for traffic from load balancer (human users that use browser + SSO), and HTTPS for traffic with x.509 cert (other ci-cd tools), but it somehow we couldn't get it to work correctly. we tried many combinations of port configuration but none of them worked as expected. 

Anyway, so our spin-gate right now only has HTTPS listener. traffic from browser goes to AWS ALB, ALB terminates SSL there and makes another HTTPS connection to spin-gate. Without x.509 cert, these connections are redirected to our SSO provider, which expected. 

CICD tools send https request with x.509 cert directly to spin-gate (spin-gate and those cicd tools are all in the same namespace, and we use spingate.namespace.svc as endpoint). it works fine with spinnaker 1.13, but started breaking since 1.14 (in spin-gate log, we can see those connections being redirected to SSO provider).

**Comment by iniinikoski** [comment]
Ok thanks @mingatfullcontact - so we are experiencing the same issue here... I tried to understand the latest updates to Gate between version but didn't quite understand what could break this.

**Comment by iniinikoski** [comment]
I fixed the issue by adding "apiPort" in Gate to port 8443 - and just exposing this to the world. X.509 works now again - we are happy. :) To my understanding, this is the recommended way to do this anyway - expose the X.509 port out for everyone to consume. For some reason, the normal port just worked before - and this changed...

**Comment by iniinikoski** [comment]
I'll close the issue - please feel to reopen if needed - but I think this is now the "desired behavior".

**Comment by mingatfullcontact** [comment]
@iniinikoski  thanks i'll try the same. to clarify, right now you only have 1 port, the "apiPort", open on 8443, and it's a https listener, am i correct? no other http or https port open.

**Comment by iniinikoski** [comment]
Yes and no :) Meaning, we have two listeners:

- the "default server" port for normal API traffic (hostname api.companyname.com), HTTPS (443)
- apiPort for X.509 traffic only (hostname api.companyname.com), HTTPS (but port 8443)

So, both https. Meaning, we balance the traffic as is to Gate - and decrypt it there. Looks really like the most working option here...

Hope this helps @mingatfullcontact.

**Comment by mingatfullcontact** [comment]
confirmed. we did the same thing. default server port and api port both https. cicd tools use api port and human web browser goes to the default server port. all working. WOOT! thanks @iniinikoski

**Comment by manu844** [comment]
Trying to enable x509 auth along with OAuth2, followed the [docs](https://www.spinnaker.io/setup/security/authentication/x509/) to enable x509 auth port to something else (8085) other than default port 8084, Tomcat comes up properly with custom port configuration.
`2020-03-03 13:08:31.963  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9001 (https) 8084 (http) 8085 (https)`

But the 8085 port is not exposed in spin-gate pod and spin-gate svc after deploy. Is there anything i'm missing here?

As a workaround edited deployment/spin-gate and svc/spin-gate to open 8085 port.

**Comment by j771** [comment]
Could anyone share what configs they used to get this working?
I have tried to get Spinnaker v1.25 deployed with the spinnaker operator with saml and x509 enabled, I can get the just saml to work on its own but when I updated the configs to add x509 auth as well (on its own port api port) it breaks the saml auth.
