### ISSUE TITLE
Lengthy console logs are cut off in the UI

### ISSUE THREAD

**Issue by jwoodsw** [spinnaker/spinnaker#4649]
### Issue Summary:

Lengthy console logs are cut off in the UI.

### Cloud Provider(s):

Deploying to k8s clusters on AWS EKS.

### Environment:

Spinnaker Release 1.14.3, deploying onto AWS EKS using V2 Run Job.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

UI @spinnaker/ui-ux-team

### Description:

Lengthy console logs from a V2 Run Job result in the log being cut off in the UI. The last displayed line in the output cut in half then nothing but white space for the remainder of the log.

### Steps to Reproduce:

1. Create a V2 run job that will produce a lot of console output (> 507 line).
2. Run the V2 run job.
3. The console log will only partially render and be cut off.

### Additional Details:

In my latest run, the console rendered 507 lines before being cut off.

**Comment by jwoodsw** [comment]
We have several users who have reported this problem. I have encountered this on both `Chrome Version 75.0.3770.142 (Official Build) (64-bit)` and `Firefox 68.0`.

**Comment by froismo** [comment]
Same here using same chrome on OSX.

**Comment by moshjeier** [comment]
Seeing this as well in Chrome on OSX.

**Comment by ethanfrogers** [comment]
@jwoodsw @froismo @moshjeier I plan on taking care of this this week!

**Comment by ethanfrogers** [comment]
@jwoodsw @froismo @moshjeier Pushed a fix, including a screen shot. Now, the modal fits the screen properly and the text scrolls if it overflows the container. LMK what you think!

![](https://cl.ly/9c6d2f557e54/download/Image%202019-07-24%20at%208.43.29%20AM.png)
