### ISSUE TITLE
Spinnaker 1.15 Bake Engine unselectable

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4656]
### Issue Summary:

Upgrading to Spinnaker 1.15 prevents you from selecting "HELM2" as the bake engine in a newly created Bake Manifest stage.

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.15.0

### Feature Area:

@spinnaker/ui-ux-team

### Steps to Reproduce:

1. Create a new Bake Manifest stage
2. Try selecting "HELM2" in the Bake Engine dropdown

You won't be able to.

**Comment by nscmcgrath** [comment]
When will the release with a patch for this be out? Going to downgrade back to 14.11 in the meantime

**Comment by plumpy** [comment]
@nscmcgrath There will be a 1.15.1 on Monday.
