### ISSUE TITLE
NullPointerException in ContainerInformationService.getTaskZone()

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#4657]
### Issue Summary:
NullPointerException occurs in ContainerInformationService.getTaskZone() in several threads.

### Cloud Provider(s):
ECS

### Environment:
Spinnaker version 1.15.0 on a Kubernetes cluster (kubeadm)

### Feature Area:
CloudDriver ECS

### Description:
NullPointerException occurs in ContainerInformationService.getTaskZone() in several threads. The issue is intermittent (meaning that my pipelines work and finish normally most of the time) but is severe enough to prevent reliable functioning of Spinnaker pipelines. I can run my pipelines 5 times in a row, only to fail during 6th run in a presentation related to adoption of Spinnaker. 

java.lang.NullPointerException: null
	at com.netflix.spinnaker.clouddriver.ecs.services.ContainerInformationService.getTaskZone(ContainerInformationService.java:177) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.clouddriver.ecs.provider.view.EcsServerClusterProvider.convertToEcsTask(EcsServerClusterProvider.java:208) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.clouddriver.ecs.provider.view.EcsServerClusterProvider.lambda$findClustersForRegion$1(EcsServerClusterProvider.java:143) ~[clouddriver-ecs.jar:na]
...
(see the attached file for full stack trace)
### Steps to Reproduce:
I will try to come up with a sample pipeline (Cron) that involves Enable/Disable Cluster operations. That NPE in CloudDriver results in the following response, which made me think of DisableCluster
     "exception": {
                    "exceptionType": "RetrofitError",
                    "shouldRetry": false,
                    "details": {
                        "responseBody": "{\"error\":\"Internal Server Error\",\"message\":\"No message available\",\"status\":500,\"timestamp\":1563844140320}",
                        "kind": "HTTP",
                        "error": "Internal Server Error",
                        "errors": ["No message available"],
                        "url": "http://spin-clouddriver.spinnaker:7002/applications/myapp/clusters/mycluster/myapp-test002-service3/ecs",
                        "status": 500
                    },
                    "operation": "disableCluster",
                    "timestamp": 1563844140321

### Additional Details:

[stacktrace.txt](https://github.com/spinnaker/spinnaker/files/3419938/stacktrace.txt)

**Comment by maggieneterval** [comment]
Hey @atyutyunnik, thanks for opening this issue; so sorry you hit this error during a presentation :grimacing: 

Looping in Amazon gurus @clareliguori and @allisaurus who might be able to help with this! :pray:

**Comment by allisaurus** [comment]
@spinnakerbot add-label provider/ecs

**Comment by allisaurus** [comment]
Hi @atyutyunnik - is it possible for you to provide the (redacted where appropriate) pipeline configuration you were using when this occurred?

**Comment by atyutyunnik** [comment]
@allisaurus, attached please find the pipeline
[pipeline.txt](https://github.com/spinnaker/spinnaker/files/3424127/pipeline.txt)

**Comment by atyutyunnik** [comment]
the cleanup routine (sub-pipeline)
[cleanup.txt](https://github.com/spinnaker/spinnaker/files/3424144/cleanup.txt)

**Comment by atyutyunnik** [comment]
@allisaurus, I have re-checked, all such failures occur during a disableCluster operation:
            "type": "disableCluster",
            "name": "disableCluster",
            "startTime": 1563844140144,
            "endTime": 1563844140339,
            "status": "TERMINAL",
            "context": {
                "exception": {
                    "exceptionType": "RetrofitError",
                    **"shouldRetry": false,**

This shouldRetry==false makes me wonder a bit. I witnessed that some GET requests related to my ECS cluster in my Web browser didn't go through yesterday, as if AWS had been unable to sustain the load. I operate from an office on the West coast, while the cluster and the rest of my infrastructure reside in us-east2.

**Comment by allisaurus** [comment]
Thanks for the info, @atyutyunnik. From the error message, it looks like the placement of the instance being described is null. This can happen if the instance was in `PENDING` when it was cached. We're working on a fix that would handle this case better and will provide an update when there's something to review.
