### ISSUE TITLE
Improve metric configuration experience for multiple Prometheus accounts

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#4672]
### Issue Summary:

Users can configure multiple Prometheus accounts, each with a different set of custom metrics. Metric configs are associated with a specific metrics provider, but not a specific account (canary stages are then associated with a specific account and config). We populate the Metric Name dropdown with options from the first configured account only, meaning it may include custom metrics _not_ available to the account it eventually is used to compose queries against, and it may exclude custom metrics that _are_ available to the account.

### Possible Solutions:

- Solution 1: Change the Metric Name dropdown so users can manually enter custom metrics unavailable to the first configured account. I would probably implement this with a "Toggle for Text Input" link similar to some other fields in the UI.
- Solution 2: We probably want to avoid metric configs being associated with a specific account. However, we could fetch and merge metric names from _all_ configured accounts. If a metric is not available to all configured accounts, make this known to the user either parenthetically in the dropdown option, or as a validation warning once they've selected it (something like, "warning: this metric is only available for accounts x and y). Depending on how many Prometheus accounts are configured, the fetching/merging could get expensive...
- Solution 3: Although we don't want users to select a specific account from the metric config, we could make the Metric Name search a little smarter. Right now it's a three-character typeahead, defaulting to searching the first configured account. We could add smarter search logic (similar to the clusters view search) where a user could type something like `cpu account:my-specific-prom-account` and we could parse the account out. If account is missing or invalid, we'll just default to the first configured account like we currently do.

cc @duftler @milesmatthias

**Comment by duftler** [comment]
I like solution 3 with type-ahead for the account name followed by type-ahead for the metric name.

Backend work to support properly querying by prometheus account name is here: https://github.com/spinnaker/kayenta/pull/598
