### ISSUE TITLE
Account for Deploy configuration always incorrect in Spinnaker UI

### ISSUE THREAD

**Issue by jojwang** [spinnaker/spinnaker#4676]
### Issue Summary:
Every time we want to edit/view a deploy configuration, 
<img width="1041" alt="Screen Shot 2019-07-24 at 10 53 50 AM" src="https://user-images.githubusercontent.com/33501969/61816642-a486aa80-ae01-11e9-9c01-51020768ca7f.png">

we are take to the "Create Server Group" where the default account value may not be the actually current account
<img width="593" alt="Screen Shot 2019-07-24 at 10 57 11 AM" src="https://user-images.githubusercontent.com/33501969/61817198-d3515080-ae02-11e9-99c5-f12bf21feca3.png">

The form will show Account "A" when I know the Account is actually Account "B", and I've confirmed that the "Edit stage as JSON" view correctly shows the Account to be "B".

However, because the form may have a different incorrect Account "A", if a user tries to make other changes on the form, eg Config Filepaths, when the user clicks "Done" and "Save changes", the Account also gets saved to the new Account "A", when that was never intended.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
UI

**Comment by jojwang** [comment]
@spinnaker/ui-ux-team

**Comment by maggieneterval** [comment]
Hey @jojwang, thanks for reporting this issue! Just to clarify, is this happening for the Appengine provider? And what version of Spinnaker are you on? Thanks!

**Comment by jojwang** [comment]
1.14.10 is the version
I believe "Appengine" as the provider is accurate. 
We're using "[spinnaker for GCP](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/master/README.md)", if that's helpful.

**Comment by maggieneterval** [comment]
Thanks for the info, @jojwang! You've uncovered what appears to be a longstanding UI bug; we will patch a fix into 1.13, 1.14, and 1.15. @duftler, would you able to update the Spinnaker for GCP version to include this fix once it is cherry-picked and released?
