### ISSUE TITLE
RFC: Spinnaker usage stats

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#4738]
### Issue Summary:
The project maintainers would like to build and enable a feature to collect usage statistics from running Spinnaker instances

Details here:
https://docs.google.com/document/d/12_YcUnbE63vshofo9krQlMRiqW2WMjSYGCjb4G6dOb8/edit#

**Comment by plumpy** [comment]
This RFC is very old. The old RFC process has been superseded by a new one. If you still care about this RFC and would like feedback, please move it over to [the new RFC process](https://www.spinnaker.io/community/contributing/submitting/#before-you-begin). Thanks.
