### ISSUE TITLE
GCE: n2, c2 instance types aren't listed

### ISSUE THREAD

**Issue by plumpy** [spinnaker/spinnaker#4759]
Someone asked about this in Slack. There are a whole bunch of instance types that I can see in the cloud console but not in Deck. I'm not sure how these get populated, but none of the n2 or c2 types from this list show up in Deck:
https://cloud.google.com/compute/docs/machine-types

**Comment by duftler** [comment]
The tables in the GCE server group wizard:
![image](https://user-images.githubusercontent.com/8437718/63267575-65ad0e80-c260-11e9-874a-38568d794452.png)

are hand-crafted here: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/google/src/instance/gceInstanceType.service.js


The actual set of instance types that can be specified in a given instance template are dynamically built in the backend and returned scoped by region/zone in the response to a call to gate:8084/credentials


To select an instance type that isn't explicitly listed in one of the wizard ui tables, you can select "Custom Type" and the pulldown will be populated with the instance types available in that region/zone.

These are the types available (for my project) in us-central1-f: 
![image](https://user-images.githubusercontent.com/8437718/63267892-03a0d900-c261-11e9-8f42-066bd3c6b40b.png)

And these are the types available in us-central1-a (note the new n2-* types): 
![image](https://user-images.githubusercontent.com/8437718/63267920-14514f00-c261-11e9-9db8-8ac2a662f301.png)


One should expect the choices in the pulldown to match what is returned by a call to: `gcloud compute machine-types list --project $PROJECT_ID`

**Comment by plumpy** [comment]
Okay, thanks for the hot tip. I suppose it would be smart to explain that and also provide a link to the docs for machine types:
https://cloud.google.com/compute/docs/machine-types

But I suppose we can close this, thanks.
