### ISSUE TITLE
Add first-class support for stage status in Check Precondition stage

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#4768]
### Issue Summary:

A common use case of the Check Precondition stage is to check if a prior stage succeeded or failed. Currently, the best way to do this is with SpEL (`${#stage("Deploy")["status"].toString() == "SUCCEEDED"}`). This seems error-prone, so I'd like to add first-class support for selecting a stage and asserting its status.

Note: the Check Precondition stage is currently in Angular, so may try to refactor parts of that while I'm adding "Stage Status" as one possible precondition to check.

**Comment by emjburns** [comment]
This is a great idea!
