### ISSUE TITLE
Improve usability of "Failed on startup" error messages on Deck

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#4772]
### Issue Summary:

There are a number of UX issues with the tooltip to display pipeline start errors, to the point it can totally unusable sometimes.

### Cloud Provider(s):

Any.

### Environment:

Any

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

UX -- @spinnaker/ui-ux-team

### Description:

When a pipeline run fails on startup, users have to hover over an icon to learn more about the problem. There are multiple issues with this approach:

1. It isn't obvious at all that one has to hover over the icon to learn more about the error.
1. It can be impossible to read the error messages, unless you alter the HTML in the page like I did in the video below.
1. It isn't possible to copy the text. And I may want to copy some of the ids mentioned there, for example.

### Steps to Reproduce:

Create a pipeline with an invalid expected artefact. Run the pipeline.

### Additional Details:

Watch this quick video to see what one has to do to be able to see error messages: https://imgur.com/eC6vLkP

**Comment by gnarea** [comment]
@spinnaker/ui-ux-team

**Comment by maggieneterval** [comment]
Hey @gnarea, thanks for taking the time to open this issue! I threw together an alternative UI, would love your feedback:

![398239a1-df5f-4a95-95a1-d51728099583](https://user-images.githubusercontent.com/15936279/64034030-d0413280-cb1b-11e9-88e2-db7f638d729f.gif)

**Comment by gnarea** [comment]
Hey @maggieneterval! That looks good to me. Thank you so much for fix the issue 🙇 Much appreciated.
