### ISSUE TITLE
Support resolved expected artifacts lookup by display name in pipeline expressions

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#4783]
### Issue Summary:

Artifacts in `${trigger['resolvedExpectedArtifacts']}` can only be looked up by index, which can be error-prone when you have multiple expected artifacts or when you add/remove expected artifacts.

### Cloud Provider(s):

Any

### Environment:

Any

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Pipelines

### Description:

I'd expect to be able to look up a resolved/expected artifact by display name. E.g., `${trigger['resolvedExpectedArtifacts']['my-artifact']}` instead of `${trigger['resolvedExpectedArtifacts'][4]}`.

### Steps to Reproduce:

Create multiple expected artifacts, then refer to them in pipeline expressions.

### Additional Details:

N/A

**Comment by evansb** [comment]
🙋‍♂ I'm volunteering to take this one, I think it's a good idea to introduce a [Helper Function](https://www.spinnaker.io/reference/pipeline/expressions/#helper-functions) for getting resolved Artifacts.

**Comment by gnarea** [comment]
Thanks @evansb! 🙇 A helper function would work for me.
