### ISSUE TITLE
Excessive Wait for Capacity Match

### ISSUE THREAD

**Issue by hodnett** [spinnaker/spinnaker#4786]
### Issue Summary:

When deploying a pipeline on Spinnaker 1.15.2., the "reset source to original size" step never seems to complete. On five separate runs, it stalled at the "wait for capacity match" task. (Each time, we aborted the job after 25 minutes.)

When deploying the exact same pipeline on Spinnaker 1.14.14, the same task is virtually instantaneous, taking less than a second. 

We suspect there may be a regression with the Clouddriver module.

### Cloud Provider(s):

AWS, Kubernetes, Cloud Foundry

### Environment:

Spinnaker itself is deployed within an Amazon Web Services Kubernetes cluster; however when deploying the desired artifact itself, we're pushing to open sourced Cloud Foundry.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Pipelines

### Description:

Error as it's shown in v. 1.15.2:
![Spinnaker version 1.15.2](https://user-images.githubusercontent.com/3912987/63471291-98533480-c423-11e9-85cb-88dac4237210.png)

Success as it's shown in v. 1.14.14:
![Spinnaker version 1.14.14](https://user-images.githubusercontent.com/3912987/63471362-c6387900-c423-11e9-8319-0b2d6f099ee8.png)

### Steps to Reproduce:

1. Execute any pipeline, confirm success.
2. Upgrade to 1.15.2. Execute any pipeline, note failure. (All pipelines stall on the same task.)
3. Via Halyard, create new deployment:
- copy existing configuration file
- set version to 1.14.14
- update override URLs in the security section
- update location within the deployment section to point to a different Kubernetes namespace
- retain all other values
4. Within new deployment, confirm Spinnaker loads pipelines from shared persistent storage.
5. Execute any pipeline, confirm success.

**Comment by hodnett** [comment]
After further discussion with my team, we're speculating that it could also have something to do with our choice of deployment strategies, i.e., a bug with red/black deployments or rolling red/black deployments.

I'll try to respond to any questions and requests for more info as quickly as I can.

**Comment by hodnett** [comment]
My team asked me to clarify that Spinnaker is running on a CFCR cluster. Hope that helps define the environment more precisely.

**Comment by anishp55** [comment]
bump.  any updates or can you point us in the direction so we can investigate and make a PR back on this item.  not being able to deploy to PCF is kinda of a bummer

**Comment by scottfrederick** [comment]
@hodnett @anishp55 Is it possible to capture logs from clouddriver when this error occurs?

**Comment by anishp55** [comment]
attached.  this was from 1.16.0
we are spinning up the latest master as well to test
[clouddriver.log](https://github.com/spinnaker/spinnaker/files/3602175/clouddriver.log)

**Comment by anishp55** [comment]
@scottfrederick are there any other details i can provide?

**Comment by anishp55** [comment]
this bug is still in latest master as well as 1.16.2.  are there any plans to fix this for the .15 or .16 releases?  I've looked over the diff set in cloud driver, unfortunately there are around ~1k commits and i can't figure out where to start to look to try to fix this.  Can you provide me some context on where to look, or are there any plans to actually fix this for the next release as its has been a month since this report has been filed

**Comment by Jammy-Louie** [comment]
@anishp55 @hodnett would it be possible to provide the pipeline JSON with sensitive data removed? I would like try to recreate the pipeline on our environments.

**Comment by Jammy-Louie** [comment]
reproduced and believe should be resolved:

![Screen Shot 2019-10-03 at 11 25 54 AM](https://user-images.githubusercontent.com/8474965/66152284-29065e00-e5e7-11e9-97be-1e8484949061.png)
