### ISSUE TITLE
Support for GPUs in distributed multiple zones deployments

### ISSUE THREAD

**Issue by raghunandanbs** [spinnaker/spinnaker#4796]
### Issue Summary:
Support for GPUs on Distribute instances across multiple zones during deployment

### Cloud Provider(s):
Google Cloud Platform

### Environment:
Distributed

### Description:
Unable to select GPUs in multi-zone deployments, which is otherwise available when a zone is selected explicitly.

### Screenshot:

![distributed_zones_not_supported](https://user-images.githubusercontent.com/52439657/63671269-b5f61480-c7fc-11e9-942e-077ae52487b7.PNG)

**Comment by reysravanga** [comment]
hi @maggieneterval ,

As you know google cloud will provide GPU support in multi zones  for few regions such as **us-west1 for T4 GPU(us-west1-a&us-west1-b) ,asia-east1 for K80 GPU(asia-east1-a&asia-east1-b)**. We would like to distribute the instances across multiple zones which supports the GPU. 


![image](https://user-images.githubusercontent.com/5931501/63764208-ee245280-c8e3-11e9-871b-1f066436fce5.png)


We would be very happy to see spinnaker multi-zone support for GPU in Google cloud platform.

**Comment by reysravanga** [comment]
Thanks @maggieneterval  and @demobox ,

kindly let us know if any further info required.

**Comment by rampatnaik** [comment]
Hope it solved and when we can expect the fix

**Comment by maggieneterval** [comment]
Hi @rampatnaik, @reysravanga, and @raghunandanbs! @plumpy and I are hoping to work on this feature this week.

Would it be acceptable if you had to select your zones explicitly when creating a regional server group (shown in the screenshot below) with guest accelerators? If so, we can probably get this feature in before our next release (1.17). Let us know!

![QEBDMi6w9SG](https://user-images.githubusercontent.com/15936279/66783927-1291b980-eea7-11e9-9395-8ffb18e05716.png)

**Comment by reysravanga** [comment]
Thanks @maggieneterval !!

We are looking for the same feature 👍

**Comment by maggieneterval** [comment]
Thanks for the response, @reysravanga. To clarify, you will need to select zones explicitly in order to add an accelerator to a regional server group. Thanks!

**Comment by maggieneterval** [comment]
Hi all! This feature will be released with 1.17 in early November. Closing this issue for now, but we'd love your feedback once it is released!
