### ISSUE TITLE
Feature Request: Add capability to control access to GCB trigger account

### ISSUE THREAD

**Issue by jonathanheaden** [spinnaker/spinnaker#4814]
### Issue Summary:
The account which Spinnaker uses to create a Cloudbuild trigger as part of the Google Cloud Build stage in a pipeline does not have permissions applied.

### Cloud Provider(s):
Google Cloud

### Environment:
We are running Spinnaker in GKE to deploy into GCP. We have multi tenant internal customers who use the service running in one cluster to deploy into different clusters within a shared VPC 

### Feature Area :
Igor

### Description:
Anyone who can create a pipeline in spinnaker can add a GCB stage from which they can select any GCB account. Each GCB account has permission to run cloudbuild jobs in the project configured for that account. In a multi-tenanted Spinnaker this can lead to teams inadvertently running cloudbuild jobs in the wrong project.

### Steps to Reproduce:

1. Add Google Cloud Build stage to a pipeline
1. Select any account from the account drop down

**Comment by afcastano** [comment]
Hello @ezimanyi =)
Is there any reference implementation for another CI or is this a completely new feature in igor?

**Comment by ezimanyi** [comment]
@afcastano : Thanks for volunteering to help with this!  There are existing implementations of permissioning for other CI services in igor, so you should be able to just extend what exists for the other services.

The original implementation of this was added in spinnaker/igor#374.  I think what you'll likely need to do here is:
(1) Augment `GoogleCloudBuildProperties.Account` to contain a `Permissions` object (similar to what is in `JenkinsService`)
(2) Add an endpoint to `GoogleCloudBuildController` that returns accounts and their permissions, suitable for `fiat` to call when it wants to cache the permissions of GCB accounts.  (This is the equivalent of the `/buildServices` endpoint for other types of build services.)  Alternatively, it might be possible (and possibly better) to just update the `/buildServices` endpoint to also return GCB accounts.
(3) Update Fiat to also fetch GCB accounts.  (Look at `IgorService` in `fiat`.)  You might actually not need to do anything here if you just update `/buildServices` to include GCB accounts.
(4) Add `@PreAuthorize` annotations to the endpoints in `GoogleCloudBuildController` to indicate whether we should check READ or WRITE permissions before allowing the endpoint.  There's a bit of subtlety here as some of these are called by `echo` in response to Pubsub events (ex: `extractArtifacts` and `updateBuild`) so likely will need to allow unauthenticated access.

I think those should be the main places that would need to be changed.  I'm sure there will be some subtleties here and there that I'm not thinking of but hopefully that is reasonable to get started.  Please keep me posted as you work on this, I can definitely help work through any issues you discover when implementing it!

**Comment by afcastano** [comment]
Thanks for the detailed explanation @ezimanyi . We will give it a try. I'll keep you posted.
Cheers!

**Comment by afcastano** [comment]
Hey @ezimanyi , we are finally working on this. We are evaluating the possibility of adding GCB accounts to `/buildServices` as you suggested.

Initially we thought we could augment `BuildServices` class to also include GCB accounts, but that implies that we need to somehow come up with a `BuildOperations` implementation for GCB accounts. (In reality `BuildServices` should be renamed to `BuildOperations` or something).

So two options we can follow:
1. The easiest way is to just add the list of GCB accounts to the existing return list from `buildServices.allBuildServices`:
```java

```

2. Try to create a _service_ similar to `ConcourseService` for GCB and add it to the current `BuildServices` class. I feel this is a bigger refactor that might require more discussion.

**Comment by ezimanyi** [comment]
@afcastano : I took a brief look at this today.  I think what would make the most sense is to find a way to have GCB accounts and other CI accounts implement a common interface that has the functionlity we need for `getAllBuildServices()` and nothing more.

I *think* this can be done by adding the following to `GoogleCloudBuildProperties.Account` and having it implement `BuildService`:
```
    @Override
    public BuildServiceProvider getBuildServiceProvider() {
      return BuildServiceProvider.GCB;
    }

    @Override
    public Permissions getPermissions() { /* ... */ }
```

You still wouldn't be able to store the the GCB account in `BuildServices` as it isn't a `BuildOperation`.  (I completely agree that class should be renamed, as this confused me as well.  Looks like it was changed in spinnaker/igor#374 which I reviewed but didn't make that suggestion.)

But I think it's fine to not store GCB accounts in `BuildServices`; it's different enough, and in reality that class isn't great as pretty much every consumer immediately casts the result of getting a service to its own type.  It could use some refactoring to figure out the common logic (which there really won't be much of for GCB anyway.)

So then `getAllBuildServices()` could just add the GCB accounts manually...which looks exactly like what you're suggesting.  (The only thing that confuses me in your code snippet is the `new ArrayList<String>`...is the `String` just a typo?)

So overall I think I agree with exactly what you're planning to do!

**Comment by afcastano** [comment]
Thanks again for the clarification. We will let you know when the PR is ready.

And yes, it was a typo. =)

**Comment by afcastano** [comment]
Hello @ezimanyi, PR ready... please let me know what do you think. =)

**Comment by jonathanheaden** [comment]
Thanks
