### ISSUE TITLE
Missing UI Wizards/Fields

### ISSUE THREAD

**Issue by jlpedrosa** [spinnaker/spinnaker#4826]
### Issue Summary:
@spinnaker/ui-ux-team

After installing spinnaker in a cluster following the [official guide ](https://www.spinnaker.io/setup/install), it starts correctly, but all the "Create XXX" as in "Create server group", "Create load balacer" don't show the appropriate wizards, with fields, it just asks for a raw manifest. So I don't get the same view as in the [guides](https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/#2-create-a-load-balancer) but a single menu asking for a manifest. 

### Cloud Provider(s):
K8s v2

### Environment:
Azure AKS k8s clusters (multiple accounts)

### Steps to Reproduce:
Create a cluster providing the official guide. 

### Additional Details
[image of the ui](https://pasteboard.co/IvqSOoY.png)

**Comment by maggieneterval** [comment]
Hey @jlpedrosa, thanks for reaching out! It looks like you are reading the tutorial for Spinnaker's legacy/v1 Kubernetes provider, which exposes wizards for workloads and load balancers. The currently-supported v2 provider is manifest-based and expects you to provide a Kubernetes manifest through either a text input or as an artifact. Do you know if you specified the v1 or v2 provider for the account in question? If you deployed with Halyard, you probably ran a command like `hal config provider kubernetes account add my-k8s-v2-account --provider-version v2 `, which added a section to your `/.hal/config` file. Let me know!

**Comment by jlpedrosa** [comment]
Hi @maggieneterval 

You are absolutely correct, I used v2.  Sorry for the miss-understanding.

**Comment by namnguyen5497** [comment]
Im facing this issue with version 1.26.3, i installed spinnaker on a kubernetes cluster using a halyard container. I was able to expose the spin deck and spin gate, created a test application, but the field "create new LoadBalancer" and "create new Firewall" is missing both corresponding tabs, my provider version is v2
