### ISSUE TITLE
GCE Clone Server Group fails

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#4859]
### Issue Summary:

When trying to clone a GCE server group, it fails with the following error:

```
angular.js:14961 TypeError: Cannot read property 'localSSDSupported' of undefined
```

### Cloud Provider(s):

GCE

**Comment by maggieneterval** [comment]
Was unable to reproduce this successfully, going to leave the client-side bandaid in place for now. If anyone else is able to reproduce this issue, please let me know!

**Comment by qllb** [comment]
Having this issue with group of E2-type instances.
