### ISSUE TITLE
Wrap call to stats in Hystrix to prevent perpetual failure if in an air-gapped environment

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#4864]
Should also probably remove connection and read timeouts and/or use the Hystrix ones

**Comment by plumpy** [comment]
FYI, there is apparently a plan afoot to use resilience4j (which is based on, but better than, Hystrix): spinnaker/kork#343

> Hystrix isn't really used here at Netflix anymore and doesn't get much love. ... This library has a few more features that we can use, has less dependencies than Hystrix, and seems to be the direction the greater Spring community is headed. Should be nice!

**Comment by ttomsu** [comment]
I put a PR together (referenced above) that uses resilience4j

**Comment by plumpy** [comment]
oh, cool, didn't see that
