### ISSUE TITLE
Templated pipelines stages disappear from the stage graph when configuring

### ISSUE THREAD

**Issue by louisjimenez** [spinnaker/spinnaker#4887]
### Issue Summary:

A regression introduced in the migration to React is causing templated stages to briefly render and then disappear from the stage graph. 

Thanks to @iniinikoski for flagging this.

### Environment:

1.16.x

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Deck

### Steps to Reproduce:

1. Create a templated pipeline with at least one stage.
2. Configure the templated pipeline.

**Comment by louisjimenez** [comment]
Issue appeared after these changes, https://github.com/spinnaker/deck/pull/7318/files#diff-d6309527c576e914ed6d0cccbe1a006f

**Comment by louisjimenez** [comment]
This issue was resolved in a subsequent patch release. To help prevent future breaking changes, [this PR](https://github.com/spinnaker/deck/pull/7491) was opened up to add testing

**Comment by iniinikoski** [comment]
A huge thanks @louisjimenez & others - I can confirm I cannot repeat the issue anymore with Spinnaker 1.16.2!

**Comment by louisjimenez** [comment]
Great! And yes, thanks to @christopherthielen and @Jammy-Louie for jumping on the original bug.
