### ISSUE TITLE
entity tags are not showing up in the UI

### ISSUE THREAD

**Issue by vava** [spinnaker/spinnaker#4897]
### Issue Summary:
I've configured entity tags as documented on https://www.spinnaker.io/guides/user/tagging/
I can set the tags through REST API and through pipeline stages successfully. I can get them through REST API as well.

However, they do not show up in the UI. I've tracked it 

### Cloud Provider(s):
Google

### Environment:
Kubernetes

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
I've configured entity tags as documented on https://www.spinnaker.io/guides/user/tagging/
I can set the tags through REST API and through pipeline stages successfully. I can get them through REST API as well.

However, they do not show up in the UI, next to server group where I expect them.
As I understand from the code, they should be rendered by ServerGroupDetails.render() method but it is never called.

I've checked that the javascript can load the tags, in particular EntityTagsReader.addTagsToServerGroups() seems to be getting correct data and doing the right thing.

### Steps to Reproduce:
Follow the tagging guide.

### Additional Details:
I'm not sure I've configured everything correctly or if my install of Spinnaker is not broken somehow but it's not clear to me how to check this.

**Comment by plumpy** [comment]
Is spinnaker/spinnaker.github.io#1507 a workaround for this issue, or is that not related to this problem?

**Comment by vava** [comment]
It's part of the same problem. Without fix applied in [spinnaker/spinnaker.github.io#1507](https://github.com/spinnaker/spinnaker.github.io/pull/1507), when I turn entityTags on, UI just shows "Application not found". This is due to EntityTagsReader.getAllEntityTagsForApplication() throwing an exception when it tries to read SETTINGS.entityTags.maxResults.

However, even with that fixed, UI still does not show any entity tags.

**Comment by vava** [comment]
Ok, I finally figured this out.

Details page for AppEngine server group doesn't have any support for entity tags, so they will not be shown there.

Tag names have to start with either spinnaker_ui_alert: or spinnaker_ui_notice: to be shown in UI.

Tags have to be attributed to server group by all of (name, account, region), neither can be missing and each has to be exactly the value, no globbing allowed.
