### ISSUE TITLE
Multiple simultanious executions of one app/pipeline

### ISSUE THREAD

**Issue by enki211** [spinnaker/spinnaker#4908]
We are running into an issue starting multiple pipelines of the same application off around the same time. Our use case is that we have a lot of apps which are very similar as far as config and deployments go, just needing to modify a few values such as what image to deploy. What we wanted to do was use this project to kick off a single Spinnaker application/pipeline for every app deployment with differing parameters. While this works great if only one is executing we get an error when we try to execute more than one; however, the error only seems to be with the cli as both pipelines are able to complete successfully. 

I think we tracked it down to https://github.com/spinnaker/spin/blob/master/cmd/pipeline/execute.go#L134-L136 that if statement, and we were even able to test removing the line and it works great.

It looks like this was changed in https://github.com/spinnaker/spin/pull/130 from returning all to returning only if there is one execution but did not find a GitHub issue or much on the pr as to why it was changed.

I was hoping to get your thoughts on if what we want to do is feasible with this project and maybe some more background on why it was changed.

**Comment by louisjimenez** [comment]
resolved by https://github.com/spinnaker/spin/pull/217
