### ISSUE TITLE
Deck not starting after upgrade, Permission denied

### ISSUE THREAD

**Issue by jzuijlek** [spinnaker/spinnaker#4934]
### Issue Summary:
When upgrading from Version 1.15.1 to version 1.16.1 the spin-deck container would not start.

### Cloud Provider(s):
Kubernetes V2

### Steps to Reproduce:
`
hal config version edit --version 1.16.1
hal deploy apply
`

### spin-deck pod logs:
```
sed: can't read spinnaker.conf: Permission denied
sed: can't read spinnaker.conf: Permission denied
Enabling site spinnaker.
To activate the new configuration, you need to run:
  service apache2 reload
ERROR: Can't open /etc/apache2/sites-available/spinnaker.conf: Permission deniedsed: can't read ports.conf: Permission denied
apache2: Syntax error on line 150 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/ports.conf: Permission denied
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

### Additional information
Reverting to version 1.15.1 resulted in the same error messages.

**Comment by jzuijlek** [comment]
Today I deleted the pod and now the new one started normally. I did try this previously with any luck. Not sure why it worked now.

**Comment by samsiu2014** [comment]
@jzuijlek Sorry to bother you but i faced the same problem no matter i used the 1.14.15 (LoveDeathAndRobots) or 1.16.2 (SecretObsession). I tried to deleted the spin-deck pod many times but it didn't help. Do you have any idea?

**Comment by sanjog152** [comment]
Same with my setup. I have tried with 1.15.6 , 1.16.4, 1.16.5, 1.17.0 ,1.17.1 and 1.17.2 version. deck pod is crashloopbackoff with below error

sed: can't read spinnaker.conf: Permission denied
sed: can't read spinnaker.conf: Permission denied
Enabling site spinnaker.
To activate the new configuration, you need to run:
  service apache2 reload
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
ERROR: Can't open /etc/apache2/sites-available/spinnaker.conf: Permission deniedsed: can't read ports.conf: Permission denied
apache2: Syntax error on line 150 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/ports.conf: Permission denied
Action '-D FOREGROUND' failed.
The Apache error log may have more information.

**Comment by jzuijlek** [comment]
What I did was create my own Dockerfile:
```
From gcr.io/spinnaker-marketplace/deck:2.12.1-20191001150241
USER root
Run chmod 777 /etc
```
And host that image on docker hub: `docker.io/jzuijlek/spin-deck:2.12.1-20191001150241`

**Comment by ananyahn** [comment]
> What I did was create my own Dockerfile:
> 
> ```
> From gcr.io/spinnaker-marketplace/deck:2.12.1-20191001150241
> USER root
> Run chmod 777 /etc
> ```
> 
> And host that image on docker hub: `docker.io/jzuijlek/spin-deck:2.12.1-20191001150241`

Thank you for the resolution provided. I am glad being a newbie was helpless.
