### ISSUE TITLE
RFC: Formal Mentorship Program

### ISSUE THREAD

**Issue by emjburns** [spinnaker/spinnaker#4953]
Here is a proposal for a formal mentorship program for the Spinnaker Community.

https://docs.google.com/document/d/1DczRUcDPdEVZ7xstZIkOkT6C7poDf_6Gvl59ig0TgYg/edit#

@ajordens @robzienert @plumpy @ezimanyi of the TOC please take a look.

**Comment by ezimanyi** [comment]
This is an excellent idea!

**Comment by costimuraru** [comment]
Nice idea!

**Comment by robzienert** [comment]
Can we move this proposal to the community repo? I'd be interested in seeing some thought put towards who is responsible for running this program.

**Comment by emjburns** [comment]
Sure, I'll move it.

**Comment by emjburns** [comment]
Moved to https://github.com/spinnaker/community/pull/51
