### ISSUE TITLE
RFC: Kubernetes operator for Spinnaker

### ISSUE THREAD

**Issue by ncknt** [spinnaker/spinnaker#4961]
Halyard is great at offering a simple way to configure Spinnaker services but is not easy to operationalize. We've come up with an MVP of a Kubernetes operator for Spinnaker that allows administrators to manage Spinnaker with `kubectl` (or whatever Kubernetes tool).

The vision is to perform preflight checks (via an admission webhook) and actively monitor Spinnaker.

We're proposing to move the operator to Spinnaker's GitHub:  https://docs.google.com/document/d/1Fs-xK7sOZ4YLSw1ae_cQ_rsB0kMNon9AfYli2a5Udhs/edit?usp=sharing

@ezimanyi @ethanfrogers @duftler

**Comment by ncknt** [comment]
@spinnakerbot add-label proposal

**Comment by robzienert** [comment]
Hi Nicolas, thanks for this RFC - we've recently changed process to move RFCs to the community repo. Could you please move this into a pull request directory: https://github.com/spinnaker/community/tree/master/rfc

**Comment by ncknt** [comment]
Added https://github.com/spinnaker/community/pull/41. Closing that issue.
