### ISSUE TITLE
Update Halyard to support apps/v1 Deployments now that apps/v1beta2 is deprecated

### ISSUE THREAD

**Issue by justinrlee** [spinnaker/spinnaker#4995]
### Issue Summary:

Halyard-created Spinnaker services will probably need to be updated to use the apps/v1 API for deployments, rather than apps/v1beta2, since the latter has been deprecated as of Kubernetes 1.16.

I think this is independent of the Clouddriver fixes that address K8s 1.16, since Halyard doesn't use Clouddriver.

Might be as simple as changing https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml#L1 ~, but there's also the possibility that Halyard will need to handle removing the old deployment if it's creating the new one (I don't know how well Kubernetes handles the same object created against different APIs).~

~I.e., if you have `apps/v1beta2/deployment` and are creating a `apps/v1/deployment`, do you have to delete the old one?  Does Halyard have to handle this?~

Nevermind - I think you can just update the object with the new API version and it'll work.

**Comment by justinrlee** [comment]
Addressed by https://github.com/spinnaker/halyard/pull/1443, I think.

**Comment by costimuraru** [comment]
Will this continue to work with K8s 1.14? (which the default right now in AWS EKS)

**Comment by justinrlee** [comment]
Yep!  The "GA" apps/v1 `deployment` object was introduced in either 1.9 or 1.10.

**Comment by ethanfrogers** [comment]
This looks complete. Closing!
