### ISSUE TITLE
Kayenta: Not possible to run NRQL queries unrelated to the application

### ISSUE THREAD

**Issue by silvez-dh** [spinnaker/spinnaker#5014]
### Issue Summary:
Not possible to run NRQL queries unrelated to the application (without appending **WHERE ... LIKE** clauses to it), making it unusable to query metrics not related to the application (but to total of orders values we can query on New Relic Insights)

### Feature Area:
kayenta

### Description:
We have an application that we would like to base its metrics on orders increase/decrease after its canary is deployed.

The NRQL query to achieve this is unrelated to the application specific metrics. The actual NR implementation expects at least some identifier (eg. **_scope_key** to **appName** on **Extended Params**) to identify the application.

Would be good to have the possibility to run NRQL that are not related to an application. In this case the comparing between baseline and canary metrics would be **Baseline Offset** time set in the **Analysis Config** (eg. comparing the actual number of orders to the amount of 30 min ago)

### Steps to Reproduce:
In the **Canary Config** for **NewRelic metricstore** add a tailored NRQL query to get values out of the application scope (like explained above). First *_scope_key* will be required to identify the application, then a WHERE ... LIKE  clauses will appended to the query, making it enclosed to the application

### Additional Details:

The query we would like base metrics from is the following:
```
SELECT filter(uniqueCount(externalDeliveryId), WHERE orderResponseStatus IS NOT NULL OR (notificationType IN ('MISSED','REJECTED','EXPIRED','ACCEPTED','CANCELLED'))) AS 'TOTAL' FROM DeliveryNotification, Transaction WITH TIMEZONE 'Europe/Berlin' WHERE appName in ('my-application') AND (testOrder IS NULL OR testOrder = 'false') LIMIT 100
```
This will not work as expected if something is appended to it.

**Comment by fieldju** [comment]
Yes, you can use inline templates and do what ever NRQL you want.
See: 
- https://github.com/spinnaker/kayenta/blob/master/kayenta-newrelic-insights/src/test/groovy/com/netflix/kayenta/newrelic/metrics/NewRelicQueryBuilderServiceSpec.groovy
- https://github.com/spinnaker/kayenta/pull/603

Basically in your canary config JSON you can define a metric like the following

```json
	"extendedScopeParams": { "foo": "bar" }
```

```json
{
	    "name": "some-name",
	    "query": {
	        "type": "newrelic",
	        "customInlineTemplate": "SELECT count(*) FROM Transaction TIMESERIES ${step} seconds SINCE ${startEpochSeconds} UNTIL ${endEpochSeconds} WHERE status_code LIKE '5%' AND asg_name LIKE '${scope}' AND region LIKE '${location}' AND foo LIKE '${foo}'"
	    },
	    "groups": [
	        "group 1"
	    ],
	    "analysisConfigurations": {
	        "canary": {
	            "nanStrategy": "remove",
	            "direction": "either"
	        }
	    },
	    "scopeName": "default"
	}
```

and this will generate NRQL like the following

```sql
SELECT count(*) 
FROM Transaction TIMESERIES 60 seconds 
SINCE 1564358400 UNTIL 1564444800 
WHERE status_code LIKE '5%' 
    AND asg_name LIKE 'myService' 
    AND region LIKE 'us-west-2' 
    AND foo LIKE 'bar'
```

**Comment by fieldju** [comment]
Also the current UI in Deck doesn't have support for inline templates as outlined here: https://github.com/spinnaker/kayenta/issues/595

**Comment by silvez-dh** [comment]
thanks for clarifying it @fieldju

Btw, trying to run inline template has mentioned, it's giving the following error:

```
"stackTrace": "java.lang.NullPointerException
 com.netflix.kayenta.newrelic.service.NewRelicTimeSeries.getDataPoints(NewRelicTimeSeries.java:76)
 com.netflix.kayenta.newrelic.metrics.NewRelicMetricsService.queryMetrics(NewRelicMetricsService.java:132)
 com.netflix.kayenta.metrics.SynchronousQueryProcessor.executeQuery(SynchronousQueryProcessor.java:100)
 com.netflix.kayenta.metrics.SynchronousQueryProcessor.processQueryAndReturnMap(SynchronousQueryProcessor.java:177)
 com.netflix.kayenta.metrics.SynchronousQueryProcessor.executeQueryAndProduceTaskResult(SynchronousQueryProcessor.java:192)
 com.netflix.kayenta.newrelic.orca.NewRelicFetchTask.execute(NewRelicFetchTask.java:93)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:113)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:330)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:112)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
 com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127)
 com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:50)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:111)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:195)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:188)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)
 com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
 com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
 com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69)
 com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)
 com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.conc
"error": "Unexpected Task Failure",
```

The full canary config used stands for:

```
{
  "applications": [
    "myapp"
  ],
  "classifier": {
    "groupWeights": {
      "Group 1": 100
    }
  },
  "configVersion": "1",
  "createdTimestamp": 1571139205274,
  "createdTimestampIso": "2019-10-15T11:33:25.274Z",
  "description": "",
  "judge": {
    "judgeConfigurations": {},
    "name": "NetflixACAJudge-v1.0"
  },
  "metrics": [
    {
      "analysisConfigurations": {
        "canary": {
          "nanStrategy": "replace"
        }
      },
      "groups": [
        "Group 1"
      ],
      "name": "orders",
      "query": {
        "serviceType": "newrelic",
        "type": "newrelic",
        "customInlineTemplate": "SELECT filter(uniqueCount(externalDeliveryId), WHERE orderResponseStatus IS NOT NULL OR (notificationType IN ('MISSED','REJECTED','EXPIRED','ACCEPTED','CANCELLED'))) AS 'TOTAL' FROM DeliveryNotification, Transaction WITH TIMEZONE 'Europe/Berlin' WHERE appName in ('myapp') AND (testOrder IS NULL OR testOrder = 'false') LIMIT 100"
      },
      "scopeName": "default"
    }
  ],
  "name": "webkick-orders",
  "templates": {},
  "updatedTimestamp": 1571139234977,
  "updatedTimestampIso": "2019-10-15T11:33:54.977Z"
}
```

Do you have an idea what's wrong?

**Comment by fieldju** [comment]
Here is where the NPE is occurring: [NewRelicTimeSeries:76](https://github.com/spinnaker/kayenta/blob/master/kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/service/NewRelicTimeSeries.java#L76)

That method looks like it's trying to iterate through the time series data returned by the New Relic Insights API.

I would assume that the NRQL query you have written is for some reason not returning the results in a form that Kayenta knows how to process (Jackson deserialization issue?).

Guessing either
0. api key issue that is being presented in a horribly obfuscated way.
1. Your query has an error.
2. Your query isn't returning any results.
3. Your query isn't aggregating multiple time series into a single series via an aggregation method.
4. Something else entirely?

I would start by running your NRQL

```sql
SELECT filter(uniqueCount(externalDeliveryId), WHERE orderResponseStatus IS NOT NULL OR (notificationType IN ('MISSED','REJECTED','EXPIRED','ACCEPTED','CANCELLED'))) AS 'TOTAL' FROM DeliveryNotification, Transaction WITH TIMEZONE 'Europe/Berlin' WHERE appName in ('myapp') AND (testOrder IS NULL OR testOrder = 'false') LIMIT 100
```

Via Curl or Postman just like the [remote service does here](https://github.com/spinnaker/kayenta/blob/master/kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/service/NewRelicRemoteService.java#L29)

Then confirm that it is returning results as you expect.

I would then check the response that is returned by a query such as https://github.com/spinnaker/kayenta/blob/master/kayenta-newrelic-insights/src/test/groovy/com/netflix/kayenta/newrelic/metrics/NewRelicQueryBuilderServiceSpec.groovy#L73-L78

Is there anything that jumps out in the responses that are different that could cause a derialization issue making [List<NewRelicSeriesEntry> timeSeries](https://github.com/spinnaker/kayenta/blob/master/kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/service/NewRelicTimeSeries.java#L30) be null?

Cheers,

Justin

**Comment by silvez-dh** [comment]
@fieldju very thanks for the great explanation and attention! Sorry for getting back late on this!

So far including the TIMESERIES did solved the issue. I'm still playing with the query to make it return what we expect. 

Saw also the commit https://github.com/spinnaker/kayenta/commit/2729ab282b0b3f1832a522d7d8010a8443f32d70 with more information on it.
