### ISSUE TITLE
[UI] Not able to one perticular Trigger to delete From Automated Triggers  

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#5019]
### Issue Summary:
  Not able  delete  second trigger From Automated Triggers
### Cloud Provider(s):
       Spinnaker [UI]
       Spinnaker version 1.16.1 & 1.16.3
### Environment:
         GCP and AWS

### Feature Area:
         Configuartion 

### Description:
        Not able to delete one perticular Trigger From Automated Triggers , when mutliple triggers enabled , trigger1,trigger2 .... , i want  to delete trigger2 , but it deletes trigger1 and then trigger2 only. its not deleting directly trigger2.

### Steps to Reproduce:
        Add any two or more Triggers in Automated Triggers , and try to delete second or thired trigger, i will not delete, it deletes first one only like stack 
           
![UI-issues](https://user-images.githubusercontent.com/8611683/66644723-49fe2d00-ec3f-11e9-8666-8abc3ebd93fe.png)

**Comment by maggieneterval** [comment]
@phanikumarp thanks so much for reporting this issue. Two questions:

- What version of Spinnaker are you running?
- Have you enabled the `artifactsRewrite` feature flag?

**Comment by phanikumarp** [comment]
> * artifactsRewrite

Spinnaker version which tested was 1.16.1 and 1.16.3
Did n't enable artifactsRewrite flag

**Comment by maggieneterval** [comment]
@phanikumarp thanks for clarifying! I'm unable to reproduce this problem on my end -- are you able to open your browser console and let me know if you're seeing any errors when you try to delete the trigger?

**Comment by phanikumarp** [comment]
Yes, seems issue resloved ,and one  when i delete any trigger ,it not showed any noftification or message.
