### ISSUE TITLE
Clouddriver huge load on pretty small deployment

### ISSUE THREAD

**Issue by 23doors** [spinnaker/spinnaker#5041]
### Issue Summary:

Terrible clouddriver performance with only 4 clusters?

### Cloud Provider(s):

Kubernetes

### Environment:

Spinnaker 1.16.3 with halyard 1.24.0 running clouddriver image clouddriver:6.3.2-20191005075315 running in GKE cluster.

### Feature Area:

Clouddriver

### Description:

Running v2 k8s with 4 clusters and experiencing huge load on clouddriver pods. 
Currently on 3 replicas (with 1 cpu limit) and seeing load 4-8+ there.

iostat seems fine though.
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          35.70    0.04   10.66    0.11    0.00   53.50

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda              12.19         0.65       405.70    4026873 2529581690
dm-0              0.00         0.18         0.00    1151848          0
```

so my guess is that network connections are taking the most of the load. Which is a bit odd, as this is only communicating with other GKE clusters running in same region.  Seeing also quite a few timeouts (one every few minutes):
```
Unable to connect to the server: dial tcp <ip>:443: i/o timeout
```

Enabled `--only-spinnaker-managed true`, tried adding `omit-namespaces` and `omit-kinds`. But nothing really changed. Is there a way to limit concurrency here or cache refresh period? Even though cacheThread is 1, I see that different namespaces for 1 cluster are concurrently polled even in same pod. I tried adding --kinds to only `namespace,event,service,ingress,replicaSet,controllerRevision,horizontalpodautoscaler` but then cache stopped to work completely. There isn't exactly a huge amount of namespaces per cluster as well, roughly ~20. 

When I increased number of clouddriver replicas to 8, load decreased to ~2 but I was still getting timeouts (which when occuring during a runJobManifests stage cause it to fail). And I don't believe that 4 relatively small clusters with 20 namespaces warrant the need for so many replicas already?

To circumvent force cache refresh taking ~2 minutes for each stage, I turned on `--live-manifest-calls true` which works nicely except for runJobManifests occassionally failing most likely due to timeout (job itself completes just fine).

**Comment by 23doors** [comment]
I found `redis.poll.timeoutSeconds` setting. Increasing it to 120 seems to have stopped the timeouts (so far) and lowered the load to 0.4-0.9. Seems that 20 namespaces with 4 clusters are too much for 3 replicas. Does it sound right though?

**Comment by 23doors** [comment]
One update, job issues seems to not be related to clouddriver timeouts. Will open a separate issue for that once I figure it out better.

**Comment by ezimanyi** [comment]
@23doors : From the above description it looks like you might have deployed multiple replicas of clouddriver?

In general, there should only be one caching clouddriver running at a time as there is no mechanism for work sharing between multiple replicas.  Increasing the number of replicas might actually reduce performance if these conflict in their updates.  You *can* set up HA clouddriver as described [here](https://www.spinnaker.io/reference/halyard/high-availability/#ha-clouddriver) which will split up different types of work between the replicas.  But given the size of your deployment I'd suggest just starting with a single clouddriver replica, but giving it sufficient CPU and memory (maybe start with 2 CPU and adjust as necessary).

We've had users succesfully operating at significantly larger scale than what you describe above, so with proper tuning you should definitely be able to get this to work!  Let me know if the above helps!  Thanks!
