### ISSUE TITLE
No container list when creating new server group (1.16.3)

### ISSUE THREAD

**Issue by djverlinden** [spinnaker/spinnaker#5048]
### Cloud Provider(s):
Kubernetes
docker-registry : GCE
ci: jenkins

### Environment:
Halyard: version-1.24.0
Spinnaker: version: 1.16.3
Kubernetes version: v1.16.2

### Feature Area:
UI

### Description:
When I type the name of a container to use in the Create New Server Group form, I should be able to select that container

### Steps to Reproduce:
- install using halyard
- install applications
- Create a new server group

### Additional Details:

same issue as https://github.com/spinnaker/spinnaker/issues/2148

- Tried in firefox, chrome and safari
- REST calls to the api appear to return results, but the dropdown is empty

<img width="927" alt="2019-10-21" src="https://user-images.githubusercontent.com/107640/67243489-f1f1d280-f457-11e9-9247-85922b9b37ea.png">

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by maggieneterval** [comment]
Hey @djverlinden, thanks for the detailed issue report! I've submitted a fix for this, which will be released with Spinnaker 1.17.
