### ISSUE TITLE
When running GCB with definition (cloudbuild.yaml) from artifacts, SpEL is not evaluated

### ISSUE THREAD

**Issue by mdk194** [spinnaker/spinnaker#5051]
### Issue Summary:
When running GDB (google cloud build) with definition file (cloudbuild.yaml pushing from git f.ex) from artifacts, SpEL is not evaluated. However, when GCB definition is defined as **text** directly in spinnaker, SpEL is evaluated.

I think spinnaker should download the cloudbuild.yaml from artifacts then evaluate SpEL before sending to GCB.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Running GCB from spinnaker

### Feature Area:
Pipelines

### Description:
Define GCB substitutions with value is SpEL, for example:
If the GCB build configuration is defined as text directly in spinnaker -> SpEL is evaluated.
If the GCB build configuration is passed as file from artifacts -> SpEL is **not** evaluated.

### Steps to Reproduce:
1. GCB definition with substitution to get the current stage name:
```
steps:
  - args:
      - '-c'
      - |
        set -e
        if [[ "${_SPINNAKER_CURRENT_STAGE_NAME}" == *"terraform plan"* ]]; then
            echo Running terraform plan
        fi
        if [[ "${_SPINNAKER_CURRENT_STAGE_NAME}" == *"terraform apply"* ]]; then
            echo Running terraform apply
        fi
    entrypoint: bash
    name: 'gcr.io/${PROJECT_ID}/terraform'
substitutions:
  _SPINNAKER_CURRENT_STAGE_NAME: '${ #currentStage()["name"].toString() }'
```
2. Create `terraform plan` stage to run GCB
3. Put above GCB build definition as **text** directly in spinnaker pipeline configuration.
4. The SpEL: `'${ #currentStage()["name"].toString() }'` will be evaluated making the above definition when running become:
```
steps:
  - args:
      - '-c'
      - |
        set -e
        if [[ "terraform plan" == *"terraform plan"* ]]; then
            echo Running terraform plan
        fi
        if [[ "terraform plan" == *"terraform apply"* ]]; then
            echo Running terraform apply
        fi
```
5. So with GCB build definition defined as **text**, the GCB work as expected.
6. Now store above GCB definition as file in git repo and push to spinnaker as artifact, then configure GCB stage to use the artifact file instead.
7. With GCB definition passed as artifact, the above GCB will become:
```
steps:
  - args:
      - '-c'
      - |
        set -e
        if [[ "${ #currentStage()["name"].toString() }" == *"terraform plan"* ]]; then
            echo Running terraform plan
        fi
        if [[ "${ #currentStage()["name"].toString() }" == *"terraform apply"* ]]; then
            echo Running terraform apply
        fi
```

### Additional Details:

![gcb_text](https://user-images.githubusercontent.com/4249480/67282056-076c0880-f4fb-11e9-843b-3089012d7dbf.png)
![gcb_artifact](https://user-images.githubusercontent.com/4249480/67282059-0935cc00-f4fb-11e9-9011-6ff36761a226.png)
![gcb_artifact_1](https://user-images.githubusercontent.com/4249480/67282276-99741100-f4fb-11e9-9187-7aca59936dac.png)

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by maggieneterval** [comment]
Hey @mdk194, thanks for opening this detailed issue! I've submitted a fix which will go out with the next version of Spinnaker (1.17).
