### ISSUE TITLE
Still application is not directly accessible after creation in latest 1.16

### ISSUE THREAD

**Issue by JamieChe** [spinnaker/spinnaker#5063]
### Issue Summary:
Bug reappear in both 1.15 and 1.16: UI reports "Application Not Found" after creating a new application 

### Cloud Provider(s):
kubernetes

### Environment:
Spinnaker 1.15.5 and 1.16.4
Minio for front50 S3 storage
Ldap for authentication

### Feature Area:
fiat

### Description:
This bug was described and fixed several months ago https://github.com/spinnaker/spinnaker/issues/4276. 
It worked fine in 1.13.10, but when we upgraded Spinnaker to 1.15.5, we met it again.  We tested with latest Spinnaker 1.16.4 but find this issue is still there. 
I know the fiat option "fiat.allowAccessToUnknownApplications: true" could bypass the issue, but we just want to know whether this issue would be considered as bug and planed to be fixed. 

### Steps to Reproduce:
1. check profiles/fiat-local.yml, you are NOT in admin role and  allowAccessToUnknownApplications is disabled. 
```
fiat:
  admin:
    roles:
      - <NOT-Your-Group>
fiat.allowAccessToUnknownApplications: false
```
2. create a new application with simple name and email input. 
3. You would see "Application Not Found" in UI

**Comment by AbdulRahmanAlHamali** [comment]
I think calls made to `createApplication` need to be followed by a sync roles

**Comment by AbdulRahmanAlHamali** [comment]
I think this should fix it:
https://github.com/spinnaker/front50/pull/619
