### ISSUE TITLE
Show original expression in check precondition for easier debugging.

### ISSUE THREAD

**Issue by evansb** [spinnaker/spinnaker#5097]
### Issue Summary:

Currently here is what we see if `CheckPrecondition (expression)` stage failed. It's not very helpful for debugging as the original expression has been reduced to `false`.

![Screenshot 2019-11-05 at 12 37 21 PM](https://user-images.githubusercontent.com/5389670/68179134-a0a22100-ffc9-11e9-8c5d-1ab8ebc8d02b.png)

Rather than having engineers need to consult the pipeline definition to get the original expression, I suggest to show it in the UI.

### Cloud Provider(s):
All

### Environment:
All

### Feature Area:

UI

### Description:

Expected Behaviour: The original expression that evaluates to false is shown
Actual Behaviour: It is not shown.

### Steps to Reproduce:

Have a failing Check Precondition using Expression Preconditions.

**Comment by evansb** [comment]
Also some observation: Both `${expression}` and `expression` are permitted but they actually behave differently (the former is evaluated by `StageHandler` and the latter is evaluated by the `ExpressionPreconditionTask`. I think that in the tooltip we can say that expression should not be wrapped in `${...}`

**Comment by maggieneterval** [comment]
Hey @evansb, thanks for opening this issue! It would definitely be a better debugging experience if the entire expression were surfaced in this error message. I'm going to add this issue to the Google OSS team's backlog, but this will likely not be an immediate-term priority, so wanted to also highlight that I've added a beginner-friendly label and would be happy to help a community member open a PR to resolve this in the meantime!

**Comment by sgarlick987** [comment]
Looks like the expression is explicitly excluded in the gui right now. See

https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/CheckPreconditionsExecutionDetails.tsx#L20

I tested removing it, and it would look like this

![image](https://user-images.githubusercontent.com/5222700/71492799-fb0c7080-2807-11ea-931e-5e5412352b7d.png)

If it sounds fine to everyone I can submit a PR to show it. Also is there a test somewhere I should update? I'm not seeing one in https://github.com/spinnaker/deck/tree/master/test/functional/tests/core at quick glance.

**Comment by maggieneterval** [comment]
@sgarlick987 thanks so much for looking into this; I didn't realize we were explicitly excluding the expression from the execution details. @christopherthielen or @erikmunson, do you happen to know if there was some reason _not_ to show the expression here (for example, does Netflix often use very long precondition expressions that it would be unhelpful to try to render here)?

For anyone else who encounters this issue, I also wanted to highlight the lovely new [debugging-friendly UI](https://github.com/spinnaker/deck/pull/7628) that @christopherthielen added for the Evaluate Variables stage: if you migrate your SpEL expressions to this stage, you can take advantage of both previewing the result of your SpEL expressions against prior executions while composing a pipeline, and a prettier debugging experience when trying to determine what a given expression evaluated to after a pipeline run.

**Comment by sgarlick987** [comment]
@maggieneterval would it make sense to make the expression itself a link/popup dialog so that if the expressions are long they wouldn't pollute the page but still let users easily view the full expression if needed?

**Comment by maggieneterval** [comment]
@sgarlick987 that could work, a link/popup is what we use to display the full manifest YAML in the execution details for the Deploy, Patch, and Bake Manifest stages.

**Comment by sgarlick987** [comment]
Here's what it would look like using that. 

![image](https://user-images.githubusercontent.com/5222700/71601091-f6a1c980-2b1f-11ea-8edb-5c78b0c3e5ba.png)

Right now its using the exact module as used in the display manifest yaml. I'm not sure if we'd really want to make it any different, possibly the text box doesn't need to be as large or maybe something different than textarea? And maybe refactor it into something more generic for other things that want a similar popup?

**Comment by christopherthielen** [comment]
> @christopherthielen or @erikmunson, do you happen to know if there was some reason not to show the expression here (for example, does Netflix often use very long precondition expressions that it would be unhelpful to try to render here)?

I think that the original expression was itself also getting evaluated by spel, causing the expression and result to be the same thing.  If that's not the case any longer, I think it's fine to show the original expression inline.

**Comment by evansb** [comment]
> I think that the original expression was itself also getting evaluated by spel, causing the expression and result to be the same thing. If that's not the case any longer, I think it's fine to show the original expression inline.

Make sure you don't have the wrapper `${...}` in the stage configuration, i.e don't write `${parameters['a'] == 'b'}`, just `parameters['a'] == 'b'`.
