### ISSUE TITLE
Embedded Artifacts Default Content are Uneditable

### ISSUE THREAD

**Issue by zackb** [spinnaker/spinnaker#5102]
### Issue Summary:
After creating an embedded artifact, I am unable to edit the Contents field of the default artifact.

This worked in 1.12 but not in 1.16.x or 1.17.0

### Cloud Provider(s):
GKE

### Environment:
Halyard

### Feature Area:
Deck

### Description:
After adding an embedded artifact to a pipeline configuration, you are unable to edit the text in the "Contents" textarea of the "Default" artifact. When typing in the textarea changes are not reflected in the UI. However, if you change one character at a time, pressing "Save Changes" after each character, the changes persist on page reload.

### Steps to Reproduce:
1. Create an artifact of type "Embedded Artifact"
2. Check the "Use Default Artifact" checkbox
3. Select "embedded-artifact" as Account
4. In the "Contents" text area enter some text
5. Click "Save Changes"
6. Reload the page - "Contents" of the Embedded Artifact is not editable

### Additional Details:
<img width="936" alt="Screen Shot 2019-11-05 at 10 46 59 AM" src="https://user-images.githubusercontent.com/422599/68239672-3df85780-ffc0-11e9-9f83-258368207d47.png">

**Comment by zackb** [comment]
Wow! Thanks!

**Comment by maggieneterval** [comment]
No problem -- we'll cherry-pick the fix into 1.17, so it will come out with the next patch release.
