### ISSUE TITLE
SpEl function #triggerResolvedArtifact() doesn't work

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#5105]
### Issue Summary:

https://github.com/spinnaker/orca/pull/3118 is listed as one of the [new features in Spinnaker 1.17](https://www.spinnaker.io/community/releases/versions/1-17-0-changelog#features-8), but it doesn't work: The expression doesn't get resolved when passed a valid artifact name.

### Cloud Provider(s):

GCP

### Environment:

Spinnaker 1.17. Spinnaker for GCP.

### Feature Area:

Orca

### Description:

I'm trying to use this function in a GCB stage, to hold the URL to a GCS object that should be downloaded within that GCB build. The expression I'm using is `${#triggerResolvedArtifact("the-artifact")["reference"]}`, and I've confirmed that the artifact was indeed resolved in the pipeline execution.

I've inspected the failing stage in the pipeline payload provided by Gate and I've found the following:

```
        "exception": {
          "details": {
            "error": "Failed Expression Evaluation",
            "errors": [
              "Failed to evaluate { #triggerResolvedArtifact( #root.execution, \"the-artifact\")[\"reference\"] } java.util.LinkedHashMap cannot be cast to com.netflix.spinnaker.kork.artifacts.model.ExpectedArtifact - EL1023E: A problem occurred whilst attempting to invoke the function 'triggerResolvedArtifact': 'null'"
            ]
          }
        }
```

Note I'm still able to use `${trigger.resolvedExpectedArtifacts[N].boundArtifact.reference}`, where `N` is the index of the artifact.

### Steps to Reproduce:

Create a pipeline stage that uses `#triggerResolvedArtifact()`.

### Additional Details:

It was mentioned on https://github.com/spinnaker/orca/pull/3118#issuecomment-530034634 back in September that there was an issue with new functions and as a workaround they had to be called with `execution` as the first argument. I tried that (`${#triggerResolvedArtifact(execution, 'the-artifact')}`) but got a different error:

```
        "exception": {
          "details": {
            "error": "Failed Expression Evaluation",
            "errors": [
              "Failed to evaluate {#triggerResolvedArtifact( #root.execution, execution, \"the-artifact\")[\"reference\"]} EL1014E: Incorrect number of arguments for function, 3 supplied but function takes 2"
            ]
          }
        }
```

Which I guess makes sense.

**Comment by marchello2000** [comment]
@evansb can you take a look please?

**Comment by evansb** [comment]
Will take a look today

**Comment by evansb** [comment]
Seems like the root cause is quite deep. I traced the thrown class cast exception to the `TriggerDeserializer` in core module. There are two unsafe casts there which breaks the strongly typed guarantee. More details in the PR above.

**Comment by evansb** [comment]
Alternative fix (if changing the core logic is deemede to risky), is to re-parse the trigger like the following, but this fix will remove the need to do something like this elsewhere.

https://github.com/spinnaker/orca/blob/3d040623dda7d3b7c2c6bf0fa8dd4f7691a48945/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java#L132

**Comment by gnarea** [comment]
@evansb, thanks for looking into this and creating a PR to fix it.

https://github.com/spinnaker/orca/pull/3285 has been merged and seems to be scheduled to be released in v1.18 so I'm happy to close this issue if that PR is all that's needed to fix the issue.

**Comment by evansb** [comment]
@gnarea Yup I tested the fix in our Spinnaker installation and it seems to be working now. 🙏

**Comment by gnarea** [comment]
Great. Thanks!
