### ISSUE TITLE
Upgrade Spring Boot to 2.2.2

### ISSUE THREAD

**Issue by scottfrederick** [spinnaker/spinnaker#5134]
### Issue Summary
 Upgrade the Spring Boot dependency managed by Kork from `2.1.7` to `2.2.2`. This upgrade should provide performance improvements in application startup, including significant improvements when very large configuration YAML files are loaded (see #4938).

### Description

Boot itself includes one backward-incompatible code change

* `XxxxHealthIndicatorAutoConfiguration` renamed to `XxxxHealthContributorAutoConfiguration`

The Boot upgrade brings in newer versions of some Boot-managed dependencies that require code changes. 

Jackson upgrade `com.fasterxml.jackson.core:*` from `2.9.9.3` to `2.10.0`

* Return types of methods that take a `TypeReference` are more strongly typed

Jedis upgrade `redis.clients:jedis` from `2.9.3` to `3.1.0`

* Packaging changes (especially `XxxCommand` classes)
* Various backward-incompatible API changes
* Previously deprecated methods removed

The Jedis upgrade necessitates an upgrade to `com.netflix.dyno:dyno-jedis:1.7.2`

* Various backward-incompatible API changes

Liquibase upgrade to `org.liquibase:liquibase-core:3.8.0`

* Backward-incompatible API change

### Process

This upgrade requires a coordinated process of updating kork, then upgrading the version of kork in all services along with any other code changes required for each service. 

- [x] kork - [PR](https://github.com/spinnaker/kork/pull/419)
- [x] clouddriver - [PR](https://github.com/spinnaker/clouddriver/pull/4168)
- [x] echo - [PR](https://github.com/spinnaker/echo/pull/702)
- [x] fiat - [PR](https://github.com/spinnaker/fiat/pull/510)
- [x] front50 - can be auto-bumped, no code changes required
- [x] gate - [PR](https://github.com/spinnaker/gate/pull/966)
- [x] igor - [PR](https://github.com/spinnaker/igor/pull/554)
- [x] kayenta - [PR](https://github.com/spinnaker/kayenta/pull/637)
- [x] keiko - [PR](https://github.com/spinnaker/keiko/pull/72)
- [x] orca - [PR](https://github.com/spinnaker/orca/pull/3333)
- [x] rosco - [PR](https://github.com/spinnaker/rosco/pull/468)
- [x] halyard - can be auto-bumped, no code changes required

**Comment by cfieber** [comment]
What is your thinking on order of upgrades? 

Can we do all the necessary dependency updates before releasing kork on boot 2.2 or are any of those incompatible with boot 2.1?

**Comment by scottfrederick** [comment]
@cfieber It appears that many services will need the kork/Boot upgrade and code changes at the same time. The Jedis and Jackson upgrades are making this a bit painful. In addition to clouddriver, I know echo and orca need code changes. Front50 is the only one I've seen so far that will upgrade cleanly. 

I don't think the order matters, with the way kork manages the dependencies now we'll need to merge the kork PR, then bump kork in the services at the same time as the related code changes are merged.

**Comment by cfieber** [comment]
We could update kork to bump Jackson , redis and liquibase versions and get that pushed through then go to boot 2.2 dependencies.

I'd like to if possible avoid the state of an extended period where the latest kork version that isn't in a compatible state with all of its consumers

**Comment by scottfrederick** [comment]
> I'd like to if possible avoid the state of an extended period where the latest kork version that isn't in a compatible state with all of its consumers

Yes, that makes things difficult during an upgrade process like this. I think this is the first time we've done a big dependency upgrade like this since the Boot 2 upgrade and the changes to kork dependency management that were introduced then, and I'm hoping we can learn from this to make the process easier. 

> We could update kork to bump Jackson , redis and liquibase versions and get that pushed through then go to boot 2.2 dependencies.

I don't think that helps. If kork is managing the Jedis and Jackson dependencies and we change them separately from Boot, we'll have the same problem. I've only seen one small code change required that's directly related to Boot, everything else is related to these other dependencies.

**Comment by Jammy-Louie** [comment]
There appears to be an issue with a dependency in `igor` when we are performing this upgrade.

Jackson was bumped in this upgrade from 2.9.9.3 to 2.10.0

which is causing an exception with the dependency `google-api-services-cloudbuild`.

```
number type formatted as a JSON number cannot use @JsonString annotation
```

in StorageSource.java  due to:
```
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long generation;
```

**Comment by robzienert** [comment]
Looks like orca is the only outstanding service! 🎉
