### ISSUE TITLE
Stages that run a child pipeline should not show "View Pipeline Execution" button before the stage starts 

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [spinnaker/spinnaker#5141]
### Issue Summary:
![image](https://user-images.githubusercontent.com/16646600/69151781-503ac100-0aa9-11ea-87a5-a65e5dd3a74c.png)

As the image above shows, the stages that run other pipelines are showing an un-clickable "View Pipeline Execution" button when they're not yet started. The button is only clickable if the stage has already started. 

This is confusing for users. I think it's better to either hide the button in that case, or to clearly disable the button with a useful tooltip.

### Feature Area:
Deck, UX

**Comment by maggieneterval** [comment]
Hey @AbdulRahmanAlHamali, I appreciate you opening this issue and 100% agree that unclickable buttons should be hidden or disabled. I'm going to add this issue to the Google OSS team's backlog, but this will likely not be an immediate-term priority, so wanted to also highlight that I've added a beginner-friendly label and would be happy to help a community member open a PR to resolve this in the meantime!

**Comment by AbdulRahmanAlHamali** [comment]
Thank you Maggie, 

Yes I agree that it is not high-priority. I just thought to log it here as I found it a bit annoying :)

**Comment by erikmunson** [comment]
Thanks for reporting! I _believe_ this was fixed via https://github.com/spinnaker/deck/pull/7563 — which appears to be in the 1.17 release. Not sure which release you're running, but will close this for now and have you re-open if you see the same behavior on 1.17 or above.

**Comment by AbdulRahmanAlHamali** [comment]
yup. Confirmed
