### ISSUE TITLE
Bake is failing for AWS accounts.

### ISSUE THREAD

**Issue by sudhakaropsmx** [spinnaker/spinnaker#5159]
### Issue Summary:
Bake is failing for AWS accounts in Distributed Spinnaker environment.
### Cloud Provider(s):
  AWS

### Environment:
Distributed Spinnaker installation. 

### Feature Area:
Bake

### Description:
Bake stage is failing with the following error because of non availability of AWS credentials (access key id and secret access key) in rosco pod.
```
Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Builds finished but no artifacts were created.
```
### Steps to Reproduce:
1. Build an application with deb package in Jenkins .
2. configure spinnaker to pick the deb package and bake. 
3. Run pipeline
So Bake stage fails with the error mentioned above.

**Comment by kirangodishala** [comment]
For Debian and LocalGit Spinnaker installations, we don't get to see this issue as all the services run in the same machine and the accessKeyId and secretAccessKey provided ouside the bakeryDefaults would create ~/.aws/credentials which then be used by rosco. But for distributed Spinnaker installation, aws credentials must be supplied insdie bakeryDefaults for rosco to bake an ami. Using the following hal command, we can achieve this:
```
hal config provider aws bakery edit --aws-access-key  xxxxxxxx --aws-secret-key xxxxxxxxx
```

**Comment by sudhakaropsmx** [comment]
The above comments will solve the issue. Hence closing.
