### ISSUE TITLE
[Feature] blue green deployment on "Patch (Manifest)"

### ISSUE THREAD

**Issue by itonito** [spinnaker/spinnaker#5166]
### Issue Summary:
Currently Red/Black deployment is only available fro the Deploy (Manifest) Configuration, however there are cases in which it is needed in Patch (Manifest). One such situation is when docker image update is needed on existing service.
Make Red/Black deployment available for Patch manifest so that docker image update is Red/Black deployment compliant. 

### Cloud Provider(s):
Kubernetes v2

### Environment:
Spinnaker application's Pipelines Configurations, Patch (Manifest) Configuration section.

### Feature Area:
Patch (Manifest) Configuration section
* Rollout Strategy Options
** Strategy (Red/Black)

### Description:

Currently Red/Black deployment is only available fro the Deploy (Manifest) Configuration, however there are cases in which it is needed in Patch (Manifest). One such situation is when docker image update is needed on existing service.

Make Red/Black deployment available for Patch manifest so that docker image update is done through Red/Black deployment. 

### Additional Details:

Rollout Strategies 
https://www.spinnaker.io/guides/user/kubernetes-v2/rollout-strategies/

**Comment by maggieneterval** [comment]
Hey @itonito, thanks for taking the time to open this feature request!

Is there a reason you would prefer to patch in your updated container image rather than simply re-applying using the Deploy (Manifest) stage?

**Comment by itonito** [comment]
@maggieneterval I currently have a CI/CD pipeline that deploys an updated docker image. When the only update required for the service is the docker image, it makes sense to execute "Patch (Manifest)" (updates the specified docker image) rather than to execute "Deploy (Manifest)" which updates the entire manifest.  In fact, most of the existing pipelines that we have in our CI/CD pipelines executes "Patch (Manifest)" as all it needs is the update on the container image. 

By enabling blue green deployment for "Patch (Manifest)", it becomes possible for the existing pipelines to do the read/black deployment without converting the existing "Patch (Manifest)" stage to "Deploy (Manifest)" stage.

**Comment by maggieneterval** [comment]
Hi @itonito, sorry for the delayed followup. We discussed this feature request at our latest Kubernetes SIG issue triage meeting, and decided that we will not be implementing it because our current recommendation is to use the Deploy (Manifest) stage even when only updating a workload's Docker image. Going to close this issue for now!
