### ISSUE TITLE
Codelabs example not working due to a missing image 

### ISSUE THREAD

**Issue by darrengarvey** [spinnaker/spinnaker#5169]
### Issue Summary: 

The following codelabs example is broken because a required docker image isn't available in gcr.io.

Example: https://codelabs.developers.google.com/codelabs/cloud-spinnaker-kubernetes-cd
Image: https://gcr.io/spinnaker-marketplace/backend

### Cloud Provider(s):

GKE

### Feature Area:

Examples
### Steps to Reproduce:

Follow steps on: https://codelabs.developers.google.com/codelabs/cloud-spinnaker-kubernetes-cd

Running `./setup.sh` appears to succeed but fails to start up the application as one of the required images is missing.

Namely:
`gcloud docker -- pull gcr.io/spinnaker-marketplace/backend`
Gives:
`Error response from daemon: manifest for gcr.io/spinnaker-marketplace/backend:latest not found`

The image is missing from the repo.

**Comment by leoytelus** [comment]
+1. The registry gcr.io/spinnaker-marketplace/ does not have `backend` repository at all. It is impossible to guess what is the new name of the repository, in condition there is one.

**Comment by maggieneterval** [comment]
Hey @darrengarvey and @leoytelus, so sorry about that, it must have been super annoying to not be able to complete the codelab. I'm not sure how the `backend` image got deleted from the spinnaker-marketplace registry, but I've just re-pushed it. Please let me know if you run into any further issues with the codelab!

**Comment by darrengarvey** [comment]
Awesome, thanks. Future sailors will be grateful for this offering from the Ocean.
