### ISSUE TITLE
Kubernetes V2: Provide ability to control order of deployment

### ISSUE THREAD

**Issue by agoyal-sfdc** [spinnaker/spinnaker#5182]
### Issue Summary:
Currently in Spinnaker, when you Bake a set of Helm charts, they get baked into a single "file", and the `Deploy (Manifest)` stage applies all the manifests together.

### Cloud Provider(s):
Kubernetes V2

### Feature Area:
Deploy Manifest

### Description:
Currently in Spinnaker, when you Bake a set of Helm charts, they get baked into a single "file", and the `Deploy (Manifest)` stage applies all the manifests together. This can be problematic when you have a sharded service (one that is composed of several different, but closely related services) in which ordering is important, especially during upgrades (since you don't want to take down the whole service -like ours, a DB - to upgrade parts of it). One way to do this is to have separate Helm charts for each of the sub-services, but for services so closely related, that doesn't quite work since there's so much in common that it would become a nightmare operationally making changes to all Helm charts separately.

To work around this, we have come up with some custom logic to "split" the generated manifests (using a job) into "manifest groups" (sets of manifests that can be applied together). We consume the manifests baked by Spinnaker, and based on a set of pre-defined manifest groups, we split them, and combine them into smaller groups. Here's a snippet of the core logic:
```
    def output_to_spinnaker(self):
        spinnaker_output = {"artifacts":[]}
        # Each manifest group will need to be a separate artifact.
        for name, manifest in self.manifest_groups.items():
            # Artifacts that are passed between stages in Spinnaker must be base64 encoded
            b64_manifest = base64.b64encode(manifest.encode()).decode()

            # This is the format expected by Spinnaker for each embedded artifact.
            # ref: https://www.spinnaker.io/reference/artifacts/types/embedded-base64/
            artifact = {"type": "embedded/base64", "reference": b64_manifest, "name": name}
            spinnaker_output["artifacts"].append(artifact)

        # For Spinnaker to parse the output of this container, it must be printed to stdout
        # with the key 'SPINNAKER_CONFIG_JSON' being set to the json produced above.
        # ref: https://www.spinnaker.io/guides/user/kubernetes-v2/run-job-manifest/
        print("SPINNAKER_CONFIG_JSON={}".format(json.dumps(spinnaker_output)))
```
In this way, we can read the outputted base64 artifacts, and deploy them in the order of our choosing in separate stages, each of which only deploys one manifest group. It would be great to have native support to control order of deployment.

**Comment by ezimanyi** [comment]
We discussed this at the SIG yesterday, and decided that implementing #3695 would solve this problem (as well as some other problems).  So I'll close this in favor of the other issue.  Thanks a lot for the detailed use case and discussion at the SIG!
