### ISSUE TITLE
Spinnaker bake configuration trusty (v14.04) deprecated

### ISSUE THREAD

**Issue by itsmetommy** [spinnaker/spinnaker#5190]
### Issue Summary:

Bake configuration error when selecting trusty (v14.04) within the Spinnaker Bake Pipeline.

### Cloud Provider(s):

GCP

### Environment:

Halyard 1.17.2

### Feature Area:

Spinnaker

### Description:

It looks like google has deprecated **ubuntu-1404** images. This means that all bakes with the default **trusty (v14.04)** image selected will fail.

**Bake error:**

`==> googlecompute: Error getting source image for instance creation: Could not find image, ubuntu-1404-lts`

### Steps to Reproduce:

1. Create Pipeline
2. Select Stage Name: Bake
3. Select Base OS: trusty (v14.04)
4. Select Save Changes
5. Select Pipelines
6. Select Start Manual Execution 

### Additional Details:

`gcloud compute images list --show-deprecated | grep ubuntu-1404-lts`

**Bake Configuration:**

![bake-configuration-ubuntu-14 04](https://user-images.githubusercontent.com/7635481/70003104-01fcd780-1517-11ea-8d0a-f5ef8f688c8a.png)

**GCP Image Search for ubuntu-1404:**

![gcp-ubuntu-image-search](https://user-images.githubusercontent.com/7635481/70003105-01fcd780-1517-11ea-9282-8acdc165379b.png)

The last time it worked for me was on **2019-11-27 18:17:28 PST**.

![bake-last-success](https://user-images.githubusercontent.com/7635481/70003106-01fcd780-1517-11ea-9a02-0155c415a169.png)

**Comment by ttomsu** [comment]
We saw this in our night builds and it blocked the release of 1.17. Assuming the tests pass a fix should go out tomorrow for 1.17, 1.16, and 1.15

**Comment by ttomsu** [comment]
Releases went out yesterday. Please let us know if you have other issues with baking.

**Comment by ttomsu** [comment]
I'll add some more color to what was actually fixed: For current release (1.15.x, 1.16.x, and 1.17.x) the `trusty` image uses the last published image (see https://github.com/spinnaker/rosco/pull/476) to continue current functionality. Going forward on `master`, `trusty` was removed and `bionic` was added, and if I remember to do so in April 2020, [`focal`](https://wiki.ubuntu.com/Releases) will be added.
