### ISSUE TITLE
error 404 

### ISSUE THREAD

**Issue by SergioTeco** [spinnaker/spinnaker#5193]
Page: [/setup/install/providers/kubernetes-v2/](https://www.spinnaker.io/setup/install/providers/kubernetes-v2/)

Feedback: error 404 in kubectl apply --context $CONTEXT \
    -f https://spinnaker.io/downloads/kubernetes/service-account.yml , it seems that the file is not longer available

**Comment by ezimanyi** [comment]
@SergioTeco : It looks like that file is still there---I was able to open it by clicking the link above.  Please re-open if you're still seeing the same issue?
