### ISSUE TITLE
Cloud Providers field is missing on new Application window 

### ISSUE THREAD

**Issue by hparashu** [spinnaker/spinnaker#5200]
### Issue Summary:
Hello,

I have installed Spinnaker 1.16.6 on VM (Ubuntu 16.04) running in Oracle OCI.

I access Spinnaker UI and try to create new application and I don’t see Cloud Providers field is missing on the new application window ;
![image](https://user-images.githubusercontent.com/46400851/70221137-c90a7000-176d-11ea-88f1-7d4eef130ec1.png)

I am following the below link and I have created storage and oracle account before I install Spinnaker -
https://www.spinnaker.io/guides/tutorials/codelabs/oci-source-to-prod/ 
![image](https://user-images.githubusercontent.com/46400851/70221258-0969ee00-176e-11ea-86ee-a47d35b7e3d6.png)

I tried with Spinnaker 1.17.3 and saw the same issue.

Any known issue / workaround to get the Cloud Providers field ? Thank you

### Cloud Provider(s):
Oracle OCI.

### Environment:
VM (Ubuntu 16.04) running in Oracle OCI.

**Comment by christopherthielen** [comment]
If you have only configured a single provider (i.e., Oracle OCI), you will not see the Cloud Providers field.  In your case Spinnaker will default all UI operations to the Oracle cloud provider.  

In contrast, when multiple cloud providers are present (and configured for the app), Spinnaker will present a modal during operations (such as "create server group") that asks which of the cloud providers the operation should use.
