### ISSUE TITLE
firelensConfiguration removed from ECS task definition artifacts

### ISSUE THREAD

**Issue by nickcatal** [spinnaker/spinnaker#5203]
### Issue Summary:

When using the ECS integration using an artifact task definition, the object `firelensConfiguration` is stripped out of the firelens container in `containerDefinitions`.

### Cloud Provider(s):

AWS ECS

### Environment:

I'm using Spinnaker 1.17.2 on an Ubuntu 18 EC2 instance to deploy docker images stored in ECR to ECS Fargate. I'm storing my container definition artifacts on S3.

### Feature Area:

Amazon Web Services Elastic Container Service deployment

### Description:

In order to use the Firelens logger on ECS you need to have the `aws-for-fluent-bit` container added to `containerDefinitions` in your task definition. Inside that container you need an object called `firelensConfiguration`.

When spinnaker sends the final task definition to AWS, that object is stripped out. If you're attempting to use firelens in another container, AWS will return the error `When awsfirelens log driver is specified in log configuration, a firelens configuration object must be configured in one of the containers.` and your deployment will fail.

### Steps to Reproduce:

Add the following to `containerDefinitions` in your ECS definition artifact.

```json
    {
      "essential": true,
      "image": "906394416424.dkr.ecr.us-west-2.amazonaws.com/aws-for-fluent-bit:latest",
      "name": "log_router",
      "firelensConfiguration": {
        "type": "fluentbit"
      }
    }
```

Then deploy to AWS.

If you go into your AWS console and look at the JSON of the task definition, you'll see that  `firelensConfiguration` will be set to `null`

If you attempt to use Firelens in another container definition, you'll get the AWS error `When awsfirelens log driver is specified in log configuration, a firelens configuration object must be configured in one of the containers.`

### Additional Details:

My quick glance at the code referenced in https://github.com/spinnaker/spinnaker/issues/4070 didn't seem to point to a cause, but I'm not a java developer by trade.

Here's a screenshot of the error:

![Screenshot 2019-12-05 14 54 14](https://user-images.githubusercontent.com/474748/70268798-29e67800-176f-11ea-92cc-81a6a69d503a.png)

**Comment by nickcatal** [comment]
Update: After a pass through the ECS code it looks like the problem is that https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java is missing `Map<String, String> firelensConfiguration` since the `firelensConfiguration` configuration is new.

But someone else will need to verify I'm reading this correctly.

Assuming I'm reading this right, I'm thinking clouddriver could just accept arbitrary new fields inside a task definition, or we can explicitly add `firelensConfiguration`. Not sure which route makes more sense.

cc @allisaurus @clareliguori

**Comment by clareliguori** [comment]
If you are using task definition artifacts, the attributes in CreateServerGroupDescription are not used to parse the artifact.  The artifact is parsed using the RegisterTaskDefinitionRequest class in the version of the AWS SDK that is included in your version of Spinnaker.
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L308

So since the version of the AWS SDK included in Spinnaker 1.17.2 is too old to have firelensConfiguration, then it can't be parsed from the task definition.

@allisaurus bumped the SDK version recently, so it will be included in the next version of Spinnaker (1.18): https://github.com/spinnaker/kork/commit/a81d4f219bc2f446181c4f4792f21aaa1d144c77

**Comment by clareliguori** [comment]
It does sound like there's a bug here, which is that the ECS provider should have refused the task definition artifact, instead of dropping unknown properties silently (in this case, firelensConfiguration).  It looks like the ObjectMapper needs to have `FAIL_ON_UNKNOWN_PROPERTIES` enabled.

**Comment by nickcatal** [comment]
@clareliguori thanks for this (and everything)! will keep an eye out for the new version so I can start using firelens.
