### ISSUE TITLE
Provider support for VMWare - VCenter or Vcloud director

### ISSUE THREAD

**Issue by githubvick** [spinnaker/spinnaker#5207]
Page: /setup/install/providers/

Feedback:
I would like to know if you have anything in pipeline to provide support for VCenter or Vcloud director?

Thanks,

**Comment by ezimanyi** [comment]
I'm not aware of any current plan to add these cloud providers.  In general, the process for adding a cloud provider is [here](https://github.com/spinnaker/community/blob/master/cloud-provider-requirements.md).  Effectively this would need to be contributed by an organization with an active stake in the project that plans to maintain it.  If you'd like to propose adding this provder (and meet the requirements on that list) then please open an issue in the [spinnaker/community](https://github.com/spinnaker/community) repo using the 'New Cloud Provider' template.
