### ISSUE TITLE
Empty `kubeconfig-file` causes NullPointerException when running `hal deploy apply`

### ISSUE THREAD

**Issue by lcareto** [spinnaker/spinnaker#5224]
### Issue Summary:
After creating an **K8s account** with an empty **kubeconfig-file**, deployment failed with `NullPointerException` without error details.

### Cloud Provider(s):
Kubernetes

### Environment:
GKE

### Feature Area:
halyard config for kubernetes account

### Steps to Reproduce:
Assuming you have a running Spinnaker already deployed
- Create an empty kubeconfig-file
`touch /home/spinnaker/.kube/empty_config`

- Create an account
```
hal config provider kubernetes account add foo \
--provider-version v2 \
--kubeconfig-file /home/spinnaker/.kube/empty_config
```

- Deploy
`hal deploy apply`

**===> RESULT**
```
spinnaker@spinnaker-spinnaker-halyard-0:/$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.NullPointerException

- Failed to deploy Spinnaker.
```

### Expected Behaviour:
Even though it's a configuration error, empty file scenario must be handled properly to avoid unexpected NPE.

---

**Comment by ezimanyi** [comment]
Agreed that the error message is not very helpful here; perhaps replacing it with a new `IllegalStateException()` noting that the provided `kubeconfig` file is empty would be more helpful.  (Just adding a `!= null` check probably isn't a good idea as it will probably just lead to an equally-hard-to-debug error downstream when we try to again use this empty file.)  I'll mark this beginner-friendly as this should be reasonably easy to implement in `KubernetesV2ClouddriverProfileFactory.java`.

**Comment by mattsanta** [comment]
Thanks for reporting the issue and sorry for the delay. I went ahead and submitted a fixed that will be out with the next release of halyard.
