### ISSUE TITLE
Improvements to Deck's CI

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#5230]
### Issue Summary:

I'd like to propose a few changes to Deck's CI in order to avoid the following situations:
- A PR passes pre-merge Travis CI, but fails post-merge Travis CI.
- A PR passes pre-merge and post-merge Travis CI, but fails nightly Jenkins CI and blocks publication of a Spinnaker BOM.

### Summary of Existing CI:
- Pre-merge: Travis runs a [script](https://github.com/spinnaker/deck/blob/master/gradle/buildViaTravis.sh#L4) to execute the Karma-run unit tests directly.
- Post-merge: Travis runs a [script](https://github.com/spinnaker/deck/blob/master/gradle/buildViaTravis.sh#L12) to execute a gradle build, which includes [a sub-task to execute the Karma-run unit tests](https://github.com/spinnaker/deck/blob/master/build.gradle#L63).
- Nightly: Jenkins runs a script to [execute Deck's functional test suite.
](https://github.com/spinnaker/deck/blob/master/build.gradle#L71)

### Proposed Changes:
- Run a gradle build pre-merge. It looks like we used to do that prior to [this PR](https://github.com/spinnaker/deck/pull/3670). I'm guessing the primary motivation behind removing the pre-merge gradle build was that it was annoying to wait a few minutes for it to run. Now that we have the `ready-to-merge` label, hopefully that is less of a concern.
- Make the execution of the functional tests a dependency of the gradle build executed pre- and post-merge.
- Remove the execution of the functional tests from Jenkins.

### Feature Area:

Deck, CI

**Comment by christopherthielen** [comment]
Speed of CI for PRs is still a major concern for me.  

> A PR passes pre-merge Travis CI, but fails post-merge Travis CI.

Do we know why this passes when built by karma-webpack but not when built via the gradle scripts?

> A PR passes pre-merge and post-merge Travis CI, but fails nightly Jenkins CI and blocks publication of a Spinnaker BOM.

How long do the functional tests take to run?

**Comment by maggieneterval** [comment]
> Do we know why this passes when built by karma-webpack but not when built via the gradle scripts?

No, I'm still unclear on why intermittently-failing tests like the one @alanmquach fixed [here](https://github.com/spinnaker/deck/pull/7691) seem to fail more frequently when run via the gradle scripts. One thought is that running the gradle scripts pre-merge could potentially help us get to the bottom of intermittently-failing tests more quickly because we'd be running them with gradle twice as often as we are now.

> How long do the functional tests take to run?

About 95 seconds.

> Speed of CI for PRs is still a major concern for me.

Good to know -- let me know if moving the functional tests from Jenkins to Travis (which will add ~1.5 minutes to pre-merge CI) would be an acceptable first step. I am also open to removing the functional tests entirely if we don't think we're getting enough value out of them: to date, they have caught exactly one real regression. My number one goal is to prevent situations like the one that occurred this week, where we spent multiple days trying to track down[ the root cause](https://github.com/spinnaker/deck/pull/7687) of functional test failures that could have been caught immediately if they had been merge-blocking (rather than BOM-creation-blocking :cry:).

I added an agenda item to the UI SIG so we can discuss this more live!

**Comment by alanmquach** [comment]
Another difference that I noticed is that I think CI Travis runs webpack (via gradle) whereas the PR Travis does not run gradle and thus does not run webpack either.

This was why the bad dcos import that @maggieneterval fixed in https://github.com/spinnaker/deck/pull/7705 only failed once it landed on master but didn't fail in PR.

**Comment by christopherthielen** [comment]
> PR Travis does not run gradle and thus does not run webpack either.

I had assumed that the karma runner (which uses webpack under the covers) would be sufficient to test that the webpack build is successful, but apparently it was not configured to fail on eslint failures like the full webpack build does.   I think this was addressed in https://github.com/spinnaker/deck/pull/7715, but it may be best just to run the full webpack build.

### Github Actions

I did some investigation over the holiday on migrating away from Travis and embracing github actions.  One key improvement in Actions is the ability to parallelize up to 20 jobs per repository.  By putting different build tasks in different jobs, I saw a reduction in CI time from 13ish minutes on Travis to 6ish minutes on GHA with 6 jobs:

Code changes:
https://github.com/spinnaker/deck/compare/actions?expand=1

Example run: 
https://github.com/spinnaker/deck/commit/82965947f61af5a0dfda94408a1a34b2c3a1047b/checks?check_suite_id=384421965

I think we could add two additional jobs, one for running webpack build and the other for running the functional tests.
