### ISSUE TITLE
feat(plugins): Deck plugin asset proxy

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#5242]
Deck plugins are imported dynamically and must be loaded from a familiar domain (CORS). A proxy will need to be created to serve these assets, similar to how Netflix already serves Deck today, but standardized for the whole community.

This proxy should be built into Gate, so there continues to be a single entrypoint into Spinnaker, the asset proxy will also need to perform checksums of the assets on Deck's behalf, as the native `import` function cannot checksum.

With this in mind, the same plugin download functionality offered in `kork-plugins` should be leveraged to download plugins for Deck, checksum them and then serve the binaries out through HTTPS to Deck.

This would build atop the functionality offered in #5239.

**Comment by robzienert** [comment]
cc @christopherthielen Can you edit this issue or add comments as necessary so it's accurate / correct? Thanks!

**Comment by christopherthielen** [comment]
lgtm
