### ISSUE TITLE
Cannot add cluster to projects

### ISSUE THREAD

**Issue by lukmy** [spinnaker/spinnaker#5246]
### Issue Summary:

The button `Save` on project configuration dialogue is disabled when cluster info is specified

### Cloud Provider(s):

- kubernetes v2
- kubernetes version: 1.13.2

### Environment:

- spinnaker: 1.17.4

### Feature Area:

- UI

### Description:

![image](https://user-images.githubusercontent.com/1225713/70971253-833d9800-20db-11ea-8217-fbaf3b8430d8.png)

If we delete all clusters, the `Save` button is enabled.

**Comment by andretw** [comment]
I met the same issue. It should be fixed by 1.17.5.

**Comment by lukmy** [comment]
> I met the same issue. It has been fixed by 1.17.5.
> 
> F.Y.I:
> https://www.spinnaker.io/community/releases/versions/1-17-5-changelog#deck-2-13-4
> [spinnaker/deck@87a97c4](https://github.com/spinnaker/deck/commit/87a97c4f635d5b7b3e981a0eb90f1bde31b48ff2)

Thanks for reminding me that, after upgrading to 1.17.5, it works. :)
