### ISSUE TITLE
Getting the info of a pipeline that doesn't exist does not return 404

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [spinnaker/spinnaker#5264]
### Issue Summary:
Hello,
getting the info of a pipeline that doesn't exist returns an empty string, with a status code of 200, (and throws an exception in swagger clients).

This function:

https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy#L148

should return a 404 in case the pipeline does not exist

**Comment by cfieber** [comment]
fixed by spinnaker/gate#1209
