### ISSUE TITLE
Bump awscli to support eks oidc serviceaccount based pod iam

### ISSUE THREAD

**Issue by rverma-jm** [spinnaker/spinnaker#5265]
### Issue Summary:
As per https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html, the aws-java-sdk and aws cli should be greater than 1.11.623 , 1.16.232 to support this. Currently this is not working.

### Cloud Provider(s):
AWS

### Environment:
EKS

### Feature Area:
Halyard
Other components using aws-sdk having version < 1.11.623

### Description:
Required for iam roles for service-account in eks

### Steps to Reproduce:
https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html

**Comment by imosquera** [comment]
More Context from the SIG: There is native IAM role using service-accounts in Kubernetes so you don't have to use hard coded credentials.  Upgrading to this new client will allow Spinnaker users to leverage this new functionality from AWS.

**Comment by rverma-jm** [comment]
It seems rather than bumping aws sdk in halyard , they have even remove aws cli and python from the 1.29.0 release. Wondering what's the reason behind that.

**Comment by duftler** [comment]
My guess is it was unintentional and that `aws` relies on `python` being present.

```
$ kubectl exec -it spin-halyard-0 -n halyard -- bash
bash-5.0$ whoami
spinnaker
bash-5.0$ python -v
bash: python: command not found
bash-5.0$ aws
bash: /usr/bin/aws: /usr/bin/python2: bad interpreter: No such file or directory
bash-5.0$
```

**Comment by duftler** [comment]
Halyard version 1.30.0 contains a fix for the issue.
