### ISSUE TITLE
Spinnaker scaling statefulset to zero is not completing in UI

### ISSUE THREAD

**Issue by rverma-jm** [spinnaker/spinnaker#5283]
### Issue Summary:
While trying to scale a statefulset to zero replicas, the scaling actually happened but the pipeline continue to run and await for status. It never finished.

### Cloud Provider(s):
EKS

### Environment:
EKS

### Feature Area:
UI/UX

**Comment by ezimanyi** [comment]
@rverma-jm : Thanks for the bug report!  This has been fixed (as well as the same bug for daemon sets) in the above-linked PR.
