### ISSUE TITLE
Proposal: new AWS CodeBuild Stage

### ISSUE THREAD

**Issue by Kaixiang-AWS** [spinnaker/spinnaker#5292]
# Problem Statement

AWS CodeBuild is a fully managed continuous integration service that compiles source code, runs tests, and produces software packages that are ready to deploy. Spinnaker is an open source, multi-cloud continuous delivery platform for releasing software changes with high velocity and confidence. Spinnaker currently doesn’t support AWS CodeBuild in a native way. Users have to set up Run Job or Webhook stages to start a CodeBuild build. It means that monitoring the status of the build is not easy, as the success/failure of the build is not directly shown in UI. Following stages also couldn’t take dependencies on the final status of the build.

# Proposed Solution

I propose adding a new AWS CodeBuild stage, which could start, stop, retry an AWS CodeBuild build and monitor the build status. Furthermore, it could take artifacts from previous stages as build sources and produce artifacts that could be used by following stages.

In AWS CodeBuild, almost all project attributes could be overridden when starts a build. However, only a small subset of these makes sense in Spinnaker context, e.g. overriding sources and artifacts. These attributes will be abstracted and configurable during Spinnaker stage setup. Other attributes such as cache override that are less used will not be configurable.

The new stage should have the following structure.

Required

* Account [aws account]
* Region [aws region]
* Project Name [String]

Optional

* Build Source Artifacts [Spinnaker Artifact of Type s3/object or git/repo]
* Source Version [String]
* Build Spec Override [String]
* Build Image Artifact [Spinnaker Artifact of Type docker/image]
* Build Output Artifacts [Spinnaker Artifact of Type s3/object]
* Environment Variables [Map]

With the stage definition above, users should have the ability to start a build in AWS CodeBuild, taking advantages of all artifacts produced in previous stage.

# Out of Scope

As mentioned above, advanced use cases such as overriding cache config will not be included in the first release. These configurations could be added later as per feature request.

**Comment by clareliguori** [comment]
What Spinnaker microservices do you expect would be touched by this proposal?  For example, Igor (the microservice for CI integrations) and Deck (the UI)?

Do you expect any changes that look significantly different from the exist CI integrations?
https://github.com/spinnaker/igor#integration-with-ci-services

**Comment by clareliguori** [comment]
Will this also include triggering a Spinnaker pipeline when a CodeBuild build completes?  I believe most (all?) of the other CI integrations support this, not sure if it is required for adding a provider to Igor.

**Comment by Kaixiang-AWS** [comment]
> What Spinnaker microservices do you expect would be touched by this proposal? For example, Igor (the microservice for CI integrations) and Deck (the UI)?
> 
> Do you expect any changes that look significantly different from the existing CI integrations (for example, the Travis CI integration)?
> https://github.com/spinnaker/igor#integration-with-ci-services

Microservices need to update: Deck, Igor, Orca.

I would expect it to be slightly different from the existing CI integrations, as it doesn't require a poller to poll build status. Instead, it uses Pub/Sub to trigger pipeline (just like what GCB does). A sample workflow would be : CodeBuild build completes -> CloudWatch Events -> SQS/SNS -> Spinnaker. I'm not sure if it requires setting up a new provider for CodeBuild. If we do it through igor then we probably have to. However, if we treat it like a CFN deploy stage then we probably don't need to add a provider and could reuse aws as provider.

**Comment by clareliguori** [comment]
How would SNS notify Spinnaker?  HTTPS?  I think many Spinnaker instances are not public on the internet, so I'm not sure if SNS can reach them.

The GCB integration also uses Echo: the PubSub integration in Echo polls PubSub for the notifications (PubSub doesn't push the notifications to Spinnaker), and then Echo sends the events to Igor.  That seems to align with a CloudWatch -> SQS design (no SNS), with Echo polling SQS for events.  There is this SQSSubscriber in Echo already, though I'm not sure what's using it:
https://github.com/spinnaker/echo/blob/master/echo-pubsub-aws/src/main/java/com/netflix/spinnaker/echo/pubsub/aws/SQSSubscriber.java

**Comment by Kaixiang-AWS** [comment]
This is I believe how SQS/SNS integrate with Spinnaker https://www.spinnaker.io/setup/triggers/amazon/

**Comment by clareliguori** [comment]
Oh got it, so that's doing SNS -> SQS -> Spinnaker, so if you're using CWE in this case I think you can go directly to SQS (CWE -> SQS -> Spinnaker)

**Comment by clareliguori** [comment]
For the GCB vs CloudFormation provider model question, I do think this should go through Igor as a CI integration (GCB) and not as a server group provider in Clouddriver (like CloudFormation). I don't think the builds map well to the server group model like CloudFormation deploys do (i.e. CFN stack as the server group, since there's not really state to move between (i.e. no 'deploy' that needs to happen).

**Comment by Kaixiang-AWS** [comment]
> For the GCB vs CloudFormation provider model question, I do think this should go through Igor as a CI integration (GCB) and not as a server group provider in Clouddriver (like CloudFormation). I don't think the builds map well to the server group model like CloudFormation deploys do (i.e. CFN stack as the server group, since there's not really state to move between (i.e. no 'deploy' that needs to happen).

I agree. In that case we will also need to update echo(notify igor of CodeBuild builds), halyard(configure codebuild account), gate(add API to list codebuild account).

**Comment by clareliguori** [comment]
Closing, this is available in 1.19
https://www.spinnaker.io/setup/ci/codebuild/

**Comment by bholat** [comment]
@Kaixiang-AWS @clareliguori 
When trying to add codebuild account in Spinnaker, it gives us the following error…
Per doc, running (with the env vars set):
hal ci codebuild account add $ACCOUNT_NAME \
  --accountId $ACCOUNT_ID \
  --assume-role $ASSUME_ROLE \
  --region $REGION
Error:
! ERROR More than one account supplied

Please advise, thanks.

**Comment by Kaixiang-AWS** [comment]
@bholat This `More than one account supplied` error only throws when you supply more than one argument after `add`. Can you check if your $ACCOUNT_NAME has spaces? If your ACCOUNT_NAME is `my account`, it will treat it as two separate accounts `my` and `account`, thus throw this exception. I would suggest concatenate using dash or underscore in this case.

**Comment by bholat** [comment]
@Kaixiang-AWS Yeah, my account name does not have spaces only a dash
Running this command throws the same error:
`hal config ci codebuild account edit test-services -—accountId 1234`

**Comment by Kaixiang-AWS** [comment]
@bholat I noticed that your command uses `--accountId` instead of `--account-id`. This should be the issue.

**Comment by bholat** [comment]
That was the issue, thanks!
