### ISSUE TITLE
1.18.x Release Candidate Front-End Issues: Blank Page & App Config Page Error

### ISSUE THREAD

**Issue by nickcatal** [spinnaker/spinnaker#5306]
### Issue Summary:

Few issues here:

1) Clicking "Edit Application Attributes" under an Application's "Config" no longer opens a modal, and where information such as the application owner's email would be filled in, `{{vm.application.attributes.email}}` appears.

![Screen Shot 2020-01-13 at 10 47 59 AM](https://user-images.githubusercontent.com/474748/72279528-527e4f00-3604-11ea-9c60-fdc5f1f707f2.png)

In the console `TypeError: Cannot read property 'baseUrl' of undefined` appears

![Screen Shot 2020-01-13 at 1 57 58 PM](https://user-images.githubusercontent.com/474748/72283429-c0c70f80-360c-11ea-892e-bd765dea560e.png)

2) When the app first loads, the page is blank

![Screen Shot 2020-01-13 at 1 55 18 PM](https://user-images.githubusercontent.com/474748/72283254-6168ff80-360c-11ea-8226-ffaeb3b89a24.png)

In the console `Uncaught (in promise) TypeError: core_src.SETTINGS.plugins.forEach is not a function` appears

![Screen Shot 2020-01-13 at 1 56 15 PM](https://user-images.githubusercontent.com/474748/72283316-7fcefb00-360c-11ea-93ba-9f1cd34f124d.png)

### Cloud Provider(s):

I'm deploying to AWS and ECS.

### Environment:

Deb installed directly on Ubuntu

### Feature Area:

Front-end

### Description:

On the new `1.18.x` release the 

### Steps to Reproduce:

Install latest RC.

### Additional Details:

Per slack, mentioning @duftler

**Comment by duftler** [comment]
I believe this was fixed by https://github.com/spinnaker/deck/pull/7768.

@ttomsu We can close this once the updated candidate has been tested.

**Comment by ttomsu** [comment]
@nickcatal - the current `release-1.18.x-latest-validated` BOM should include the fix. Can you give it a try and see if it has been resolved?

**Comment by nickcatal** [comment]
@ttomsu that fixed the homescreen not appearing, but not the attribute/config issue

![Screen Shot 2020-01-13 at 2 20 43 PM](https://user-images.githubusercontent.com/474748/72284860-f4efff80-360f-11ea-8a66-b58d7d3f7f8f.png)
