### ISSUE TITLE
Bug(Deck): Cursor focuses on incorrect field when editing PubSub attributes

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#5307]
### Issue Summary:
In 1.17.x it is difficult to edit PubSub parameters due to some ui bug which always infocuses the field you attempt to edit and jumps the page scroll up.

### Cloud Provider(s):
n/a

### Environment:
1.17.3

### Feature Area:
Deck/UI/Pubsub

### Description:
The ui makes it extremely diffucult/impossible to edit PubSub constraints due to some scrolling bug in the deck code.

### Steps to Reproduce:
1.) Create Pipeline, go to config stage
2.) Add a pipeline trigger for PubSub
3.) Attempt to add a Payload/Attribute constraint, the page will scroll to the top.

### Additional Details:
![demo](https://media.giphy.com/media/S4AVBDzjfM6PW3MmTC/giphy.gif)

**Comment by maggieneterval** [comment]
This should be fixed by https://github.com/spinnaker/deck/pull/7769 :smile:
