### ISSUE TITLE
Bump AWS SDK in Kork (?) to latest available (at the moment) for additional AWS-support

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#5338]
### Issue Summary:

As AWS SDK updates, Spinnaker's libraries would need to be bumped as well.

This is just a reminder issue to bump the AWS SDK to latest available (?) in the moment of bump, so the next release (1.19.0) would get updated AWS features as well.

### Cloud Provider(s):

AWS

@allisaurus knows about this :)

**Comment by rrijkse** [comment]
Isn't this the same as #5265?

**Comment by allisaurus** [comment]
@rrijkse my understanding is that this is primarily a tracking issue for bumping the SDK to the latest just prior to 1.19.x being cut, where #5265 requires bumping the SDK and AWSCLI past a specific version to enable some EKS features with IAM. 

I think that one can be closed once the PRs for those updates are done, but this would remain open until closer to the 3/2/20 window for 1.19.x so we could incorporate the latest version prior to release.

**Comment by rverma-jm** [comment]
I believe the version in front50 is still very old. 
```	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1338) ~[aws-java-sdk-sts-1.11.415.jar:na]
```
