### ISSUE TITLE
Spinnaker 1.18.0 front50 and igor - CrashLoopBackOff

### ISSUE THREAD

**Issue by babinin** [spinnaker/spinnaker#5349]
### Issue Summary:
Spinnaker 1.18.0 front50 and igor - CrashLoopBackOff

### Cloud Provider(s):
Kubernetes

### Environment:
Container

### Feature Area:
Java Virtual Machine

### Description:
Spinnaker 1.18.0 front50 and igor - CrashLoopBackOff

### Steps to Reproduce:
hal deply apply

### Additional Details:
container log:
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by babinin** [comment]
After adding deploymentEnvironment.imageVariant: UBUNTU_JAVA8
- Get current deployment
  Failure
Problems in Global:
! ERROR Could not translate your halconfig: Cannot deserialize
  value of type
  `com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment$ImageVariant`
  from String "UBUNTU_JAVA8": value not one of declared Enum instance names:
  [SLIM, UBUNTU]
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["deploymentEnvironment"]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment["imageVariant"])
- Failed to get deployment name.

**Comment by duftler** [comment]
Please try halyard version 1.29. The new enum value is present in that release.

**Comment by babinin** [comment]
@duftler
Thank You!
(everything working now)

**Comment by plumpy** [comment]
@babinin also, using Halyard 1.29 means you shouldn't need to use the `JAVA8` variants, so you should just go back to using `SLIM`. Let me know if that still doesn't work...

**Comment by babinin** [comment]
@plumpy 
with 1.29 SLIM variant works perfectly (in my case)

**Comment by plumpy** [comment]
Great, glad to hear it, thanks for letting me know!

**Comment by rverma-jm** [comment]
It seems halyard 1.29 is missing aws cli

**Comment by duftler** [comment]
Halyard version 1.30.0 contains a fix for the issue.
