### ISSUE TITLE
front50 pod not starting up properly

### ISSUE THREAD

**Issue by eboumendil** [spinnaker/spinnaker#5350]
### Issue Summary:
Front50 is not starting properly in v1.18.0 with this error message
```
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
### Cloud Provider(s):
Kubernetes

### Environment:
GKE

### Feature Area:
Front50

### Description:
Front50 is not starting properly in v1.18.0 with this error message
```
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
It looks like front50 run Java11 and does not support the UseCGroupMemoryLimitForHeap flag.

### Steps to Reproduce:
Deploy Spinnaker v1.18 using Halyard

**Comment by bnutt** [comment]
Are you passing this flag in? I have upgraded spinnaker to 1.18.0 without this issue on front50. I believe this experimental flag was removed in Java 10 or 11 as 11 now supports out of the box setting the heap size based off the memory specified for the container.

**Comment by duftler** [comment]
Please try upgrading to halyard 1.29.0.

**Comment by eboumendil** [comment]
Thanks @duftler. Upgrading to halyard 1.29.0 fixed the issue.
