### ISSUE TITLE
Config Name empty

### ISSUE THREAD

**Issue by Guillaume-BVS** [spinnaker/spinnaker#5370]
### Issue Summary:
Hello, I created a canary config into my Spinnaker application, and when I create a Canary Analysis stage, the field "Config Name" is empty.

### Cloud Provider(s):
/

### Environment:
Netflix

### Feature Area:
Prometheus / Canary

### Description:
I've configure canary setting in my Spinnaker server, I've checked the box in pipeline config and I've created a canary config, but when I use a "Canary Analysis" stage into my pipeline, the field "Config name" is empty.
I tried to 
- disable and enable canary and prometheus, 
- delete and re-create the prometheus account, 
- change the Canary Config name, 
- update halyard version, ( I use 1.29.0 )
- change the metrics selected in Canary Config,
- try to do this stage into another application

Tutorials followed 
[https://www.spinnaker.io/setup/canary/](url)
[https://docs.armory.io/spinnaker/configure_kayenta/](url)
[https://www.spinnaker.io/guides/user/canary/config/](url)

### Steps to Reproduce:
/

### Additional Details:
---------- `hal config canary` ----------
`Canary(enabled=true, serviceIntegrations=[GoogleCanaryServiceIntegration(super=AbstractCanaryServiceIntegration(enabled=false, accounts=[]),
	name=google, gcsEnabled=false, stackdriverEnabled=false, metadataCachingIntervalMS=null),
PrometheusCanaryServiceIntegration(super=AbstractCanaryServiceIntegration(enabled=true, accounts=[PrometheusCanaryAccount(super=AbstractCanaryAccount(name=prometheus-cluster-232), 
	endpoint=PrometheusCanaryAccount.Endpoint(baseUrl=http://127.0.0.1:30732), username=null, password=null, usernamePasswordFile=null, supportedTypes=[METRICS_STORE])]), name=prometheus, metadataCachingIntervalMS=null),
DatadogCanaryServiceIntegration(super=AbstractCanaryServiceIntegration(enabled=false, accounts=[]), name=datadog),
	SignalfxCanaryServiceIntegration(super=AbstractCanaryServiceIntegration(enabled=false, accounts=[]), name=signalfx), 
AwsCanaryServiceIntegration(super=AbstractCanaryServiceIntegration(enabled=true, accounts=[AwsCanaryAccount(super=AbstractCanaryAccount(name=aws), 
	bucket=canary, region=null, rootFolder=kayenta, profileName=null, endpoint=http://127.0.0.1:9001, accessKeyId=admin, secretAccessKey=admin123, supportedTypes=[CONFIGURATION_STORE, OBJECT_STORE])]), 
	name=aws, s3Enabled=true)], reduxLoggerEnabled=true, defaultMetricsAccount=prometheus, defaultStorageAccount=aws, defaultJudge=NetflixACAJudge-v1.0, defaultMetricsStore=prometheus, stagesEnabled=true,
	atlasWebComponentsUrl=null, templatesEnabled=true, showAllConfigsEnabled=false)`

**Comment by duftler** [comment]
What version of Spinnaker are you running?

**Comment by Guillaume-BVS** [comment]
1.17.1, halyard version : 1.29

**Comment by Guillaume-BVS** [comment]
The solve it's : update halyard and Spinnaker version, with Spinnaker version 1.18.1 and halyard version 1.31, the problem it's solved.

**Comment by duftler** [comment]
Thanks for the update. I tried to reproduce this, and was so far unsuccessful, so glad you were able to resolve it.
