### ISSUE TITLE
Manually execution of pipeline failed when explicitly specifying docker image with digest.

### ISSUE THREAD

**Issue by in-cloud-opensource** [spinnaker/spinnaker#5376]
### Issue Summary:
Manual execution of pipeline failed when explicitly specifying docker image with digest. Container image is wrongly red-black-spinnaker:sha256:341dacc7271d1cd7cbaee77f2e06687738e211c1d80e837b5f165874749dc3f

### Cloud Provider(s):
BareMetal with Kubernetes

### Environment:
Spinnaker 1.18.0 installed with Halyard to Kubernetes
Istio Ingress for spinnaker(Deck) and spinnaker-api(Gate)
KeyCloak for OpenID Connect

### Feature Area:
Deck UI: Manuel execution of pipelines 

### Description:
We are new to spinnaker and evaluating right now the red/black deployment strategy. For testing we set up a simple pipeline that uses the automated trigger for docker registries and kubernetes manifests V2. When executing pipelines manually by explicitly specifying docker image with digest the pipeline hangs since the deployment does not stabilize. The reason for that seems to me the wrong container image that comes out of the deck UI. 

Actual behavior:
`red-black-spinnaker:sha256:341dacc7271d1cd7cbaee77f2e06687738e211c1d80e837b5f165874749dc3fe`

Expected behavior:
`red-black-spinnaker@sha256:341dacc7271d1cd7cbaee77f2e06687738e211c1d80e837b5f165874749dc3fe 
`

### Steps to Reproduce:
Manually execution of pipeline failed when explicitly specifying docker image with digest

### Additional Details:
It seems that digest is not well handled in method updateArtifact
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx

**Comment by maggieneterval** [comment]
@ezimanyi just so you don't spend time looking into this as well, a community member actually opened a PR to resolve this issue: https://github.com/spinnaker/deck/pull/7896 :tada:

**Comment by maggieneterval** [comment]
Huge thanks to @dragon3 for fixing this bug; a fix will be released with the next patch release of 1.18.
