### ISSUE TITLE
There is no response after clicked "Rollback" button in Server Group Actions

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#5408]
### Issue Summary:
There is no response and rollback window isn't opened after clicked "Rollback" button in Server Group Actions. After investigated, seems that there is some issue in the commit "10b3491" of Deck. Because it works fine once I revert the code to the previous one commit of the commit "10b3491" after tested. The commit "10b3491" is mapped to PR "https://github.com/spinnaker/deck/pull/7743" after checked.

### Cloud Provider(s):
Azure

### Environment:
ubuntu 16.04

### Feature Area:
Deck

### Steps to Reproduce:
1. version=1.18.1
2. hal config version edit --version $version
3. hal deploy apply
4. Create two server groups
5. Click "Rollback" button in Server Group Actions against enabled server group
6. There is no response and rollback window isn't opened

### Additional Details:
![image](https://user-images.githubusercontent.com/19754191/74018323-ab0cf600-49d0-11ea-8fca-47e7ed794eeb.png)
![image](https://user-images.githubusercontent.com/19754191/74018482-f4f5dc00-49d0-11ea-8d54-835ba6d898a4.png)

**Comment by neil-yechenwei** [comment]
Hi @anotherchrisberry , I found there is no response and rollback window isn't opened after clicked "Rollback" button in Server Group Actions. After investigated, it seems that there is some bug in your PR https://github.com/spinnaker/deck/pull/7743. Could you help to fix it asap since we're blocked now? Thanks so much.

**Comment by anotherchrisberry** [comment]
Sorry about that. This is fixed in https://github.com/spinnaker/deck/pull/7816

**Comment by maggieneterval** [comment]
Closing this since a fix was patched into [1.18.3](https://www.spinnaker.io/community/releases/versions/1-18-4-changelog#spinnaker-release-1-18-3).
