### ISSUE TITLE
ECS: Reserved Compute Units and Memory field missing from deck 'Container' component

### ISSUE THREAD

**Issue by allisaurus** [spinnaker/spinnaker#5425]
### Issue Summary:
The "Container" section of the server group modal from ECS was recently migrated to React during the multiple target group feature work, however the new component is missing the `Reserved Compute Units` and `Reserved Memory` UI fields.

### Cloud Provider(s):
Amazon ECS

### Environment:
Deck

### Feature Area:
server group modal : container inputs section

### Steps to Reproduce:
1. in the 'deploy' step for ECS, click "Add Server Group"
2. Fill in available fields for the default "inputs" Task Definition setting (CPU and memory fields are not visible)
3. Save server group and pipeline
4. Manually deploy pipeline, deployment fails due to:
```
Exception ( Create Server Group )
createServerGroupDescription.computeUnits.not.nullable
createServerGroupDescription.reservedMemory.not.nullable
```

### Additional Details:

Workaround: these values can be specified in the cluster JSON using the JSON stage or pipeline editor:
```
...
"computeUnits": 256, 
"reservedMemory": 512,
...
```

**Comment by pkandasamy91** [comment]
PR to address the issue: https://github.com/spinnaker/deck/pull/7869
