### ISSUE TITLE
ECS - "roleName is Invalid" when Role contains a path

### ISSUE THREAD

**Issue by away168** [spinnaker/spinnaker#5430]
### Issue Summary:
Using ECS provider to deploy an image, and specifying the ECS IAM Instance Profile with: 
e.g. arn:aws:iam::accountno:role/projects/spinnaker/SpinnakerRole 

### Cloud Provider(s):
AWS

### Environment:
Spinnaker in EKS, deploying to ECS

### Feature Area:
CloudDriver

### Description:
Please note, that I had to edit the stage json in order to put in the iam role.  See sample stage json below.

### Steps to Reproduce:
Configure an ECS deploy stage that utilizes an IAM instance profile that contains a path.

### Additional Details:

Error Message:
```
Exception ( Monitor Deploy )
The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_- (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 3b2d7dcd-3cef-48a3-9b25-b62e4217398d)
```

JSON of Stage Definition: 
```
{
  "clusters": [
    {
      "account": "ecs",
      "application": "helloworld",
      "availabilityZones": {
        "us-west-2": [
          "us-west-2a",
          "us-west-2b",
          "us-west-2c",
          "us-west-2d"
        ]
      },
      "capacity": {
        "desired": 1,
        "max": 1,
        "min": 1
      },
      "cloudProvider": "ecs",
      "computeUnits": 512,
      "containerPort": 443,
      "copySourceScalingPoliciesAndActions": false,
      "dockerImageCredentialsSecret": "None (No registry credentials)",
      "dockerLabels": {},
      "ecsClusterName": "dev",
      "environmentVariables": {},
      "healthCheckGracePeriodSeconds": "",
      "healthCheckType": "EC2",
      "iamRole": "projects/spinnaker-helloworld/SpinnakerHelloWorld-SpinnakerHelloWorldRole",
      "imageDescription": {
        "fromContext": true,
        "imageId": "simple-nginx-ssl:latest",
        "imageLabelOrSha": "simple-nginx-ssl:latest",
        "stageId": "2"
      },
      "launchType": "EC2",
      "loadBalancers": [],
      "moniker": {
        "app": "helloworld",
        "stack": "from_spinnaker_config"
      },
      "networkMode": "bridge",
      "placementConstraints": [],
      "placementStrategyName": "",
      "placementStrategySequence": [],
      "provider": "ecs",
      "reservedMemory": 1024,
      "securityGroups": [],
      "serviceDiscoveryAssociations": [],
      "stack": "from_spinnaker_config",
      "strategy": "highlander",
      "subnetType": "",
      "tags": {},
      "targetGroup": "dev1-spinnaker-helloworld-https",
      "taskDefinitionArtifact": {},
      "useSourceCapacity": false,
      "useTaskDefinitionArtifact": false,
      "vpcLoadBalancers": []
    }
  ],
  "name": "Deploy",
  "type": "deploy"
}
```

---

"Please assign a label from the right so your issue can be properly sorted." 
Sorry, I do not see how to apply labels.

**Comment by jasonmcintosh** [comment]
Digging through the code,
https://github.com/spinnaker/clouddriver/blob/3f10a63aea05aba393d8887d5f4dda34576952e4/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L681

Checks the role status - I think this works.  However on this line, it sets the role ARN to the role from the description which does NOT include the path.  I think 
https://github.com/spinnaker/clouddriver/blob/3f10a63aea05aba393d8887d5f4dda34576952e4/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L314
should be changed so that checkRoleTrust returns the response, then uses the response.getRole().getArn() 

IF this looks like the issue I'm happy to create a PR & such.

**Comment by jasonmcintosh** [comment]
Note, digging through ECS behavior, I think I see some other places this MIGHT be an issue, would need to dig.  https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgent.java#L142 is one thought but it looks like it's pulling out the shortname as the key for the entry but still stores the ARN.

**Comment by clareliguori** [comment]
Fixed by https://github.com/spinnaker/clouddriver/pull/4321
