### ISSUE TITLE
Javascript console error when selecting kind of artifact in Produces Artifacts in a stage in a pipeline (deploy manifest stage)

### ISSUE THREAD

**Issue by nikhilkhanna** [spinnaker/spinnaker#5450]
### Issue Summary:
When selecting a kind of artifact in the "Produces Artifact" section of pipeline stage creation None of the forms change and no additional inputs are created (so as to specify for the resource type for instance if the artifact kind selected was kubernetes) and the following javascript console errors appear `Error: [$injector:strictdi] controller is not using explicit annotation and cannot be invoked in strict mode` and `Error: [ng:areq] Argument 'fn' is not a function, got undefined`.

### Cloud Provider(s):
Kubernetes V2

### Feature Area(s):

UI / Javascript

### Description:
Expected behavior: The UI should change to reflect the selected artifact option
Actual behavior: Nothing changes and a javascript error is thrown

### Steps to Reproduce:
On the latest stable version, in the kubernetes v2 provider, try making a pipeline with a deploy manifest stage and try to declare a specific artifact as being produced by this manifest and you will hit in error.

### Additional Details:
<img width="1678" alt="Screen Shot 2020-02-16 at 11 39 33 PM" src="https://user-images.githubusercontent.com/1312196/74633170-ebc5e700-5115-11ea-85d9-9a5c43c0cff8.png">

**Comment by maggieneterval** [comment]
@nikhilkhanna thanks so much for reporting this! We've already merged a fix for this issue, and we'll cherry-pick it into the next patch release of 1.18.
