### ISSUE TITLE
Broken link in Kubernetes document

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [spinnaker/spinnaker#5458]
### Issue Summary:
I found a dead link in the documentation:
https://www.spinnaker.io/reference/providers/kubernetes/#server-group
The link that says `here` when talking about Server Groups. It leads to 404 on Github. I'm not sure where it's supposed to lead instead

### Feature Area:
Documentation

**Comment by maggieneterval** [comment]
Hey @AbdulRahmanAlHamali, thanks for letting us know! As part of the [removal of the V1 provider](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md), we'll be auditing its documentation to clarify that new users should install the V2 provider instead, and we'll be sure to fix these broken links as well.

**Comment by AbdulRahmanAlHamali** [comment]
Great, thanks Maggie! Should I close this?

**Comment by maggieneterval** [comment]
I'll close it when the documentation is actually updated -- thanks!
