### ISSUE TITLE
Update community content to reflect Kubernetes V1 provider removal

### ISSUE THREAD

**Issue by maggieneterval** [spinnaker/spinnaker#5463]
### Issue Summary:

As part of the removal of Spinnaker's Kubernetes V1 provider ([RFC](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md)), let's update Spinnaker community content to reduce user confusion regarding:

- Which Kubernetes provider is this blog post, tutorial, or demo referring to?
- Which Kubernetes provider(s) are supported? Which one should I install?

To quickly answer these questions, let's add a short blurb above each relevant blog post, similar to the one we've added to the [Kubernetes V1 documentation](https://www.spinnaker.io/setup/install/providers/kubernetes/#kubernetes-legacy-provider) on spinnaker.io.

### Suggested Blurb:

> This content refers to Spinnaker’s legacy Kubernetes provider (V1), which is [scheduled for deletion](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md) in Spinnaker 1.21. We recommend using the [manifest-based provider (V2)](https://www.spinnaker.io/reference/providers/kubernetes-v2/) instead.

#### Spinnaker Community Blog
- [x] [Lifting the Sail: How Spinnaker Maps Resources to Kubernetes](https://blog.spinnaker.io/lifting-the-sail-how-spinnaker-maps-resources-to-kubernetes-57da9c1657ba)

- [x] [Deploying Database Migrations with Spinnaker and Kubernetes](https://blog.spinnaker.io/deploying-database-migrations-with-spinnaker-and-kubernetes-6e6761f9d28a)

#### Armory Blog
- [x] [Kubernetes V1 & V2: What’s the Difference?](https://www.armory.io/blog/kubernetes-v1-v2-whats-the-deal/). Let's also remove the following sentence from this post, which is no longer true: 

> It also exposes some compelling features like the Run Job stage (not available in V2) and the Red/Black deployment strategy.

- [x] [Spinnaker Training Series #7: Red/Black Strategy](https://www.armory.io/blog/spinnaker-training-series-7/)

- [x] [Skuid User Demo: Deploying to Kubernetes with Spinnaker](https://www.armory.io/blog/user-demo-deploying-to-kubernetes-with-spinnaker/)

- [x] [Managing Kubernetes with Spinnaker at scale](https://www.armory.io/blog/managing-kubernetes-with-spinnaker/)

- [x] [Spinnaker and Kubernetes (the peanut butter to your jam)](https://www.armory.io/blog/spinnaker-and-kubernetes/). I don't think we need to add the blurb here, but instead of linking to a “stable” and “experimental” implementation, let’s link only to the V2 provider.

- [x] [Continuous Delivery to Clouds & Kubernetes with Spinnaker and Helm](https://www.armory.io/blog/continuous-delivery-to-clouds-kubernetes-with-spinnaker-and-helm/)

**Comment by maggieneterval** [comment]
@dorbin @brian-armory any edits to the suggested blurb?

@dorbin Are you able to add the blurb to the Spinnaker Community Blog posts, or give me permission to do so?

@brian-armory: Would you mind adding the blurb to the Armory Blog posts? I reviewed Armory's Kubernetes documentation and I actually could not find any V1-specific documentation, but if you know of any could you add the blurb to that as well?

Finally, @ethanfrogers, I noticed that you authored most of these posts. Let me know if you have any reservations about prefacing them with this blurb (and great job at community content creation! :1st_place_medal: ).

**Comment by dorbin** [comment]
@maggieneterval I haven't figured out how to add this, yet. Since the two articles you list from the Spinnaker blog are both by @ethanfrogers , It makes sense for him to add the blurb to those.

**Comment by brian-armory** [comment]
Thanks for the thorough investigation @maggieneterval. I can update the Armory blogs hosted by Armory. @ethanfrogers is on his own for the ones on Medium! 

To my knowledge, Armory doesn't have any V1 specific documentation, but we do have a page here or two that mentions v2 being alpha. I'll make sure to get those cleaned up too.

The blurb LGTM.

**Comment by dorbin** [comment]
And the blurb looks good to me, @maggieneterval!

**Comment by maggieneterval** [comment]
Thanks so much, @dorbin, @brian-armory, and @ethanfrogers. Feel free to check off each post in the main issue as you update it, and I'll close this when they're all updated. Appreciate your help :pray:

**Comment by brian-armory** [comment]
The Armory blog posts are done.  (I can't edit the issue to check off the boxes.)

**Comment by kevinawoo** [comment]
@maggieneterval Shouldn't we do a major version bump for v1.21 since it's a breaking change?

**Comment by maggieneterval** [comment]
Thanks, @brian-armory and @kevinawoo!

> Shouldn't we do a major version bump for v1.21 since it's a breaking change?

Good question. In the past, breaking changes (including the removal of other cloud providers) have been communicated through the changelog rather than by incrementing the major version of a release. Let me follow up with the upcoming release managers on my team as 1.21 approaches so we can make a decision about that.

**Comment by ethanfrogers** [comment]
I've added the blurb to both of my blog posts.

**Comment by maggieneterval** [comment]
@ethanfrogers you are the best. Thanks all! 🤗
