### ISSUE TITLE
ECS Proposal: Require service-linked roles

### ISSUE THREAD

**Issue by clareliguori** [spinnaker/spinnaker#5465]
### Current Situation
The ECS provider currently passes the Spinnaker-managed role (i.e. the role associated with the ECS account in Spinnaker) as the ECS service scheduler role, the ECS task execution role, and the ECS service autoscaling role.

For example, if you have the following role in hal config:
```
    aws:
      enabled: true
      accounts:
      - name: my-aws-acct
        assumeRole: role/SpinnakerManaged
    ecs:
      enabled: true
      accounts:
      - name: ecs-my-aws-acct
        awsAccount: my-aws-acct
```
Then when the server group is created, the "SpinnakerManaged" role will be passed in as:
* the `executionRoleArn` parameter of ECS RegisterTaskDefinition (for Fargate services only)
* the `role` parameter of ECS CreateService (not for Fargate services, as they require using service-linked role)
* the `roleARN` parameter of Application Auto Scaling RegisterScalableTarget

Self-managed service scheduler roles and auto scaling roles are now considered to be legacy for ECS, in favor of service-linked roles where the permissions and trust policy are managed by AWS
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-legacy-iam-roles.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html
https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-service-linked-roles.html

### The Problems

Many newer features of ECS (Fargate, service registries, multiple load balancers) require the use of service-linked roles.  We have some logic in Spinnaker to determine when the self-managed role is allowed to be passed, but it is sometimes out of date or buggy (#5412, #4475).

Re-using the Spinnaker-managed role as the ECS service scheduler role and autoscaling role requires giving the role very broad permissions, including allowing two service principals (`ecs` and `application-autoscaling`) permission to assume the role, attaching `AmazonEC2ContainerServiceRole` and `AmazonEC2ContainerServiceAutoscaleRole` policies,  and allowing the role to pass itself (`iam:PassRole`).

Debugging incorrect permissions in the Spinnaker-managed role is challenging: Spinnaker's behavior of passing the role to ECS and Application Auto Scaling is not well-documented, and ECS only gives an error of "Unable to assume the role" if the trust policy is incorrect.

### The Proposal

I propose that starting with Spinnaker 1.19, the Spinnaker ECS provider will always use the service-linked role for the ECS service scheduler role and all ECS scalable targets in Application Autoscaling, including for existing server groups.

The task execution role behavior will not change, as there is no service-linked role for that role. Spinnaker will still pass the Spinnaker-managed role.  Task definition artifacts can be used to set the task execution role to a custom role ARN.

This change can cause new deployments after upgrading to 1.19 to fail:

If an ECS service-linked role has not yet been created in the account, the next deployment will fail with `Unable to assume the service linked role. Please verify that the ECS service linked role exists.`.  This can be fixed with `aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com`.  Many accounts already have a service-linked role, as ECS attempts to create it automatically on behalf of the caller when new clusters are created.

If an Application Auto Scaling service-linked role has not yet been created in the account, Application Auto Scaling will attempt to create it automatically on behalf of the caller when Spinnaker calls RegisterScalableTarget.  If the caller does not have permission to create the role, the deployment will fail with a message about missing `iam:CreateServiceLinkedRole` permissions.  This can be fixed with `aws iam create-service-linked-role --aws-service-name ecs.application-autoscaling.amazonaws.com`

**Comment by smitjainsj** [comment]
This indeed is required as of now, where the infrastructure is already running and Spinnaker is trying to fit in. This could help to narrow down permissions and have dedicated services roles for Spinnaker ECS.
