### ISSUE TITLE
clouddriver bootstrap pod throws redis pool error after 1.18.2 upgrade - kubernetesV1ProviderSynchronizable failure

### ISSUE THREAD

**Issue by BrundaBS** [spinnaker/spinnaker#5468]
### Issue Summary:

After upgrading Spinnaker to 1.18.2, the clouddriver-bootsrap pod starts but never becomes healthy due to this error when attempting to create the Bean for kubernetesV1ProviderSynchronizable in the Kubernetes V1 provider.

Without authentication there are no issues/errors during Spinnaker set up. Getting the below error only when OAuth2 is enabled.

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configurationRefreshListener' defined in URL [jar:file:/opt/clouddriver/lib/clouddriver-web.jar!/com/netflix/spinnaker/clouddriver/listeners/ConfigurationRefreshListener.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kubernetesV1ProviderSynchronizable': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Unimplemented at`

After this error the connection to the redis pool is closed, resulting in constant printing of this error:
`ERROR 1 --- [gentScheduler-1] c.n.s.c.r.c.ClusteredAgentScheduler : Unable to run agents
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
`

### Cloud Provider(s):
Spinnaker version upgrade from 1.11.3 to 1.18.2
Halyard version - 1.31.1
Kubernetes v1 provider has been configured along with Outh2 authentication.

### Environment:
GKE

**Comment by ezimanyi** [comment]
@BrundaBS : Is there any error further up in the log file?  Often this error is a symptom that something earlier in the initialization process failed.

Also, given that you're upgrading 7 major versions, it might be useful to try upgrading in smaller increments to see if you can isolate what version upgrade is causing issues.

If you're still experiencing failures after upgrading one version at a time, Slack is a great resource for troubleshooting this type of problem with other operators.

Thanks!

**Comment by BrundaBS** [comment]
Thanks for the suggestion @ezimanyi. I would definitely try that.

" Error creating bean with name 'kubernetesV1ProviderSynchronizable'" is the first error we get in clouddriver-bootstrap pod log. After this error getting constant redis related errors. 

Surprisingly 1.18.2 version spinnaker works without any issues if OAuth2 is not enabled.
As soon as we enable authentication, we are facing this issue.
