### ISSUE TITLE
Enhance ECS Cloud Provider Support to detect and wait on draining service before new deployment

### ISSUE THREAD

**Issue by bholat** [spinnaker/spinnaker#5476]
### Issue Summary:
Enhance ECS Cloud Provider Support to detect and wait on draining service before new deployment

### Cloud Provider:
ECS

### Description:
We leverage the ECS Cloud Provider to deploy new artifact versions on ECS with the deployment strategy set to **None**. Due to custom canary requirements, we have our own ECS tear down functionality as the last step in the pipeline. On successive pipeline runs, we see ECS CP trying to deploy to a service name that is in draining status and pipeline fails with a message like so: 

> Unable to Start a service that is still Draining. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 64d96390-b3a0-4e85-89cb-2e5761dc8576)

### Additional Details:
Sample steps on reproducing error:
- Pipeline runs with ECS deploy stage, ECS CP creates ecs service v000
- Next pipeline runs with ECS deploy stage, ECS CP creates ecs service v001 and v000 is terminated via a custom stage
- On next pipeline run, ECS CP attempts to deploy v000 even though it is still in draining status and fails with above mentioned exception

As a customer, we would like ECS Cloud Provider to be more robust and not attempt to deploy to an ECS service in draining status or at least wait for it to drain successfully.

**Comment by clareliguori** [comment]
@bholat For the example you gave, would an acceptable behavior be that ECS CP attempts to deploy with a service name v002 on the next pipeline run, instead of using service name v000? (Leaving v000 to drain in parallel with deploying v002)

**Comment by bholat** [comment]
Yes, that is perfectly fine, thanks!
