### ISSUE TITLE
Enhance ECS Cloud Provider to support parallel deployments (for canary capability)

### ISSUE THREAD

**Issue by bholat** [spinnaker/spinnaker#5477]
### Issue Summary:
Enhance ECS Cloud Provider to support parallel deployments (for canary capability)

### Cloud Provider:
ECS

### Description:
When attempting to Deploy via two parallel Deploy stages using the ECS Cloud Provider, one of the stage fails with the following error since both Deploy stages attempt to deploy to the same ecs service (e.g. v000)

**Error**:

> Creation of service was not idempotent. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2f6abc34-5d56-448c-9289-6d943f3297a4)

### Steps to Reproduce:
- Create a pipeline with two parallel Deploy stages via ECS cloud provider
- Pipeline fails with above mentioned error.

As a customer, we would like to have two ECS Deploy stages run in parallel without having to add arbitrary wait times before the Deploy stage to avoid race condition from above mentioned error.

**Comment by clareliguori** [comment]
Why do the two deploy stages have the same Spinnaker cluster name (i.e. application-stack-details)?  For example why not append "-baseline" and "-canary" to the respective Deploy stages?

**Comment by clareliguori** [comment]
Closing this, the recommended approach is to name the Deploy stages with different suffixes in the detail string to deploy in parallel

**Comment by bholat** [comment]
Apologies @clareliguori for missing your message.
Adding a different suffix does not really work for us. If we append "-baseline" and "-canary", it get's confusing because if canary version is promoted as the new stable version, it looks odd to see an ecs service named with "canary" (since it's the new stable version now).
If this is really not feasible in Spinnaker, we can try to work around this by adding some random wait in the pipeline or an integer based suffix value.
Thank you

**Comment by clareliguori** [comment]
Notes from discussing this on the AWS SIG: further suggestions are to promote artifacts from baseline/canary server groups, and not the server groups themselves.  Once the canary passes, the canary server group is terminated.

**Comment by bholat** [comment]
To circle back on this, the feature request is really around the initial deployment of bringing up two additional services (one running stable and one running canary) in parallel. Per AWS SIG, to avoid this issue and enable parallel deployments, version locking would need to be introduced within Spinnaker core.
