### ISSUE TITLE
Feature Request: Option to color code and order pipelines for each application

### ISSUE THREAD

**Issue by linjmeyer** [spinnaker/spinnaker#5490]
### Issue Summary:
Applications with several pipelines often have a cluttered UI and it is not immediately clear which pipeline is the one the user wants to interact with.  There doesn't seem to be any particular ordering, so for applications with the same pipeline templates the order may not even be the same (e.g. app1 has prod on top, while app2 has prod on bottom).  

Similar to [#1972](https://github.com/spinnaker/spinnaker/issues/1972) it would be helpful to color code pipelines and additionally have an option to order them.

### Cloud Provider(s):
Any

### Environment:
Any

### Feature Area:
UI

### Description:

Proposal to add:
* Ability to change a pipeline's 'banner' color in the pipelines view UI
* Ability to order the pipelines in the UI

### Steps to Reproduce:
N/A

### Additional Details:
N/A

---

**Comment by linjmeyer** [comment]
First suggestion to implement this:

# Ordering

Add an integer property like `orderPriority` (or something more UI specific like `uiOrderPriority`) which can be used in the UI to order pipelines.  If two pipelines have the same priority the title/alphabetical ordering can be used.

# Coloring

![image](https://user-images.githubusercontent.com/7676659/75156682-e159ad80-5712-11ea-9559-e89145a49762.png)


It would be great if we could color both the environment block on the top left of each pipeline as well as the entire bar on the top.  This can be implemented using CSS variables and a color picker just like banners are done today:

![image](https://user-images.githubusercontent.com/7676659/75156611-c129ee80-5712-11ea-9433-3b37a44306ec.png)

**Comment by costimuraru** [comment]
AFAIK, you can change the pipeline order on the UI already. Check the top left list, on the Pipelines page, there should be a reorder link. Then drag the pipelines in the list.

**Comment by linjmeyer** [comment]
You're right, somehow I've never noticed this button.

Not exactly what we want, but is a start for sure.  We have a large amount of service and use templates very heavily to create the pipelines.  It would be great if we can bake the pipeline order into the templates somehow.  Looking at the chrome debug tool's network tab it looks like this reorder is an API endpoint and doesn't seem to change any of the json properties of the pipeline itself.

**Comment by maggieneterval** [comment]
Hey @linjmeyer, sorry for the slow follow up on this issue: we chatted about this at today's UI SIG, and since Armory is tentatively planning a re-design of the pipelines view, we're going to close this for now, but your feedback of wanting to attach metadata for the purpose of visually sorting your pipelines has been shared with their designer.
