### ISSUE TITLE
bug(deck): artifact constraint changes does not trigger the "Save Changes" button

### ISSUE THREAD

**Issue by anthonywoo** [spinnaker/spinnaker#5513]
### Issue Summary:
Pipeline configuration does not seem to detect when a user makes a change on an Artifact Constraint. As a result, if a user makes changes to an artifact constraint, they don't see the "Save Changes" button on the Configuration Stage, and navigating to another screen loses the user's changes

https://recordit.co/OhSRrbB6kJ

### Environment:
Spinnaker 1.18.2

### Feature Area:
Configuration Stage: Artifact Constraints

### Description:
If I make changes to an Artifact Constraint and click on "Save Artifact", the changes should be saved to my configuration. At the very least, the Save Changes button should appear on the Configuration stage so I am aware my changes still need to be saved.

The current behavior, when a user makes changes to an Artifact Constraint and clicks on "Save Artifact", nothing is saved and the "Save Changes" button does not appear on the lower right

### Steps to Reproduce:
1. Create a trigger with an artifact constraint and save.
2. Reload the page and make changes to the artifact constraint and save artifact
3. Save changes button does not appear in the Configuration Page and artifact constraint changes are not saved

https://recordit.co/OhSRrbB6kJ

**Comment by sathishavm** [comment]
Same here, I can reproduce this bug!!

**Comment by maggieneterval** [comment]
Thanks for reporting and confirming this bug, @anthonywoo and @sathishavm. We've submitted a fix that will be included with our next patch release of 1.18 (1.18.5).

**Comment by sathishavm** [comment]
Thanks @maggieneterval
