### ISSUE TITLE
Cannot install spinnaker

### ISSUE THREAD

**Issue by freedom1989** [spinnaker/spinnaker#5515]
### Issue Summary:
Got the following error when installing Spinnaker.
E: Version '6.4.5-20200114034416' for 'spinnaker-clouddriver' was not found

### Cloud Provider(s):
Kubernetes

### Environment:
localdebian. ubuntu 16.04
Hal version: 1.31.1-20200207105616
Spinnaker version: 1.17.6

### Feature Area:
halyard

### Description:
E: Version '6.4.5-20200114034416' for 'spinnaker-clouddriver' was not found

### Steps to Reproduce:
Follow the installation instruction.

**Comment by jornjambers** [comment]
Having the same issue with a local install as well after running:
`sudo hal deploy apply`

`(Reading database ... 56017 files and directories currently installed.)
    default: Preparing to unpack .../spinnaker-igor_1.7.0-20191029183208_all.deb ...
    default: Unpacking spinnaker-igor (1.7.0-20191029183208) ...
    default: Processing triggers for ureadahead (0.100.0-19.1) ...
    default: Setting up spinnaker-igor (1.7.0-20191029183208) ...
    default: W: --force-yes is deprecated, use one of the options starting with --allow instead.
    default: Reading package lists...
    default:
    default: Building dependency tree...
    default:
    default: Reading state information...
    default: E: Version '6.4.5-20200114034416' for 'spinnaker-clouddriver' was not found
    default: ! ERROR Error encountered running script. See above output for more
    default:   details.`

**Comment by plumpy** [comment]
This should be fixed now. Sorry about that.

**Comment by jornjambers** [comment]
Just out of curiosity, what was causing it @plumpy?

**Comment by plumpy** [comment]
I was worried you might ask about that... I, uh, accidentally deleted all the `clouddriver` debian packages on 2/27 while thinking I was working on a test repository. I'm working on restoring them all back through 1.15.0 now.

**Comment by jornjambers** [comment]
No worries, thanks for resolving this!

**Comment by aleon1220** [comment]
Just to clarify guys: is this the deployment type used for Dev purposes???

**Comment by plumpy** [comment]
This is for anyone who wants to install Spinnaker 1.17.6 using the Debian packages... If you're doing Spinnaker development, you're probably deploying from git repositories?

**Comment by aleon1220** [comment]
> This is for anyone who wants to install Spinnaker 1.17.6 using the Debian packages... If you're doing Spinnaker development, you're probably deploying from git repositories?

i dont know. I tried to install spinnaker by using debian install and it never worked. I created an issue, had to close it as no one replied and then moved to use Minnaker and make small contributions to docs...

**Comment by milosbackonja** [comment]
> I was worried you might ask about that... I, uh, accidentally deleted all the `clouddriver` debian packages on 2/27 while thinking I was working on a test repository. I'm working on restoring them all back through 1.15.0 now.

@plumpy Could you please restore this one? :D E: Version '4.2.6-20190130153044' for 'spinnaker-clouddriver' was not found

**Comment by plumpy** [comment]
From 1.11.9? Not easily. What are you doing with a version of Spinnaker that old?

**Comment by milosbackonja** [comment]
I am reproducing production setup locally so I can validate upgrade process before I implement that in production :)
I proceeded with 1.17.10 locally. Hopefully it will give same result at the end.
