### ISSUE TITLE
CloudFoundryServerGroupCreator manifest artifact resolution results in null pointer

### ISSUE THREAD

**Issue by ZachDev1** [spinnaker/spinnaker#5519]
### Issue Summary:
Class: CloudFoundryServerGroupCreator
Package: com.netflix.spinnaker.orca.clouddriver.tasks.providers.cf
Line 57: 
`manifest.getArtifact().getArtifactAccount()`
If the mapping from lines 50-51 don't map an Artifact, this value will be null. Calling an operation on a null object returns a null pointer exception. As an example, If the deploy stage references an manifest thats an artifact from a different stage, then all that will be mapped is an artifactId. I believe there was an artifact resolver in this class that would resolve an artifact from a different stage based on the Id but its not happening anymore. 

### Cloud Provider(s):
Cloud Foundry

### Environment:
Version: 1.18.3

### Feature Area:
Pipeline deploy stage (manifest resolution)

### Description:
Prior to some of the recent changes, if the manifest file for the deploy stage was an artifact produced in another stage, it would resolve it and deploy fine. Now, that artifact isn't getting resolved and producing a null pointer.

### Steps to Reproduce:
1) have a stage that produces an artifact (in my case its a manifest.yml). For example, an artifact of type: http/file.
2) reference that as a manifest in the deploy stage by artifact name. (should auto populate)

Run the deploy

---

**Comment by duftler** [comment]
fyi @pdelagrave
