### ISSUE TITLE
orca-validator: upgrade to json-schema-tools edition of json-schema-validator.

### ISSUE THREAD

**Issue by Capstan** [spinnaker/spinnaker#5523]
### Issue Summary:
https://github.com/spinnaker/orca/blob/master/orca-validation/orca-validation.gradle has a reference to com.github.fge:json-schema-validator:2.2.6. @fge has long since stopped maintaining that repo, and passed the torch to https://github.com/java-json-tools/json-schema-validator. Suggest changing the implementation line to "com.github.java-json-tools:json-schema-validator:2.2.12.

2.2.6 is problematic due to CVEs in the depended-upon versions of Guava, and cannot be updated to modern Guava because that version uses deprecated/removed features.

I'm one of the maintainers of https://github.com/java-json-tools and found the reference via indexing of the orca-validator project.

**Comment by ezimanyi** [comment]
Thanks for finding this and for the PR to fix it!
