### ISSUE TITLE
clouddriver-kubernetes-v1: update to java-json-tools edition of json-patch

### ISSUE THREAD

**Issue by Capstan** [spinnaker/spinnaker#5525]
### Issue Summary:

https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v1/clouddriver-kubernetes-v1.gradle has a reference to com.github.fge:json-patch:1.9. @fge has long since stopped maintaining that repo, and passed the torch to https://github.com/java-json-tools/json-patch. Suggest changing the implementation line to "com.github.java-json-tools:json-patch:1.12.

1.9 is problematic due to CVEs in the depended-upon versions of Guava and Jackson Databind.

I'm one of the maintainers of https://github.com/java-json-tools and found the reference via indexing of the clouddriver project.

### Cloud Provider(s):

Kubernetes

### Additional Details:

Although there are plans to [remove this provider](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md), it'd be preferable to create an intermediate release for folks who are on v1 and cannot update to v2 in a security-fix timeframe.

**Comment by ezimanyi** [comment]
Thank you for the detailed description and analysis, as well as the PR!  The PR looks good and I'll merge it.
