### ISSUE TITLE
manual execution of pipelines with more than one docker image artifact: tags

### ISSUE THREAD

**Issue by dbyron0** [spinnaker/spinnaker#5527]
With a pipeline that species multiple docker image artifacts, it's not possibly to specify a different tag for each one.

### Environment:
I'm using spinnaker version 1.16.4, though I think this has been an issue for some time, and is still an issue with the newest version (currently 1.18.4).

I'm also using v2 of the kubernetes provider, though I'm not sure how relevant that is.

### Description:
With a pipeline that specifies one docker image artifact, the manual execution dialog box displays the docker artifact as fixed text next to `Trigger`.  With multiple docker image artifacts in a pipeline, that fixed text becomes a dropdown.  It appears that the tags available in the `Tag` dropdown change when the selected trigger image changes.

It's not totally clear how to go about selecting the tag for each image.  What I've done is, selected a tag for image one, chosen image two from the Trigger dropdown, chosen a tag for image two, and then clicked Run.

The relevant bits (I think) of the pipeline json are:
```
{
  "expectedArtifacts": [
    {
      "displayName": "my.docker.registry.com/locationlabs/image_one",
      "id": "f62dbb25-0f29-4dc2-be57-d3e27fc77dcc",
      "matchArtifact": {
        "artifactAccount": "docker-registry",
        "kind": "docker",
        "name": "my.docker.registry.com/locationlabs/image_one",
        "type": "docker/image"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": true
    },
    {
      "displayName": "my.docker.registry.com/locationlabs/image_two",
      "id": "2270505a-beb9-4592-83a2-b4995b78dee1",
      "matchArtifact": {
        "artifactAccount": "docker-registry",
        "kind": "docker",
        "name": "my.docker.registry.com/locationlabs/image_two",
        "type": "docker/image"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": true
    }
  ],
  "triggers": [
    {
      "account": "my-docker-registry",
      "enabled": true,
      "expectedArtifactIds": [
        "f62dbb25-0f29-4dc2-be57-d3e27fc77dcc"
      ],
      "organization": "locationlabs",
      "registry": "my.docker.registry.com",
      "repository": "locationlabs/image_one",
      "tag": "^[1-9][0-9]*[-][0-9a-f]{6,8}$",
      "type": "docker"
    },
    {
      "account": "my-docker-registry",
      "enabled": true,
      "expectedArtifactIds": [
        "2270505a-beb9-4592-83a2-b4995b78dee1"
      ],
      "organization": "locationlabs",
      "registry": "my.docker.registry.com",
      "repository": "locationlabs/image_two",
      "tag": "^[1-9][0-9]*[-][0-9a-f]{6,8}$",
      "type": "docker"
    },
  ]
}
```

When I do what I explained above, the I see a POST from gate to deck (`https://my.spinnaker.com/pipelines/v2/<application>/<pipeline name>`) with this request body:
```
{
  "account": "my-docker-registry",
  "enabled": true,
  "expectedArtifactIds": [
    "2270505a-beb9-4592-83a2-b4995b78dee1"
  ],
  "organization": "locationlabs",
  "registry": "my.docker.registry.com",
  "repository": "locationlabs/image_two",
  "tag": "259-4cd1ecd",
  "type": "manual",
  "artifacts": [
    {
      "type": "docker/image",
      "name": "my.docker.registry.com/locationlabs/image_two",
      "version": "259-4cd1ecd",
      "reference": "my.docker.registry.com/locationlabs/image_two:259-4cd1ecd"
    }
  ],
  "dryRun": false,
  "parameters": {
    "git_rev": "master"
  },
  "user": "david.byron@avast.com"
}
```
I suppose the key bits of info are:
* one element in the expectedArtifactIds array (corresponding to the last choice from the Trigger dropdown), where I expect to see two.
* similarly for the artifacts array, though the tag here is whatever tag I selected last.

If it's possible to make a UI change to make it more obvious that each tag choice corresponds with a particular docker image, that would be great.  At a minimum though, if gate could send info about all the docker image artifacts in the json it sends to deck in this case, that would get me over the hump.

Thanks much.

**Comment by maggieneterval** [comment]
Hey @dbyron0! Thanks again for opening this issue. It appears that the UI was designed to support manual execution overrides of only one trigger's expected artifact. We chatted about this again at the UI SIG, and no one has any immediate plans to re-design this workflow. For now, our recommendation for specifying multiple artifact overrides at pipeline runtime would be to parameterize your default artifacts, since you can supply multiple parameter values.

We can definitely revisit this in the future if there's more community interest in redesigning the manual execution workflow.

Thanks!

**Comment by dbyron0** [comment]
And so it is.  Thanks for letting me know.
