### ISSUE TITLE
Clouddriver: docker-registry --sort-tags-by-date bad performance

### ISSUE THREAD

**Issue by rbadillo** [spinnaker/spinnaker#5538]
### Issue Summary:
Clouddriver takes about 8 to 12 hours to cache big docker registries with a lot of repositories (~500) and hundreds tags. 

### Cloud Provider(s):
docker-registry
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy#L163

### Environment:
Spinnaker 1.18.4
AWS EKS 1.14.9
Halyard 1.31.1-20200207105616
Docker Registries: AWS ECR

### Description:
We found that we had enabled the **--sort-tags-by-date** flag which was causing Clouddriver to make an extra API call for each Tag available in every Docker repository to be able to get the Tag Creation Date and be able to sort them.

Just for comparison, with the **--sort-tags-by-date** flag enabled it was taking Clouddriver microservice around 8 to 12 hours to read all the tags in all the Docker registries we use in Production (10 Docker Registries X 500 Repositories Each X Hundreds of Tags). After disabling the  **--sort-tags-by-date** flag we went down to minutes to read all the tags in all the Docker registries we use in Production.

### Steps to Reproduce:
hal config provider docker-registry account add ACCOUNT **--sort-tags-by-date** true

**Comment by robzienert** [comment]
I added both AWS & Kubernetes SIGs, since they're the most dominant in docker usage.

**Comment by maggieneterval** [comment]
Thanks for reporting this performance issue, @rbadillo. I've added discussion of this issue to the agenda for the next [Kubernetes SIG](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md) so we can talk about if/why folks are using this flag, and hopefully brainstorm alternate solutions. There doesn't appear to be a great way to remedy the performance concerns given the limitations of the Docker V2 API, so my preference at this point would be to remove (or at least highly discourage use of) the flag. I'll keep this issue updated with the results of the discussion at the SIG.

**Comment by maggieneterval** [comment]
After discussing this issue in Slack and at the Kubernetes SIG, we learned that users with smaller registries still find this flag valuable and are not hindered by these performance issues. I'm adding a warning to the documentation for now, and in the future we can revisit either 1) removing the flag or 2) improving the performance of its implementation pending improvements to the Docker V2 API.

Thanks again for raising this issue, @rbadillo!
