### ISSUE TITLE
ECS/Fargate: useSourceCapacity does not work as expected

### ISSUE THREAD

**Issue by lifeofguenter** [spinnaker/spinnaker#5541]
### Issue Summary:

When enabling `useSourceCapacity`, according to the tooltip:

![Screen Shot 2020-03-05 at 19 13 22](https://user-images.githubusercontent.com/241073/76012283-56e52b00-5f16-11ea-89a9-fe94038afc98.png)

only the `desired` capacity should be copied over from a previous build.

Currently however it will copy over min/max as well, and completely ignore whatever was set in the pipeline config.

### Cloud Provider(s):

ecs

**Comment by awsiv** [comment]
Desired is copied here.. which is correct: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L567-L573


But while registering the autoscaling group.. its using the min/max from the source server group as well:

https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L567-L573

think min/max should be picked up from the pipeline config instead for consistency?

**Comment by clareliguori** [comment]
The ECS provider behavior of copying over the min, max, and desired count from the previous server group (not from the pipeline settings) matches the AWS provider behavior:
https://github.com/spinnaker/clouddriver/blob/7db3aca0243e0ae90231b115158c655c6ff59902/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy#L415-L419

The tooltip should be updated to reflect the actual behavior.
