### ISSUE TITLE
clouddriver/ecs: deregister containers from service registry on disable/destroy

### ISSUE THREAD

**Issue by awsiv** [spinnaker/spinnaker#5542]
### Issue Summary:
ECS automatically registers containers into service registry [if service registry definition(s) is present ](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L470-L490)

It would be nice if Spinnaker would de-register the same containers when the cluster is disabled/resized or destroyed. I understand this functionality is not provided natively by ECS, but running something like the following might work?

```
aws servicediscovery deregister-instance --service-id srv-utcrh6wavdkggqtk --instance-id 16becc26-8558-4af1-9fbd-f81be062a266 --region us-east-1
```

With Eureka integration, we would get this deregistration. Without this, spinnaker becomes pretty much unusable with ECS deploys with service discovery as we have to build custom solutions to cater for this :(
 

### Cloud Provider(s):
ecs

### Environment:
local debian

### Feature Area:
ecs, service discovery

**Comment by awsiv** [comment]
Please hold off on this.. I might be wrong... seeing containers being de-registered after sometime .. will verify and update

**Comment by awsiv** [comment]
Oops.. sorry, think this is still valid - the behaviour we want is:
- disable cluster
- deregister instances from service registry
- this allows us to stop traffic to the old instances
- target group draining + stopping instances happens in the background


Current behaviour:
- disable cluster
- target group draining starts
- old instances are still actively receiving requests as they are healthy in cloudmap
- ECS terminates old instances
- and deregisters from cloudmap (this is only when the downstream apps know that instances are unhealthy which would have been too late)

**Comment by rrijkse** [comment]
> Current behaviour:
> 
>     * disable cluster
> 
>     * target group draining starts
> 
>     * old instances are still actively receiving requests as they are healthy in cloudmap
> 
>     * ECS terminates old instances
> 
>     * and deregisters from cloudmap (this is only when the downstream apps know that instances are unhealthy which would have been too late)

The current behaviour that is observed is native to ECS, when updating a services within the ECS UI itself (or using the aws cli/API) the old instances are terminated and then removed from cloudmap. This is probably better fixed by AWS in the ECS service itself, just like there is a load balancer deregistration delay.

**Comment by allisaurus** [comment]
As correctly state above, this is an issue on the ECS side and is being tracked here: https://github.com/aws/containers-roadmap/issues/343
