### ISSUE TITLE
echo for spinnaker version 1.18.4 is not available in repositories

### ISSUE THREAD

**Issue by kowshikRoy** [spinnaker/spinnaker#5547]
### Issue Summary:

Spinnaker version 1.18.4 uses echo 2.10.1-20200219152126 which is not available on bintray as well as maven repositories

### Cloud Provider(s):

AWS

### Environment:

Spinnaker 1.18.4

### Feature Area:

N/A

### Description:

We're upgrading spinnaker to 1.18.4 and noticed Echo is not available on either bintray or maven repositories. 

  From hal version, we found out it this 1.18.4 spinnaker version requires 
```
   echo:
    version: 2.10.1-20200219152126
    commit: 407d2b9f83968d36947691c6f328eaa280ea5d7a
```

This artifact is not available in the configured repository.
```
jcenter()
maven { url = uri("https://spinnaker-releases.bintray.com/jars") }
```

### Steps to Reproduce:

Upgrade to Spinnaker 1.18.4

### Additional Details:

---

**Comment by cfieber** [comment]
@spinnaker/release-managers PTAL

**Comment by plumpy** [comment]
I believe this is fixed, please let me know if you see it happen again, thanks.
