### ISSUE TITLE
What are the options (and opinions) around storing durable data outside of Cassandra (and Redis)?

### ISSUE THREAD

**Issue by ajordens** [spinnaker/spinnaker#556]

**Comment by dstengle** [comment]
Is there a specific problem with Cassandra? I'm guessing it has to do with the issue of having spinnaker depend on a datastore with complex support requirements (doing cassandra right takes work).

Using a platform datastore would take away the support requirements but one of the nice things about the current setup is that it is cloud-neutral and self-contained.

The other side of making this part of the system pluggable is creating more permutations to test for a release.

**Comment by ajordens** [comment]
@dstengle - Management and support primarily. From a cloud-neutral perspective, there are alternative and arguably easier to support data stores that would fit the requirements.

We don't have a tremendous amount of durable data, and an argument could be made that straight SQL would be reasonable. Although I'm not against the possibility of allowing someone to plugin a cloud-managed solution (in AWS-land, either something from RDS or perhaps DynamoDB). 

From Front50's point of view, it would also be nice to support either a Filesystem or GIT-backed storage model. Something that would be trivial to track modifications over time. For pipeline configs and application metadata, this would be valuable.

**Comment by okapies** [comment]
Cassandra is a great data store but it's operation seems pain for small teams. I would like to use the Spinnaker with managed data stores such like RDS or DynamoDB to minimize our operational cost in the AWS environment.

**Comment by tomaslin** [comment]
what about something like Spring Data - http://projects.spring.io/spring-data/ ?

**Comment by ajordens** [comment]
Spring Data would definitely be a natural thing to look at as far as implementation goes.

**Comment by gregturn** [comment]
There is currently repository support for Cassandra and JPA regarding the repository model. A teammate is working to bring repository support to Redis as well. If you're totally unfamiliar, check out https://speakerdeck.com/gregturn/intro-to-spring-data-lightning-talk

**Comment by gregturn** [comment]
Is there any benefit with me setting up an experimental branch on front50?

**Comment by tomaslin** [comment]
we should discuss this first before writing any code

**Comment by ajordens** [comment]
Specifically in the context of Front50, I'd like to investigate what a Git-backed datastore would look like.

It may not fit into the whole Spring Data model but would be a functional enabler for a couple features (_notably history tracking and simple archival_) that we've been looking to get in.

I'll take a stab at putting together an API design, nothing should prohibit a subsequent or alternative implementation backed by a traditional datastore (_fronted by Spring Data_).

**Comment by danveloper** [comment]
An S3-backed implementation of app metadata and config could scale nicely between AWS and Google Cloud since Google Datastore supports the S3 APIs.

Consul's K/V store might be a good option as well, since it can provide high or eventual consistency across its cluster according to the data type (config vs metadata, for example).

It'd be cool if the underlying implementation was conditionally bound according to configuration.

**Comment by ttomsu** [comment]
@ajordens - Any progress on this? I'd be glad to take a first pass at extracting the storage interface (and take a look at Spring Data). Since Cassandra is the backing store across multiple components (Echo, Front50), does it make sense to put the interface in a common library? Is Kork the right place for that?

**Comment by ajordens** [comment]
Sorry, this fell a bit down the list of priorities.

Happy to have a hand in implementation, perhaps something to chat about in-person. We have some nice-to-haves particularly around versioning in Front50.

**Comment by tomaslin** [comment]
@ttomsu I would say keep the storage interface in front50 since cassandra use in echo right now only consists of storing upcoming cron trigger events. That can easily be migrated to redis. The only persistent data in Spinnaker ( aside from orca executions ) will probably just live in front50.

**Comment by tomaslin** [comment]
closing this as Adam is moving forward with s3 api compatible storage interface

**Comment by JohnTheodore** [comment]
This looks like the PR for those that want to follow along: https://github.com/spinnaker/front50/pull/73
