### ISSUE TITLE
How to set the logging level for microservices using Helm?

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5565]
### Issue Summary:
I've deployed Spinnaker on K8s using the [Helm chart](https://github.com/helm/charts/tree/master/stable/spinnaker), but I'm couldn't find any ways to set the logging level for Spinnaker microservices. How the set the logging level using the Helm `values.yml` file? 

**Edit1**: Actually I just need to see the logs of Clouddriver in debug mode, I found this code 
```
# logging.level.com.netflix.spinnaker.clouddriver.listeners: DEBUG
``` 
in the `clouddriver.yml` but I don't know how to set this from outside the code.

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.16.1
**Edit1**: Updated Spinnaker version to 1.19.0

### Feature Area:
Microservices

**Comment by maggieneterval** [comment]
Hi @dpolicastro, you can enable debug logs in Clouddriver by adding the following to your [`clouddriver-local.yml`](https://www.spinnaker.io/reference/halyard/custom/#custom-profiles-versus-service-settings):

```
logging:
  level:
    com.netflix.spinnaker.clouddriver: DEBUG
```

In general, we would recommend that you open GitHub issues for only bug reports and feature requests, and instead try to use [Spinnaker Slack](https://join.spinnaker.io/) for operational questions like this. For example, here's a thread on Spinnaker Slack started by an operator with a [similar question](https://app.slack.com/client/T091CRSGH/DE05Z9Z9Q/thread/C091CCWRJ-1576886845.063500?cdn_fallback=2).

Have a great day!

**Comment by dpolicastro** [comment]
Thanks a lot @maggieneterval !
I asked first on Slack but got no answers =(
