### ISSUE TITLE
Pipeline stages with automated trigger artifacts are removed on a trigger update

### ISSUE THREAD

**Issue by hugocortes** [spinnaker/spinnaker#5573]
### Issue Summary:
Pipeline stages that use artifacts defined in an Automated Trigger are removed when making a change to any automated trigger (or adding a new automated trigger). However, this does not affect artifacts defined by  `Artifact from execution context` option.

### Cloud Provider(s):
Kubernetes v1.16.3

### Environment:
Reproduced on Spinnaker 1.18.5 and 1.19.0

### Feature Area:
Pipelines

### Description:
I ran into this issue using a `Bake (Manifest) Configuration` stage that overrides a helm chart  values with values in `Expected Artifact`. The chosen artifacts are always removed after I make any kind of change to my Automated Triggers where I primarily use `Docker Registry` and `Pub/Sub` (saving is not required for this issue to reproduce).

### Steps to Reproduce:
1. Create a pipeline with following:
1a.  Configuration with an automated trigger that has a artifact constraint. (i tested with docker registry and gcs artifact type)
1b. Add a stage which allows you to use an artifact from 1a. (i tested with Deploy Manifest and Bake Manifest)
2. Update any part of the trigger, i.e. change registry name, organization, tag, add a new artifact constraint. (saving the pipeline is not required)
3. All selected artifacts from stages created in 1b will no longer have an artifact selected.

### Additional Details:

![Screen Shot 2020-03-13 at 11 48 59 AM](https://user-images.githubusercontent.com/26414988/76661007-8fe55700-6537-11ea-8bbc-885653335202.png)

An example configured bake stage with two selected manifests.

![Screen Shot 2020-03-13 at 11 49 09 AM](https://user-images.githubusercontent.com/26414988/76660958-704e2e80-6537-11ea-8d83-5625d1cd43f2.png)

Docker registry trigger which defines the artifact constraints. Updating anything in this trigger will reset the selected manifests.

**Comment by maggieneterval** [comment]
Hi @hugocortes, thanks so much for taking the time to report this issue. We'll release a fix with the next patch release of each supported version (1.17, 1.18, 1.19).

We are hoping to default the new artifacts UI (currently enabled with the `artifactsRewrite` feature flag) to enabled with release 1.20, so please continue to report any bugs you encounter.

Thanks again!
