### ISSUE TITLE
clouddriver doesn't work if ec2 metadata api call is blocked 

### ISSUE THREAD

**Issue by sanjeevpandey19** [spinnaker/spinnaker#5578]
### Issue Summary:
spinnaker clouddriver doesn't work if ec2 metadata api call is blocked 

### Cloud Provider(s):
AWS

### Environment:
Running spinnaker in eks enviourment

### Feature Area:
Clouddriver

### Description:
followed https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html to block the ec2 metadata call from kubenertes pods.

clouddriver pod is not working from the time we blocked the ec2 metadata api and giving

Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), com.amazonaws.auth.profile.ProfileCredentialsProvider@25639962: profile file cannot be null, WebIdentityTokenCredentialsProvider: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region., com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@7cc19564: Unable to load credentials from service endpoint]

### Steps to Reproduce:
Below commands can be run in eks enviourment to reproduce the error

yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables 
systemctl enable --now iptables

### Additional Details:
We have service account attached with clouddriver pods and service account is used to call iam role  using oidc provider, it starts working as soon as ec2 metadata api call is allowed

**Comment by avram** [comment]
Probably fixed here: https://github.com/spinnaker/kork/pull/554 (so in a later 1.19 build)

**Comment by clareliguori** [comment]
This will go into 1.20, this is the pull request that bumps the kork version in clouddriver:
https://github.com/spinnaker/clouddriver/pull/4442
This has been built into the nightly build.

@sanjeevpandey19  are you able to try out version `master-latest-unvalidated` to confirm that this is fixed?

**Comment by clanesf** [comment]
This is probably failing because if the pod cannot reach out to the metadata API then it isn't able to get the AWS credentials for this pod. This is what your log says. 

The AWS Provider goes and reaches out to 
`http://169.254.169.254/latest/meta-data/iam/security-credentials/` which returns the name of the role for that pod to use. Then you make a subsequent call to get the actual credentials from the STS service. If you run `aws sts get-caller-identity --debug` from the command line then you can see that part here

```
58,017 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2020-03-18 20:17:59,020 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2020-03-18 20:17:59,021 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 42
2020-03-18 20:17:59,021 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
2020-03-18 20:17:59,022 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials
```

If you're going to block access to the metadata API then you're not going to be able to authenticate using those credentials, which is why you get the failure above. 

To get around this, then you are going to need to provide your credentials to clouddriver for AWS in some other way. Your options for this are

1) set the environment variables in halyard service settings. In this approach you would create a file called `clouddriver.yml` in ~/.hal/default/service-settings/ and in there put
```
env:
  AWS_ACCESS_KEY_ID: <AWS ACCESS KEY>
  AWS_SECRET_ACCESS_KEY: <AWS SECRET ACCESS KEY>
```
2) mount your aws credentials at /home/spinnaker/.aws/credentials instead. You can do this by generating the ~/.aws/credentials file using the `aws configure` command and then copying it into a secret, which you mount in your clouddriver pod by defining it in the same clouddriver.yml service settings described above with something like
```
kubernetes:
  volumes:
     id: my-secret-name
     mountPath: /home/spinnaker/.aws/
     type: secret
```

you would then create the secret in your kubernetes cluster with something like
```
kubectl -n spinnaker create secret generic my-secret-name --from-file=credentials=/home/myuser/.aws/credentials
```

Once you've got creds manually attached to the pod, you'll no longer need to reach out to the metadata api.

Good luck! Let me know if you run into more trouble.

**Comment by avram** [comment]
@clanesf I think the report is based on this approach to binding IAM roles  (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), which runs all access to IAM through an OIDC provider on the cluster, a feature only supported in later AWS SDK versions.

**Comment by kskewes** [comment]
Yes, without Metadata server access from clouddriver we can complete `--assume-role-with-web-identity` calls. The check could be removed or limited to AWS accounts relying on `--assume-role`.

**Comment by sanjeevpandey19** [comment]
> This will go into 1.20, this is the pull request that bumps the kork version in clouddriver:
> [spinnaker/clouddriver#4442](https://github.com/spinnaker/clouddriver/pull/4442)
> This has been built into the nightly build.
> 
> @sanjeevpandey19 are you able to try out version `master-latest-unvalidated` to confirm that this is fixed?

@clareliguori haven't tried out with the patch that you mentioned, will check this soon and will confirm if this is indeed a fix or not

**Comment by sanjeevpandey19** [comment]
> This is probably failing because if the pod cannot reach out to the metadata API then it isn't able to get the AWS credentials for this pod. This is what your log says.
> 
> The AWS Provider goes and reaches out to
> `http://169.254.169.254/latest/meta-data/iam/security-credentials/` which returns the name of the role for that pod to use. Then you make a subsequent call to get the actual credentials from the STS service. If you run `aws sts get-caller-identity --debug` from the command line then you can see that part here
> 
> ```
> 58,017 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
> 2020-03-18 20:17:59,020 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
> 2020-03-18 20:17:59,021 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 42
> 2020-03-18 20:17:59,021 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
> 2020-03-18 20:17:59,022 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials
> ```
> 
> If you're going to block access to the metadata API then you're not going to be able to authenticate using those credentials, which is why you get the failure above.
> 
> To get around this, then you are going to need to provide your credentials to clouddriver for AWS in some other way. Your options for this are
> 
> 1. set the environment variables in halyard service settings. In this approach you would create a file called `clouddriver.yml` in ~/.hal/default/service-settings/ and in there put
> 
> ```
> env:
>   AWS_ACCESS_KEY_ID: <AWS ACCESS KEY>
>   AWS_SECRET_ACCESS_KEY: <AWS SECRET ACCESS KEY>
> ```
> 
> 1. mount your aws credentials at /home/spinnaker/.aws/credentials instead. You can do this by generating the ~/.aws/credentials file using the `aws configure` command and then copying it into a secret, which you mount in your clouddriver pod by defining it in the same clouddriver.yml service settings described above with something like
> 
> ```
> kubernetes:
>   volumes:
>      id: my-secret-name
>      mountPath: /home/spinnaker/.aws/
>      type: secret
> ```
> 
> you would then create the secret in your kubernetes cluster with something like
> 
> ```
> kubectl -n spinnaker create secret generic my-secret-name --from-file=credentials=/home/myuser/.aws/credentials
> ```
> 
> Once you've got creds manually attached to the pod, you'll no longer need to reach out to the metadata api.
> 
> Good luck! Let me know if you run into more trouble.

@clanesf this is regarding the use service account straigh away to be used with pods, iam role attchement to service account provided though an OIDC provider, cann't use harded access/secret keys

**Comment by clareliguori** [comment]
Note this guidance to set the AWS_REGION environment variable in order for this to work:
https://github.com/spinnaker/spinnaker/issues/5521#issuecomment-601707130

**Comment by clareliguori** [comment]
Closing as rrijkse@ was able to validate this on Fargate (where ec2 metadata is also blocked)

**Comment by kskewes** [comment]
If you are using IRSA and `--assume-role` for EC2 Providers then you still need access to metadata server on startup of clouddriver-caching at least.
Just tested with access (succeeds), then removed it (still succeeds), then finally redeploy without netpol (fails).

**Comment by kskewes** [comment]
Sorry please disregard, I had pulled in another account without role setup in AWS IAM.
