### ISSUE TITLE
Deck not updating JSON with default account

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5579]
### Issue Summary:
When creating a `Deploy (Manifest)` stage, Deck does not update the JSON `account` field in the stage.

![image](https://user-images.githubusercontent.com/29067941/76763178-60ba2a00-6771-11ea-84cf-c7327f5a503e.png)

![image](https://user-images.githubusercontent.com/29067941/76763217-76c7ea80-6771-11ea-9aa7-99505e34d91c.png)

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.19.0

### Feature Area:
Deck

### Steps to Reproduce:
- Setup Spinnaker without any other account
- Create a new application
- Create a new pipeline
- Create a Deploy (Manifest) stage

**Comment by maggieneterval** [comment]
@spinnakerbot cherry-pick 1.19

**Comment by maggieneterval** [comment]
Thanks for reporting, @dpolicastro! We will release a fix for this with the next patch release of 1.19.
