### ISSUE TITLE
ServerGroup details not shown in the UI when "Canary" enabled

### ISSUE THREAD

**Issue by yogeek** [spinnaker/spinnaker#5588]
### Issue Summary:

In the UI, the ServerGroup details section is not displayed when enable "Canary"  is enabled in the Features of an application.

### Cloud Provider(s): 

AWS

### Environment: 

Minnaker on an AWS EC2

### Feature Area: 

Deck UI

### Steps to Reproduce:

On a given application, go to "Config" and enable "Canary" in the "Features" list. Save and go to "Infrastructure" > "Clusters" and select one ServerGroup => the detailed information is not displayed on the right colum
Go back to the application "Config", disable "Canary" in the "Features" list and Save.
Go to "Infrastructure" > "Clusters" and select one ServerGroup => the detailed information is now displayed !

**Comment by maggieneterval** [comment]
Hi @yogeek, thanks for taking the time to open this issue. We chatted about this today at the UI SIG, and our best guess as to why you're experiencing this behavior is that your canary data sources are failing to initialize. Can you check your browser console for any JavaScript errors, and your Network tab for any failed outgoing requests?

Thanks!

**Comment by yogeek** [comment]
@maggieneterval In the browser console, I get this error in the network tab :
```
{"failureCause":"retrofit.RetrofitError: 400 ","error":"Bad Request","message":"400 ","status":400,"url":"http://spin-kayenta.spinnaker:8090/canaryConfig","timestamp":1586211018924}
```

and these in the console :
![image](https://user-images.githubusercontent.com/9500406/78610555-659c6600-7865-11ea-8375-69b748f83216.png)

All infrastructure details panels are impacted (servergroups, instances, loadbalancers and firewalls detailed information are missing from the UI)
Even if one has not configure Canary datasources yet, the fact that one enabled it on an application should not cause these graphical bugs, shouldn't it ?

**Comment by maggieneterval** [comment]
@yogeek thanks for the additional info; 100% agree that canary data source failures should be isolated.

In addition to improving the failure isolation of individual data sources, how would we feel about hiding the Canary feature checkbox in the application config unless `SETTINGS.feature.canary` is enable? [Gate's canary controller is not even enabled unless the canary feature is enabled](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy#L28), so any requests are guaranteed to fail.

 cc @erikmunson & @christopherthielen

**Comment by erikmunson** [comment]
Yeah +1 to using the settings flag to control registering those data sources — we follow that same pattern for other data sources that are tied to optional backend components (e.g. entity tags and keel/managed).
