### ISSUE TITLE
[ECS] Unable to deploy services without target groups

### ISSUE THREAD

**Issue by awsiv** [spinnaker/spinnaker#5592]
### Issue Summary:
According to https://github.com/spinnaker/spinnaker/issues/4475, we should be allowed to deploy non-loadbalanced ecs services, ie without target group. However, it is not possible to do so in v1.19.1 (also v1.18.3, v1.18.5). I haven't tried a version where it was possible TBH. Am I doing something wrong?

### Cloud Provider(s):
aws, ecs

### Environment:
local debian, v1.19.1

### Feature Area:
clouddriver-ecs, orca

### Description:
According to https://github.com/spinnaker/spinnaker/issues/4475, we should be allowed to deploy non-loadbalanced ecs services, ie without target group. However, it is not possible to do so in v1.19.1 (also v1.18.3, v1.18.5). I haven't tried a version where it was possible TBH. Am I doing something wrong?

I get the following error when I don't have targetGroups in json:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/1265825/76897254-b25ad580-6893-11ea-96cc-a57c4d629d92.png">

ECS cluster json:
```
{
  "clusters": [
    {
      "account": "ecs",
      "application": "testapp",
      "associatePublicIpAddress": false,
      "availabilityZones": {
        "us-east-1": [
          "us-east-1a",
          "us-east-1b",
          "us-east-1c",
          "us-east-1d",
          "us-east-1e",
          "us-east-1f"
        ]
      },
      "capacity": {
        "desired": 2,
        "max": 6,
        "min": 2
      },
      "cloudProvider": "ecs",
      "containerMappings": [
        {
          "containerName": "app",
          "imageDescription": {
            "fromContext": true,
            "imageId": "111111.dkr.ecr.us-east-1.amazonaws.com/test/testapp:master-latest",
            "imageLabelOrSha": "111111.dkr.ecr.us-east-1.amazonaws.com/test/testapp:master-latest",
            "stageId": "1"
          }
        }
      ],
      "containerPort": 8080,
      "copySourceScalingPoliciesAndActions": true,
      "dockerImageCredentialsSecret": "None (No registry credentials)",
      "dockerLabels": {},
      "ecsClusterName": "test-ecs",
      "environmentVariables": {},
      "healthCheckGracePeriodSeconds": 2147483647,
      "healthCheckType": "EC2",
      "iamRole": "None (No IAM role)",
      "launchType": "FARGATE",
      "loadBalancedContainer": "app",
      "loadBalancers": [],
      "moniker": {
        "app": "testapp"
      },
      "networkMode": "awsvpc",
      "placementConstraints": [],
      "placementStrategyName": "None",
      "placementStrategySequence": [],
      "preferSourceCapacity": false,
      "provider": "ecs",
      "securityGroupNames": [
        "testap20191209184944756500000002"
      ],
      "securityGroups": [],
      "serviceDiscoveryAssociations": [],
      "strategy": "",
      "subnetType": "test",
      "tags": {
        "Env": "test"
      },
      "taskDefinitionArtifact": {
        "artifactId": "testapp"
      },
      "taskDefinitionArtifactAccount": "testapp",
      "useSourceCapacity": false,
      "useTaskDefinitionArtifact": true
    }
  ],
  "name": "Deploy",
  "stageTimeoutMs": 2700000,
  "type": "deploy"
}
```

**Comment by allisaurus** [comment]
cc: @pkandasamy91

**Comment by allisaurus** [comment]
@spinnakerbot add-label provider/ecs

**Comment by pkandasamy91** [comment]
@awsiv it looks like the validation is failing because you've provided a load balanced container property: `"loadBalancedContainer": "app"`. 

As can be seen [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java#L150-L152), the validation fails when a loadbalancedcontainer is specified, but a targetgroup is not provided. If you remove the loadbalancedcontainer property, you should be able to successfully deploy your app.

**Comment by awsiv** [comment]
@pkandasamy91 you are right.. thanks! 💯 

Also note that you need to remove `healthCheckGracePeriodSeconds` from the json config:
```
Health check grace period is only valid for services configured to use load balancers (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: a76bc98e-b750-4431-b0ad-13d5f1d719a0)
```
