### ISSUE TITLE
Orca will raise 500 NullPointerException for ad-hoc server group creation

### ISSUE THREAD

**Issue by lukmy** [spinnaker/spinnaker#5596]
### Issue Summary:

Orca will raise 500 NullPointerException for ad-hoc server group creation

### Cloud Provider(s):

- kubernetes v2
- kubernetes version: 1.13.2

### Environment:

- spinnaker: 1.19.0

### Feature Area:

- Orca
- kubernetes v2 

### Description:

When use ad-hoc server group creation, deck will raise an error:

![image](https://user-images.githubusercontent.com/1225713/77034960-49d03d80-69e6-11ea-8943-e5e6422fa3f4.png)

tracking to task detail, we found an error from orca:

![image](https://user-images.githubusercontent.com/1225713/77035090-a29fd600-69e6-11ea-839b-f86bb07d5df5.png)

We found the manifest is okay, cause **it can be applied by `Deploy (Manifest)` stage in pipeline**, but cannot be applied by `POST /tasks` API

### Steps to Reproduce:

Approach 1:
- Apply a valid deployment manifest from `Create Server Group` button in deck

Approach 2:
- ad-hoc Edit a existed deployment from deck

Approach 3:
- use `POST /tasks` API to create a valid deployment

### Additional Details:

my task details:

[response.json.txt](https://github.com/spinnaker/spinnaker/files/4352845/response.json.txt)

**Comment by maggieneterval** [comment]
Great catch, @lukmy! We'll release a fix with an upcoming patch of 1.19.

**Comment by lukmy** [comment]
Thanks for quick fix and release. :) @maggieneterval

**Comment by clanesf** [comment]
As a heads up, we're getting similar behavior when trying to run PatchManifest in 1.19.6 when trying to retrieve the source manifest from an existing cluster. Details are in https://github.com/spinnaker/deck/pull/8065. Would really appreciate any advice when you have time!
