### ISSUE TITLE
Deck not refreshing travis execution details section with more than one travis stage

### ISSUE THREAD

**Issue by sergiopena** [spinnaker/spinnaker#5601]
### Issue Summary:
A Pipeline with more than one Travis stage, it displays the same execution detail info for all of them.

### Cloud Provider(s):
Travis 

### Environment:
1.18.x / AWS

### Feature Area:
Deck / UX

### Description:
When a pipeline has more than one Travis stage, the execution details section is fetched when the application is loaded and doesn't get refreshed when you switch between stages.

Looks like the controller fetch the buildInfo from the current stage when it gets initialized and does not contemplate a multiple Travis stage scenario.

### Steps to Reproduce:
1. Create a pipeline with more than one travis stage
2. Run it
3. Try to visualize the execution info for all the stages.

### Additional Details:
Active stage with the correct details
<img width="1078" alt="Screenshot 2020-03-20 at 09 46 26" src="https://user-images.githubusercontent.com/1881230/77150074-51015500-6a93-11ea-9edb-de3a95d55f79.png">

Active stage with no details updated.
<img width="1077" alt="Screenshot 2020-03-20 at 09 46 35" src="https://user-images.githubusercontent.com/1881230/77150079-5494dc00-6a93-11ea-94e5-5508d56df35b.png">

**Comment by maggieneterval** [comment]
Thanks for reporting this bug, @sergiopena!

Marking as beginner-friendly so that it is discoverable by [Spinnaker Gardening Days hackathon](https://github.com/spinnaker-hackathon/gardening) participants. Please feel free to reach out to me here or on Slack (@maggieneterval) if you would like help contributing a fix for this issue!

**Comment by sergiopena** [comment]
Hi @maggieneterval 

I've opened a PR with a patch for this issue in deck https://github.com/spinnaker/deck/pull/8114

**Comment by maggieneterval** [comment]
Huge thanks to @sergiopena for submitting a fix for this bug! 🎉
