### ISSUE TITLE
Spinnaker only listens to localhost

### ISSUE THREAD

**Issue by ervansetiawan** [spinnaker/spinnaker#561]
I installed Spinnaker using InstallSpinnaker.sh on Ubuntu (AWS). I can't seem to access it using the server IP / DNS name. Accessing it using localhost works. 

This is my netstat -l output.

$ netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp        0      0 localho:afs3-fileserver *:*                     LISTEN
tcp        0      0 localhost:43707         *:*                     LISTEN
tcp        0      0 localhost:7199          *:*                     LISTEN
tcp        0      0 localhost:9000          *:*                     LISTEN
tcp        0      0 localhost:9160          *:*                     LISTEN
tcp        0      0 localhost:6379          *:*                     LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
tcp6       0      0 localhost:8087          [::]:*                  LISTEN
tcp6       0      0 localhost:8089          [::]:*                  LISTEN
tcp6       0      0 localhost:http-alt      [::]:*                  LISTEN
tcp6       0      0 localhost:9042          [::]:*                  LISTEN
tcp6       0      0 localhost:8083          [::]:*                  LISTEN
tcp6       0      0 localhost:8084          [::]:*                  LISTEN
tcp6       0      0 localhost:8085          [::]:*                  LISTEN

**Comment by dpeterka** [comment]
There is no authentication on the services so they are currently bound to local host since the services have admin access to your environment.  A few ways ways you can remove this restriction:
1) Edit /etc/apache/ports.conf and remove change Listen 127.0.0.1:9000 to Listen 9000
1a) Add a reverse proxy for ports you wish to open in Apache
2) You may edit service files in /opt/spinnaker/conf to disable the bind to local host.  Change localhost to domain name or 0.0.0.0

**Comment by ervansetiawan** [comment]
That makes sense. I am closing this issue.

**Comment by dgarc23** [comment]
can someone help me with this?  Im fighting with this with no luck....
this commands run perfect  
curl localhost:9000
curl public_ip:9000

but not from other machines....

**Comment by dgarc23** [comment]
fixed changing from localhost to 0.0.0.0 in apache config files and /opt/spinnaker/conf

**Comment by evaldasou** [comment]
Hey guys,

Working on same issue. My issue is I see not spinnaker dashboard at IP:9000 , but Apache2 html page?
Any ideas what's wrong here? 

Thanks

**Comment by lwander** [comment]
If you've installed via halyard this will help: https://blog.spinnaker.io/exposing-spinnaker-to-end-users-4808bc936698

**Comment by reysravanga** [comment]
Hi @evaldasou,

Change the config in apache2/sites-enables/spinnaker.cfg, "localhost:9000" to 0.0.0.0:9000 and restart apache service spinnaker will be up with your publicip

Thanks
Sravan

**Comment by Anchal-kansal** [comment]
Hi @reysravanga, i am stuck with the same issue, can you help?
I am able to telnet/curl from within the box using localhost as well as ip, but from public internet, it is not accesible.
"localhost:9000" to 0.0.0.0:9000, it is already done in my file, yet it is not working. Is there any other settings that I am missing?

**Comment by Anchal-kansal** [comment]
> fixed changing from localhost to 0.0.0.0 in apache config files and /opt/spinnaker/conf

hi @dgarc23 , in which file did u change localhost to 0.0.0.0 in /opt/spinnaker/config

**Comment by andrewcheny** [comment]
If you installed Spinnaker on distributed form (a k8s cluster) there is no /opt/spinnaker/config to edit. I solved the issue by setting up an Nginx reverse proxy to listen on some port (e.g. 9001) and point to localhost:9000. [Here](https://www.keycdn.com/support/nginx-reverse-proxy) is how to setup the reverse proxy.
