### ISSUE TITLE
Spinnaker forces the apiVersion to extensions/v1beta1

### ISSUE THREAD

**Issue by katsew** [spinnaker/spinnaker#5612]
### Issue Summary:

When we deploy manifest of Deployment or Replicaset with apiVersion `apps/v1`, Spinnaker change their version to `extensions/v1beta1`.

### Cloud Provider(s):

GCP (GKE)

### Environment:

```
hal --version
1.31.1-20200207105616
spinnaker 1.18.4
```

### Feature Area:

clouddriver
kubernetes provider

### Description:

We expect that Spinnaker deploys exact the same apiVersion we defined in the manifest.

### Steps to Reproduce:

Deploy manifest of Deployment or Replicaset with apiVersion: apps/v1.

### Additional Details:

We encountered this issue with kubernetes provider, both v1 and v2.

UPDATE:
If we open the infrastructure > select deployment > deployment actions > Edit,
we have the correct apiVersion.
![Screen_Shot_2020-03-24_at_14_37_12](https://user-images.githubusercontent.com/2446460/77392186-b5971980-6ddd-11ea-9755-2a4b70e0e32f.png)

However, if we see the pipeline > Deploy Status > YAML, our deployment's apiVersion becomes `extensions/v1beta1`.
![Screen_Shot_2020-03-24_at_14_39_45](https://user-images.githubusercontent.com/2446460/77392221-c6e02600-6ddd-11ea-85ba-40e397275a5a.png)

UPDATE:
We test deploying Deployment and ReplicaSet to 1.16 cluster.
Here is the result:

Deployment with `apps/v1beta1` is failed to deploy
Deployment with `extensions/v1beta1` is failed to deploy
Replicaset with `extensions/v1beta1` is failed to deploy

Both deployment is done with kubernetes-v2 provider.

error message:
```
Deploy failed: error: unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta1"
```

**Comment by ezimanyi** [comment]
@katsew : What you're seeing here is the behavior at the Kubernetes cluster level, and not anything that Spinnaker itself does.

Regardless of what `apiGroup` you specify when creating a resource, calls to `kubectl get` will still return the `extensions` group for compatibility reasons for Kubernetes <= 1.15.  There's a brief comment referencing that on kubernetes/kubernetes#61430, and @maggieneterval and I just tested it against a 1.13 and a 1.16 cluster.

On the 1.13 cluster, even when applying a deployment with `apiGroup: apps/v1`, the result from `kubectl get` returns `apiVersion: extensions/v1beta1`.  On a 1.16 cluster, the result show `apiVersion: apps/v1`.  This matches what would be expected from the above comment, where the older API group is returned until such time as that API group is completely removed.

There's a [blog post](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) on the deprecation of some API groups in Kubernetes 1.16.  That explains the updated part of the issue, where you are unable to deploy using these deprecated API groups to a cluster running 1.16.

But in summary, the behavior noted here is reflecting the behavior of Kubernetes itself and not anything coming from Spinnaker.

**Comment by iainwo** [comment]
Hi all - just looking to document, a similar problem and solution for readers like me who came by way of this thread by the same situation:

#### Problem

Had this same problem with a different symptom. In my case, during K8 Manifest Deployments Clouddriver would reject these underlying alterations - and cause the deploy to fail with a "Waiting for Manifest to Stabilize" error.

#### Cause

Clouddriver validates extensions/versions.

V7 allows for beta1: https://github.com/spinnaker/clouddriver/blob/version-7.3.4/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesReplicaSetHandler.java#L165.

V8+ doesnt. 

#### Solution

Perhaps theres a compatability matrix (of k8 version to Spinnaker) - but I haven't read it 😅. I solved my issue by downgrading Clouddriver to a v7 variant.
