### ISSUE TITLE
attempt to bake a manifest results in a rosco error

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5625]
### Issue Summary:
Trying to bake a manifest, getting this error:
_Bake failed: Error: file '/tmp/rosco-6077017291324877178/6fd7e411-ec21-40c6-a3fb-339f132d313f' does not appear to be a gzipped archive; got 'text/plain; charset=utf-8'_

### Cloud Provider(s):
kubernetes

### Environment:
all spinnaker versions (current 1.19.2)

### Feature Area:
orca/rosco

### Description:
my pipeline has an embedded artifact and attempts to bake a manifest out of it. The Bake Manifest stage fails:

> Exception ( Create Bake )
> Bake failed: Error: file '/tmp/rosco-6077017291324877178/6fd7e411-ec21-40c6-a3fb-339f132d313f' does not appear to be a gzipped archive; got 'text/plain; charset=utf-8'
> 
>

### Steps to Reproduce:
Use the provided pipeline to observe the aforementioned error:
`
{
  "appConfig": {},
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "cb258977-4685-4aac-9eb7-1f279b12f446",
        "name": "Selenium server manifest",
        "reference": "YXBpVmVyc2lvbjogbmV0d29ya2luZy5rOHMuaW8vdjFiZXRhMQpraW5kOiBJbmdyZXNzCm1ldGFkYXRhOgogIG5hbWU6IHNlbGVuaXVtLWNocm9tZQpzcGVjOgogIHJ1bGVzOgogICAgLSBob3N0OiBzZWxlbml1bS1jaHJvbWUubG9jYWwKICAgICAgaHR0cDoKICAgICAgICBwYXRoczoKICAgICAgICAgIC0gYmFja2VuZDoKICAgICAgICAgICAgICBzZXJ2aWNlTmFtZTogc2VsZW5pdW0tY2hyb21lLXN2YwogICAgICAgICAgICAgIHNlcnZpY2VQb3J0OiA0NDQ0Ci0tLQphcGlWZXJzaW9uOiB2MQpraW5kOiBTZXJ2aWNlCm1ldGFkYXRhOgogIG5hbWU6IHNlbGVuaXVtLWNocm9tZS1zdmMKc3BlYzoKICBwb3J0czoKICAgIC0gbmFtZTogaHR0cAogICAgICBwb3J0OiA0NDQ0CiAgICAgIHByb3RvY29sOiBUQ1AKICBzZWxlY3RvcjoKICAgIGFwcDogc2VsZW5pdW0tY2hyb21lCi0tLQphcGlWZXJzaW9uOiBhcHBzL3YxCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgbGFiZWxzOgogICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICBuYW1lOiBzZWxlbml1bS1jaHJvbWUtZGVwbG95bWVudApzcGVjOgogIHJlcGxpY2FzOiAxCiAgc2VsZWN0b3I6CiAgICBtYXRjaExhYmVsczoKICAgICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgYXBwOiBzZWxlbml1bS1jaHJvbWUKICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgICAgLSBpbWFnZTogJ3NlbGVuaXVtL3N0YW5kYWxvbmUtY2hyb21lLWRlYnVnOjMuMTQxLjU5JwogICAgICAgICAgbmFtZTogbmdpbngKICAgICAgICAgIHBvcnRzOgogICAgICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDQ0NDQKICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgICAgLSBtb3VudFBhdGg6IC9kZXYvc2htCiAgICAgICAgICAgICAgbmFtZTogZHNobQogICAgICB2b2x1bWVzOgogICAgICAgIC0gZW1wdHlEaXI6CiAgICAgICAgICAgIG1lZGl1bTogTWVtb3J5CiAgICAgICAgICBuYW1lOiBkc2htCg==",
        "type": "embedded/base64"
      },
      "displayName": "Selenium server manifest",
      "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b",
      "matchArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "33041425-001f-4cb9-8bf9-542b09190b5c",
        "name": "Selenium server manifest",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": false
    }
  ],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "alexandert",
  "limitConcurrent": true,
  "parameterConfig": [],
  "spelEvaluator": "v4",
  "stages": [
    {
      "evaluateOverrideExpressions": true,
      "expectedArtifacts": [
        {
          "defaultArtifact": {
            "id": "0fc95257-93b8-418d-ac03-6195ecb2654a",
            "type": "embedded/base64"
          },
          "displayName": "Bake Selenium Server manifest",
          "id": "ab99bc75-bfd4-417d-a99c-678335e2eb3b",
          "matchArtifact": {
            "id": "c936424f-b14c-430f-bc12-c6637e311581",
            "name": "Bake Selenium Server manifest",
            "type": "embedded/base64"
          },
          "useDefaultArtifact": false,
          "usePriorArtifact": false
        }
      ],
      "inputArtifacts": [
        {
          "account": "embedded-artifact",
          "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b"
        },
        {
          "account": "embedded-artifact",
          "id": "a2a462d2-7a7a-43be-8d04-6060a5cb123b"
        }
      ],
      "name": "Bake Chrome Selenium Server Manifest",
      "namespace": "",
      "outputName": "",
      "overrides": {},
      "refId": "4",
      "requisiteStageRefIds": [],
      "templateRenderer": "HELM2",
      "type": "bakeManifest"
    },
    {
      "account": "k8s-local",
      "cloudProvider": "kubernetes",
      "manifestArtifactAccount": "embedded-artifact",
      "manifestArtifactId": "ab99bc75-bfd4-417d-a99c-678335e2eb3b",
      "manifests": [
        {
          "apiVersion": "networking.k8s.io/v1beta1",
          "kind": "Ingress",
          "metadata": {
            "name": "selenium-chrome"
          },
          "spec": {
            "rules": [
              {
                "host": "selenium-chrome.spin.kollab.link",
                "http": {
                  "paths": [
                    {
                      "backend": {
                        "serviceName": "selenium-chrome-svc",
                        "servicePort": 4444
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "apiVersion": "v1",
          "kind": "Service",
          "metadata": {
            "name": "selenium-chrome-svc"
          },
          "spec": {
            "ports": [
              {
                "name": "http",
                "port": 4444,
                "protocol": "TCP"
              }
            ],
            "selector": {
              "app": "selenium-chrome"
            }
          }
        },
        {
          "apiVersion": "apps/v1",
          "kind": "Deployment",
          "metadata": {
            "labels": {
              "app": "selenium-chrome"
            },
            "name": "selenium-chrome-deployment"
          },
          "spec": {
            "replicas": 1,
            "selector": {
              "matchLabels": {
                "app": "selenium-chrome"
              }
            },
            "template": {
              "metadata": {
                "labels": {
                  "app": "selenium-chrome"
                }
              },
              "spec": {
                "containers": [
                  {
                    "image": "selenium/standalone-chrome-debug:3.141.59",
                    "name": "nginx",
                    "ports": [
                      {
                        "containerPort": 4444
                      }
                    ],
                    "volumeMounts": [
                      {
                        "mountPath": "/dev/shm",
                        "name": "dshm"
                      }
                    ]
                  }
                ],
                "volumes": [
                  {
                    "emptyDir": {
                      "medium": "Memory"
                    },
                    "name": "dshm"
                  }
                ]
              }
            }
          }
        }
      ],
      "moniker": {
        "app": "compute"
      },
      "name": "Deploy Chrome Selenium Server",
      "refId": "5",
      "requiredArtifactIds": [
        "ab99bc75-bfd4-417d-a99c-678335e2eb3b"
      ],
      "requiredArtifacts": [],
      "requisiteStageRefIds": [
        "4"
      ],
      "skipExpressionEvaluation": false,
      "source": "artifact",
      "stageEnabled": {
        "expression": "false",
        "type": "expression"
      },
      "trafficManagement": {
        "enabled": false,
        "options": {
          "enableTraffic": false,
          "services": []
        }
      },
      "type": "deployManifest"
    }
  ],
  "triggers": [],
  "updateTs": "1585318374000"
}
`

**Comment by maggieneterval** [comment]
Hi @atyutyunnik!

It looks like the error you're seeing, `Error: file...does not appear to be a gzipped archive; got 'text/plain; charset=utf-8'` actually originates from Helm ([source code](https://github.com/helm/helm/blob/master/pkg/chart/loader/archive.go#L96)).

The input artifact supplied to the Bake (Manifest) stage must be a gzipped archive (or tarball), so should have a `.tar.gz` file extension. Running `helm package /path/to/your/chart` should generate the gzipped archive for you, which you should then store in source control and supply as an artifact to Spinnaker.

Feel free to check out our [docs](https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/#deploy-helm-charts) for more details. Closing this issue since this does not appear to be a bug with Spinnaker. Thanks!
