### ISSUE TITLE
Unable to disable unique naming of kubernetes resources

### ISSUE THREAD

**Issue by ghostsquad** [spinnaker/spinnaker#5653]
### Issue Summary:

I've setup a dynamically generated pipeline such that I pass in base64 manifests with pre-versioned names. I'd like to disable any sort of additional versioning of these resources, since they are already versioned.

### Cloud Provider(s):

AWS/K8s

### Environment:

1.19.4

### Feature Area:

Kubernetes V2 Provider

### Description:

Spinnaker does some "automatic" binding/versioning of some resources. But this was surprising to me, since I already am versioning my resources. The addition of `-v000` was a surprise and I can't turn off this functionality.

### Steps to Reproduce:

    Define a k8s configmap manifest
    Create a pipeline to deploy the manifest
    Observe the name has a unique suffix added to the name provided

**Comment by maggieneterval** [comment]
Hey @ghostsquad! I think the `strategy.spinnaker.io/versioned` annotation is what you're looking for to disable Spinnaker's default behavior for versioning certain resources. Check out the docs [here](https://www.spinnaker.io/reference/providers/kubernetes-v2/#strategy) for more details!

**Comment by ghostsquad** [comment]
@maggieneterval thank you!
