### ISSUE TITLE
"Find Artifact From Execution" Artifact UI is broken

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#5664]
### Issue Summary:
We have noticed that the Find Artifact From Execution stage no longer properly displays the artifact chooser ui

### Cloud Provider(s):
n/a

### Environment:
1.18.2

### Feature Area:
UI, Pipeline Stage

### Description:
You can no longer use the UI to configure the match artifacts in the Pipeline Execution stage.

### Steps to Reproduce:
1.) Create "Find Artifacts From Execution" stage
2.) Add a new match artifact
3.) THe ui is broken, look at the console to see the error

### Additional Details:
Screenshots: https://imgur.com/a/Jotew9J

**Comment by maggieneterval** [comment]
Closing because this was fixed in [1.18.3](https://www.spinnaker.io/community/releases/versions/1-18-8-changelog#spinnaker-release-1-18-3).
