### ISSUE TITLE
Support Property file for CodeBuild

### ISSUE THREAD

**Issue by vinhlh** [spinnaker/spinnaker#5686]
Before when using Jenkin, there is an option

![image](https://user-images.githubusercontent.com/261283/79434530-1a224e80-8001-11ea-872a-b9fef6e31a2b.png)

to pass properties to later stages.

![image](https://user-images.githubusercontent.com/261283/79434626-3aeaa400-8001-11ea-8062-c848ca8529d2.png)
(${ #stage('Build')['context']['ENTRY_SCRIPT'] })

But now when switching to CodeBuild, I can't find any way yet.

**Comment by Kaixiang-AWS** [comment]
@vinhlh Does my PR above address your issue?

**Comment by vinhlh** [comment]
@Kaixiang-AWS This is great, probably will solve my issue, thank you.

cc @DeKal
