### ISSUE TITLE
Clouddriver fails to download valid Helm chart

### ISSUE THREAD

**Issue by razvan-ig** [spinnaker/spinnaker#5688]
### Issue Summary:
When adding a step of type Bake, a valid .tgz from a non-authenticated HTTP location works if added as no-auth-http-account with the full URL, but fails if added via a Helm repo

If using the Deck web interface, when selecting Helm account, the drop-down with charts is populated, and for each one the available releases are shown. But, when triggering the pipeline, the following is logged:

spin-clouddriver-5547bd988c-tbv66 clouddriver 2020-04-16 13:04:13.797 ERROR 1 --- [        task-88] c.n.s.c.artifacts.helm.IndexParser       : Failed to resolve reference url:local://chart-name/chart-name-x.y.z.tgz

Tested with multiple releases of Spinnaker 1.19.x over the past month

**Comment by ajordens** [comment]
This might be something the Kubernetes SIG could help with ... you may also consider pinging #kubernetes on the OSS slack.

**Comment by maggieneterval** [comment]
Hi @razvan-ig! Thanks for reporting this issue.

We'd love to try to reproduce this to make sure there is not a bug with Helm artifact accounts. Would you be able to share the following (with any sensitive values omitted)?
- Pipeline JSON for a functioning pipeline (non-authenticated HTTP)
- Pipeline JSON for a non-functioning pipeline (Helm artifact type)
- Account configuration for your Helm account (from your Hal config)

**Comment by angelcervilla** [comment]
hi @razvan-ig 

FYI I had a similar issue with Artifactory, which is our repository for Helm charts.

So, the issue I had there is that when clouddriver retrieved the index.yaml file from our local Helm repository, and the URL for charts looked exactly like yours, and for evident reasons that URL is not correct. 

In our case, with Artifactory the solution was to use virtual repositories, which generated correct URL's for the chart, but I don't know if it's your case too. Could you download the index.yaml from the Helm repository and see if it looks correct?

Hope it helps

**Comment by razvan-ig** [comment]
That was it, thank you for the hint!
