### ISSUE TITLE
How to update orca config (webhook stages) using Halyard?

### ISSUE THREAD

**Issue by ghostsquad** [spinnaker/spinnaker#5689]
### Issue Summary:

How to create a custom webhook stage in halyard?

### Cloud Provider(s):

AWS/K8s/Halyard

### Environment:

1.19.2

### Feature Area:

Halyard, Custom Webhook Stages

### Description:

The following page describes how create a pre-defined webhook type (that has the benefit of keeping some thing secret like Authorization header)

https://www.spinnaker.io/guides/operator/custom-webhook-stages/

We are using halyard to manage spinnaker and spinnaker configuration, so I'm unsure how to edit the config using `halyard`. None of the halyard commands seem to touch on this.

**Comment by maggieneterval** [comment]
Hi @ghostsquad! Your [configuration for custom webhook stages](https://www.spinnaker.io/guides/operator/custom-webhook-stages/#creating-a-custom-webhook-stage) belongs in your [Orca custom profile](https://www.spinnaker.io/reference/halyard/custom/#custom-profiles). I think you're correct that these are not configurable with the Halyard CLI. Feel free to post in [Spinnaker Slack](https://join.spinnaker.io/) if you're still having trouble!
