### ISSUE TITLE
Spinnaker installation problem

### ISSUE THREAD

**Issue by bilalsbl** [spinnaker/spinnaker#5690]
Hi,
i am also trying to deploy spinnaker offline, followed combination of approaches and still no luck, please help me, i am struggling on this from last 30 days. or the question is, can we install spinnaker in behind proxy setup?

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms$ ls -a**
. .. bom clouddriver deck echo fiat front50 gate igor kayenta orca rosco

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms$ cd bom/**
**ubuntu@ubuntu-virtual-machine:~/.hal/.boms/bom$ ls -a**
. .. 1.10.1.yml pull_sub_components.sh

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms/bom$ hal -v**
1.33.0-20200325200017

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms/bom$ vi 1.10.1.yml**
version: 1.10.1
timestamp: '2018-10-24 15:31:30'
services:
echo:
version: local:2.1.0-20181003100130
commit: d20259cd47acd432670dcbddd8191eabbdbf7a4e
clouddriver:
version: local:4.0.1-20181024113115
commit: ad521d622193bd36b90f7c8b3fb453044222cd72
deck:
version: local:2.5.1-20181018042808
commit: 9a096f216be8bf36da14f2f5faa15e94e0a407c5
fiat:
version: local:1.1.0-20181012042808
commit: b1fd0b386534dd170f61c845ee8cda9a5865de82
front50:
version: local:0.13.0-20181005212906
commit: 62da4dc86c663230d897dc8da5ffbbb2c7793bbe
gate:
version: local:1.2.0-20181016042808
commit: 0b204b7b4e36819b2f469dd3850dc89b45a50bf8
igor:
version: local:0.13.0-20181003100130
commit: a4fd89756144d4b0722dc43ee679b9ae51a75171
kayenta:
version: local:0.4.0-20180928152808
commit: 788433f454505e7848d185868ed78d73ac0ef4cd
orca:
version: local:1.1.0-20181003100130
commit: bde9d946c68b8305e7ecd48c045a52eaa9b63cbc
rosco:
version: local:0.8.0-20181003100130
commit: 2f1a4f856b04971fe0fa04c7d402ee8f03827f61
defaultArtifact: {}
monitoring-third-party:
version: local:0.9.0-20180913172809
commit: 1559f0a03c2c1d88bf07a164e1c9c21a7c5e6af4
monitoring-daemon:
version: local:0.9.0-20180913172809
commit: 1559f0a03c2c1d88bf07a164e1c9c21a7c5e6af4
dependencies:
redis:
version: 2:2.8.4-2
consul:
version: 0.7.5
vault:
version: 0.7.0
artifactSources:
debianRepository: https://dl.bintray.com/spinnaker-releases/debians
dockerRegistry: gcr.io/spinnaker-marketplace
gitPrefix: https://github.com/spinnaker

**execution**:
**hal config version edit --version local:1.10.1 --no-validate**

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms/bom$ sudo hal deploy apply --no-validate**

Get current deployment
Success
Prep deployment
Success
Preparation complete... deploying Spinnaker
Get current deployment
Success
Apply deployment
Failure
Validation in Global:
! ERROR Error retrieving contents of archive packer.tar.gz

Failed to deploy Spinnaker.

**ubuntu@ubuntu-virtual-machine:~/.hal/.boms/bom$ cd /home/ubuntu/.hal/default/profiles**

**ubuntu@ubuntu-virtual-machine:~/.hal/default/profiles$ ls**
front50-local.yml

**ubuntu@ubuntu-virtual-machine:~/.hal/default/profiles$ vi front50-local.yml**
spinnaker.s3.versioning: false

**ubuntu@ubuntu-virtual-machine:~/.hal/default/profiles$ cd /opt/spinnaker/config**

**ubuntu@ubuntu-virtual-machine:/opt/spinnaker/config$ ls**
halyard-local.yml halyard-user halyard.yml

**ubuntu@ubuntu-virtual-machine:/opt/spinnaker/config$ vi halyard-local.yml**
spinnaker.config.input.gcs.enabled: false

**ubuntu@ubuntu-virtual-machine:/opt/spinnaker/config$ vi halyard.yml**
halyard:
halconfig:
directory: /home/ubuntu/.hal

spinnaker:
artifacts:
debianRepository:
dockerRegistry:
googleImageProject:
config:
input:
bucket: halconfig

**Comment by maggieneterval** [comment]
Hi @bilalsbl, I'm sorry to hear you've been struggling with your Spinnaker installation for 30 days! I'd recommend asking for help with your offline installation in [Spinnaker Slack](https://join.spinnaker.io/) since we try to reserve GitHub issues for bug reports and feature requests. The #dev and #operations channels could be a good start! 😄

**Comment by aleon1220** [comment]
man get started by using minnaker that run on K3S in any compute instance 
https://github.com/armory/minnaker

**Comment by bilalsbl** [comment]
> Hi @bilalsbl, I'm sorry to hear you've been struggling with your Spinnaker installation for 30 days! I'd recommend asking for help with your offline installation in [Spinnaker Slack](https://join.spinnaker.io/) since we try to reserve GitHub issues for bug reports and feature requests. The #dev and #operations channels could be a good start! 😄

Thank you maggieneterval

**Comment by sramek5** [comment]
I have same problem, I just get the error:
`Unexpected exception: java.lang.NumberFormatException: For input string: "local:1"`, because it still ignores local BOM and wants to validate that in GCS.

Another step was to turn off public connection to gcs (because it cannot reach it):
```
spinnaker:
      artifacts:
        docker: dcreq.service.consul/prod
      config:
        input:
          gcs:
            enabled: false
```
 in `/opt/spinnaker/config/halyard-local.yml`, but it did not work either.
Now it gives me: 
```
No profile reader exists to read '6.7.3-20200401190525'.
  Consider setting 'spinnaker.config.input.gcs.enabled: true' in
  /opt/spinnaker/config/halyard.yml
```

I do not reader to valid version.yaml, I am stuck here and cannot move further.
