### ISSUE TITLE
RunJob/DeployManifest fails Binding Artifact by ID

### ISSUE THREAD

**Issue by andrijaperovic** [spinnaker/spinnaker#5692]
### Issue Summary:

Exception ( Run Job )
Unexpected Task Failure

### Cloud Provider(s):
kubernetes

### Environment:
GKE / GKE On-Prem (Both)

### Feature Area:
Orca

### Description:
Creating a spinnaker pipeline from a pipeline template which refers to both deployManifest and runJob stages. The pipeline is otherwise working normally when not using a template. 
During the runJob portion of the stage, an NPE is thrown, which results in an en unexpected task failure. The templateVariables are being interpolated correctly from the pipeline template. ID's and Display Names are uniquely defined within the template. 

`{
id: "01E64KQX49TTHEPA9D7JDPP8FA",
refId: "19",
type: "runJob",
name: "Create/Upgrade Config DB Schema (Job)",
startTime: 1587145352777,
endTime: 1587145352960,
status: "TERMINAL",
context: {
exception: {
exceptionType: "NullPointerException",
shouldRetry: false,
details: {
stackTrace: "java.lang.NullPointerException at com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.lambda$getBoundArtifactForId$8(ArtifactUtils.java:165) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631) at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631) at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) at com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.getBoundArtifactForId(ArtifactUtils.java:166) at com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.getBoundArtifactForStage(ArtifactUtils.java:129) at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.getManifestArtifact(ManifestEvaluator.java:171) at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.getManifestsFromArtifact(ManifestEvaluator.java:126) at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.getManifests(ManifestEvaluator.java:110) at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestEvaluator.evaluate(ManifestEvaluator.java:102) at com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesJobRunner.getOperations(KubernetesJobRunner.java:59) at com.netflix.spinnaker.orca.clouddriver.tasks.job.JobRunner$getOperations.call(Unknown Source) at com.netflix.spinnaker.orca.clouddriver.tasks.job.RunJobTask.execute(RunJobTask.groovy:71) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:129) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:378) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:127) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt) at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92) at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:126) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:208) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:67) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:45) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:84) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:45) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:93) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:73) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:59) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:201) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:87) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:72) at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36) at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:72) at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69) at com.netflix.spinnaker.q.QueueProcessor$callback$1$1.run(QueueProcessor.kt:89) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) ",
error: "Unexpected Task Failure",
errors: [ ]
},
operation: "runJob",
timestamp: 1587145352895
},
manifestArtifactId: "job_create-upgrade-config-db-smf-eng",
application: "scai",
cloudProvider: "kubernetes",
namespace: "scai",
cloudProviderType: "kubernetes",
moniker: {
app: "scai"
},
source: "artifact",
manifestArtifactAccount: "callidus-open-source",
notifications: [ ],
account: "rgw-eng",
skipExpressionEvaluation: false
},`

### Steps to Reproduce:
Create a pipeline template which has an artifact of type GCS and reference the artifact in a pipeline stage using manifestArtifactId and manifestArtifactAccount, with cloudProvider kubernetes and cloudProviderType kubernetes. 

### Additional Details:

Spinnaker Version: 1.19.5

**Comment by andrijaperovic** [comment]
@ajordens could you please tag the issue in the appropriate category?

**Comment by andrijaperovic** [comment]
Thank you!

**Comment by ezimanyi** [comment]
@andrijaperovic : Do mind sharing the contents of the `expectedArtifacts` section of the fully-hydrated pipeline (minus of course any sensitive data)?

Based on the stacktrace and looking at the code, it seems like one of the entries in `expectedArtifacts` has an ID that is not defined, which is what is causing the NPE.  I know you noted above that the IDs/names are unique, but I wanted to check if you were referring to the artifacts themselves or the defined `expectedArtifacts` in the pipeline.

Somehow the code is ending up with `expectedArtifact.getId() == null` so my first guess would be that there's an entry in that list without an ID defined.  If that's not it, then I'm really not sure what it could be as the `id` field is immutable so there's no way that it could be accidentally cleared by code.

**Comment by ezimanyi** [comment]
In spinnaker/kork#667, I improved the null-safety of the `ExpectedArtifact` class so this error should no longer appear as of Spinnaker 1.21.  That being said, per the above comment it seems like this is due to a misconfiguration where an expected artifact did not have an ID defined.  Please feel free to re-open if this is reproducible in cases where all expected artifacts have a defined `id`.  Thanks!

**Comment by andrijaperovic** [comment]
Thank you @ezimanyi ! I believe you are in fact correct, this was related to a misconfiguration with respect to `expectedArtifact` id's not being properly configured in the pipeline JSON, thank you however for adding the null safety!
