### ISSUE TITLE
Pipeline-level custom notification text editor steals focus

### ISSUE THREAD

**Issue by eaceaser** [spinnaker/spinnaker#5693]
### Issue Summary:
Editing the custom messages for pipeline-level notifications steals focus after each character.

### Feature Area:
Deck

### Environment:
* Spinnaker 1.19.5
* Firefox 75.0 and Chromium 81.0.4044.113 (issue occurs in both)

### Description:
When typing in a custom message for pipeline-level notifications, focus is stolen away from the textbox after each character is typed. There are no obvious errors in the javascript console.

### Steps to Reproduce:
Create a pipeline, add a notification. Select a notification type that allows you to add a custom message, and begin typing.

**Comment by ajordens** [comment]
We also have an internal issue tracking this but haven't prioritized the fix yet. 

I'll ask around to see if someone can chime in on what the fix might look like.

**Comment by nerddelphi** [comment]
I have the same issue here in 1.19.7.

In 1.18.4 it doesn't exist.

**Comment by rrijkse** [comment]
Have confirmed this bug is also present on 1.20.0.

**Comment by erikmunson** [comment]
closed via https://github.com/spinnaker/deck/pull/8267
