### ISSUE TITLE
Custom banners push content off the bottom of the screen

### ISSUE THREAD

**Issue by esprehn** [spinnaker/spinnaker#5696]
### Issue Summary:
Custom banners push the pipeline runs off the bottom of the viewport making them inaccessible.

### Cloud Provider(s):
All.

### Environment:
All.

### Feature Area:
UI

### Description:
When displaying a custom banner it adds an additional 30px of height to the header, but that's not accounted for in the styles for spinnaker-content which has height: calc(100% - 40px) which means content gets pushed off the bottom of the screen.

If there's a collapsed pipeline the header row for that pipeline ends up pushed off the bottom of the screen and becomes inaccessible entirely.

I think this bug was introduced in https://github.com/spinnaker/deck/pull/6450 when the banners were added.

.spinnaker-content either needs to be calc(100% - 70px) when the banner is displayed, or the whole page layout could use flexbox instead of calc which is more robust.

ex.

1. Remove the fixed height from spinnaker-content.
2. Add:
```css
   .spinnaker-container { display: flex; flex-direction: column; }
   .spinnaker-content { flex: 1; min-height: 0; }
```

### Steps to Reproduce:
1. Display a custom banner at the top of the page.
2. Go to an executions list that has a bunch of executions.
3. Scroll to the bottom.

Note: This bug can be reproduced on any page, not just the executions list.

**Comment by Chinikins** [comment]
Out of curiosity, is this still an issue for you? I'm not able to reproduce it on spinnaker 1.20.6

**Comment by caseyhebebrand** [comment]
@esprehn  Echoing the previous comment, I am also unable to reproduce this issue. Is this still a problem for you?
