### ISSUE TITLE
UI doesn't show expected artifact section inside configuration

### ISSUE THREAD

**Issue by michalmarszalek-flyr** [spinnaker/spinnaker#5709]
### Issue Summary:
Spinnaker UI doesn't show 'Expected Artifacts' section

### Cloud Provider(s):
GCP, (GKE)

### Environment:
spinnaker 1.17.10
spinnaker 1.18.9
spinnaker 1.19.6

### Feature Area:
UI

### Description:
When pipeline is created Expected artifacts section is not visible.
![image](https://user-images.githubusercontent.com/54277971/80278360-eed0eb00-86f5-11ea-828b-b7138c76d600.png)

When run hal config features edit --artifacts-rewrite true
result:
Was passed main parameter '--artifacts-rewrite' but no main parameter was defined in your arg class

I have updated feature directly in config file so command hal config features returns:
Features(auth=false, fiat=false, chaos=false, entityTags=false, pipelineTemplates=null, artifacts=true, artifactsRewrite=true, mineCanary=null, infrastructureStages=null, travis=null, wercker=null, managedPipelineTemplatesV2UI=null, gremlin=null)

All changes were applied using hal deploy apply

### Steps to Reproduce:
Create pipeline.

### Additional Details:

---

**Comment by SubatomicHero** [comment]
I am also having this exact same issue. Using 1.19.6

**Comment by tunahan7el** [comment]
same here, 1.18.3

**Comment by SubatomicHero** [comment]
To get this working, downgrade Hal to v1.34.0

**Comment by maggieneterval** [comment]
Hi @michalmarszalek-flyr, @SubatomicHero, and @tunahan7el! Apologies for the confusion here. If you enable the `artifacts-rewrite` UI, you will no longer see a separate section for Expected Artifacts. Instead, you'll see each expected artifact listed in the Artifact Constraints section of the triggers it is associated with, and you can edit them from there. Let me know if that makes sense! The [docs](https://www.spinnaker.io/reference/artifacts-with-artifactsrewrite/) might also be helpful.

The artifacts rewrite will be enabled by default in Spinnaker 1.20, and so those Halyard commands will soon no longer have any effect. However, we'll replace the commands shortly in the next Halyard release to prevent confusion for those using pre-1.20 releases.

Thanks!

**Comment by michalmarszalek-flyr** [comment]
Unfortunately hal -v returns Unknown. I have that problem on debian and macOs

**Comment by vuxuanlai** [comment]
Hi @maggieneterval, I'm using v1.19.6, hallyard version 1.35.0. When I run "hal config features edit --artifacts-rewrite true" I got the notice as below:

> bash-5.0$ hal config features edit --artifacts-rewrite true
Was passed main parameter '--artifacts-rewrite' but no main parameter was defined in your arg class


and I can't see "Artifact Constraints" in UI to create expected artifacts. Please help me to resolve it.

**Comment by maggieneterval** [comment]
Please upgrade to Halyard 1.35.1 and this should be resolved. Thank you!

**Comment by myoussef89** [comment]
I have the same issue using "gcr.io/spinnaker-marketplace/halyard:stable" image on K8s
hal -v return Unknown
