### ISSUE TITLE
googlecompute: Error creating instance: time out while waiting for instance to create

### ISSUE THREAD

**Issue by mega-destruction-mega-ball-of-darkness** [spinnaker/spinnaker#5718]
### Issue Summary:
Hi, I use Spinnaker to run a Bake stage, but it always results in a timeout.

### Cloud Provider(s):
GCE

### Environment:
Spinnaker is running on GKE, with GCE provider enabled.

### Feature Area:
Rosco/bake

### Description:
So, I want to create a deployment in GCE using Spinnaker. For that, I created a pipeline in Spinnaker with a `Bake` stage to build the instance template. But, the `Bake` stage always fails with a timeout. It usually happens after more than 8 mins with Packer log showing:
```==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Using image: beartooth-0538402
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-central1-f
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
==> googlecompute: Error creating instance: time out while waiting for instance to create
Build 'googlecompute' errored: Error creating instance: time out while waiting for instance to create

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error creating instance: time out while waiting for instance to create

==> Builds finished but no artifacts were created.
```

I expect the `Bake` stage to finish without any timeout error.

### Steps to Reproduce:
I created a regular pipeline in Spinnaker, adding the `Bake` stage, input my package name and bionic (v18.04) as the base OS. The pipeline I created is triggered by the completion of a Jenkins job producing the Debian package, as stated in this tutorial: https://docs.armory.io/spinnaker-user-guides/baking-images/#baking-in-a-pipeline.

### Additional Details:
I've been searching Google for this issue, but the only thing related to this that I found is perhaps this: https://github.com/hashicorp/packer/issues/8951? I'm not sure.

**Comment by prudhvio33** [comment]
Hi, did this issue got resolved? I am facing similar issue. 

I used packer version 1.8.2 and googlecompute 1.0.13 which are most recent.

Couldn't figure out exact reason for the time out with "packer -debug build <file>". 

Please let me know if I am missing anything.
