### ISSUE TITLE
Cloning Bake (Manifest) stage results in shared artifact uuids

### ISSUE THREAD

**Issue by jaygorrell** [spinnaker/spinnaker#5738]
### Issue Summary:
If you create a Bake (Manifest) stage (ie. Helm) with a base64 artifact produced and then create a new stage as a copy of this stage, you end up with the same artifact ID in the clone. When you later try to use that artifact in a Deploy stage, you can't even click the cloned version in the artifact drop-down.

### Cloud Provider(s):
AWS

### Environment:
EKS

### Feature Area:
Pipelines

### Steps to Reproduce:
1. Create a Bake (Manifest) stage that produces an artifact
2. Clone the stage and change the resulting artifact name
3. Create a Deploy Manifest stage and see that you can only select one of the two artifacts
4. Observe in the Pipeline JSON that the same ID is shared for both artifacts

**Comment by maggieneterval** [comment]
Hi @jaygorrell! This is expected behavior; see https://github.com/spinnaker/spinnaker/issues/4354 for a full discussion.

**Comment by jaygorrell** [comment]
Hey @maggieneterval, thanks for the response. It looks like the discussion there resulted in a partial solution but the original request wasn't really addressed or called out as expected. Did I miss something?

Is there a situation where a user would actually want copy stage to copy IDs, and thus break UI elements like artifact selector drop-downs?

**Comment by maggieneterval** [comment]
Sorry for the confusion; there was indeed a lot of back-and-forth on that issue! To clarify, although there are many possible stage fields, like artifact IDs, that you may need to replace when cloning a stage, there are no plans to add logic that selectively omits certain fields when cloning. Would love to hear more about your use case in case there are any other recommendations we can make, but just want to be transparent that this isn't something the community plans on addressing (as far as I know) given the investment in other tools for pipeline reuse (such as [pipeline templates](https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/create/)).

**Comment by jaygorrell** [comment]
Thanks, I sorta' follow. If the warning is already added to the clone step similar to deployments and I missed it, that's a decent fix.

>Would love to hear more about your use case in case there are any other recommendations we can make

Similar to the linked issue, I was just cloning stages to save time. For example, I have a stage that bakes a manifest from a Helm chart for 3 different environments. I believe all the inputs (chart + values) were probably fine, but the resulting artifact doesn't make sense to copy. 

You mentioned probably not wanting to get into omitting certain fields and I understand wanting to avoid complicated lists of what to copy but a safe rule would probably be any artifact-producing stage should automatically generate a new uuid on clone as a blanket rule for the produced artifact. Everything else should be okay as-is.

As a sidenote, I'd love to talk to someone about pipeline templates a bit. I'm making that migration right now and running into all kinds of (documentation?) issues I'd be happy to discuss. :)

**Comment by maggieneterval** [comment]
Hi @jaygorrell; thanks for taking the time to explain your use case! If you're interested in asking how other folks are handling similar situations with pipeline templates, definitely worth joining the #pipeline-templates channel in [Spinnaker Slack](https://join.spinnaker.io/) or dropping in at the Spinnaker [Kubernetes](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md) or [As-Code SIGs](https://github.com/spinnaker/governance/blob/master/sig-spinnaker-as-code/README.md).

As for a warning when cloning a stage that artifact fields will indeed be cloned, I believe one already exists:

![QdyHzCCNHC4](https://user-images.githubusercontent.com/15936279/81415406-68b19d00-9116-11ea-85ad-32e2bc0a69bc.png)

Thanks!

**Comment by jaygorrell** [comment]
Thanks Maggie - I'm in that channel but it's pretty inactive lately... other than the folks looking for help. :) I'll keep trying though.

That message helps - I did see it but for some reason I thought it applied specifically to deploy stages. The first line says they won't show in the list but they definitely do. I guess that's another issue to file.
