### ISSUE TITLE
"hal --version" shows "Unknown" since Halyard version 1.34.0

### ISSUE THREAD

**Issue by dragon3** [spinnaker/spinnaker#5740]
### Issue Summary:

`hal --version` shows `Unknown` since Halyard version `1.34.0`.

### Environment:

Ubuntu and macOS (probably other environments as well)

### Feature Area:

Halyard

### Description:

`hal --version` doesn't work with Halyard version `1.34.0` or later.

It works properly with previous Halyard versions like 1.33.0:
```console
$ hal --version
1.33.0-20200325200017
```

#### 1. Install Halyard
Follow https://www.spinnaker.io/setup/install/halyard/#install-on-debianubuntu-and-macos

( You can see `Unknown` when you install the latest version as well )
```console
...
x hal
x update-halyard
~/dev/spinnaker
The halyard daemon isn't running yet... starting it manually...
Unknown
```

#### 2. Run `hal --version`

```console
$ hal --version
Unknown
```

#### 3. Test with other Halyard versions

```console
$ sudo update-halyard --version 1.32.0
...
The halyard daemon isn't running yet... starting it manually...
1.32.0-20200311111902

➜  ~ hal --version
1.32.0-20200311111902
```

```console
$ sudo update-halyard --version 1.33.0
...
The halyard daemon isn't running yet... starting it manually...
1.33.0-20200325200017

$ hal --version
1.33.0-20200325200017
```

```console
$ sudo update-halyard --version 1.34.0
...
The halyard daemon isn't running yet... starting it manually...
Unknown

$ hal --version
Unknown
```

```console
$ sudo update-halyard --version 1.35.0
...
The halyard daemon isn't running yet... starting it manually...
Unknown

$ hal --version
Unknown
```

**Comment by dragon3** [comment]
The `--version` command uses `HalCommand.class.getPackage().getImplementationVersion()` result:
https://github.com/spinnaker/halyard/blob/75b41743ea9c52910b3d5b98709dfa9b458c3afd/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java#L65-L66

So I checked `META-INF/MANIFEST.MF` file in `halyard-cli.jar`:

### Halyard 1.33

`META-INF/MANIFEST.MF` file in `halyard-cli-1.33.0-20200325200017.jar` from Halyard 1.33:
```
Manifest-Version: 1.0
Implementation-Title: com.netflix.spinnaker.halyard#halyard-cli;1.33.0
 -20200325200017
Module-Origin: https://github.com/spinnaker/halyard
Build-Date: 2020-03-25_20:06:44
Build-Id: 5213
Implementation-Version: 1.33.0-20200325200017
Module-Owner: netflixoss@netflix.com
Build-Number: 5213
Built-By: jenkins
Change: 1156e2c
Module-Source: /halyard-cli
Branch: master
Built-Status: integration
Gradle-Version: 5.3.1
Build-Job: Build_PrimaryArtifacts
Built-OS: Linux
X-Compile-Target-JDK: 1.8
Build-Host: https://builds.spinnaker.io/
X-Compile-Source-JDK: 1.8
Created-By: 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08 (Oracle Corporation
 )
Module-Email: netflixoss@netflix.com
Build-Java-Version: 1.8.0_242
```

### Halyard 1.34

`META-INF/MANIFEST.MF` file in `halyard-cli.jar` from Halyard 1.34:
```
Manifest-Version: 1.0
```

---

So the `META-INF/MANIFEST.MF` file generation was changed after 1.33 released.
Might it be caused by upgrading `spinnaker-gradle-project`? (https://github.com/spinnaker/halyard/pull/1601)

**Comment by dragon3** [comment]
Is there anything I can help?

Still I haven't figure out what is the root cause and I don't have access to the Jenkins job `Build_PrimaryArtifacts` configuration: https://builds.spinnaker.io/job/Build_PrimaryArtifacts/ 😢 

Current my ideas:
- Add something to generate the same MANIFEST.MF in the `Release` GitHub action
    - (But I'm not sure if the GitHub action is now used for releasing)
- Change the implementation for `hal --version` command to use some other file like `VERSION` file
    - It also needs generating `VERSION` file in CI (GitHub action)

**Comment by talbright** [comment]
This has been bothering me as well, I spent some time yak shaving to try and find it and I didn't get far. The following *would* create the version, but without seeing the intention in the Github build its difficult to know where to fix it:

` $./gradlew -PenablePublishing=true -PossVersion=1.2.3 ....`

**Comment by dragon3** [comment]
@talbright 
Thank you for your comment and help.

>  @plumpy said he would take a look at this further as he has visibility into some of the internal build stuff that's not visible to the open source community at large.

Sounds great. I'm looking forward to his investigation and comment here.

Thanks!

**Comment by plumpy** [comment]
Okay, I verified this fix in `1.36.0-20200521163751`. Yay!

**Comment by dragon3** [comment]
@plumpy 
Thank you for fixing it!
I'm looking forward to the new version halyard 👍

**Comment by talbright** [comment]
Nice work all!
