### ISSUE TITLE
Pipeline execution comments not displaying after page refresh

### ISSUE THREAD

**Issue by sathishavm** [spinnaker/spinnaker#5758]
### Issue Summary:
 We can add comments to every stage in spinnaker, Where comment values can also be dynamic for execution with expressions. 
The comments are displayed correctly in the execution details during execution, but after refreshing the page the comments disappear from the execution details.
FYI: I can see the execution comment in the JSON source under the stages section.

Attached screen cast for reference
![spinnaker](https://user-images.githubusercontent.com/1404500/81654890-b8c88200-93ea-11ea-9727-d9d8e96fb273.gif)
. 
### Cloud Provider(s):
deck
### Environment:
Spinnaker Version: 1.19.7
Deployed in Kubernetes via halyard.

**Comment by maggieneterval** [comment]
Hi @sathishavm, thanks for reporting! I believe that @AbdulRahmanAlHamali fixed this ([PR](https://github.com/spinnaker/deck/pull/8202)), so this should be resolved in 1.20. Do you mind letting us know if upgrading to 1.20 does not resolve this issue for you? Thanks!

**Comment by sathishavm** [comment]
yes, it is working now, thanks @maggieneterval !!
I will close this issue.
