### ISSUE TITLE
Unable to connect to dl.bintray.com

### ISSUE THREAD

**Issue by daanemanz** [spinnaker/spinnaker#576]
When following the tutorial, the `Bake` step in a pipeline fails because the packer script `install_packages.sh` can't connect to dl.bintray.org.

The reason for that is that the EC2 instance that's being created by Packer is set up in the subnet in the VPC, but doesn't get assigned a public IP address. The documentation in the AWS setup steps on [this page](http://spinnaker.io/documentation/getting_started.html) should be updated to enable *Auto-Assign Public IP* when setting up the VPC.

**Comment by daanemanz** [comment]
@tomaslin @duftler I just confirmed that that solved the issue

**Comment by dpeterka** [comment]
I think the packer tempate needs ```associate_public_ip_address (boolean) - If using a non-default VPC, public IP addresses are not provided by default. If this is toggled, your new instance will get a Public IP.```

**Comment by Japh** [comment]
The change suggested by @daanemanz for the Getting Started tutorial (which appears to have been made), hasn't fixed this for me. I enabled `Auto-Assign Public IP` when creating the VPC, but still get this issue.

**Comment by duftler** [comment]
Can you try adding the setting (and setting it to `true`) to the packer template `/opt/rosco/config/packer/aws-ebs.json`? It would go in the `builders` section as per: https://www.packer.io/docs/builders/amazon-ebs.html#associate_public_ip_address

If this works, I'll add it to the template as @dpeterka suggested.

**Comment by Japh** [comment]
@duftler No problem. I've made the config change and then restarted All The Things. Re-running pipeline now...

**Comment by Japh** [comment]
Oh, I also terminated the orphan Packer Builder instance prior to re-running (may not be relevant, but now you have all the details :smile: ).

**Comment by Japh** [comment]
Watching the "View Bakery Details" URL, and things have progressed further than before, so I guess that's fixed it. Thanks!

**Comment by duftler** [comment]
Great. Thanks for the details. Will update the template accordingly.
