### ISSUE TITLE
Custom stage broken in Spinnaker 1.20

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5767]
### Issue Summary:
Some of my Custom Job stages become broken once I upgrade to 1.20. If I go back to 1.19, they are alright

### Cloud Provider(s):
kubernetes

### Environment:
Only in Spinnaker 1.20 (1.19 is fine)

### Feature Area:
orca

### Description:
I wonder if it's related to a post by Ethan in spinnaker's dev channel that announces that Spinnaker no longer adds suffixes in 1.20 for Kubernetes Jobs. Compare pod names:
**1.19**: cloudformation-delete-3fb213f569be1048-ddm4r
**1.20**: cloudformation-delete-ddm4r

As a result, some of my Jobs that execute within one pipeline start failing like this:

_Deploy failed: The Job "cloudformation-delete" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"cloudformation-delete", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/managed-by":"spinnaker", "app.kubernetes.io/name":"email", "controller-uid":"ab43e35b-69dd-4f62-9092-aa8e7095b157", "job-name":"cloudformation-delete"}, Annotations:map[string]string{"artifact.spinnaker.io/location":"", "artifact.spinnaker.io/name":"cloudformation-delete", "artifact.spinnaker.io/type":"kubernetes/job", "moniker.spinnaker.io/application":"email", "moniker.spinnaker.io/cluster":"job cloudformation-delete"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"aws-creds", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(0xc016a4b840), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"cf", Image:"amazon/aws-cli", Command:[]string{"/bin/bash", "-c"}, Args:[]string{"set -vx;\nS3BUCKET=$APP-$ENV.collablynk.com;\n\naws s3 rb --force s3://$S3BUCKET;\n\nfor serviceArn in aws ecs list-services --cluster $APP-$ENV-ecs-cluster --query \"serviceArns\" --output text\ndo\n echo "'$serviceArn'"\n for service in aws ecs describe-services --cluster $APP-$ENV-ecs-cluster --services \"$serviceArn\" --query \"services[].serviceName\" --output text\n do\n aws ecs delete-service --force --cluster $APP-$ENV-ecs-cluster --service $service\n done\ndone\n\nfor SVC in aws ecr describe-repositories --output text --query \"repositories[?starts_with(repositoryName, '$APP-$ENV-')][repositoryName]\"\ndo\n aws ecr delete-repository --force --repository-name $SVC;\ndone\n\naws cloudformation delete-stack --stack-name $APP-$ENV;\n\naws cloudformation wait stack-delete-complete --stack-name $APP-$ENV || echo Failed but who cares..."}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"ENV", Value:"test001-sql-exec", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"AWS_DEFAULT_REGION", Value:"us-west-2", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"APP", Value:"mft", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"aws-creds", ReadOnly:false, MountPath:"/root/.aws", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc021898c18), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc01a623dc0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable_

**Comment by ezimanyi** [comment]
It looks like somehow what's happening here is that your pipeline is trying to update a job, which isn't possible as jobs are immutable.  Along with the [changes in 1.20](https://www.spinnaker.io/community/releases/versions/1-20-1-changelog#kubernetes-v2-run-job-stage) there was also a change that deletes and recreates the job if you supply a `name` rather than a `generateName`.  Can you give an overview of what your pipeline looks like?  Is this a simple one-stage run job, or do you have something more complex where you are using SpEL in later stages to act on jobs in prior stages?

**Comment by atyutyunnik** [comment]
[environment_termination.json.txt](https://github.com/spinnaker/spinnaker/files/4629004/environment_termination.json.txt)

here is my pipeline. Somehow where was no issue with attempted Job updates in 1.19, probably because, even despite calling the same custom stage but with different parameters, Spinnaker added a unique suffix in 1.19

**Comment by atyutyunnik** [comment]
> It looks like somehow what's happening here is that your pipeline is trying to update a job, which isn't possible as jobs are immutable. Along with the [changes in 1.20](https://www.spinnaker.io/community/releases/versions/1-20-1-changelog#kubernetes-v2-run-job-stage) there was also a change that deletes and recreates the job if you supply a `name` rather than a `generateName`. Can you give an overview of what your pipeline looks like? Is this a simple one-stage run job, or do you have something more complex where you are using SpEL in later stages to act on jobs in prior stages?

the `generateNames` helps resolve this issue

**Comment by atyutyunnik** [comment]
an important observation:
  if there are stages when names coincide even, if they in different apps, for example:
```
app1:
  name: job-execute-script

app2:
  name: job-execute-script
```

then the job app2's job-execute-script appears to replace app1's name job. I don't think it's acceptable behavior

**Comment by ezimanyi** [comment]
The comments above are consistent with what was in the [release notes](https://www.spinnaker.io/community/releases/versions/1-20-1-changelog#kubernetes-v2-run-job-stage), notably that:
* Users who want the pre-1.20 behavior of having a random suffix will need to specify `metadata.generateName` instead of `metadata.name`
* If a job specifies only `name` it will replace any prior job with that name every time it is run as jobs are immutable

We are aware that this will require some changes from end-users to update their pipelines to account for the change; but after discussion in the Kubernetes SIG decided that it was a reasonable one-time change (particularly to a reasonably new feature).

The alternative would have been to add Spinnaker-specific annotations that control whether a suffix is added, which creates more of a learning curve for users of Spinnaker who already understand Kubernetes, and makes objects behave differently when applied by Spinnaker vs. when applied directly to Kubernetes.

Obviously, we try to avoid these types of changes, but in this case felt that it was worth the long-term improvement to the stage (and alignment with Kubernetes) and decided to include detailed release notes about the change.

**Comment by atyutyunnik** [comment]
in other words, the users will have to sift through ALL their numerous pipelines that use Run Job (Manifest) to ensure that their Job have unique names??? Otherwise they will have a subtle inconsistent behavior because the unrelated jobs may overlap each other. Even after I saw those changes mentioned in the release notes I didn't realize the significance of the breaking changes and the scope of the required effort until I encountered them.

**Comment by ezimanyi** [comment]
If you have suggestions for how to make the release notes more clear, I would be happy to update them.  We did our best to highlight this in the release notes, but certainly are open to suggestions if you think it is not adequately clear.

**Comment by atyutyunnik** [comment]
1. Such breaking changes should stand out of the crowd of other updates much more, for example:
**_ATTENTION: BREAKING CHANGE: Your Kubernetes Jobs are affected and may not work consistently_**:
**_In order to retain previous behavior, you must MANUALLY update your Kubernetes Job manifests in the following places: Git artifacts, Orca configuration, Spinnaker pipelines._**

P.S. I firsthand observed that weird behavior just because I had two Kuberentes Jobs totally unrelated but that had some generic names such as dockerpush, which was totally fine prior to 1.20. What I saw in the output of one wasn't quite expected for the job and couldn't figure out  why I was getting output from another Job. Do you think other average users will have more luck?

2. However, the problem would haven't been that bad, had the changes been breaking with an immediate visible effect. Quite the contrary, they are subtle and require changes in many places and it's easy to overlook a number of places.

3. Do we have a tool that would upgrade from `metadata.name` to `metadata.generateName` for appropriate manifests for those who are willing to run the upgrade willingly?

**Comment by atyutyunnik** [comment]
4. Release notes alone are far from adequate for this particular case. Can we have a global flag that restores the behavior to that of 1.19, while it's all threshed out?

**Comment by maggieneterval** [comment]
Hi @atyutyunnik, we really appreciate your feedback! Would you like me to add an agenda item for the next meeting of the [Kubernetes SIG](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md) to discuss this further? The Kubernetes SIG is the group of developers and operators that owns Spinnaker's Kubernetes provider. This change was discussed at the Kubernetes SIG on 4/7 and 4/21, and we agreed that the one-time cost of potentially requiring manifest updates was worth the benefits of alignment with native Kubernetes behavior. That said, we'd love to learn more about your specific workflows. I've noticed several issues from you recently and have been meaning to extend a personal invite to the Kubernetes SIG -- we'd love to have you become a part of the SIG community and share feedback! We meet every other Tuesday, and all the meeting details are available on the [SIG page](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md). If you're not able to attend, I'm also happy to share the feedback you've provided here with the rest of the SIG. Let me know!

**Comment by atyutyunnik** [comment]
@maggieneterval, thank you, I have already looked up for and scheduled to crash the party at 10:00 Tue May 19, 2020.

For everyone concerned, just to realize what happened is this analogy: imagine a product that processes both positive and negative numbers and the negative numbers have this specific notation:
```-123.00```

then one day the product changes how it recognizes negative numbers:
```(123.00)```

while treating previous notation of ```-123.00```, which used to designate a negative number, as a positive number and simply putting a release note (which generally no one reads, expecting things to work the same with newer version of software) of the said changes in processing without an attempt to re-format already existing customer data or at least retain the same behavior.

This is how bad this update is. Which is aggravated by its non-immediate effects. So the best and easiest remedy would be to have a global setting restoring prior-1.20 behavior.

**Comment by maggieneterval** [comment]
> @maggieneterval, thank you, I have already looked up for and scheduled to crash the party at 10:00 Tue May 19, 2020.

🎉 Can't wait to see you at the party! Let me know if there's an email address you'd like me to add to the calendar invite. I've added items for this issue and your [artifacts UI issue](https://github.com/spinnaker/spinnaker/issues/5761) to the [agenda](https://docs.google.com/document/d/1db_yw1uru99Byvin4lQgm7aUZ9xMmvsARtEiiNUrmBo/edit#heading=h.n8s5hncvzjcx); looking forward to discussing solutions next week!

**Comment by ezimanyi** [comment]
Thanks for the report, and the constructive discussion at the SIG yesterday!  The above PR (which will be backported to 1.20 for the next patch release) restores the behavior to the 1.19.x behavior.

This is now controlled by `kubernetes.jobs.append-suffix`, which defaults to `true`.  The rollout plan which I propose is:
* This defaults to `true` in 1.20 and 1.21 with a warning printed to the log upon adding a suffix.
* This defaults to `false` in 1.22 (but can still be explicitly set to `true`), so a suffix is not added by default but can be added by flipping this flag.
* The flag is removed in 1.23, and a suffix will not be added.

Regardless of the flag, manifests which explicitly specify `generateName` will have a suffix added by Kubernetes, allowing users to migrate their manifests incrementally during 1.20 and 1.21 (as well as 1.22 if they flip the flag).

I think that this should balance between giving time for users to upgrade any necessary manifests (which is more of a burden than we initially anticipated in discussing this feature) but also avoids having long term flags which ultimately make configuration more confusing.
