### ISSUE TITLE
VPC Subnet field does not get populated

### ISSUE THREAD

**Issue by geVikrant** [spinnaker/spinnaker#5768]
### Issue Summary:
The VPC Subnet field doesn't get populated for AWS accounts in the Spinnaker UI. Because of this, we are not able to create Load Balancers through Spinnaker in AWS accounts.

### Cloud Provider(s):
AWS

### Environment:

 - 1.19.8 (Gilmore Girls A Year in the Life):
   Changelog: https://gist.github.com/spinnaker-release/cc4410d674679c5765246a40f28e3cad
   Published: Mon May 11 13:14:58 UTC 2020

 - 1.20.1 (Drive to Survive):
   Changelog: https://gist.github.com/spinnaker-release/75d50c7b931f1089e710a0e9d1acf8c4
   Published: Mon May 11 13:19:09 UTC 2020

### Feature Area:
 UI

### Description:
When trying to create a load balancer from Spinnaker, the Subnet field does not get populated. 
We have our AWS account added in the spinnaker and when trying to create a application load balancer or classic load balancer, the subnet field in not populated on opening the create page. 

### Steps to Reproduce:
1. Setup AWS as provider for Spinnaker. 
2. Start Spinnaker UI.
3. Create an application. 
4. Click on Create load balancer and select application load balancer. 
5. On the create screen the account is populated.
6. However, the subnet field is blank. 
7. Trying to create a Load balancer without the subnet field selection fails. 

![Screen Shot 2020-05-14 at 10 04 14 AM](https://user-images.githubusercontent.com/64217511/81955109-4f559880-95cf-11ea-9da7-be3defa470b1.png)

### Additional Details:

When we check the chorme DevTool - network, the endpoint for subnet http://localhost:8084/subnets/aws is not called at all.  

For Network Load Balancer - this subnet endpoint is called. Yet the drop-down is not populated.

A similar issue has been marked closed - https://github.com/spinnaker/spinnaker/issues/3242
---

**Comment by akshayabd** [comment]
Just wondering if the subnets tagged correctly?

**Comment by geVikrant** [comment]
@akshayabd Thanks. This worked after tagging the subnets according to the link you shared.

**Comment by geVikrant** [comment]
This worked after tagging the subnets according to the link you shared.

**Comment by swaroop1012** [comment]
The link for the doc has changed to - https://docs.armory.io/continuous-deployment/armory-admin/aws/aws-subnets-configure/
