### ISSUE TITLE
Spinnaker UI OSS and customization support

### ISSUE THREAD

**Issue by BenjaminMalley** [spinnaker/spinnaker#577]
### GOALS
Provide an easy deployment path for the Spinnaker UI with the ability to exclude unused functionality (at the cloud provider level) from the deployed client bundle as well as to provide some high-level configurability (e.g., setting the API host URL, enabling/disabling core features and pipeline stages) through environment variables while allowing the development and integration of non-standard features (e.g., custom pipeline stages).

### PROPOSAL
The current deck repository (https://github.com/spinnaker/deck) will be refactored to create two distinct deployment artifacts: a deployable application (“deployable”) that will be served as a set of static JS files and an npm library (“library”). While each of these deployment artifacts will have a separate webpack build, they will share a single `package.json` and set of Javascript dependencies in `node_modules`. The resulting repository will be laid out as follows:

    deck/
        package.json
        src/
            index.js
            core/
            aws/
            …
            karma.conf.js
            webpack.config.js
        deployable/
            index.js
            index.html
            webpack.config.js
            build.gradle
        .eslintrc
        ...

The `webpack.config.js` in the `src/` folder will emit a single `index.js` file including all of the javascript code and static assets (css, templates, images and fonts) that can be installed via npm and required via webpack, browserify or other front-end module loader. It will bundle all of the third party dependencies specified in `package.json` except for angular and jquery, which will be expected to be provided by consumers of the library. Individual modules can be excluded from the final bundle by setting environment variables in the webpack process. The current `settings.js` block will be replaced by Angular providers with getters and setters for changing those values at runtime.

The `webpack.config.js` in the deployable/ folder will emit a deployable index.html and `index.js` bundle. The deployable webpack process will use webpack’s alias functionality to build the code in the `src/` folder with an internal dependency on Angular & jQuery and will provide facilities for setting the configuration variables currently in settings.js (and moved into angular providers) via environment variables as well as excluding modules via environment variables.

The `build.gradle` file in the deployable/ will create a `.deb` artifact that will orchestrate the use of webpack to build the deployable artifact on an instance to be served by Apache.

To develop locally, one would run the webpack process in the deployable folder, which will watch for code changes in the src/ folder and rebuild the deployable as needed.

To deploy the deployable, one would run the `build.gradle` to create a .deb and set environment variables on the production instance that will affect the outcome of the webpack process.

To add custom code to the Spinnaker UI, one would create a separate deployable artifact, outside of the deck and add the deck repo as a dependency to their project, requiring it with webpack, browserify or some other front-end loader. To facilitate customization, we will include a Yeoman generator to help set up a custom build of the Spinnaker UI.

#### LIBRARY
- [ ] module isolation. each module aws, core, etc. should be completely isolated and bring in its entire subtree
- [ ] bring fonts/icons into dist bundle
- [ ] webpack with external jquery/angular
- [ ] environment variable-based module exclusion
- [ ] replace settings.js with runtime angular factoryProvider getters/setters
- [ ] karma.conf.js

#### DEPLOYABLE
- [x] webpack with internal jquery/angular
- [ ] environment variable-based setting of lib factoryProvider getters/setters
- [ ] build.gradle
- [x] webpack alias for src

**Comment by BenjaminMalley** [comment]
UPDATE: It turns out that the `.config` blocks in `src/` will run before the module defined in `deployable/`, which means that the `deployable` module can't set the `baseUrl` and other configuration parameters before the application bootstraps. In order to resolve this, we will need to rewrite a significant portion of the `.config` blocks in `src/` to either a) be `.run` blocks or b) allow for external configuration.

@zanthrash & I will look at the best way to accomplish this over the next week.

^ @anotherchrisberry please let me know if you have any concerns.

**Comment by anotherchrisberry** [comment]
Makes sense. I ran into similar issues in a few places and converted some `config`s to `run`s to get around it. If I'm understanding it correctly, given the following application structure:

```javascript
// app
angular.module('spinnaker.app', [
  require('core'),
  require('amazon')
]);

// core module
angular.module('spinnaker.core', [])
  .config(/* stuff */)
  .run(/* other stuff */);

// amazon module
angular.module('spinnaker.amazon', [])
  .config(/* stuff */)
  .run(/* stuff */);
```
the execution order is:
 1. spinnaker.core config block
 2. spinnaker.amazon config block
 3. spinnaker.core run block
 4. spinnaker.amazon run block

If you switch the app dependencies (so `spinnaker.amazon` is the first dependency), the operations above would run in the following order: 2, 1, 4, 3

Is this what you're talking about?

**Comment by BenjaminMalley** [comment]
Yes, but also in that scenario, both the `spinnaker.core` and `spinnaker.amazon` config blocks run before anything in `spinnaker.app`. In our proposal, we want to use the config block in what is essentially `spinnaker.app` in your example to configure core, etc, which means we can't have any config blocks in core for those things.

**Comment by anotherchrisberry** [comment]
@JargoonPard Can you and the other Azure folks take a look at this proposal and provide feedback?

**Comment by JargoonPard** [comment]
Makes sense, it would be nice to see the additional structure and modularity enabled. @rguthriemsft any concerns?

**Comment by ajordens** [comment]
Whats the deal @anotherchrisberry  ... can we close this in lieu of other Q4 efforts?

**Comment by anotherchrisberry** [comment]
yup
