### ISSUE TITLE
Canary results in either 0 or 100 score 

### ISSUE THREAD

**Issue by Galileo1** [spinnaker/spinnaker#5771]
### Issue Summary:
When canary stage runs. It either results in giving 0 or 100 score. Is this is expected behavior??

### Cloud Provider(s):
k8s v2

### Environment:
Running spinnaker onprimise k8s cluster. 

### Feature Area:
Kayenta - Canary Analysis 

### Description:
Looking at the pattern, seems like if the 
Run Canary#  fails because of genuine reason ['Canary score of previous interval(doesn't matter whether you have intervals or not) in less than marginal score.']. The `Aggregate Canary Results` phase never runs. Example snapshot below. It just produces a score of 0.

![image](https://user-images.githubusercontent.com/9716232/82001806-235e1400-96b0-11ea-9840-f38517490e3f.png)
![image](https://user-images.githubusercontent.com/9716232/82001855-4c7ea480-96b0-11ea-9a2a-1bdac71482d7.png)

### Steps to Reproduce:
- Set up a canary pipeline in spinnaker.
- Set it fail during canary analysis.

### Additional Details:
When Run Canary# phase is successful. It executes the `Aggregate Canary Results` phase and produces a score of 100.

![image](https://user-images.githubusercontent.com/9716232/82002248-6e2c5b80-96b1-11ea-8530-dd26b28d4131.png)

**Comment by Galileo1** [comment]
Just found out it was configuration that was causing kayenta to terminate the canary build and not perform the Aggregate Canary Results phase.

`Criticality:  Fail the canary if this metric fails` option was toggle on. It should be off to get the score.

![image](https://user-images.githubusercontent.com/9716232/82128195-5f5abb80-980d-11ea-8f77-a104d9b88780.png)

**Comment by aleon1220** [comment]
> Just found out it was configuration that was causing kayenta to terminate the canary build and not perform the Aggregate Canary Results phase.
> 
> `Criticality: Fail the canary if this metric fails` option was toggled on. It should be off to get the score.
> 
> ![image](https://user-images.githubusercontent.com/9716232/82128195-5f5abb80-980d-11ea-8f77-a104d9b88780.png)

Good detail. Thanks

**Comment by elvis-cai** [comment]
thanks for sharing, found the same issue here 👍
