### ISSUE TITLE
Spinnaker shows "Run As User" in pipeline's configuration

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5774]
### Issue Summary:
After a number of upgrades between 1.20 and 1.19 I noticed these GUIDed-names for service accounts:

![image](https://user-images.githubusercontent.com/45210095/82072247-41198200-968c-11ea-9fbc-c1535388fd7d.png)

### Environment:
Spinnaker 1.19 - Spinnaker 1.20

### Feature Area:
orca/deck

### Description:
I am NOT supposed to see those accounts because I have

- in .hal/default/profiles/orca-local.yml

```
tasks:
  useManagedServiceAccounts: true
```

- in .hal/default/profiles/settings-local.js:
```
window.spinnakerSettings.feature.managedServiceAccounts = true;
```

and I didn't see those GUIDed accounts until recently and had nice looking roles but not anymore after migrating back and forth between 1.19 and 1.20

**Comment by atyutyunnik** [comment]
It looks like this comment
```
#window.spinnakerSettings.feature.legacyArtifactsEnabled = true;
```
which is not correct JS, silently breaks the whole config.

I would expect that halyard, or whatever else that does config assembly, to do some basic validation of the config, given the fact that different config files have different symbols to designate comments.

**Comment by plumpy** [comment]
Thanks for reporting the issue. While Halyard does do some config validation, it's not really feasible for it to validate everything. And as development on Halyard's replacement (kleat) continues, we're not likely to invest a lot in enhancements to it like this.
