### ISSUE TITLE
Cannot Add Server Group

### ISSUE THREAD

**Issue by alisonchico** [spinnaker/spinnaker#5777]
I m trying to add a ReplicaSet Yaml at Servers Groups in My Spinnaker at GCE.
But does not create any cluster server and generate java.lang.NullPointerException at  , any idea of what can be:

Service Yaml:
apiVersion: v1
kind: Service
metadata:
  name: elasticsearchapp-staging-service
  namespace: elasticsearchapp-staging
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    frontedBy: elastic-search-service

ReplicaSet.YAML
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elasticsearchapp-backend
  namespace: elasticsearchapp-staging
  annotations:
    version: "1"
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '[service elasticsearchapp-staging-service]'
  labels:
    app: elasticsearch-app-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-app-servers
  template:
    metadata:
      labels:
        app: elasticsearch-app-servers
      annotations:
        timestamp: ""
        version: "1"
    spec:
      containers:
        - name: elasticsearchapp
          image: gcr.io/addotnet-development-245417/elasticsearch_teste
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          env:
          - name: APP_NAME
            value: nodeapp
          - name: APP_PORT
            value: "9200"
          - name: APP_HOST
            value: "0.0.0.0"
          - name: APP_VERSION
            value: "1"
          - name: TIME_BEFORE_START
            value: "5000"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 512Mi

**Comment by maggieneterval** [comment]
Hi @alisonchico! I think we'll need more detailed steps to reproduce in order to address this issue: are you seeing an NPE when using the Deploy (Manifest) stage? Could you please provide the full error message from your execution details, and a (sanitized) version of your pipeline JSON? Thanks!

**Comment by ezimanyi** [comment]
Closing this; please re-open if you're still experiencing this and have the additional info requested by @maggieneterval .
