### ISSUE TITLE
API - Trigger a Manual Judgement Stage

### ISSUE THREAD

**Issue by ghostsquad** [spinnaker/spinnaker#5778]
### Issue Summary:

Is there a way to continue or stop (select an action) on a manual judgement stage via the API. If not this is a request to implement.

**Comment by maggieneterval** [comment]
Hey @ghostsquad! Check out [this Slack conversation](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1579730201135400); it looks like you should be able to curl Gate with a judgment to either continue or stop a manual judgment stage (can also check out the request Deck is making to Gate in your browser's Network tab when you click that button for an example). Feel free to re-open this issue with more details if this isn't exactly what you're looking for. Thanks!
