### ISSUE TITLE
Wrong error message display on deck for 1.20.1

### ISSUE THREAD

**Issue by lukmy** [spinnaker/spinnaker#5782]
### Issue Summary:

Wrong error message display on Deck

### Cloud Provider(s):

- kubernetes v2
- kubernetes environment 1.17.3

### Environment:

- spinnaker: 1.20.1, 1.19.0, 1.19.2

### Feature Area:

- Deck
- Orca

### Description:

We met 2 error in Deploy stage:

- Cause we upgrade kubernetes to 1.17.3, so statefulset with api version `apps/v1beta2` is not available anymore
- **SpEL evaluation error, but we skipped SpEL evaluation for this stage.**

Error message only displayed in `stages[].context.exception`, but actual error should be `stages[].context.kato\.tasks[].exception`.

Frontend display error:

![PipelineExecutionFrontend](https://user-images.githubusercontent.com/1225713/82291255-3e47c580-99db-11ea-8d6d-e49fdb4da4db.png)

Backend api response:

![PipelineExecutionBackend](https://user-images.githubusercontent.com/1225713/82291620-ecec0600-99db-11ea-8b35-646be3e0b3cb.png)

It seems that `SkipSpELExpressionEvaluation` performed the evaluation and skipped the result, but left exception, eventually caused the wrong error display.

**Comment by ezimanyi** [comment]
It looks like this has been mostly solved by the above-linked PR spinnaker/deck#8330 by @evansb.  I just tried this out myself and now if I have both an actual error and a SpEL warning, both are displayed:
![image](https://user-images.githubusercontent.com/1391982/86060163-347d9d00-ba32-11ea-8a79-b89aab41195b.png)

Obviously there still remains the fact that we log these warnings and there's no way to fully disable SpEL evaluation (only to avoid having failures result in the pipeline failing).  That is being tracked directly in #5626.  The plan for addressing that is to implement #5676, which will solidify the orca-clouddriver contract to hopefully avoid needing to pass all of the deployed YAML through the pipeline context (which will avoid having multiple passes of SpEL evaluation happen on it).

Based on that I'm going to close this issue, in favor of the other two issues tracking the remaining problem of SpEL evaluation...but please feel free to comment/re-open if I'm missing something and there is still something in this issue that is not covered by the other ones.  Thanks!
