### ISSUE TITLE
Fix account selection by handling null values passed

### ISSUE THREAD

**Issue by vgantam** [spinnaker/spinnaker#5783]
### Issue Summary:
This is an issue we are experiencing in our Spinnaker instance that has to do with Deck not loading something in right. We are finding this issue by attempting to create a server group, on the account drop-down (which we have populated with at least 2 accounts) It prevents us from selecting a different account than the first option it loads. 

We found a similar issue corresponding to the Kubernetes side
 [k8's github issue](https://github.com/spinnaker/deck/pull/6440/files)

### Cloud Provider(s):
Google App Engine

### Environment:
Spinnaker in GCP deploying to Google App Engine

### Feature Area:

Deck

### Description:

The expected behavior is to be able to pick any account we need from the drop-down

### Steps to Reproduce:

Try adding a couple of AppEngine accounts to the clouddriver and from the pipeline try to pick one account, you should be able to see only one account being selected all time.

### Additional Details:
In the below SC we are not able to select the gae-demo-account2

<img width="918" alt="image" src="https://user-images.githubusercontent.com/25491856/82366657-8d442980-99e0-11ea-915a-394c06d798a3.png">

**Comment by maggieneterval** [comment]
Hey @vgantam, thanks for reporting this issue! What version of Spinnaker are you running? Are you seeing any errors in your browser console when observing this behavior?

**Comment by vgantam** [comment]
@maggieneterval The version of the spinnaker we are running on 1.19.8,This is error i am seeing in web console.
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/25491856/82815398-189d3f00-9e67-11ea-8a5f-207a7b4f2a38.png">

**Comment by maggieneterval** [comment]
Thanks for sending that screenshot, @vgantam! Hmm, not sure how that plugins-related error could be related to your inability to select your account. Is that error only appearing when you try to select the account, or before? Are you using plugins?

**Comment by vgantam** [comment]
@maggieneterval I am not sure if that error is related, I am not using any plugins, when we add an account it comes with a default and we are not able to change the default. There is a workaround by editing the JSON and changing the account name over there and save. it is helping us now.

**Comment by maggieneterval** [comment]
Hey @vgantam, [a fix for the account selection component](https://github.com/spinnaker/deck/pull/8013) was recently cherry-picked to the 1.19 release branches and will be released with the next patch release of 1.19 (1.19.11). Once you upgrade, please feel free to re-open this if you're still seeing this issue. Thanks!

**Comment by vgantam** [comment]
Sure, Thank you @maggieneterval

**Comment by vgantam** [comment]
![deckuibugfix](https://user-images.githubusercontent.com/25491856/83466485-34937880-a445-11ea-839f-b52c42e4b9dc.gif)
I can confirm this issue is fixed, now i'm able to change GAE accounts in spinnaker V1.19.11

**Comment by maggieneterval** [comment]
Great, thank you so much for confirming! 🎉
