### ISSUE TITLE
Poor performance with ECR registry

### ISSUE THREAD

**Issue by rverma-jm** [spinnaker/spinnaker#5806]
### Issue Summary:
While using ECR with clouddriver, our current setup includes 5 ecr registry, each with 15-20 repos.
We have observed that the time lag between the image is uploaded to ecr and trigger is activated is too high for us. Initially it was 2 minutes and now over 5-6 minutes and sometimes take upto 30 minutes.
The clouddriver pod seems too much resource hungry and currently running with 3cpu and 4G memory. Orca is 1cpu and 1G, but its consumption is very less.

### Cloud Provider(s):
AWS

### Environment:
EKS 1.16

### Feature Area:
Ecr Triggers

### Description:
Ecr triggers are notably slow, it would be nice to see a guide for perfomance optimization with ecr

**Comment by robzienert** [comment]
Disable the sorted tags feature on the docker registry configuration. This is a performance issue of ECR, not Spinnaker: This setting should not be enabled.

**Comment by allisaurus** [comment]
Related AWS Containers Roadmap issue: 
https://github.com/aws/containers-roadmap/issues/418

Closing this issue in favor of using the above to track the underlying cause.

**Comment by allthatjazzleo** [comment]
```
            trackDigests: false
            sortTagsByDate: false 
```
It works for me after setting these value to `false`
