### ISSUE TITLE
[Request]Customize Jenkins getArtifacts timeout 

### ISSUE THREAD

**Issue by charliezang** [spinnaker/spinnaker#5808]
### Issue Summary:
The Jenkins our Spinnaker instance connect with is not stable, although Orca has the retry for get artifacts job but 25s is not enough when the artifact is too big, so could someone make this parameter customizable, so we could override this value to a bigger one.

### Environment:
Spinnaker 1.19

### Feature Area:
Orca

**Comment by evansb** [comment]
Currently fetching Build Properties/Artifact in Jenkins is a synchronous operation, I don't think it's a good idea to increase its timeout. It's different from monitor/wait tasks.

Speaking of reliability, we fixed a similar issue recently with Igor not retrying on 404 (Jenkins sometimes returns it when unstable/delayed in producing the artifact), maybe this commit will help. https://github.com/spinnaker/igor/commit/7c47ce3fece8120fc53c615a9683f4ce0070ea4b#diff-11c69381f59e62bb2a05700317ec9f6d

Currently, Orca will retry 5 times with a backoff value of 5 seconds (check `RetryableIgorTask` in Orca), but within each retry, Igor itself also retried 5 times, I think this is already reasonable.

I'm more concerned about your artifact/properties size that it needs more than 25 seconds to download, it seems that you should aim to return the reference to the actual artifact instead and store it elsewhere (path to S3/HTTP/etc)

**Comment by charliezang** [comment]
@evansb Thanks for your explanation, it is reasonable, I will check the Jenkins return and artifact, btw, when will this patch release to which version?

**Comment by evansb** [comment]
The bot in the PR tells you which version it is targetted at.

**Comment by charliezang** [comment]
@gal-yardeni  yes, we need to wait for the patch released to see if it get solved, meanwhile seems our jenkins has some performance issue we need to fix,anyway this issue can be closed, thanks
