### ISSUE TITLE
Git trigger based on regex fails with multiple matching artifacts

### ISSUE THREAD

**Issue by rverma-jm** [spinnaker/spinnaker#5813]
### Issue Summary:
While spinnaker support **git based trigger** with an artifact constraint which support regex.
If multiple files matching the regex are pushed, spinnaker failed to start the pipeline withi exception of `multiple artifacts`

### Cloud Provider(s):
AWS

### Environment:
EKS
SPINNAKER 1.20.4

### Feature Area:
IGOR

### Description:
Our use case is that if any of the files changes in the kustomization directory, we should be able to build the kustomize and redeploy.

### Steps to Reproduce:
1. Create a regex trigger like
folder/.*\.yml
2. push 2 files matching the above regex in 1 commit.

### Additional Details:

```
Failed on startup: Expected artifact ExpectedArtifact(matchArtifact=Artifact(type=github/file, customKind=true, name=services/cbs/deposit-manager/.*\.yaml, version=null, location=null, 
reference=null, metadata={id=844de938-8149-477b-9efe-b2da52c98bf9}, artifactAccount=github, provenance=null, uuid=null), usePriorArtifact=false, useDefaultArtifact=true, defaultArtifact=Artifact(type=http/file, customKind=false, name=null, version=null, location=null, reference=null, metadata={id=74e952e4-4d83-47b8-9b83-00ddab625faa}, artifactAccount=no-auth-http-account, provenance=null, uuid=null), 
id=0ac59ca0-a929-4fd7-be5b-78ed355babb6, boundArtifact=null) matches multiple artifacts [Artifact(type=github/file, customKind=false, name=services/cbs/deposit-manager/flyway.yaml, version=e28cbf9a2f9b69810e90b020689d79c5325d352b, location=null, 
reference=https://api.github.com/repos/jupitermoney/dev.jupiter.money/contents/services/cbs/deposit-manager/flyway.yaml, metadata=null, artifactAccount=null, provenance=null, uuid=null), Artifact(type=github/file, customKind=false, name=services/cbs/deposit-manager/kustomization.yaml, version=e28cbf9a2f9b69810e90b020689d79c5325d352b, location=null, 
reference=https://api.github.com/repos/jupitermoney/dev.jupiter.money/contents/services/cbs/deposit-manager/kustomization.yaml, metadata=null, artifactAccount=null, provenance=null, uuid=null)]
```

**Comment by jensvdh** [comment]
@rverma-jm 
Can you please give us some more information on your artifact configuration?

Also if possible, could you join one of the [SIG-CI](https://www.spinnaker.io/community/#slack) meetings so we can discuss this issue?

**Comment by gal-yardeni** [comment]
ping @rverma-jm  -- are you still facing this issue? will you be able to join our sig meeting tomorrow at 10:00 PST?

**Comment by emccallum** [comment]
Hi @rverma-jm , we have another sig meeting tomorrow at 10:00 AM PST. If you're able, please join us to discuss this issue! Otherwise, feel free to reach out in the sig-ci channel in the Spinnaker Slack.

**Comment by Chinikins** [comment]
To get around this issue in the past I've pushed the entire github folder into an S3 bucket and listened for S3 bucket changes instead but I would like to see a way for spinnaker to handle this kind of change straight from github.

**Comment by emccallum** [comment]
Hi @rverma-jm , due to inactivity we will be closing this issue. Feel free to open a new issue with the additionally requested context if this persists!
