### ISSUE TITLE
orca can't resolve pipeline parameters inside collection selection expression

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5824]
### Issue Summary:
Attempt to use parameters within collection selection is unsuccessful:
```
${execution.stages.?[refId == parameters["refId"]]}
```

### Cloud Provider(s):
any

### Environment:
Spinnaker 1.18.2 - 1.20.3 (didn't verify outside of these versions)

### Feature Area:
Orca

### Description:
I cannot use a parameter to dynamically filter arbitrary json objects
```
${execution.stages.?[refId == parameters["refId"]]}
```

results in:
```
Error: java.lang.IllegalArgumentException: Failed to evaluate [expression] requested getter parameters not found on type class com.netflix.spinnaker.orca.pipeline.model.Stage - EL1021E: A problem occurred whilst attempting to access the property 'parameters': 'requested getter parameters not found on type class com.netflix.spinnaker.orca.pipeline.model.Stage'
```
At the same time:
```
${parameters.refId}
```

resolves just fine:
```
1
```
<img width="723" alt="wrong_eval" src="https://user-images.githubusercontent.com/45210095/84091802-64dd9880-a9aa-11ea-9f41-9a514c657b05.PNG">

### Steps to Reproduce:
Use the attached pipeline

**Comment by atyutyunnik** [comment]
[test_pipeline.json.txt](https://github.com/spinnaker/spinnaker/files/4749173/test_pipeline.json.txt)

**Comment by ajordens** [comment]
Can you try `#root.parameters` vs `parameters`. The `#root` prefix is necessary when nesting within an expression.
