### ISSUE TITLE
Failed to evaluate <expression>... `execution` property not found

### ISSUE THREAD

**Issue by ghostsquad** [spinnaker/spinnaker#5830]
### Issue Summary:

```
[spin-orca-7df495bb9f-2zqjt] 2020-06-10 23:47:12.632  INFO 1 --- [.0-8083-exec-20] c.n.s.k.expressions.ExpressionTransform  : [] Failed to evaluate ${ (#stage("k/namespace").status.toString() == "SUCCEEDED") }, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.HashMap'
```

### Cloud Provider(s):

AWS/Kubernetes

### Environment:

Halyard

### Feature Area:

Webhook Trigger - Pipeline Execution

### Description:

receiving error when attempting to run a pipeline (via webhook):

```
[spin-orca-7df495bb9f-2zqjt] 2020-06-10 23:47:12.632  INFO 1 --- [.0-8083-exec-20] c.n.s.k.expressions.ExpressionTransform  : [] Failed to evaluate ${ (#stage("k/namespace").status.toString() == "SUCCEEDED") }, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.HashMap'
```

expected behavior: no error is received

### Steps to Reproduce:

Attempt to trigger a pipeline with stages with a precondition expression (listed in error message) from a webhook

### Additional Details:

Spinnaker 1.19.2

I can verify this expression works on an existing pipeline execution with this:

```bash
EXPRESSION='${ (#stage("k/namespace").status.toString() == "SUCCEEDED") }'
echo "$EXPRESSION" | http POST https://mydomain/pipelines/$SPINNAKER_PIPELINE_ID/evaluateExpression "cookie:SESSION=$SESSION_TOKEN" Content-Type:text/plain
```

where `http` is https://httpie.org/

**Comment by wmcnamee-tunein** [comment]
Some other details, I see this error everywhere I'm using a `spel` expression:

```
[spin-orca-685f7b5cf8-sqhzp] 2020-06-11 01:18:19.243  INFO 1 --- [0.0-8083-exec-9] c.n.s.k.expressions.ExpressionTransform  : [] Failed to evaluate https://mydomain/#/applications/${execution.application}/executions/details/${execution.id}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.HashMap'
```

**Comment by ghostsquad** [comment]
Some other details, I see this error everywhere I'm using a `spel` expression:

```
[spin-orca-685f7b5cf8-sqhzp] 2020-06-11 01:18:19.243  INFO 1 --- [0.0-8083-exec-9] c.n.s.k.expressions.ExpressionTransform  : [] Failed to evaluate https://mydomain/#/applications/${execution.application}/executions/details/${execution.id}, returning raw value EL1021E: A problem occurred whilst attempting to access the property 'execution': 'requested getter execution not found on type class java.util.HashMap'
```

**Comment by ghostsquad** [comment]
ok, so I figured out the issue, it was strangely that the stages didn't have a name.

**Comment by ghostsquad** [comment]
@ajordens - any chance this can be re-opened? the error message did not reflect the problem, and it took me awhile to figure that out.

**Comment by kowshikRoy** [comment]
@ghostsquad We're having this issue. Can you please share how you resolved this?

**Comment by ffrizzo** [comment]
> @ajordens - any chance this can be re-opened? the error message did not reflect the problem, and it took me awhile to figure that out.

Do you mind sharing what you have done to fix this error?

**Comment by kowshikRoy** [comment]
For us, it's related to https://stackoverflow.com/a/28513868
We removed the jar `jsr311-api-1.1.1.jar`
