### ISSUE TITLE
Document how to delete ServiceAccount

### ISSUE THREAD

**Issue by evansb** [spinnaker/spinnaker#5831]
### Issue Summary:

Add instruction to delete service account in https://www.spinnaker.io/setup/security/authorization/service-accounts/#service-account-roles

### Cloud Provider(s):

N/A

### Environment:

N/A

### Feature Area:

Documentation, spinnaker.io

**Comment by ajordens** [comment]
This is a good contribution opportunity, do you mind submitting a PR?

In this case it should be a simple `DELETE` to `/serviceAccounts/{serviceAccountName}`.
