### ISSUE TITLE
groovy.lang.MissingMethodException when referencing github config artifact for GAE deploy

### ISSUE THREAD

**Issue by billiford** [spinnaker/spinnaker#5836]
### Issue Summary:
groovy.lang.MissingMethodException when referencing github config artifact for GAE deploy

### Cloud Provider(s):
App Engine

### Environment:
GCP

### Feature Area:
Orca

### Description:
groovy.lang.MissingMethodException when referencing github config artifact for GAE deploy

### Steps to Reproduce:
Create a pipeline with the following JSON
```json
{
  "appConfig": {},
  "expectedArtifacts": [],
  "keepWaitingPipelines": false,
  "limitConcurrent": true,
  "spelEvaluator": "v4",
  "stages": [
    {
      "clusters": [
        {
          "account": "your-account",
          "application": "yourapplication",
          "branch": "develop",
          "cloudProvider": "appengine",
          "configArtifacts": [
            {
              "artifact": {
                "artifactAccount": "github.com",
                "id": "41dfba03-0c2f-406b-870a-4ab386591504",
                "name": "app.yaml",
                "reference": "https://github.com/api/v3/repos/<ORG>/<REPO>/contents/app.yaml",
                "type": "github/file",
                "version": "master"
              }
            }
          ],
          "configFilepaths": [
            "app.yaml"
          ],
          "configFiles": [],
          "containerImageUrl": "us.gcr.io/<IMAGE>:<TAG>",
          "freeFormDetails": "",
          "fromArtifact": false,
          "gitCredentialType": "HTTPS_USERNAME_PASSWORD",
          "interestingHealthProviderNames": [
            "App Engine Service"
          ],
          "promote": true,
          "provider": "appengine",
          "region": "us-east1",
          "repositoryUrl": "<REPOSITORY_URL>",
          "sourceType": "containerImage",
          "stack": "default",
          "stopPreviousVersion": true,
          "strategy": "highlander"
        }
      ],
      "name": "Deploy",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "deploy"
    }
  ]
}
```

Attempt to run the pipeline. The following error is shown in Deck.

```
Exception ( Create Server Group )
No signature of method: com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.getBoundArtifactForStage() is applicable for argument types: (com.netflix.spinnaker.orca.pipeline.model.Stage, null, HashMap) values: [Stage {id='01EAN5XXHW1Y46G3R6TFA9R9T4', executionId='01EAN5XXATZZVTMFBTD85RZGNK'}, ...] Possible solutions: getBoundArtifactForStage(com.netflix.spinnaker.orca.pipeline.model.Stage, java.lang.String, com.netflix.spinnaker.kork.artifacts.model.Artifact)
```

**Why is the artifact being bound to a HashMap?**

**Comment by ajordens** [comment]
@ezimanyi may be able to shed some light on the artifact behavior here.

**Comment by guido9j** [comment]
Here is the stack trace:

> Possible solutions: getBoundArtifactForStage(com.netflix.spinnaker.orca.pipeline.model.Stage, java.lang.String, com.netflix.spinnaker.kork.artifacts.model.Artifact)
> groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.getBoundArtifactForStage() is applicable for argument types: (com.netflix.spinnaker.orca.pipeline.model.Stage, null, HashMap) values: [Stage {id='01EAN5XXHW1Y46G3R6TFA9R9T4', executionId='01EAN5XXATZZVTMFBTD85RZGNK'}, ...]
> 2020-06-12 21:10:50.079 ERROR 1 --- [    handlers-16] c.n.s.orca.q.handler.RunTaskHandler      : [] Error running CreateServerGroupTask for pipeline[01EAN5XXATZZVTMFBTD85RZGNK]
>     java.base/java.lang.Thread.run(Thread.java:834)
>     java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>     java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>     com.netflix.spinnaker.q.QueueProcessor$callback$1$1.run(QueueProcessor.kt:89)
>     com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
>     com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:87)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:201)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:59)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:73)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:93)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:45)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:84)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:45)
>     com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:67)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:208)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:126)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51)
>     com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92)
>     com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:127)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:378)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:72)
>     com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:129)
>     com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.CreateServerGroupTask.execute(CreateServerGroupTask.groovy:52)
>     com.netflix.spinnaker.orca.clouddriver.tasks.servergroup.ServerGroupCreator$getOperations.call(Unknown Source)
>     com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator.getOperations(AppEngineServerGroupCreator.groovy:51)
>     com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator$appendArtifactData.callCurrent(Unknown Source)
>     com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator.appendArtifactData(AppEngineServerGroupCreator.groovy:77)
>     org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
>     org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
>     org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
>     org.codehaus.groovy.runtime.dgm$87.invoke(Unknown Source)
>     org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3659)
>     org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3559)
>     org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3574)
>     groovy.lang.Closure.call(Closure.java:421)
>     groovy.lang.Closure.call(Closure.java:405)
>     groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
>     org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
>     groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
>     org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
>     java.base/java.lang.reflect.Method.invoke(Method.java:566)
>     java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     com.netflix.spinnaker.orca.clouddriver.tasks.providers.appengine.AppEngineServerGroupCreator$_appendArtifactData_closure1.doCall(AppEngineServerGroupCreator.groovy:78)
>     org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
>     org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
>     org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
> Possible solutions: getBoundArtifactForStage(com.netflix.spinnaker.orca.pipeline.model.Stage, java.lang.String, com.netflix.spinnaker.kork.artifacts.model.Artifact)
> groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.orca.pipeline.util.ArtifactUtils.getBoundArtifactForStage() is applicable for argument types: (com.netflix.spinnaker.orca.pipeline.model.Stage, null, HashMap) values: [Stage {id='01EAN5XXHW1Y46G3R6TFA9R9T4', executionId='01EAN5XXATZZVTMFBTD85RZGNK'}, ...]
> 2020-06-12 21:10:50.077  WARN 1 --- [    handlers-16] c.n.s.o.e.DefaultExceptionHandler        : [] Error occurred during task createServerGroup

**Comment by guido9j** [comment]
@ezimanyi I got past the error above. The config artifacts were returning a HashMap (not sure if that's a groovy behavior vs java. Anyhow, I converted the HashMap to Artifact object (from kork project) and orca is not failing anymore.

Unfortunately, I seem to be running into another issue  (this time in clouddriver), which causes this error:

> Failed to deploy to App Engine with command gcloud app deploy /var/tmp/clouddriver/gs:--billy1234-/./5809b2d7-c38d-47f5-ac53-54d1a0617279.yaml --version=myapp-billy-v032 --promote --stop-previous-version --project=github-replication-sandbox --account=spinnaker-onboarding@github-replication-sandbox.iam.gserviceaccount.com: stdout: , stderr: ERROR: gcloud crashed (UnicodeDecodeError): 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

I found this in the logs:
> c.n.s.c.a.g.GitRepoArtifactCredentials   : Cloning git/repo https://github.com/guido9j/spin-test.git into /tmp/8c441a44-ccf7-4db5-8bde-355d385ef6f7

Which is good, and then I see this after:
> org.eclipse.jgit.util.FS                 : Mount point not found

Which may be a configuration issue on our side. If so, the code is not handling this misconfiguration well. Let me know if you have any feedback. Thanks

**Comment by guido9j** [comment]
Did some more digging, the repo is getting cloned. The file is an actual tar.gz with the contents of the repo. The code is not extracting the archive.

**Comment by ezimanyi** [comment]
@guido9j : Thanks for the update, and figuring this out!  It does indeed look like the change in #spinnaker/orca#3008 did not correctly account for whether the `expectedArtifact` was a map or an actual `Artifact`.

Please do submit your fix for this, and feel free to tag me on the PR!

**Comment by guido9j** [comment]
@ezimanyi : Now that this issue been resolved. Am I supposed to close this issue?

**Comment by ezimanyi** [comment]
@guido9j : I ended up merging the test cases, so I think this can be closed.  Thanks for following up!
