### ISSUE TITLE
how dockerRegistry displays the specified version image

### ISSUE THREAD

**Issue by areswxin** [spinnaker/spinnaker#5848]
### Issue Summary:
how to display the specified version image

### Environment:
aws

### Description:
i used only one dockerRegistry,Each environment image tag is different。
For example, the test environment begins with dev，prod environment begins with prod。
The test environment only wants to show awards at the beginning of dev，i know the trigger can do it,but If i specify a image tag deployment,i can  see all the mirror images，how can i do it?

**Comment by ealebed** [comment]
@areswxin You can use 'Tag' field from Docker Image trigger.
```
(Optional) If specified, only the tags that match this Java Regular Expression will be triggered. Leave empty to trigger builds on any tag pushed.

Builds will not be triggered off the latest tag or updates to existing tags.
```

E.g.:
<img width="851" alt="Screenshot 2020-06-17 at 14 43 07" src="https://user-images.githubusercontent.com/8081901/84894298-3d24b980-b0a9-11ea-822c-a738f5d91496.png">

or

<img width="783" alt="Screenshot 2020-06-17 at 14 44 30" src="https://user-images.githubusercontent.com/8081901/84894302-3f871380-b0a9-11ea-83b4-adc47171f336.png">

**Comment by areswxin** [comment]
> @areswxin You can use 'Tag' field from Docker Image trigger.
> 
> ```
> (Optional) If specified, only the tags that match this Java Regular Expression will be triggered. Leave empty to trigger builds on any tag pushed.
> 
> Builds will not be triggered off the latest tag or updates to existing tags.
> ```
> 
> E.g.:
> <img alt="Screenshot 2020-06-17 at 14 43 07" width="851" src="https://user-images.githubusercontent.com/8081901/84894298-3d24b980-b0a9-11ea-822c-a738f5d91496.png">
> 
> or
> 
> <img alt="Screenshot 2020-06-17 at 14 44 30" width="783" src="https://user-images.githubusercontent.com/8081901/84894302-3f871380-b0a9-11ea-83b4-adc47171f336.png">
> 
> but if you want to see ONLY **dev** tags in drop-down list - start typing 'dev':
> <img alt="Screenshot 2020-06-17 at 14 47 40" width="628" src="https://user-images.githubusercontent.com/8081901/84894683-d9e75700-b0a9-11ea-8964-a44720d8bac9.png">

@ealebed Thank you for your answer，It's very useful to me.
