### ISSUE TITLE
Hide the property values from Jenkins Stage Configuration

### ISSUE THREAD

**Issue by vijay-sapient** [spinnaker/spinnaker#5852]
It would be good if we have a way to hide the property file coming from jenkins build stage, this prints the whole content of the file. I use to bring some secrets from jenkins as well. is it possible? 

Also is there a way we can handle passwords/secrets through spinnaker itself?

**Comment by ethanfrogers** [comment]
@vijay-sapient could you give us a little more context for what you're trying to do with the secrets? Are the secrets you're sending over being used in your deployments? API keys for a webhook stage? Knowing a bit more about your goal would help us give you better advice!

**Comment by vijay-sapient** [comment]
Hi @ethanfrogers yes these are secrets being used over deployment. we use https://github.com/GoogleCloudPlatform/berglas to manage our passwords/keys, so it has to be pulled from jenkins, and sent to spinnaker through a jenkins stage. here Spinnnaker only accepts the property file.

Just to test I replaced stage.context.propertyFileContents to stage.context.propertyFileContentsignore in core~apps.js in the deck container and its not printing on the screen. may be i can build a custom container removing this?

I also see the below in the core~apps.js, but not sure how do i pass the values sent from jenkins as password type. 

`/div>\n      <div class="col-md-5" ng-switch on="parameter.type">\n        <div ng-switch-when="PasswordParameterDefinition">\n          \x3c!-- Passwords do not expose their defaults, for obvious reasons, so we can skip this --\x3e\n          <input\n            ng-if="!useDefaultParameters[parameter.name]"\n            type="password"\n  `

**Comment by gal-yardeni** [comment]
hi @vijay-sapient, we have a CI sig meeting tomorrow at 10:00 am PST, will you be able to join us so we can discuss it? thanks!

**Comment by vijay-sapient** [comment]
Hi @gal-yardeni sure i can

**Comment by gal-yardeni** [comment]
hi @vijay-sapient , can you take a look here and see if it helps? https://spinnaker.io/reference/halyard/secrets/

**Comment by vijay-sapient** [comment]
Hi @gal-yardeni no this does not, the secrets am talking about is application specific, which is visible via UI. I think the fix has to be done on the deck not to show secret.yml during the deploy stage

**Comment by gal-yardeni** [comment]
hi @vijay-sapient after reviewing it again, it looks like we cannot determine from the backend side (Igor) whether a property inside the Jenkins properties file contains any secrets.
One way to handle it is similar to what you've experienced above - you can add a checkbox to `deck` and when this checkbox is checked, you can hide the properties file results. You can directly contribute to `deck` open source project, or to write a wrapper that will use only you (if you choose not to contribute it into OSS). Let us know how you are planning to solve it, and we will take it from there. Thanks!

**Comment by gal-yardeni** [comment]
Closing this as per my previous comment. Feel free to reopen if needed!
