### ISSUE TITLE
Supporting IRSA in clouddriver

### ISSUE THREAD

**Issue by AndriMar** [spinnaker/spinnaker#5857]
### Issue Summary:
It looks like the aws-iam-authenticator cersion 0.4.0 currently installed during docker build does not work with IRSA.
After downloading aws-iam-authenticator version 0.5.0, the same as in halyard then it works fine and I can see that when communicating with other EKS cluster that it is using the correct role and not the role on the node.  

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker running in EKS

### Feature Area:
Clouddriver EKS 

### Description:
Looks like the aws-iam-authenticator in clouddriver does not support IRSA.

### Steps to Reproduce:
Create service account for clouddriver.
Make clouddriver use that service account.
Add other EKS clusters and grant role tied to clouddriver service account access to that cluster.
See authentication errors in clouddriver logs and authentication errors in authenticator on other EKS cluster.

### Additional Details:
Created a PR on clouddriver https://github.com/spinnaker/clouddriver/pull/4696

**Comment by AndriMar** [comment]
Closing this since my PR has been merged.

**Comment by aRobinson-R7** [comment]
@AndriMar - have you been able to get this working for Clouddriver / front50 in Spinnaker v1.22?
I've been getting some errors from the aws-sdk about being unable to read the secrets file
