### ISSUE TITLE
helm v2 converts double dash to single dash during deploy stage.

### ISSUE THREAD

**Issue by vijay-sapient** [spinnaker/spinnaker#5865]
We are using helm v2 to deploy and during bake stage my Baked Manifest yaml looks fine, with double dash. But after during deploy stage the same is converted to a single dash.
Any one faced this issue? 
We deploying some workflows using https://github.com/argoproj/argo, and it requires us to use double dash
                      - - name: call-ingest-template
                          templateRef:
                            name: ingest-template
                            template: ingest

**Comment by ezimanyi** [comment]
@vijay-sapient : Thanks for reporting this issue!  I'm not sure I fully understand exactly what's happening.  Can you provide more information about where you're seeing the double dash, and what you'd expect to see?  Is this in the actual output manifest after running Helm?

**Comment by vijay-sapient** [comment]
Hi @ezimanyi , Thanks for the response.

We need them to double dash. We have argo custom CRD's which uses double dash. https://github.com/argoproj/argo/blob/master/examples/README.md (search for double dash to see some examples)

**For example:-** when i use the below in deploy stage.
- - name: call-ingest-template
templateRef:
name: ingest-template
template: ingest

deploy stage is converting it to single dash.

- name: call-ingest-template
templateRef:
name: ingest-template
template: ingest

when i use the same for kubectl apply it comes as double dash.

Looks like the spinnaker is converting double dash to single when deploying. 
So is there any escape sequence we can use, or can be fixed? I tried many yaml escape characters but did not work

**Comment by ezimanyi** [comment]
@vijay-sapient : Thanks for the details!  I was able to reproduce the exact issue, and tracked it down to a subtle bug in how we are doing SpEL evaluation.  I'll have a fix shortly and will link it back to this issue.  As the fix is a bit risky (and this behavior has been around for a long time) I won't be able to cherry-pick this fix back to current release branches, but this will be fixed in the next release of Spinnaker.

**Comment by vijay-sapient** [comment]
Thanks a lot @ezimanyi. I will keep an eye, and test it out once its out.

**Comment by ezimanyi** [comment]
Fixed in `kork`; the fix was then pulled into `orca` in spinnaker/orca#3818.
