### ISSUE TITLE
Infrastructure Tab missing Kubernetes Clusters, LoadBalancers, Firewalls

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#5866]
### Issue Summary:

Deck has stopped showing `Infrastructure` items. 
The `Projects` page continues to show Kubernetes application image version and replica count & status.
We believe this has happened sometime after our migration from 1.20.2 ish to master.
We have done a couple of master deploys since.
The cluster information is available within the chrome response from https://api.example/com/applications/my-app/serverGroupManagers

### Cloud Provider(s):

Kubernetes

### Environment:

Spinnaker master (just deployed) running on Kubernetes backed by Aurora MySQL (front50/orca/clouddriver).

### Feature Area:

UI - Deck

### Description:

Should this line still have `V2` prefix?
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/loadBalancer/transformer.ts#L8

Per: https://github.com/spinnaker/deck/pull/8226 @maggieneterval 

### Steps to Reproduce:

Suspected steps:

1. Deploy Spinnaker ~1.20.2+
2. Add a Kubernetes provider
3. Add project
4. Add application
5. Deploy application
6. Note missing infrastructure info
7. Look at Project and note infrastructure info is there

### Additional Details:

Possibly related?
https://github.com/spinnaker/deck/pull/8323

Chrome console shows:
```
angular.js:14961 Error: No "loadBalancer.transformer" service found for provider "kubernetes"
    at ProviderServiceDelegate.getDelegate (providerService.delegate.ts:27)
    at Object.normalizeLoadBalancer (loadBalancer.transformer.js:16)
    at loadBalancer_read_service_LoadBalancerReader.normalizeLoadBalancer (loadBalancer.read.service.ts:54)
    at loadBalancer.read.service.ts:29
    at Array.map (<anonymous>)
    at loadBalancer.read.service.ts:29
    at angular.js:17330
    at angular.js:17378
    at Scope.$digest (angular.js:18514)
    at Scope.$apply (angular.js:18903) "Possibly unhandled rejection: {}"
```

**Comment by maggieneterval** [comment]
@kskewes thanks so much for reporting! Are you using Halyard to deploy Deck at HEAD? Would you mind checking the value of `window.spinnakerSettings.providers.kubernetes` in your browser console? I'm guessing it's `undefined`, which is totally my fault and should be fixed here: https://github.com/spinnaker/deck/pull/8381

**Comment by kskewes** [comment]
Thanks very much @maggieneterval.
It is `undefined`.
We are on `version: master-latest-unvalidated` and will roll Spinnaker today with your linked fix and close issue once done. :)

**Comment by kskewes** [comment]
All back now. Thanks again :tada:
