### ISSUE TITLE
Can't get started; "New Application" screen broken

### ISSUE THREAD

**Issue by adamcath** [spinnaker/spinnaker#587]
I am very eager to try out Spinnaker but I can't create an application.

1. I followed the instructions in https://github.com/spinnaker/spinnaker/tree/master/experimental/docker-compose
2. and then picked up from step 3 in http://spinnaker.io/documentation/getting_started.html. 
3. When I go to create an application, the "create" button is always disabled. Perhaps it's related to the mangled "accounts" field?

![screen shot 2015-11-18 at 10 19 46 am](https://cloud.githubusercontent.com/assets/763813/11249844/3785e7da-8dde-11e5-8fac-1bf68e7b6f85.png)

I did not touch config/spinnaker.yml, as it said that having credentials in .aws would work, and I do have that (and they work with, e.g., the AWS CLI).

**Comment by duftler** [comment]
Please try (on your vm): `curl localhost:8084/credentials`

**Comment by adamcath** [comment]
I get `[ ]`

**Comment by adamcath** [comment]
Is this because my credentials are on my host machine and not mapped into the Docker world?

**Comment by tomaslin** [comment]
no, but you probably want to enable aws in your spinnaker-local.yml

**Comment by tomaslin** [comment]
you need to complete step 1 - http://spinnaker.io/documentation/getting_started.html#step-1-set-up-your-target-deployment-environment

**Comment by tomaslin** [comment]
you need a spinnaker-local.yml to map to your account and regions at least.

**Comment by adamcath** [comment]
Derp, I misread the docs. Trying fix.

FWIW, I think the docker-compose readme could be more clear on this point ("first do step one from the getting started guide").

Also, both you and the docs referred to spinnaker-local.yml, but I only have spinnaker.yml.

**Comment by tomaslin** [comment]
There is a default-spinnaker-local.yml file that provides an example. I will make this more explicit in the docker compose docs. 

The getting started guide has gone through many many revisions. The docker compose docs made complete sense a week ago

**Comment by adamcath** [comment]
I'll open a ticket if something is broken that's not between keyboard and chair.

**Comment by sunil2438** [comment]
![capture](https://cloud.githubusercontent.com/assets/17194422/14984117/bad811ea-115e-11e6-9760-e8795ea0c110.PNG)
 i am getting error from below
