### ISSUE TITLE
Unable to Use Pipeline Expressions with Expected Artifacts

### ISSUE THREAD

**Issue by alyssahardy** [spinnaker/spinnaker#5870]
### Issue Summary:
It is not possible to use pipeline expressions with expected artifacts in newer versions of Spinnaker.

### Cloud Provider(s):

Kubernetes V2

### Environment:

Spinnaker 1.20.5 deploying into GKE

### Feature Area:

UI

### Description:

[Documentation](https://spinnaker.io/guides/user/pipeline/expressions/#where-can-i-use-pipeline-expressions) states it is possible to use pipeline expressions with expected artifacts.

>  just enable “Use Default Artifact” and write the expression in the Object path

This does not seem possible in later versions.

### Steps to Reproduce:

Attempt to add an artifact in 1.20.5 Spinnaker. Find there is no default artifact button.

**Comment by maggieneterval** [comment]
Hey @alyssahardy! Thanks for taking the time to open this issue. Could you please help me understand where you are expecting to find a "Use Default Artifact" section but not seeing one?

The standard artifacts UI, which became the default artifacts UI in Spinnaker 1.20, is slightly different than the legacy UI, but you should still be able to define default artifacts. See screenshot for an example:

![Tq8LZja8ZwL](https://user-images.githubusercontent.com/15936279/85898814-f16dc080-b7ca-11ea-9bd1-18966dff4df7.png)

If the [documentation](https://spinnaker.io/reference/artifacts-with-artifactsrewrite/in-pipelines/) is missing anything or you have suggestions for how it could be clarified, please let me know. Thanks so much!

**Comment by alyssahardy** [comment]
Thanks @maggieneterval -- this capability does show up in our 1.19.11 version in the Configuration stage, but not in our 1.20.5 version. When I define an artifact in the Bake stage (as it's no longer possible in the configuration stage), there is no option. If there is another way to do this, I would love to hear it!

I am unable to upload a file here for some reason, so you can see the screenshot [here](https://pasteboard.co/JeVpP1V.png).

**Comment by maggieneterval** [comment]
Hi @alyssahardy! I'm still not 100% clear on what you are trying to do -- are you trying to use a pipeline expression in the Version field of your default Helm artifact?

I just re-deployed my dev Spinnaker at version 1.20.5 and confirmed that this is possible:

![ad48d975-0319-43ab-9146-41efbd02b713](https://user-images.githubusercontent.com/15936279/86019957-4856de00-b9f5-11ea-83cd-0fc3b870d242.gif)

If your artifact is not associated with a trigger and only consumed by one pipeline stage, I'd recommend just defining it inline in the consuming Bake (Manifest) stage.

I also wanted to share some additional [documentation](https://spinnaker.io/reference/artifacts-with-artifactsrewrite/#transitioning-from-the-legacy-artifacts-ui) on the UI differences between 1.19 and 1.20.

Please feel free to reopen this issue if you are still unable to make your pipeline work as expected. Thanks!

**Comment by alyssahardy** [comment]
Hi @maggieneterval -- I was away for a bit and now returned. The issue is not with the version, but the name/account. For example, the values file for dev might reside in a different gcs bucket. I am unable to reopen this issue, though. We are mainly working on trying to templatize some pipelines.
