### ISSUE TITLE
Deleted application not being removed from spinnaker

### ISSUE THREAD

**Issue by silvez-dh** [spinnaker/spinnaker#5883]
### Issue Summary:
An application cached from a k8s account and delete via UI or spin cmdline are not being deleted as it was supposed to

### Cloud Provider(s):
Kubernetes

### Environment:
Sinnaker version: 1.20.5 (deployed via helm)
Running on EKS cluster

### Feature Area:
clouddriver, front50

### Description:
Spinnaker caches all applications (deployment manifests, etc) from k8s clusters/accounts, but some specific applications are not desired to be created/managed by it. Deleting them either via UI or spin cmdline doesn't works (although it shows `application deleted` message).

According to [this doc](https://spinnaker.io/reference/providers/kubernetes-v2/#caching) setting this annotation `caching.spinnaker.io/ignore: true` should do the trick but it doesn't also.

### Steps to Reproduce:
Setup a k8s provider account on spinnaker (via hal cmdline), deploy some application and let spinnaker caches it (until it shows up in the UI). Try to delete it via UI/spin cmdline and set `caching.spinnaker.io/ignore: true`. The application still shows up

### Additional Details:
Nothing relevant is shown in the logs

**Comment by maggieneterval** [comment]
Hi @silvez-dh! Thanks for taking the time to open this issue.

Have you tried configuring your accounts with the `--only-spinnaker-managed` flag set to true? (See [here](https://spinnaker.io/reference/halyard/commands/#hal-config-provider-kubernetes-account-edit) for Hal CLI docs and [here](https://github.com/spinnaker/kleat/blob/master/docs/docs.md#kubernetesaccount) if you are using Kleat or hand-writing your Clouddriver config.)

Please feel free to reopen this bug with further details if enabling that flag does not work for you. Thanks!

**Comment by silvez-dh** [comment]
thanks for the support @maggieneterval ! haven't tried it yet, will reopen case it persists.
