### ISSUE TITLE
include openstack provider

### ISSUE THREAD

**Issue by shashipratap** [spinnaker/spinnaker#5898]
Page: [/reference/providers/](https://www.spinnaker.io/reference/providers/)

Feedback: Big telecom companies are using openstack for their Network Cloud.
can you include it again ? without openstack it is not usable for them

**Comment by dorbin** [comment]
@emjburns , for comment

**Comment by plumpy** [comment]
We can't include code that doesn't have an owner. No one actively involved with the project is familiar with Open Stack. If you would like to own it, we have [a list of requirements for owning a cloud provider](https://github.com/spinnaker/governance/blob/master/cloud-provider-requirements.md).
