### ISSUE TITLE
Enable Spinnaker to handle retry for accessing GCS objects

### ISSUE THREAD

**Issue by ouyangz314** [spinnaker/spinnaker#5899]
### Issue Summary:
GCS can run into problems on 503 service unavailable [1] (expected) when GCS object is accessed at high frequency and it can cause the build script to fail. The request would succeed on retry and GCS has a standard design to handle this issue by using exponential backoff for retry [2]. Spinnaker does not seem to have this feature implemented to automatically handle this error and thus it would cause delay and thus slow down the build (and development) process

[1] https://cloud.google.com/storage/docs/json_api/v1/status-codes#503_Service_Unavailable
[2] https://cloud.google.com/storage/docs/exponential-backoff

### Cloud Provider(s):
GCP

### Environment:
- Spinnaker instance set up in GKE cluster
- GCS bucket with private access

### Feature Area:
build Configuration 

### Description:
One of our clients is experiencing failure in running their build script that access their GCS object. When the object is accessed at higher frequency, request would return 503 service unavailable and thus cause the build to fail. This requires client to rerun their entire process and thus cause their build process to be much longer '

### Steps to Reproduce:
- set up Spinnaker instances in GCP
- create GCS bucket and grant Spinnaker instance appropriate permission to write to GCS object
- create a build script that writes to a particular GCS object with yaml config
- run the script at high frequency (eg 10 times per second)

**Comment by ouyangz314** [comment]
Here is the configuration for the build file:
gcs 
enabled: true
  project: project_name
  bucket: "$bucket_name"
  jsonKey: [redacted]

**Comment by plumpy** [comment]
Do you happen to have a stack trace showing the 503?

**Comment by ouyangz314** [comment]
Yeah, here is the trace our customer received: 

com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
{
  "code" : 503,
  "errors" : [ {
    "domain" : "global",
    "message" : "Backend Error",
    "reason" : "backendError"
  } ],
  "message" : "Backend Error"
}

**Comment by plumpy** [comment]
Is there a stack trace in the Spinnaker logs?

**Comment by plumpy** [comment]
i.e. a Java stack trace showing what code was running that got this error

There might not be one, but if they had one it would be very helpful...

**Comment by ouyangz314** [comment]
Let me ask the customer to see if they have the Java stack trace.

**Comment by plumpy** [comment]
This was fixed in spinnaker/front50#911. It will be released as part of Spinnaker 1.22 next week.

**Comment by ouyangz314** [comment]
Thank you!
