### ISSUE TITLE
Spin CLI is unable to create new pipelines after updating to Spinnaker 1.21.0

### ISSUE THREAD

**Issue by friendly-pineapple** [spinnaker/spinnaker#5900]
### Issue Summary:
Aloha!

We are seeing an issue where the `spin` CLI is unable to create new pipelines after we have updated Spinnaker to `1.21.0`. For reference, we are running `spin` CLI version `1.17.0`.

### Cloud Provider(s):
GCP

### Environment:
Spinnaker deployed into GKE cluster.

### Feature Area:
Pipelines / `spin` CLI

### Description:
`spin` CLI is unable to create new pipelines, and will print `Encountered an error querying pipeline, status code: 404`.

We believe that this is because the CLI always attempts to fetch the pipeline via application name and pipeline, even if the pipeline was never created before:

https://github.com/spinnaker/spin/blob/version-1.17.0/cmd/pipeline/save.go#L83-L90

Note that in previous Spinnaker versions (i.e. `1.20.4` and below), querying:

`curl -I -X GET /applications/<application-name>/pipelineConfigs/<pipeline-name>`

would return a `200` even when `pipeline-name` does not yet exist, allowing us to proceed through the rest of the logic and eventually create the new pipeline.

However, in the most recent Spinnaker version (`1.21.0`), the same query will now return `404`, resulting in the error above.

### Steps to Reproduce:
`spin pipeline save --file <any pipeline configuration with a brand new pipeline name>`

### Additional Details:
We are seeing this just after updating to Spinnaker `1.21.0`. This appeared to work correctly on Spinnaker `1.20.4` and below.

**Comment by andrijaperovic** [comment]
Is there a timeline when this will be fixed @maggieneterval ?

**Comment by maggieneterval** [comment]
Hi @andrijaperovic! I'm on Spinnaker build cop rotation this week, so I'm tagging all newly opened issues with their appropriate SIG labels. Since there isn't currently a SIG that owns Spin CLI, I don't know that any core contributors will be actively looking into a fix, but a community-contributed fix for this issue would be welcome!

**Comment by vijay-sapient** [comment]
had same issue with spin CLI version 1.17.0 with spinnaker 1.20.6. i tried spin cli 1.14 and it worked fine for me

**Comment by Chinikins** [comment]
I believe this PR would fix this issue: https://github.com/spinnaker/spin/pull/257
