### ISSUE TITLE
Helm3 Bake Manifest fails when lookup method is called from tpl logic

### ISSUE THREAD

**Issue by sdpoueme** [spinnaker/spinnaker#5914]
### Issue Summary:

A spinnaker pipeline is failing when baking a manifest. The helm chart includes a secret which is built based on some conditional logic located in a tpl file. The logic in the tpl file looks up for a resource that is supposed to be located on the target cluster, but when Spinnaker bakes the chart, it tries to read that resource from its runtime cluster. 

### Cloud Provider(s):
Kubernetes v1.16.9

### Environment:

Open Stack

### Feature Area:

Rosco - Bakery

### Description:

The pipeline is baking and deploying an helm chart. The bake manifest stage uses HELM3 as rendering engine. During the bake operation a failure occurs and it shows that a lookup operation has failed. The lookup happens when Spinnaker tries to render the following manifest:

```
apiVersion: v1
kind: Secret
metadata:
  name: "minio-secret"
type: Opaque
data:
{{- ( include "gen.minio.secret" . ) | indent 2 -}}
```
The manifest data is conditionally built using some logic located in the following tpl file:
```{{/*
   https://github.com/helm/charts/issues/5167#issuecomment-619137759
*/}}
{{- define "gen.minio.secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "minio-secret" -}}
{{- if $secret -}}
{{/*
   Reusing existing keys since secret exists
*/}}
accesskey: {{ $secret.data.accesskey }}
secretkey: {{ $secret.data.secretkey }}
{{- if $secret.data.encryptionkey }}
encryptionkey: {{ $secret.data.encryptionkey }}
{{- else if and .Values.minio.tls.enabled .Values.minio.encryptionEnabled }}
encryptionkey: {{ randAlphaNum 10 | b64enc }}
{{- end -}}
{{- else -}}
{{/*
    Generate new keys
*/}}
accesskey: {{ randAlphaNum 10 | b64enc }}
secretkey: {{ randAlphaNum 10 | b64enc }}
{{- if and .Values.minio.tls.enabled .Values.minio.encryptionEnabled }}
encryptionkey: {{ randAlphaNum 10 | b64enc }}
{{- end -}}
{{- end -}}
{{- end -}}


{{/*
   If imagepullsecret does not exist, then create imagepullsecret;
   Else, if imagepullsecret exist and it is part of same chart-release then return existing-secret, otherwise skip
*/}}
{{- define "imagePullSecretCommonRepo" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "dockerrepocommonsecrets" -}}
{{- if $secret }}
{{- if eq (index $secret.metadata.annotations "meta.helm.sh/release-name") .Release.Name -}}
{{- index $secret.data ".dockerconfigjson" -}}
{{- end }}
{{- else }}
{{- with .Values.imageCredentialsCommonRepo }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .repo .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- end }}

```

The bake operation fails with error:

```Exception (Create Bake) 
Bake failed: Error: template: apimdeps/templates/minio-secret.yaml:7:7: executing "apimdeps/templates/minoo-secret.yaml" at <include "gen.minio.secret", > error calling include: template: apimdeps/templates/_helpers.tpl:5:15: executing "gen.minio.secret" at <lookup "v1" "Secret" .Release.Namespace "minio-secret">: error calling lookup: secrets "minio-secret" is forbidden: User "system"service:account:spinnaker:default" cannot get resource "secrets" in API group "" in the namespace "apim". 
```

### Steps to Reproduce:

0. Create an helm3 chart with a secret manifest and logic in tpl files
1. Create a pipeline with bake and deploy manifests stages
2. Run the pipeline 

### Additional Details:
Screenshot from the issue. 
![image](https://user-images.githubusercontent.com/10876571/87450216-3f0c6a80-c5cc-11ea-93ac-06fa14013587.png)

---

**Comment by ethanfrogers** [comment]
@sdpoueme  - Thanks for reporting this. If I'm reading this correctly, you're using the `lookup` function to query Kubernetes for a specific secret and injecting it into the template? If so, I think that's an unsupported use case at this time. The way we've implemented chart baking involves running `helm template` in Rosco, the service for baking things like VMs or Helm Charts. Unfortunately, Rosco doesn't have access to Kubernetes credentials which I assume would be a prerequisite for this type of thing.

**Comment by sdpoueme** [comment]
Hi @ethanfrogers that is correct. We have several SRE teams relying more and more on this type of logic in their helm charts. Thanks for the feedback. I will report this back to the teams and see if I can find a different approach for these templates.

**Comment by sdpoueme** [comment]
Closing this issue.
