### ISSUE TITLE
Gate saml maximum authentication age property should be made configurable

### ISSUE THREAD

**Issue by sanopsmx** [spinnaker/spinnaker#5922]
### Issue Summary:
Gate saml maximum authentication age is hardcoded to 7200 secs(2 hrs). Saml server token is valid by default for 8 hrs. Once the spinnaker session timeout, we enter into a continuous loop with the saml server asking for a new session. Saml server sends the same token , which does not exist in the spinnaker gate.

### Feature Area:
@Gate

### Description:
Gate saml maximum authentication age is hardcoded to 7200 secs(2 hrs). Saml server token is valid by default for 8 hrs. Once the spinnaker session timeout, we enter into a continuous loop with the saml server asking for a new session. Saml server sends the same token , which does not exist in the spinnaker gate.

### Steps to Reproduce:
Configure saml properties in the gate.
Configure your saml server.
Enter Spinnaker deck url.
It will be router to saml login. Enter the credentials and login.
Spinnaker application is opened. Do not do any activity for 2 hours.
Spinnaker logs out and enters into loop.

### Additional Details:

Suggested Solution:

Make the saml maximum authentication age as a configurable parameter.

**Comment by sanopsmx** [comment]
I will be working on this issue.

**Comment by iniinikoski** [comment]
Hi @sanopsmx 

Is this the same issue as here: https://github.com/spinnaker/spinnaker/issues/5539 - or even closely related...?

**Comment by jaygorrell** [comment]
Those appear to be the same. Have you already started on a solution @sanopsmx?

**Comment by sanopsmx** [comment]
Not yet after seeing that this issue is related to 5539. We can make this issue as duplicate of #5539.
