### ISSUE TITLE
Canary Analysis Support is not working on the latest release of 1.21.0

### ISSUE THREAD

**Issue by galvarado** [spinnaker/spinnaker#5939]
### Issue Summary:

Set up Canary Analysis Support is not working on the latest release of 1.21.0 and had to downgrade to the latest 1.20.6 release

### Cloud Provider(s):
Kubernetes

### Environment:
Localdebian

### Feature Area:
Canary Analysis

### Description:
I am trying to enable canary following:https://spinnaker.io/setup/canary/:
```
hal config canary enable
hal config canary google enable
hal config canary google account add my-google-account \
  --project $PROJECT_ID \
  --json-path $JSON_PATH \
  --bucket $MY_SPINNAKER_BUCKET
hal config canary google edit --gcs-enabled true \
  --stackdriver-enabled true
```
Next, set the Spinnaker version to v1.7.0 or higher:

```
hal config version edit --version 1.7.0
```

Lastly, update your Spinnaker deployment to include Kayenta:

```
hal deploy apply (to Kubernetes) 
sudo hal deploy apply (to local VM)
```

 I have made the configuration changes but I am unable to see the checkbox in the UI (Application config). After downgrade to  1.20.6 release with the same config now Canary checkbox at the UI is visible:

```
hal config version edit --version  1.20.6 
sudo hal deploy apply
```

Canary analysis configuration and reporting cehckbox is now visible.

### Steps to Reproduce:
Try to enable Canary following https://spinnaker.io/setup/canary/ on the latest release of 1.21.0 

### Additional Details:
After downgrade to  1.20.6 release with the same config now Canary checkbox at the UI is visible

---

**Comment by maggieneterval** [comment]
@galvarado thanks for taking the time to write this up.

Unfortunately, there are currently two flags required to enable the canary front-end and back-end integrations in Spinnaker. Do you have both of the following blocks in your halconfig?

```
canary:
  enabled: true
```
```
features:
  mineCanary: true
```

My guess is that you are missing the `features` flag. In 1.21, we began only registering Canary data sources in Deck when that flag is enabled, to [fix a different issue](https://github.com/spinnaker/spinnaker/issues/5588) folks were encountering when they didn't expect the canary UI to be enabled.

I'd like to remove the need for the `features` flag and have Deck consume the same `canary` flag as the other microservices. I'll shoot for the 1.22 release to make that change, but in the meantime you can work around it by adding the other flag ([hal command](https://spinnaker.io/reference/halyard/commands/#hal-config-features-edit)).

**Comment by maggieneterval** [comment]
@galvarado thanks again for reporting this -- this was 100% my bad! The workaround I described in my previous comment of adding the `features.mineCanary` flag should do the trick for 1.21, but in 1.22 you will be able to remove it and the `canary.enabled` flag will be sufficient to enable the canary UI.

**Comment by galvarado** [comment]
ok thanks for your clarification @maggieneterval  so from what i understand we can confirm an issue with canary.enabled flag in 1.22, it is being  ignored or is not sufficeint to enable the canary UI
