### ISSUE TITLE
build and release process for spinnaker projects

### ISSUE THREAD

**Issue by cfieber** [spinnaker/spinnaker#594]
# Build and Release for Spinnaker projects - Proposal
This issue proposes a build and release process for spinnaker projects

### Developer
* develops/runs against HEAD of all services
* may implement a change that requires a coordinated merge and deploy across multiple services

### Integrator
* wants a stable set versions known to work together
* wants to understand upgrade requirements (e.g deploy orca before deck, run XYZ migration)

### Committer
* want some level of confidence in accepting pull requests

### build via travis-ci
* builds pull requests
* add github branch protection for developer branch and integrator branch
 * prevents accidental force push
 * requires builds pass before merging PRs into these branches

### version via github tags
* current gradle plugin uses git tags for versioning (`vN.N.N`)
* supports final (`vN.N.N`), candidate (`vN.N.N.rc.N`), and devSnapshot (`vN.N.N-dev.N+hash`) tag generation (see [Nebula Release Plugin](https://github.com/nebula-plugins/nebula-release-plugin#tasks-provided))

#### developer
* today this is `master`
* should be always buildable (ideally runnable/non broken)
* developers run off this branch and PR to this branch

#### integration
* on some cadence, merge a known good version from the developer branch to this branch

### work from forks
* even for those with write access - work in a fork an PR into the main repo
 * prevents pull builds / snapshot publishes in the main repo

### Developer
1. Accept PRs into developer branch
 * travis-ci build ensures tests pass
2. Create tag for developer release
3. travis-ci builds and publishes release from developer branch

### Integrator
1. PR developer branch to integrator branch
 * travis-ci build ensures tests pass
2. Tag integrator branch
3. travis-ci builds and publishes release fron integrator branch

## Questions
* Integrator branch
 * which branch? (`master`, `release`, `???`)?
 * release-train for services?
 * what versioning strategy ? ( final? )
* developer branch
 * which branch? (`master`, `develop`, `???`)
 * what versioning strategy? (candidate?)
  * right now - auto-incrementing minor version number per master commit
  * potentially - candidate?
* how do we version packages (deb/rpm)
 * naming restrictions on versions
 * Need to map developer (prerelease) and integrator (release) versions to ospackage
  * rpm guidelines - https://fedoraproject.org/wiki/Packaging:NamingGuidelines#Pre-Release_packages
  * deb guidelines - https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**Comment by cfieber** [comment]
I have tested out branch protection and travis-ci builds on the [kork library project](https://github.com/spinnaker/kork) - https://travis-ci.org/spinnaker/kork

Going to work with @rspieldenner to get some more examples of how other teams are doing releases via the [netflixoss-project-plugin](https://github.com/nebula-plugins/gradle-netflixoss-project-plugin) and travis-ci

**Comment by cfieber** [comment]
@duftler @ttomsu @gregturn @ewiseblatt - have any opinions from the developer perspective?

@ewiseblatt @dstengle @dpeterka @skorten - have any opinions from the integrator perspective?

**Comment by tomaslin** [comment]
So right now deck is on version v2.439.0 but rosco is version v0.12.0. 

It would be nice if our versioning scheme shared one common number across all services that would get bumped out whenever we cut a major release. I would have expected releasing of Spinnaker to be tagged as version v2 in all APIs, for example. 

Don't see a reference to this in the doc and wonder if it should be considered. Would make grouping of the images and individual services much more logical for consumption.

**Comment by tomaslin** [comment]
do we see a need to have a critical vulnerability / yolo branch mechanism or process here that will allow some sort of hotfix release to happen that would allow a non-passing build to be merged?

**Comment by duftler** [comment]
Thanks for putting all this together @cfieber. Just reading it now.

I agree with @tomaslin  on the versioning. It would make troubleshooting much easier (if the numbers aren't sync'd, we'll be hunting down tags or a table of what versions of each module go together).

**Comment by dpeterka** [comment]
**Repos:**
I would like to have a stable unstable repository available which means maintain at least one "head" branch to run tests against.  A developer is likely to just test a single service whereas the umbrella spinnnaker will be pulling in all versions.
**Packages**
Should delineate in package name if possible beta,rc. Spinnaker version should increment if child packages increment (maybe just sum the version tags???)
**Branches**
Given the above that's really either head and tags (unstable/stable) or two branches.  I don't really see any huge reason to deviate from standard git flow here: master,develop, release (branch or tags)
**Artifacts**
We've GCE/Amazon images, Packages (RPM/Deb), services themselves, .jars and gradle plugins to account for here.  One take-away I would like to get is consistency and the ability to trace back quickly to source so that if an issue is encountered we can hopefully deduce where it came from quickly.
**Issues** 
If we are testing packages and developers are working on various forks we would require a third fork to keep just for running the package builds.

**Comment by dstengle** [comment]
Probably the first thing we need to figure out is what we are doing with semantic versioning and how this impacts various artifacts of the build process.

For instance, if we want a common numbering scheme across the services, it would be useful to let individual services drift on patch and all bump on minor OR major depending on the semantic meaning of the release. Everyone seems to consider spinnaker a single product, so it will just be a matter of a release maintainer, probably @cfieber,  deciding if the release is major or minor depending on the content of the constituent parts.

As far as the individual release numbering, having commits produce a new version number is really useful for packaging, since it forces apt to pull a new package down.

On a related note, what is the plan for Long Term Support? That will require some more thought for branching and versioning, like maybe we wouldn't want to increase patch so that prior releases could be patched easily.

**Comment by ewiseblatt** [comment]
On Versioning:
I agree that spinnaker should be versioned as a product. But it isnt clear that means that the independent systems have versions tied to it. It would be nice if that were possible, but the components are independent and have their own lifecycles. A change in echo's bus would be a major version change, but that doesnt necessitate a major version change in clouddriver. I think the complexity comes from these all being different repositories, not the version numbering of the components themselves.

I assume others have addressed this issue before. I'm not familiar with the solutions, but we should look into that.

Intuitively, I'd want to add "spinnaker product version" tags in addition to the existing component versioning tags. So the version tags could remain as they are, but there would be a cross-cutting spinnaker version tag also layed down when you "cut" a release. So from a product perspective you could pull that tag new but from a component perspective you pull the existing tag. If you need a product-level patch update, it would be the closure of latest patch release of each minor subsystem version in the product tag for each subsystem.

**Comment by ttomsu** [comment]
Ref: http://blog.codinghorror.com/whats-in-a-version-number-anyway/

In projects past, I've found versioning with dates far more useful than incremental versioning (i.e. v2015.08.19-RC01 vs v2.3.1) This syncs up all version numbers across components.

As for backwards incompatible changes, a major version could be introduced as a prefix. Example:

* v1-2015.11.01-RC00
* v1-2015.11.03-RC00 (cut, includes bug found during testing later that day)
* v1-2015.11.03-RC01 (bug fixed)
* v1-2015.11.05-RC00
* v2-2015.11.07-RC00 (breaking change introduced, major version incremented)

**Comment by ewiseblatt** [comment]
@ttomsu I'm thinking your date proposal makes sense for what I was calling a spinnaker product version. As for the subsystem components, whether dates, numbers or something else, i'm not sure that you want to change the version number of something that hasnt changed. If I release a new spinnaker but rush hasnt changed, does that rush component get a new version number? I can argue either way and dont really care what the answer is myself, just asking the question in case someone else can see where it matters.

**Comment by ttomsu** [comment]
@ewiseblatt I would argue that yes, even if the component hasn't changed, it will get a new version number.

The primary reason is for troubleshooting a user's issue. If a user says "I'm seeing a bug in echo on version X", then it's very easy to get all of your components on that same version to try to reproduce. Otherwise, you would have to go hunting for what version was clouddriver on at that time, how about orca, how about deck, etc...

**Comment by gregturn** [comment]
I don't know if dragging all the modules along to the same major version number is worth the effort. With a little investment in the gradle builds, you can generate a [git.properties file](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-git-commit-information), Spring Boot will pick up that info and serve it underneath /info. That makes it easy to fetch what version each module is running at.

**Comment by robfletcher** [comment]
I'm very much in favor of coordinating the version numbers across µservices. With git tags it's not a problem to have multiple versions point to the same commit if a particular service doesn't change. It makes things so much simpler from a user point of view and makes it clearer when we have a requirement for a coordinated rollout, for example an API change that affects both _deck_ and _gate_.

**Comment by duftler** [comment]
I'm still in favor of coordinated version numbers as well.

**Comment by ajordens** [comment]
Personally, I don't really think of Spinnaker as a single product but can see how doing so creates a more consistent picture for the OSS releases.

`wants to understand upgrade requirements (e.g deploy orca before deck, run XYZ migration)`

I'd really like to see a strong avoidance of the need for coordinated upgrade or migration processes.

**Comment by johnrengelman** [comment]
Even if the version numbers on the micro-services aren't kept in lock step, it would be nice if there was a top-level `spinnaker` version that corresponded to a selection of versions of the various components. i.e Spinnaker 1.0.0 maps to gate 0.12.0, deck 2.19.0, etc.
This would be helpful when versioning other distributions (i.e. AMIs or other coordinated packages that wrap all the components).

**Comment by cfieber** [comment]
> Spinnaker 1.0.0 maps to gate 0.12.0, deck 2.19.0, etc.

That makes sense. Currently the spinnaker repo is publishing a versioned deb file, but the requires inside it are not version locked at all. We should update that for sure.

**Comment by cfieber** [comment]
> I'd really like to see a strong avoidance of the need for coordinated upgrade or migration processes.

Agree, but it feels like it is going to happen (we just migrated how many pipeline executions?). Specifically for someone who is deploying all of spinnaker and migrating from release to release of that, I'd expect there may be cases where we've (developers, deploying each service per release) rolled through a series of changes that along the way were incremental updates but if compared from start to finish maybe aren't?

**Comment by cfieber** [comment]
I've pushed travis-ci config to all the repos, and enabled/tested it out on a couple (see https://travis-ci.org/spinnaker/)

This doesn't address the open questions around exactly what semantics of version numbers we should use, but it will maintain the status quo (merge to master releases the next .minor version increment) with the builds in the open and able to be initiated by anyone with project commit access.

Once this is enabled, this will be the repercussions on the repos:
`master` becomes a protected branch. You can't force push to it
`master` requires travis-ci checks to pass (You have to merge in via a PR)

The release process becomes:
A committer drafts a new release in the repo ( e.g. https://github.com/spinnaker/kork/releases ) or pushes a tag to the repo
Travis-CI build picks up the tag and runs the release build which publishes jars and debs to bintray

Known issues:
pushing a release candidate version (e.g. 0.1.0-rc.1) will result in pushing a deb that truncates the rc component of the version string, and trying to push a final release of that version will result in a 409 conflict trying to publish a deb (jars are not affected).  Upgrading to https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v3.2.0 will potentially resolve this issue. For now - keep versions as final.

**Comment by ajordens** [comment]
> Agree, but it feels like it is going to happen (we just migrated how many pipeline executions?). Specifically for someone who is deploying all of spinnaker and migrating from release to release of that, I'd expect there may be cases where we've (developers, deploying each service per release) rolled through a series of changes that along the way were incremental updates but if compared from start to finish maybe aren't?

Although we migrated a lot of executions, it was contained within a single service with no need to coordinate a rollout.

Perhaps it speaks to needing (and introducing as necessary at the point of first migration) version identifiers across durable data. In theory migrations should be treated as legitimate and long-lived artifacts that have some cadence around when they're deprecated and removed from the code base?

**Comment by cfieber** [comment]
+1 to versioning durable data

**Comment by cfieber** [comment]
CI and release builds are in place, still TODO is the versioning semantics

**Comment by cfieber** [comment]
We had discussed building a script that captures the current package versions that we are running in each environment and using that as something that feeds into the spinnaker deb file build to pin versions of all the components.

We could capture the versions we are running in prod at Friday at midnight and cut a spinnaker stable release off that (choosing Friday as it is semi unlikely we would have promoted some risky feature just before the weekend...)

If we could get other providers to export the same set of data from deploys they manage we would get some potentially better coverage across platforms.

Good/bad/ugly idea?

**Comment by gregturn** [comment]
I think a weekly automated cadence would work fine.

**Comment by skorten** [comment]
We've been thinking about the need for something like this WRT to the community AMIs and had it on our list to restart the conversation.  So, definitely a good idea.

**Comment by ewiseblatt** [comment]
Sounds like a good start. Not sure how you would correlate all the
different combinations into a definitive version, but we can figure that
out as we go. The concern is that if kato remains the monolith it is
(within the larger clouddriver) then when provider platforms are stable at
different releases, what does a multi-cloud user deploy?

The reporting tool should be included with the runtime product so that
customers can report back their configuration along with bug reports or
other diagnostic/support needs.

**Comment by gregturn** [comment]
I would put an info.properties file in each component. Since they're all boot apps. The metadata would served automatically.

**Comment by tomaslin** [comment]
We now have a job that will publish the Netflix current production snapshot into this gist - https://gist.github.com/tomaslin/d7846caa6fc62057d1dc . I will add this to spinnaker/spinnaker and the new site.

**Comment by ajordens** [comment]
Close due to lack of activity ...
