### ISSUE TITLE
Spinnaker v1.21.2 does not honour given pipeline ID when saving new pipeline with spin

### ISSUE THREAD

**Issue by stellirin** [spinnaker/spinnaker#5945]
### Issue Summary:
We create pipelines exclusively with spin, with jsonnet to generate the actual json pipeline. After upgrading from 1.18 to 1.21 we can update existing pipelines, but new pipelines do not use the provided pipeline ID. Instead, a random UUID is used.

### Cloud Provider(s):
GCP

### Environment:
Halyard is used to deploy Spinnaker to a GKE cluster.

### Feature Area:
Pipelines

### Description:
We depend on a stable pipeline ID to periodically update pipelines as needed. When the pipelines are created with random UUIDs, update is not possible without storing the UUIDs somewhere. We have hundreds of pipelines, so storing lists of UUIDs is not practical.

### Steps to Reproduce:
**test.json**
```json
{
   "application": "dialogflow-agents",
   "id": "test-pipeline",
   "name": "Test Pipeline"
}
```
```sh
cat test.json | ./spin pipeline save
Pipeline save succeeded

cat test.json | ./spin pipeline save
pipeline ID "test-pipeline" does not match the found pipeline "Test Pipeline" in application "dialogflow-agents" with ID "651ecf94-dd1f-4d2f-9cc6-7cad63a70ba4"
```

### Additional Details:
spin is compiled from spin master as of 2020-07-27, latest spin release suffers from 404 issue that is fixed with https://github.com/spinnaker/spin/commit/f971df571a0302f80a29d260e74933f24a510248

![image](https://user-images.githubusercontent.com/1012095/88629299-5e68c480-d0af-11ea-8e4a-9882b5ef2e25.png)

**Comment by robzienert** [comment]
We do not allow user-defined identifiers for pipeline configs or pipeline executions, however there is (deprecated) capabilities of referring to a pipeline config by its name, which you could try using. This deprecated functionality is dangerous, however, if you happen to accidentally create two pipeline configs with the same name, you will end up having a "ghost" pipeline config which can cause a lot of confusion - hence the deprecation, and eventual removal, of this feature.

**Comment by kskewes** [comment]
Hmm, we also make heavy use of setting pipeline config's (id) as we:
1. generate all projects, apps, pipelines client side in jsonnet.
2. use the `id`'s in pipelines that have a `pipeline` stage. Because we know the id's we have set this is easy to do.
3. take care to avoid collisions locally.

`Project` json also requires submitting the pipeline config id, see below `aws-k8s-cni-dos` being the pipeline config:
```json
{
   "config": {
<snip>
      "pipelineConfigs": [
         {
            "application": "aws-k8s-cni",
            "pipelineConfigId": "aws-k8s-cni-dos"
         },
```

To use UUID we would need an intermediate stage to hydrate pipeline configs into our repo. :(

**Comment by stellirin** [comment]
> We do not allow user-defined identifiers for pipeline configs or pipeline executions

Sorry but, whether intentional or not, choosing the ID has been possible for at least a _year_, (when my team started using Spinnaker, which I then inherited when I joined 6 months ago). I'm sure we're not the only ones that rely on this feature.

So let's look at some ways to workaround.

I see we can get the pipeline ID from spinnaker with something like:

```sh
spin pipeline get --application='dialogflow-agents' --name='Test Pipeline' | jq -r '.id' 
```

I also see that omitting the ID completely does update the correct pipeline, because at least Names are unique within an Application:

**test.json**
```json
{
   "application": "dialogflow-agents",
   "name": "Test Pipeline 2"
}
```
```sh
cat test.json | ./spin pipeline save
Pipeline save succeeded

cat test.json | ./spin pipeline save
Pipeline save succeeded
```

With this we can trivially fix _some_ of our pipeline generators by simply removing `.withId(pipelineId)`.

That does not help for pipelines that trigger another pipeline as one of its stages. Here you must reference the pipeline by ID, so we will have to introduce additional logic somewhere to pre-generate dependent pipeline names, retrieve the pipeline IDs based on application and name, then inject those IDs into the pipeline generators.

There's gonna be some unhappy folk at today's standup. 😱 

But clearly Spinnaker can and does work perfectly fine with custom pipeline IDs, I see no reason why this shouldn't be officially supported as an 'advanced' feature. Please reconsider!

**Comment by kskewes** [comment]
> That does not help for pipelines that trigger another pipeline as one of its stages. 

I wonder if it's possible for pipeline stage and Projects to accept app name and pipeline name as values instead of using ID's. 

Spinnaker would need to hydrate server side at execution of pipeline or Project page view?

This also might require enforcing unique pipeline names if not done already. Can't think of a use case for reusing pipeline name and it would be very confusing. 
We don't use MPTv# so not sure if something there.

**Comment by robzienert** [comment]
I took a closer look and I spoke incorrectly - custom pipeline config IDs _are_ deliberately allowed. I'll update the ticket and will investigate a fix personally. Sorry for the scare. :(

**Comment by robzienert** [comment]
I was unable to reproduce this in our environments by submitting to the API directly (not using `spin`). I'm working on getting `spin` on my machine so I can test there.

**Comment by Chinikins** [comment]
So this line is new: https://github.com/spinnaker/spin/blob/master/cmd/pipeline/save.go#L92 but that was put in because of issues in being able to create new pipelines. See https://github.com/spinnaker/spinnaker/issues/5900 so is the Gate returning a 404 incorrectly causing the ID to be blown away?

**Comment by Chinikins** [comment]
I'm able to reproduce this after updating our spinnaker to latest and with spin cli built from latest master, I can save new pipelines but if I try to save them again, the ID was ignored in the save. i.e.

`pipeline ID "given pipeline id sent" does not match the found pipeline "given pipeline name sent" in application "appName" with ID "cc7a22e4-5569-456c-933c-aa9372f124d3"`.

It seems the ID is being randomly set regardless of if sent in the payload or not.

On the latest Spin CLI built from the 1.17.2 tag, a new pipeline save from the same payload returns the 404 error.

**Comment by kevinawoo** [comment]
@robzienert, @Chinikins I remove the pipeline ID check from spin cli to go back to the previous behavior of allowing custom config IDs https://github.com/spinnaker/spin/pull/289.

**Comment by kevinawoo** [comment]
I just cut a release for the [spin cli 1.17.3](https://github.com/spinnaker/spin/releases/tag/version-1.17.3) which was made for Spinnaker v1.21.2. Can you all give it a try? 🙏 🙏

**Comment by stellirin** [comment]
@kevinawoo I just tested `version-1.17.3` and it seems to be fixed. Thanks!

**Comment by kskewes** [comment]
Tested with `spin` master and it seems fixed. Thanks very much.
