### ISSUE TITLE
Spinnaker UI/Deck: Uncaught TypeError RunJobExecutionDetails.tsx:58

### ISSUE THREAD

**Issue by andrijaperovic** [spinnaker/spinnaker#5951]
### Issue Summary:
Observing a crashed DOM when inspecting a runJob stage of v2 pipeline in 2.21. 

### Cloud Provider(s):

GCP 

### Environment:
Kubernetes/GKE v1.16.9-gke.6
Deployed using gcr.io spinnaker-marketplace images

### Feature Area:
Spinnaker Deck (UI)
gcr.io/spinnaker-marketplace/deck:3.2.0-20200625152925

### Description:
Observing a DOM failure with the following exception in the dev console: 
The UI goes completely blank after clicking on the runJob stage. 

```
react-dom.production.min.js:248 Uncaught TypeError: Cannot destructure property 'resources' of 'cluster' as it is undefined.
    at RunJobExecutionDetails_RunJobExecutionDetails.render (RunJobExecutionDetails.tsx:58)
    at Qg (react-dom.production.min.js:173)
    at Og (react-dom.production.min.js:172)
    at Tg (react-dom.production.min.js:180)
    at bi (react-dom.production.min.js:232)
    at ci (react-dom.production.min.js:233)
    at Di (react-dom.production.min.js:249)
    at Yh (react-dom.production.min.js:248)
    at Xh (react-dom.production.min.js:245)
    at qf (react-dom.production.min.js:243)
```

### Steps to Reproduce:

Create a v2 runJob stage as part of a multi-stage pipeline object (without use of templates). 

The request looks like this:
https://spinnaker-env.com/#/applications/scai/executions/01EEF07BX15MCYKVYM6Z8WTPRN?q=gamma&pipeline=pipeline1,pipeline2&stage=18&step=0&details=runJobConfig

### Additional Details:

N/A

**Comment by andrijaperovic** [comment]
@robzienert can you tag this with spinnaker ui/ux label and tag the relevant team?

**Comment by maggieneterval** [comment]
@andrijaperovic thanks for reporting this issue. The exception you mentioned appears to be [from the Titus provider's Run Job execution details](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx#L58). To clarify, are you running the Kubernetes Run Job stage or the Titus Run Job stage? I'm unable to reproduce this issue running at latest release for the Kubernetes Run Job stage.

**Comment by andrijaperovic** [comment]
@maggieneterval this is the Kubernetes Run Job stage in the OSS spinnaker.

**Comment by maggieneterval** [comment]
Thanks for clarifying; are you able to provide some minimally reproducible stage config JSON for the Run Job stage resulting in this error? And just to confirm, what top-level OSS release of Spinnaker are you running?

**Comment by andrijaperovic** [comment]
@maggieneterval sorry for the late response. 
We are running Spinnaker OSS 1.21.2. 
Here is the snippet of our create upgrade db stage which is the runJob stage for which the stage expansion in execution details causes the DOM failure: 

```
{
        "account": "{{ account }}",
        "cloudProvider": "kubernetes",
        "completeOtherBranchesThenFail": false,
        "continuePipeline": true,
        "failPipeline": false,
        "manifestArtifactAccount": "{{ artifact_account }}",
        "manifestArtifactId": "job_create-upgrade-config-db-artifact",
        "moniker": {
          "app": "scai"
        },
        "name": "Create/Upgrade Config DB Schema (Job)",
        "refId": "18",
        "requiredArtifactIds": [],
        "requiredArtifacts": [],
        "requisiteStageRefIds": [
          "1",
          "2"
        ],
        "skipExpressionEvaluation": false,
        "source": "artifact",
        "trafficManagement": {
          "enabled": false,
          "options": {
            "enableTraffic": false,
            "services": []
          }
        },
        "type": "runJob"
      },
```

**Comment by maggieneterval** [comment]
Hey @andrijaperovic, the `type` for a Kubernetes Run Job stage should be `runJobManifest`, not `runJob` ([source](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/pipelines/stages/runJob/runJobStage.ts#L18)). If changing that doesn't resolve this issue, please feel free to re-open. Thanks!

**Comment by andrijaperovic** [comment]
Hi @maggieneterval , 
Seeing the following issue after modifying our pipelines to use `runJobManifest`:
```
No StageDefinitionBuilder implementation for runJobManifest(alias: null) 
```
