### ISSUE TITLE
Spinnaker Pipelines: No StageDefinitionBuilder implementation for runJobManifest(alias: null) 

### ISSUE THREAD

**Issue by andrijaperovic** [spinnaker/spinnaker#5957]
### Issue Summary:

Observing the error No StageDefinitionBuilder implementation for runJobManifest(alias: null) when using stage type of runJobManifest (as opposed to runJob which was used previously). 

### Cloud Provider(s):

GCP 

### Environment:

N/A

### Feature Area:

Pipelines

### Steps to Reproduce:
```
No StageDefinitionBuilder implementation for runJobManifest(alias: null) found (knownTypes: googleCloudBuild,upsertDeliveryConfig,shrinkCluster,reorderPipelines,upsertLoadBalancers,resumeRolloutManifest,modifyAsgLaunchConfiguration,upsertEntityTags,deleteSnapshot,deregisterInstancesFromLoadBalancer,bulkUpsertEntityTags,quickPatch,deleteLaunchConfiguration,destroyAsg,runJob,deployCloudFormation,checkPreconditions,createV2PipelineTemplate,determineTargetReference,clouddriverClearAltTablespace,upsertSecurityGroup,manualJudgment,upsertLoadBalancer,getProperties,disableCluster,modifyGceAutoscalingPolicy,deployService,script,restoreSnapshot,gremlin,disableManifest,terminateInstanceAndDecrementServerGroup,copyAmazonLoadBalancer,rollbackCluster,disableInstancesInDiscovery,cloneServerGroup,updatePipeline,setStatefulDisk,wait,serverGroupForceCacheRefresh,deleteTencentCloudScheduledAction,statefullyUpdateBootImage,upsertDisruptionBudget,saveSnapshot,upsertAmazonDNS,findImage,scaleManifest,awsCodeBuild,undoRolloutManifest,noop,upsertAsgScheduledActions,enableInstancesInDiscovery,deleteEntityTags,concourse,createPipelineTemplate,findArtifactsFromResource,destroyService,registerInstancesWithLoadBalancer,jenkins,rebootInstances,rollbackServerGroup,upsertServerGroupTags,captureSourceServerGroupCapacity,upsertPluginInfo,destroyJob,cloudOperation,bulkQuickPatch,deployManifest,scaleDownCluster,findImageFromTags,pipeline,upsertScalingPolicy,upsertProject,detachInstances,updateApplication,preconfiguredWebhook,createApplication,deleteDeliveryConfig,unmapLoadBalancers,terminateInstanceAndDecrementAsg,modifyAwsScalingProcess,rollingPush,shareService,enableServerGroup,disableServerGroup,savePipelinesFromArtifact,webhook,deleteLoadBalancer,createServiceKey,resizeServerGroup,updateV2PipelineTemplate,waitUntil,patchManifest,deploy,deleteManifest,lambdaFunction,upsertAmazonLoadBalancer,evaluateVariables,determineTargetServerGroup,updateJobProcesses,deleteImage,enableManifest,setPreferredPluginRelease,jira,deleteSecurityGroup,upsertAsgTags,enableAsg,wercker,waitForCondition,deleteProject,preconfiguredJob,updatePipelineTemplate,copySecurityGroup,deleteV2PipelineTemplate,mapLoadBalancers,restrictExecutionDuringTimeWindow,loadPluginRelease,terminateInstances,savePipeline,pauseRolloutManifest,startAppEngineServerGroup,dependsOnExecution,upsertTencentCloudScheduledActions,updateSecurityGroupsForServerGroup,modifyScalingProcess,upsertApplication,applySourceServerGroupCapacity,updateLaunchConfig,findArtifactFromExecution,bakeManifest,upsertAppEngineLoadBalancers,stopAppEngineServerGroup,copyLastAsg,pinServerGroup,upsertImageTags,deleteApplication,modifyScalingGroup,deletePipelineTemplate,rollingRestartManifest,bulkDestroyServerGroup,disableAsg,modifyAsg,resizeAsg,unshareService,pageApplicationOwner,createServerGroup,deleteAmazonLoadBalancer,deleteScalingPolicy,bake,travis,destroyServerGroup,deleteServiceKey)
```
Create a stage that runs a Kubernetes job (with the v2 provider).

### Additional Details:

Linked to https://github.com/spinnaker/spinnaker/issues/5951 @maggieneterval

**Comment by maggieneterval** [comment]
Hi @andrijaperovic, sorry that you took the time to open a new issue -- I saw your reply on the other issue and was about to respond there.

I'm not sure how you ended up in a state where the `alias` is missing from your stage config, but for the Kubernetes Run Job stage, both of the following fields are required:
```
type: runJobManifest
```
```
alias: runJob
```

Check out this [comment](https://github.com/spinnaker/spinnaker/issues/4888#issuecomment-531386503) for further details.

Thanks!

**Comment by andrijaperovic** [comment]
Thanks @maggieneterval , can you share some information on how Deck can be configured to generate the stage type with the alias? I'm not able to deduce what the next steps are for our configuration from the comment on #4888. Would be quite helpful.

**Comment by maggieneterval** [comment]
@andrijaperovic sorry for the confusion -- Deck should automatically add the correct `type` and `alias` when you are configuring a Run Job (Manifest) stage from the UI. How are you generating your pipeline JSON? If you have some stages that somehow ended up in an incorrect state, you can manually correct these fields using the "Edit as JSON" functionality in Deck.

**Comment by andrijaperovic** [comment]
@maggieneterval we were originally using pipeline templates, but due to performance concerns are creating pipeline objects in Spinnaker directly using spin-cli. `runJob` was working fine, with recent upgrades of Spinnaker we have encountered this UI bug which I mentioned originally in #5951 .

**Comment by andrijaperovic** [comment]
Would it be possible to add some exception handling in the React JS layer to handle property `resources` of `cluster` being undefined?

**Comment by maggieneterval** [comment]
> @maggieneterval we were originally using pipeline templates, but due to performance concerns are creating pipeline objects in Spinnaker directly using spin-cli. runJob was working fine, with recent upgrades of Spinnaker we have encountered this UI bug which I mentioned originally in #5951 .

That's strange; I'm not sure how this could have been working in a previous version of Spinnaker, since my understanding is that both the correct `type` and `alias` must be defined for the Run Job (Manifest) to work. On which version was this working for you? When you downgrade back to that version, are you able to successfully run a Run Job (Manifest) stage without the `alias` defined? Can you send a screenshot of the execution details?

> Would it be possible to add some exception handling in the React JS layer to handle property resources of cluster being undefined?

These errors you were seeing around properties of `cluster` being undefined were coming from a different cloud provider's Run Job stage execution details component, which Deck was attempting to load as a fallback because you did not have the type/alias of the stage properly defined. I don't think these fields are ever expected to be undefined in that cloud provider's Run Job stage.

**Comment by andrijaperovic** [comment]
@maggieneterval I believe we were just using `type: runJob` prior with no `alias` defined, after adding `alias` key to the pipeline JSON of each `type: runJobManifest` stage in Spinnaker version 1.21.2, things are working as expected. 

I am not certain if we can do that downgrade testing to verify the behavior of only supplying `type: runJob` without `alias` in a previous version, simply because this is a shared environment with other teams.

Thank you for your help and the detailed explanation of the UI behavior, it helped us resolve this issue.
Let me know if I should close out this issue.
