### ISSUE TITLE
Testing process for Spinnaker projects

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#596]
Similar to @cfieber 's thread on versioning (https://github.com/spinnaker/spinnaker/issues/594), I think it's prudent to start a similar discussion on integration testing across different providers. I know I've introduced changes that inadvertently broken NFLX, and it's likely to get more complex as CF and MSFT contribute more and more. 

@ewiseblatt has written a cloud testing framework that invokes a Spinnaker REST API with a test payload, then uses the provider-specific CLI tool to verify the expected change is made on the backend.
I think a combination of this and Protractor tests would be good to at least have some confidence that any particular build does what we expect it to.

I believe @anotherchrisberry and @zanthrash had some opinions on Protractor tests that I'd like to hear.

Other ideas? @duftler @lwander @gregturn @rguthriemsft  @tomaslin @ajordens

**Comment by aglover** [comment]
I really like the idea of employing @ewiseblatt's test suite although Python might be a slight learning curve for implementers.

**Comment by tomaslin** [comment]
We had some success with pipelines that exercise a set of tests ran on a cron process. We should at the least have a set of checked in pipelines that all new code must see pass before it is deemed production ready. 

Now that Spinnaker is more portable, it would be nice to spin up a Kubernetes or Docker Compose cluster to test each permutation of providers ( ie. AWS only, AWS + GCE, GCE only , AWS + Azure + GCE ).

**Comment by duftler** [comment]
Great idea.

**Comment by ajordens** [comment]
I see some movement on the `citest` front ... otherwise close due to lack of activity.
