### ISSUE TITLE
Wrap spinnaker in a C# project

### ISSUE THREAD

**Issue by KingCrah** [spinnaker/spinnaker#5969]
I wrote an C# project with Visual studio 2017.
Then I need to wrap spinnaker in my project to get images and save images.
I modified .csproj to reference spinnakerNET_v140.dll accroding to it's target platform like "anycpu" or "x64".
I added the files in Spinnaker\bin64\vs2015 with [XMLParser_MD_VC140_v3_0.dll,
 Spinnaker_v140.dll,
 MathParser_MD_VC140_v3_0.dll,
 Log_MD_VC140_v3_0.dll,
 libiomp5md.dll,
 GenTL_v140.dll,
 GenApi_MD_VC140_v3_0.dll,
 GCBase_MD_VC140_v3_0.dll,
 GCBase_MD_VC140_v3_0.dll]
Then, the project can build and run, but with the method of "GetCameras" -- always can not get any cameras.
Did I missed any .dll or other files?
Or what should I do to solve this problem.
Thanks so much

**Comment by KingCrah** [comment]
And I change target platform to x86.
Then, compiler said it didn't find spinnakerNET and spinnakerNET.Genapi, I add the SpinnakerNet into .csproj , but I got this error.

**Comment by christopherthielen** [comment]
This repo is for http://spinnaker.io, not https://www.flir.com/products/spinnaker-sdk/
Sorry!
