### ISSUE TITLE
Conflicting 'Base OS' options in Bake stage

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#597]
This has bothered me for a while - 'trusty' and 'ubuntu' are confusing options in the Bake stage, since Trusty is a very of Ubuntu.

@cfieber Since the bake stage is now provider specific, I can fix it for GCE, but I still think it's confusing for AWS users. IIRC from a convo we had a while back, your in-house bakery expects `ubuntu` and `trusty` as param values, correct? 

FYI - @duftler (rosco), @anotherchrisberry (deck)

**Comment by duftler** [comment]
I think all we need to do is serve up from the backend a list of Base OS options derived from here: https://github.com/spinnaker/rosco/blob/master/rosco-web/config/rosco.yml#L35-L117

And then all bake stages can just render that list as the set of radio buttons. The labels will just be opaque choices as far as the frontend is concerned (that's all they are now anyway), and the backend won't have to change anything as it already maps whatever name is passed down to the configured image attributes.

**Comment by skorten** [comment]
I submitted a PR to remove the "ubuntu" definitions as they are for 12.04 and should not be included.

**Comment by ttomsu** [comment]
Could you paste the link to the PR here?

**Comment by jpancoast-kenzan** [comment]
Canonical publishes a (invalid) json file of all their releases for AWS:

http://cloud-images.ubuntu.com/locator/ec2/releasesTable

I did this in python to get it to the point where it can be parsed:

```
ubuntu_good_json = re.sub("],\n]\n}", ']]}', ubuntu_bad_json)
```

**Comment by ttomsu** [comment]
All set on this issue. Please let me know if you have any troubles.
