### ISSUE TITLE
AWS ECS create server group UI not loading

### ISSUE THREAD

**Issue by pkandasamy91** [spinnaker/spinnaker#5971]
When adding a new ECS Server Group to an existing pipeline, the UI loads the popup in the background. This prevents the user from being able to interact with the popup, and thus is not able to configure or close the popup. The only way to exit the popup is to refresh the page.

Looks to be specific to how Deck loads the different provider widgets/popups.

<img width="1280" alt="Screen Shot 2020-08-13 at 1 19 37 PM" src="https://user-images.githubusercontent.com/44981951/90166290-fc26e980-dd67-11ea-9ff4-06aa4aeecf15.png">

Steps:
1. Within an existing pipeline, within the deploy stage, click 'Add Server Group'.
2. Select the ECS provider.

The popup will load in the background, and you will no longer be able to interact with the page.

**Comment by maggieneterval** [comment]
@pkandasamy91 are you looking into this? Not sure if this is a known issue with the UI nav refactor (cc @caseyhebebrand)?

**Comment by pkandasamy91** [comment]
@maggieneterval, I've started looking into it, but would love any thoughts. Raised this issue to see if others might have an idea of what the problem might be, so that we can resolve this quickly (since this would break with the next release that's being cut today?).

**Comment by caseyhebebrand** [comment]
This is not a known issue. It looks like the z-index needs to be increased. I updated `.modal` to `--layer-critical`, but this must have a different class associated.

I checked out the code. There is both a react and angular `DeployInitializer`. The react component is working, as verified in my aws test account. The ecs provider uses `deployInitializer.component.html`, which has another parent class called `modal-page`. I think this is where the z-index should be increased.

**Comment by maggieneterval** [comment]
Thank you both for the quick response! Would be great to get this resolved today since @german-muzquiz will be cutting the 1.22 release branches tomorrow and this issue feels like a blocker if ECS users would no longer be able to use the create server group modal. @pkandasamy91 would you be able to update the z-index as Casey described? (I would offer to do it but do not have access to ECS creds to test with!)

**Comment by pkandasamy91** [comment]
Sure, I can update the z-index. I'll update this issue with more info once it's been done. Thank you both! @caseyhebebrand @maggieneterval

**Comment by caseyhebebrand** [comment]
Thank you! I also do not have access to ecs, so it would be fastest for someone who does. Let me know if you need any other context!

**Comment by pkandasamy91** [comment]
I've tried updating the zindex to be z-index: var(--layer-critical) !important; to modal-page, but it looks like it's being overridden by the default z-index: 1050 defined by uib-modal. Any thoughts on how to get around this?

**Comment by caseyhebebrand** [comment]
> I've tried updating the zindex to be z-index: var(--layer-critical) !important; to modal-page, but it looks like it's being overridden by the default z-index: 1050 defined by uib-modal. Any thoughts on how to get around this?

@pkandasamy91 You can just override this parent style. Its likely the same z-index problem affects all components that use this. You can look up the classes needed to override bootstrap css, since I can't recall it off the top of my head.
