### ISSUE TITLE
Pipeline times out after spinning in "Wait for manifest to stabilize" stage for 30 mins

### ISSUE THREAD

**Issue by lsarangi1** [spinnaker/spinnaker#5972]
### Issue Summary:

Spinnaker pipeline times out after spinning in "Wait for manifest to stabilize" stage for 30 mins

### Description:

I am able to successfully create a pipeline that gets triggered on aws ECR image push and deploys it to the dev cluster (cluster that spinnaker is deployed in) using an existing manifest. However deploying to the other clusters/accounts does not succeed. Execution details show that it's waiting in the wait for manifest to stabilize stage for > 30 mins. 

### Steps to Reproduce:

Start manual execution of a pipeline configured with 2 stages.

1. Configuration - Pick up image from AWS ECR
2. Deploy (Manifest) - Deploy to cm-spin-test account using a manifest.

### Additional Details:

From cloud driver logs :

```
**2020-08-13 22:29:26.835  INFO 1 --- [0.0-7002-exec-2] c.n.s.c.k.v.c.KubernetesV2SearchProvider : Querying [securityGroups] for term help
2020-08-13 22:29:27.220  INFO 1 --- [0.0-7002-exec-2] c.n.s.c.cache.CatsSearchProvider         : Querying [securityGroups] for term: help
2020-08-13 22:29:27.221  INFO 1 --- [0.0-7002-exec-2] c.n.s.c.cache.CatsSearchProvider         : Paginating 0 results; page number: 1, items per page: 500
2020-08-13 22:29:27.308  INFO 1 --- [0.0-7002-exec-6] v.c.v.p.KubernetesV2LiveManifestProvider : Live call to lookup manifest 'help-web:deployment' in namespace 'cm' under account 'cm-spin-test'
2020-08-13 22:29:27.917  WARN 1 --- [0.0-7002-exec-6] c.n.s.c.controllers.ManifestController   : Failed to read manifest 

com.netflix.spinnaker.clouddriver.kubernetes.v2.op.handler.UnsupportedVersionException: No deployment is supported at api version apps/v1
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.handler.KubernetesDeploymentHandler.status(KubernetesDeploymentHandler.java:89) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.provider.KubernetesV2AbstractManifestProvider.buildManifest(KubernetesV2AbstractManifestProvider.java:107) ~[clouddriver-kubernetes.jar:na]
```**


![Screenshot from 2020-08-13 15-50-21](https://user-images.githubusercontent.com/59097763/90201712-88e59d80-dd90-11ea-9e53-9e2dba3de2d8.png)

**Comment by german-muzquiz** [comment]
@lsarangi1 what version of spinnaker and Kubernetes are you using? from the error it seems that support for `apps/v1` was not available in the version of spinnaker that you are running. This PR https://github.com/spinnaker/clouddriver/pull/4055 shows that it was added in Spinnaker `1.17`, if you have an older one, can you try with a newer version?

That said, waiting 30 minutes to fail the stage in these types of errors is bad user experience and we seek for a way to improving it.

**Comment by lsarangi1** [comment]
Kubernetes - 1.15+
Spinnaker - 1.16.1

I installed spinnaker using the stable helm chart (version 1.23.3) - https://hub.helm.sh/charts/stable/spinnaker/1.23.3
Using a later version of a chart gives me an error. 
```

helm install cm-spinnaker stable/spinnaker --timeout 600s --namespace spinnaker
Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```

**Comment by lsarangi1** [comment]
@german-muzquiz curious how did it deploy successfully to the default dev account ?

**Comment by german-muzquiz** [comment]
That's a good question. Is there any difference in the account definition of both environments? I see from the logs `Live call to lookup manifest`, that probably means you have `liveManifestCalls: true`. Setting it to false will make spinnaker look into the cache instead of a live call and it could go through a different route in the code.

**Comment by lsarangi1** [comment]
I see..afaik the account definitions are the same. I changed the liveManifestCalls to true while I was debugging this issue. I thought may be it's not able to get the manifest properly from the cache so a live lookup may help. What's the correct setting ?

**Comment by german-muzquiz** [comment]
`liveManifestCalls` has [known issues](https://github.com/spinnaker/spinnaker/issues/5607) and it's advisable to have it turned off, it was created as a workaround for performance problems.
It's a shame that the helm charts cannot install a newer version of spinnaker, that's the preferred way to go

**Comment by lsarangi1** [comment]
I did manage to find a workaround to install spinnaker version 1.19 and configured the pipelines again. Now it says pipeline succeeded but the new pods are not deployed. From the UI it almost seems like it waited in the force cache refresh stage for 30 seconds and did not move after that...

No obvious errors in the clouddriver logs either. Any ideas on what's missing ?

![Screenshot from 2020-08-17 09-20-20](https://user-images.githubusercontent.com/59097763/90419666-c20d5e80-e06b-11ea-8c1c-77705cd6f73e.png)

**Comment by german-muzquiz** [comment]
The execution looks fine, can you double check that everything was deployed to the right cluster and namespace? If you click `Deploy Status` there's a link to see the actual yaml that spinnaker deployed. Also at the bottom right corner of that frame there's a `Source` link that shows you the full pipeline execution context, which contains more detailed information about that execution. I don't remember how it works in older spinnaker versions, but if you don't indicate a specific `namespace` in the manifest, things get deployed to `default` namespace unless you override it in the stage configuration.

Meanwhile I'm closing this issue since the original problem about `No deployment is supported at api version apps/v1` was solved by upgrading spinnaker to a newer version.
