### ISSUE TITLE
Add AWS VPC naming requirement to getting_started guide and/or Troubleshooting guide

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#598]
Someone on the NFLX side want to grab this? There are still questions coming up in the Slack channel about it.

@cfieber @anotherchrisberry @tomaslin @ajordens

**Comment by anotherchrisberry** [comment]
I can work on this tomorrow morning.

**Comment by anotherchrisberry** [comment]
see https://github.com/spinnaker/spinnaker.github.io/pull/82
