### ISSUE TITLE
Error 500 when trying to enable nexus repository

### ISSUE THREAD

**Issue by somejavadev** [spinnaker/spinnaker#5995]
### Issue Summary:

I am running Spinnaker on GKE and I am trying to integrate nexus. When running the following command: `hal config repository nexus enable` to enable the nexus repository it returns ERROR 500, when adding debug to the command: `hal config repository nexus enable --debug` it results in `! ERROR No repository service with name "nexus" could be found`. Link to documentation for running the command: https://spinnaker.io/reference/halyard/commands/#hal-config-repository-nexus-enable. 

### Cloud Provider(s):

GKE, Kubernetes

### Environment:

hal --version: 1.38.0-20200727213212
hal config version (spinnaker): 1.21.4
ubuntu 18:04 64Bit

Update:

This also occurs with version 1.22.0 of spinnaker and version 1.39.0-20200821230018 of hal. 

### Feature Area:

Nexus, Repositories

### Description:

I would expect to be able to enable the nexus repository but I am getting an error when trying to do so.

### Steps to Reproduce:

Using the version of hal and spinnaker above, run the following command: `hal config repository nexus enable`

### Additional Details:

Debug log: [log.txt](https://github.com/spinnaker/spinnaker/files/5112501/log.txt)

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by somejavadev** [comment]
@claymccoy @christopherthielen, I see you have done some commits in the past with regards to nexus. Is it possible for you to confirm if this is an issue?

**Comment by jmalvarezf-lmes** [comment]
Hi,

The problem comes because the Repository class declares only an artifactory node and not a nexus node.

[https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Repositories.java]

From my point of view, it should be declared a field for nexus in order for halyard to work as expected:

`NexusRepository nexus = new NexusRepository();`

I'll try to patch this privately and see if it works in our environment.

Cheers!

**Comment by somejavadev** [comment]
@jmalvarezf-lmes Thank you for having a look. I had to do a whole workaround and pull the gitlab artifacts from ci cd extracting the zip and constructing special url to curl from which isn't clean and is bound to break at some point. I would also like to start contributing to spinnaker at some point but haven't had time to start going over the code to inspect the inner workings. I appreciate your efforts.

**Comment by jmalvarezf-lmes** [comment]
Hi @somejavadev,

No worries, we are also using spinnaker for deployment and we have found some issues in the past, so we are used to check into the code, and we were suffering the same issue.

This PR should fix it: https://github.com/spinnaker/halyard/pull/1787

You can also build halyard if you want to fix it in your environment, while the team checks the PR.

Hope it helps!

**Comment by jmalvarezf-lmes** [comment]
I have to say that we haven't been able to configure Nexus. It seems that it works through an api in Igor that sends an event to echo, but it seems it is not finished yet. Nexus from halyard point of view is configured, but there are other things that seems to be missing compared to Artifactory.

Regards,

**Comment by somejavadev** [comment]
@jmalvarezf-lmes thanks for the response, if I may ask, which version of spinnaker are you currently running?

**Comment by jmalvarezf-lmes** [comment]
1.21.4

**Comment by jensvdh** [comment]
Since this PR has been merged. Can this issue be closed?

**Comment by jmalvarezf-lmes** [comment]
I'd say yes but @somejavadev should confirm as he opened the issue in the first place.

**Comment by somejavadev** [comment]
Hi, thank you for everyone's assistance.
