### ISSUE TITLE
The container does not exist in the task definition

### ISSUE THREAD

**Issue by paragbhingre** [spinnaker/spinnaker#6004]
### Issue Summary:
Toggling from task definition artifact to the input in task definition introduces the issue of container does not exist in the task definition.

### Cloud Provider(s):
ECS

### Environment:
git installation

### Feature Area:
ECS Deploy stage in Pipeline

### Description:
Background - when you set the task definition artifact, you tend to set the container name for container mappings as well as for target group mappings

![task definition](https://user-images.githubusercontent.com/18301288/91369098-b0d8f600-e7bf-11ea-8b77-249db5db79d2.png)

If you change your mind and toggle back to input then you will not see the container name input box for container mappings and target group mappings. Container name in input type is not expected from the customer for the fast that container name is auto-generated. But in the background, JSON file still has the container name that you set for the task definition artifact

This causes an error "The container does not exist in the task definition"

![error](https://user-images.githubusercontent.com/18301288/91369221-1e852200-e7c0-11ea-9583-b462c210aded.png)

### Steps to Reproduce:
1. Configure task definition as an artifact.
2. Now toggle back to task definition source input and configure all the parameters to deploy the pipeline
3. The container does not exist in the task definition error occurs

### Additional Details:
Error occurs in only one specific condition which is mentioned in the steps to reproduce. It also has a workaround to avoid the error. 

Workaround - if you remove container name value for container mappings and target group mappings from the JSON then it should deploy the pipeline.

Note -  I plan to contribute a fix for this issue.

**Comment by allisaurus** [comment]
Resolved by https://github.com/spinnaker/deck/pull/8527
