### ISSUE TITLE
create Load Balancers stage fails during UpsertLoadBalancer

### ISSUE THREAD

**Issue by sdpoueme** [spinnaker/spinnaker#6013]
### Issue Summary:
A user is trying to add an additional stage to create a load balancer in a pipeline. The pipeline execution fails despite the fact that the load balancer configuration being set is correct. We are seeing this issue on 1.20.8

### Cloud Provider(s):

Kubernetes

### Environment:

OpenStack

### Feature Area:

Clouddriver

### Description:

Users are not able to create load balancers from a pipeline using the Create Load Balancers stage. The following error is returned during the stage configuration: 

    
         "responseBody": "{\"error\":\"Bad Request\",\"message\":\"No message available\",\"status\":400,\"timestamp\":1599003404458}",
          "kind": "HTTP",
          "error": "Bad Request",

### Steps to Reproduce:

1. Create a pipeline in a spinnaker
2. Add a bake stage that produces a base64 artifact
3. Add a deploy manifest stage to deploy the base64 artifact
4. Add a Create Load Balancers stage and fill the required configuration, then save the stage definition

### Additional Details:

Source data: 
```{
  "id": "01EH605D5XBRJ0CR56HXV3BPY0",
  "name": "Create Load Balancer: observability-consolidation-service-cos-anything",
  "application": "observability-consolidation-service",
  "status": "TERMINAL",
  "variables": [
    {
      "key": "serviceType",
      "value": "ClusterIP"
    },
    {
      "key": "serviceLabels",
      "value": {
        "app": "observability-consolidation-service",
        "name": "observability-consolidation-service"
      }
    },
    {
      "key": "exception",
      "value": {
        "exceptionType": "RetrofitError",
        "shouldRetry": false,
        "details": {
          "responseBody": "{\"error\":\"Bad Request\",\"message\":\"No message available\",\"status\":400,\"timestamp\":1599003080219}",
          "kind": "HTTP",
          "error": "Bad Request",
          "errors": [
            "No message available"
          ],
          "url": "http://spin-clouddriver-rw.spinnaker:7002/kubernetes/ops?clientRequestId=688664481808d60dd7d8634463fc0726218608f045597540b2d8e44ef2a6a8f4",
          "status": 400
        },
        "operation": "upsertLoadBalancer",
        "timestamp": 1599003080225
      }
    },
    {
      "key": "stack",
      "value": "cos"
    },
    {
      "key": "externalIps",
      "value": [
        
      ]
    },
    {
      "key": "sessionAffinity",
      "value": "None"
    },
    {
      "key": "availabilityZones",
      "value": {
        "canary": [
          "canary"
        ]
      }
    },
    {
      "key": "ports",
      "value": [
        {
          "protocol": "TCP",
          "port": 8080,
          "name": "http",
          "targetPort": 8080
        }
      ]
    },
    {
      "key": "provider",
      "value": "kubernetes"
    },
    {
      "key": "loadBalancerIp",
      "value": ""
    },
    {
      "key": "cloudProvider",
      "value": "kubernetes"
    },
    {
      "key": "namespace",
      "value": "canary"
    },
    {
      "key": "name",
      "value": "observability-consolidation-service-cos-anything"
    },
    {
      "key": "serviceAnnotations",
      "value": {
        "name": "observability-consolidation-service",
        "type": "kubernetes/service"
      }
    },
    {
      "key": "detail",
      "value": "anything"
    },
    {
      "key": "user",
      "value": "[REDACTED]"
    },
    {
      "key": "account",
      "value": "ocas-dev"
    },
    {
      "key": "clusterIp",
      "value": ""
    }
  ],```

---

**Comment by ezimanyi** [comment]
@sdpoueme : Thanks for reporting this!  The Kubernetes V2 provider (now the only Kubernetes provider) doesn't have a "Create Load Balancer" stage, as the way to create a load balancer would be by deploying a manifest of the appropriate type (likely a `Service`).

Do you have any more details on how the stage was created?  Were you able to create this stage in the UI?  If so that's probably where the bug is, as the back-end would not know how to actually run the stage.  Thanks!

**Comment by sdpoueme** [comment]
Hi @ezimanyi,  the stage was created from the UI.  I guess, the recommendation would be to deploy a service with a type LoadBalancer right ? There was a bit of confusion on the documentation since it references the possibility of creating load balancers but when looking at the UI we see that confusing option. The team has since started using a k8s manifest to deploy a service instead.

**Comment by ezimanyi** [comment]
@sdpoueme : Yes, exactly, the correct workflow is to use the 'Deploy (Manifest)' stage to deploy an object of the desired type (likely a `Service`).  I've make the above-linked PR to remove the `Create Load Balancers` stage from the drop-down for the Kubernetes provider, as it's just confusing to have it there when it doesn't work.  (We have a list of incompatible stages to hide from the Kubernetes provider, and it looks like we just forgot to include this stage in that list.)

**Comment by sdpoueme** [comment]
Thanks @ezimanyi !!!
