### ISSUE TITLE
Is there any dedicated docker image registry in China to replace gcr.io/spinnaker-marketplace

### ISSUE THREAD

**Issue by minkjj** [spinnaker/spinnaker#6014]
### Issue Summary:
how to pull Google's gcr.io/spinnaker-marketplace image in China Region?
Is there any dedicated docker image registry in China to replace gcr.io?

**Comment by jonsie** [comment]
There is no dedicated registry in China for these images -- the resource would have to be mirrored in China.  I assume people who do this now set the mirrors up themselves.
