### ISSUE TITLE
Clouddriver doesn't get the correct latest Helm chart version

### ISSUE THREAD

**Issue by nerddelphi** [spinnaker/spinnaker#6020]
Spinnaker is getting the latest helm chart version - semVer (when not specified) lexicographically during Bake process with `Template Artifact` https://github.com/spinnaker/clouddriver/blob/release-1.22.x/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParser.java#L107.

So based on that scenario it is getting the wrong latest version:

Eg:
`chart-1.0.9` (older) <- If I don't set the specific version, Spinnaker gets this instead the newer one 1.0.10.
`chart-1.0.10` (newer)

How can we deal with? I wouldn't lovely bumpping minor version when my patch version be in .9.

Anyway, based on RFC/SPEC (https://github.com/spinnaker/spinnaker/issues/3284) Spinnaker should be able to always get the latest one.

So, can we change it to `based on changed date` instead `versions based`? Or perhaps fix that lexical behavior to understand a semVer way (like helm binary does).

**Spinnaker version**: `1.22.1`
**Enviroment**: GKE `1.15` and `1.16`.

**Comment by german-muzquiz** [comment]
@nerddelphi thanks for investigating the issue! It seems that you already found why it's failing and where to fix it. Do you want to submit a PR for fixing the lexicographical sorting to a semver compatible one? I think that was the original intent.

**Comment by nerddelphi** [comment]
@german-muzquiz Unfortunately, I'm not Java developer :(
