### ISSUE TITLE
Fiat: Spinnaker version 1.20.8 is not available in repositories

### ISSUE THREAD

**Issue by deepakr199** [spinnaker/spinnaker#6023]
### Issue Summary:
Fiat with Spinnaker version `1.20.8` uses fiat version `1.11.0-20200428134356` which is not available on bintray as well as maven repositories

### Cloud Provider(s):
N/A

### Environment:
Spinnaker 1.20.8

### Feature Area:
N/A

### Description:
We are upgrading spinnaker to 1.20.8 and noticed Fiat is not available on bintray and maven repositories.

From `hal`, we found out spinnaker version 1.20.8 requires

```
  fiat:
    version: 1.11.0-20200428134356
    commit: c88008c3a1359c445eee8cff23184e5484e472a9
```

But this artifact is not available in the configured repository.

    jcenter()
    maven { url = uri("https://spinnaker-releases.bintray.com/jars") }

### Steps to Reproduce:
Upgrade Fiat to Spinnaker version 1.20.8

### Additional Details:

---

**Comment by jonsie** [comment]
Weird.  Looks like all of Fiat 1.11x is missing from bintray.  @plumpy @ezimanyi This is going to block 1.20.8 updates - should we move forward to 1.20.9 and publish a new Fiat artifact?  I wonder what happened here.

**Comment by ezimanyi** [comment]
I noticed this when I was running the `Admin_AuditBoms` job.  I'm not sure how these were deleted; my best guess is that someone trying to fix a "409 conflict" during the build process accidentally deleted the wrong artifact.

I think that publishing a 1.20.9 is probably the right way forward here.

**Comment by evansb** [comment]
Hmmm should the last release manager do that? cc: @german-muzquiz

**Comment by german-muzquiz** [comment]
I'll do a release for `1.20.9` so that fiat artifacts are published.

**Comment by german-muzquiz** [comment]
It's not possible to do a `1.20.9` release because it seems that the publish job searches for the previous version artifacts, since they are not found, it tries to do again a release for `1.20.8` and fails because it already exists. Seeking help from @plumpy on regenerating fiat artifacts

**Comment by plumpy** [comment]
Okay, I rebuilt the jars. Just FYI, the debian packages were there, so this seemingly only affects people who are trying to build on top of the fiat jars. I actually didn't really realize people were using these jars, so I guess that's good to know.

Here, for posterity, is what I did:
```
$ wget https://storage.googleapis.com/halconfig/bom/1.20.8.yml -O - -q | grep -A 2 fiat 
  "fiat":
    commit: "c88008c3a1359c445eee8cff23184e5484e472a9"
    version: "1.11.0-20200428134356"
$ cd dev/spinnaker/fiat
$ git checkout c88008c3a1359c445eee8cff23184e5484e472a9
$ gcloud builds submit . \
    --config ../buildtool/dev/buildtool/cloudbuild/debs.yml \
    --project spinnaker-community \
    --account plumpy@google.com \
    --substitutions  '_IMAGE_NAME=fiat,_BRANCH_NAME=release-1.20.x,_VERSION=1.11.0,_BUILD_NUMBER=20200428134356'
```
