### ISSUE TITLE
ECS Task Definition Cache Slow To Populate

### ISSUE THREAD

**Issue by deverton** [spinnaker/spinnaker#6063]
### Issue Summary:

The Clouddriver cache for ECS task definitions takes a very long time to populate with a large number of task definitions.

### Cloud Provider(s):

AWS ECS

### Description:

We have close to 10,000 ECS task definitions in some AWS accounts. While this is something we're looking to tidy up, it does make the ECS clouddriver cache unusable for a while. The problem is that the API to describe task definitions doesn't allow for a list to be queried so clouddriver has to query each individual task definition which takes a while.

I'm not sure there's much that can be done from the Spinnaker side unless AWS extends the API. One thought is maybe adding a relationship from the Service cache item to TaskDefinition so at least the cache would be populated with task definitions actually being used by running services.

**Comment by piradeepk** [comment]
@deverton task definition caching improvements were made and released as part of Spinnaker v1.24.0. Would you be able to use the latest version and let us know if this is still an issue?

**Comment by piradeepk** [comment]
Closing this issue as 1.24.0 has been released. @deverton please reopen if you find this issue hasn't improved the experience with the latest release.

**Comment by deverton** [comment]
Sorry, been on leave recently. The change from @allisaurus vastly improved the cache start up. Nice work.

Here's the output from one of our accounts from Spinnaker 1.23 (yes it really took 46 minutes to fetch all the task definitions).

```
13:03:08.400 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Caching 90 services in ecs-test/us-west-2/ServiceCachingAgent
13:03:08.401 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Caching 3 ECS clusters in ecs-test/us-west-2/ServiceCachingAgent
13:03:08.420 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Evicting 1 services in ecs-test/us-west-2/ServiceCachingAgent
...
13:49:44.084 [AgentExecutionAction-3] INFO  c.n.s.c.e.p.a.TaskDefinitionCachingAgent - Caching 10650 task definitions in ecs-test/us-west-2/TaskDefinitionCachingAgent
13:49:44.108 [AgentExecutionAction-3] INFO  c.n.s.c.e.p.a.TaskDefinitionCachingAgent - Evicting 1 taskdefinitions in ecs-test/us-west-2/TaskDefinitionCachingAgent
```

Same account, but now on 1.24

```
12:47:20.341 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Caching 90 services in ecs-test/us-west-2/ServiceCachingAgent
12:47:20.341 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Caching 3 ECS clusters in ecs-test/us-west-2/ServiceCachingAgent
12:47:20.348 [AgentExecutionAction-11] INFO  c.n.s.c.e.p.a.ServiceCachingAgent - Evicting 1 services in ecs-test/us-west-2/ServiceCachingAgent
...
12:48:34.644 [AgentExecutionAction-1] INFO  c.n.s.c.e.p.a.TaskDefinitionCachingAgent - Described 0 new task definitions (89 already cached)
12:48:34.645 [AgentExecutionAction-1] INFO  c.n.s.c.e.p.a.TaskDefinitionCachingAgent - Caching 89 task definitions in ecs-test/us-west-2/TaskDefinitionCachingAgent
12:48:34.847 [AgentExecutionAction-1] INFO  c.n.s.c.e.p.a.TaskDefinitionCachingAgent - Evicting 1 taskdefinitions in ecs-test/us-west-2/TaskDefinitionCachingAgent
```
