### ISSUE TITLE
gitlab or git as pipeline trigger

### ISSUE THREAD

**Issue by rizi82** [spinnaker/spinnaker#6066]
### Issue Summary:
Is it possible to use gitlab (or any git) as pipeline trigger without using a webbhook on gitlab side. I want spinnaker to detect change instead of gitlab triggering it with webhook option

**Comment by robzienert** [comment]
There is a git trigger for pipelines, yes.

![Screen Shot 2020-09-23 at 1 00 32 PM](https://user-images.githubusercontent.com/108741/94063380-dcd69f80-fd9c-11ea-97a7-b7219e29af3b.png)

**Comment by ajordens** [comment]
This is not supported out of the box but it should be possible to build this integration. We would welcome a contribution.

**Comment by gal-yardeni** [comment]
As per Adam's response above, I'm going to close this issue for now. @rizi82, we would appreciate seeing a GitLab support if you are interested in contributing! feel free to reach out on slack[ #sig-ci].(https://spinnakerteam.slack.com/archives/CQJP8H05P)
