### ISSUE TITLE
question - can this tool be leveraged to perform gradual rollouts/upgrades to client machines for desktop applications

### ISSUE THREAD

**Issue by avnerbarr** [spinnaker/spinnaker#6068]
### Issue Summary:
I am distributing client software through a homegrown mechanism. I'd like to be able to use a "canary" style model to provide upgrades to clients once new versions become available.
I see that this tool is geared towards cloud applications but the underlying mechanism is a good fit for client distribution as well.
Is this tool able to handle client type upgrades?

**Comment by ajordens** [comment]
Best to reach out to the community on [Slack](http://join.spinnaker.io/).

In reality, almost any style of deployment is possible to orchestrate but may require some custom integration.
