### ISSUE TITLE
K8s podAnnotations - Parsing Anti-Affinity doesn't work

### ISSUE THREAD

**Issue by aservera** [spinnaker/spinnaker#6075]
### Issue Summary:
When I try to apply pod antiaffinity configuration using Pod Annotations in a Replica Set it doesn't be applied
The purpose is to ensure that any new pod created is deployed in a different node than the existing ones.

### Cloud Provider(s):
Azure AKS

### Environment:
Any

### Feature Area:
Replica Set

### Description:
I want to ensure that every pod of an application is deployed in a different node. For that I have tested to use https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/ 

### Steps to Reproduce:
Go to Pod Annotations and add the next Key:
scheduler.alpha.kubernetes.io/affinity
Then at value field set:
scheduler.alpha.kubernetes.io/affinity: '["podAntiAffinity": { "requiredDuringSchedulingIgnoredDuringExecution": { "labelSelector": [ { "matchExpressions": [ { "key": "app", "operator":         "In", "values": [ "waglobsbujavaboilerplt" ] } ] } ] }]'
### Additional Details:
If I modifed out of Spinnaker, using affinity section it works fine. I have tried different kind of combinations with no luck

/sig autoscaling

**Comment by aservera** [comment]
Hi, I just got a response from K8s guys related to this point which makes me a little bit lost if I am following the right steps.
https://github.com/kubernetes/kubernetes/issues/95107
Thanks in advance

**Comment by kskewes** [comment]
Yes, per your link the anti-affinity rules go in the pod `spec:`. :-)

We define anti-affinity rules in our yaml files and Spinnaker deploys them correctly.

**Comment by aservera** [comment]
Thanks @kskewes for your response, maybe I should have included the next link [https://github.com/spinnaker/spinnaker/issues/1420](url) 
If I understand correctly you mean to use manifest files instead of UI. My question was about the UI options, so is that possible?

**Comment by ezimanyi** [comment]
@aservera : The UI options for configuring a deployment are only available in the  [now-deprecated](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md) V1 version of the Kubernetes provider.  (The [last version of Spinnaker](https://spinnaker.io/community/releases/versions/1-20-0-changelog#final-release-with-the-kubernetes-v1-provider) to contain support for the V1 provider is 1.20 and it is no longer supported/maintained.)

The V2 version of the provider only supports deploying a manifest, so the solution above by @kskewes should work.  (The issue you linked #1420 notes that the reporter there waited for the V2 provider a solution to the problem.). Thanks!
