### ISSUE TITLE
How to create Daemonsets with Spinnaker

### ISSUE THREAD

**Issue by aservera** [spinnaker/spinnaker#6078]
### Issue Summary:
I would like to create a Daemonset however I can't find the way, even documentation about how to do it, or if it is possible to do it.

### Cloud Provider(s):
Azure AKS

### Environment:
All

### Feature Area:
Scheduling

### Description:
I would like to create a Daemonset however I can't find the way, even documentation about how to do it, or if it is possible to do it.

**Comment by ajordens** [comment]
This is probably a question best answered via Slack, feel free to [join us there](http://join.spinnaker.io/).

**Comment by maggieneterval** [comment]
Hi @aservera! If you are using the [legacy](https://spinnaker.io/setup/install/providers/kubernetes/) (v1) Kubernetes provider (which was removed in Spinnaker 1.21) I'm not sure DaemonSets were ever supported, but Spinnaker's [standard](https://spinnaker.io/setup/install/providers/kubernetes-v2/) (v2) Kubernetes provider accepts any Kubernetes resource YAML as input, so you should definitely be able to apply a DaemonSet using the [Deploy (Manifest)](https://spinnaker.io/guides/user/kubernetes-v2/deploy-manifest/) stage.

As @ajordens mentioned, please feel free to join the #kubernetes or #sig-kubernetes [Spinnaker Slack](join.spinnaker.io) channels with any additional questions. Thanks!
