### ISSUE TITLE
Problems in Global: ! ERROR Unexpected exception:

### ISSUE THREAD

**Issue by MeghaTek** [spinnaker/spinnaker#6080]
issue faming in GLobal while performing "hal deploy apply" for spinnaker

+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception:
  io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET
  at:
  https://kubernetes.default/apis/extensions/v1beta1/namespaces/spinnaker/replicasets.
  Message: the server could not find the requested resource. Received status:
  Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null,
  kind=null, name=null, retryAfterSeconds=null, uid=null,
  additionalProperties={}), kind=Status, message=the server could not find the
  requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null,
  additionalProperties={}), reason=NotFound, status=Failure,
  additionalProperties={}).

 

- Failed to deploy Spinnaker.

**Comment by ajordens** [comment]
This is probably a question best answered via Slack, feel free to [join us there](http://join.spinnaker.io/).
