### ISSUE TITLE
Pipeline triggered by cron has concurrent executions even if concurrency is disabled

### ISSUE THREAD

**Issue by sdpoueme** [spinnaker/spinnaker#6081]
### Issue Summary:

A pipeline is triggered by a cron job and is running two concurrent executions. 

### Cloud Provider(s):

Kubernetes v1.17

### Environment:

I am running Spinnaker on SAP Gardener in GCP. 

### Feature Area:

Orca

### Description:

A cron schedule triggers a pipeline at 10:00 Mon-Fri, when the trigger runs the pipeline is executed twice instead of once. Even if the flag to disable concurrent executions is set to true.
This issue has been referenced in #1070 and #2310 as well. 

### Steps to Reproduce:

1. Create a pipeline in spinnaker
2. Disable concurrent pipeline executions
![image](https://user-images.githubusercontent.com/10876571/94579642-0da85000-0247-11eb-9735-d0fe42580e7b.png)

2. Set an automated trigger with a weekly cron schedule. 
![image](https://user-images.githubusercontent.com/10876571/94579580-fb2e1680-0246-11eb-8710-61b9fb7172aa.png)
3. Wait for the trigger to execute

### Additional Details:

Despite the settings we are seeing concurrent executions happening:
![image](https://user-images.githubusercontent.com/10876571/94579831-3892a400-0247-11eb-9b7d-7773fa5e70bb.png)

**Comment by ajordens** [comment]
Couple quick questions:
* Is it double triggering the same cron event?
* Are you running SQL for orca and/or echo?

**Comment by sdpoueme** [comment]
Hi @ajordens yes it is double triggering the same cron event, ant we are not running SQL. We are still using redis, but a managed redis on GCP. 
Something I should mention is that I have recently scaled echo, orca and front 50 to 2 replicas each. Could this be related ?

**Comment by sdpoueme** [comment]
Hi @ajordens I noticed this note in the custom sizing guide on spinnaker.io
`Important: To avoid duplicate triggering, echo and igor must each be deployed with exactly one pod.`
I guess that is the reason why we are seeing the issue. I did some changes yesterday and the error is not visible anymore. I do have a question however, how can we achieve a better resilience for echo if we can not run ore than one pod on a cluster ?

**Comment by ajordens** [comment]
The SQL support for `echo` correctly locks and allows for multiple instances. Instead of that, you can run a single scheduler and multiple non-scheduled instances of `echo.`

The `scheduler.enabled` config attribute controls whether the scheduler is enabled (valid values: true/false).

At Netflix, we're running SQL and have split scheduler instances from event processing instances to spread the load better and improve operational visibility (i.e., we can spot issues that affect only the scheduler, etc.).
