### ISSUE TITLE
Kubernetes clusters not appearing on Infrastructure page

### ISSUE THREAD

**Issue by linjmeyer** [spinnaker/spinnaker#6110]
### Issue Summary:

Kubernetes cluster/accounts periodically missing from infrastructure page

### Cloud Provider(s):
Kubernetes v2

### Environment:
GKE/Kubernetes (Installed using Halyard)

### Feature Area:
Infrastructure

### Description:
Anywhere from 1-3 of our kubernetes clusters are not appearing in the Infrastructure UI page for all applications.  It seems to change over time, sometimes we can see cluster 1 but not 2 and 3, other times it is 1 and 2 but not 3, etc.  It is consistent between applications, meaning if application 1 only shows cluster 2, other applications will have the same issue.  Pipelines are unaffected and are succeeding, but results of the pipeline are not correctly reflected in the Infra UI.  This issue started when upgrading to v1.22.1.

Restarting cloud driver temporarily fixes this issue, but we are seeing it reoccur within around 20-30 minutes.  There are no errors in the UI console and when getting server groups via Gate/Swagger the response is missing clusters.

### Steps to Reproduce:

Best guess:
* Install Spinnaker v1.22.1 via Halyard in a Kubernetes cluster
* Cloud Driver should use default in memory caching
* Add several kubernetes accounts and pipelines
* Observe if Infra page contains all clusters

### Additional Details:

* Originally reported on [Slack](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1602512544329900) and it seems to be affecting other users as well.
* I have not found any errors in Cloud Driver logs to explain the issue

---

**Comment by linjmeyer** [comment]
An observation I've made, in our clouddriver logs we have log lines like:
* cluster1/KubernetesCoreCachingAgent[1/1]
* cluster1/KubernetesUnregisteredCustomResourceCachingAgent[1/1]

It seems when the KubernetesCoreCachingAgent is running, KubernetesUnregisteredCustomResourceCachingAgent is not and vice versa.  Around 20 minutes after cluster1/KubernetesUnregisteredCustomResourceCachingAgent starts, we stop seeing cluster1 in the UI.  It shows up again once cluster1/KubernetesCoreCachingAgent kicks on again.

**Comment by linjmeyer** [comment]
A workaround for anyone else experiencing this, scaling clouddriver horizontally has helped the issue.  We are only seeing short blips of missing clusters.  We are monitoring the clouddriver APIs with a cronjob and are seeing the issue significantly less with 2 clouddrivers vs. 1 clouddriver.

**Comment by ezimanyi** [comment]
@linjmeyer : Thanks for opening this!  It looks to be similar to #5611 which ended up being a scaling issue, with a lot of scaling ideas on that issue.  Longer-term we are working to reduce the resource usage of clouddriver so it does not take as many resources (tracked in issues such as #5905).

**Comment by linjmeyer** [comment]
@ezimanyi cool thanks, that thread has lots of good ideas for us to try
