### ISSUE TITLE
Spinnaker pipeline Base(manifest) stage Hot to use private variable???

### ISSUE THREAD

**Issue by herozabbix** [spinnaker/spinnaker#6130]
### Issue Summary:
# I want to use private variable with Base(manifest) stage，How should i do ?

![image](https://user-images.githubusercontent.com/56722758/97006701-d17cbc80-1572-11eb-8052-184b5334bb0e.png)

**Comment by ezimanyi** [comment]
Thanks for opening this issue!  This is actually a general problem not specific to the bake manifest stage---there is not (to my knowledge) a great workflow for how to include secrets as parameters in a pipeline.  Issue #2787 is tracking that general issue and assigned to `sig/security` but as noted there is not being actively worked on.

You may find some help asking in the Slack channel about any workarounds or workflows other users have found for this.  Sorry that we don't have a great solution for this at this point!
