### ISSUE TITLE
Allow Jenkins in Igor without polling (only launching jobs from Spinnaker)

### ISSUE THREAD

**Issue by julienduchesne** [spinnaker/spinnaker#6143]
### Issue Summary:
Setting jenkins.enabled to false disables polling but it also disables using jenkins jobs in pipelines

### Cloud Provider(s):
Igor

### Environment:
Probably any. Using standard images 1.23.0 in EKS

### Feature Area:
Jenkins

### Description:
It seems like the only way to enable Jenkins jobs is to also enable polling. When I set jenkins.enabled to false, I cannot use Jenkins jobs

It would be nice to have an attribute in each jenkins item to disable polling
```
          - name: ${jenkins.name}
            permissions: {}
            address: ${jenkins.url}
            username: ${jenkins.username}
            password: ${jenkins.password}
            poll: true|false
```
Would that be an OK solution? If it is, I can open a PR

**Comment by julienduchesne** [comment]
Alright, I found a setting that helped me in the code: https://github.com/spinnaker/igor/pull/898
For future users

**Comment by gal-yardeni** [comment]
@julienduchesne I've approved your PR!
