### ISSUE TITLE
Added new cluster to existing Spinnaker and reinstalled to see new error "Please check connectivity and access permissions to the cluster"

### ISSUE THREAD

**Issue by arafatmohammed** [spinnaker/spinnaker#6145]
### Issue Summary:

Added a new cluster to Spinnaker and seeing this error:
```
deployKubernetesManifest.deployKubernetesManifest.configMap.Error reading kind [configMap]. Please check connectivity and access permissions to the cluster
```

### Cloud Provider(s):
AWS EKS 1.15

### Environment:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### Description:
Added new cluster by adding to spinnaker-kubeconfig secret:
```
$ kubectl create secret generic --from-file=./spinnaker-kubeconfig.yaml spinnaker-kubeconfig -n spinnaker
```

### Additional Details:
```
halyard:
  spinnakerVersion: 1.17.1
  image:
    repository: gcr.io/spinnaker-marketplace/halyard
    tag: 1.29.0
```

### Other Errors seen CloudDriver Logs:
```
2020-10-31 03:17:27.342 ERROR 1 --- [     Thread-626] c.n.s.c.k.v.s.KubernetesV2Credentials    : Could not list namespaces for account bravo: Failed to read [namespace] from : Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

**Comment by maggieneterval** [comment]
Hi @arafatmohammed! This sounds like it may be a configuration or permissions issue. I'd recommend asking for help in the [Spinnaker Slack](http://join.spinnaker.io/) #sig-kubernetes channel, or attending a [Spinnaker Kubernetes SIG](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md) if you'd prefer to chat live with other Spinnaker operators/developers about this. Thanks!

**Comment by snorlaX-sleeps** [comment]
Adding a note for future visitors - if you are running your Spinnaker installation in K8s, configmaps / secrets are not updated automatically on a Clouddriver pod, even if you restart the pod
Halyard creates a unique copy of the current file, which is what is attached to Clouddriver.

To pick up changes you must:
- Update the kubeconfig secret file
- restart / rollout redeploy halyard
- run `hal deploy apply` to update clouddriver
