### ISSUE TITLE
Should Kayenta issues be filed here?

### ISSUE THREAD

**Issue by tillig** [spinnaker/spinnaker#6184]
### Issue Summary:

There are several issues [in the Kayenta repo](https://github.com/spinnaker/kayenta/issues) but it doesn't appear they get any sort of traction or discussion. I noticed in other Spinnaker repos that the issues lists have been turned off in favor of filing all issues in this main Spinnaker repo.

Should Kayenta issues be filed here instead?

If so, should the Kayenta issues list be turned off to avoid misleading folks?

Thanks for any help you can provide.

**Comment by robzienert** [comment]
Looking into this.

**Comment by robzienert** [comment]
@tillig Hello, I've shutdown the issues on `spinnaker/kayenta`. Issues should be placed here, along with all other issues related to Spinnaker. Thanks for bringing this to our attention - I wasn't aware that the project had been misconfigured.
