### ISSUE TITLE
Keel build failure 

### ISSUE THREAD

**Issue by saimadineni** [spinnaker/spinnaker#6186]
### Issue Summary:
Keel's gradle build on the master branch is failing because of change that was introduced in the latest commit.

### Cloud Provider(s):
N/A. The failure is on the gradle build of the microservice.

### Environment:
local. I'm trying to build the microservice from the source code on my local

### Description:
When I run ./gradlew build on keel repository, I get
: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spinnaker.baseUrl' in value "${spinnaker.baseUrl}
This was a newly introduced the value which doesn't exist in keel.yml or spinnaker.yml. 
I was able to resolve the issue by replacing  "${spinnaker.baseUrl} with ${gate.baseUrl}

### Steps to Reproduce:
Clone the keel repository and run ./gradlew from the root of the repository

### Additional Details:
N/A

**Comment by robzienert** [comment]
Looks like there was a failing master commit 2 days ago. The latest few commits have been passing, please update to the latest. Reopen if the issue persists.

**Comment by saimadineni** [comment]
So, this https://github.com/spinnaker/keel/blob/master/keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt#L30 is from the latest master branch. And, the spinnaker baseURL is a new entry. I believe the intention was to point to gate but somehow  "${spinnaker.baseUrl} was added.
