### ISSUE TITLE
Propose changes to spinnaker.io documentation site / organization

### ISSUE THREAD

**Issue by rbuskens** [spinnaker/spinnaker#619]
Have been thinking about the spinnaker.io site a bunch, and wanted to get folks' thoughts about it. I have three issues with the site in its current form:
* There's no search box.
* The Quick Reference section seems inappropriately named, and the content under it feels disconnected with anything.
* I anticipate that the number of docs under Guides will continue to increase over time, such that a pulldown menu may not be the best organization.

In response to the above, I'd like to propose that we make a few changes to the site:
* Add a search box/bar. Search will return all relevant items available at the docs site (i.e., will not be scoped to a specific menu).
* Instead of having pulldown menus, have one top-level navigation menu. When folks click on a top-level item, a sidebar (e.g., on the left side) containing the expanded menu for that top-level item appears.
* Move the current Quick Reference material under a more appropriate (set of) heading(s) under Guides, maybe under 'Reference material' or some such thing. Here, it seems like it would be worthwhile to also provide links to various cloud provider web site (AWS, Google, Pivotal, Microsoft, etc.).
* Rename 'Guides' to 'Docs' or 'Documentation'.

In addition, I think we should add:
* A blog menu item (though maybe we can add this only after we've added our first blog item).
* A menu item under which we place interesting news items, announcements, media events, etc.

Thoughts?

**Comment by rbuskens** [comment]
@spinnaker/reviewers

**Comment by tomaslin** [comment]
is there a simple implementation to power the search box that you're talking about?

**Comment by tomaslin** [comment]
I am a fan of the tensorflow style view for subsections. Is this what you mean by removing the quicknav? http://www.tensorflow.org/tutorials/index.html

**Comment by rbuskens** [comment]
Re: the search box. I don't know the answer to your question...yet.
Re: tensorflow style view for subsections vs quicknav: yes, this is exactly the kind of thing I'm thinking of.

**Comment by tomaslin** [comment]
This might be controversial but I think the quick reference section should be inlined with the content that it is relevant to. Move the current content into installation guide

**Comment by rbuskens** [comment]
I agree with your comments about the quick ref section.

Please LGTM if/when you're good with the proposed changes, and I'll figure out how to make them.

**Comment by tomaslin** [comment]
LGTM . Go for it!

**Comment by tomaslin** [comment]
@rbuskens site search seems like a good solution for the search issue - https://cse.google.com/cse/sitesearch/create

**Comment by rbuskens** [comment]
This will be perfect, thanks! I'll work to get search added before the end of the year.

**Comment by tomaslin** [comment]
latest consensus is to change to use readme.io. I'm going to close this issue as most ideas have been done ( specially search )
