### ISSUE TITLE
Email Notification is not working 

### ISSUE THREAD

**Issue by daparthi001** [spinnaker/spinnaker#6196]
Added the config echo.yaml to the service-settings path .
/home/jenkins/.hal/default/service-settings

But still the email notification is not working ?

**Comment by ajordens** [comment]
Your best bet is to follow up on Slack and/or review the documentation on spinnaker.io.

There isn't enough in this issue report to diagnose.

**Comment by daparthi001** [comment]
/home/jenkins/.hal# hal deploy apply
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "mail" (class com.netflix.spinnaker.halyard.config.model.v1.node.Notifications),
  not marked as ignorable (3 known properties: "slack", "twilio",
  "github-status"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["notifications"]->com.netflix.spinnaker.halyard.config.model.v1.node.Notifications["mail"])

- Failed to get deployment name.
