### ISSUE TITLE
Enable HTTPS on Azure Storage for Kayenta

### ISSUE THREAD

**Issue by tillig** [spinnaker/spinnaker#6205]
### Issue Summary:

Kayenta has support for storing objects and metrics in Azure Storage but [it's hardcoded to HTTP](https://github.com/spinnaker/kayenta/blob/7345b5a2615873bec6954d90a3ab4e0149e8c5f7/kayenta-azure/src/main/java/com/netflix/kayenta/azure/security/AzureCredentials.java#L44). By default Azure Storage is deployed with HTTPS and it takes extra work to make it HTTP-enabled... which is also less secure.

Can we make this HTTPS? It seems like a simple one-char PR I'd be happy to throw in if that's OK.

### Cloud Provider(s):

Azure

### Environment:

Standalone Kayenta (but any use of Kayenta is affected)

### Feature Area:

Canary, component/kayenta

**Comment by man0s** [comment]
I have opened for this issue the following PR: spinnaker/kayenta#827.

**Comment by AlexChesser** [comment]
It looks like the merge has been completed. Can this be closed? 

@cfieber, @tillig

**Comment by tillig** [comment]
I think so. It hasn't made it into the armory container yet that I've seen but I guess that's more a release problem.
