### ISSUE TITLE
Destroying old ECS server-group always first enables it

### ISSUE THREAD

**Issue by lifeofguenter** [spinnaker/spinnaker#6222]
When destroying a disabled ECS server-group, spinnaker will first enable the cluster before destroying it:

<img width="1046" alt="Screen Shot 2020-12-10 at 10 31 59" src="https://user-images.githubusercontent.com/241073/101753723-411f1a80-3ad3-11eb-9b24-3a79316cc6ea.png">

<img width="1382" alt="Screen Shot 2020-12-10 at 10 32 16" src="https://user-images.githubusercontent.com/241073/101753745-49775580-3ad3-11eb-8aae-fe77d1882841.png">

This causes a bit of an issue, especially if clouddriver is taking a bit time before sending out the "destroy" command.

I don't see this happening with `highlander` but mostly with `redblack` strategies.

**Comment by allisaurus** [comment]
`Cause: minimum capacity was set to 5` ugh, that's annoying. This value perhaps needs to be better handled during a destroy operation.
