### ISSUE TITLE
When stopping and starting a k8s cluster where spinnaker is installed on all docker pipelines kick off.

### ISSUE THREAD

**Issue by somejavadev** [spinnaker/spinnaker#6258]
### Issue Summary:

We currently "park" some of our Google Kubernetes Engine environments when not in use. We do this by scaling down all nodes to 0 and then scale them back up when we need them. Our spinnaker installation is done via hal on GKE and what we have noticed is that when we scale the cluster down to 0 and then back up all our docker triggered pipelines kick off with various old images triggering the pipelines.

### Cloud Provider(s):

Google Kubernetes Engine  
Google Container Registry  

### Environment:

I am running spinnaker deployed to GKE via hal. Pipelines are triggered via changes to docker images stored in Google Container Registry. Pipelines are configured via pipeline templates and deploy images via k8s manifest to GKE.

Versions:
hal: 1.40.0-20201028133206
spinnaker: 1.24.1 also occurs on 1.23.1

### Feature Area:

Docker pipelines, I believe this might have to do to how igor detects changes in the container registry.

### Description:

The docker triggered pipelines does not kick off automatically when doing a `hal deploy apply`. I would expect that scaling down the k8s cluster and scaling it back up wouldn't trigger changes in the docker registry images. 

### Steps to Reproduce:

Deploy spinnaker via hal to a GKE cluster. Set up a pipeline that get's triggered via a docker images changes (images stored in GCR). Scale down the cluster to 0 nodes, scale the cluster nodes back up and the docker triggered pipeline kicks off.

### Additional Details:

---

**Comment by kskewes** [comment]
Bingo.
By default Halyard provisions a redis pod with no pvc to get Spinnaker up and running.
Igor and others use this for persistence, so when pod scales down the image cache is lost as you surmised.
Recommend using an external redis or adding a pv for it at least.

See the below doc and others in category: https://www.spinnaker.io/setup/productionize/caching/externalize-redis/

**Comment by somejavadev** [comment]
@kskewes, thanks we don't have a dedicated redis cluster at the moment so I might end up adding a PVC for the redis instance until we have one setup. Unfortunately from what I can see is that halyard doesn't support adding PVC via the `service-settings.yml`  link: https://spinnaker.io/reference/halyard/custom/#using-custom-volumes, have you perhaps done so yourself and if so which route did you take?

**Comment by kskewes** [comment]
Sounds good :)

We use raw yaml and I don't know how to do it with Halyard.

**Comment by somejavadev** [comment]
@kskewes Thanks, I have logged a ticket since I think it could be useful for others as well. Otherwise I will create a basic redis cluster in the interim. If I am gonna manually edit the yml I will have to re-apply the change every time we update spinnaker which is not ideal.
