### ISSUE TITLE
[Azure-Spinnaker] VM/VMSS deploys default to UTC timezone

### ISSUE THREAD

**Issue by bm7150** [spinnaker/spinnaker#6313]
### Issue Summary: 

When a VMSS is deploy through Spinnaker, the timezone defaults to UTC regardless of original image timezone setting.

### Cloud Provider(s): 

Azure

### Feature Area: 

Clouddriver (Azure)

### Description:

When deploying an image through spinnaker, there is no way of specifying a time zone that the newly created machine will use. This causes all machines deployed to use UTC since it is the default value. Would like to be able to pass a variable into the deployment pipeline that can be utilized to specify a timezone id for the deployment. The arm template provides a parameter for timezone at `VirtualMachineProfile`.`osProfile`.`WindowsConfiguration`.`timeZone`: https://docs.microsoft.com/en-ie/azure/templates/microsoft.compute/virtualmachinescalesets#windowsconfiguration-object

### Steps to reproduce:

Deploy a new Windows machine through spinnaker, log in and view that timezone is set to UTC regardless of original images timezone.

**Comment by EasyAsABC123** [comment]
@spinnakerbot add-label sig/azure

**Comment by Asha-Hiremath** [comment]
Deploy a new Windows machine through ARM template, log in and view that timezone is set to UTC regardless of original images timezone.

Is there any solution for this?
