### ISSUE TITLE
Fiat Role Sync Slow and Requires High Memory

### ISSUE THREAD

**Issue by deverton** [spinnaker/spinnaker#6319]
### Issue Summary:

We're finding that the role sync process in `fiat` is very slow with the number of users, roles, and applications we have. This makes it problematic to use automated triggers with managed service accounts as that triggers the sync process and eventually times out.

The roles come from Okta SAML setup as the external role provider in `fiat`. We have about 500 active users and roughly 600 applications with on average one pipeline each. Some users have more than 500 roles coming via the SAML assertion.

The `fiat` JVM is configured with 4 vCPUs and 24 GB of heap with two replicas. They talk to a dedicated `cache.m6g.4xlarge` Elasticache instance. The metrics from Elasticache are pretty happy with engine CPU utilization typically under 25% and the item count around about 17,500.

I've been profiling the sync process locally with a snapshot of our production Elasticache instance with the results below. It roughly matches what we see in production where about a third of the time is spent reading from Redis, a third is spent parsing the data in to the in-memory model, and third updating the permissions.

![image](https://user-images.githubusercontent.com/287143/106237840-61559500-624b-11eb-9566-85377da14443.png)

Related issue would be https://github.com/spinnaker/spinnaker/issues/6179 which would help with the pipeline creation but ideally sync would be faster.

**Comment by deverton** [comment]
Here's a flame graph from async-profiler including the sync process and some prod traffic over 15 minutes.
[fiat-flamegraph.zip](https://github.com/spinnaker/spinnaker/files/5908361/fiat-flamegraph.zip)

**Comment by deverton** [comment]
I think we've tracked this down to write amplification due to how we've migrated application permissions from our in-house pipeline tool to Spinnaker. The basics of it are that the majority of applications in our setup are accessible by being part of one security group. Each application has at least one pipeline and we've got pipeline permissions enabled for automated triggers.

What seems to be happening is each pipeline's service account has access to every other pipeline's service account (since they run under the same role) so any updates to one pipeline account affect every other one. User accounts also get updated since they have access to the service accounts, though that's not so bad.

You can see this reflected in the profiling screenshot I initially posted where around 800 pipelines ended up generating 3.5 million invocations of `ServiceAccount.setMemberOf()`.

One solution for this would be to stop using pipeline permissions and go back to manual service account creation. However the convenience of the pipeline permission setup is pretty high.

**Comment by deverton** [comment]
A possible solution would be to allow a change in the way service accounts are provisioned when using pipeline permissions. Instead of creating one unique account per-pipeline, instead we would use the set of roles to derive the account name. Something simple like concatenating the (lowered, sorted, uniqued) set of roles, taking the sha256 of the value, and then creating a service account with that name. As the accounts are just normal service accounts, they behave as before with any application or account restriction.

That way we preserve the ability to allow users to select the required permissions while keeping the number of distinct service accounts (in our use case) low.

**Comment by KeisukeYamashita** [comment]
Nice idea.

However, I think we need to take care of the scalability issue. In our organization, with nearly 1,800 in the pipeline(=service accounts), we had a problem as described in the issue https://github.com/spinnaker/spinnaker/issues/6179. I'm worried that a similar problem will occur.

We are using GitHub Team as our role provider, and there are nearly 1,100 teams at the moment and given the number of possible combinations, there are 2 to the power of 1,100. So in the worst case scenario, I suspect we'll have scalability issues again.

**Comment by deverton** [comment]
@KeisukeYamashita true, the combinations expand pretty quickly so this is more of a workaround if your role set isn't too diverse for across a large number of triggers. 

I think I've found another way to at least reduce the cost of the sync in spinnaker/fiat#380 and have a couple more ideas to try improve the performance of real time calls as well.

**Comment by deverton** [comment]
Well, we just rolled out the approach I mentioned using the hash of the roles to generate service account IDs. We've gone from 4000+ service accounts to around 20. Obviously something a bit off with our setup, but it's pretty much fixed our performance issues with `fiat` with sync times back under 1 second instead of 5+ minutes.

**Comment by deverton** [comment]
Well, sync times have crept up again to about 15 seconds but I think I know why. We have somewhere over 100,000+ security groups that are gradually getting synced in to `fiat` as users login. 99.9% of those groups are unused by Spinnaker but we currently don't have a naming convention that would allow for easy filtering.
