### ISSUE TITLE
How to setup a spinnaker instance using AWS Federated login

### ISSUE THREAD

**Issue by kishorchintal** [spinnaker/spinnaker#632]
Hi,

I have been trying to setup spinnaker in AWS with my Federated login. I do not have the privileges to create VPCs/roles etc. I would like to know how to do the setup in this case and what are the changes I need to make. 

Also, I would like to know how to use the actual IP of the EC2 instance instead of port forwarding. I tried making changes suggested in Troubleshooting section on your site but it does not seem to work.

- kc

**Comment by ajordens** [comment]
This is a much delayed response but I suspect you're going to need to have someone with AWS power user access at least complete the Spinnaker setup.
