### ISSUE TITLE
Gitrepo artifacts can't checkout a SHA with the new git binary support

### ISSUE THREAD

**Issue by eaceaser** [spinnaker/spinnaker#6363]
### Issue Summary:
With the new gitrepo git binary support in clouddriver under spinnaker 1.25, an artifact with a git SHA version (vs. a branch or a tag) can't clone. This regressed from jgit's previous behavior.

### Feature Area:
gitrepo artifacts

### Description:
With the new gitrepo git binary support in clouddriver, an artifact with a git SHA version (vs. a branch or a tag) can't clone. This regressed from jgit's previous behavior.

For example:

> Status: 500, URL: http://spin-clouddriver-ro.spinnaker:7002/artifacts/fetch/, Message: Failed to clone repository https://REDATCED.git into /tmp/2b3a567a-3261-4bd8-a9df-112be47e47b4. Error: Cloning into 'REDACTED... warning: Could not find remote branch 7bdd14d8d79dbe47983492f7a23fd1a40e7ac27b to clone. fatal: Remote branch 7bdd14d8d79dbe47983492f7a23fd1a40e7ac27b not found in upstream origin Output:

### Steps to Reproduce:
make a pipeline with a gitrepo artifact, bind the artifact with a SHA version.

### Additional Details:
The offending command appears to be [here](https://github.com/spinnaker/clouddriver/blob/9f9e767d8623efe1c0b63f2990f8d49ca8c75428/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitJobExecutor.java#L90-L91) - the `--branch` argument to git doesn't accept a hash, just a branch or a tag name.

**Comment by german-muzquiz** [comment]
@eaceaser I couldn't find information on how jgit supports cloning by SHA. Are you using full SHAs (40 characters) in your pipeline or are also using short SHAs (7 characters)?

**Comment by eaceaser** [comment]
Full sha. I'm looking at the jgit code and I'm actually not sure how this is currently working either. 

I wonder if it's because the sha we're passing is actually being pointed to by a ref name as well, so jgit's `getAdvertisedRef` logic is successfully matching the sha to a ref?

**Comment by german-muzquiz** [comment]
Thanks for clarifying. I think it makes sense to support only full SHAs in git binary implementation to avoid collisions with branch names or tag names. I'm not sure either how jgit works with that.

**Comment by german-muzquiz** [comment]
Given that there are reports of using short SHA references in some pipelines, the fix will include support for that for not breaking backwards compatibility. The code will first try the regular clone as if the "version" refers to a branch, in case of failing and the "version" matches a short SHA regex, it will do a full clone and check it out.
