### ISSUE TITLE
Fiat 1.14 fails to start - PermissionReadException: request processing timeout

### ISSUE THREAD

**Issue by oradwell** [spinnaker/spinnaker#6365]
### Issue Summary:
Fiat fails to start when upgraded to Fiat 1.14 (Spinnaker 1.23)

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker on Kubernetes deployed using Halyard 1.41

### Feature Area:
Setup

### Description:
I'd expect fiat to stabilise after `hal deploy apply`. Fiat seems to try to connect to Redis and fail to fetch last modified date in 50ms. It was working fine on Fiat 1.13 (Spinnaker 1.22.6). Downgrading fixes the issue.

### Steps to Reproduce:
Upgrade from Spinnaker 1.22 to 1.23.7 using the following commands:
```
hal config version edit --version=1.23.7
hal deploy apply
```
fiat will keep restarting

### Additional Details:
```
2021-03-09 20:25:24.830 ERROR 1 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  : [] 
The use of configuration keys that are no longer supported was found in the environment:
Property source 'applicationConfig: [classpath:/fiat.yml]':
	Key: endpoints.health.sensitive
		Line: 13
		Reason: Endpoint sensitive flag is no longer customizable as Spring Boot no longer provides a customizable security auto-configuration .
Property source 'applicationConfig: [file:/opt/spinnaker/config/fiat-local.yml]':
	Key: endpoints.health.sensitive
		Line: 5
		Reason: Endpoint sensitive flag is no longer customizable as Spring Boot no longer provides a customizable security auto-configuration .
Please refer to the migration guide or reference guide for potential alternatives.
2021-03-09 20:25:25.132  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : [] 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-09 20:25:25.232 ERROR 1 --- [           main] o.s.boot.SpringApplication               : [] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'addUnrestrictedUser' defined in class path resource [com/netflix/spinnaker/fiat/config/UnrestrictedResourceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.lang.String]: Factory method 'addUnrestrictedUser' threw exception; nested exception is com.netflix.spinnaker.fiat.permissions.PermissionReadException: request processing timeout after PT0.05S for checkLastModified
```

**Comment by darkpeak** [comment]
We get this issue as well, and have resorted to fixing fiat to the previous version which doesn't seem very satisfactory, but does allow us to run 1.23.

`kubectl set image deployment/spin-fiat fiat=us-docker.pkg.dev/spinnaker-community/docker/fiat:1.13.0-20200817170018 --record`

**Comment by oradwell** [comment]
I believe it was caused by https://github.com/spinnaker/fiat/pull/751

**Comment by oradwell** [comment]
I've increased the redis timeouts by adding configuration into `/home/spinnaker/.hal/default/profiles/fiat-local.yml`:
```yaml
redis:
  repository:
    checkLastModifiedTimeout: PT0.5S
    getPermissionTimeout: PT1.5S
```
I no longer get the timeouts. The defaults are PT0.05S (50ms) and PT1S (1s)

**Comment by oradwell** [comment]
I'll close this since I found a workaround mentioned above. I've also increased resource limits on fiat container which is likely to be the reason the timeouts were hit

**Comment by mattgogerly** [comment]
Just a note that we've also been seeing this issue, applying the config above fixed it. Seems to be a regression as we didn't see this before 1.23.
