### ISSUE TITLE
deck: Loosen warnings for deck when setting up Cloud Foundry deployment

### ISSUE THREAD

**Issue by gregturn** [spinnaker/spinnaker#639]
A warning is visible when editing a pipeline:

```
The following errors may affect the ability to run this pipeline:

You must have a Bake or Find Image stage before any deploy stage.
```

This should not kick-in if the deployment target is just Cloud Foundry, because Cloud Foundry doesn't require finding or baking images.

**Comment by ajordens** [comment]
cc: @anotherchrisberry

**Comment by anotherchrisberry** [comment]
Sorry for the delay. I need to prioritize this, but it should not be super difficult. I will need to extend the functionality around the pipeline validators and add a `skipValidation` option to the validator. Ping me in ten days if this isn't in place and I'll make it happen.

**Comment by gregturn** [comment]
@anotherchrisberry Ping!

**Comment by tomaslin** [comment]
I thought we were adding the notion of a bake for cloud foundry, is this no longer the case?

**Comment by gregturn** [comment]
Bake didn't seem to fit. We talked about adding a new stage like "Find Artifact" where you can specify coordinates.

**Comment by anotherchrisberry** [comment]
I've got a PR here: https://github.com/spinnaker/deck/pull/2082 

I am curious about the "Find Artifact" stage. Does that seem like a cleaner approach for the CF deployment model?

**Comment by gregturn** [comment]
In essence, I don't need to bake an image. I can just immediately deploy the artifact found in my repository. I toyed with some form of noop Bake stage in orca, but didn't see that panning out. I see little value in going out to roscoe for nothing. So we can either stick with having CF Deploy handle this, or pursue Find Artifact, which just means spec out a repository/artifact and an account.

Thoughts??

**Comment by anotherchrisberry** [comment]
That sounds like a lot of work - both for you and for the user - just to make it look and behave like AWS/Azure/GCP. The user would have to specify the location twice and it wouldn't do any actual work beyond verifying the artifact existed, right?

Totally up to you. We can merge that PR and revisit it later, or I can hold off if you want to think about it more or discuss with other folks.

**Comment by gregturn** [comment]
My thoughts are to pull the "Repository/Artifact" subitem from CF's Deploy details and move it into Find Artifact.

From that point, either Find Artifact or Find Image could be placed in a pipeline to put artifact details into the pipeline's context. 

Yeah, it only sounds of value if something outside CF would merit such an extraction.

**Comment by lwander** [comment]
Why not update find image to work find static images (artifacts)? I'm not sure why they need to be separate but similar sounding stages that accomplish mostly the same thing.

**Comment by JargoonPard** [comment]
As part of a different project a team at msft has built a Jenkins plugin that builds an image file and drops it into an Azure storage location. Essentially adding bake into Jenkins. We have been thinking that a Find Artifact stage that pulls an image from a storage location might also make sense for us as well. I haven't looked into enough of the pipeline workings to know what the output of the bake stage is exactly but I'm assuming it's a location to the built ami.  Is that correct?
