### ISSUE TITLE
QIODEVICE::Write (QFile, "Spinview_QT_log"): device not open

### ISSUE THREAD

**Issue by anshulverma22** [spinnaker/spinnaker#6394]
### Issue Summary:
I have a FLIR camera (CM3-U3-50S5M-CS) connected to my rspi and the **spinview** and **spinnaker_python** python code say that camera is not connected.

### Environment:
OS -> Ubuntu: 18.04.4
CPU -> arm64 (rspi 4)
installed spinnaker-2.3.0.77 for this OS and *arm64 CPU* using `python3.6.9` -> *python3*
installed spinnaker_python-2.3.0.77 for this OS and *linux_aarch64*

I can import `PySpin` in python3 and launch `Spinview` 

### Description:
The device is connected as I can see it in the `lsusb` output
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1e10:3300 Point Grey Research, Inc. 
Bus 001 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
And I have checked the camera in other machines (amd64 CPU) with Windows OS and Ubuntu OS. The camera does get detected in those machines with the same cable.

but when I open SpinView in rspi, it shows no camera. with the following text in the terminal -> 

```
Warning: (null) ((null):0, QFontDatabase: Cannot find font directory /opt/spinnaker/bin/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
Warning: (null) ((null):0, QFontDatabase: Cannot find font directory /opt/spinnaker/bin/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
Warning: (null) ((null):0, QLayout: Attempting to add QLayout "" to QGroupBox "", which already has a layout)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
Warning: (null) ((null):0, QLayout: Attempting to add QLayout "" to QGroupBox "", which already has a layout)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
Warning: (null) ((null):0, QLayout: Attempting to add QLayout "" to QGroupBox "", which already has a layout)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
Warning: (null) ((null):0, QLayout: Attempting to add QLayout "" to QGroupBox "", which already has a layout)
QIODevice::write (QFile, "SpinView_QT_log"): device not open
```

I am hoping someone would have seen a similar issue and any leads on a possible solution would be great.

**Comment by ck3mp3r** [comment]
@anshulverma22 I think you are getting this project confused with the [spinnaker sdk](https://www.flir.com/products/spinnaker-sdk/)

**Comment by Anshul22Verma** [comment]
oh yep i’m sorry wrong repo. I’ll ask my question in the sdk repo. Thanks for replying 🙂
