### ISSUE TITLE
front50 is unable to get credentials form instance profile in kubernetes

### ISSUE THREAD

**Issue by jaekunchoi** [spinnaker/spinnaker#6397]
### Issue Summary:
Front50 was not able to get credentials from instance profile in Kubernetes node and it does not start because of this. It keeps looking at access key id and secret which is not something I can provide as it needs to be use instance profile instead

```
front50 unable to load aws credentials from any provider in the chain: [environmentvariablecredentialsprovider: unable to load aws credentials from environment variables (aws_access_key_id (or aws_access_key) and aws_secret_key (or aws_secret_access_key)), systempropertiescredentialsprovider: unable to load aws credentials from java system properties (aws.accesskeyid and aws.secretkey), webidentitytokencredentialsprovider: you must specify a value for rolearn and rolesessionname, com.amazonaws.auth.profile.profilecredentialsprovider@78b9d614: profile file cannot be null, com.amazonaws.auth.ec2containercredentialsproviderwrapper@5cbb2b1d: failed to connect to service endpoint: ]
```

### Cloud Provider(s):

EKS

### Environment:

EKS private cluster deploy (it's fully private with air gap using local BOM)
Self managed worker nodes

### Feature Area:

AWS SDK update and sts:AssumeRoleWithWebIdentity support

### Steps to Reproduce:

IAM role has S3 Full policy attached to all of EKS worker node EC2 instances.
Run `hal deploy` to successfully deploy all microservices.
See front50 failing with above error

### Additional Details:

I was looking at [this](https://github.com/spinnaker/spinnaker/issues/5521) but not sure whether it is related as I'm using instance profile. I have actually set AWS_REGION which successfully comes in as env var inside the pod container but the issue still persists with same error. Next thing I was going to try was to set IAM role with k8s service account to see if front50 picks up from there but I'm not sure whether this would solve the problem I am facing?

**Comment by jaekunchoi** [comment]
any help here would be great

**Comment by kskewes** [comment]
IRSA works for us running in EKS.
This is also a lot more secure than giving every pod on the node access to the nodes InstanceProfile which may include many networking permissions (create ENI/etc).

**Comment by jaekunchoi** [comment]
@kskewes is that related to `failed to connect to service endpoint` so if we don't have ISRA defined it fails because it's blocked?

**Comment by jaekunchoi** [comment]
FYI this is already working now after using EKS service account with IAM role and referenced in front50 config
