### ISSUE TITLE
Error accessing pod logs

### ISSUE THREAD

**Issue by babinin** [spinnaker/spinnaker#6412]
### Issue Summary:
Error in 'Console Output (Raw)'

### Cloud Provider(s):
Kubernetes

### Environment: 
Spinnaker v1.26.0, Kubernetes v1.21.0

### Feature Area:
UI

### Description:
expected: pod log
actual: TypeError: can't access property "name", selectedLog is undefined

**Comment by wwalters12** [comment]
I'm seeing this issue on Spinnaker v1.26.0, Kubernetes v1.16.0 as well. When inspecting the page, I'm seeing these errors after clicking **Logs:** Console Output (Raw)

`react-dom.production.min.js:209 TypeError: Cannot read property 'name' of undefined
    at ConsoleOutputModal.tsx:50
    at Array.map (<anonymous>)
    at ConsoleOutputModal_ConsoleOutputModal (ConsoleOutputModal.tsx:47)
    at oh (react-dom.production.min.js:153)
    at di (react-dom.production.min.js:175)
    at Rj (react-dom.production.min.js:263)
    at Qj (react-dom.production.min.js:246)
    at Kj (react-dom.production.min.js:246)
    at yj (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
Ci @ react-dom.production.min.js:209
Xi.c.callback @ react-dom.production.min.js:226
Cg @ react-dom.production.min.js:131
Ji @ react-dom.production.min.js:212
Sj @ react-dom.production.min.js:255
exports.unstable_runWithPriority @ scheduler.production.min.js:19
cg @ react-dom.production.min.js:122
Jj @ react-dom.production.min.js:248
yj @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:19
cg @ react-dom.production.min.js:122
fg @ react-dom.production.min.js:123
gg @ react-dom.production.min.js:122
Ig @ react-dom.production.min.js:230
zh @ react-dom.production.min.js:163
(anonymous) @ useLatestPromise.hook.ts:79
(anonymous) @ angular.js:17330
(anonymous) @ angular.js:17378
$digest @ angular.js:18514
$apply @ angular.js:18903
(anonymous) @ angular.js:12775
completeRequest @ angular.js:13032
xhr.onload @ angular.js:12937
load (async)
(anonymous) @ angular.js:12920
(anonymous) @ angular.js:12720
(anonymous) @ angular.js:12461
(anonymous) @ angular.js:17330
(anonymous) @ angular.js:17378
$digest @ angular.js:18514
(anonymous) @ angular.js:18835
completeOutstandingRequest @ angular.js:6439
(anonymous) @ angular.js:6718
setTimeout (async)
Browser.self.defer @ angular.js:6716
$evalAsync @ angular.js:18833
(anonymous) @ angular.js:17202
scheduleProcessQueue @ angular.js:17378
then @ angular.js:17299
chainInterceptors @ angular.js:12389
$http @ angular.js:12376
request @ ApiService.ts:117
get @ ApiService.ts:108
get @ ApiService.ts:182
getConsoleOutput @ InstanceReader.ts:25
(anonymous) @ ConsoleOutputModal.tsx:19
(anonymous) @ useLatestPromise.hook.ts:65
Ii @ react-dom.production.min.js:211
Vj @ react-dom.production.min.js:257
exports.unstable_runWithPriority @ scheduler.production.min.js:19
cg @ react-dom.production.min.js:122
Dj @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
X @ scheduler.production.min.js:17
H.port1.onmessage @ scheduler.production.min.js:14
angular.js:14961 TypeError: Cannot read property 'name' of undefined
    at ConsoleOutputModal.tsx:50
    at Array.map (<anonymous>)
    at ConsoleOutputModal_ConsoleOutputModal (ConsoleOutputModal.tsx:47)
    at oh (react-dom.production.min.js:153)
    at di (react-dom.production.min.js:175)
    at Rj (react-dom.production.min.js:263)
    at Qj (react-dom.production.min.js:246)
    at Kj (react-dom.production.min.js:246)
    at yj (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 "Possibly unhandled rejection: {}"`

**Comment by sramek5** [comment]
In our situation there are no logs at all. 

When I click on **Logs: Console Output (Raw)** pop-up window will show up and immediately after disappear, showing no logs. 
Unfortunately I cannot see any error messages in spinnaker service logs.

Halyard: 1.42.0
Spinnaker: 1.26.2 (Disenchantment)
Kubernetes: v1.19.0

**Comment by wwalters12** [comment]
I'm seeing this as resolved in Spinnaker v1.26.3

**Comment by babinin** [comment]
With v1.26.3 the issue is resolved. Thank you @german-muzquiz. 
Thank you all for participating.
