### ISSUE TITLE
Error viewing a Server Group details with ASG MIG without "instanceMonitoring" flag

### ISSUE THREAD

**Issue by black-mirror-1** [spinnaker/spinnaker#6427]
### Issue Summary:
If a server group is creating without the flag **instanceMonitoring**, we are not able to view the details of the server group in the UI.

### Cloud Provider(s):
AWS EC2

### Environment:
Spinnaker 1.26.2

### Feature Area:
Deck UI

### Description:

When I try to view the details of the server group I get the below error in the UI.

![image](https://user-images.githubusercontent.com/35616070/118019430-d5eda480-b30d-11eb-8616-b45d09d8add4.png)

### Steps to Reproduce:

1. Create a new Server Group.

`curl 'http://localhost:8084/tasks' \
-X 'POST' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Content-Type: application/json;charset=utf-8' \
--data-binary '{"job":[{"type":"createServerGroup","cloudProvider":"aws","account":"my-aws-account","application":"demoapp","stack":"","credentials":"my-aws-account","onDemandBaseCapacity":3,"onDemandPercentageAboveBaseCapacity":0,"spotAllocationStrategy":"capacity-optimized","setLaunchTemplate":true,"launchTemplateOverridesForInstanceType":[{"instanceType":"m5.large"},{"instanceType":"m4.large"}],"capacity":{"min":3,"max":9,"desired":6},"subnetType":"private-subnet","availabilityZones":{"us-west-2":["us-west-2a","us-west-2b","us-west-2c","us-west-2d"]},"keyPair":"my-key-pair","securityGroups":["sg-0873865956785cef3"],"spotPrice":2,"instanceType":"c4.large","virtualizationType":"hvm","amiName":"amzn2-ami-hvm-2.0.20210427.0-x86_64-gp2","targetGroups":["demoapp-targetgroup"],"base64UserData":"","associatePublicIpAddress":false}],"application":"demoapp","description":"Create New Server Group in cluster demoapp"}'`

2. Try to view the details of that server group in the UI.

**Comment by pdk27** [comment]
Fix merged. Target-release - 1.27
