### ISSUE TITLE
ECS: Support enableExecuteCommand in service definitions

### ISSUE THREAD

**Issue by iandelahorne** [spinnaker/spinnaker#6429]
### Issue Summary:

Add support for enableExecuteCommand in ECS services

### Cloud Provider(s):

AWS ECS

### Environment:

AWS ECS Fargate

### Feature Area:

Clouddriver

### Description:

AWS released a new feature enabling the ability to `exec` into containers running in ECS, akin `docker exec`. This was detailed in a [blog post](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/). This is enabled by setting the new `enableExecuteCommand` field in a service definition to `true`

### Steps to Reproduce:

1. Create a pipeline that deploys an ECS service
2. Edit the deploy stage to include `"enableExecuteCommand": true`
3. Deploy the service
4. Inspect the resulting task with `aws ecs describe-tasks --query tasks[0].enableExecuteCommand`
5. The result is false

### Additional Details:

This feature was released in the AWS SDK [1.11.975](https://github.com/aws/aws-sdk-java/blob/a5c2161eae2c549843884e032ef7df6664592f2e/CHANGELOG.md#L860) and thus this can be easily supported by updating the AWS SDK and Netflix AWS Object Mapper, along with some code inside clouddriver ECS.  For example this would be partially fixed by spinnaker/kork#862 and then passing `withEnableExecuteCommand(bool)` to CreateServiceRequest [here](https://github.com/spinnaker/clouddriver/blob/70f3fbe415a0d8b7d04436f1ef36503fbc359c5e/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java#L522-L531)

**Comment by paragbhingre** [comment]
@spinnakerbot add-label provider/ecs

**Comment by allisaurus** [comment]
Closing as this feature [has been merged](https://github.com/spinnaker/clouddriver/pull/5378) and should be available in 1.27
