### ISSUE TITLE
ECS Deploy stage throws NPE while trying to resolve Security Groups

### ISSUE THREAD

**Issue by autero1** [spinnaker/spinnaker#6440]
### Issue Summary:
Deploy stage throws NPE for an ECS application when resolving Security Groups.

### Cloud Provider(s):
- AWS ECS

### Environment:
- Spinnaker running in EKS, deploying to AWS ECS 

### Feature Area:
- Pipelines / ECS Deploy

### Description:
When running deploy stage in a manually configured pipeline, Clouddriver fails to resolve Security Groups:
```
Exception ( Monitor Deploy )
java.lang.NullPointerException at java.base/java.util.HashSet.(HashSet.java:119) at com.netflix.spinnaker.clouddriver.ecs.services.SecurityGroupSelector.resolveSecurityGroupNames(SecurityGroupSelector.java:63) at com.netflix.spinnaker.clouddriver.ecs.deploy.ops.CreateServerGroupAtomicOperation.makeServiceRequest(CreateServerGroupAtomicOperation.java:588) 
```
This only happens when the pipeline and stages are configured with the UI. Also, new security groups are not added to the ECS task when added using the UI.  

After configuring the pipeline and stages, the resulting pipeline JSON contains the following:

```
...
          "securityGroups": [
            "dev-test-fargate-sg",
            "ssm-machine-marker"
          ]
...
```
Running the pipeline results in the above failure. After manually modifying the JSON to this, it works ok:
```
...
          "securityGroups": [
            "dev-test-fargate-sg",
            "ssm-machine-marker"
          ],
          "securityGroupNames": [
            "dev-test-fargate-sg",
            "ssm-machine-marker"
          ]
...
```
However, if a new SG is added in the UI, it is appended to `securityGroups`, not `securityGroupNames` and never gets added to the ECS task.

### Steps to Reproduce:
See description

### Additional Details:
- Release 1.25.5

**Comment by allisaurus** [comment]
This should be addressed by https://github.com/spinnaker/deck/pull/9032
