### ISSUE TITLE
ECS Deployment task definition execution role bugged name resolution

### ISSUE THREAD

**Issue by Arthurflame** [spinnaker/spinnaker#6441]
### Issue Summary:
Task definition role arn is generated with an error.

### Cloud Provider(s):
AWS

### Environment:
AWS ECS, region eu-central-1

### Feature Area:
ECS Deployment (Fargate)

### Description:
When deploying to AWS ECS (Fargate), Service can't run the task, because the execution role that is being assigned to it doesn't exist.

### Additional Details:

Task Definition execution role is created with a role that is expected, but once Service tries to run the task with this role, role is wrongfully resolved.
![image](https://user-images.githubusercontent.com/43091238/120212071-3fd8da00-c23a-11eb-8fd2-c6a8c9cd9788.png) 
Task Definition JSON template 
![image](https://user-images.githubusercontent.com/43091238/120212098-48311500-c23a-11eb-8bf9-b521be66d0a7.png) 
Service event log
![image](https://user-images.githubusercontent.com/43091238/120212111-4bc49c00-c23a-11eb-8715-ad108915f5c4.png)

---

**Comment by Arthurflame** [comment]
Similar issue:
https://github.com/spinnaker/spinnaker/issues/6053

**Comment by allisaurus** [comment]
@Arthurflame which Spinnaker version are you using? We merged a fix for #6053 into 1.26, so I'm curious whether you're working on an older version or this is still a problem.

**Comment by Arthurflame** [comment]
@allisaurus using Spinnaker 1.25.1, seems to be the version issue, thanks.

**Comment by Arthurflame** [comment]
Tested it using with Spinnaker v1.26.3, this issue no longer exists, thank you.

**Comment by allisaurus** [comment]
@Arthurflame awesome, glad you got it working and thank you for circling back!
