### ISSUE TITLE
EC2: Support capacity rebalancing

### ISSUE THREAD

**Issue by pdk27** [spinnaker/spinnaker#6457]
### Issue Summary:
* Add support for EC2 capacity rebalance in Clouddriver and Deck
* Add support for lifecycle hooks in Clone, Modify, Delete operations
* ~~Display lifecycle hooks details under `server group details` in Deck (lifecycle hooks are already supported in Clouddriver API)~~ (Lifecycle Hooks API needs changes for this feature. A new issue will be created at a later to address this.)

More about capacity rebalance and hooks [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html)

### Cloud Provider(s):
AWS

### Feature Area:
Clouddriver, Deck

### Description:
Capacity rebalance is a simple yet powerful feature addition that can help Spot customers. 

Amazon EC2 Auto Scaling Groups can be configured to monitor and automatically respond to changes that affect the availability of Spot Instances. Capacity Rebalancing helps maintain workload availability by proactively augmenting your fleet with a new Spot Instance before a running instance is interrupted by EC2. Optionally, lifecycle hooks can be configured to perform a custom action on instances before termination. And, hence need to be displayed in Deck for completeness.

**Comment by jeyrschabu** [comment]
What actions do you envision making available in UI for lifecycle hooks?

**Comment by pdk27** [comment]
> What actions do you envision making available in UI for lifecycle hooks?

After digging into it, I realized that the [API](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeLifecycleHooks.html) requires an ASG name and  is not currently suitable to be added to Spinnaker's caching layer. I will probably pull that task out into a separate issue and create that issue when I have a better estimate of when that will be feasible. 
Whenever that happens, that task would involve 
1. adding a new caching agent for lifecycle hooks
2. changes to server group cache data to include relationships to hooks
2. include hooks in Clouddriver API response 
3. display hooks in Deck under `Advanced Settings` (yet to be reviewed by UI folks)

Does this answer your question?
