### ISSUE TITLE
Add support for user data

### ISSUE THREAD

**Issue by AMeng** [spinnaker/spinnaker#647]
It looks like there is currently no way of editing user data when creating a new server group. In fact, user data is empty when creating an AWS launch config. Asgard adds some basic user data by default, such as:

```
export CLOUD_ENVIRONMENT=prod
export CLOUD_MONITOR_BUCKET=
export CLOUD_APP=appname
export CLOUD_APP_GROUP=group
export CLOUD_STACK=
export CLOUD_CLUSTER=appname-d0prod-p0enrichment
export CLOUD_AUTO_SCALE_GROUP=appname-d0prod-p0partner-v041
export CLOUD_LAUNCH_CONFIG=appname-d0prod-p0partner-v041-20151207233047
export EC2_REGION=us-east-1
export CLOUD_DEV_PHASE=prod
export CLOUD_PARTNERS=partner
```

It would be nice to have a field exposed for user data, maybe under "Advanced Settings," when creating a server group.

There appears to be support for reading user data from the filesystem, but it didn't notice any documentation around it:

https://github.com/spinnaker/clouddriver/tree/9e1af03bef0da3f244d64dc8dadfab759b398003/kato/kato-aws/src/main/groovy/com/netflix/spinnaker/kato/aws/deploy/userdata

Would this be the preferred method for handling user data? Any plans to expand this and add some documentation? Otherwise I think a text field under "Advanced Settings" would be the easiest solution.

**Comment by anotherchrisberry** [comment]
@AMeng I think you implemented this - are you good with us closing this issue?
