### ISSUE TITLE
Failed to compile Deck while starting Deck

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6482]
### Issue Summary:
It failed to compile Deck while starting Deck and threw below error message after deployed successfully.

### Error Message:
yarn run v1.22.0
$ sh ./start.sh
Node is currently v12.16.1. Activating 12.16.0 using nvm...
Using 12.16.0...
Now using node v12.16.0 (npm v6.13.4)
Launching deck using node v12.16.1...

> deck@0.0.0 start-dev-server /home/spintester/dev/spinnaker/deck
> webpack-dev-server --config app/scripts/modules/app/webpack.config.js --mode=development

INFO: cpus: 16 physical: 8 thread-loader threads: 2
Webpack mode: development
Starting type checking service...
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/spintester/dev/spinnaker/deck
Version: typescript 4.0.2
Time: 4793ms
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...

### Cloud Provider(s):
Azure

### Environment:
ubuntu 16.04

### Feature Area:
Deck

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. It failed to compile Deck while starting Deck
4. Get the error message by command "cat ~/dev/spinnaker/logs/deck.log"

**Comment by neil-yechenwei** [comment]
@vigneshm, after investigated, I found this failure is caused by the [commit](https://github.com/spinnaker/deck/pull/9382). Could you take a look and fix it? Thanks in advance.

**Comment by neil-yechenwei** [comment]
+ @ajordens for awareness

**Comment by neil-yechenwei** [comment]
@vigneshm, kindly ping. Is there any update for this issue?

**Comment by vigneshm** [comment]
@neil-yechenwei , sorry about that. I totally missed the notifications in github.

**Comment by vigneshm** [comment]
@neil-yechenwei , I can't figure out how/where halyard handles the configuration. But I sense that the issue is due to spinnaker app packages not being built before `yarn build`. In the deploy script, can you run `yarn modules` before running `yarn build`? That should fix the issue.

**Comment by neil-yechenwei** [comment]
Thanks @vigneshm  for the suggestion. Below is the result. Does it mean it works fine now?

```
(spin) spintester@spin-vm:~$ cat ~/dev/spinnaker/logs/deck.log
yarn run v1.22.0
$ sh ./start.sh
Node is currently v12.16.1. Activating 12.16.0 using nvm...
Using 12.16.0...
Now using node v12.16.0 (npm v6.13.4)
Launching deck using node v12.16.1...

> deck@0.0.0 start-dev-server /home/spintester/dev/spinnaker/deck
> webpack-dev-server --config app/scripts/modules/app/webpack.config.js --mode=development

INFO: cpus: 16 physical: 8 thread-loader threads: 2
Webpack mode: development
Starting type checking service...
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/spintester/dev/spinnaker/deck
```

**Comment by vigneshm** [comment]
Yep, that looks like the build is succeeding.

**Comment by neil-yechenwei** [comment]
Thanks for your help.
