### ISSUE TITLE
Pipeline graphs with many stages take a long time to render

### ISSUE THREAD

**Issue by CalvinTse** [spinnaker/spinnaker#6504]
### Issue Summary:

We have some pipelines with over 500+ stages. The graphs for these pipelines take a very long time to render in the **Execution Details** section.

### Cloud Provider(s):
NA

### Feature Area:

Deck (Spinnaker UI)

### Description:

For pipelines with 500+ stages, the **Execution Details** section of the pipeline execution takes very long to render. This often results in the page becoming unresponsive to the user, even though Deck is still processing information to render the pipeline graph. Also, resizing the window with these large graphs often result in unresponsiveness because the information to render the graph is re-processed when resizing the window. 

### Steps to Reproduce:

View the **Execution Details** of a Pipeline run with more than 500+ stages.

### Additional Details:

There is a function in PipelineGraph.tsx [(here)](https://github.com/spinnaker/deck/blob/master/packages/core/src/pipeline/config/graph/PipelineGraph.tsx#L289-L303) that takes a very long time to calculate the height of each node in the graph. This function takes up most of the processing time when generating the attributes for the graph to be rendered. 

A feature to initially minimize the pipeline graph if it has more than a **configurable** amount of stages (defaulted to 500 stages) has been implemented. This feature would help save time on the initial mount of PipelineGraph components with a lot of stages and improve responsiveness during window resizing, by not rendering and processing the graph. If minimized, users can click **Expand** to the see the full pipeline graph rendering. This feature is only available for the **Execution Details** section, the pipeline graph on the **Configure** page will not be minimized.

**Comment by mattgogerly** [comment]
Hi @CalvinTse, is this now resolved with the above PR?

**Comment by CalvinTse** [comment]
Hi @mattgogerly, we have tested this PR in our own environment and the **Pipeline Execution Details Page** is more responsive and gets rendered faster on the initial load.

**Comment by mattgogerly** [comment]
Awesome, I'm going to close out this issue then. Feel free to reopen if further issues crop up.
