### ISSUE TITLE
v1.21 on Google has stopped working `Target proxy url all-apis malformed.`

### ISSUE THREAD

**Issue by aholyoake-bc** [spinnaker/spinnaker#6516]
### Issue Summary:
HTTP batch requests to the google cloud API have finally been turned off:
https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html

### Cloud Provider(s):
GCP

### Feature Area:
Clouddriver

### Environment:
Using spinnaker to deploy instance groups to GCE

### Description:
The user is presented with the cryptic message `Target proxy url all-apis malformed.` in the UI.

The solution (we hope) is to upgrade spinnaker, although we're having trouble with this because we use the debian-based install and bintray has been retired.

### Additional Details:

I'm mostly posting this for others' benefit.
[clouddriver.txt](https://github.com/spinnaker/spinnaker/files/7059481/clouddriver.txt)

**Comment by ravichander82** [comment]
Debian based installation is not supported anymore. Going forward only Kubernetes based installations are supported.
