### ISSUE TITLE
dpkg complains about existing filesystem link

### ISSUE THREAD

**Issue by layered-esell** [spinnaker/spinnaker#652]
When upgrading via apt-get this error pops up:

    Setting up spinnaker (0.15.0-3) ...
    ln: failed to create symbolic link ‘/opt/spinnaker/scripts/bin’: File exists
    dpkg: error processing package spinnaker (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     spinnaker
    E: Sub-process /usr/bin/dpkg returned an error code (1)

This should be fixed with https://github.com/spinnaker/spinnaker/pull/651

**Comment by layered-esell** [comment]
https://github.com/spinnaker/spinnaker/commit/466ca58a3129f1b2ead117a43535ecb410d621ac

**Comment by duftler** [comment]
I just cut a new release of spinnaker/spinnaker if you want to verify the behavior is fixed.

**Comment by layered-esell** [comment]
Looks like it's good, no errors this time around:

    The following packages will be upgraded:
      spinnaker
    1 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
    1 not fully installed or removed.
    Need to get 67.7 kB of archives.
    After this operation, 0 B of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 https://dl.bintray.com/spinnaker/debians/ trusty/spinnaker spinnaker all 0.16.0-3 [67.7 kB]
    Fetched 67.7 kB in 0s (157 kB/s)
    (Reading database ... 58148 files and directories currently installed.)
    Preparing to unpack .../spinnaker_0.16.0-3_all.deb ...
    Unpacking spinnaker (0.16.0-3) over (0.15.0-3) ...
    Processing triggers for ureadahead (0.100.0-16) ...
    Setting up spinnaker (0.16.0-3) ...
    Rewriting deck settings in "/var/www/settings.js".
     * Restarting web server apache2
