### ISSUE TITLE
Step Bake manifest with option `--set` active is not able to pass boolean value as string to labels section. 

### ISSUE THREAD

**Issue by mknapcok** [spinnaker/spinnaker#6596]
### Issue Summary:
Step Bake manifest with option `--set` active is not able to pass boolean value as string to labels section. 

### Cloud Provider(s):
AWS

### Environment:
Running on halyard
Spinnaker v1.25.6

### Feature Area:
Pipelines - Bake step

### Description:
I'm trying to pass a boolean value as string that needs to end up as either `labelName: "true"` or `labelName: 'true'`
When overriding values in configuration with switch `Raw Overrides` **ON** to use `--set` option.

When passing `true` the baked result is `true`, which is unacceptable as Kubernetes label 
(_Deploy failed: error: unable to decode "STDIN": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t_)

When passing `'true'` or `\'true\'` the baked result is `'''true'''` (three single quotes)

When passing `"true"` or `\"true\"` the baked result is `'"true"'` (double and single quote)

I believe this is not expected behavior. 

Another way how to solve this issue would be passing only one argument with `--set-string` option but I didn't find a way how to pass only one argument with `--set-string` option, which is probably inapplicable this way.

**Comment by dbyron-sf** [comment]
Do you know a `helm template` invocation that creates the yaml you're looking for?  Perhaps we can start from there and then figure out how to get spinnaker to do the same.

**Comment by mknapcok** [comment]
> Do you know a `helm template` invocation that creates the yaml you're looking for? Perhaps we can start from there and then figure out how to get spinnaker to do the same.

Yes, you're right. I'm unable to do what I need with `--set` option. I can only do it with `--set-string` parameter.
Normally I'm passing this value as values file. 
Would be nice to have an option to choose from `--set` and `--set-string` for each individual override key:value pair.

**Comment by dbyron-sf** [comment]
I imagine specifying this per-override would make for a bit of a cumbersome pipeline, especially with backwards compatibility concerns.  I'm not sure how many other folks need this level of flexibility, but if there's a reasonable way to do it, I could see it making sense.  I'd be happy to review a proposal, and a PR that implements it.

**Comment by mknapcok** [comment]
Well, this was just a proposition to think about. That some boolean values might be wanted to be passed as string and some not. It'd be a cool functionality but I agree that this might overcomplicate things a bit.
To fix my problem I did a workaround in the helmchart so I'm fine now. 
Would you like to close this issue or let it be to see if someone else will be looking for this as well?

**Comment by dbyron-sf** [comment]
Glad you found a workaround.  I'll close the issue, but it'll be here to re-open if someone wants to pick this up.
