### ISSUE TITLE
Database migration lock expiry

### ISSUE THREAD

**Issue by mattgogerly** [spinnaker/spinnaker#6625]
### Issue Summary:
A common issue with using Liquibase on Kubernetes is that if a pod is killed for whatever reason whilst it has a lock on the DATABASECHANGELOGLOCK then manual intervention is required to 'unlock' to allow future pods to start.

### Cloud Provider(s):
N/A

### Environment:
Production

### Feature Area:
SQL

### Steps to Reproduce:
Deploy a service pod backed by SQL and kill it during startup. Observe further pods cannot start as they wait to acquire the lock.

### Additional
My proposed fix for this would be to introduce a library such as [this](https://github.com/blagerweij/liquibase-sessionlock) to override the default lock mechanism with session locks. This way if a pod is killed (session ends) the lock will be released. The linked library supports MySQL and PostgreSQL.

**Comment by mattgogerly** [comment]
@german-muzquiz would love your thoughts on this because Liquibase is outside my expertise

**Comment by apoorvmahajan** [comment]
@mattgogerly as it turns out, we ran into the exact same problem at Salesforce a few months ago. And we fixed it by using the above mentioned library, to enable session level locking. I can put up a PR with the change if it helps.

**Comment by german-muzquiz** [comment]
This looks promising, we just need to double check the versions of the library and liquibase involved. Liquibase is pulled in by spring and it's getting really old.
