### ISSUE TITLE
Halyard missing/stale tagged docker image releases on Google Artifact Registry

### ISSUE THREAD

**Issue by costeirs** [spinnaker/spinnaker#6662]
### Issue Summary:
Halyard release v1.45.0 is missing tagged docker image for Ubuntu variant, and `stable`/`stable-ubuntu` are pointing to v1.44.1.

### Cloud Provider(s):
N/a

### Environment:
- macOS 11.6.5
- Docker Desktop 4.8.2 (79419)

### Feature Area:
Halyard

### Description:
Hi,
Spinnaker v1.27.0 and Halyard v1.45.0 were released about a month ago.
I attempted to pull `us-docker.pkg.dev/spinnaker-community/docker/halyard:1.45.0-ubuntu` similar to [as shown in the docs](https://spinnaker.io/docs/setup/install/halyard/#install-halyard-on-docker) (we were previously using `1.44.1-ubuntu`). We have some existing additional setup scripts that are already assuming an Ubuntu flavor so we would prefer not to rewrite them for Alpine.

We see that there is a `halyard:1.45.0` but no `halyard:1.45.0-ubuntu` tagged image.
Also, the `stable`/`stable-ubuntu` tags are pointing to `1.44.1` and `1.44.1-ubuntu` tagged images, respectively.

Please let me know if you need any additional information.
Thank you!

### Steps to Reproduce:
1. Open Google Artifact Registry https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker/halyard .
2. Search for `Tags:1.45.0-ubuntu` to see missing tag.
3. Search for `Tags:stable` to see outdated stable tags.

### Additional Details:
This may be related to #6657 .

**Comment by workman-Lu** [comment]
sad

**Comment by kskewes-sf** [comment]
Bummer. Missed the `1.45.0-ubuntu` tags during release, will look to add tag.
It will be an additional tag on this one: https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker/halyard/sha256:038c124649b0368760c921ed4ec4848881ff7b5f96420a5ab62b59cb98ccecca

re: `stable`
Second bummer. Wasn't aware of this when we were migrating CI to GitHub Actions.

I guess we could either:
1. manually tag the latest Halyard release container with `:stable` as part of this https://spinnaker.io/docs/releases/release-manager-runbook/#release-minor-version-halyard
2. change docs to suggest `:latest`. A `release-*` branch version is probably safer but may be slower to be fixed (backport process/etc).

Any other ideas?

If anyone is able to help with PR's improving Halyard or updating docs that would be great.

**Comment by kskewes-sf** [comment]
Thanks again for raising this.
Have pushed missing tags for `1.45.0-ubuntu`, `stable`, `stable-ubuntu` images.
See: https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker/halyard

```
$ docker run --name halyard --rm -it us-docker.pkg.dev/spinnaker-community/docker/halyard:1.45.0-ubuntu

$ docker exec -it halyard hal --version
1.45.0
```

Note integration testing is not running per #6628.
Alpine Halyard image was used for basic 1.27.0 spinnaker on kubernetes testing only.

**Comment by slopez-quotient** [comment]
Folks  we have Halyard installed on both Ubuntu 18.04 and 20.04
This command

sudo update-halyard

is not working on either one of them

hal
update-halyard
~
Install completed... restarting Halyard
The halyard daemon isn't running yet... starting it manually.....
1.44.1-20210628193525
Bash auto-completion updated.

Is there any other way to upgrade Halyard?

**Comment by kskewes-sf** [comment]
@slopez-quotient - I think your comment is more related to this issue: https://github.com/spinnaker/spinnaker/issues/6657

**Comment by slopez-quotient** [comment]
@kskewes-sf  Thank you very much
I have posted my comments  on #6657 as well
