### ISSUE TITLE
Reopen: CheckPrecondition doesn't evaluate expression correctly when upstream stages get restarted

### ISSUE THREAD

**Issue by JamieChe** [spinnaker/spinnaker#6675]
### Issue Summary:
CheckPrecondition doesn't evaluate expression correctly when upstream stages get restarted

### Cloud Provider(s):
kubernetes

### Environment:
Still found in 1.22

### Feature Area:
Pipeline Expressions

### Description:
To reopen the issue https://github.com/spinnaker/spinnaker/issues/5507

My checkPrecondition stage uses upstream stage results in the expression. If the upstream stage need restart and the stage result get changed, the following checkPrecondition still uses history result for evaluation and causes incorrect result.
We uses jenkins stage for upstream stage,

### Steps to Reproduce:

1. add two jenkins stages: "jenkins1" and "jenkins2" in pipeline. Set “jenkins2” as the downstream stage of "jenkins1".
2. Set both jenkins stage ExecutionOption "If stage fails ignore the failure", to enable pipeline keep running even upstream stage fails
3. add checkPrecondition stage as downstream of "jenkins2", and set the expression as
4. ${( #stage("jenkins1")["status"] matches 'SUCCEEDED|SKIPPED') && (#stage("jenkins2")["status"] matches 'SUCCEEDED|SKIPPED') }
5. Config jenkins job of "jenkins1" and "jenkins2" to get give a failure output, then run pipeline. You should see "jenkins1" and "jenkins2" fail and checkPrecondition fails too, which is correct.
6. Config jenkins job of "jenkins1" and "jenkins2" to get give a success output, and restart "jenkins1". Then "jenkins1" and downstream "jenkins2" will pass, but the checkPrecondition still fails, which is incorrect.

**Comment by rjalander** [comment]
@JamieChe I need someone help with adding reviewers for the PRs and approval for the workflows as I am First-time contributor
https://github.com/spinnaker/orca/pull/4278
https://github.com/spinnaker/gate/pull/1560
