### ISSUE TITLE
Feature request: add ability to show reservation reports

### ISSUE THREAD

**Issue by anotherchrisberry** [spinnaker/spinnaker#669]
This should be feature flagged and off by default.

Code exists, but is in Netflix-specific modules/packages, so it's just a question of moving that code into OSS codebases and adding a feature flag to enable/disable it.

Requires changes to Gate + Clouddriver + Deck

**Comment by ajordens** [comment]
Off by default? or just not displayed if there are no actual reserved instances setup in the account?

**Comment by anotherchrisberry** [comment]
Good question. I was thinking off by default so users are explicitly opting in; otherwise, we need to add guards in the UI (and probably modify the backend) to determine if there are *any* reserved instances in any account in order to decide whether or not to show the report.

**Comment by tomaslin** [comment]
@ajordens @anotherchrisberry what is the status of this?

**Comment by anotherchrisberry** [comment]
Still a todo - I think the "help wanted" tag is a good one.

**Comment by ajordens** [comment]
Not a huge LoE to get backend bits exposed for non-Netflix users. 

When this work does get done, we should also update `deck` such that it splits out reservations by VPC/EC2-Classic (_we have a new version of the API that supports this_).

**Comment by anotherchrisberry** [comment]
@ajordens is any of the reservation report code in clouddriver/front50 in our private modules, or is it just feature flagged?

**Comment by ajordens** [comment]
It's in private modules.

Also feels to me like it should be on for everyone, but perhaps smart enough to hide if their are no reservations.

**Comment by cfieber** [comment]
If we turn it on for all we should handle the regions where reservations aren't available (India?)

**Comment by ajordens** [comment]
Did we ever do this @anotherchrisberry

**Comment by anotherchrisberry** [comment]
We never did it but the LOE is still pretty small.

**Comment by anotherchrisberry** [comment]
It's been 2.5 years, let's just acknowledge this isn't happening.
