### ISSUE TITLE
fiat admin group can't see other group info for adding permissions at application level

### ISSUE THREAD

**Issue by MANOHAR452** [spinnaker/spinnaker#6690]
### Issue Summary:
fiat admin group can't see other group info for adding permissions at application level, when adding application permissions only groups visible if log in user belongs to those groups.

### Cloud Provider(s): 
AWS

### Environment:
Running and deploying  the spinnaker using Halyard on EKS

### Feature Area:
Security(RBAC)

### Description:
Expected Behavior: As a Fiat admin roles member should see all the applications and able to edit the application and add other role permissions.
Actual Behavior: To add other roles, only groups visible if log in user really belongs to, even though log in user is part of Fiat Admin Group, it still expects to be part of other AD Groups to add the permissions at the application level.

### Steps to Reproduce:
Spinnaker version: "1.26.7"
Authentication: SAML 2.0

**Comment by mattgogerly** [comment]
I believe the modal only shows you the groups you have.

You can however just type in the name of a role and it will let you add it.
