### ISSUE TITLE
Latest clouddriver version

### ISSUE THREAD

**Issue by sramek5** [spinnaker/spinnaker#6711]
### Issue Summary:

Which `clouddriver` version is the latest?

`8.1.0` or `5.76.2` mentioned n the latest version of `spinnaker`?

**Comment by dbyron-sf** [comment]
Can you send a link to the mention of 8.1.0 please.  5.76.2 is the version of clouddriver at the [current HEAD of the release-1.28.x branch](https://github.com/spinnaker/clouddriver/tree/178ccdb149c78bc4eb4ef6d6cdcfe54892f90851).  It's the latest one included in a released version of spinnaker: [1.28.0](https://console.cloud.google.com/storage/browser/_details/halconfig/bom/1.28.0.yml) and [1.28.1](https://console.cloud.google.com/storage/browser/_details/halconfig/bom/1.28.1.yml)

**Comment by sramek5** [comment]
I am following upgrading order...
Spinnaker `1.25.0` has clouddriver `7.3.0`
Spinnaker `1.26.0` has clouddriver `8.0.0`
Spinnaker `1.26.2` has clouddriver `8.1.0`

and then mysteriously

Spinnaker `1.27.0` has clouddriver `5.74.3`
Spinnaker `1.28.1` has clouddriver `5.76.2`

I naturally wondering, if the major version is right and if I should even upgrade to lowest major version.

**Comment by dbyron-sf** [comment]
Small nit that [1.26.2 has clouddriver 8.0.1](https://console.cloud.google.com/storage/browser/_details/halconfig/bom/1.26.2.yml), but yes, you're right.

1.25.0/1.26.0/1.26.2 (and several before 1.25.0) used a different versioning/tagging scheme (`version-x.y.z`) than 1.27.0 and so on (`vx.y.z`).  It's unfortunate and super confusing.  https://github.com/spinnaker/buildtool/pull/181 has some info, as does https://docs.google.com/spreadsheets/d/1CCF6ssl3ZQUWlqUp9ktxJkbsOGX7CgutMkkd36w_GXE/edit#gid=0.

I'd look to the [release notes for 1.27.0](https://spinnaker.io/changelogs/1.27.0-changelog/) for breaking changes, and ignore whatever semantic versioning might imply about the version numbers.

**Comment by sramek5** [comment]
Ok, thanks for answering and looking up.
