### ISSUE TITLE
pod deck unready : error AH00558: apache2 in ipv6 environment

### ISSUE THREAD

**Issue by amirbh913** [spinnaker/spinnaker#6732]
### Issue Summary:
deck pod is running but not ready

### Cloud Provider(s):
AWS
EKS

### Environment:
EKS 1,21
spinnaker operator
spinnaker 1.28.1

### Description:
I want to install spinnaker but pod deck are unready.

### Steps to Reproduce:
install spinnaker with operator

### Additional Details:
All pods : 
![image](https://user-images.githubusercontent.com/46217433/194101566-9904bcfe-3a32-471d-953a-66a56f8e6d98.png)

pod deck log :
![image](https://user-images.githubusercontent.com/46217433/194101455-63b94588-9d68-4efd-9ad4-df3ae9345c9d.png)

operator manisfest : 
![image](https://user-images.githubusercontent.com/46217433/194101895-4b73f658-057a-4f55-9703-c26c3e7e5f9b.png)

**Comment by queueburt** [comment]
I can +1 this, Deck indeed doesn't behave properly by default in an IPv6 environment.  Specifically, after some digging into the deployment, I found that the default apache2 config generation scripts default to setting listeners to IPv4's `0.0.0.0` when the `DECK_HOST` environment variable isn't set.

Fortunately, the [Halyard Custom Settings](https://spinnaker.io/docs/reference/halyard/custom/) (which I believe are accessible via the Operator) enable environment overrides, so there's a fairly easy fix.  Under custom service settings, you can use the following config in `deck.yaml` (which you may have to create) to set apache2 to listen on its IPv6 interfaces as opposed to its IPv4:
```
env:
  DECK_HOST: "[::]"
```

**Comment by amirbh913** [comment]
hi @queueburt ,

thx for your reply.

After looking at the apache2 startup scripts, I also noticed this and modified the spinnaker.yml file accordingly to change the env variable.
