### ISSUE TITLE
The `Clone` button to clone a server group is disabled after cloning a server group after upgrading to Spinnaker 1.29.0

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6734]
### Issue Summary:

After Cloning a Server Group for a particular application within the Deck UI, the `Clone` button becomes disabled after upgrading to Spinnaker 1.29.0.

### Cloud Provider(s):

AWS

### Environment:

- Ubuntu 22.04 LTS VM
- Spinnaker 1.29.0

### Feature Area:

Not sure, assuming either Deck or Clouddriver.

### Description:

I upgraded from Spinnaker 1.28.1 to Spinnaker 1.29.0.
After upgrading, I can clone a server group for an application within the Deck UI, but after cloning a server group, the `Clone` button becomes disabled and I can no longer clone any other server groups within the same application until I hard-refresh my browser.

### Steps to Reproduce:

1. Install Spinnaker 1.28.1.
2. Configure AWS as the Cloud Provider.
3. Create an application that has more than one server group.
4. Upgrade Spinnaker from 1.28.1 to 1.29.0.
5. Clone a Server Group within the application that you created.
6. Attempt to Clone another server group within the same application, and the `Clone` button is disabled.

### Additional Details:

* This worked fine in Spinnaker 1.28.1, so assuming it is a bug introduced in Spinnaker 1.29.0.
* If you hard-refresh your web browser, the button becomes enabled again.

**Comment by pdk27** [comment]
There are a few issues here: 
1. Filtering out instance types without metadata / info leads to errors like below and as a result prevents instance type selector from working:
<img width="400" alt="• Uncaught Typetrror" src="https://user-images.githubusercontent.com/3614196/196494396-66e2292a-8d7a-48e8-8f67-d7b3618bb9d6.png">

Fix: 

2. Previously allowed AMI + instance type combination, now results in validation error without details and lack clarity in messaging. The failed validation clears the incompatible instance type and shows message `Instance Type required`. 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3614196/196496328-ecf531bd-2c4f-458c-86d3-d9ad979f4e4b.png">

Fix: **WIP**
- make validation happen on render so its clear for the user cloning a server group
- add a clear error message like `t2.small was unselected as it is incompatible with the AMI selected.`

**Comment by dbyron-sf** [comment]
Reopening as https://github.com/spinnaker/deck/commit/563b6f6cbfc72a3122d4cfe669ffc347c9dd7168 only addresses some of the issues here.

**Comment by pdk27** [comment]
Opened new issue - https://github.com/spinnaker/spinnaker/issues/6755 for the unfixed issue of inconsistent CX. 
Before [fix](https://github.com/spinnaker/deck/pull/9901) the inconsistent CX was a problem for all cases. After fix, it is relevant only to the simple mode / single instance type case which is handled in Angular code that resides in the core package. Changing it safely requires a Deck expert / extensive testing in multiple environments and scenarios. Hence the new issue. 

Closing this issue.

**Comment by ashleykleynhans** [comment]
Confirmed fixed in 1.29.1.
