### ISSUE TITLE
Azure Provider

### ISSUE THREAD

**Issue by aaranmcguire** [spinnaker/spinnaker#675]
Hi,

Just wondering how easy it would be to incorporate Azure as a provider, I'm not quite sure how it's coded but it would be awesome if it was easy to plug & play other providers e.g:

- Azure
- Digital Ocean
- Rackspace

Or even local providers like:

- ESXi (vSphere)
- Hyper-V

**Comment by anotherchrisberry** [comment]
Azure support is in the works right now - you can see most of the work involved here:
* https://github.com/spinnaker/clouddriver/tree/master/clouddriver-azure
* https://github.com/spinnaker/deck/tree/master/app/scripts/modules/azure

We're actively working on making it easier to plug in new providers. Right now, it's frankly quite a bit of work, but it should be isolated to those two repositories: [clouddriver](https://github.com/spinnaker/clouddriver) for the backend to provide caching and operations against the provider itself, and [deck](https://github.com/spinnaker/deck) for the UI components.

If the provider has a nice, well-documented Java SDK, the backend work is less of a challenge, and if the provider has a similar shape to AWS - concepts like server groups, load balancers, security groups, networks, regions - it's even easier (or less difficult, maybe).

We are hoping to have a better story around creating a new provider - or even customizing an existing one - in the coming few months.

**Comment by aaranmcguire** [comment]
@anotherchrisberry Thats great thanks, are there any plans to create providers for private cloud? I'm not sure the percent of users/companies that use public vs private cloud, but I know in my case it would be quite useful. Also, with the release of the Azure provider, will windows support come shortly after? or is that out of scope at the moment?

**Comment by aaranmcguire** [comment]
(Also, feel free to close this issue, or do you want me to?)

**Comment by anotherchrisberry** [comment]
Good question on Windows support - I'm _guessing_ that's out of scope for now, but @milismsft or one of the other Azure folks can probably answer that.

The Google devs and @gregturn have done a great job helping us figure out the abstractions to make a more generic provider model. With that in place, it's our hope that it's pretty straightforward to plug in a provide cloud provider.

Let's leave this open for a few days and see if anyone from the Azure team wants to chime in.

**Comment by gregturn** [comment]
I'm frankly not sure what "private cloud" is. Cloud Founsry can be run on your laptop or a closed data center in addition to the public instances like PWS. 

Essentially, if a given cloud has an SDK, someone can work on the module as Chris just said. But someone has to step up and do the work. "Private cloud" is not a well defined API unless there is something I'm missing.

**Comment by aaranmcguire** [comment]
@gregturn I define Private Cloud as something like Hyper-V or ESXi (from VMware), Private cloud is where you own the infrastructure. I'm not quite sure if they have API's but I know it would make this product a lot more attractive to companies (as we don't use public cloud at my workplace).

**Comment by gregturn** [comment]
Those sound like virtualization technologies, which appears to be on the infrastructure level. Is there some API where those technologies would actually spin up whole new virtualized servers, install applications/images, and provide monitoring of said items? If not, then the conversation is moot.

**Comment by aaranmcguire** [comment]
@gregturn Yh, there are just not sure the extent of how they work. I'll try do some research this week and feedback to you.

**Comment by JargoonPard** [comment]
@aaranmcguire I'm with the MSFT team that's adding the Azure support. We're using the new ARM templates for deploying infra so it will all work with Azure Stack for private cloud as well. We're interested in understanding what you mean by Windows support. There are a lot of things we could be doing in that space if it makes sense and some that don't. :-) I'd be happy to chat offline if you'd like, my microsoft alias is larrygug.

**Comment by aaranmcguire** [comment]
@JargoonPard I'm just going off the screenshots & bits of the documentation so correct me if I'm wrong, but you cant currently install Spinnaker on Windows (maybe you can but theres no documentation for it?) and also, you cant bake Windows VMs. 

My dream implementation of Spinnaker (correct me if anything is out of scope):

- *Trigger pipeline*
- Builds new servers based on a pre-set configs
- Runs Chef or Puppet (to make sure the server is setup correctly) 
- Deploy the code (IIS Sites/App Pools/Services)
- Automated tests are run
- Manual Judgment
- Change Loadbalancer to point to new VM
- Wait (30 mins)
- Manual Judgment
- Setup/Deploy second server (same sort of pipeline for the first VM)

**Comment by JargoonPard** [comment]
@aaranmcguire we haven't run spinnaker on Windows boxes yet but it should all run fine.  It's certainly something that we need to get to. Getting it all running in containers is certainly on the list. Adding packer support for Azure is also on our backlog. Everything that you list should make sense. I'll follow up with you after the holidays to understand your scenarios better to see how they fit with what we're thinking.

**Comment by ldhertert** [comment]
Count me in as someone that would be interested in Windows baking support (but we use aws). We already have Packer set up to build a Windows ami, is there a way currently to leverage the rest of spinnaker's features but to build the ami externally?

**Comment by tomaslin** [comment]
@ldhertert yes, you can bypass the bake stage completely if you provide an amiName field to the cluster in your spinnaker pipeline's deploy stage.

**Comment by Blackbaud-SriniHasti** [comment]
I am wondering whats the target date for supporting azure ?

**Comment by JargoonPard** [comment]
@Blackbaud-SriniHasti there's a small team of us at MSFT that are working on it. We hope to have rudimentary server groups (Azure Scale Sets) and Network Security Groups implemented in early Feb. It would be great to hear what the minimum requirements are for you to make it usable.  Feel free to reach out to me via email (larrygug) at microsoft.

**Comment by ajordens** [comment]
Closing this issue as Azure support is actively being worked on by @JargoonPard and the rest of the Microsoft team.

Probably best to reach out to them directly (via Slack) if more details are required.

**Comment by SurferJeffAtGoogle** [comment]
I'm looking to bake Windows VMs with Spinnaker.  The last mention of baking Windows VMs I can find anywhere is from 2015, and the answer was no.  Is there any news or changes?

**Comment by skim1420** [comment]
I haven't tried them myself, but there have since been added packer templates for Windows, one for [AWS](https://github.com/spinnaker/rosco/blob/master/rosco-web/config/packer/aws-windows-2012-r2.json) and one for [Azure](https://github.com/spinnaker/rosco/blob/master/rosco-web/config/packer/azure-windows-2012-r2.json).
