### ISSUE TITLE
Some details of document to run spinnaker on kubernetes

### ISSUE THREAD

**Issue by larry-fuy** [spinnaker/spinnaker#678]
When I run spinnaker on kubernetes in Google Cloud according to README, an issue of clouddriver always rebooting hits me painfully. After hours digging, I found it is only fixed only when I set provider/aws/enabled as false in spinnaker-local.yml. Although this should be a tiny problem for someone familiar with spinnaker, as a new user I spend hours to figure out. So I suggest to add this detail into README. 

Another thing I noticed when I scramble on spinnaker-local.yml is the header comments ask to copy this file to .spinnaker/, but the README file said it should be copied to .spinnaker/config. This may be another inconsistency between code and documents.

**Comment by tomaslin** [comment]
@ttomsu could you comment on this?

**Comment by ttomsu** [comment]
Thanks for the feedback! I'm sorry that something so small caused you hours of pain :-(

I've removed the AWS sections to keep the setup simple.
