### ISSUE TITLE
Change of kubectl authentication on GKE

### ISSUE THREAD

**Issue by Lark-super** [spinnaker/spinnaker#6782]
Issue Summary:
Change of kubectl authentication on GKE

Cloud Provider(s):
Google

Environment:
Spinnaker 1.29.1

Description:
I saw [1] in the GCP news that if you want to use kubectl with GKE-v1.26, it states that you have to install the gke-gcloud-auth-plugin plugin.
We also use kubectl in Spinnaker, but after checking the latest version [2], it appears that the gke-gcloud-auth-plugin plugin is not installed.
If this is the case, it appears that Spinnaker cannot be used with GKE-v1.26. Is there any support planned?

[1]
 https://cloud.google.com/kubernetes-engine/docs/deprecations/auth-plugin?hl=en

[2]
 https://github.com/spinnaker/clouddriver/blob/release-1.29.x/Dockerfile.slim#L40

**Comment by jasonmcintosh** [comment]
https://github.com/spinnaker/clouddriver/pull/5847 should fix this when merged

**Comment by Lark-super** [comment]
Thank you
