### ISSUE TITLE
Join community slack link not working

### ISSUE THREAD

**Issue by gilesrapkinb** [spinnaker/spinnaker#6783]
### Issue Summary:

Not able to join your community slack as the site you link to from your docs shows a placeholder page.

### Cloud Provider(s):

N/A

### Environment:

N/A

### Feature Area:

N/A

### Description:

I was trying to join your community slack, but the page your docs link to just shows a Heroku placeholder page.

### Steps to Reproduce:

1. Go to the community page in the docs: https://spinnaker.io/docs/community/
2. Click on the slack link, which takes you to: http://join.spinnaker.io/
3. See a holding page

**Comment by adammw** [comment]
Found an invite link on the spinnaker.io homepage: https://join.slack.com/t/spinnakerteam/shared_invite/zt-7juwxmx0-nQ4Ud4pJcbuPykX3SXwQrg - community page needs to be updated to match

**Comment by dbyron-sf** [comment]
Thanks for the pointer: https://github.com/spinnaker/spinnaker.io/pull/297

**Comment by jasonmcintosh** [comment]
Going to close/resolve this thanks!
