### ISSUE TITLE
Cloud driver fails to start when upgrading from 1.28.4 to 1.29.2

### ISSUE THREAD

**Issue by somejavadev** [spinnaker/spinnaker#6791]
### Issue Summary:

Cloud driver fails to start when upgrading from 1.28.4 to 1.29.2

### Cloud Provider(s):

GCP
Kubernetes

### Environment:

I am running spinnaker deployed to a GKE cluster in GCP,  deploying via halyard 1.51.0

### Feature Area:

Cloud driver

### Description:

When upgrading from 1.28.4 to 1.29.2 via `hal config version edit --version 1.29.2` all services/workloads start but the cloud driver workload fails to start with the following error.

```text
Field credentialsRepository in com.netflix.spinnaker.clouddriver.security.AbstractAtomicOperationsCredentialsConverter required a single bean, but 3 were found:
- kubernetesCredentialsRepository: defined by method 'kubernetesCredentialsRepository' in class path resource [com/netflix/spinnaker/config/KubernetesConfiguration.class]
- googleCredentialsRepository: defined by method 'googleCredentialsRepository' in class path resource [com/netflix/spinnaker/clouddriver/google/config/GoogleCredentialsConfiguration.class]
- dockerRegistryCredentialsRepository: defined by method 'dockerRegistryCredentialsRepository' in class path resource [com/netflix/spinnaker/config/DockerRegistryConfiguration.class]
```

![image](https://user-images.githubusercontent.com/6507120/214637024-d6a99586-9f30-4dfe-9eab-490e5d085477.png)

This error looks like it could potentially be related to https://github.com/spinnaker/spinnaker/issues/6733 although it was fixed in 1.29.1

### Steps to Reproduce:

```bash
hal config version edit --version 1.29.2
hal deploy apply
```

### Additional Details:

Halyard version: 1.51.0 (docker)
All version 1.29.x gives this issue.

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by kirangodishala** [comment]
This issue has been addressed [here](https://github.com/spinnaker/clouddriver/pull/5875) and is getting back-ported to 1.29.x.

**Comment by somejavadev** [comment]
Excellent, thanks @kirangodishala
