### ISSUE TITLE
Spinnaker docker images compatibility of ubunto 21.04

### ISSUE THREAD

**Issue by gchan2** [spinnaker/spinnaker#6794]
### Issue Summary:
Spinnaker docker images compatibility of ubunto 21.04

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

Descriptions:

Dockerfiles:

![image](https://user-images.githubusercontent.com/10932979/215713279-290ae8b9-c484-4d7a-8abf-6a213688982e.png)

Can we have compatibility with Ubuntu 21.04 ? Because we found that the current version of Ubuntu has too many unfixable bugs and we would like to be compatible with Ubuntu 21.04.

![image](https://user-images.githubusercontent.com/10932979/215713430-dfad176a-5969-4b00-8d39-c4a7f050ed19.png)

**Comment by mattgogerly** [comment]
Looks like this is just updating the base image in the Dockerfile from bionic to jammy?

**Comment by ashleykleynhans** [comment]
> Looks like this is just updating the base image in the Dockerfile from `bionic` to `jammy`?

Yes, it would be better to upgrade to the 22.04 LTS release than the 21.04 release that the person who logged the issue is requesting.

**Comment by ashleykleynhans** [comment]
> Would absolutely welcome PRs to https://github.com/spinnaker/clouddriver/blob/master/Dockerfile.ubuntu ;) to fix some of these. I wonder if the slim version might be better in this case?

Not for Halyard though.  It does not support Alpine.  Only supports Debian or Ubuntu.

**Comment by aman-agrawal** [comment]
I can see jammy in clouddriver, gate, deck.
But other services still use bionic. Are we not upgrading for other services ?

**Comment by jasonmcintosh** [comment]
Related a bit to https://github.com/spinnaker/spinnaker/issues/6794 - needing to update all the images really....

**Comment by ashleykleynhans** [comment]
> Related a bit to #6794 - needing to update all the images really....

Yeah, they should all be updated to `noble` (24.04 LTS), `jammy` (22.04 LTS) is not the latest anymore.

**Comment by jasonmcintosh** [comment]
Everything is on Jammy with 1.36.  We can look at upgrading to noble on 1.37 or 1.38.... jammy should be good for now!
