### ISSUE TITLE
[Kayenta] Signalfx canary account configuration appears broken in 1.30.0

### ISSUE THREAD

**Issue by robert-blackman** [spinnaker/spinnaker#6826]
### Issue Summary:

Hi, we are currently using multiple metric stores for canary analysis (datadog/signalfx), we noticed that once moving to `1.30.0` the option to select the `Metric Store` in the UI is missing and any previously configured `signalfx` configurations report as invalid.   

This isn't a major issue for us as we update the configs using the API (via spin-cli) and functionally the configurations work correctly.

### Cloud Provider(s): 
AWS

### Environment:
We are running Spinnaker `1.30.0` on EKS `v1.24+` deployed with Halyard `1.51.0`

### Feature Area: 
Kayenta/Canary Analysis

### Description:

Expected Behaviour: Canary config can be created using the Signalfx metric store

![Screen Shot 2023-04-11 at 4 54 40 pm](https://user-images.githubusercontent.com/57333677/231107893-a9dbc227-bab3-40d2-b51f-c7c7ffef465a.png)

Actual Behaviour: Config that uses the Signalfx metric store reports as invalid. (missing accounts)

![Screen Shot 2023-04-11 at 4 58 30 pm](https://user-images.githubusercontent.com/57333677/231108444-e61972ca-ce12-427b-813b-c27792e59981.png)

![Screen Shot 2023-04-11 at 4 59 14 pm](https://user-images.githubusercontent.com/57333677/231108538-5494d168-c769-4999-a095-49df19d0961f.png)

### Steps to Reproduce:

On Spinnaker `1.30.0`:
1. Setup the Signalfx service integration with a `METRIC_STORE` account
2. Create a new config (in the UI) selecting the Signalfx metric store (or as default)
3. Attempt to save the config

### Additional Details

also present in `1.30.1`
reverting to `1.29.4` fixes the issue

Thanks!

**Comment by jasonmcintosh** [comment]
I THINK this is tied to some refactoring on going.  Can you share logs please?  Any additional data?  There's an attempt to "cleanup" the codebase and refactor all of this down.  Integration tests had passed, but sounds like we missed some aspects of config :(

**Comment by robert-blackman** [comment]
hey @jasonmcintosh, happy to provide any further details. Attempting to debug this, I naively enabled `DEBUG` on `com.netflix.kayenta` though didn't see anything of interest in our test instance 🤔 should I be looking elsewhere?

**Comment by jasonmcintosh** [comment]
FYI can get more details in slack if it'd help to discuss!

**Comment by jasonmcintosh** [comment]
https://github.com/spinnaker/kayenta/pull/957 should resolve this one.
