### ISSUE TITLE
[FEATURE] Support helmfile as render engine in Spinnaker

### ISSUE THREAD

**Issue by thameezb** [spinnaker/spinnaker#6837]
### Issue Summary:

This is a proposal to add support for [helmfile](https://helmfile.readthedocs.io/en/latest/) as a "Render Engine" in the "Bake (Manifest)" stage.

Spinnaker surfaces a "Bake (Manifest)" stage to turn templates into manifests with the help of a templating engine. Currently, the supported templating engine is Helm and Kustomize. We propose adding support for helmfile as an alternative templating engine.

### Cloud Provider(s):
Kubernetes 1.9+

### Environment:
Baking Kubernetes manifests using helmfile.

### Feature Area:
"Bake (Manifest)" stage
Rosco
Deck (depending on UI implementation)

### Description:
Helmfile is a declarative spec for deploying helm charts. It allows one to maintain a single file which lists various helm-chart deployment spec and config. With many users utilizing it for config management, including helmfile into Spinnaker as a first class templating engine for the "Bake (Manifest)" stage would enable a wide variety of use cases, and simplify pipelines for anyone not wanting to use Helm/Kustomize for templating.

One of the primary features this allows is to _keep a directory of chart value files and maintain changes in version control_. 
This is a specific feature Spinnaker would benefit from when baking k8s manifests.

Currently if a Spinnaker "Bake (Manifest)" stage has multiple helm value files, each file needs to be added as an "Override" as a "Value Artifact". 
If a developer needs to edit the value files used in a given deployment, it requires a change to the actual pipeline code, which creates a negative experience. 
Additionally If account a or region b requires a different set of values, a generic parameterised pipeline is no longer an option. 
This scales negatively as the amount of value files scale.

Supporting helmchart as a render engine would very closely follow the design of the current HELM implementation in "Bake (Manifest)", surfacing new helmfile specific options in addition to the existing helm options (as to avoid upgrades for each iteration of helm, the helmfile executable delegates to helm)

### Steps to Reproduce:
n/a

### Additional Details:
Issue description based on https://github.com/spinnaker/spinnaker/issues/4703

**Comment by mazzy89** [comment]
@dbyron-sf would you mind to take a look at this please?

**Comment by link108** [comment]
Hi @thameezb, thank you for the contributions! I took a look at helmfile, it sounds like some companies are using it in production, however its hasn't released a 1.0 version yet, and may have some breaking changes when that version is released. I think we have a couple options with this:
1. Adding it to the main Spinnaker codebase behind a feature flag, removing the feature flag once helmfile has made a 1.0 release. 
2. Add this feature as a plugin. See https://github.com/spinnaker-plugins/ for some official plugins, as well as https://github.com/spinnaker-plugin-examples/ for some examples. 

At the moment, I'm leaning more towards the latter option, as it would be difficult to modify / remove if the feature doesn't gain much traction. I'm happy to share some resources if you're interested building a plugin

**Comment by mazzy89** [comment]
Thanks @link108 for getting back to us providing guidance.

Yes indeed it is used by several companies. If we have a look at the kubernetes slack workspace, you might found plenty of discussions about it.

Looking at your recommended options we would like to lean towards the first one. Let me provide some explanation. 

After speaking with Thameez, we think that writing a plugin would take a lot more time. Writing a maintaining a plugin has high costs. Few of the services interested do not have Extension Point and this would put us to write a raw spring boot plugin with higher maintenance costs.

Of course please feel free to say whether our ideas are not in line with the current Spinnaker community. 

Also let me add that we as a company are pretty sold to invest into Spinnaker. We would not hit-and-run on this feature but we are offering here our time to mantain this feature for the foreseeable future.

**Comment by thameezb** [comment]
> Hi @thameezb, thank you for the contributions! I took a look at helmfile, it sounds like some companies are using it in production, however its hasn't released a 1.0 version yet, and may have some breaking changes when that version is released. I think we have a couple options with this:
> 
> 1. Adding it to the main Spinnaker codebase behind a feature flag, removing the feature flag once helmfile has made a 1.0 release.
> 2. Add this feature as a plugin. See https://github.com/spinnaker-plugins/ for some official plugins, as well as https://github.com/spinnaker-plugin-examples/ for some examples.
> 
> At the moment, I'm leaning more towards the latter option, as it would be difficult to modify / remove if the feature doesn't gain much traction. I'm happy to share some resources if you're interested building a plugin

Hey @link108 thanks for the response, very much appreciate the comments and guidance.

To build upon the points @mazzy89 has already touched on:

- yes whilst helmfile has not yet published a `v1`, for all intents and purposes the current version is generally considered to be stable by the community as it has not changed in the last 2 years or so since inception (and being a golang wrapper application, it really does not need to). Many of its largest users (can be found [here](https://helmfile.readthedocs.io/en/latest/users/)) use helmfile in production as the primary manner to deploy more complex helm charts using CD tools. 
- integrating helmfile directly into spinnaker would be the preferred approach IMO (I have no opposition to having it behind a feature flag) as writing and maintaining a full on raw springboot plugin would change the maintainability calculus quite a bit 
- if we are able to get helmfile added into Spinnaker, DC would be utilising helmfile as our preferred baking engine within Spinnaker for all of our deployments (for every team in every environment). This would mean that we would be heavily reliant upon the feature working simply, optimally, consistently, and reliably. Therefore we would be almost dogfooding the feature, and would by extension ensure that it always upto date and in tiptop shape

**Comment by thameezb** [comment]
> Adding the code directly to spinnaker could be OK, but even with a feature flag, there are some drawbacks. The rosco executable now contains an additional binary, which makes it bigger, and exposes it to more security vulnerabilities. I'm not sure how many of those there are today, or that we'll find over time.
> 
> Are you using the PRs you've submitted internally already?

@dbyron-sf thanks for the response. I will attempt to respond to your comments point-by-point

>  which makes it bigger

this is undeniably true (however it has a relatively small footprint)

>  exposes it to more security vulnerabilities

I will perform a verification of this using our internal security tool against the built image and present the results.
Additionally Is there a specific image scan tool that spinnaker-team prefers to utilise? If so, I can run an additional scan using the specified tool (if it is open-source/public)

> Are you using the PRs you've submitted internally already?

Not in a real-world state just yet. However I have coded up a set of e2e tests locally (encompassing my changes to rosco, deck and orca) to verify that various bits of helmfile functionality works as expected (this includes features we use internally, and most of the standard features helmfile offers). 

The tests in a nutshell
```
Tests:
- helmfile definition as a custom artifact 
- helmfile definition which points to a remote chart repo and chart 
- namespace flag works 
- overrides key-value works
- overrides artifacts work
- includeCRDs works
- environment flag works (and can reference other files in the repo)
- helmfile as repo artifact
  - no helmfilePath works
  - helmfilePath specified works
  - works for internal charts without any values
  - works for internal charts referencing value files in the repo
  - works for internal charts with environments configured 
  - works for internal charts with crds configured 
  - works for internal charts with multiple values files configured works
  - works for internal charts with override artifacts
```

The repo (with a spinnaker pipeline) can be found -> https://github.com/thameezb/test-spinnaker-helmfile

If there is a better way to e2e test this, please let me know

**Comment by thameezb** [comment]
> The best way to test this is to actually use it in real-life spinnaker installations. Doing this before PRs merge does mean building your own docker images, etc. but it's often something companies end up doing for one reason or another eventually.

Apologies for my ignorance, what would the aim of testing this in our live cluster be? (Would it be to verify that the feature is working as expected and we have not borked any other functionality/caused regressions?) 

If the first, I think I've covered it in my testing above. 
To expand upon my e2e testing methodology a bit. I've run the entirety of Spinnaker locally. And then created 8 Spinnaker stages each testing aspects of helmfile resulting in actual baked (and deployed) manifests into a test k8s cluster (including the various types of deployments we would like to utilize the helmfile feature for). 

As helmfile is not currently supported by Spinnaker, beyond demo bakes and deployments (as completed above), should I be testing anything else specifically?

**Comment by thameezb** [comment]
Circling back to the vulns. 

Whilst I cannot speak to future vulns, currently `helmfile` adds no critical vulns. Going through the current modules it relies on, the list if fairly standard and small. Additionally the type of work that helmfile does (primarily yaml parsing, layering, formatting) should result in a fairly safe binary to add to the docker image.

Scans were performed using [trivy](https://github.com/aquasecurity/trivy). For the sake of completion I ran the scan against the latest version of stable rosco (both alpine and ubuntu) and then did the same with the proposed dockerfile (which includes helmfile)

Scan reports can be found [here](https://github.com/thameezb/rosco/tree/tmp/trivyScans/scan_results).

**Comment by thameezb** [comment]
An update regarding live-running the changes.

It has been live for the past four days. We have not noticed any issues regarding slow-downs, increased resource-usage, crashes, or abnormal errors. 
I have run pipelines using the helmfile feature to ensure that it is invoked and ensure that it does not have any side-effects.
Admittedly at our current usage of Spinnaker we would not be able fully stress-test it or the feature, however we are quite confident in the stability and reliability (and usefulness of this feature). 

Please do let me know what else can be done to get the ball moving on this again (and if there are any other ways to foster confidence in DC's - and by extension my - commitment to supporting this feature, please do let me know)

**Comment by dbyron-sf** [comment]
Thanks for doing this.  I have one more request and then I'm OK with merging this.  Would you document this at https://spinnaker.io/?  I'm not 100% sure of the correct place.  Something like https://spinnaker.io/docs/guides/user/kubernetes-v2/kustomize-manifests/ seems good, but then so does https://spinnaker.io/docs/guides/user/kubernetes-v2/deploy-helm/.  Not sure a whole separate guide makes sense for helmfile, but at least a mention there.

**Comment by dbyron-sf** [comment]
BTW, the source for the website is at https://github.com/spinnaker/spinnaker.io.

**Comment by thameezb** [comment]
> Thanks for doing this. I have one more request and then I'm OK with merging this. Would you document this at https://spinnaker.io/? I'm not 100% sure of the correct place. Something like https://spinnaker.io/docs/guides/user/kubernetes-v2/kustomize-manifests/ seems good, but then so does https://spinnaker.io/docs/guides/user/kubernetes-v2/deploy-helm/. Not sure a whole separate guide makes sense for helmfile, but at least a mention there.

Awesome

Had created a PR 
https://github.com/spinnaker/spinnaker.io/pull/349/files

**Comment by mazzy89** [comment]
@dbyron-sf documentation is now available. are you going the champion to review that and all the PRs around?

**Comment by mazzy89** [comment]
Thanks a lot @dbyron-sf for your time. I'm going to make the required changes tomorrow.

**Comment by thameezb** [comment]
Big ups to @dbyron-sf @jasonmcintosh @ovidiupopa07 @mazzy89 for helping to get this over the finishline. 

Last PR is for Docs when anyone has a minute https://github.com/spinnaker/spinnaker.io/pull/349/files

**Comment by thameezb** [comment]
Set to release in v1.32

Once again big thanks to all
