### ISSUE TITLE
Stuck on 'Promote Outputs` Task on Deploy Stage

### ISSUE THREAD

**Issue by HenryChan309** [spinnaker/spinnaker#6844]
### Issue Summary:
Spinnaker gets stuck on the `Promote Outputs` Task during the Deploy K8s stage.

### Cloud Provider(s):
EKS on AWS

### Environment:
1.26.7

### Feature Area:
Unsure, likely orca.

### Description:
Spinnaker hangs during the deploy stage, and is stuck on the `Promote Outputs` task.

### Steps to Reproduce:
This is occurring on all Spinnaker deploys.

### Additional Details:
In our pipeline, we have a stage to Deploy to Staging first, and then Deploy to Prod. There is no issue with deploying to staging, but when it gets to Deploy to Prod, there is an issue with Promote Outputs task. When we individually deploy to Prod, there is no issue with the deploy hanging.

---

**Comment by mattgogerly** [comment]
Are you using MySQL as a backend for Orca? If the execution context is particularly large (i.e. with two deploy steps deploying many manifests) then the `max_packet_size` on the database could be hit, which seems to silently fail.

Workaround is to increase `max_packet_size` on the database.

**Comment by HenryChan309** [comment]
Thanks @mattgogerly ! Wound up increasing the `max_allowed_packet` parameter on the MySQL backend, and it fixed the issue
