### ISSUE TITLE
Allow Jenkins stage to continue on failed builds

### ISSUE THREAD

**Issue by AMeng** [spinnaker/spinnaker#685]
There is a nice option in the `Check Precondition` stage to enable/disable "Fail Pipeline". See screenshot:

![image](https://cloud.githubusercontent.com/assets/192336/12405632/2acfa698-be03-11e5-9f54-0a7dfbbc4239.png)

It would be nice to have this same feature on the `Jenkins` stage. This would allow users to run a different step based on the results of the Jenkins job. For example, I may want to scale down an ASG if my integration tests (which I run on Jenkins) fail.

**Comment by tomaslin** [comment]
we added this flag to the jenkins stage. However, be aware that the behaviour is that the current executing branch will be marked as stopped and subsequent pipeline stages will not continue running.

**Comment by AMeng** [comment]
I'm not sure I understand the use case if it stops the pipeline. Are you saying other branches in the pipeline will continue to execute?

**Comment by tomaslin** [comment]
in-progress branches will continue but it won't start new stages, AFAIK.

**Comment by tomaslin** [comment]
So the way to do what you're asking for right now is to set a pipeline trigger and fire it on failure of the pipeline containing the integration test.

I think the behavior to not stop the jenkins stage on failure is slightly different than in the precondition stages. Feels like it is two things:

(a) fail pipeline if jenkins job fails
(b) stop running pipeline when jenkins job fails

If feels like (b) in this case should be configurable

**Comment by peterpd** [comment]
we'd like to work on this issue.

Are the followings in the right direction?

1.	For Jenkins stage, add a new flag: Stop Pipeline. 
        By default, it is checked, as that is the current behavior.
2.	If Stop Pipeline is unchecked, pipeline execution will continue, even if Jenkins stage fails

Any thought about how Fail Pipeline and Stop Pipeline should be used together?

thanks,
peter

**Comment by tomaslin** [comment]
@peterpd there might be a nontrivial amount of work to ensure that the subflows of a pipeline that has been stopped executes correctly. @ajordens or @robfletcher might want to chime in here.

**Comment by peterpd** [comment]
Should we define a new ExecutionStatus, for example, FAILED_CONTINUE?
Current logic is to execute next stage only if current stage SUCCEEDED
That logic probably needs change to support the new status as well.

thanks
peter

**Comment by peterpd** [comment]
Seeking comments on the mockup
![jenkins_stage_stop_pipeline](https://cloud.githubusercontent.com/assets/17052513/13996993/3c23a850-f0ed-11e5-9832-66c507bc87f4.png)

**Comment by robfletcher** [comment]
So this is not about executing a different downstream action when the stage fails, it's just to allow the next stage to continue?

**Comment by peterpd** [comment]
the logic of next stage can decide what action to take. a simple example is manual judgement as next stage. more complex example is checking stage context then decide what action to take.
@robfletcher could you give some advanced examples?

**Comment by robfletcher** [comment]
Do you mean that if Jenkins stage A succeeds then stage B runs, otherwise stage C runs?

**Comment by peterpd** [comment]
Right, suppose both B and C are immediate next stages of A.
Not sure how much it involves to provide following:
if Jenkins stage A succeeds then stage B runs, otherwise stage C runs

**Comment by robfletcher** [comment]
Right now Spinnaker doesn't support that kind of conditional workflow although it's something that's always been on our roadmap. I think if that's what you want it's a good deal bigger than just adding the ability to ignore failures in the Jenkins stage.

**Comment by bfarrell** [comment]
If the jenkins stage was just updated to continue on fail, couldnt a check precondition stage be used to handle this conditional workflow?  The context of that that stage would just have to say whether or not the Jenkins job failed, along with the other meta-data.  That would reduce the complexity and utilize existing functionality.

**Comment by robfletcher** [comment]
I see, you're right I think. I'd only seen the check preconditions stage used with manual judgment before but I think this makes sense.

**Comment by gburrell** [comment]
If I had a Jenkins stage with continue-on-fail enabled then I'd branch the pipeline right after the Jenkins stage.  Both branches would start with a Precondition stage.  Branch A would do a Precondition check to see if the Jenkins succeeded.  Branch B would do a Precondition check to see if the Jenkins failed.  The result is that only one branch would get executed.

The precondition expression for the positive branch would be 

${stages.?[name == 'Jenkins'][0].status == 'SUCCEEDED'} 

which is a mouthful.  Is there some way to add a shorthand "previousStage" element so that one could write:

${previousStage.status == 'SUCCEEDED'}

which is a lot clearer to read.

**Comment by peterpd** [comment]
On deck UI, renamed option as "Continue Pipeline". 
Let me know your comments.
see mockup:
![option-to-continue-pipeline-with-failed-jenkins](https://cloud.githubusercontent.com/assets/17052513/14266238/b1fe6ff0-fa7b-11e5-9df8-47ffe088a628.png)

**Comment by peterpd** [comment]
Submitted PR for deck UI changes:
https://github.com/spinnaker/deck/pull/2168

**Comment by peterpd** [comment]
PR for ORCA changes
https://github.com/spinnaker/orca/pull/783

**Comment by peterpd** [comment]
PTAL of the code changes.
thanks,
peter

**Comment by anotherchrisberry** [comment]
This is merged and complete.

**Comment by michaalm** [comment]
@robfletcher wrote: "Do you mean that if Jenkins stage A succeeds then stage B runs, otherwise stage C runs?"

Could you please give an example code snippet of how to use this feature in a Jenkins Pipeline Script?
