### ISSUE TITLE
"Required Artifacts to Bind" is broken since 1.30

### ISSUE THREAD

**Issue by sydorovdmytro** [spinnaker/spinnaker#6850]
### Issue Summary:
"Required Artifacts to Bind" in the Deploy (Manifest) stage is broken since 1.30 (including 1.31). Might be related to the new artifacts handling in 1.30. 

### Cloud Provider(s):
Kubernetes (in our case, not tested with other providers)

### Environment:
spinnaker, 1.30.0, 1.30.1, 1.31.0, AWS EKS 1.25

### Feature Area:
Pipelines

### Description:
We have a "build" pipeline that produces a docker image artifact that is used in the "Deploy (Manifest)" stage of the deployment pipeline. I can select the artifact in the dropdown list of "Required Artifacts to Bind", but the deployment fails with "No artifact with id <artifact name> could be found in the pipeline context."
![broken_config](https://github.com/spinnaker/spinnaker/assets/11457338/4537dd7c-455a-46a5-9444-1eb9ae6bc5fc)
![error](https://github.com/spinnaker/spinnaker/assets/11457338/7557bf16-e6a3-40ba-b4d0-90d66937e040)
![broken_artifacts](https://github.com/spinnaker/spinnaker/assets/11457338/3667a789-bf63-41cf-a9c5-ba31df3bc027)

The JSON of the failing stage:
```
{
  "account": "dmytro-demo",
  "cloudProvider": "kubernetes",
  "completeOtherBranchesThenFail": true,
  "continuePipeline": false,
  "failPipeline": false,
  "manifestArtifactAccount": "embedded-artifact",
  "manifestArtifactId": "demo-kekse-k8s-manifests",
  "moniker": {
    "app": "demo-kekse-k8s"
  },
  "name": "deploy-manifest",
  "notifications": [],
  "requiredArtifactIds": [
    "demo-kekse-k8s-docker-image"
  ],
  "sendNotifications": true,
  "skipExpressionEvaluation": true,
  "source": "artifact",
  "type": "deployManifest"
}
```

Exactly the same pipeline works on Spinnaker 1.29.4.
<img width="569" alt="correct_stage" src="https://github.com/spinnaker/spinnaker/assets/11457338/11b54301-41eb-4b9f-8467-cf7f984c9fee">
<img width="821" alt="correct_artifacts" src="https://github.com/spinnaker/spinnaker/assets/11457338/46ec9389-191a-42e7-8e7b-4d2e3a06b337">

### Steps to Reproduce:
Build a Docker image with another pipeline and try to use it as "Required Artifacts to Bind" in the "Deploy (Manifest)" stage.

**Comment by sydorovdmytro** [comment]
> I suspect this is related to https://spinnaker.io/changelogs/1.30.0-changelog/#artifact-handling?

I think so

**Comment by nemesisOsorio** [comment]
I reproduced the issue using Kustomize and Helm, I'll be working on a fix for this
![image](https://github.com/spinnaker/spinnaker/assets/4973876/30d39f08-84b1-4f9b-80e6-6c13da066dfe)

**Comment by nemesisOsorio** [comment]
You can use `usePriorArtifact` or `useDefaultArtifact` in `expectedArtifacts` in the meantime as a workaround
Example: 
```json
"expectedArtifacts": [
    {
      "displayName": "artifact-docker-image",
      "id": "artifact-docker-image",
      "matchArtifact": {
        "kind": "docker",
        "name": "docker.io/<your-org>/<your-image>",
        "type": "docker/image"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": true
    }
  ]
  ```
But definitely, we need to fix this issue
