### ISSUE TITLE
Rush: Open-ended cassandra call to retrieve all rows in `execution` could fail.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#686]
The call is here: https://github.com/spinnaker/rush/blob/master/src/main/groovy/com/netflix/spinnaker/rush/scripts/ScriptExecutionRepo.groovy#L96

Could use some pagination or at least a `maxNumResults` parameter.

**Comment by ajordens** [comment]
Is this still a thing anymore with `rush` in it's current non-existent state @duftler?

**Comment by duftler** [comment]
Nope.
