### ISSUE TITLE
Igor Java17 Slim Image fails to start

### ISSUE THREAD

**Issue by thameezb** [spinnaker/spinnaker#6881]
### Issue Summary:

Spinnaker Release 1.32.0 shifts Igor to Java 17. Slim version of Igor (`us-docker.pkg.dev/spinnaker-community/docker/igor:4.13.0-dev-master-03c1ace-202309181541-unvalidated `) fails to start. Throws the following error

Related to https://github.com/spinnaker/spinnaker/issues/6879

`
{"@timestamp":"2023-09-19T07:24:02.067+00:00","@version":1,"message":"Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not \"opens java.time\" to unnamed module @453da22c","logger_name":"com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerRetrofitExceptionHandlers","thread_name":"http-nio-0.0.0.0-8088-exec-4","level":"ERROR","level_value":40000,"stack_trace":"com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerServerException: Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not \"opens java.time\" to unnamed module @453da22c\n\tat com.netflix.spinnaker.kork.retrofit.exceptions.SpinnakerRetrofitErrorHandler.handleError(SpinnakerRetrofitErrorHandler.java:66)\n\tat retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)\n\tat jdk.proxy2/jdk.proxy2.$Proxy153.postEvent(Unknown Source)\n\tat com.netflix.spinnaker.igor.health.EchoServiceHealthIndicator.lambda$checkHealth$1(EchoServiceHealthIndicator.java:81)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.allowAnonymous(AuthenticatedRequest.java:137)\n\tat com.netflix.spinnaker.igor.health.EchoServiceHealthIndicator.lambda$checkHealth$2(EchoServiceHealthIndicator.java:81)\n\tat java.base/java.util.Optional.ifPresent(Optional.java:178)\n\tat com.netflix.spinnaker.igor.health.EchoServiceHealthIndicator.checkHealth(EchoServiceHealthIndicator.java:78)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not \"opens java.time\" to unnamed module @453da22c\n\tat java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)\n\tat java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)\n\tat java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)\n\tat java.base/java.lang.reflect.Field.setAccessible(Field.java:172)\n\tat com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)\n\tat com.google.gson.Gson.getAdapter(Gson.java:489)\n\tat com.google.gson.Gson.toJson(Gson.java:727)\n\tat com.google.gson.Gson.toJson(Gson.java:714)\n\tat com.google.gson.Gson.toJson(Gson.java:669)\n\tat com.google.gson.Gson.toJson(Gson.java:649)\n\tat retrofit.converter.GsonConverter.toBody(GsonConverter.java:80)\n\tat retrofit.RequestBuilder.setArguments(RequestBuilder.java:375)\n\tat retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:298)\n\tat retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)\n\t... 18 common frames omitted\n"}
`
Kubernetes on AWS (EKS)

### Steps to Reproduce:

Attempt to run an Igor pod with the specified image version

### Additional Details:

This issue is not present in Java 11 version of the image `us-docker.pkg.dev/spinnaker-community/docker/igor:4.13.0-java11`

**Comment by un-stantane** [comment]
Just want to mention that setting imageVariant: java11-slim does not work as specified in the [changelog](https://spinnaker.io/changelogs/1.32.0-changelog/)

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment$ImageVariant` from String "java11-slim": not one of the values accepted for Enum class: [SLIM, JAVA8, UBUNTU, UBUNTU_JAVA8]
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["deploymentEnvironment"]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment["imageVariant"]
I am using armory/halyard:operator-28d08e6

**Comment by mattgogerly** [comment]
> Just want to mention that setting `imageVariant: java11-slim` does not work as specified in the [changelog](https://spinnaker.io/changelogs/1.32.0-changelog/)
> 
> ```
> com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment$ImageVariant` from String "java11-slim": not one of the values accepted for Enum class: [SLIM, JAVA8, UBUNTU, UBUNTU_JAVA8]
>  at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["deploymentEnvironment"]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment["imageVariant"]
> ```
> 
> I am using `armory/halyard:operator-28d08e6`

Fixed - thanks! You'll need to upgrade Halyard.

**Comment by eeriwan** [comment]
Got the same error on 1.32.1

We upgraded halyard to 1.62.0, and edit halconfig as:
  deploymentEnvironment:
    imageVariant: JAVA11
The igor and front50 pods can start normally with image has a '-java11' suffix. While pods of other services run into ImagePullBackOff status, e.g.,
spin-orca-74bd46967d-rj2r2             0/1     ImagePullBackOff   0          4m43s

It seems the halyard config 'imageVariant' will give '-java11' as suffix for all service images, but there is no such image for services other than igor/fron50.

**Comment by mattgogerly** [comment]
> Got the same error on 1.32.1
> 
> We upgraded halyard to 1.62.0, and edit halconfig as: deploymentEnvironment: imageVariant: JAVA11 The igor and front50 pods can start normally with image has a '-java11' suffix. While pods of other services run into ImagePullBackOff status, e.g., spin-orca-74bd46967d-rj2r2 0/1 ImagePullBackOff 0 4m43s
> 
> It seems the halyard config 'imageVariant' will give '-java11' as suffix for all service images, but there is no such image for services other than igor/fron50.

Hm that sucks. I'm not sure how to fix that, as it's just a side effect of Halyard's weirdness. On 1.33 we should be doing `-java11` images for all services so it should work then.
