### ISSUE TITLE
Images from us-docker.pkg.dev cannot be downloaded

### ISSUE THREAD

**Issue by ohjongsung** [spinnaker/spinnaker#6882]
### Issue Summary:
some image cannot downloaded.
When upgrading settings, previously used images are not pulled.

Fail
```
docker pull us-docker.pkg.dev/spinnaker-community/docker/gate:1.23.0-20220107200021
Error response from daemon: manifest for us-docker.pkg.dev/spinnaker-community/docker/gate:1.23.0-20220107200021 not found: manifest unknown: Failed to fetch "1.23.0-20220107200021"
```

However, images used in the development environment are downloaded.

Success
```
docker pull us-docker.pkg.dev/spinnaker-community/docker/gate:1.22.1-20210603020019
1.22.1-20210603020019: Pulling from spinnaker-community/docker/gate
ddad3d7c1e96: Pull complete
9fd2298321d7: Pull complete
b9f74a34fe5e: Pull complete
6e6b08fdc159: Pull complete
16f8d131041f: Pull complete
9faa4ec9d086: Pull complete
Digest: sha256:3a7e7d93b5842cb7f8a80c4de3a83c9cd13979060b26c5ebdc7be99a97518e86
Status: Downloaded newer image for us-docker.pkg.dev/spinnaker-community/docker/gate:1.22.1-20210603020019
us-docker.pkg.dev/spinnaker-community/docker/gate:1.22.1-20210603020019

```

Fortunately, The pod was moved to the node where the previously downloaded image exists and executed.

### Cloud Provider(s):
private k8s

### Environment:
I'm using images from private k8s to run Spinnaker

**Comment by mattgogerly** [comment]
1.23 is now nearly 3 years old - my guess would be the image was not part of a release (it looks like a nightly build) and was purged as per https://spinnakerteam.slack.com/archives/CKXFWFB53/p1692247922667259.

A quick search of the registry shows images tagged from `1.23.0-slim` to `1.23.7-slim`, so I'd suggest short term switching to an official release version, and long term upgrading to a much newer version.
