### ISSUE TITLE
Automated triggers with artifact constraints are broken if you have 2 or more of the same type

### ISSUE THREAD

**Issue by nemesisOsorio** [spinnaker/spinnaker#6897]
In Orca's master branch for target-release `1.33`, we found that automated triggers with artifact constraints are broken if you have 2 or more triggers of the same type.
For example: create a pipeline with 2 webhooks and add at least 1 artifact constraint
![image](https://github.com/spinnaker/spinnaker/assets/4973876/6d81db6c-085b-4b43-b0f7-2a8393cb1956)
when you trigger one of the webhooks you will get the following error
![image](https://github.com/spinnaker/spinnaker/assets/4973876/c60b22a7-8fe3-48d4-a758-7b9f3e845cef)

pipeline:
```json
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "customKind": true,
        "id": "4341be0f-8394-4838-87b6-6e2dc0bcaedc"
      },
      "displayName": "artifact-001",
      "id": "df8b5f87-10ef-4e06-8d8c-2b8723f8d21c",
      "matchArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "2e26bed0-07c6-4359-ad17-d42c14053846",
        "name": "artifact-001",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": false
    },
    {
      "defaultArtifact": {
        "customKind": true,
        "id": "8b871668-f726-4afc-92f2-7b6f1049c1ba"
      },
      "displayName": "artifact-002",
      "id": "ddb6466b-e8c6-48c4-aa56-0028d09a57f9",
      "matchArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "86e3f4cb-4c3f-4ceb-9018-660730490110",
        "name": "artifact-002",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": false
    }
  ],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "anonymous",
  "limitConcurrent": true,
  "schema": "1",
  "spelEvaluator": "v4",
  "stages": [
    {
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 30
    }
  ],
  "triggers": [
    {
      "enabled": true,
      "expectedArtifactIds": [
        "df8b5f87-10ef-4e06-8d8c-2b8723f8d21c"
      ],
      "source": "test-001",
      "type": "webhook"
    },
    {
      "enabled": true,
      "expectedArtifactIds": [
        "ddb6466b-e8c6-48c4-aa56-0028d09a57f9"
      ],
      "source": "test-002",
      "type": "webhook"
    }
  ],
  "updateTs": "1698089519000"
}
```

Webhook request:
```shell
curl --location 'http://localhost:8084/webhooks/webhook/test-001' \
--header 'Content-Type: application/json' \
--data '{
    "artifacts": [
        {
            "artifactAccount": "embedded-artifact",
            "type": "embedded/base64",
            "name": "artifact-001"
        }
    ]
}'
```

Seems like the issue was introduced in https://github.com/spinnaker/orca/pull/4526

**Comment by xibz** [comment]
Hmm, are we sure it's from that PR? That change was additive, so only more artifacts would be found, not less.

**Comment by nemesisOsorio** [comment]
> Hmm, are we sure it's from that PR? That change was additive, so only more artifacts would be found, not less. One thing Im not too sure on is what the behavior would look like for the two webhooks triggers, but Im pretty sure it'd just append both of the expected artifact IDs, and find whichever artifact that was appropriate. So definitely some unknowns there that we would need to confirm

Yes, it is from that PR, we tested it by removing only your changes and it worked

**Comment by xibz** [comment]
Hmm, that is really unexpected, and I don't see how that even would happen. I'll need to do a little digging

**Comment by xibz** [comment]
Okay, found the bug. Will have a fix soon-ish
