### ISSUE TITLE
Does Spinnaker support AWS Aurora MySQL 3.04?

### ISSUE THREAD

**Issue by DodgeCamaro** [spinnaker/spinnaker#6900]
### Cloud Provider(s):
AWS

**Comment by mattgogerly** [comment]
Should be. Do let us know if you encounter any issues!

**Comment by tonyg4864** [comment]
@DodgeCamaro 
Did you end up getting Spinnaker working with AWS Aurora MySQL 3.0.4 out of the box by any chance ? .. or any later version ?
