### ISSUE TITLE
Allow specifying Packer template file at the baseImage level

### ISSUE THREAD

**Issue by ervansetiawan** [spinnaker/spinnaker#692]
We use packer to create AMIs for our Linux based services and also Windows based ones.  We then use Asgard to deploy them.

Now that the bake and deploy stages are handled by Spinnaker, we are wondering if it is possible to specify Packer template file at the baseImage level in Rosco. That way we can use Packer Windows template file for Windows base images and Linux template for Linux images.

**Comment by duftler** [comment]
There is now support in the Bake Stage ui for specifying a Template File Name. If specified, it will override the template file specified in rosco's configuration.

**Comment by ervansetiawan** [comment]
Tested it locally. Thanks!

**Comment by colutti** [comment]
Where should I store the template file if I want to use it in Spinnaker? Can I have the full path of the template in the Template File Name, like "/templates/windows.json"? Does the template need to be stored at the Spinnaker server?

**Comment by ervansetiawan** [comment]
@colutti you can add your packer file to  /opt/rosco/config/packer

**Comment by colutti** [comment]
Do I have to do something else in order it to work? How will spinnaker know what ami to deploy if I am using my own template? Should I configure any variable or field in the deploy stage?

**Comment by CB-dave-arnold** [comment]
<img width="326" alt="screen shot 2016-12-19 at 4 24 21 pm" src="https://cloud.githubusercontent.com/assets/22603776/21333894/0983a72e-c608-11e6-8994-b318cb31c32f.png">

`
stat /opt/rosco/config/packer/AdserverCallbacks.json 
  File: ‘/opt/rosco/config/packer/AdserverCallbacks.json’
  Size: 1700      	Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 272789      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-12-20 00:01:57.828940568 +0000
Modify: 2016-12-20 00:01:57.828940568 +0000
Change: 2016-12-20 00:26:23.912940568 +0000
 Birth: -`
