### ISSUE TITLE
Failed to start clouddriver

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6935]
### Issue Summary:
It failed to start clouddriver and threw below error message after deployed successfully. After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/clouddriver/pull/6172. Could you fix it asap since we're blocked now. Thanks.

### Cloud Provider(s):
Azure

### Environment:
ubuntu 18.04

### Feature Area:
Clouddriver

### Error Message:
```
2024-03-14 01:10:31.399  INFO 23857 --- [onPool-worker-5] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for 
scopes [https://management.core.windows.net//.default]: SUCCESS
2024-03-14 01:10:31.399  INFO 23857 --- [onPool-worker-5] c.a.c.implementation.AccessTokenCache    : Acquired a new access token.
2024-03-14 01:10:32.069  WARN 23857 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context ini
tialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'az
ureLoadBalancerProvider': Unsatisfied dependency expressed through field 'azureLoadBalancerProvider'; nested exception is org.springframework
.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'azureLoadBalancerProvider': Requested bean is currently in cr
eation: Is there an unresolvable circular reference?
2024-03-14 01:10:32.073  INFO 23857 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-14 01:10:32.101  INFO 23857 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-03-14 01:10:32.141 ERROR 23857 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  azureLoadBalancerProvider (field private com.netflix.spinnaker.clouddriver.azure.resources.loadbalancer.view.AzureLoadBalancerProvider com
.netflix.spinnaker.clouddriver.azure.resources.loadbalancer.view.AzureLoadBalancerProvider.azureLoadBalancerProvider)
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle be
tween beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

### Steps to Reproduce:
hal config version edit --version branch:upstream/master
hal deploy apply
It failed to start clouddriver.

**Comment by neil-yechenwei** [comment]
Hi @j-sandy & @dbyron-sf , seems above blocking issue is caused by your change. Could you take a look this blocking issue? Thanks.

**Comment by emmanuelstroem** [comment]
We're facing the same issue:

**Cloud Provider(s):**
GCP

**Environment:**
GKE - cos_containerd

**Feature Area:**
Clouddriver

**Comment by emmanuelstroem** [comment]
The comments in this issue solved the problem for us: https://github.com/spinnaker/spinnaker/issues/6859

**Comment by neil-yechenwei** [comment]
It's a workaround. It's not a bug fix.

**Comment by neil-yechenwei** [comment]
Hi @j-sandy & @dbyron-sf , Could you fix this blocking issue since it has blocked many users? Thanks.

**Comment by neil-yechenwei** [comment]
Hi @j-sandy & @dbyron-sf , kindly ping. Could you fix this blocking issue since we're blocked for a long time? Thanks.

**Comment by j-sandy** [comment]
In the above given commit kork has been upgraded to bring Spring boot 2.6.15 and Spring Cloud 2021.0.8, and along with it upgraded the required version of jgit package.
The new feature "circular reference prohibition" is introduced in [Spring Boot 2.6.x](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default), that discourages and prohibits the circular references by default.
The issue reported above is related to the coding done that introduced the scope for circular reference, but till now it was being managed by the Spring boot.
In the absence of test coverage for this scenario, issue passed unnoticed.
@neil-yechenwei Could you add a test coverage for Azure startup ?

**Comment by neil-yechenwei** [comment]
@j-sandy , Sorry. We don't contribute code for this project for a long time so that we're not equipped to contribute code for this issue. But our customer is still using Spinnaker. So we would regularly run the basic E2E test case which we built previously in our internal environment for the basic scenario of Spinnaker to ensure that there is no blocking issue on Spinnaker. May I ask if there is any ETA for the bug fix? Thanks.
