### ISSUE TITLE
Clouddriver Debian Package for Spinnaker 1.35.0 fails

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6969]
### Issue Summary:

The Clouddriver debian package installation for Spinnaker 1.35.0 fails during the post installation script execution.

### Cloud Provider(s):

* AWS
* GCP

### Environment:

* Ubuntu 24.04 LTS single server
* Upgrading from Spinnaker 1.34.3

### Feature Area:

* Clouddriver

### Description:

Installation failed with the following error:

```bash
You can now run: /usr/local/bin/aws --version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: aws-iam-authenticator
dpkg: error processing package spinnaker-clouddriver (--configure):
 installed spinnaker-clouddriver package post-installation script subprocess returned error exit status 6
Errors were encountered while processing:
 spinnaker-clouddriver
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
! ERROR Error encountered running script. See above output for more
  details.
  ```

### Steps to Reproduce:

Upgrade Spinnaker from version 1.34.3 to 1.35.0 on a standalone Ubuntu machine.

**Comment by dbyron-sf** [comment]
I've released [Spinnaker 1.35.1](https://spinnaker.io/changelogs/1.35.1-changelog/).  Please confirm whether it fixes this issue.
