### ISSUE TITLE
Only None (EC2 Classic) is shown when creating new Load Balancer

### ISSUE THREAD

**Issue by teewhey** [spinnaker/spinnaker#697]
My set up is based on the docs at http://spinnaker.io/documentation/getting_started.html.

When I wanted to create a new load balancer, somehow only 2 lines are shown:
- None (EC2 Classic)
- <<Blank Line>>

<img width="590" alt="screen shot 2016-01-22 at 3 44 12 pm" src="https://cloud.githubusercontent.com/assets/4113595/12505154/4595b714-c11f-11e5-93bb-10fd08c171cf.png">

Anything wrong in my set up?

**Comment by nicolasgramlich** [comment]
Most likely you didn't follow the naming conventions 100%.

If your vpc is named `default`, then your subnets should be `default.external.us-west-1a`, etc...
