### ISSUE TITLE
Allow AWS loadbalancing scheme to be selected

### ISSUE THREAD

**Issue by cfieber** [spinnaker/spinnaker#698]
Currently the scheme is inferred by the subnet name containing 'internal' ( see https://github.com/spinnaker/clouddriver/blame/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy#L214 )

It would be better if the subnet configuration had something (a tag perhaps) that specified the default value and the UI presented the option to select internal vs external when creating an ELB

**Comment by ajaijoy** [comment]
@cfieber  I fixed this. Should be mark it as fixed/ closed?
