### ISSUE TITLE
Deck, is it possible to set color for provider AWS accounts? 

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [spinnaker/spinnaker#6989]
### Issue Summary:
Currently if we have multiple AWS accounts configured on Clouddriver, it looks like only the primary account is showing red background color while the other accounts are set grey
![Screenshot 2024-10-18 at 6 08 07 PM](https://github.com/user-attachments/assets/836d258c-2beb-4d11-8158-4dc8b36a2c30)

I tried to tackle down what is triggering this color change and it looks like Deck is checking the `accountType` field from the AWS provider account. https://github.com/spinnaker/deck/blob/14977d16c8b3c31d7c54ae9691cb340fcb2c0631/packages/core/src/account/collapsibleAccountTag.directive.html#L2

However I tried to add field `accountType` to my CloudDriver AWS account configuration and the color remains unchanged

I am wondering if there is anyway we can enable the red background color for multiple AWS accounts
### Cloud Provider(s):
AWS

### Environment:
all

### Feature Area:
Deck

**Comment by jasonmcintosh** [comment]
accountType is NORMALLY set automatically in the API return types.   I'd DOUBT this is tied to the account type...

**Comment by CharmanderJieniJieni** [comment]
Found this to be controlled by `challengeDestructiveActionsEnvironments` field.
