### ISSUE TITLE
Anyone aware of integration of azure as Rbac for spinnaker ?

### ISSUE THREAD

**Issue by sai-srikarms** [spinnaker/spinnaker#6995]
### Issue Summary:
Does spinnaker support azure for rbac 
if yes how can we integrate it , documentation didn't help much

**Comment by jasonmcintosh** [comment]
Docs are available using oauth.  Depends on exactly what you're trying to figure out.  For questions & help, please join the spinnaker slack & ask for help there - these are for bug reports & errors.
