### ISSUE TITLE
Will spinnaker support CD on kubernetes?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#707]
I look into the codes of spinnaker, and found there are some codes about kubernetes, so I ask this question. And does it mean spinnaker support kubernetes to support deploying on docker?

**Comment by rbuskens** [comment]
Yes, Spinnaker will support continuous delivery of docker containers on Kubernetes. We are adding this support now, and hope to have something available by the end of this quarter.

**Comment by lwander** [comment]
Hey @feihujiang, I'm adding Kubernetes support. As @rbuskens said this will hopefully be in by the end of the quarter. 

Kubernetes schedules docker containers, so you'll be able to deploy your docker images (from Dockerhub, Google Container Registry, a private registry, etc...) to a Kubernetes container cluster running anywhere (Google Container Engine, EC2, or in your own server room).

**Comment by feihujiang** [comment]
:+1: Thanks, I got it. I've joined kubernetes community, :)  looking forward to spinnaker supporting kubernetes.

**Comment by tomaslin** [comment]
I'm closing this issue as it is work in progress and addressed by Google comments

**Comment by feihujiang** [comment]
What's the progress of spinnaker supporting continuous delivery of docker containers on Kubernetes , is it finished now?  Does spinnaker support  continuous delivery of docker containers on kubernetes running anywhere (GCE, AWS, Bare metal etc)?

**Comment by duftler** [comment]
@lwander

**Comment by lwander** [comment]
It's pretty much finished, I'm tidying up bugs this week and adding one last feature. Later this week I plan to have a "getting started" guide for anyone willing to test this knowing it's in Beta.

It will deploy to a Kubernetes cluster running anywhere, as long as you have a valid kubeconfig file for authenticating with that cluster.

**Comment by feihujiang** [comment]
:+1: Great job, thanks!
