### ISSUE TITLE
Set project, zone and network for bake stage

### ISSUE THREAD

**Issue by JorritSalverda** [spinnaker/spinnaker#710]
Similar to be able to set zone for the bake stage (see #709) it would help to set both the project and the network as well. Defaulting to default network and us-central1-f zone can issues, especially if you do not have the default network.

**Comment by duftler** [comment]
I addressed `zone`/`project`/`credentials` in a comment on the referenced issue. I just checked on `network`, and we are not exposing that. I'll add support for that.

**Comment by duftler** [comment]
Closing this as the reference PR addressed the issue.
