### ISSUE TITLE
Server group 'us-east1:codelab-test-v001' does not exist

### ISSUE THREAD

**Issue by JorritSalverda** [spinnaker/spinnaker#712]
I'm running the codelab, but I've extended the zones to deploy to in pipeline Bake & Deploy to Test, stage Deploy, so it deploys to all 4 regions.

When deploying it fails intermittently in various regions with the exception **Server group 'us-east1:codelab-test-v001' does not exist**, where the actual group varies. Restarting the pipeline manually has this happening over and over for all of the regions.

**Comment by skim1420** [comment]
Can you post the JSON of your pipelines? To do so, from the Configure Pipeline screen, click the drop-down on the upper right button "Pipeline Actions", then "Edit as JSON". Thanks.

**Comment by JorritSalverda** [comment]
Below is the Bake & Deploy to Test pipeline config

`{
  "stages": [
    {
      "requisiteStageRefIds": [],
      "refId": "1",
      "type": "bake",
      "name": "Bake",
      "cloudProviderType": "gce",
      "region": "global",
      "user": "[anonymous]",
      "baseOs": "precise",
      "baseLabel": "release",
      "package": "hello-karyon-rxnetty"
    },
    {
      "requisiteStageRefIds": [
        "1"
      ],
      "refId": "2",
      "type": "deploy",
      "name": "Deploy",
      "clusters": [
        {
          "application": "codelab",
          "zone": "europe-west1-b",
          "network": "default",
          "strategy": "",
          "capacity": {
            "min": 1,
            "max": 1,
            "desired": 1
          },
          "instanceMetadata": {
            "load-balancer-names": "codelab-test"
          },
          "tags": [],
          "preemptible": false,
          "automaticRestart": true,
          "onHostMaintenance": "MIGRATE",
          "authScopes": [
            "cloud.useraccounts.readonly",
            "devstorage.read_only",
            "logging.write",
            "monitoring.write"
          ],
          "cloudProvider": "gce",
          "availabilityZones": {
            "europe-west1": [
              "europe-west1-b"
            ]
          },
          "securityGroups": [],
          "stack": "test",
          "loadBalancers": [
            "codelab-test"
          ],
          "instanceType": "f1-micro",
          "disks": [
            {
              "type": "pd-ssd",
              "sizeGb": 10
            }
          ],
          "targetSize": 1,
          "provider": "gce",
          "account": "my-google-account"
        },
        {
          "application": "codelab",
          "zone": "asia-east1-b",
          "network": "default",
          "strategy": "",
          "capacity": {
            "min": 1,
            "max": 1,
            "desired": 1
          },
          "instanceMetadata": {},
          "tags": [],
          "preemptible": false,
          "automaticRestart": true,
          "onHostMaintenance": "MIGRATE",
          "authScopes": [
            "cloud.useraccounts.readonly",
            "devstorage.read_only",
            "logging.write",
            "monitoring.write"
          ],
          "cloudProvider": "gce",
          "availabilityZones": {
            "asia-east1": [
              "asia-east1-b"
            ]
          },
          "stack": "test",
          "freeFormDetails": "",
          "loadBalancers": [],
          "securityGroups": [],
          "instanceType": "f1-micro",
          "disks": [
            {
              "type": "pd-ssd",
              "sizeGb": 10
            }
          ],
          "targetSize": 1,
          "provider": "gce",
          "account": "my-google-account"
        },
        {
          "application": "codelab",
          "strategy": "",
          "stack": "test",
          "freeFormDetails": "",
          "loadBalancers": [],
          "securityGroups": [],
          "capacity": {
            "min": 1,
            "max": 1,
            "desired": 1
          },
          "zone": "us-central1-c",
          "network": "default",
          "instanceMetadata": {},
          "tags": [],
          "availabilityZones": {
            "us-central1": [
              "us-central1-c"
            ]
          },
          "cloudProvider": "gce",
          "instanceType": "f1-micro",
          "preemptible": false,
          "automaticRestart": true,
          "onHostMaintenance": "MIGRATE",
          "authScopes": [
            "cloud.useraccounts.readonly",
            "devstorage.read_only",
            "logging.write",
            "monitoring.write"
          ],
          "disks": [
            {
              "type": "pd-ssd",
              "sizeGb": 10
            }
          ],
          "targetSize": 1,
          "provider": "gce",
          "account": "my-google-account"
        },
        {
          "application": "codelab",
          "zone": "us-east1-c",
          "network": "default",
          "strategy": "",
          "capacity": {
            "min": 1,
            "max": 1,
            "desired": 1
          },
          "instanceMetadata": {},
          "tags": [],
          "preemptible": false,
          "automaticRestart": true,
          "onHostMaintenance": "MIGRATE",
          "authScopes": [
            "cloud.useraccounts.readonly",
            "devstorage.read_only",
            "logging.write",
            "monitoring.write"
          ],
          "cloudProvider": "gce",
          "availabilityZones": {
            "us-east1": [
              "us-east1-c"
            ]
          },
          "stack": "test",
          "freeFormDetails": "",
          "loadBalancers": [],
          "securityGroups": [],
          "instanceType": "f1-micro",
          "disks": [
            {
              "type": "pd-ssd",
              "sizeGb": 10
            }
          ],
          "targetSize": 1,
          "provider": "gce",
          "account": "my-google-account"
        }
      ]
    },
    {
      "requisiteStageRefIds": [
        "2"
      ],
      "refId": "3",
      "type": "destroyServerGroup",
      "name": "Destroy Server Group",
      "cloudProviderType": "gce",
      "zones": [
        "asia-east1-b",
        "us-east1-c",
        "us-central1-c",
        "europe-west1-b"
      ],
      "cloudProvider": "gce",
      "credentials": "my-google-account",
      "target": "ancestor_asg_dynamic",
      "cluster": "codelab-test"
    }
  ],
  "triggers": [
    {
      "enabled": true,
      "type": "jenkins",
      "master": "jenkins",
      "job": "TestJob2"
    }
  ],
  "limitConcurrent": true,
  "parallel": true
}`

**Comment by skim1420** [comment]
This is a race condition issue due to the resource map cache method we're currently using (in-memory with global locks). We have plans under way to migrate the resource map to a redis cache, which will address this issue. This issue will be triggered by making 2 mutating calls simultaneously (e.g. deploy and monitor). This is an active priority for us.

**Comment by skim1420** [comment]
Just a comment to let you know this is still an active priority for us. There is development under way currently to address this issue among a few other related endeavors.

**Comment by ttomsu** [comment]
Hi - there have been a number of PRs submitted moving the resource map cache into Redis. Currently supported items include:

* Server Groups
* Security Groups
* Clusters
* Applications
* Load Balancers

Still to do:
* Machine Images
* Move Network and Subnet caching agents to extend `AbstractGoogleCachingAgent`

To test what is currently available, change the `providerImpl` from "old" to "new" in https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/config/clouddriver.yml#L119. Better yet, do it in your clouddriver-local.yml file.

Known issues/limitations:
* I'm pretty sure I have some instance health logic flipped around somewhere, because switching between provider implementations, one says all instances are up, the other says they're all down. (working on this today)
* Load balancers do not list server group instances (working on this today, too)

**Comment by ttomsu** [comment]
As for time estimate, I plan to knock out the remaining caching agents by next week, but still have to investigate and implement any and all of the on-demand cache updates (read: any stage that involves a "Force Cache Update" will be affected.) Hopefully that will take less than a week, but the devil is in the details, and I haven't looked into it yet.

**Comment by duftler** [comment]
Closing this as @ttomsu has completed the migration to the redis-backed cache.
