### ISSUE TITLE
FR tags

### ISSUE THREAD

**Issue by gianrubio** [spinnaker/spinnaker#716]
I use tags for [cost allocation ](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html), and i can't find this feature on spinnaker. I can create this feature, but before start this work i need to know if its relevant to this project.

**Comment by ajordens** [comment]
Hi Giancarlo,

What resources are you looking to tag in Spinnaker?

- ASGs
- Load Balancers

Anything else?

We currently have API support for tagging an ASG but nothing exposed in the UI yet ... no support for Load Balancers tho.

**Comment by gianrubio** [comment]
@ajordens currently I only use tags on asg and load balancers. In aws all ec2 instance inherits tags from asg. 

What do you think about this features? It's relevant for the project?

**Comment by ajordens** [comment]
Apologies for the delay @gianrubio.

There is an open PR in spinnaker/clouddriver that provides the ability to specify tags on a server group. 

I suspect that would address half of what you need.

As for tagging load balancers, this isn't something that we actively need here at Netflix but would welcome a community contribution along the lines of the ASG tagging.

Feel free to put together a PR or reach out in Slack if you need additional information.
