### ISSUE TITLE
UserData field in the Deploy stage is not being honored by clouddriver for AWS

### ISSUE THREAD

**Issue by cholin-bmc** [spinnaker/spinnaker#717]
In a pipeline Deploy stage, the optional base64-encoded UserData field is not being honored by the clouddriver service for AWS.

I see that it is saved as part of the pipeline JSON and is sent to orca and clouddriver as the attribute 'base64UserData'. However, clouddriver doesn't deserialize that when converting to a bean object of type BasicAmazonDeployDescription.

I have a fix that adds this missing model attribute.

**Comment by cfieber** [comment]
@cholin-bmc I see this attribute:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/BasicAmazonDeployDescription.groovy#L46

**Comment by cholin-bmc** [comment]
Ah, I was looking at an older version of the code. Thanks for letting me know. I'll close this one.
