### ISSUE TITLE
API description

### ISSUE THREAD

**Issue by dlsniper** [spinnaker/spinnaker#720]
First of thank you for releasing this.

Would it be possible to have all the API calls that the project currently offers, with parameters and response formats and so on?

This would make it a lot more easier to get a grasp of the project. Ultimately my personal goal is to port this to Go, which might never happen if I don't have the time for it, but at least people could understand what happens within the API itself.

**Comment by tomaslin** [comment]
there is a swagger endpoint in gate right now at ( gateUrl / swagger-ui.html ). We don't really do a good job of the parameters being passed in, a big part being that we usually pass in arbitrary objects, but you can look at that to start.

**Comment by rbuskens** [comment]
Hi Florin -

Thanks for attending the meetup in Berlin tonight (and for shepherding me
to my hotel).

I'll add a bit to what Tomás wrote: we do plan to provide full API
documentation on the spinnaker.io site.
Will do our best to get to this as soon as possible. In the meantime,
hopefully Tomás' guidance can get you started. Also, please don't hesitate
to reach out to us on Slack or other avenues if you have questions.

Thanks!
Rick.

**Comment by dlsniper** [comment]
@tomaslin that was fast, thank you. I've tried to search for the file using Githubs interface both in this repo and in https://github.com/spinnaker/gate/ but without luck. I've did found https://github.com/spinnaker/gate/tree/master/gate-manual but it doesn't look updated.

How could one help to document this? How do you see this done / where could this be started from by a new contributor?

@rbuskens happy to hear you've got to the hotel ok. Thank you once again for the whole presentation and the excellent Q&A afterwards.

**Comment by tomaslin** [comment]
it gets ran as a swagger endpoint. So you need to spin up the gate service to see it.

**Comment by tomaslin** [comment]
we are in the process of moving the generated manual so it can be referenced and modified, but we're working out the details

**Comment by tomaslin** [comment]
@dlsniper is this still an issue for you?
