### ISSUE TITLE
Alternative to using plain text password in config files

### ISSUE THREAD

**Issue by jcusa** [spinnaker/spinnaker#722]
Hi, when we configure jenkins in the yml files, we had to put plain text password in there. Is there alternative to using plain text password in the config for this?

**Comment by tomaslin** [comment]
you should really be using jenkins auth tokens

**Comment by jcusa** [comment]
thanks. I used token before and somehow didn't work. it just appeared to work after i switched over to plain password.  I will try again. maybe the error I had was due to something else rather than the token.
