### ISSUE TITLE
How could I develop a custom stage?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#724]
Is there any examples or instructions to follow to develop a custom stage? Does spinnaker have plugin mechanism to develop custom stages? If there is not,  could you give me some advice to get me started? Thanks very much!

**Comment by tomaslin** [comment]
right now to add your own stage, you would need to add a module that registers stages and tasks. Orca bakery is probably a good example to look at as this is pretty self contained - https://github.com/spinnaker/orca/tree/master/orca-bakery . We have it in our roadmap to make the mechanism more extensible so you can create a stage from configuration, but it's not there yet.

**Comment by tomaslin** [comment]
if you don't want to write your own stage, you could use the jenkins stage to call out to your own code.

**Comment by feihujiang** [comment]
Thanks. And one another question, is there any spinnaker roadmap? I didn't find it here. Could you please post them?

**Comment by tomaslin** [comment]
We will publish a roadmap shortly. @aglover is working in finalizing it.

**Comment by tomaslin** [comment]
I'm closing this issue as it contains details that are in progress or planned.

**Comment by yue9944882** [comment]
@tomaslin Any tutorial for developing custom stage can be provided for now?
