### ISSUE TITLE
What’s the difference between spinnaker and AWS CodePipeline?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#747]
Is there any relationship between spinnaker and AWS CodePipeline? Does community do feature Comparison? What are competitive advantages of spinnaker?

**Comment by feihujiang** [comment]
Ping @tomaslin @ajordens :)

**Comment by tomaslin** [comment]
Fundamentally they were developed in isolation as we were not told that CodePipeline was in development until it was released.

CodePipeline is an Amazon product and integrates well with their ecosystem. They have features integration with CodeDeploy and Lambda that Spinnaker does not have but will be added soon. It appears that they also have a deeper integration with the Amazon authentication system based on IAM Roles that Spinnaker does not have.

I think here are a few areas where Spinnaker does better: 

* **Open Source** - you have access to the Spinnaker source code and can enhance to meet your needs. 

* **More robust pipelines** - Spinnaker pipelines allow for expressions, parallel execution, manual judgement and conditional executions, there doesn't seem that level of customization in Code pipelines.

* **Multiple Cloud Providers** - Google Compute Platform, Kubernetes, Cloud Foundry and Azure on top of Amazon Web Services.

* **Application and Project centric views** - Spinnaker lets you group your pipelines around an application and trace the execution of your stages centered around an application. Having the ability to look at your cloud resources around the application is pretty powerful, and I feel we do this better than in the AWS Console.

* **It's a platform** - At the end of the day, we want Spinnaker to handle other type of deployments. We've made some headways around docker images, but the ultimate goal is to also be able to support CDN-type deployments and other approaches.

**Comment by feihujiang** [comment]
Thank you for your detailed reply. One another question, what are CDN-type deployments? CDN is Content Delivery Network,  isn't it?

**Comment by tomaslin** [comment]
yes, the intent is to be able to upload to support deployments to services like Akamai, etc.

**Comment by ajordens** [comment]
Going to close this issue as I believe the question has been answered.

Feel free to reach out on Slack if you need any additional clarification.
