### ISSUE TITLE
Syntax to specify build number to a jenkins stage parameter

### ISSUE THREAD

**Issue by unicman** [spinnaker/spinnaker#749]
I have a trigger set on a jenkins job Jen-A of PROJ-A.

As part of first stage, I would like to trigger another jenkins job, Jen-B, that will work on build N of PROJ-A. So Jen-B has a text build parameter called 'BUILD_NUMBER'.

This starts showing this parameter and text field in the 'add stage' GUI of spinnaker.

What is the syntax to specify build N in that text field so that Jen-B will get triggered with build N of Jen-A selected at the time of 'Start Manual Execution' or automatically when Jen-A build triggers and finishes successfully?

**Comment by tomaslin** [comment]
The syntax should be ${ trigger.buildNumber }. You can see what is available to the trigger by clicking on an execution, show details and then clicking on source.

**Comment by unicman** [comment]
Ok thanks.
