### ISSUE TITLE
Deck operation monitoring times seems to start at 0:34

### ISSUE THREAD

**Issue by ewiseblatt** [spinnaker/spinnaker#752]
When you perform an operation (e.g. creating a load balancer) and it monitors the tasks, it ticks off a time for each one. The running counter in the UI seems to start at 0:34 then increment up. Then when it completes, it seems to subtract back the 34 seconds from the duration it records.

**Comment by anotherchrisberry** [comment]
I have not seen this - wondering if there's a big difference between your local system clock and the clock Orca is running on. When a task is running and doesn't have an end time, we'll calculate the duration based on the start time and the current time, and if there's that much sway between the clocks, it might cause this.

That's my only guess - but that seems like a lot of sway...

**Comment by ewiseblatt** [comment]
The clock ticks upward. It is elapsed time.

**Comment by tomaslin** [comment]
@ewiseblatt are you still seeing this?
