### ISSUE TITLE
Cleanup clouddriver endpoints

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#755]
This will wind up requiring changes between deck, clouddriver, gate, and possibly orca.

Right now, retrieving each resource from clouddriver seems to follow a different pattern. Security groups are retrieved using a `/search` endpoint, load balancers are retrieved using either the generic `/application/{application}/loadBalancers` provider, or the provider specific controllers at `{provider}/loadBalancer` depending on what information is needed. Each provider has their own image lookup controller. Server groups are retrieved using the cluster provider, rather than their own.

Once the kubernetes integration simmers down I'd like to make the resource retrieval more uniform, where each resource type can be found using consistent rules. I'll post more information then.

@duftler @ajordens @cfieber @tomaslin @ttomsu WDYT?

**Comment by duftler** [comment]
Sounds good to me.

Please add /credentials to the list.

**Comment by ttomsu** [comment]
Totally agree on this. @ajordens - Do you have any data on endpoint usage internally? I'd gladly take on this task if I knew what things I could or couldn't delete or provide an alternative for.

**Comment by ajordens** [comment]
I can pull usage from our apache logs internally.

**Comment by ajordens** [comment]
- /credentials is certainly used
- /application/{application}/loadBalancers is certainly used
- /{provider}/loadBalancers/{account}/{region}/{name} is used
- /{provider}/loadBalancers is used (less than the others)

Pulled ^^ from hystrix metrics.

**Comment by ttomsu** [comment]
`/application/{application}/loadBalancers` and `/{provider}/loadBalancers` seem like duplicates to me. Do load balancers outside of an Application context make sense?

**Comment by lwander** [comment]
`/{provider}/loadBalancers` returns all load balancers without needing to know all available applications.

**Comment by anotherchrisberry** [comment]
We use the `/{provider}/loadBalancers` endpoint to ensure names are unique when creating a new load balancer.

**Comment by lwander** [comment]
Closing this until we can better determine scope/implementation path
