### ISSUE TITLE
Allow webhooks to trigger a build

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#759]
We currently use CircleCI for all of our builds, rather than Jenkins, and it would be really nice for Spinnaker pipelines to be triggered by a webhook call once the Circle job has completed. I'm currently going down the path of running a CRON every minute, that leads to a script that polls Circle, but that's pretty undesirable.

**Comment by JohnTheodore** [comment]
@robzienert have you seen this: https://github.com/spinnaker/echo/pull/60 ?

**Comment by tomaslin** [comment]
still need a generic way to say : if this webhook has been triggered, fire off a pipeline

**Comment by bkarakashev** [comment]
@robzienert you can trigger pipeline with curl like that:
`curl -X POST --header "Content-Type: application/json" --header "Accept: */*" -d '{"parameters": {"git_revision": "1.0.343"}}' "http://spinnaker.my.domain/gate/pipelines/<appname>/<pipename>"
`
and in my case I am passing `parameters` which I have setup in the Configuration Stage of the pipeline.

**Comment by imosquera** [comment]
@tomaslin - is @bkarakashev's solution not the generic way of firing off the pipeline? Could you describe a more generic way?

**Comment by bkarakashev** [comment]
@imosquera I would love if spinnaker introduce webhooks but unfortunately there are no webhoos for now.

**Comment by tomaslin** [comment]
there api calls and event webhooks in echo. Right now there is not a generic way to start off pipelines based on a webhook event.

**Comment by willgorman** [comment]
@tomaslin I'm interested in webhook triggered pipelines and just wanted to see if I understood the current state.   Is the UI in deck the only missing component but it might work if the webhook trigger was configured directly in the pipeline json?

**Comment by psyhomb** [comment]
Can someone please explain to me hows possible that we have official documentation for the feature that basically isn't implemented yet?
https://www.spinnaker.io/guides/user/triggers/webhooks/

**Comment by lwander** [comment]
Implemented in Spinnaker 1.6

**Comment by KhadijaAmmar** [comment]
> hod explained by @bkarakashev, it doesn't have to be specifically configured at all, you can still trigger it via g

Does this method still working @bkarakashev ? I didn't managed to trigger the pipeline using curl.
