### ISSUE TITLE
ForceCacheRefresh Timeout Exception after 10 minutes

### ISSUE THREAD

**Issue by shankarapailoor** [spinnaker/spinnaker#761]
Hi,

I am running spinnaker on a m4.xlarge with the ami Spinnaker-Ubuntu-14.04-22. 
I have a pipeline that consists of a bake and deploy phase. The deploy phase always fails after 10 minutes because of an exception. Below is the exception

"Unexpected Task Failure","errors":["Operation timed out after 10 minutes"],"stackTrace":"com.netflix.spinnaker.orca.batch.exceptions.TimeoutException: Operation timed out after 10 minutes\n\tat "

The stage shows forceCacheRefresh","startTime":1456263052610,"endTime":1456263655975,"status":"TERMINAL

I'm looking at the ORCA code at the head, and it seems like it should return success if it times out. 

Any comments would be helpful.

**Comment by ajordens** [comment]
Looks like that AMI is a couple weeks behind `head`.

Perhaps @skorten can slot in some time to publish new AMIs?

**Comment by skorten** [comment]
There's a newer version that the one you're running, Spinnaker-Ubuntu-14.04-23, that was published on February 11.  I've been wanting to get a newer one out for the last week, I'll make some time this afternoon to get that done.

**Comment by shankarapailoor** [comment]
Ok so is this a known issue with the 14.04-22 version?

**Comment by skorten** [comment]
It is not an issue I'm aware of, I was only speaking to the availability of a more recent AMI.  Development is rapid so a lot can change in two weeks.

Looking at your exception I would double check the SG on your cluster and make sure the ELB can connect to it.

Also, there are new community AMIs available under the name "Spinnaker-Ubuntu-14.04-24".

**Comment by shankarapailoor** [comment]
No problem. Thanks!

**Comment by itomaldonado** [comment]
+1 I am also experiencing the same issue and am also using the same AMI `Spinnaker-Ubuntu-14.04-22 (ami-1d230877)` ...

I'll try with the version `Spinnaker-Ubuntu-14.04-24` again now and will report back

**Comment by itomaldonado** [comment]
Yes, it was that, I used `Spinnaker-Ubuntu-14.04-24` and it worked for me.

**Comment by skorten** [comment]
Glad to hear that, @itomaldonado .  Sounds like we can close this issue.

**Comment by itomaldonado** [comment]
I agree @skorten we can. Thanks for the suggestion

**Comment by RyPeck** [comment]
@skorten wasn't going to create a new bug - but I wanted to point out that the list of AMIs on http://www.spinnaker.io/docs/amazon-ami-ids is out of date if there is a -24 available. This issue could have been avoided on our side if this reference was kept up to date.

Is there a place were we can get the list of latest Spinnaker AMIs?

Also - if you are the creator - major thanks for these. Helps everyone experiment quickly!

**Comment by skorten** [comment]
My apologies for the site being out of date.  Currently to get a list of all the Spinnaker AMIs the best way is to got to "AMIs" in the AWS console, select "Public Images" from the drop down and search for "Spinnaker-Ubuntu".  The latest version is currently Spinnaker-Ubuntu-14.04-28, built yesterday.  The list should be automatically updated, I will try and make that happen over the next couple days.

**Comment by RyPeck** [comment]
@skorten couldn't anyone name an image "Spinnaker-Ubuntu-14.04-*"?

Perhaps you could have the Amazon AMI page in the docs be a link to a repo that contains the latest - or the file in the repo that contains the latest - just like Google Cloud Launcher and Current Versions page.

**Comment by skorten** [comment]
@RyPeck yes, they could, I only brought up search as a way to get a list of all the AMIs.  I'm putting something together now to auto publish the official AMIs now as this is definitely an issue.  Thanks for the reminder.
