### ISSUE TITLE
When a spinnaker service, such as rush, is deployed standalone, it does not startup automatically.

### ISSUE THREAD

**Issue by peterpd** [spinnaker/spinnaker#762]
when rush service is deployed standalone, it does not startup automatically,

However, if rush it is deployed together with spinnaker, then spinnaker starts it.

A fix should work for both cases, standalone or together with spinnaker.

Same issue for other services, except deck.

**Comment by ttomsu** [comment]
Also PTAL @dpeterka and @skorten

**Comment by tomaslin** [comment]
@ewiseblatt @dpeterka @skorten is there an update for this?

**Comment by ewiseblatt** [comment]
This was fixed last week.
