### ISSUE TITLE
Where is the total definition of  the JSON that represents the pipeline configuration?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#764]
We know the JSON is used to represents the pipeline configuration. But I couldn't find the total definition of  the JSON that represents the pipeline configuration,  Could you tell me where it is defined?
The JSON  below represents a wait stage, Is this right?
~~~
   {
      "type": "wait",
      "name": "Wait",
      "waitTime": 8
    }, 
~~~

**Comment by duftler** [comment]
It is available here when editing a pipeline: 
![image](https://cloud.githubusercontent.com/assets/8437718/13372721/bf2fae48-dd1e-11e5-97d8-66fa53bed287.png)

**Comment by duftler** [comment]
The same information is available programmatically. You can learn about the available apis via the swagger interface: http://localhost:8084/swagger-ui.html

Note that the host/port above resolves to gate (the api gateway).

**Comment by duftler** [comment]
Hm, reading back I think you may have been asking for a formal definition of the pipeline 'language'?

**Comment by feihujiang** [comment]
Yes, Using Edit as JSON just get an instance, but I want to ask for a formal definition of the JSON that represents the pipeline configuration.

**Comment by duftler** [comment]
At the moment, there isn't a formal definition of the full config language. It is something we've discussed, but it remains unresolved at the moment.

It's a bit of a chore, but you can learn what each attributes each stage type exposes by examining orca and clouddriver (many of the tasks in orca merely pass-thru their payload to clouddriver).

There is a manual exposed by gate as well, but I'd assume it's fairly out-of-date at this point: /gate/gate-manual/build/resources/main/static/manual/index.html

Still, it will give you a rough idea of what each stage config looks like.

**Comment by feihujiang** [comment]
I got it, thanks :)

**Comment by arikkfir** [comment]
Hi everyone - couple of questions on this:
* has anything changed in this space? is there now documentation about the JSON supported by Gate's API?
* is there an open ticket to implement this? this would enable contributors to at least document parts as an on-going PR until we have something that can be merged eventually.

**Comment by dorbin** [comment]
I've created an [issue](https://github.com/spinnaker/spinnaker.github.io/issues/364) for it in the /spinnaker.github.io repo.
