### ISSUE TITLE
How could a custom stage get the information of stages preceding this one?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#765]
When we develop a custom stage, this stage needs information of stages preceding this one, how could this stage get the information? and results of stages preceding this one?

**Comment by duftler** [comment]
The deploy stage makes use of information from either the Find Image stage or the Bake stage. You can dig around here (https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/CreateDeployTask.groovy) to see a call to `withImageFromPrecedingStage()` to learn how this works. There is context available from the stages themselves, and also a 'global' context. This particular stage prefers context from upstream stages (working backwards), and then uses global context if it doesn't find what it needs. I hope this is a good example of what you were looking for.

**Comment by feihujiang** [comment]
Thanks, this is very useful.  :+1:
