### ISSUE TITLE
Unable to start deck for development due to the following error during npm install

### ISSUE THREAD

**Issue by hiradha** [spinnaker/spinnaker#772]
sudo npm install
npm WARN package.json deck@0.0.0 No repository field.
npm WARN package.json deck@0.0.0 No license field.
npm WARN cannot run in wd deck@0.0.0 npm install -g bower@1.4.1 (wd=/Users/rpopuri/spinnakerworkspace/build/deck)
|
> ui-select@0.12.1 postinstall /Users/rpopuri/spinnakerworkspace/build/deck/node_modules/ui-select
> bower install

sh: bower: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ui-select@0.12.1 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ui-select@0.12.1 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the ui-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ui-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rpopuri/spinnakerworkspace/build/deck/npm-debug.log

**Comment by anotherchrisberry** [comment]
Can you try with some slightly older versions of npm and/or node?

Locally, I am running node v4.2.2 and npm 3.7.2

The build script for Deck uses node v0.12.3 and npm 3.6.0

**Comment by tomaslin** [comment]
@hiradha is this still an issue? Have you tried using node 4?

**Comment by hiradha** [comment]
I tried explicitly installing bower first and I think it is not an issue
any more after that.

**Comment by Ragr2018** [comment]
Hi , I am seeing below error for deck - 

 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-dev-server"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error deck@0.0.0 start-dev-server: `webpack-dev-server --progress --mode=development`
22 error Exit status 1
23 error Failed at the deck@0.0.0 start-dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


Can you please advice.
