### ISSUE TITLE
Does spinnaker support authenticate and authorization now?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#774]
Does spinnaker support login for different users now? As we set up a spinnaker instance, we can’t find any login UI, so I want to ask this question.
  If it does, which mode spinnaker uses to authenticate users? client certificates, tokens, or http basic auth? And does spinnaker support authorization? Support ABAC that allows for user-configured authorization policy?

**Comment by feihujiang** [comment]
I found the example in http://www.infoq.com/news/2016/02/netflix-spinnaker, there is a user (chrisb@netflix.com) login.

**Comment by tomaslin** [comment]
Samuel Toriel did a write up on setting up SAML authentication in Spinnaker - http://riltsken.github.io/devops/infrastructure/deploymenttools/2015/12/08/setup-okta-saml-with-spinnaker.html 

Currently, there is no fine grain level authorization, but you can allow or deny permissions based on group memberships. I.e, if I only want members of supersecret to be able to access supersecretAccount, I would add

```
      requiredGroupMembership:
        - supersecret
```

to clouddriver.yml file under the supersecretAccount definition.
