### ISSUE TITLE
no ability to specify base image in bake stage

### ISSUE THREAD

**Issue by skorten** [spinnaker/spinnaker#777]
We are seeing a need for the ability to specify a base image in the bake phase.  This can be done by manually modifying the json but there is no option from within deck.  We would like to add this option into deck but before proceeding wanted to collect comments.  Thanks.

**Comment by duftler** [comment]
This option exists under 'Advanced Options'.

For GCE Bake Stage:
![image](https://cloud.githubusercontent.com/assets/8437718/13582965/04b91688-e47d-11e5-9614-42c6201c4349.png)

And for AWS Bake Stage:
![image](https://cloud.githubusercontent.com/assets/8437718/13582971/0f9efb62-e47d-11e5-8308-be80a721f9bc.png)

**Comment by skorten** [comment]
So it is.  Thanks, @duftler .
