### ISSUE TITLE
Add a "How to create a custom stage type" in the spinnaker.io.github website Developer Guide

### ISSUE THREAD

**Issue by cholin-bmc** [spinnaker/spinnaker#783]
I am working on a section for the Developer Guide in the spinnaker.io.github repo that adds details on how to create a custom stage type in Spinnaker.

I plan on covering:

- Stage base classes: LinearStage, ParallelStage
- A hello world stage example for both LinearStage and ParallelStage
- Deck service additions required (Angular modules, controller, views)
- Orca service additions required (Stage, Task subclasses, accessing context)

Please let me know if these topics makes sense.

**Comment by tomaslin** [comment]
would suggest making a suggestion on spinnaker.readme.io instead

**Comment by cholin-bmc** [comment]
@tomaslin I can't seem to find spinnaker.readme.io. I didn't see a way to add issues on spinnaker.github.io. Is there a way to do this?

**Comment by tomaslin** [comment]
No, this is the place to add issues. We're migrating the content to https://spinnaker.readme.io as spinnaker.github.io is difficult to edit.

**Comment by cholin-bmc** [comment]
Ok I see that now. Thanks. I will sign up and put the suggestion there.

**Comment by tomaslin** [comment]
does this link work for you? https://spinnaker.readme.io/docs/developer-guide

**Comment by cholin-bmc** [comment]
Yes it does. Thanks. But how do I go about submitting my changes for creating a custom stage type?

**Comment by MALATHI02** [comment]
Is there is a step by step guide to create custom orca stage

**Comment by lluu** [comment]
@cholin-bmchttps://spinnaker.readme.io/docs/developer-guide returns a 404.. do you have this info available somewhere else?.  Appreciate the assistance.
