### ISSUE TITLE
deck: AWS "Create Load Balancer" doesn't check if account/region is empty

### ISSUE THREAD

**Issue by vjames-bmc** [spinnaker/spinnaker#791]
The "Create Load Balancer" modal allows to click the "Create" button even if account and region are not selected. The LB creation will fail without these two required values.
The "Create" button should be disabled if account or region is empty.

**Comment by anotherchrisberry** [comment]
Yep, this is a regression - thanks for catching it! Fix is here: https://github.com/spinnaker/deck/pull/2080

**Comment by vjames-bmc** [comment]
Thanks @anotherchrisberry for the quick fix.
