### ISSUE TITLE
AWS application creation fails

### ISSUE THREAD

**Issue by gergelyke** [spinnaker/spinnaker#792]
Hey,

just followed your setup guide, and have the spinnaker UI in front of me opened. When I try to create an app, the account fields are empty:

<img width="483" alt="screen shot 2016-03-12 at 08 07 21" src="https://cloud.githubusercontent.com/assets/2174968/13721487/8043aee4-e829-11e5-8bd0-77075c77011e.png">

Any idea on what went wrong?

**Comment by tomaslin** [comment]
Are you seeing any errors in the logs following the troubleshooting guide? http://spinnaker.io/documentation/troubleshooting.html

**Comment by murarisumit** [comment]
I was also facing the same issue, let's see if it's replicating at your end or not. 
Try overriding values in `spinnaker-local.yml` file in `/opt/spinnaker/config` directory.

**Comment by aioue** [comment]
I was able to fix a similar problem by following the steps here: http://stackoverflow.com/questions/34788034/unable-to-create-an-application-no-accounts-listed-in-dashed-rectangle-beside

**Comment by tomaslin** [comment]
this issue is a few months old. closing.
