### ISSUE TITLE
Does it support CentOs in Bake Process ?

### ISSUE THREAD

**Issue by medyagh** [spinnaker/spinnaker#797]
when I bake something I only have two options ubuntu 12 and 14, what if I want CentOs ?

**Comment by duftler** [comment]
You'll need to configure whatever base image make sense for your deployment in the bakery configuration: https://github.com/spinnaker/rosco/blob/master/rosco-web/config/rosco.yml

Not sure what platform you're on, but you should be able to find `baseImages` in that file for whichever you are on.

Then you'll need to cycle rosco to pick up the changes: http://spinnaker.io/documentation/troubleshooting.html#i-changed-my-configuration-how-do-i-get-spinnaker-to-pick-up-the-modified-configuration

The ui (deck) will dynamically render the Bake Stage with the set of choices you've configured within rosco.

**Comment by medyagh** [comment]
Thanks where is the location of the config file on my spinnaker instance ? I couldn't find it under home/ubuntu or /var/ or /etc/...

**Comment by duftler** [comment]
If you are on a prebuilt spinnaker image, it is likely within /opt/rosco
somewhere.

**Comment by duftler** [comment]
It is `/opt/rosco/config/rosco.yml`.

**Comment by medyagh** [comment]
Thanks, yes I use a prebuild image, do I need to re-build or re-compile after I change the configurations?

**Comment by duftler** [comment]
You should just need to cycle rosco to pick up the config change: http://spinnaker.io/documentation/troubleshooting.html#i-changed-my-configuration-how-do-i-get-spinnaker-to-pick-up-the-modified-configuration

**Comment by duftler** [comment]
Seems like this is resolved. Ok to close this issue?
