### ISSUE TITLE
E-mail notifications in echo don't work when enabled

### ISSUE THREAD

**Issue by cholin-bmc** [spinnaker/spinnaker#798]
E-mail notifications in echo aren't working due to a missing JavaMailSender bean. I have a fix to add back the missing bean so that it properly initializes from the mail configuration of echo.

**Comment by tomaslin** [comment]
do you have mail enabled? javaMailSender should be coming from https://github.com/spinnaker/echo/blob/master/echo-notifications/echo-notifications.gradle#L26

**Comment by cholin-bmc** [comment]
I did have mail.enabled, mail.host. and mail.from configured correctly as it was working on an installed Spinnaker stack from Dec 2015. I saw a change to echo where the groovy class with the JavaMailSender bean was removed and that was consuming the mail.host property. After that change, I no longer saw anywhere in the code where mail.host was being utilized and I kept getting exceptions about JavaMailSender bean not being found when starting up echo with mail enabled. This issue is consistent on the dev stack, deb pkg installed stack, and docker container stack.

**Comment by tomaslin** [comment]
The hierarchy changed based on spring mail. Sorry it wasn't communicated better.

Here is an example of the config:

https://github.com/spinnaker/echo/pull/59

note it's spring.mail and not mail 

but mail.enabled is at the same level

**Comment by cholin-bmc** [comment]
Ah ok. Thanks. Maybe I can submit another PR around updating the default local yamls for default-spinnaker-local.yml and echo.yml in the spinnaker repo under the config directory?

**Comment by cholin-bmc** [comment]
Ah ok. Thanks. Maybe I can submit another PR around updating the default local yamls for default-spinnaker-local.yml and echo.yml in the spinnaker repo under the config directory?

**Comment by tomaslin** [comment]
yeah, that makes sense
