### ISSUE TITLE
docker registry needs to handle pagination for _catalog endpoint

### ISSUE THREAD

**Issue by tomaslin** [spinnaker/spinnaker#800]
@lwander 

Seems that the docker registry will only return 100 items from the registry and further results need to be paginated. https://github.com/docker/distribution/blob/master/registry/handlers/catalog.go#L15

**Comment by lwander** [comment]
Darn... I'll look into it soon.

**Comment by lwander** [comment]
https://github.com/spinnaker/clouddriver/pull/431
