### ISSUE TITLE
Compare spinnaker with Jenkins as a continuous delivery tool

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#803]
As we know, jenkins is a well known open source CI tool. But it also could for continuous delivery,
it has lots of plugin for continuous delivery, like AWS Cloudformation Plugin.
And there is an opensource CD product based on jenkins that is openshift fabric8. 
And there is a commercial CD product based on jenkins that is CLoudBees. 
What are competitive advantages of spinnaker compared to  jenkins (extends jenkins) as a CD tool?

**Comment by tomaslin** [comment]
this question is too vague to be tracked as an issue. please ask in slack channel

**Comment by blueandgold** [comment]
Actually OP's question is very valid, and the answer has value, so it deserves to be posted here so that other folks (like me) with the same question can see it.
Otherwise, please let me know how I can see the answer in slack.

**Comment by feihujiang** [comment]
@blueandgold I asked this question on stackoverflow too, http://stackoverflow.com/questions/37936967/compare-spinnaker-with-jenkins-2-0-as-a-continuous-delivery-tool, but the authors of spinnaker didn't answer this question, just a user gave some helpful information. You can see it, and maybe it is helpful for you.

**Comment by tomaslin** [comment]
http://stackoverflow.com/questions/37936967/compare-spinnaker-with-jenkins-2-0-as-a-continuous-delivery-tool/38407442#38407442

**Comment by tomaslin** [comment]
to clarify, I closed this issue not because the question is not valid, but rather because there are no actionable tasks that can come out of this that is not just an opinion. Slack or stackoverflow is a better place to ask these type of questions

**Comment by blueandgold** [comment]
Thanks Tomas, I see.  The link to SO is exactly what I'm looking for, and is a very helpful.  Cheers!
