### ISSUE TITLE
Base OS CentOS

### ISSUE THREAD

**Issue by radkin** [spinnaker/spinnaker#804]
The "Hello Spinnaker" documentation indicates that you can install a Base OS of CentOS; however, that is not an option on the latest release 0.29.0, nor is it available in the version found on the master branch at present. Where can we get the version that is in the documentation?
http://spinnaker.io/images/hello-spinnaker/bake.png

The documentation is here: http://spinnaker.io/documentation/hello-spinnaker.html#setup-spinnaker-pipeline

Thanks,
Noel

**Comment by duftler** [comment]
I believe this is the issue that was addressed in #797.

If you're on GCE, this is the exact section you'll need to add the new mapping to: https://github.com/spinnaker/rosco/blob/master/rosco-web/config/rosco.yml#L136-L150

**Comment by radkin** [comment]
This looks good, thanks. Haven't tested it yet as my dev instance has an issue with credentials. I suppose we can close it.

**Comment by duftler** [comment]
I'm ok leaving it until the blocking issue is resolved and you've verified that the linked notes address your situation.

**Comment by radkin** [comment]
It worked. I made the change and it shows up in the UI, thanks.
