### ISSUE TITLE
The notification function is an extendable model, is it?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#806]
As we know, spinnaker supports hipchat/slack notification. Is spinnaker easy to extend the notification function to support other private group chats or other notification type, like [github's notification](https://github.com/notifications)?

**Comment by tomaslin** [comment]
yes, look at the commits in echo for an idea

**Comment by tomaslin** [comment]
for future reference, the slack channel is a better place to ask these type of questions. http://join.spinnaker.io/
