### ISSUE TITLE
centOS bake packer says ssh authentication fails

### ISSUE THREAD

**Issue by radkin** [spinnaker/spinnaker#820]
The message that shows in bake details is as follows:

```bash
   googlecompute: IP: [ip address here]
==> googlecompute: Waiting for SSH to become available...
==> googlecompute: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

How to duplicate:

* edit rosco.yml and add a google compute default image for centOS like this

```bash
     baseImages:
      - baseImage:
          id: precise
          shortDescription: v12.04
          detailedDescription: Ubuntu Precise Pangolin v12.04
          packageType: deb
        virtualizationSettings:
          sourceImage: ubuntu-1204-precise-v20150910
      - baseImage:
          id: trusty
          shortDescription: v14.04
          detailedDescription: Ubuntu Trusty Tahr v14.04
          packageType: deb
        virtualizationSettings:
          sourceImage: ubuntu-1404-trusty-v20150909a
      - baseImage:
          id: centos6
          shortDescription: centos-6
          detailedDescription: Centos 6
          packageType: rpm
        virtualizationSettings:
          sourceImage: centos-6-v20160301
```

then, create a "bake" and "deploy" pipeline. It appears as if there needs to be a gce.json template change so that the correct username is in there, or similar as there is for aws.json (E.G.)

*note* `ssh_username`
https://github.com/spinnaker/spinnaker/blob/master/experimental/packer/aws.json

This is not a problem for ubuntu. Tried both of the GCE centos public images

`gcloud compute images list`

```bash
centos-6-v20160301                     centos-cloud        centos-6                      READY
centos-7-v20160301                     centos-cloud        centos-7                      READY
```

**Comment by radkin** [comment]
@duftler 
This looks like something you might have seen.

**Comment by duftler** [comment]
I don't recall seeing this, but I was able to reproduce it.

Thanks for providing such a detailed report so I could easily recreate the issue.

**Comment by duftler** [comment]
Looks like you were right on the root cause. Found this on the packer Google Comute builder page:
```
Gotchas
Centos images have root ssh access disabled by default. Set ssh_username to any user, which will be created by packer with sudo access.
```

**Comment by radkin** [comment]
Thanks, I'll try setting the ssh_user and see if that sorts it out.

**Comment by duftler** [comment]
Got me a bit further, but still not working completely.

**Comment by radkin** [comment]
Per the above ticket, was able to bake GCP using those changes. It looks like it will solve the trouble we have here. Thanks :+1:
