### ISSUE TITLE
Baking problems in docker-compose installation:

### ISSUE THREAD

**Issue by empath** [spinnaker/spinnaker#823]
1) Packer isn't installed in the Rush container.
2) All of the packer commands reference files that exist in the rosco container, which aren't available to rush when it attempts to bake.  /opt/rosco/config/packer/aws-ebs.json and /opt/rosco/packer/install_packages.sh for example.  I worked around that by just copying the files over, but that can't be the right answer.
3) Updating spinnaker-local or rosco.yml in the spinnaker config directory doesn't change the images available via rosco.  You have to modify /opt/rosco/config/rosco.yml in the rosco container.
4) I don't think I understand where aws credentials for packer are supposed to be set.  Are we meant to be saving them in the aws packer template?

**Comment by empath** [comment]
Also the link to View Bakery Details points to bakery.test.netflix.net  I don't know where in the source that's coming from, or where in the config.

**Comment by gbougeard** [comment]
In the docker-compose file, rosco is not linked to gate, which might be the reason it is not reachable by gate. Adding the link might introduce a kind of circular dependency because it does not start anymore (orca does not find clouddriver anymore).

**Comment by gbougeard** [comment]
Close?
