### ISSUE TITLE
Rosco service should flow through Gate 

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#832]
The `View Bakery Details` link from Rosco-driven Bake stages should go through a Gate endpoint instead of directly to Rosco (port 8087). This removes the requirement to have port 8087 forwarded as well as Deck and Gate ports (9000 and 8084, respectively).

@spinnaker/google FYI

**Comment by duftler** [comment]
Seems like this would be pretty straightforward:
1) Add a /logs or /details endpoint to `BakeController` and `BakeService` in gate.
2) Configure `bakeryBaseUrl` and `bakeryDetailUrl` in `settings.js` in deck (just for OSS) to point to the new gate endpoint.
3) Leave `bakeryBaseUrl` and `bakeryDetailUrl` in `settings.js` as-is for Netflix-internal deck.

**Comment by ajordens** [comment]
Did this ever get tackled @duftler?

**Comment by duftler** [comment]
Not yet, but will do so shortly.
