### ISSUE TITLE
InstallSpinnaker.sh checks ubuntu version not as documented

### ISSUE THREAD

**Issue by kaizimmerm** [spinnaker/spinnaker#835]
*Environment*

Ubuntu 15.04

*Feature Area*

InstallSpinnaker.sh

*Description*

The script states "Version is $DISTRIB_RELEASE we require 14.04 **or higher**".

However, the check is "-ne 14" (not equal to 14). Should be "-lt 14" (less than 14) I guess.

*Steps to Reproduce*

Run ```bash <(curl --silent https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh)``` on Ubuntu >14

**Comment by kkapelon** [comment]
The truth is that Spinnaker does not work with "higher". It just needs 14.x and nothing else will make it work. So I will create a new PR to revert this change. See #1544 for more details.

In this case the code is correct and the documentation is wrong.
