### ISSUE TITLE
Spinnaker documentation difficult to read on mobile

### ISSUE THREAD

**Issue by netwolfuk** [spinnaker/spinnaker#838]
When trying to read the documentation on spinnaker.io the menu appears under the documentation.

I am viewing on android and have tried Chrome, Firefox and Ghostery browsers. 

![screenshot_2016-04-02-10-38-12](https://cloud.githubusercontent.com/assets/88687/14221014/6d3ec282-f8c0-11e5-9e9f-24d850ba3daa.png)

**Comment by gianrubio** [comment]
:+1

**Comment by gianrubio** [comment]
Same problem on iOS 9

**Comment by tomaslin** [comment]
applied a white background to the main content so the styling will cover the navigation. seems to work on iPhone, didn't try on anything else
