### ISSUE TITLE
java.io.InterruptedIOException: timeout -  Error in Orca while fetching build status

### ISSUE THREAD

**Issue by amitsehgal** [spinnaker/spinnaker#840]
Cloud Provider

AWS

*Environment*

```I am running Spinnaker on RHEL into AWS. ```

*Feature Area*

Pipelines and Jenkins

*Description*

When I trigger a pipeline which connects to Jenkins in Cloudbees for jenkins stages using proxy. It timeouts sporadically and error message in UI is timeout.

*Steps to Reproduce*

Create a pipeline with few back to back jenkin stages 

*What i have done so far ? *
I'm planning increase the timeout 
https://github.com/spinnaker/orca/blob/master/orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy#L54
In parallel also logging the issue if its a known issue ?

*Additional Details*

https://github.com/spinnaker/orca/blob/master/orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.groovy#L36

- This is the only pipeline running and Igor is not loaded at all.
- Looking at the orca logs here's an exception trace

[Exceptionlogs.txt](https://github.com/spinnaker/spinnaker/files/202667/Exceptionlogs.txt)

**Comment by amitsehgal** [comment]
I have a PR for timeout fix in orca for above.
https://github.com/spinnaker/orca/pull/784

**Comment by ajordens** [comment]
Believe the underlying issue has been addressed
