### ISSUE TITLE
https://dl.bintray.com/spinnaker/scripts/InstallSpinnaker.sh is out of date

### ISSUE THREAD

**Issue by ewiseblatt** [spinnaker/spinnaker#873]
It looks like the InstallSpinnaker.sh script is not updated as it is very old.
Not sure where or how this is supposed to get updated, but clearly it is not.
I would expect it to be tied to the process updating the bintray Spinnaker package.

**Comment by skorten** [comment]
Per our discussion on Slack I will be updating the build job that uploads InstallSpinnaker.sh to bintray.  The job will update the script on each new official release of spinnaker/spinnaker.

**Comment by rguthriemsft** [comment]
did the build job get updated?  I ask because I tried this weekend and was still getting old InstallSpinnaker.sh from bintray.

**Comment by ewiseblatt** [comment]
@skorten, is this fixed? It looks like bintray was updated but not sure if it was manual or travis automated.

**Comment by ewiseblatt** [comment]
@skorten, this still looks broken. The version on bintray does not have the changes from v0.52.0 that were released a ago. I'm not sure what version is actually there.

https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh

**Comment by rguthriemsft** [comment]
Is there any reason the latest installspinnaker.sh is not on bintray?  This is preventing us from publishing azure setup instructions as we can't validate our steps currently.

**Comment by msettro** [comment]
@ewiseblatt I'm trying to help @skorten with this issue. You mention you think fixing this issue might be tied to the process updating the bintray Spinnaker package. Where is that process? Somewhere in the gradle folder / build scripts ?

**Comment by ewiseblatt** [comment]
I dont know anything about the processes interacting with github or how
things get into bintray. If I did I would have tried to fix this myself.

**Comment by duftler** [comment]
The starting point is here:
https://github.com/spinnaker/spinnaker/blob/master/.travis.yml

**Comment by ajordens** [comment]
Did this ever get sorted out?

**Comment by ewiseblatt** [comment]
obsolete
