### ISSUE TITLE
AWS: Populate ASG Name tag automatically

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#881]
I'm working on transitioning our current infrastructure over to Spinnaker. Right now, we need the ASG Name tag to be populated with the full Frigga server group name, including the push version at instance launch time. Our userdata script uses this to dynamically locate configs for the service on startup.

@anotherchrisberry looked into this and mentioned that since ASG tags are assigned within Clouddriver and not Orca, doing any SpEL work is not currently possible. Ideally, I'd like to use SpEL to define `Name=${ frigga.name }` or similar from the UI during a Deploy stage.

**Comment by robzienert** [comment]
Also something just as simple as Spinnaker setting the `Name` tag to the `aws:autoscaling:groupName` value would be a thing.

**Comment by anotherchrisberry** [comment]
I just noticed the last bullet point in http://docs.aws.amazon.com/autoscaling/latest/userguide/autoscaling-tagging.html#tag_restrictions -
```
Note that when you launch an instance in an Auto Scaling group, Auto Scaling adds a tag to the instance with a key of aws:autoscaling:groupName and a value of the name of the Auto Scaling group.
```
Looking at some instances that Spinnaker is caching, I see that tag. Is that something your userdata script could take advantage of?

**Comment by robzienert** [comment]
Yeah, this is what we've decided to do. Fairly unobtrusive to both our codebase and Spinnaker.

**Comment by anotherchrisberry** [comment]
Awesome - okay if I close this issue?

**Comment by robzienert** [comment]
Yep thanks Berry.
