### ISSUE TITLE
Jenkins Stage Test Results getting cut off

### ISSUE THREAD

**Issue by tonyrzhang** [spinnaker/spinnaker#882]
_Title_

Jenkins Stage Test Results getting cut off

_Feature Area_

Pipeline Jenkins stages with test results being archived

_Description_

It seems like the execution details for a parallel pipeline build doesn't take into account the space that the test result will end up taking up when computing how tall to make the view area.

Here's a link to an image of the issue: https://www.dropbox.com/s/dlojbtgs3lhd9a3/Screenshot%202016-05-06%2013.04.23.png?dl=0

It's not a super big issue, just a cosmetic one in Deck. I looked at it briefly in chrome explorer, but it seems like you do some explicit calculations in the JS side that sets the dimensions of these labels and of the entire view area.

_Steps to Reproduce_
1. Have a pipeline with parallel jenkins stages that include Test Results.
2. Once the jenkins jobs have finished, note that the execution details area isn't adjusted to show the new label.

**Comment by anotherchrisberry** [comment]
I finally got a fix out for this issue over the weekend (https://github.com/spinnaker/deck/commit/6292220a189144a0354abff36b62fb2ef5022976). Thanks for calling it out!
