### ISSUE TITLE
Documentation about available expressions variables

### ISSUE THREAD

**Issue by gbougeard** [spinnaker/spinnaker#883]
*Title*

Documentation about available expressions variables

*Cloud Provider*

N/A

*Environment*

I'm running Spinnaker through docker-compose

*Feature Area*

 Pipelines, UI

*Description*

I'm trying to implement a simple pipeline with a Manual Judgement then a Check Preconditions.
I can't figure out how to retrieve the selected input in the Check Preconditions.

The tooltip on the judgement value (when editing the Manual Judgement) is not really handy : it's not possible to select and copy the example.
However I tried to set-up the Check Preconditions using what specified in the tooltip `execution.stages[n].context.judgmentInput=="GO"` it does not do what I think. I do not also know if I have to replace the `n` value in the `stages[n]` (and if I have, by which value?) or if the whole expression need to be enclosed in `${}` (not precised in the tooltip).

The list of all available expressions/variables in the documentation would be a first step.
The perfection would be a kind of syntax highlighting and validation (as it's done in the groovy console in Jenkins for example).

**Comment by gbougeard** [comment]
I finally found this file in the slack archive https://slack-files.com/files-pri-safe/T091CRSGH-F0R2B2KG8/templated_pipelines_in_spinnaker_-_google_docs.pdf and figured out to have a simple pipeline with a `Manual Judgment` followed by 2 forked `Check Preconditions` stages (depending on the selected value in the `Manual Judgment`) .
The expression I used : `execution.stages[1].context.judgmentInput=="value1"` where `value1` is a possible value from the `Manual Judgment` stage. 
The `execution.stages[1]` is relative to the first stage of the pipeline (if I well understood, the `Configuration` stage of a pipeline might be the `stages[0]`). If it was possible to use ids instead of index to refer to a specific stage it would be awesome :)

**Comment by mmlac-bv** [comment]
+1. Variables (in the UI as well as in the config) are a black magic that I couldn't even figure out by poking at the code. This needs tons of docs or easier ways to find them in the code.

**Comment by gburrell** [comment]
Referring to stages via array index is prone to breakage if the stage order changes.  I generally reference by name as in `${execution.stages.?[name == 'Groovy Script'][0]['name'] }`

**Comment by gbougeard** [comment]
http://www.spinnaker.io/docs/pipeline-expressions-guide by @tomaslin

**Comment by tomaslin** [comment]
@gburrell fyi there is now a helper method called #stage http://www.spinnaker.io/docs/pipeline-expressions-guide#stagestring
