### ISSUE TITLE
Jenkins property/artifact variables not being correctly passed to deploy stage.

### ISSUE THREAD

**Issue by TheDigitalNinja** [spinnaker/spinnaker#885]
**Cloud Provider:** AWS

**Environment:** I am running Spinnaker using the Amazon image ami-01718261 to deploy into AWS 

**Feature Area:** Pipelines, Jenkins, Rosco

**Description:** Expect to be able to use values in the json artifacts from jenkins to deploy a cluster. Instead get 'unable to resolve AMI imageId from ${amiName}'.

When the variable is added to the description of a manual judgment step it is readable. 

**Steps to Reproduce:**

- Create a new jenkins job called 'json-artifact-test' 
- Add in the following build script and add 'AMI-base.json, AMI-base.txt' to the post build action archive the artifacts. `echo "{ \"amiName\": \"ami-01718261\" }" > AMI-base.json && echo "amiName=ami-01718261" > AMI-base.txt`
- Create a new app and pipeline
- Create jenkins stage and set property file to AMI-base.json
- Add a deploy stage and configure a server group and save.
- Edit as json and add "amiName": "${amiName}", to the clusters object. 
- Update and save
- Manually run the pipeline. 

You should get an error 'unable to resolve AMI imageId from ${amiName}' on the deploy stage. 

If you add in a manual judgment step and set the description as ${amiName} you will see the correct ami id listed out. 

**Additional Details:** Tried with both json and key=value

**Comment by moondev** [comment]
We can mark this as closed. Worked with @TheDigitalNinja and can't recreate with newer versions of rosco and other components. Will work with @skorten on updating the ami.

**Comment by TheDigitalNinja** [comment]
Still seems to be an issue. These screenshots really highlight what ever the underling issue is though. It populates the drop-down choice but not the description. So we know the data is getting into spinnaker.

![artifact_setup](https://cloud.githubusercontent.com/assets/135572/15334421/57e550fc-1c2b-11e6-8e57-a31e3638ad88.png)

![manual_artifact](https://cloud.githubusercontent.com/assets/135572/15334424/5aebf7f6-1c2b-11e6-94e8-33363e79dd65.png)

**Comment by TheDigitalNinja** [comment]
Triggered jobs seem to work just fine. So this narrows it down to something specific with the jenkins stage.

**Comment by TheDigitalNinja** [comment]
context.VARIBLENAME works, closing ticket.
