### ISSUE TITLE
Introduce Openstack as a provider in clouddriver

### ISSUE THREAD

**Issue by ashleykasim** [spinnaker/spinnaker#890]
Introducing an Openstack provider in clouddriver

**Comment by cfieber** [comment]
in terms of a start at a list of things to do:

* cloud mutation operations (clouddriver)
  * implement some subset of the operations in [c.n.s.c.o.AtomicOperations.groovy](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/AtomicOperations.groovy)
* cloud read operations (clouddriver)
  * implement caching agents for
    * ServerGroup
    * Instance
    * SecurityGroup (if applicable)
    * LoadBalancer (if applicable)
* orchestration support
  * deploy stage likely needs some tweaks
* application/pipeline persistence
  * support openstack equivalent of S3 (if applicable)
* UI
  * detail views for Server Group/Instance/Security Group/Load Balancer
  * pipeline stage configuration views for operations
* Bakery
  * rosco updates to support openstack machine image format (if applicable)

**Comment by jakeegan10** [comment]
Bakery:  #895
Rosco updates to support openstack machine image format (if applicable)

Cloud read operations (cloud driver): #896
Implement caching agents for
              Instance

**Unable to add labels

**Comment by raffian** [comment]
@ashleykasim 
Thanks for posting this question, we're doing the same, just not with OpenStack :-) 

@cfieber 
> cloud read operations (clouddriver)  Instance, ServerGroup
I noticed you marked _SecurityGroup_ and _LoadBalancer_ as optional, so I'm assuming _Instance_ and _ServerGroup_ are essential for spinnaker to function properly?

> implement some subset of the operations in c.n.s.c.o.AtomicOperations.groovy
Can you elaborate on this? What does implementing an operation actually entail? Took a look at CREATE_SERVER_GROUP for [Azure](https://github.com/spinnaker/clouddriver/blob/42f8e57673caea4636fac0a3ff2222533b158371/clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/converters/CreateAzureServerGroupAtomicOperationConverter.groovy), but it wasn't clear what _else_, if anything, was required to complete the implementation.  

In the abscence of a clouddriver template with mock implementation -- that would be ideal -- which existing clouddriver would you say is the least complex, but complete and working, nonetheless? We can focus on that and use it as our guide moving forward (my guess is k8)
