### ISSUE TITLE
Orca should support restarting in-flight workflows after a node failure.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#893]
If an orca node goes down today, its in-flight workflows will not be automatically restarted. There is a chance a user could manually restart a pipeline depending on the state when the node failed.

Orca should be capable of automatically restarting workflows that were halted when the node executing them failed.

**Comment by duftler** [comment]
@robfletcher @ajordens

**Comment by lwander** [comment]
Largely addressed by the v3 execution engine
