### ISSUE TITLE
Rosco updates to support openstack machine image format

### ISSUE THREAD

**Issue by jakeegan10** [spinnaker/spinnaker#895]
In-Progress -drmaas

**Comment by drmaas** [comment]
https://github.com/spinnaker/rosco/pull/97 merged

Additional items to address:
1) packer openstack variables - required vs optional (currently have a best guess for what is required for v3)
2) openstack username/password/identity url management (currently will load via environment variable passed to java process)
3) v2 vs. v3 apis (currently implemented for v3)
