### ISSUE TITLE
Igor trigger ci job - specify parameters

### ISSUE THREAD

**Issue by gardleopard** [spinnaker/spinnaker#901]
Currently we can pass in a property file from a ci job to the trigger, but there is no field for custom properties. Imagine you have a pipeline that deploys to dev and you want to inject the target url for your integration tests. As I understand it you will need a dev.json, pre.json and a prod.json to have separate configs for each target. Simply passing `TARGET_URL=http://dev.myservice.myorg` would make this very easy to control.

Example jenkins trigger config:
<img width="1125" alt="screen shot 2016-05-23 at 13 30 30" src="https://cloud.githubusercontent.com/assets/842541/15469547/398d08ec-20eb-11e6-851a-318af0636d27.png">

A concept of parameters in the config would make it easy to trigger ci jobs with custom parameters for targeting tests, reusing parameters from previous steps in the pipeline and so on. Jenkins supports [it](https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API) and also [travis](https://docs.travis-ci.com/user/triggering-builds).

There is something similar to this in the bakery configuration:
<img width="985" alt="screen shot 2016-05-23 at 13 39 34" src="https://cloud.githubusercontent.com/assets/842541/15469637/d5b71208-20eb-11e6-93db-b9d57e8353fa.png">

**Comment by tomaslin** [comment]
closing. remember this used to be just a misunderstanding in the UI

**Comment by dforrest88** [comment]
@tomaslin could you shed some light on the alternative to this feature request? I'm looking to do something similar.

**Comment by ignasr** [comment]
+1 for the alternative.
