### ISSUE TITLE
Remove /home/spinnaker/.spinnaker from docs

### ISSUE THREAD

**Issue by ewiseblatt** [spinnaker/spinnaker#903]
Somewhere in the docs it might say to put spinnaker local in /home/spinnaker/.spinnaker. That directory was deprecated. Fix the docs. Also, dont look there in reconfigure_spinnaker.

**Comment by ajordens** [comment]
This still an issue @ewiseblatt

**Comment by ewiseblatt** [comment]
@ajordens are you asking or are you aware of an example. I just checked
spinnaker.io and didnt notice it.

**Comment by ajordens** [comment]
Sorry ... was asking. 

Just doing a pass through all open issues and closing those that don't seem relevant anymore.
