### ISSUE TITLE
Support log rotation

### ISSUE THREAD

**Issue by ervansetiawan** [spinnaker/spinnaker#904]
*Cloud Provider*
All

*Environment*
All

*Feature Area*
Logging

*Description*
After running Spinnaker for a long time, eventually the disk is filled up with huge log files.

Example : 

ubuntu@ip-10-0-0-228:/etc/init$ ls -alt /var/log/spinnaker/clouddriver/clouddriver.log
-rw-r--r-- 1 spinnaker spinnaker 705542752 May 23 20:08 /var/log/spinnaker/clouddriver/clouddriver.log

It appears that currently the startup script simply redirects stderr and stdout to a file. 

exec /opt/clouddriver/bin/clouddriver 2>&1 > /var/log/spinnaker/clouddriver/clouddriver.log &

There needs to be a way to do log rotation and cleanups.

**Comment by robertsigler** [comment]
I tried out ami-21a26d41 and it seems to me that this issue is resolved. Sorry for not properly linking up my last pull request so that the issue would be closed when it was merged.
