### ISSUE TITLE
Deck - The port of instances is hard coded to 7001

### ISSUE THREAD

**Issue by gbougeard** [spinnaker/spinnaker#913]
*In instance details, the link to ips use hard coded port*

https://github.com/spinnaker/deck/blob/0ca99df81f69924096835bf33faf904e3358bd22/app/scripts/modules/azure/instance/details/instanceDetails.html#L126
https://github.com/spinnaker/deck/blob/0ca99df81f69924096835bf33faf904e3358bd22/app/scripts/modules/amazon/instance/details/instanceDetails.html#L119

*AWS, Azure*

I don't know what is the best solution to fix it : try to find a correct port from the security groups or the health check, or do not specify the port at alll (looks like the solution chosen by google here https://github.com/spinnaker/deck/blob/0ca99df81f69924096835bf33faf904e3358bd22/app/scripts/modules/google/instance/details/instanceDetails.html#L134 )

**Comment by milismsft** [comment]
Displaying Azure instance details is still "work-in-progress" and should come in the next couple weeks except for the proper health status reporting which might be at least two months out (platform team is currently working to implement the proper API support for health related status reporting via the Application Gateway).

If you're looking to log in into a particular instance via SSH (or RDP it's a Windows VM), we currently default to port 50000 through port 50099 through the Public IP assigned to the scale set's internal load balancer (not the Application Gateway), which you would be able to get via the Azure Portal web site at this time.

**Comment by gbougeard** [comment]
I personnaly use AWS ;)
I quoted Azure because I found the same pattern in the code linked above.

**Comment by anotherchrisberry** [comment]
@gbougeard I'm also unsure about the right way to handle this. At Netflix, 7001 is the default port for our applications, which is why it's hard-coded. If that instance port were configurable, would that work for you, or do your applications' default ports vary?

**Comment by gbougeard** [comment]
At which level would it ,be configurable? per application or (more global) per account?
In my case the default ports vary, so if it's configurable per app it's awesome :)

**Comment by anotherchrisberry** [comment]
We'll make it configurable at the application level, with a default configurable system-wide (see https://github.com/spinnaker/deck/pull/2313)

**Comment by anotherchrisberry** [comment]
Completed via https://github.com/spinnaker/deck/pull/2358
