### ISSUE TITLE
Support docker pipeline triggers without organization

### ISSUE THREAD

**Issue by leelasharma** [spinnaker/spinnaker#941]
A [recent change](https://github.com/spinnaker/deck/pull/2306) in the docker pipeline trigger configuration requires organization field.
While most repositories follow a \<organization\>/\<repo-name\> naming scheme it isn't true in all cases.
Is there a way to support images with \<repo-name\>:\<tag\> alone? (Eg: docker hub redis image)

Env: I am running Spinnaker on kubernetes to manage kubernetes applications

**Comment by tomaslin** [comment]
I believe this is a misunderstanding of the UI. Things with repo-name:tag alone should be categorized under the empty organization ( first one in the list ) 

<img width="474" alt="screen shot 2016-06-16 at 8 19 09 am" src="https://cloud.githubusercontent.com/assets/74310/16122376/ad7f8172-339b-11e6-93bf-5c6b62bf537d.png">

the organization is there really for easier navigation across large repositories, but the underlying reference to the repository, either with a org or not should be the same

**Comment by leelasharma** [comment]
This works now, thanks Tomas!
