### ISSUE TITLE
Igor unable to parse Jenkins 2.x ProjectsList

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#943]
When adding a Jenkins 2.x master (currently using 2.9) to Igor, it throws a the following stacktrace: https://gist.github.com/robzienert/5e05196c38bd0a31611c93268b1d3ab2

Reproduction only requires setting up a Jenkins 2 master and having Igor poll for jobs.

**Comment by tomaslin** [comment]
this should not be an issue, are you on the latest version of igor?

**Comment by robzienert** [comment]
Ah, v1.26.0 - I'll update.

**Comment by robzienert** [comment]
Confirmed working on 1.45.0-SNAPSHOT. Thanks.
