### ISSUE TITLE
Creating a previously deleted application contains remnant pipelines

### ISSUE THREAD

**Issue by mroderus** [spinnaker/spinnaker#945]
*Cloud Provider*
AWS

*Environment*
I am running Spinnaker using the Amazon images to deploy into AWS eu-central-1.

*Feature Area*
Pipelines

*Description*
Creating a new application.
Expected behavior: `Pipelines`-section is empty.
Actual behavior: `Pipelines`-section contains entries from a previously existing application that had the same name.

*Steps to Reproduce*

1. create an application, name it `test123`
2. in this application, create a pipeline, name it `deploy to abc`
3. delete application `test123`
4. create an application, name it `test123`

*Installed Versions*
ii  spinnaker                        0.45.0-3                         all          spinnaker
ii  spinnaker-clouddriver            1.211.0                          all          spinnaker-clouddriver
ii  spinnaker-deck                   2.661.0-3                        all          spinnaker-deck
ii  spinnaker-echo                   1.103.0-3                        all          spinnaker-echo
ii  spinnaker-front50                1.26.0-3                         all          spinnaker-front50
ii  spinnaker-gate                   2.60.0-3                         all          spinnaker-gate
ii  spinnaker-igor                   1.46.0-3                         all          spinnaker-igor
ii  spinnaker-orca                   1.148.0-3                        all          spinnaker-orca
ii  spinnaker-rosco                  0.46.0-3                         all          spinnaker-rosco
ii  spinnaker-rush                   1.25.0-3                         all          spinnaker-rush

**Comment by anotherchrisberry** [comment]
This was fixed a week ago via https://github.com/spinnaker/front50/pull/117
