### ISSUE TITLE
Automatic availability zone balancing in eu-central-1 does not work 

### ISSUE THREAD

**Issue by mroderus** [spinnaker/spinnaker#952]
*Cloud Provider*
AWS

*Environment*
I am running Spinnaker using the Amazon images to deploy into AWS eu-central-1

*Feature Area*
Clusters

*Description*
When creating a new server group (either as part of a deploy-stage in a pipeline or in the Clusters-section), I set _Automatic Availability Zone Balancing_ to _Enabled_ and check _Keep instances evenly distributed across zones_. In this config dialog I can see both available zones, _eu-central-1a_ and _eu-central-1b_. However, when I execute the pipeline, all instances are created only in eu-central-1a. 

*Versions*
ii  spinnaker                        0.45.0-3                         all          spinnaker
ii  spinnaker-clouddriver            1.211.0                          all          spinnaker-clouddriver
ii  spinnaker-deck                   2.661.0-3                        all          spinnaker-deck
ii  spinnaker-echo                   1.103.0-3                        all          spinnaker-echo
ii  spinnaker-front50                1.26.0-3                         all          spinnaker-front50
ii  spinnaker-gate                   2.60.0-3                         all          spinnaker-gate
ii  spinnaker-igor                   1.46.0-3                         all          spinnaker-igor
ii  spinnaker-orca                   1.148.0-3                        all          spinnaker-orca
ii  spinnaker-rosco                  0.46.0-3                         all          spinnaker-rosco
ii  spinnaker-rush                   1.25.0-3                         all          spinnaker-rush

**Comment by anotherchrisberry** [comment]
There are a few ways this can happen. A couple things worth looking at:
 1. Scaling Activities - in the server group details panel, there's a "View Scaling Activities" link in the "Size" section. Take a look at the messages there. It's possible AWS didn't have enough instances available in eu-central-1b, so launched both in eu-central-1a.
 2. If you were launching in a VPC, verify you have subnets in each AZ with the same name.

**Comment by mroderus** [comment]
(2.) was the solution. Sorry for having missed that, my mistake.
