### ISSUE TITLE
Inventory of operations

### ISSUE THREAD

**Issue by jakeegan10** [spinnaker/spinnaker#985]
Went through and worked on the heavy hitters -- review the swagger doc to make sure we have implemented everything or confirm that it was skipped for a reason

**Comment by varikin** [comment]
I reviewed the swagger spec and the atomic operations. I don't see any gaps that pertain to openstack. AWS and GCE include a couple operations around updating the size and scaling policy of an ASG, but Openstack doesn't have that ability currently.
