### ISSUE TITLE
Why spinnaker doesn't use Cassandra?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#995]
I found Spinnaker uses redis/s3 to replace Cassandra.  Why spinnaker doesn't use Cassandra? Which version of spinnaker Cassandra was deprecated in? And which version Cassandra  will be removed totally?

**Comment by JohnTheodore** [comment]
@feihujiang spinnaker didn't 'replace' cassandra, to my knowledge. In addition to being able to write to cassandra/redis, now it can write to s3/redis. I don't know of any plans for deprecation.

In general the slack channel is a better place to ask questions like this. https://spinnakerteam.slack.com/messages/general/ or on stackoverflow. This isn't exactly an issue.

**Comment by feihujiang** [comment]
Thanks, I got it. And I'll ask questions on stackoverflow.

**Comment by feihujiang** [comment]
I ask a similar question on stackoverflow,  the url is http://stackoverflow.com/questions/38473868/is-cassandra-just-an-option-in-spinnaker
