### ISSUE TITLE
Please approve slack invitation requests

### ISSUE THREAD

**Issue by raffian** [spinnaker/spinnaker#998]
Hello,

Can someone please approve pending invitation requests on slack? We've got detailed questions not suitable for stackoverflow, and out of respect we're not using git for general questions, but without acess to spinnaker on slack, we're stuck with no place to ask questions.

**Comment by anotherchrisberry** [comment]
I just went through the signup flow via join.spinnaker.io. It sent me an email, and I was able to create an account and immediately join the channel with no intervention or delay.

You should have gotten an email with the subject "Tomas Lin invited you to Spinnaker on Slack" - did you receive that?

**Comment by raffian** [comment]
Just sent another request from _rbasmaji...@ofig..com_ , got message on screen saying invite was previously sent; so that's good, thank you. I suspect spam filters are the culprit on my end.

Is there any limitation to the email I can use for the reqeust? Can I use a gmail account not linked with any slack account?

**Comment by anotherchrisberry** [comment]
@raffian there should not be any limits AFAIK regarding what email address you use.

Going to close this issue, since it sounds like this was a spam filter situation.
